### ISSUE TITLE
Wrong link to required browsers

### ISSUE THREAD

**Issue by Hb-** [novnc/noVNC#1001]
On http://novnc.com/info.html in section "Install" is a link with the faulty target URL https://github.com/novnc/noVNC/wiki/Browser-support Perhaps this URL https://github.com/novnc/noVNC#browser-requirements is meant.

**Comment by samhed** [comment]
Thank you, fixed in [this commit].(https://github.com/novnc/novnc.github.io/commit/f05ec045b1e7b8093e337398e5af633f0d34cbdd)
