### ISSUE TITLE
Unable to retry connection after entering wrong password

### ISSUE THREAD

**Issue by yefimg** [novnc/noVNC#1003]
Hello,

After entering wrong VNC password and getting "New connection has been rejected with reason: Authentication failure" it's impossible to retry — "Connect" button doesn't react until page is refreshed.

Is this behaviour expected?

Thanks!

**Comment by samhed** [comment]
Good find!

No, this is not expected.

**Comment by CendioOssman** [comment]
This is fallout from a4822c3a8604a9807a4dcff771aaace81757e24b and 75e1161434064a406cd23f2e3b14c71e065c243a. We aren't clearing `UI.rfb` in the right place. I'll have a look.

**Comment by CendioOssman** [comment]
Fixed in d1aeb435515579c73beaf3641aec0ff5ec322e70.
