### ISSUE TITLE
Keyboard input stops working after pressing ALT (Gr) with Firefox Quantum

### ISSUE THREAD

**Issue by sonicnkt** [novnc/noVNC#1004]
Hi,
i noticed that keyboard input (letters and numbers only, backspace and enter still work) after i press the Right Alt key. i have an @ symbol in my password and with a german keyboard layout you have to press ALT-GR + Q to creat this symbol.
VNC Password works fine btw, im talking about entering this symbol after a connection is established (windows password in my case)

But like i said after i the symbol is added cant input anything else until i reload the complete page and connect again.

Cant test it with another browser atm because chromium refuses to load my novnc page at all with my current test setup. Maybe this is a firefox related problem but i thought i ask if someone else experiences this. And I just cloned the latest repository to make sure i have the latest version.

Nils

**Comment by CendioOssman** [comment]
Which version or commit of noVNC are you testing with?

And what does the server setup look like?

**Comment by sonicnkt** [comment]
Just updated my setup 2-3 Hours ago, so it should be 3729976.

This a basic testing setup with node.js running websockify and no custom settings beside a self signed certificate, everything running on windows 10 LTSB.  VNC server is UltraVNC, input with other viewers works fine and noVNC works great as well besides the described problem with the input.

**Comment by CendioOssman** [comment]
I don't have a UltraVNC server to test with here, but I don't see any issues with a TigerVNC server and Firefox.

Can you enable debug in the noVNC settings and see what you get in the browser console when you press AltGr+Q and any presses after that?

**Comment by sonicnkt** [comment]
I had some very poor performance results with tigervnc compared to ultravnc and it has less config options. I can try it with another server as well, but i think its not related to it.

I did what you ask and i noticed something, it seems to be that after i press the right-alt key that the ctrl key seems to be locked, even tho i never touched that one. I just noticed it because while typing my debug test in notepad.exe the "Bearbeiten" menu item open after the text input stopped working (press B), that would be the normal behavior for CTRL+B.

Here is the Debug log:
`
>> Keyboard.allKeysUp
keyboard.js:297:8
<< Keyboard.allKeysUp
keyboard.js:302:8
>> Keyboard.allKeysUp
keyboard.js:297:8
<< Keyboard.allKeysUp
keyboard.js:302:8
>> set_cursor
rfb.js:2506:8
<< set_cursor
rfb.js:2525:8
onmousebutton down, x: 354, y: 319, bmask: 1
mouse.js:101:8
onmousebutton up, x: 354, y: 319, bmask: 1
mouse.js:101:8
onkeyevent down, keysym: 110 , code: KeyN
keyboard.js:63:8
Sending keysym (down): 110
rfb.js:377:12
onkeyevent up, keysym: 110 , code: KeyN
keyboard.js:63:8
Sending keysym (up): 110
rfb.js:377:12
onkeyevent down, keysym: 111 , code: KeyO
keyboard.js:63:8
Sending keysym (down): 111
rfb.js:377:12
onkeyevent up, keysym: 111 , code: KeyO
keyboard.js:63:8
Sending keysym (up): 111
rfb.js:377:12
onkeyevent down, keysym: 118 , code: KeyV
keyboard.js:63:8
Sending keysym (down): 118
rfb.js:377:12
onkeyevent up, keysym: 118 , code: KeyV
keyboard.js:63:8
Sending keysym (up): 118
rfb.js:377:12
onkeyevent down, keysym: 110 , code: KeyN
keyboard.js:63:8
Sending keysym (down): 110
rfb.js:377:12
onkeyevent up, keysym: 110 , code: KeyN
keyboard.js:63:8
Sending keysym (up): 110
rfb.js:377:12
onkeyevent down, keysym: 99 , code: KeyC
keyboard.js:63:8
Sending keysym (down): 99
rfb.js:377:12
onkeyevent up, keysym: 99 , code: KeyC
keyboard.js:63:8
Sending keysym (up): 99
rfb.js:377:12
onkeyevent down, keysym: 65507 , code: ControlLeft
keyboard.js:63:8
Sending keysym (down): 65507
rfb.js:377:12
onkeyevent down, keysym: 65514 , code: AltRight
keyboard.js:63:8
Sending keysym (down): 65514
rfb.js:377:12
onkeyevent down, keysym: 64 , code: KeyQ
keyboard.js:63:8
Sending keysym (up): 65514
rfb.js:377:12
Sending keysym (up): 65507
rfb.js:377:12
Sending keysym (down): 64
rfb.js:377:12
Sending keysym (down): 65507
rfb.js:377:12
Sending keysym (down): 65514
rfb.js:377:12
onkeyevent up, keysym: 64 , code: KeyQ
keyboard.js:63:8
Sending keysym (up): 64
rfb.js:377:12
onkeyevent up, keysym: 65507 , code: ControlLeft
keyboard.js:63:8
Sending keysym (up): 65507
rfb.js:377:12
onkeyevent down, keysym: 103 , code: KeyG
keyboard.js:63:8
Sending keysym (down): 103
rfb.js:377:12
onkeyevent up, keysym: 103 , code: KeyG
keyboard.js:63:8
Sending keysym (up): 103
rfb.js:377:12
onkeyevent down, keysym: 105 , code: KeyI
keyboard.js:63:8
Sending keysym (down): 105
rfb.js:377:12
onkeyevent up, keysym: 105 , code: KeyI
keyboard.js:63:8
Sending keysym (up): 105
rfb.js:377:12
onkeyevent down, keysym: 116 , code: KeyT
keyboard.js:63:8
Sending keysym (down): 116
rfb.js:377:12
onkeyevent up, keysym: 116 , code: KeyT
keyboard.js:63:8
Sending keysym (up): 116
rfb.js:377:12
onkeyevent down, keysym: 104 , code: KeyH
keyboard.js:63:8
Sending keysym (down): 104
rfb.js:377:12
onkeyevent up, keysym: 104 , code: KeyH
keyboard.js:63:8
Sending keysym (up): 104
rfb.js:377:12
onkeyevent down, keysym: 117 , code: KeyU
keyboard.js:63:8
Sending keysym (down): 117
rfb.js:377:12
onkeyevent up, keysym: 117 , code: KeyU
keyboard.js:63:8
Sending keysym (up): 117
rfb.js:377:12
onkeyevent down, keysym: 98 , code: KeyB
keyboard.js:63:8
Sending keysym (down): 98
rfb.js:377:12
onkeyevent up, keysym: 98 , code: KeyB
keyboard.js:63:8
Sending keysym (up): 98
rfb.js:377:12
onmousebutton down, x: 391, y: 321, bmask: 1
mouse.js:101:8
onmousebutton up, x: 391, y: 321, bmask: 1
mouse.js:101:8
onkeyevent down, keysym: 98 , code: KeyB
keyboard.js:63:8
Sending keysym (down): 98
rfb.js:377:12
onkeyevent up, keysym: 98 , code: KeyB
keyboard.js:63:8
Sending keysym (up): 98
rfb.js:377:12
onmousebutton down, x: 395, y: 326, bmask: 1
mouse.js:101:8
onmousebutton up, x: 395, y: 326, bmask: 1
mouse.js:101:8
onmousebutton down, x: 241, y: 227, bmask: 1
mouse.js:101:8
onmousebutton up, x: 175, y: 226, bmask: 1
mouse.js:101:8
>> set_cursor
rfb.js:2506:8
<< set_cursor
rfb.js:2525:8
>> set_cursor
rfb.js:2506:8
<< set_cursor
rfb.js:2525:8
>> set_cursor
rfb.js:2506:8
<< set_cursor
rfb.js:2525:8
>> set_cursor
rfb.js:2506:8
<< set_cursor
rfb.js:2525:8
>> Keyboard.allKeysUp
keyboard.js:297:8
<< Keyboard.allKeysUp
keyboard.js:302:8
>> Keyboard.allKeysUp
keyboard.js:297:8
onkeyevent up, keysym: 65514 , code: AltRight
keyboard.js:63:8
Sending keysym (up): 65514
rfb.js:377:12
<< Keyboard.allKeysUp
keyboard.js:302:8
`

Like i said i just typed something in notepad.exe:

novnc@github, but as i said, github was not written anymore, tho the last key b opened the menu.

**Comment by CendioOssman** [comment]
> And of course i noticed this in the log: onkeyevent up, keysym: 65507 , code: ControlLeft
> But Ctrl was never touched :)

That's a Windows misfeature unfortunately that we haven't found a nice workaround for. It sends AltGr as Ctrl+Alt.

But it looks like it is Alt that is getting stuck, not Ctrl. Your log shows a proper release of Ctrl, but the Alt release is waaaay later.

What version of Firefox are you using? And what client OS? Any virtualisation or remote access?

**Comment by sonicnkt** [comment]
VNC Server OS: Win10 LTSB x64
Client OS: Win8.1 x64 
Client Browser: Firefox 58.0.1 (x64)

No other remote Access or virtualisation. But i will try another client OS on monday just to rule this out.

**Comment by CendioOssman** [comment]
I upgraded Firefox and now I'm seeing this as well. And I'm afraid it's a bug in Firefox that we can't easily work around. :/

I've filed the bug here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1435717

We'll have to wait and see what they say.

**Comment by wintamute** [comment]
I'm also having issues with German keyboard layout, using novnc (commit 24231f) on Openstack, using both Firefox and Chrome. All keys using AltGr combinations show just the normal key.

Client OS: Win10 x64
Client Browser: Firefox 59/Chrome 66 x64
VM OS: Windows Server 2016 x64

When using Chrome on a Linux Client OS, everything is fine.

I also used this tool to check what the browsers actually do: [https://w3c.github.io/uievents/tools/key-event-viewer.html](https://w3c.github.io/uievents/tools/key-event-viewer.html)
I attached screenshots of the output, test was holding down AltGr for about a second, then pressing 7,8,9,0, then releasing AltGr.
From the output it seems Chrome and Firefox behave quite different.

If I can help in any way please let me know.

![keys_firefox](https://user-images.githubusercontent.com/11716734/39117468-31638140-46e7-11e8-9389-241cb666587b.PNG)
![keys_chrome](https://user-images.githubusercontent.com/11716734/39117471-3452dbe4-46e7-11e8-9971-85e3776b343d.PNG)

**Comment by CendioOssman** [comment]
Chrome looks fine, so whatever issue you are having there it is not the same thing. Please file a new issue in that case with details of what goes wrong.

As for Firefox, we have a (crappy) workaround in place in the development version. But to get it fixed properly we need to get Firefox to fix this bug. So please chime in on the linked bug to let them know that this affects users.

**Comment by wintamute** [comment]
Sorry, created new issue for Chrome here #1062 
I'll also comment on the Firefox issue, thanks.

**Comment by CendioOssman** [comment]
Firefox claims to have fixed this now. @sonicnkt, feel like testing a nightly Firefox build?

**Comment by samhed** [comment]
No response, assuming this is fixed.
