### ISSUE TITLE
Web Elements are not visible, Object Picker selecting entire canvas

### ISSUE THREAD

**Issue by SugumarMoorthy** [novnc/noVNC#1006]
Hi , We are trying to automate the noVNC web page, while selecting the object using object picker its selecting entire canvas not each elements, Could you please help in this?.

**Comment by samhed** [comment]
You are going to have to be more specific? What object picker are you talking about? Which elements are you trying to select? What browser are you using?

**Comment by SugumarMoorthy** [comment]
We are starting web Sockets service for NOvnc in  Linux and trying to access the VNC in windows Chrome and Firefox browser, We are able connect desktop through VNC  but while inspect web page elements(developer tools in web page) like Xpath, ID, Name etc, Its selecting whole screen as  canvas and not able identify each elements seperately

**Comment by DirectXMan12** [comment]
I'm not sure we can help you with this one.  Sounds like you need to refine your Xpath expressions.  We're not using any shadow DOM or anything, so you should just be able to select the elements you want.

**Comment by SugumarMoorthy** [comment]
![elementscanvas](https://user-images.githubusercontent.com/35955508/35605954-59464d10-0672-11e8-96f7-983af6aec3ab.PNG)
