### ISSUE TITLE
Double Mouse Pointer in Firefox

### ISSUE THREAD

**Issue by kkomara** [novnc/noVNC#1014]
Pretty sure this is a Firefox issue.  This is what I posted on the Firefox support forum:

"I use Firefox to access my Proxmox Hypervisor HTML5 System interface.  The Web interface to Proxmox has much information about my guest OS containers, and allows user to open a Console HMI session to the Guest OS using NoVNC.  In this case I have many Ubuntu 16.04 guest OS's defined in Proxmox.  All works well except the NoVNC console session.  When I open the NoVNC console session - it works - BUT there are 2 mouse pointers - a Local Pointer, and a remote pointer.  If anyone has every used VNC Client - Server this is quite common.  And depending on the VNC Client - you can usually disable either the local or remote cursor so you only see one - which I prefer.  In the case of NoVNC - it is all HTML5 based - no VNC client to download.  Very nice.  Only issue is with Firefox there are 2 cursors - local and remote.  In ALL other browsers that I have tested (Edge, IE, Chrome, etc.) they ALL only show 1 cursors (remote) when the user has the mouse inside the NoVNC area.  From what I have been told by the Proxmox support forums - there is an HTML5 command being sent by the NoVNC server that should be telling the browser to not show the local cursor when the mouse is within the NoVNC area.  Edge, IE, Chrome, etc. all respect that and work properly.  In the case of Firefox - the local cursor is NOT turning off.  Is this a know issue/limitation in Firefox.  Is there a an about:config parameter that I can tweak ??  This problem exists in latest stable release of Firefox in Windows and Ubuntu.  And I can repeat issue with daily builds for both Windows and Ubuntu."

Do you agree this is a Firefox issue ???  Do you know of this issue. ???  Is there a parameter in Firefox you know of to fix this issue ??  Do you have any additional information I can post in Firefox forum to fix this issues.

I can upload screen prints of how it works in Edge/IE/Chrome, and the double (Local and remote) pointers in Firefox

thanks !!

**Comment by CendioOssman** [comment]
Generally we can't really support custom versions of noVNC (like in Proxmox) as we don't know what version of noVNC they are based on or what modifications they've done. That said we might be able to do some light debugging that you can then bring to the proxmox developers.

So first, we've not heard of this issue before. Blank cursors work fine with noVNC and Firefox in other scenarios. And no, there is no command being sent by the server specifically to hide the cursor. It is usually handled by sending an empty cursor using the same mechanism as other cursors.

So we should check what cursor the browser has set at the moment. Please open the inspector in Firefox and Chrome and check what attributes are set on the `<canvas>` element.

**Comment by kkomara** [comment]
When I open the proxmox main screen and inspect element  in both Edge (works with single cursor on left) and Firefox (has double cursor on right) there is no canvas section.  In fact I believe there is a section completely missing in the Firefox display element ???  
![capture](https://user-images.githubusercontent.com/20228592/36097461-133bb03e-0fc9-11e8-9dae-443a93ceccbb.PNG)

**Comment by CendioOssman** [comment]
You need to click the little arrow wedge there to expand things and see the sub elements.

Also, please use Chrome not Edge. Edge does not support local cursors so it's not really interesting to compare with that.

**Comment by kkomara** [comment]
thanks.. obviously I am not an expert in reading HTML !!!
In Firefox when I expand - the cursor type is set to default !!


![firefox](https://user-images.githubusercontent.com/20228592/36098424-e35eaad4-0fcc-11e8-811b-17d756862b3e.PNG)

I am loading up Chrome on my PC and will try it and post results.

**Comment by kkomara** [comment]
I loaded up Chrome - and there is a double cursor with it too !!

And - Cursor is set to default there too !!

![chrome](https://user-images.githubusercontent.com/20228592/36098580-75045876-0fcd-11e8-82f4-fe88f3e12e76.PNG)

So where do I go from here ??  I do not use Chrome on ANY of my computers - just Edge on my Windows Tablet (works fine) and Safari on my iPhone (works fine now that I got the Certificate for Proxmox loaded into my iPhone) and Firefox on my Linux PCs.  Is this an issue with Firefox that I should alter them to - or is there a setting in about:config that I can change to have Firefox support cursor:none in the canvas ?  Thanks a bunch for your help !!!

**Comment by CendioOssman** [comment]
This is not an issue with Firefox, and I don't think Firefox has any settings to override this. What is needed is for proxmox to update their version of noVNC. They need at least commit cd74793b443cb31e33ca71c63e3cdcce9f10df43.

I'm afraid I'll be closing this issue now as it is a proxmox problem, not a noVNC one. But feel free to point the proxmox developers here.

**Comment by kkomara** [comment]
Understood.
Not what I was hoping .... but it is what it is....
I will follow up with Proxmox.
Thanks for the help !!!
