### ISSUE TITLE
Choosing encoding and compression level

### ISSUE THREAD

**Issue by yefimg** [novnc/noVNC#1015]
Hello,

Cannot find docs on how to choose encoding and compression level. It looks, like default method is JPEG with highest compression level, which is not always required.

Could you please advise?

Thank you!

**Comment by samhed** [comment]
you can't choose, you will have to modify your code

**Comment by yefimg** [comment]
Can you please give any insights on the scale? Like what do the values in encodings.js mean?

**Comment by samhed** [comment]
I'm no expert, you should have a look at the specification:

https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#encodings

**Comment by CendioOssman** [comment]
> Like what do the values in encodings.js mean?

I assume you are referring to the JPEG level. `pseudoEncodingQualityLevel0` is the most heavily compressed, and `pseudoEncodingQualityLevel9` is the least compressed. Exactly what that means is not standardised and up to the server. But you can play around with any value between those extremes. E.g. "quality level 5" would be `-27`. There are no constants for these intermediate values.
