### ISSUE TITLE
Unexpected token: name (size)

### ISSUE THREAD

**Issue by wachri** [novnc/noVNC#1017]
I'm using the `RFB` class in a TypeScript project with webpack and Uglify. During the build, with `1.0.0-beta`,  and uglify I'm getting following error:

```
ERROR in 3.1866f27dbb218fc59c58.chunk.js from UglifyJs
Unexpected token: name (size) [./node_modules/source-map-loader!./node_modules/angular-router-loader/src!./node_modules/@novnc/novnc/core/rfb.js:517,0][3.1866f27dbb218fc59c58.chunk.js:7463,16]

ERROR in 10.91f18665b1cff638bcb4.chunk.js from UglifyJs
Unexpected token: name (size) [./node_modules/source-map-loader!./node_modules/angular-router-loader/src!./node_modules/@novnc/novnc/core/rfb.js:517,0][10.91f18665b1cff638bcb4.chunk.js:7463,16]
```

This happens because typescript doesn't compile javascript files to ES5 and uglify doesn't supporting ES6 features like `const` or `let`.

I worked around by adding the `babel-loader` to my build process and an update of the webpack config to following:

```
{
    test: /\.js$/,
    include: root('node_modules/@novnc/novnc'),
    use: {
        loader: 'babel-loader',
        options: {
            presets: ['@babel/preset-env'],
        },
    },
}
```
Currently this is only needed in combination with this lib (and we are using quite a few). Unfortunately I have no idea how this could be better fixed, but an "offical" solution would be great.

**Comment by CendioOssman** [comment]
`const` and `let` are minimum requirements from our point of view, so we probably won't have any official guides for converting away from those. But yes, using babel is what we'd recommend to support older JavaScript parsers.

Uglify seems to have some work done for support ES6 features, but I'm not sure how far along they are.
