### ISSUE TITLE
Include ES5-Lib in NPM Package

### ISSUE THREAD

**Issue by MarcusWichelmann** [novnc/noVNC#1018]
Hi,

it would be great to have the generated ES5 build of the lib in the npm package as well so it's far easier to use it in web applications.
All other web-targeted npm packages I know include a "dist" or "lib" folder with a transpiled ES5 build, but this doesn't.
At the moment I've included `@novnc/novnc` into my application but I can't build it anymore, because this single dependency is ES6.
I'd be fine with running the convert-script in  `./utils` (as suggested in your docs) automatically at build-time, but that isn't possible too, because you don't ship the utils-folder with your npm package.

Is there another way to include the ES5-version of this great library or could you decide to ship the ES5-lib-folder (or at least the utils)?

**Comment by CendioOssman** [comment]
We already do such transpiling as nodejs doesn't support ES6 modules. nodejs does however support other ES6 features, so we don't do a full downgrade to ES5.

Exactly what problems are you seeing?

**Comment by MarcusWichelmann** [comment]
I'm developing a Vue.js application and make use of the noVNC library. To build this application I'm using webpack together with uglifyJs like in this template: 
https://github.com/vuejs-templates/webpack/blob/d232576a19a99d6212f16b7f69a709a6c057dc56/template/build/webpack.prod.conf.js#L36
As mentioned in the code comment there is an issue with any ES6+ code like I've experienced with noVNC, too.

But I see right now that the template has been updated to use another newer version of uglifyJs. I'll try if that works.

But still, what do you think about shipping a plain ES5 build of the lib with your mom package for compatibility reasons?

**Comment by CendioOssman** [comment]
Ideally not. Any transpiling introduces a risk (and possible limitations). So if we can keep it minimal then that is a win.

I don't suppose you know when Uglify plans to support more ES6 stuff?

**Comment by MarcusWichelmann** [comment]
Okay, I totally understand that.

I've tried it with the new `uglifyjs-webpack-plugin` now and it works just fine. https://github.com/webpack-contrib/babel-minify-webpack-plugin

Even though many other packages go the way of shipping an ES5 build with their npm-package I think with today's ever-growing ES6 support in the ecosystem it's problably fine to keep the ES6 requirement.

Thank you, I think this can be closed then if you agree.

**Comment by CendioOssman** [comment]
Great. I also dug around, and for those using uglify-js, they should be switching over to uglify-es, which is the new branch supporting ES6.
