### ISSUE TITLE
100% CPU load before first access

### ISSUE THREAD

**Issue by rkarlsba** [novnc/noVNC#1019]
Hi

I have a bunch of raspberry pi's for controlling infoscreens. These work well, and to help central monitoring, they also run novnc. This also works, but… It seems that after a reboot, whatever caused it, novnc uses 100% CPU on all cores until accessed on the net. If I try that, it works well and CPU load drops to normal. When running strace -fp <pid> while it's running on 100%, this is what it does, all the time

[pid  1354] <... gettimeofday resumed> {1518703139, 289353}, NULL) = 0
[pid  1355] gettimeofday( <unfinished ...>
[pid  1353] gettimeofday( <unfinished ...>
[pid  1355] <... gettimeofday resumed> {1518703139, 289411}, NULL) = 0
[pid  1353] <... gettimeofday resumed> {1518703139, 289437}, NULL) = 0
[pid  1354] gettimeofday( <unfinished ...>
[pid  1353] gettimeofday( <unfinished ...>
[pid  1355] gettimeofday( <unfinished ...>
[pid  1353] <... gettimeofday resumed> {1518703139, 289541}, NULL) = 0
[pid  1355] <... gettimeofday resumed> {1518703139, 289558}, NULL) = 0
[pid  1354] <... gettimeofday resumed> {1518703139, 289588}, NULL) = 0
[pid  1353] gettimeofday( <unfinished ...>
[pid  1355] gettimeofday( <unfinished ...>
[pid  1354] gettimeofday( <unfinished ...>
[pid  1355] <... gettimeofday resumed> {1518703139, 289684}, NULL) = 0
[pid  1354] <... gettimeofday resumed> {1518703139, 289729}, NULL) = 0
[pid  1355] gettimeofday( <unfinished ...>
[pid  1353] <... gettimeofday resumed> {1518703139, 289663}, NULL) = 0
[pid  1355] <... gettimeofday resumed> {1518703139, 289793}, NULL) = 0

After visiting nosql and then closing the browser, it goes back to what looks normal (or where it should have been in the first place)

[pid  1563] recv(4, "\210\202\2269n\214\225\320", 4096, 0) = 8
[pid  1563] send(4, "\210\0", 2, 0)     = 2
[pid  1563] shutdown(7, SHUT_RDWR)      = 0
[pid  1563] close(7)                    = 0
[pid  1563] exit_group(0)               = ?
[pid  1563] +++ exited with 0 +++
<... select resumed> )                  = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1563, si_uid=1000, si_status=0, si_utime=13, si_stime=6} ---
sigreturn() (mask [])                   = -1 EINTR (Interrupted system call)
wait4(1563, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 1563
gettimeofday({1518703147, 631963}, NULL) = 0
select(4, [3], [], [], {1, 0})          = 0 (Timeout)
gettimeofday({1518703148, 633782}, NULL) = 0
select(4, [3], [], [], {1, 0})          = 0 (Timeout)
gettimeofday({1518703149, 635654}, NULL) = 0
select(4, [3], [], [], {1, 0})          = 0 (Timeout)
gettimeofday({1518703150, 637354}, NULL) = 0
select(4, [3], [], [], {1, 0})          = 0 (Timeout)
gettimeofday({1518703151, 638865}, NULL) = 0
select(4, [3], [], [], {1, 0})          = 0 (Timeout)
gettimeofday({1518703152, 640382}, NULL) = 0
select(4, [3], [], [], {1, 0})          = 0 (Timeout)
gettimeofday({1518703153, 642039}, NULL) = 0
select(4, [3], [], [], {1, 0})          = 0 (Timeout)
gettimeofday({1518703154, 643825}, NULL) = 0
select(4, [3], [], [], {1, 0})          = 0 (Timeout)
gettimeofday({1518703155, 645688}, NULL) = 0
select(4, [3], [], [], {1, 0}^CProcess 1303 detached

Edit: I'm using a git version from october or thereabouts. I tried with the latest, and the problem persists.

**Comment by CendioOssman** [comment]
noVNC runs entirely in the browser, so are you saying that it's the browser that's consuming 100% CPU? Or are you referring to websockify?

**Comment by rkarlsba** [comment]
Obviously websockify - can this bug report be moved there or hsould I just report a new one?

**Comment by rkarlsba** [comment]
Registered as  #330 on websockify
