### ISSUE TITLE
graphic glitch for noVNC

### ISSUE THREAD

**Issue by leslie-qiwa** [novnc/noVNC#1023]
We're using noVNC in our application. Sometimes, we found some [graphic glitch](https://ibb.co/enrE3H) which doesn't have in native VNC player. Does anyone have any clue on it?

![screen capture](http://image.ibb.co/iQdu3H/Screen_Shot_2018_02_21_at_2_13_46_PM.png)

**Comment by samhed** [comment]
What version of noVNC are you using?

**Comment by leslie-qiwa** [comment]
thanks for reply. It is from master : a4d51bd22048df40963c999903e5156f343df293

**Comment by CendioOssman** [comment]
Which browser and VNC server?

**Comment by leslie-qiwa** [comment]
Safari - Version 11.0.2 (13604.4.7.1.3)
Firefox - 57.0.2 
Chrome - Version 64.0.3282.167 (Official Build) (64-bit)

We are using this [vncproxy](https://github.com/amitbet/vncproxy)

**Comment by DirectXMan12** [comment]
Can you send us a recording with the issue?

**Comment by leslie-qiwa** [comment]
Thanks for prompt reply. I'm trying to identify if problem is at [vncproxy](https://github.com/amitbet/vncproxy) side. Once it is done, will update you.

**Comment by leslie-qiwa** [comment]
Just one correction, we are using https://github.com/libvirt/libvirt-console-proxy as proxy. 

For more information. Our server is ESX. Per this issue: https://github.com/novnc/noVNC/issues/44, seems like ESX VNC is not officially supported. It works in our side if using above proxy, then we saw above glitch sometimes.

**Comment by leslie-qiwa** [comment]
After more investigation, I found out this issues is at our implementation. So I'll just close it. Seems like VMWare ESXi uses tight_png encoding, so it would be great if https://github.com/novnc/noVNC/issues/51 can be solved.

**Comment by CendioOssman** [comment]
#51 is already solved, so I'm not sure what you are waiting for in that case? And #44 is about extra stuff, not the basic things like working image.

**Comment by leslie-qiwa** [comment]
Thanks for the confirmation. Seems like `function encodingName(num)` at `core/encodings.js` need add support for `pseudoEncodingTightPNG` as well.

It is interesting that above graphic glitch problem can happen if I just change `encodingTight` to -260. But once I enable `pseudoEncodingTightPNG`, it will display correctly.

**Comment by leslie-qiwa** [comment]
#1026 is created. It works in our ESX environment.
