### ISSUE TITLE
ncache only works in remote resizing mode

### ISSUE THREAD

**Issue by realies** [novnc/noVNC#1024]
As the title describes, using local scaling with the ncache parameter of x11vnc turns the noVNC page gray.

**Comment by CendioOssman** [comment]
Is this also with an old version of noVNC?

Still, `ncache` will not work well with local scaling even when working as intended. It's a hack that makes the screen much larger than it really is.

**Comment by realies** [comment]
This is with 1.0.0 beta.

**Comment by CendioOssman** [comment]
Could you attach a screen shot?

**Comment by realies** [comment]
Currently not able to. The canvas disappears (hence gray background) and the scroll bars of the page goes really wide and tall. Scrolling both ways shows nothing.

**Comment by CendioOssman** [comment]
Maybe you're hitting some limit on how large a canvas can be. What is the size of the VNC session?

**Comment by realies** [comment]
1280x720@24

**Comment by CendioOssman** [comment]
I'm unable to reproduce the issue in either Firefox or Chrome. How are you starting x11vnc?

**Comment by realies** [comment]
`/usr/bin/x11vnc -xkb -noxrecord -noxfixes -noxdamage -display :1 -nopw -wait 5 -shared -permitfiletransfer -tightfilexfer
`

**Comment by CendioOssman** [comment]
That would be the same I used.

Anything in the browser console?

Which browser and platform?

**Comment by realies** [comment]
Nothing in the browser console. Latest Chrome on latest macOS.

**Comment by CendioOssman** [comment]
Tested the same setup here and it works perfectly. Even tested with a retina monitor.

Have you confirmed that things work fine without `-ncache`?

Does it work from some other machine?

**Comment by samhed** [comment]
Closing due to no response.

**Comment by realies** [comment]
@CendioOssman, unable to reproduce with latest stable - e91a095, works as expected.
