### ISSUE TITLE
Util is not defined

### ISSUE THREAD

**Issue by 0xC4N1** [novnc/noVNC#1025]
In order to update to 1.0.0 I'm trying to adapt noVNC to another location but apparently I am missing something.

The location of noVNC lib files in my project is `static/vendors/novnc/` so I have prepended all href and src attributes as well as all occurrences ending with `.js` in the `vnc.html`.

In a previous noVNC release it was also necessary to define an `INCLUDE_URI` variable so I have done that as well with a trailing slash but the error persists.

This is the error message:

```
Util is not defined
  Evaluating http://127.0.0.1:8000/static/vendors/novnc/core/rfb.js
  Evaluating http://127.0.0.1:8000/static/vendors/novnc/app/ui.js
  Loading http://127.0.0.1:8000/static/vendors/novnc/app/ui.js
http://127.0.0.1:8000/static/vendors/novnc/vendor/browser-es-module-loader/dist/browser-es-module-loader.js line 1408 > eval:254:0
execute/<@http://127.0.0.1:8000/static/vendors/novnc/core/rfb.js!transpiled:254:21
execute@http://127.0.0.1:8000/static/vendors/novnc/core/rfb.js!transpiled:253:14
declarativeExecute@http://127.0.0.1:8000/static/vendors/novnc/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:1133:5
doEvaluate@http://127.0.0.1:8000/static/vendors/novnc/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:1065:13
doEvaluate@http://127.0.0.1:8000/static/vendors/novnc/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:1049:17
ensureEvaluate@http://127.0.0.1:8000/static/vendors/novnc/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:997:13
RegisterLoader$1.prototype[Loader.resolveInstantiate]/</<@http://127.0.0.1:8000/static/vendors/novnc/vendor/browser-es-module-loader/dist/browser-es-module-loader.js:610:14
```

I can't find any usage of `Util` in noVNC so I am kinda lost on this.

**Comment by CendioOssman** [comment]
Imports are now relative so you should not modify any `.js` files, which I suspect is why you're getting that crash. Please try with just `vnc.html` modified and see how that goes.

**Comment by 0xC4N1** [comment]
Apparently <kbd>CTRL</kbd>+<kbd>F5</kbd> didn't refresh everything. After deleting the cache it magically works. 

However the network tab in the developer tools reveals that `noVNC` is trying to load the locale file from `app/locale/de.json` instead of `static/vendor/novnc/app/locale/de.json`.

**Comment by DirectXMan12** [comment]
What's the path to the page that it's being loaded on?  The loader in question just makes an XHR to `app/locale/de.json`, so it should be relative to the path of the page executing the script.

**Comment by 0xC4N1** [comment]
The path is relative to the page executing script but static files aren't loaded from there. That's why I've modified the vnc.html template. 

If the INCLUDE_URI is deprecated it seems the only way to do this is modifying `ui.js` or `webutil.js`.
