### ISSUE TITLE
Uncaught SyntaxError: The requested module does not provide an export named 'default'

### ISSUE THREAD

**Issue by cyrilrey** [novnc/noVNC#1029]
I am currently migrating from vnc_auto.html to vnc_lite.html.  
So I download last version from git and copy older vnc_auto.html from testing. 

## 1) While not using https, it is working with vnc_auto.html but not with vnc_lite:

http://192.168.91.26:6080/vnc_auto.html?token=yyy&password=xxx&debug01 => ok
http://192.168.91.26:6080/vnc_lite.html?token=yyy&password=xxx&debug01 =>  error

console show:
- 11:24:19.928 Navigated to http://192.168.91.26:6080/vnc_lite.html?token=yyy&password=xxx&debug01
- 11:24:19.987 vnc_lite.html?token=yyy&password=xxx&debug01:1 Uncaught SyntaxError: The requested module does not provide an export named 'default'

## 2) While using https it is working with vnc_lite.html but not with vnc_auto.html :

https://192.168.91.26:6080/vnc_lite.html?token=yyy&password=xxx => ok
https://192.168.91.26:6080/vnc_auto.html?token=yyy&password=xxx => error

Page dose not load completely. It is blank with "loading" on top left and 4 stacked buttons on top right.
console show :

- 11:28:07.680 Navigated to https://192.168.91.26:6080/vnc_auto.html?token=yyy&password=xxx
- 11:28:07.686 webutil.js:10 Uncaught SyntaxError: Unexpected token {
- 11:28:07.690 vnc_auto.html?token=arbaz&password=yyy:81 Uncaught ReferenceError: WebUtil is not defined at vnc_auto.html?token=arbaz&password=ABRA:81

Tell me if I can help you solving that issue while providing you need more detail.

Best Regards
Cyril

**Comment by CendioOssman** [comment]
It sounds like you have some caching issues. Please try clearing your cache and try again.

And you cannot use the old `vnc_auto.html` with the current library. You have to use the updated `vnc_lite.html`.

**Comment by cyrilrey** [comment]
Ok I would not use  `vnc_auto.html` anymore as a result it is not compatible. 

> Please try clearing your cache and try again.

I try cleaning it and **it solve the problem**. By the way I am using Opera.

Cendio, Thanks for you help and you reactivity.

**Comment by CendioOssman** [comment]
No problem, glad it works now for you.
