### ISSUE TITLE
Add Cache control headers to code/*.js and util/*.js

### ISSUE THREAD

**Issue by spacelama** [novnc/noVNC#1033]
Since noVNC is served out of its own webserver, I feel that fewer "bugs" like #729 would exist if there was an option (on by default) to cache *.js for a relatively short time (surely no one cares about excessive reloads - the entire javascript seems to be only a few hundred kB).  These are the HTTP headers I get on core/display.js:

```
    HTTP/1.1 200 OK
    Date: Mon, 05 Mar 2018 07:52:04 GMT
    Server: WebSockify Python/2.7.13
    Content-type: application/javascript
    Content-Length: 22202
    Last-Modified: Thu, 01 Mar 2018 23:31:46 GMT
    Vary: Accept-Encoding
    Connection: close
```

Add an ETag and/or Expires: and/or Cache-Control headers, and we won't have mysterious failures caused by the browser caching old javascript files forever (since it now seems impossible to convince a modern browser (particularly "smart"phones) to fully reload a page and dependencies).

**Comment by samhed** [comment]
Sending these headers would be Websockify's job. How are you thinking noVNC could change here?

**Comment by samhed** [comment]
Or, of course it doesn't have to be Websockify specifically, but the webserver.

**Comment by spacelama** [comment]
Ah of course, duh.  I was forgetting how novnc fit into websockify and thought it was all the one thing.  Never mind me.
