### ISSUE TITLE
[RFE] Create 'stable/v1.0' branch

### ISSUE THREAD

**Issue by stephenfin** [novnc/noVNC#1034]
Given that #889 was recently resolved, we (OpenStack) are looking to bump the version of noVNC deployed by default. This will allow us to work around some issues we're facing (like [this one](https://launchpad.net/bugs/1682020)).

There's currently a `stable/0.6` branch for the 0.6 release series. However, there does not appear to be any similar branch for the 1.0 release series. Could this be created? We use this in [DevStack](https://github.com/openstack-dev/devstack/blob/af43b825029c2288a76734f7a08be9e16196eb45/stackrc#L603-L606) to ensure we always get the latest and greatest version of a given release.

**Comment by DirectXMan12** [comment]
there is a `stable/0.6` branch, but I don't think we've been very good at keeping it updated.  I'd imagine a similar issue for a stable/1.0 branch.  I wonder if there's any tooling about designed to say "pull the latest GitHub release matching the given semver query"?

**Comment by CendioOssman** [comment]
I don't think we have any plans to do a 1.0.1, so adding a branch seems premature. Close this issue?

**Comment by DirectXMan12** [comment]
It's worth considering if we ever do a 2.0 (and, in that case, we'll want to give people ample time to switch over to the 1.0 branch if they're pulling from master instead of tags), but I think if we follow semver (no breaking changes in Y or Z releases), until we decide to do a 2.0, it should be fine not to have one.

**Comment by CendioOssman** [comment]
Closing this as we have no plans of creating branches "just in case".
