### ISSUE TITLE
TypeError: MouseEventConstructor is not a constructor

### ISSUE THREAD

**Issue by xiaolou86** [novnc/noVNC#1037]
Hello, 

I encountered the problem, that was "TypeError: MouseEventConstructor is not a constructor". 
My environmemt is: 
  ubuntu 16.04 + gir1.2-webkit-3.0

Thanks very much for any help.

**Comment by CendioOssman** [comment]
Which browser is this? I can't say we're too keen on more browsers that don't support event constructors.

**Comment by CendioOssman** [comment]
I'm not sure I understand your use case in that case?

**Comment by xiaolou86** [comment]
^-^

**Comment by xiaolou86** [comment]
So, I will commit a PR later, and can you help to review it?

**Comment by CendioOssman** [comment]
Sure

**Comment by xiaolou86** [comment]
please see here, thanks.
https://github.com/novnc/noVNC/pull/1038

**Comment by samhed** [comment]
We won't do anything about this, see discussion in #1038.
