### ISSUE TITLE
Adding --run-once to websockify makes noVNC inaccessible

### ISSUE THREAD

**Issue by hochas** [novnc/noVNC#1040]
I'm using version 1.0.0 and have encountered an issue with the `--run-once` option.

I'm launching x11vnc:

`x11vnc -bg -noxdamage -shared -display :0 -rfbport 5900`

I'm then launching websockify and noVNC using the following command:

`~/novnc/utils/websockify/run --web ~/novnc 6080 127.0.0.1:5900 --daemon --run-once`

Having set `--run-once` make the server inaccessible. I can reach the server at `http://127.0.0.1:6080/vnc.html?host=127.0.01:&port=6080`, but it's stuck at loading. Removing `--run-once` seems to resolve this, but I have not found the reason behind it.

Any help would be appreciated!

**Comment by CendioOssman** [comment]
`--run-once` seems to be a bit buggy. Any reason why you need that flag? It's not really meant to be used for a general server as it can only handle a single request at a time.

**Comment by CendioOssman** [comment]
Found the issue and fixed it in noVNC/websockify@e5e1dcef79fe73446dc19455d151d91210e9aa39.
