### ISSUE TITLE
Access through CiscoAsa5510

### ISSUE THREAD

**Issue by mityai013** [novnc/noVNC#1042]
There is a problem. I have installed noVNC , WebSockets, TightVnc on the local network. Everything is working. But if I try to publish via Assa5510 (local network) i get a script error.
`SyntaxError: missing } after function body`
 Help solve the problem.
![image](https://user-images.githubusercontent.com/37611352/37697553-8518c79a-2cee-11e8-99e9-5052a5f6727c.png)

**Comment by CendioOssman** [comment]
I'm not sure there is much we can do as it seems the Cisco device is corrupting the files. :/

Could you attach that file as it looks after it has passed through the box?

**Comment by mityai013** [comment]
[https://yadi.sk/d/kDKiSx303Tba3u](url)

**Comment by mityai013** [comment]
All files noVNC are on the local computer.  Only the publication passes through the cisco

**Comment by CendioOssman** [comment]
There is a removed `;` in that file, but otherwise it is not modified. So I cannot see any issue, nor reproduce the problem with Firefox here. :/

Can you try another browser and see if that changes things?

**Comment by CendioOssman** [comment]
Does it work in a newer Firefox? 50 is even older than the current ESR.

**Comment by mityai013** [comment]
no, no working in a newer Firefox.

**Comment by mityai013** [comment]
did not understand what I should do?
![image](https://user-images.githubusercontent.com/37611352/37713842-22a60f60-2d29-11e8-9b40-3e2603537719.png)

**Comment by CendioOssman** [comment]
Press F12 so you get the browser console:

![screenshot from 2018-03-21 15-29-38](https://user-images.githubusercontent.com/6640916/37715630-d2f0851a-2d1c-11e8-8d16-b4c3350287f3.png)

Then click the name on the right so it opens the source file at the right place:

![screenshot from 2018-03-21 15-29-53](https://user-images.githubusercontent.com/6640916/37715663-e67dd5d8-2d1c-11e8-9f00-4564cbf6531f.png)

**Comment by mityai013** [comment]
![image](https://user-images.githubusercontent.com/37611352/37754272-eab42e78-2db1-11e8-97f7-119b9948a743.png)

**Comment by CendioOssman** [comment]
Something must have gone wrong there. That is not Firefox 59, and the error is not in the console log.

**Comment by mityai013** [comment]
That is Firefox 50, and the error  in the console log.

**Comment by CendioOssman** [comment]
Perhaps it doesn't log as well... Could you try it with 59?

**Comment by mityai013** [comment]
![image](https://user-images.githubusercontent.com/37611352/37768775-d6b15896-2ddf-11e8-8c09-741b8f795efa.png)

**Comment by CendioOssman** [comment]
I guess the Cisco modifications mess this up as well.

I'm afraid there isn't really anything we can do here. You'll have to file a support request with Cisco and see if their device can be modified so it doesn't break things.
