### ISSUE TITLE
Missing MutationObserver 

### ISSUE THREAD

**Issue by mareklibra** [novnc/noVNC#1043]
When integrating the `noVNC v1.0.0` into another project, the `jest` complains about missing 'MutationObserver' in `core/util/events.js`.

Can be fixed by adding polyfill like https://www.npmjs.com/package/mutation-observer .

**Comment by DirectXMan12** [comment]
What browser are you testing in?

**Comment by DirectXMan12** [comment]
or, rather, if you're not testing in a browser-like environment (chrome headless, etc), why?

**Comment by mareklibra** [comment]
I'm wrapping noVNC into React component (btw. big thank you for the ES6!!) with additional elements within `pattenrfly-react` library.

The consuming application will be browser-based - there is no issue, work's fine.

Anyway, the `patternfly-react` project is tested by `jest` (as the majority of recent React projects). It has no global `MutationObserver` class defined, use of [browser configuration](https://facebook.github.io/jest/docs/en/configuration.html#browser-boolean) does not help.

I don't do actual UI testing in patternfly-react, just `import` of `core/rfb.js` prior bunch of non-browser-rendering tests. Not absolutely sure when, maybe when `jest` passes through the code for the `coverage` report, but it fails on this missing reference.

I can easily fix this in patternfly-react by adding the missing polyfill within test environment setup but I believe this issue is something what others will face as well when testing with `jest`.

**Comment by CendioOssman** [comment]
That's unfortunate, but I don't think we want to start adding workarounds for other stuff than the browsers. It's quite enough just dealing with their bugs and limitations. :/

Have you tried requesting this feature from jest?

**Comment by mareklibra** [comment]
> That's unfortunate, but I don't think we want to start adding workarounds for other stuff than the browsers. It's quite enough just dealing with their bugs and limitations. :/

That's understandable. The fix in jest env setup is still feasible.

> Have you tried requesting this feature from jest?

Good idea, but timeframe to fix (if ever) is expected to be long leading to a workaround anyway.
