### ISSUE TITLE
Change remote server on WebGui

### ISSUE THREAD

**Issue by Quving** [novnc/noVNC#1044]
Hello there,
I wonder if it is possible to change the remote-server on run time through the web gui.
I couldn't find an other solution but passing the port and ip of the desired remote server to the launch.sh file.

**Comment by CendioOssman** [comment]
No, as that would create a very insecure proxy. What you can do is look at the token system in websockify. That allows you to match different websocket paths to different VNC servers:

https://github.com/novnc/websockify/wiki/Token-based-target-selection
