### ISSUE TITLE
How to set quality and/or compression for slow network connection

### ISSUE THREAD

**Issue by stecky** [novnc/noVNC#1046]
Hello, I am using noVNC for testing a web app and the lag is significant on my network.
I don't need full color depth so how can I force it to low quality so that it will respond more quickly?
I have seen some comments in other issues stating that it can be done by modifying the code, but I haven't seen how to do that exactly. Any help would be appreciated.

**Comment by samhed** [comment]
You can experiment with changing the quality and compression values in core/rfb.js:

https://github.com/novnc/noVNC/blob/master/core/rfb.js#L1267
https://github.com/novnc/noVNC/blob/master/core/rfb.js#L1268

**Comment by stecky** [comment]
Thank you so much @samhed! It worked like a charm!
