### ISSUE TITLE
babel-worker.js:13014:4 unreachable code after return statement with firefox 52.7.3 (64-bit)

### ISSUE THREAD

**Issue by sarcarx** [novnc/noVNC#1047]
When using NoVNC embedded with firefox 52.7.3 (64-bit) I get the following error in the console :

`babel-worker.js:13014:4 (http://localhost:1234/static/noVNC/vendor/browser-es-module-loader/dist/babel-worker.js) unreachable code after return statement babel-worker.js:13026:4 (http://localhost:1234/static/noVNC/vendor/browser-es-module-loader/dist/babel-worker.js) unreachable code after return statement babel-worker.js:13014:4 (http://localhost:1234/static/noVNC/vendor/browser-es-module-loader/dist/babel-worker.js) unreachable code after return statement babel-worker.js:13026:4 (http://localhost:1234/static/noVNC/vendor/browser-es-module-loader/dist/babel-worker.js) unreachable code after return statement babel-worker.js:13014:4 (http://localhost:1234/static/noVNC/vendor/browser-es-module-loader/dist/babel-worker.js) unreachable code after return statement babel-worker.js:13026:4 (http://localhost:1234/static/noVNC/vendor/browser-es-module-loader/dist/babel-worker.js) unreachable code after return statement babel-worker.js:43349:1 (http://localhost:1234/static/noVNC/vendor/browser-es-module-loader/dist/babel-worker.js) unreachable code after return statement babel-worker.js:43349:1 (http://localhost:1234/static/noVNC/vendor/browser-es-module-loader/dist/babel-worker.js)`

Using Chrome browser the code works perfectly

**Comment by CendioOssman** [comment]
Those are just warnings and are harmless, so nothing to worry about.
