### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by KOPACb** [novnc/noVNC#1049]
I have tested a little bit noVNC and got some experience at connectring it with nginx.
and i got some refinement to https://github.com/novnc/noVNC/wiki/Proxying-with-nginx
Serving static files:
```
        location /vnc {
                index vnc.html;
                alias /var/www/noVNC/;
                try_files $uri $uri/ /vnc.html;
        }
```
i was working on many local vnc connections, so i dont need to use websockify at all.
The url to connect will be something like that:
```
example.com/vnc/vnc.html??host=vnc.example.com&port=5900&password=secret&autoconnect=true
```
in case the vnc host isnt behind nat from client ( or got port forwarding )

**Comment by samhed** [comment]
If you are suggesting a change to the wiki, feel free to change it. The wiki is editable, and the nginx page is mostly written by non-maintainers anyway. Personally I have only tried nginx briefly so I don't know much about it.

**Comment by KOPACb** [comment]
Ok. i updated the wiki page. Im not sure about alias path.
Should it be /var/www/noVNC/; or /path/to/noVNC. 
Thank you.

**Comment by samhed** [comment]
From what I understand it seems like alias path should be the actual location, that is when someone navigates to /vnc they will actually be served the content found at alias path. In that case it should be /path/to/noVNC, no?

**Comment by KOPACb** [comment]
yep. if you using root directive when you set
```
root /path/to/
``` 
in `location /static` nginx will bring you to `/path/to/static`
`alias /path/to/ will bring you to `/path/to`

i mean how it should be written in wiki: /path/to/noVNC or real path /var/www/noVNC

**Comment by samhed** [comment]
I'd prefer `/path/to/noVNC`since I believe it won't be `/var/www/noVNC` for everyone?

**Comment by KOPACb** [comment]
ok, ill change it.

**Comment by samhed** [comment]
Thank you @KOPACb
