### ISSUE TITLE
noVNC pending tools on left side missing icon

### ISSUE THREAD

**Issue by ringyear** [novnc/noVNC#1051]
I have deployed noVNC on centos7,
```bash
# uname -r 
Linux 5ea857feb14c 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
I take mate as the desktop and tiger-vncserver as vncserver, which turns out that i can't find the icon of left-side tools, it appear as the following image, while my broswer is chrome which of version 64.0.3282.140

![snipaste_2018-04-13_15-48-34](https://user-images.githubusercontent.com/5770579/38722925-2418842a-3f32-11e8-8c6f-6e378bb49a5e.png)

![snipaste_2018-04-13_15-47-26](https://user-images.githubusercontent.com/5770579/38722887-06a4b4c2-3f32-11e8-8825-5a165975c6cd.png)

could anyone help me? thanks a lot.

**Comment by CendioOssman** [comment]
Your web server is sending the SVG files with an incorrect MIME format. If you are using websockify then this usually indicates that the MIME database isn't properly installed on the system. If it's another web server then you'll have to check its configuration for how to get this properly set up.
