### ISSUE TITLE
npm run build - Failed to minify the code from rfb.js

### ISSUE THREAD

**Issue by ketysek** [novnc/noVNC#1059]
Hello!
I'm using your awesome library in my react app (builded in [create-react-app](https://github.com/facebook/create-react-app)) and when I try to make my production build, I'm getting error:
```
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/@novnc/novnc/core/rfb.js:517 

Read more here: http://bit.ly/2tRViJ9
```

I've installed your library via npm. Thank you for your support! We are building web interface for user friendly automated cloud deploying of [Scipion](https://github.com/I2PC/scipion/wiki) application :)

**Comment by CendioOssman** [comment]
We want to keep the transpiling to a minimum, so I don't think we'll add more just to support tools that aren't keeping themselves up to date. Can your work flow incorporate an extra step of running babel by hand on the files?

(note that we might get more ES5 transpiling as a side effect of #1013, but that's not an explicit goal)

**Comment by ketysek** [comment]
I've forked create-react-app and modified minification settings

**Comment by ketysek** [comment]
Yes, it's okay now, I've changed minification plugin for the one with es6 support.
