### ISSUE TITLE
My program use noVNC to play my rfb video. but it work slowly.

### ISSUE THREAD

**Issue by Felix199404** [novnc/noVNC#1061]
the rfb server  writes 4096 bytes  to websock.js every time.
but when it update a frame  need to receive more than 6000000 bytes.
so the websock will be invoked more than 1400 times .  and every time it may cost 1 millisecond. 
totally it spends more than 1 seconds updating a frame. 
and the javascript is not mult-thread code language . i have not idea to deal this problem

**Comment by CendioOssman** [comment]
That should not be an issue, so I suspect something goes wrong with how you feed your data.

Could you share your code and video file with us?

**Comment by Felix199404** [comment]
> _handle_message: function () {
            if (this._sock.rQlen() === 0) {
                Util.Warn("handle_message called on an empty receive queue");
                return;
            }

            if (this._msgTimer) {
                clearInterval(this._msgTimer);
            }
            if(!this._seekInterval) {
                this._seekInterval = setInterval(function() {
                    if(this.player.check_seek()) {
                        this._sock._rQi = this._sock._rQlen;
                    }
                }.bind(this), 100);
            }

            switch (this._rfb_state) {
                case 'disconnected':
                case 'failed':
                    Util.Error("Got data while disconnected");
                    break;
                case 'normal':
                    if(this.player.current_state != this.player_states.PLAY) {
                      
                        return;
                    }
                    if(!this.playerProto.read()) {
                        //return false;
                    }
                    if(this.playerProto.packet_type == 255 && this.playerProto.packet_stamp == -1) {
                        console.log("end");
                        this.playerProto.canReplay = true;
                        this.playerProto.doStop();
                        return;
                    }
                  // to handle the message
                    var ret = this.process_message();

**Comment by Felix199404** [comment]
>   process_message: function() {
            var type = this.playerProto.packet_type;
            var ret = true;

           
            var start = new Date().getTime();
            if (type == this.playerProto.RfbContextPacket) {
                this.load_context();
               
            } else if (type == this.playerProto.RfbClientPacket) {
                var oldLen = this._sock.rQlen();
                this.player.process_client_message();
                this.playerProto.packet_len -= oldLen - this._sock.rQlen();

            } else if (type == this.playerProto.RfbServerPacket) {
                var oldLen = this._sock.rQlen();
              //  it will run the code when this video play
                ret = this.player.process_normal_protocol();
                this.playerProto.packet_len -= oldLen - this._sock.rQlen();
            }

**Comment by Felix199404** [comment]
` process_normal_protocol: function() {
                return this._normal_msg();
            }.bind(this),`

**Comment by Felix199404** [comment]
>  _normal_msg: function () {
            var msg_type;

            if (this._FBU.rects > 0) {
                msg_type = 0;
            } else {
                msg_type = this._sock.rQshift8();
            }

            switch (msg_type) {
                case 0:  // FramebufferUpdate
				
                    var ret = this._framebufferUpdate();
					
                    if (ret) {
                        RFB.messages.fbUpdateRequests(this._sock, this._display.getCleanDirtyReset(), this._fb_width, this._fb_height);
                        this._sock.flush();
                    }
                    return ret;

**Comment by Felix199404** [comment]
and then it will run the function _framebufferUpdate and decoder HEXTILE.

first of all . i am very sorry for  that i am not good at using the git editor to write a nice comment.
and the code quailty of my eo-worker's code  and my bad writing in  english.

i write the comment with the normal code flow . i mean it will run 
handle_message -- >process_message --> process_normal_protocol --> _normal_msg --> _framebufferUpdate --> HEXTILE.

and we also add some codes in the original noVNC in version 6.0 perhabs. but it decode the  frame data
very fast .so i think it is not matter.

**Comment by Felix199404** [comment]
and when i use another Java rfb Video Player . it can play smoothly. 
the java I\O  inputstream read API method . it will be blocked when the sock inputstream can not be read enough bytes. 
but javascript language is without this feature. it seemly only can use the "if" condition to cycle check the 
receive queue is enough to update the frame.
so when the websocke method "onmessage" receiced 1000 times data is for writing the stamp frame.
it maybe check the receive queue 999 times.

**Comment by Felix199404** [comment]
i tested result  when i got all the 6057344 bytes in the receive queue  . and to use HEXTILE to decode.
how can i optimize the time？ make it decoding this 6057344 faster.?

// the HEXTILE decoder spent 1419 miliscond to decode 6057344 bytes. 
rfb.js:1936 handle time : 1419

//this is a frame i need to update
rfb.js:285 this.packet_type:2,this.packet_len:6057344,this.packet_stamp4680

**Comment by CendioOssman** [comment]
I would suspect you're relying on timers somewhere which are slowing things down (Javascript timers are rate limited). But these snippets don't really give the full picture. Please give us something we can test ourselves or we can't really help you.

**Comment by Felix199404** [comment]
[novnc.zip](https://github.com/novnc/noVNC/files/1957338/novnc.zip)

**Comment by Felix199404** [comment]
i want upload the video file .but the file is too big to upload.

**Comment by CendioOssman** [comment]
Can you make a smaller recording?

**Comment by CendioOssman** [comment]
I'm afraid the code is not that clear, and it also lacks the server component of things. But it does use a bunch of timers, and it is also based on an older version on noVNC. So I suggest upgrading, and getting rid of those timers.

Other than that I would suggest using the profiling tools in the browsers to see where things stall. I'm afraid we cannot really provide any more help for such a modified version of noVNC.
