### ISSUE TITLE
Multiple connections & access canvas window

### ISSUE THREAD

**Issue by suneel11** [novnc/noVNC#1068]
Hello
Greetings of the day!!

**#1 Multiple Connections**
I am working with the tightvncserver and noVNC. Everything is working good but then when multiple users try to access their own login all they see is the already logged in session. Is there a way to configure noVNC which automatically can generate session for the new logged in user. 

**#2 Access Canvas Window**
I want to access the window inside the vnc view which comes from canvas so that I can trigger my custom javascript functions to make it work according to my requirements.

Please provide me some solution and links so I can make my noVNC config according to me.

Thanks & Regards

**Comment by CendioOssman** [comment]
> #1 Multiple Connections

The VNC protocol has no session management so that is something you'll have to handle outside of noVNC.

> #2 Access Canvas Window

I'm afraid I don't understand what you want to do here. Could you give me an example?

**Comment by suneel11** [comment]
#2 Access Canvas Window
Let's take a example I want some secure files from the user. So, I want user to get login at my server using noVNC and download the file. So, the file will be downloaded at my server. Now, within this whole process server is responsible to open the page/tab of the website and click to download. User has to just login.
Does it possible to write some script which will automatically trigger once user gets login at my server?

**Comment by samhed** [comment]
1: no
2: not something you can do with noVNC
