### ISSUE TITLE
Catching errors

### ISSUE THREAD

**Issue by ketysek** [novnc/noVNC#1071]
Hi, I can't figure out, how to catch noVNC connecting errors? I tried it these ways, but none worked.

1.
```
this.rfb = new RFB(this.containerDOM, url, {
  shared: true,
  credentials: { password: deployment.vnc_password }
}).catch((error) => console.log(error))
```

2.
```
try {
  this.rfb = new RFB(this.containerDOM, url, {
    shared: true,
    credentials: { password: deployment.vnc_password }
  })
} catch(error) {
  console.log(error)
}
```

**Comment by samhed** [comment]
RFB won't throw errors on connection problems, there are a number of events you can look at. Check out the API documentation:

https://github.com/novnc/noVNC/blob/master/docs/API.md#disconnect

**Comment by ketysek** [comment]
Okay, thanks, I didn't notice that these are events. But there's no message if error occurs, why disconnect event has fired?

**Comment by samhed** [comment]
Not in the events no. The reasoning here is that the user interface should be simple and end-user friendly. You can find some more detailed info logged in the browser's javascript console.
