### ISSUE TITLE
Multiple users connection

### ISSUE THREAD

**Issue by suneel11** [novnc/noVNC#1072]
Hello 
I am trying to access multiple users but when multiple users try to access their own login all they see is the already logged in user. I just want to grant multiple users to access there own window not the same window for all. Is there any way in noVNC which can help me to solve my issue.

**Comment by CendioOssman** [comment]
I'm afraid this is outside of the scope of this project. The VNC protocol doesn't have any session management, so any such handling will have to be built separately. E.g. you could create a login page before noVNC that sets everything up.

**Comment by CendioOssman** [comment]
No, I'm afraid we do not have any such examples. You would have to have multiple noVNC instances with different WebSocket settings in each.
