### ISSUE TITLE
netstat is deprecated, use ss instead

### ISSUE THREAD

**Issue by lpreams** [novnc/noVNC#1075]
noVNC appears to require the `netstat` command from the `net-tools` package. This package is considered deprecated. `man netstat` will tell you that `This program is mostly obsolete.  Replacement for netstat is ss.`. 

Newer Linux distros don't ship with `net-tools` anymore, instead using the newer and still actively-supported `iproute2` package which includes the `ss` command to replace `netstat`. noVNC should consider replacing its use of `netstat` with `ss`.

**Comment by DirectXMan12** [comment]
it's not strictly required for using noVNC -- just for using launch.sh, but yet, we should support `ss` as well.

**Comment by hvindin** [comment]
Just saw this while I was trying to do noVNC for something, seems like a ridiculously easy thing to fix, and we can even remove the dependencies on external tools by just using bash itself.
