### ISSUE TITLE
Hangs at connecting...

### ISSUE THREAD

**Issue by gurde** [novnc/noVNC#1077]
I built it with `node ./utils/use_require.js --as amd --with-app`. From the html I excluded the ES6 modules.
The server works fine, tested it using the novnc.html from the project.
But, when I'm including (requirejs) noVNC into my project and for some reason it hangs at connecting...

Any ideas? Suggestions?

```
>> RFB.constructor
12:45:03.422 display.js?_=1525859100604:62 >> Display.constructor
12:45:03.423 display.js?_=1525859100604:92 User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
12:45:03.423 display.js?_=1525859100604:197 Setting viewport to full display region
12:45:03.424 display.js?_=1525859100604:102 << Display.constructor
12:45:03.425 display.js?_=1525859100604:197 Setting viewport to full display region
12:45:03.425 rfb.js?_=1525859100604:285 << RFB.constructor
12:45:03.436 rfb.js?_=1525859100604:680 New state 'connecting', was ''.
12:45:03.437 rfb.js?_=1525859100604:449 >> RFB.connect
12:45:03.437 rfb.js?_=1525859100604:451 connecting to wss://192.168.2.110/vnc?hypervisor=192.168.5.153&ticket=4ce8aaa9239ec861
12:45:03.442 rfb.js?_=1525859100604:473 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
_connect @ rfb.js?_=1525859100604:473
_updateConnectionState @ rfb.js?_=1525859100604:693
12:45:03.442 rfb.js?_=1525859100604:475 << RFB.connect
12:45:03.493 websock.js?_=1525859100694:243 >> WebSock.onopen
12:45:03.493 websock.js?_=1525859100694:245 Server choose sub-protocol: binary
12:45:03.493 rfb.js?_=1525859100604:240 Starting VNC handshake
12:45:03.493 websock.js?_=1525859100694:249 << WebSock.onopen
12:45:03.494 rfb.js?_=1525859100604:864 Server ProtocolVersion: 003.008
12:45:03.495 rfb.js?_=1525859100604:906 Sent ProtocolVersion: 003.008

**Comment by CendioOssman** [comment]
So if I understand you correctly it works fine when using the unmodified `vnc.html` in the root of the project, but not when using the converted one?

PS. It seems you are using `master` rather than 1.0. In that case `use_require.js` has the argument `--only-legacy` to omit the ES6 module code completely.

**Comment by gurde** [comment]
I included only the legacy scripts and removed the es6 code.

**Comment by CendioOssman** [comment]
But it works if you don't use `use_require.js`?

**Comment by gurde** [comment]
I recompiled with only legacy. So this was is clearer. Using vnc.html works, in my project included with requirejs hangs at connect.

**Comment by gurde** [comment]
Chrome, firefox, safari. And the websocket stream is from vmware.

**Comment by CendioOssman** [comment]
I'm afraid I cannot reproduce the issue. Could you test with a different VNC server?

**Comment by gurde** [comment]
The server is ok. As I was saying, when connecting using vnc.html that is in the build dir it works.
Only when I include the app.js with requirejs in my project it stops working.

**Comment by gurde** [comment]
from vnc.html -> ![image](https://user-images.githubusercontent.com/36549/39813047-9b55021a-5397-11e8-84b9-0923f1c26084.png)

from my project -> ![image](https://user-images.githubusercontent.com/36549/39813085-bd4a5208-5397-11e8-8a3f-030ba4abe4c6.png)

**Comment by gurde** [comment]
Help please.

**Comment by gurde** [comment]
Figured it out. The problem was caused by pace.js and the solution is to make pace.js ignore websocket requests.

```
window.paceOptions = {
	ajax: false,
	restartOnRequestAfter: false,
};
```
