### ISSUE TITLE
No mouse pointer

### ISSUE THREAD

**Issue by cerriex** [novnc/noVNC#1078]
Hi Guys, 

I have found that on a HP Envy laptop I am unable to use the mouse in NoVNC.

Works fine on other machines.

Strange issue, not sure what else I can provide here?

Thanks.

**Comment by samhed** [comment]
What version of noVNC are you using and on which operating system and browser? Does the laptop have a touch screen, if so does touch input work?

**Comment by cerriex** [comment]
Hi, thanks for getting back to me.

I've been informed it's 0.4 version of Novnc. Its going to be updated to 1.0.0 shortly.

It's Windows 10, Chrome and FF. It is touch screen but didn't think to try that! I'll try and update you.

Thanks.

**Comment by samhed** [comment]
Ok, if it's version 0.4 of noVNC then it's a known issue with devices with touch screens. It was fixed and an upgrade to the latest release should fix the problem.
