### ISSUE TITLE
Connection to Mac OS 10.13 (High Sierra) not possible

### ISSUE THREAD

**Issue by Luzifer** [novnc/noVNC#1079]
When trying to connect to a MacBook Pro 15" late 2013 an "Incompatible Version" error occurs.

----

- Screen-Sharing is enabled, all users are allowed to connect, VNC control using password is enabled, guests may not ask for control:  
![image](https://user-images.githubusercontent.com/20142/40245209-3d8804ae-5ac5-11e8-85ea-0deaa8eb48a4.png)
- Changing the protocol to `3.7` or `3.8` (trying to solve the "Incompatible Version") did change the error message but did not solve the issue itself.
- Using the same setup to connect to a Linux VNC server (same path of connections etc.) results in a successful connection.

----

### Versions of used components

| Component | Version |
| ---- | ---- |
| noVNC | tag v1.0.0 |
| websockify | commit 38b77714a9987dc5fc4d4e6158c57072c568236a |
| Mac OS | 10.13.4 |
| Google Chrome | 67.0.3396.30 (Official Build) beta (64-bit) |

----

### Browser console output (Protocol 3.3)

```
rfb.js:400 		connecting to wss://46111751.eu.ngrok.io:443/websockify
websock.js:217 	Server choose sub-protocol: binary
rfb.js:819 		Server ProtocolVersion: 003.889
rfb.js:689 		Failed when connecting: Security negotiation failed on authentication scheme (reason: Incompatible Version.)
websock.js:239 	Closing WebSocket connection
rfb.js:453 		Encoding stats for this connection:
rfb.js:461 		Encoding stats since page load:
```

----

### Browser console output (Protocol 3.7 / 3.8)

```
rfb.js:400 		connecting to wss://46111751.eu.ngrok.io:443/websockify
websock.js:217 	Server choose sub-protocol: binary
rfb.js:818 		Server ProtocolVersion: 003.889
rfb.js:688 		Failed when connecting: Unsupported security types (types: 30,33,36,35)
websock.js:239 	Closing WebSocket connection
rfb.js:452 		Encoding stats for this connection:
rfb.js:460 		Encoding stats since page load:
```

----

### Patch used for protocol version change

```patch
--- /opt/novnc/core/rfb.js
+++ /opt/novnc/core/rfb.js.patch
@@ -823,13 +823,13 @@
                 break;
             case "003.003":
             case "003.006":  // UltraVNC
-            case "003.889":  // Apple Remote Desktop
                 this._rfb_version = 3.3;
                 break;
             case "003.007":
                 this._rfb_version = 3.7;
                 break;
             case "003.008":
+            case "003.889":  // Apple Remote Desktop
             case "004.000":  // Intel AMT KVM
             case "004.001":  // RealVNC 4.6
             case "005.000":  // RealVNC 5.3
```

**Comment by CendioOssman** [comment]
I'm afraid it doesn't seem like your configuration has had any effect as the server is still only advertising proprietary Apple stuff. Or perhaps they've finally dropped support for standard VNC authentication.

I'm afraid it always going to be a bit of a gamble connecting to Apple's server as they're not really properly compatible with standard VNC and their changes aren't documented. :/
