### ISSUE TITLE
Type Error: type 1 character novnc show 2 same character

### ISSUE THREAD

**Issue by n7tequila** [novnc/noVNC#1081]
I am use novnc connect to realvnc server(system is windows 2012 server). 
but when i type 1 character, novnc will type 2 same character.

why???

**Comment by n7tequila** [comment]
i find problem, because novnc canvas bind double event.
keyup, keydown, keypreee bind two event.

**Comment by binhex** [comment]
Can you give more detail, is this a setting for noVNC? I'm seeing the same issue

**Comment by CendioOssman** [comment]
Are you using `vnc.html`? Where are you seeing a double bind?

**Comment by arnaudmorin** [comment]
We are using vnc_auto.html and we have the same issue.
Is there any known fix?

**Comment by CendioOssman** [comment]
We haven't even pinpointed the issue yet. Might be a server bug.

What server are you using? And are you using noVNC 1.0.0? Doesn't sound like it since `vnc_auto.html` has been renamed there.

**Comment by duvayu** [comment]
I have this problem too.server is acentos6 and tigervnc and it happens only on chrome.

**Comment by duvayu** [comment]
tigervnc-server version 1.1.0
noVnc 0.6.1
apache 2.2.15
centos 6.5

**Comment by CendioOssman** [comment]
Please try again using noVNC 1.0. We've made lots of fixes for the keyboard since 0.6.1.

**Comment by duvayu** [comment]
same problem with novnc 1
no problem with same server and vncviewer
no problem with firefox

**Comment by duvayu** [comment]
updating to chrome 71 fixed the problem i think.

**Comment by samhed** [comment]
I am unable to reproduce your issue with:

chrome 70
noVNC 1.0.0
tigerVNC 1.9.0

tigerVNC 1.1.0 (which you said you are using) is from 2011, how come you are using such an ancient version?

**Comment by duvayu** [comment]
yum installs this version.can it be the problem?

**Comment by samhed** [comment]
Ok. I don't know if this is the problem or not, but it might be worth it for you to test a newer version of TigerVNC.

**Comment by duvayu** [comment]
The new version stoped working on two of my servers at the same time and i was forced to downgrade to the old no vnc.
The new version was ok.
