### ISSUE TITLE
dynamic target via query string

### ISSUE THREAD

**Issue by flexsingit** [novnc/noVNC#1085]
Hello All,

I have been trying to utilize noVNC for my application and I want to send the target host and port from the query string or somehow dynamically from a PHP file.

Any help will be highly appreciated.

Thanks,
Himanshu

**Comment by samhed** [comment]
Yes? simply append `?host=HOST&port=PORT` to the url (replace HOST and PORT with the host and port you want to use)

**Comment by flexsingit** [comment]
@samhed  thanks for the information, 
JYI i want to send the target host and port which I want to access remotely. Please confirm if the above will  work for the same as well.

**Comment by samhed** [comment]
If you are talking about specifying the VNC server - that isn't possible. How that works will depend on your websocket proxy.

**Comment by flexsingit** [comment]
Thanks @samhed ,

I am also looking at Token Based process and i am receiving the below error 

[01/Jun/2018 15:24:12] code 405, message Method Not Allowed

can please help on this ?

**Comment by samhed** [comment]
Is that a message from Websockify?
