### ISSUE TITLE
Not seeing local cursor when connected to touch-enabled device

### ISSUE THREAD

**Issue by HotelCalifornia** [novnc/noVNC#1090]
Preface: I'm honestly not sure whether this is a bug or an unimplemented feature, but it's had me scratching my head for a couple days now.

I've been working at embedding a VNC viewer in a react app, using [@novnc/novnc](https://www.npmjs.com/package/@novnc/novnc). Effectively, I've made a react component that wraps an `RFB` object, which seems to work well.

The problem is that no cursor renders over the canvas at all, when I'd expect to see... something. This makes it nearly impossible to control the remote device, because I can't tell what I'm pointing at.

A little more investigation reveals that there should be a cursor rendering with a data URI, but as far as I can tell, it's just a 16x16 (or 8x8?) fully transparent square (I've checked this using a few different online base64->image decoders). For reference, here is what chrome dev tools reports:

```css
    cursor: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAH0lEQVQ4T2NkoBAwUqifYdQAhtEwYBgNA1A+Gvi8AAAmmAARf9qcXAAAAABJRU5ErkJggg==") 8 8, default;
```

PS: at one point, I tried overriding the CSS with
```css
canvas {
    cursor: pointer !important;
}
```
but that ended up degrading the performance of the viewer significantly.

**Comment by DirectXMan12** [comment]
Is the remote server sending an actual cursor, or just a blank one?  What happens with other VNC clients?

**Comment by HotelCalifornia** [comment]
re: is the remote server sending a cursor
I _think_ it is. the server is `x11vnc` (running through websockify), and as far as I can tell, the default behavior is to render some shape for the cursor. That said, I can try to specify the `-cursor [mode]` option and see if that works.

re: other clients
testing with [this client](https://www.realvnc.com/en/connect/download/viewer/) (on macOS, if that makes a difference) reveals that we do get a small square rendered as a cursor. 

I guess I should have mentioned above that we're running `x11vnc` through `websockify`

**Comment by CendioOssman** [comment]
That means it is sending a blank cursor (realvnc shows a square when it gets a blank cursor from the server). Unfortunately x11vnc has had a history of not handling cursors properly. So I'm afraid you'll have to file a bug with them and have them either send a proper cursor, or start rendering it server side.

**Comment by HotelCalifornia** [comment]
for posterity, setting `-cursor X` as an option to `x11vnc` was enough to get a cursor passed through and rendering
