### ISSUE TITLE
Resize noVNC 

### ISSUE THREAD

**Issue by mervekaya** [novnc/noVNC#1091]
Hello,
I use noVNC both Linux and Windows. In Linux , I can resize screen with  `vncserver :1 -geometry 1024x768  ` command but in Windows althought i use TigerVNC, TightVNC UltraVNC in server side i can not find command for resize screen. There is only a way from GUI. I want to resize screen from command line interface to use this command in java code. Is there a way to do it with noVNC ?

**Comment by CendioOssman** [comment]
I'm afraid this has nothing to do with noVNC so you'll have to check with the respective server you want to use.

**Comment by mervekaya** [comment]
thank you for quick answer.
