### ISSUE TITLE
"Caps Lock" key doesn't work

### ISSUE THREAD

**Issue by QinXiao2017** [novnc/noVNC#1092]
I use online version of the noVNC client: http://novnc.com/noVNC/vnc.html
Connect to my selenoid ui.
In noVNC, "Caps Lock" key doesn't work.
When the light on or off, i can't get the letter in uppercase.
But when i visit  in selenoid ui, "Caps Lock" key is OK.

**Comment by CendioOssman** [comment]
We don't have any known issues with CapsLock in noVNC. Are you sure your server supports it properly? Many don't.

**Comment by QinXiao2017** [comment]
Yes.
In Selenoid UI,  "Caps Lock" key is OK.

**Comment by CendioOssman** [comment]
Please enable debug logging in the settings and check your browser console for what noVNC sends when you press the keys you have problems with.

**Comment by CendioOssman** [comment]
No response.

**Comment by dennisvanderpool** [comment]
Can you please re-open this or should i make a new ticket? I have the same issue. I have no problem in support debugging it.

**Comment by CendioOssman** [comment]
We can reopen it. The last instructions are still valid; please enable debug logging and check the browser console for key press messages.

**Comment by samhed** [comment]
@dennisvanderpool did you find time to provide some logs for further troubleshooting?

**Comment by dennisvanderpool** [comment]
@samhed No, haven't took the time yet. I will take a look at it wednesday. Where/how to enable the debug logging?

**Comment by samhed** [comment]
If you use vnc.html you can enable it from the settings GUI

**Comment by samhed** [comment]
No response

**Comment by fcwu** [comment]
Chrome 80 on OSX 10.15

Got 
```
Sending keysym (down): 65509
keyboard.js:53 onkeyevent up, keysym: 65509 , code: CapsLock
rfb.js:373 Sending keysym (up): 65509
```

![image](https://user-images.githubusercontent.com/165370/79240507-758afa00-7ea4-11ea-8bd9-0f54bd611438.png)

**Comment by CendioOssman** [comment]
That is the correct keysym for CapsLock, so I'm afraid that is a server bug. So I'll have to direct you to file a bug with the maintainers of the server.

**Comment by fcwu** [comment]
Thank you. I got the problem. Fixed the problem by add `-capslock` on x11vnc.

Reference: https://bugzilla.redhat.com/show_bug.cgi?id=577187
