### ISSUE TITLE
Check if an vpn connection is already open.

### ISSUE THREAD

**Issue by jtothe4n** [novnc/noVNC#1099]
I want to limit the access to my vpn server to one client at a time.
Already configured the server to just allow one connection.

If I open a 2nd instance to my vpn server, it allows me to login, but it shows just a white window.
So the 2nd connection i successfully blocked.
I want to show the 2nd user a messag though, but failed to far where and what I need to implement.

**Comment by CendioOssman** [comment]
The only place the protocol allows messages is during authentication failures. noVNC already shows such messages, so I'm afraid you'll have to see if you can configure your server to behave the right way. Right now it sounds like your server is accepting the second connection, but gives it a fake screen.
