### ISSUE TITLE
no image when embedded into a React component

### ISSUE THREAD

**Issue by pashazz** [novnc/noVNC#1100]
**Describe the bug**
I try to use noVNC in my React application. To do so, I use a modified version of `react-vnc-display` component. The original component uses 'novnc-node' which is outdated and it seems that the old version is slow in my setup (compared to `vnc_lite.html`. So I modified a `react-vnc-display` component so it looks like [this](https://github.com/pashazz/novnc-react-mwe/blob/master/src/VncDisplay.js).

So I try to use current noVNC from git and this is the log I get: [LOG](https://gist.github.com/pashazz/73f124ead4545cf4f68027581d8b3d4c)

I don't have any image at all.
 
To ease reproduction process I created a [minimal "working" example](https://github.com/pashazz/novnc-react-mwe).
**To Reproduce**
1. Get Minimal working example: 
2. Replace the URL

**Screenshots**
I am sure that the same input source  works via vnc_lite.html:
![image](https://user-images.githubusercontent.com/45922/42341288-408887ae-809b-11e8-8b7b-6ca42a0c9b29.png)

**Client (please complete the following information):**
 - OS: Linux Mint
 - Browser: firefox, chrome 
 - Browser version: 

**Server (please complete the following information):**
 - noVNC version: git master
 - VNC server: XenServer RFB console
 - WebSocket proxy: my own, but it works with vnc_lite.html anyway

**Comment by CendioOssman** [comment]
`novnc-node` is not ours and seem to be based on a very ancient version of noVNC. The official one is `@novnc/novnc`.

The problem with your example that you are giving a `<canvas>` to the `RFB` object. That method is no longer supported. Instead you have to give it a block element (e.g. a `<div>`).
