### ISSUE TITLE
the height of noVNC_canvas just only about 10px

### ISSUE THREAD

**Issue by zitanlin** [novnc/noVNC#1101]
We use noVNC in our production. We found noVNC work well in most of computers, but in some computer (eg. ThinkPad T420; Window NT 10.0; WOW64; Chrome/65.0.3325.181) it didn't work well. The heigth of noVNC_canvas just only about 10px, while in most of computers the height of noVNC_canvas is 540px.

It is too strange and why !

Screenshots
![screenshot](https://user-images.githubusercontent.com/23631975/42366936-136b9564-8135-11e8-84be-4b9917150f70.jpeg)

Client Environment :
    Computer: ThinkPad T420
    OS: Window 10
    Browser: Chrome ( Chrome/65.0.3325.181 )

VNC server: 
    Android device( screen size: 14 inch )

**Comment by CendioOssman** [comment]
This doesn't look like it is noVNC 1.0.0. Could you test with the stable release and see if you are getting the same issue?

**Comment by zitanlin** [comment]
@CendioOssman  thank you for you reply ! 

We use noVNC v0.6.2 in our production. I will update noVNC to the latest stable release version. 

But I’m curious about why it works well on most of computers while in this computer doesn’t? we mad lots of tests on different computers before publish application, but didn’t find this problem.

Did you encounter this problem?

We found the method "screenSize" in ui.js is called and the screen.offsetHeight value is 2px. This may be the reason why the height of noVNC_canvas just only about 10px. But I don't know why?

**Comment by zitanlin** [comment]
@CendioOssman   

when i modify the method "screenSize" in ui.js, just set the return value = {w: screen.offsetWidth, h: 540}. The problem will be resolved, but i find the mouse arrow is disappeared when i move mouse to the region of canvas.

**Comment by samhed** [comment]
I have some vague memory of seeing the behavior you describe many years ago.. but I'm afraid we cant help you with such an old version.
