### ISSUE TITLE
RFB connection code does not gracefully handle forced proxy authentication

### ISSUE THREAD

**Issue by calebj** [novnc/noVNC#1104]
**Describe the bug**
noVNC's connection handling does not account for some corporate proxies which force a retry with authentication on all requests. I attempted using the demo page [here](http://novnc.com/noVNC/vnc.html) to rule out anything else.

In the network log, most uncached requests on most sites (including the websocket for noVNC) appear as a 407 Proxy Authentication Required error followed by a 200 (or 204, if applicable). The first websocket connection reports an error with code 1006, but by the time the second attempt succeeds, the RFB code has already shut down the attempt, removed the open event handler, and displayed the connection failed error.

This would also happen when the app is loaded from an internal site or localhost, but an attempt is made to connect to an external websocket through any HTTP proxy that the browser hasn't yet authenticated to. For regular authentication, a username and password prompt will appear to the user and, if the credentials are entered, the browser will retry the request. For NTLM authentication (which is what is used in my case), the OS is used instead of a prompt, but it still has to attempt the request twice.

**To Reproduce**
1. Attempt to connect to websockify endpoint through a proxy that hasn't been authenticated to

**Expected behavior**
In cases where the browser retries the connection automatically, noVNC shouldn't consider connection errors to be permanent failure or shut down the overall connection attempt. I don't know what all of these cases these might be, but I know 407 is one of them, and that Discord works fine with this setup,

**Client (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox and IE 11
 - Browser version: ESR 52.8.0 and 11.2312.14393.0 respectively

**Server (please complete the following information):**
 - noVNC version: unknown (attempted using the [public demo](http://novnc.com/noVNC/vnc.html))
 - VNC server: unknown
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
I'm afraid I don't see any sane way we can support this. The browser has just told us the connection failed. It is not waiting for any authentication, or indicating in some way that we should try again.

Discord and other such services generally fall back to older methods, but that's not really an option for us.

**Comment by calebj** [comment]
I can confirm Discord is still using the websocket. For 401 errors, you can check the response headers for `WWW-Authenticate`. For 407, it's `Proxy-Authenticate` instead. Both headers will cause the browser to reuse cached credentials or asynchronously prompt the user. If they are not present, it simply fails.
