### ISSUE TITLE
psql -U noc-ps insert into users values('changeme','fa9beb99e4029ad5a6615399e7bbae21356086b3');

### ISSUE THREAD

**Issue by Sologigabit** [novnc/noVNC#1106]
Hello I need to change a password for a psql user with these commands but I can not write some keystrokes.
psql -U noc-ps
insert into users values('changeme','fa9beb99e4029ad5a6615399e7bbae21356086b3');
<ctrl+d>

how can copy paste this into noVNC  OS Shell, I don't find the keystroke   ('

![image](https://user-images.githubusercontent.com/35578253/42815352-6d946846-89c7-11e8-8f05-27b6bf45dd56.png)

**Comment by Sologigabit** [comment]
![image](https://user-images.githubusercontent.com/35578253/42815651-48399c3c-89c8-11e8-8611-52b889b73542.png)
Autor

**Comment by CendioOssman** [comment]
I assume it is Ctrl+D that isn't working? It's probably grabbed by the browser. We can't do much about that unfortunately, so what you'll have to do is use the Ctrl modifier from the menu. Enable Ctrl there. Press just D, and then disable the modifier from the menu again.

**Comment by Sologigabit** [comment]
I dont find this -> '

**Comment by Sologigabit** [comment]
its possible paste?

**Comment by ossman** [comment]
That should in the standard place. If it doesn't work then I'd say you have some server issue. Which server are you running?

Yes, noVNC has clipboard support. But you have to run the standard application, not the lite one. And your server must support it. Just use the clipboard icon on the toolbar.

**Comment by CendioOssman** [comment]
That should in the standard place. If it doesn't work then I'd say you have some server issue. Which server are you running?

Yes, noVNC has clipboard support. But you have to run the standard application, not the lite one. And your server must support it. Just use the clipboard icon on the toolbar.

**Comment by Sologigabit** [comment]
I am running NOC-PS on Proxmox KVM VM

**Comment by Sologigabit** [comment]
looks like is too old server has 5 years VM, but should be upgraded maybe installing a current Proxmox ver

**Comment by CendioOssman** [comment]
Then I think you'll have to talk to them. It's not a standard noVNC setup at that point.
