### ISSUE TITLE
Incorrect logic for disabling "Clip to Window" mode

### ISSUE THREAD

**Issue by patrakov** [novnc/noVNC#1110]
**Describe the bug**
"Clip to Window" setting does not make sense in the "Local Scaling" mode, and the UI does attempt to account for this fact by disabling the checkbox. However, the logic of disabling it is wrong.

**To Reproduce**
1. Go to http://novnc.com/noVNC/vnc.html
2. Click on 'Settings'.
3. Fill out the host, port, and websocket path under Advanced Settings, to the values of a VNC server with a big screen (that does not fit without downscaling).
4. Set the "Scaling Mode" to "Local Scaling".
5. Press the "Connect" button, see the screen.
6. Without disconnecting, set the "Scaling Mode" to "None".
7. Check the "Clip to Window" checkbox, the hand button (for moving/dragging the viewport) should appear.
8. Press the "Move/Drag Viewport" button. Drag the viewport.
9. Set the "Scaling Mode" back to "Local Scaling".
10. See the unexpected behavior.

**Expected behavior**
The "Move/Drag Viewport" should disappear, and drags should drag objects on the remote screen.

**Actual behavior**
It doesn't disappear, and attempts to drag anything on the VNC screen fail because noVNC still thinks we are going to drag the viewport.

**Client (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chromium
 - Browser version: Version 67.0.3396.99 (Official Build) Arch Linux (64-bit)

**Server (please complete the following information):**
 - noVNC version: whatever is on novnc.com, also reproducible with f90c2a6
 - VNC server: any (tested with x11vnc)
 - WebSocket proxy: websockify

**Comment by samhed** [comment]
Thank you for the good bug report! I'll have a look.

**Comment by samhed** [comment]
@patrakov could you verify that #1118 fixes your issue?

**Comment by patrakov** [comment]
Yes, the issue is fixed. Thanks!

**Comment by samhed** [comment]
Good, thanks for testing.
