### ISSUE TITLE
Scrollbars are sometimes shown in "Local scale" mode

### ISSUE THREAD

**Issue by patrakov** [novnc/noVNC#1111]
**Describe the bug**
The "Local Scale" mode is supposed to scale the remote screen to fit the browser window. Unfortunately, sometimes it doesn't fit by a fraction of a pixel, and scrollbars appear.

**To Reproduce**
1. Go to your favorite noVNC installation
2. Set the browser zoom to something different than 100%
3. Set the scaling mode to "Local Scale"
4. Connect
5. Play with the browser zoom and window size
6. See a scrollbar

**Expected behavior**
No scrollbar.

**Screenshots**
Well, no screenshots, but some copy-paste from the JS console just to explain what happens here :)

```
> var c = document.getElementsByTagName('canvas')[0];
> c.getBoundingClientRect()
DOMRect {x: 93.1971206665039, y: 0, width: 1768.9903564453125, height: 995, top: 0, …}
> c.offsetHeight
995
> var p = c.parentElement;
> p.getBoundingClientRect()
DOMRect {x: 0, y: 0, width: 1970, height: 994.6154174804688, top: 0, …}
> p.offsetHeight
995
```
See - _screenSize() would think we have a 1970x995 screen, but in fact we have 1970x994 + some fraction of a logical pixel, and it should either think in terms of fractional pixels, or return 1970x994. In other words, the problem is that offsetHeight sometimes rounds up.

**Client (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chromium
 - Browser version: Version 67.0.3396.99 (Official Build) Arch Linux (64-bit)

Also reproducible in Firefox 61.0.1 with 300% zoom

**Server (please complete the following information):**
 - noVNC version: f90c2a6 with some irrelevant local modifications
 - VNC server: any (tested with x11vnc)
 - WebSocket proxy: websockify

**Additional context**
I was able to fix this problem in Chromium like this, but did not test in anything except Firefox and Chromium:

```
diff --git a/core/rfb.js b/core/rfb.js
index 3150082..9dc32b2 100644
--- a/core/rfb.js
+++ b/core/rfb.js
@@ -549,8 +549,9 @@ RFB.prototype = {
 
     // Gets the the size of the available screen
     _screenSize: function () {
-        return { w: this._screen.offsetWidth,
-                 h: this._screen.offsetHeight };
+        const r = this._screen.getBoundingClientRect();
+        return { w: Math.floor(r.width),
+                 h: Math.floor(r.height) };
     },
 
     _fixScrollbars: function () {
```

**Comment by patrakov** [comment]
For the record, the environment here is MATE desktop, with DPI set to 120. So, by default (with 100% zoom), in Chromium, window.devicePixelRatio is 1.3 here, not sure why. And 1.25 in Firefox.

**Comment by patrakov** [comment]
also in display.js, in _rescale, I would say that the use of round() is questionable

**Comment by patrakov** [comment]
Possibly better patch:

```
diff --git a/core/display.js b/core/display.js
index 7360e61..15357f1 100644
--- a/core/display.js
+++ b/core/display.js
@@ -533,8 +533,8 @@ Display.prototype = {
         //                   style width to a number, the canvas is cleared.
         //                   However, if you set the style width to a string
         //                   ('NNNpx'), the canvas is scaled without clearing.
-        const width = Math.round(factor * vp.w) + 'px';
-        const height = Math.round(factor * vp.h) + 'px';
+        const width = factor * vp.w + 'px';
+        const height = factor * vp.h + 'px';
 
         if ((this._target.style.width !== width) ||
             (this._target.style.height !== height)) {
diff --git a/core/rfb.js b/core/rfb.js
index 3150082..81c6115 100644
--- a/core/rfb.js
+++ b/core/rfb.js
@@ -549,8 +549,9 @@ RFB.prototype = {
 
     // Gets the the size of the available screen
     _screenSize: function () {
-        return { w: this._screen.offsetWidth,
-                 h: this._screen.offsetHeight };
+        const r = this._screen.getBoundingClientRect();
+        return { w: r.width,
+                 h: r.height };
     },
 
     _fixScrollbars: function () {
```

Yes, fractional pixels.

**Comment by CendioOssman** [comment]
Yeah, I guess we tried to ignore the problem of fractional pixels. :)

Your patch is a good start. It just needs a few more additions as there are some parts that really need integer pixels, so we need to use `Math.floor()` there. I'll try to get a PR up.

**Comment by mholzel** [comment]
Where is the local scale option? I don't even see how to enable it?

**Comment by patrakov** [comment]
![image](https://user-images.githubusercontent.com/2943163/53570365-1ecf3d80-3b88-11e9-9ea1-bea50a534eb5.png)
