### ISSUE TITLE
handler exception: [Error 104] Connection reset by peer

### ISSUE THREAD

**Issue by pythonmao** [novnc/noVNC#1115]
I start no vnc server with port 6080, it is ok.
But when I start no vnc server with port 6802/6803 or other ports, I can't access it successfully, the error message as below,
"handler exception: [Error 104] Connection reset by peer"

**Comment by pythonmao** [comment]
I start vnc server with  port 6802/6803 or other ports, it is ok. But if the ports is used by no vnc server, they will failed.

**Comment by CendioOssman** [comment]
Could you share exactly how you are starting the VNC and websockify servers?

**Comment by pythonmao** [comment]
I start no vnc server with command “./utils/launch.sh --vnc localhost:$VNC_PORT --listen $NO_VNC_PORT“。

**Comment by pythonmao** [comment]
for example，if the localhost is 10.240.xxx.xxx and the port is 6082, I can access no vnc server in network segment 10.240.xxx.xxx, but I can't access it in other network segment, 10.57.xxx.xxx, 10.230.xxx.xxx.

if the port is 6080, I can access no vnc server in all network segment.

**Comment by CendioOssman** [comment]
What error are you getting in the browser console when it fails? And are you seeing any log output on the server?

**Comment by pythonmao** [comment]
Error log on the server is "handler exception: [Error 104] Connection reset by peer",
and error log in the browser is "Something went wrong, connection is closed".

**Comment by CendioOssman** [comment]
We need the error message from the browser, not what is displayed on screen. If you look under developer tools you will find a section called "Console". Please let us know what that says when you try to connect.

**Comment by pythonmao** [comment]
[](url)
![browser](https://user-images.githubusercontent.com/8006192/43814007-ce82c03c-9afa-11e8-9b95-47bcbe78d484.PNG)
![server](https://user-images.githubusercontent.com/8006192/43814009-cef0426a-9afa-11e8-890d-3faac309d9d5.PNG)

**Comment by pythonmao** [comment]
[
![browser](https://user-images.githubusercontent.com/8006192/43814053-02cc167c-9afb-11e8-964d-2eea5ddb8b8f.PNG)
![server](https://user-images.githubusercontent.com/8006192/43814054-0335e872-9afb-11e8-905d-671c53eb96ef.PNG)

](url)### If I use port 6080, it is ok.

**Comment by pythonmao** [comment]
[
![browser](https://user-images.githubusercontent.com/8006192/43814112-46da5e14-9afb-11e8-8793-eba4e1bd2fd6.PNG)
](url)

**Comment by pythonmao** [comment]
[
![server](https://user-images.githubusercontent.com/8006192/43814116-4f07e8ea-9afb-11e8-8f0f-d60a7c65b327.PNG)
](url)

**Comment by pythonmao** [comment]
If I use port 6080, it is ok.

**Comment by samhed** [comment]
None of those screenshots show the browser console which @CendioOssman asked for. It looks like you are using Firefox, I believe the default keyboard shortcut for opening the browser console is `Ctrl+Shift+J`.

**Comment by pythonmao** [comment]
I use chrome to test it again.
[
![chrome](https://user-images.githubusercontent.com/8006192/43827712-1a9b6e92-9b2d-11e8-8876-39fc62d6158d.PNG)
](url)

**Comment by CendioOssman** [comment]
Okay, so you are getting connection reset from both sides. I'm afraid this indicates that something on the network is forcefully terminating your connections. That would fit with the fact that only some ports are affected.

You will need to look for a restrictive firewall that needs to be configured to allow these connections. I'm afraid there isn't anything we can do more.
