### ISSUE TITLE
How to access information in the event  object returned to the connected and disconnect events

### ISSUE THREAD

**Issue by jeffforbes** [novnc/noVNC#1116]
I am examining the event object returned in the connected function with chrome debugger tools.
I do not see where the information is stored.
e.detail object is there, but there is no e.detail.name which is used in a different function.
I am afraid that I am a novice in this aspect of javascript and need some guidance as to how to get the
rfb information that is passed in the event object.

**Comment by DirectXMan12** [comment]
`connect` doesn't actually have an details, so it's not weird that you can't find name on that event.  Looks like the `updateDesktopName` method has that detail, though.  Can you point at the spot that you were looking at, or what you're trying to do?

**Comment by jeffforbes** [comment]
Since updatestate has been replaced by the event functions, I need the rfb information that called the connected and disconnected functions. In your vnc_lite.html, I would like to be able to get the rfb object from the event object "e" in this example.  If that is not possible, then the target name. 
        function connected(e) {
            document.getElementById('sendCtrlAltDelButton').disabled = false;
            if (WebUtil.getConfigVar('encrypt',
                                     (window.location.protocol === "https:"))) {
                status("Connected (encrypted) to " + desktopName, "normal");
            } else {
                status("Connected (unencrypted) to " + desktopName, "normal");
            }
        }

**Comment by CendioOssman** [comment]
Unfortunately there is no such information on the event object. However, as mentioned in your previously opened issues, [`this`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this) will be pointing at the RFB object.

**Comment by jeffforbes** [comment]
OK, I have been able to use "this" to get the in target name for the rfb associated with the event.
However, the updatedesktopName function is not being called and the event.detail.name is not set in the event object passed to the connected function. Is this the expected behavior?  In previous versions of noVNC, the desktop name is what is being returned in this._fb_name.

**Comment by samhed** [comment]
If you aren't receiving the desktopname event, something is very wrong with your version of noVNC. It should always be dispatched at the start of new connections. Make sure your application code listens to this event properly.

Look here:

https://github.com/novnc/noVNC/blob/master/app/ui.js#L1034

> In previous versions of noVNC, the desktop name is what is being returned in this._fb_name.

just so you know any variables prefixed with '_' are internal and not part of the API.

**Comment by samhed** [comment]
Closed due to no response.
