### ISSUE TITLE
RFB target type

### ISSUE THREAD

**Issue by jeffforbes** [novnc/noVNC#1120]
The current API documentation states that the target for the rfb object is a block HTMLElement.
Previous versions used a canvas element as the target. In our application of noVNC, we used multiple
canvases in one div, with each canvas connected to a different rfb. We would hide or show the desired canvas in the single div. 

Is it still possible to get a RFB to attach to a predefined canvas or does it have to create its own in a HTMLElement? I was not able to get the rfb to attach to one of our canvases, but it is likely that I was missing something. If we can't have the rfb attach to a predefined canvas, then we would have to stay with the previous version of noVNC. Am I missing something?

**Comment by samhed** [comment]
> Is it still possible to get a RFB to attach to a predefined canvas

No, it will always create it's own.

> If we can't have the rfb attach to a predefined canvas, then we would have to stay with the previous version of noVNC. Am I missing something?

Can't you just have multiple container divs which you show or hide just like you did with the different canvases as before?

**Comment by samhed** [comment]
Closed due to no response.
