### ISSUE TITLE
Add Passive event listeners to better scroll on touch devices 

### ISSUE THREAD

**Issue by al3x609** [novnc/noVNC#1123]
scrolling performance in all touch events
https://github.com/novnc/noVNC/blob/862967e08950c2a9c71529420321395737e2734d/app/ui.js#L259 
**Mayble solution**
`.addEventListener('touchstart', UI.activateControlbar, , {passive: true}); `

**Comment by samhed** [comment]
Yeah, that looks like it would be useful! Did you try it and see any improvements?

Could you open a pull request that includes this fix along with a code comment in the "activateControlbar" function mentioning that we have promised that it won't call preventDefault()?

**Comment by samhed** [comment]
#1124

**Comment by CendioOssman** [comment]
This is a messy area. See also #934, where some browsers have passive as the default.

What we probably need to do is to be explicit in all calls for `addEventListener()` and not rely on defaults.

**Comment by samhed** [comment]
ah, yes that sounds good

**Comment by samhed** [comment]
See reasoning in #1124, this doesnt help us since we don't do any passive scrolling in noVNC.
