### ISSUE TITLE
Travis tests fail on Safari 11

### ISSUE THREAD

**Issue by samhed** [novnc/noVNC#1125]
A large number of our unit tests fail in Travis on Safari 11. The other platforms are working fine. The error in Safari is "Value is not a sequence". It seems like this is a common issue with Safari 11 and disabling a "WebDriver" extension in Safari seems to help.

The question is whether we should wait and see if Saucelabs fixes this on their Safari 11 machines or if we should change to for example Safari 12 for these tests?

**Comment by DirectXMan12** [comment]
probably just change to safari 12 -- I'd rather having some working safari tests

**Comment by DirectXMan12** [comment]
:-/ that's frustrating.  Is there a bug filed with Sauce?

**Comment by samhed** [comment]
I have filed a support request with Sauce, didn't receive a response yet.

**Comment by samhed** [comment]
Fixed with 6d1c036
