### ISSUE TITLE
copy paste large data

### ISSUE THREAD

**Issue by babarismail** [novnc/noVNC#1130]
Is there a copy/paste limit for large data? We were having some issues with copy pasting large data so I want to know if there is a copy paste limit?

Also, is there any fix in the first stable release 1.0.0?

Thanks!

**Comment by samhed** [comment]
There were a number of issues with large clipboards, both copying and pasting with noVNC 1.0.0. The fixes for these bugs haven't made it into any release yet. You will have to wait for the next release or use the code from master.

On master there are no limits imposed by noVNC, it will all depend on your server.
