### ISSUE TITLE
what is the current large data copy/paste behavior? weird behavior observed

### ISSUE THREAD

**Issue by babarismail** [novnc/noVNC#1133]
When I try to paste large data into the vm, I don't see the correct behavior. I would expect that the data would be pasted but I see one of the two behaviors:

1. Sometimes nothing will happen. No data will be pasted
2. Sometimes last copied data which was below the 10240 byte limit will get pasted.

Can someone explain what the intended behavior? I am referring to this change:
https://github.com/novnc/noVNC/commit/cfe1e44ed707976f2dd77da83c2e26264a59593f

**Comment by samhed** [comment]
Your server probably doesn't allow receiving large clipboards. What VNC server are you using?

Note also that most servers will log something in these cases.

**Comment by babarismail** [comment]
I will check and get back to you on that. 

What is the expected behavior though? Should all data get copied over?

**Comment by babarismail** [comment]
the copy paste seems to be working now for me. Closing this issue.
