### ISSUE TITLE
Embedding issues

### ISSUE THREAD

**Issue by asim-richierich** [novnc/noVNC#1134]
After password authentication the canvas is not rendered, i just get a full grey screen  (no SSH small black screen as expected) which is the background color of the NoVNC page (image below).
https://imgur.com/a/dIvKFsQ

I am able to run noVNC and access the remote server with the same server (host) and port details on the online demo here : http://novnc.com/noVNC/vnc.html?host=HOST&port=PORT&logging=debug hosted by novnc.com, passing the same host and port number(image below),

https://imgur.com/a/B837Aj3

I am using vncterm package provided by proxmox https://git.proxmox.com/?p=vncterm.git;a=summary for vnc server, command below :
vncterm  -rfbport 5902 -timeout 20 -passwd 123456 -c /usr/bin/dtach -A /var/run/dtach/lxc11 -r winch -z lxc console lxc11

Using linux websockify package v0.8.0 for tcp/websockets to vnc proxy
command below : 
websockify 6902 1X.XX.XX.X:5902

I am also able access VNC using external VNC viewers on the VNC port.

**Console debugging messages Given below :** 
```
>> Keyboard.allKeysUp
keyboard.js:299 << Keyboard.allKeysUp
rfb.js:149 >> RFB.constructor
display.js:39 >> Display.constructor
display.js:69 User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
display.js:166 Setting viewport to full display region
display.js:79 << Display.constructor
display.js:166 Setting viewport to full display region
rfb.js:255 << RFB.constructor
rfb.js:640 New state 'connecting', was ''.
rfb.js:402 >> RFB.connect
rfb.js:404 connecting to ws://1XX.XX.XXX.X:6902/websockify
rfb.js:428 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
_connect @ rfb.js:428
_updateConnectionState @ rfb.js:653
rfb.js:430 << RFB.connect
[Violation] 'setTimeout' handler took 51ms
websock.js:198 >> WebSock.onopen
websock.js:200 Server choose sub-protocol: binary
rfb.js:209 Starting VNC handshake
websock.js:204 << WebSock.onopen
keyboard.js:295 >> Keyboard.allKeysUp
keyboard.js:299 << Keyboard.allKeysUp
rfb.js:816 Server ProtocolVersion: 003.008
rfb.js:856 Sent ProtocolVersion: 003.008
rfb.js:883 Server security types: 2,19
rfb.js:907 Authenticating using scheme: 2
ui.js:1151 Server asked for a password
credentials @ ui.js:1151
_listeners.get.forEach @ eventtarget.js:36
dispatchEvent @ eventtarget.js:35
_negotiate_std_vnc_auth @ rfb.js:985
_negotiate_authentication @ rfb.js:1118
_init_msg @ rfb.js:1307
_handle_message @ rfb.js:736
_recv_message @ websock.js:287
rfb.js:1136 Authentication OK
rfb.js:1206 Screen: 744x400, bpp: 8, depth: 8, big_endian: 0, true_color: 0, red_max: 7, green_max: 7, blue_max: 3, red_shift: 0, green_shift: 3, blue_shift: 6
rfb.js:1222 Server native red-shift is not 16
_negotiate_server_init @ rfb.js:1222
_init_msg @ rfb.js:1318
_handle_message @ rfb.js:736
_recv_message @ websock.js:287
rfb.js:1226 Server native blue-shift is not 0
_negotiate_server_init @ rfb.js:1226
_init_msg @ rfb.js:1318
_handle_message @ rfb.js:736
_recv_message @ websock.js:287
mouse.js:252 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
grab @ mouse.js:252
_negotiate_server_init @ rfb.js:1237
_init_msg @ rfb.js:1318
_handle_message @ rfb.js:736
_recv_message @ websock.js:287
rfb.js:640 New state 'connected', was 'connecting'.
[Violation] 'message' handler took 168ms
[Violation] Forced reflow while executing JavaScript took 56ms
rfb.js:1491 First FBU latency: 308
rfb.js:2523 >> set_cursor
rfb.js:2542 << set_cursor
keyboard.js:295 >> Keyboard.allKeysUp
keyboard.js:299 << Keyboard.allKeysUp
keyboard.js:295 >> Keyboard.allKeysUp
keyboard.js:299 << Keyboard.allKeysUp
```
I have also noticed that "Timing of full FBU" and "full FBU round-trip, cur: " are not printed in failure case (my implementation) in console debugging mode.

I have tried running NoVNC on both locahost and uploaded on server, both are not working as expected. (running apache)

**Client:**
 - Windows 10 
 - Browser:  chrome, firefox (latest version)

**Server:**
 - noVNC version:  e15950a (commit)
 - VNC server: vncterm
 - WebSocket proxy:  websockify (linux)
- Host OS : Ubunutu

**Comment by samhed** [comment]
Hi @asim-richierich 

You mention "embedding" in your title, but never touch upon this in detail. In what way are you embedding noVNC?

**Comment by asim-richierich** [comment]
Hi @samhed 

I have uploaded the code my webserver in a new directory /novnc and I am just hitting example.com/novnc/vnc.html (without any manipulation) with the parameters required in the URL.

I was able to connect and access VNC when I use all the resources (js files mainly) from the demo here : http://novnc.com/noVNC/vnc.html

But I see to many changes in the code running on demo from the github code.

**Comment by samhed** [comment]
Ok, so you haven't modified noVNC in any way.

Does your VNC server logs give any clues? You said that clicking eventually results in a disconnect?

**Comment by asim-richierich** [comment]
>>Ok, so you haven't modified noVNC in any way.
Not modified, it was uploaded as is.

>>Does your VNC server logs give any clues? 
The webscokfiy shows connected without any error:

X.X.X.X- - [26/Aug/2018 19:54:24] X.X.X.X: Plain non-SSL (ws://) WebSocket connection
X.X.X.X - - [26/Aug/2018 19:54:27] X.X.X.X: Version hybi-13, base64: 'False'
X.X.X.X - - [26/Aug/2018 19:54:30] connecting to: X.X.X.X:5902

>>You said that clicking eventually results in a disconnect?
After getting a successful connection message when clicked on the screen multiple times novnc shows disconnect message with encoding error in console.

Failed while connected: Unsupported encoding (encoding: 537114662)

Encoding stats for this connection: rfb.js:460:9
    [unknown encoding -239]: 1 rects rfb.js:464:17
Encoding stats since page load: rfb.js:468:9
    [unknown encoding -239]: 1 rects rfb.js:469:43
<< RFB.disconnect

**Comment by asim-richierich** [comment]
Hi @samhed 

The vnc terminal emulator does not generate any log. I tried to log output to std err or by supplying a valid xterm arg -lf but it seems that logging has been disabled internally by proxmox.
We are bound to use this "vncterm" package to support VNC for LXC.

We can use the old code (for novnc) hosted on novnc.com for our project unless there are no security issues.

If you want to have a closer look I can provide the access to the test server.
If you want me to debug further in NoVNC code then please let me know.

**Comment by samhed** [comment]
@CendioOssman any idea what change could have caused this? I assume novnc.com is running version 1.0

**Comment by CendioOssman** [comment]
Not sure if it's a code change yet.

@asim-richierich, could you try installing noVNC 1.0.0 on your server and see if you get the same issue? Make sure you've reset your browser cache.

**Comment by asim-richierich** [comment]
Hi @CendioOssman 

Thanks a lot, that works.
@samhed please close this issue.

**Comment by samhed** [comment]
Well, that just enforces the theory that the problem is caused by a code change post v1.0. I understand that you are no longer in need of a solution, but unless we get to the bottom of this, future releases won't work for you.

**Comment by asim-richierich** [comment]
You are absolutely right.
What can I do to dig in deep to find the cause of the issue ?

**Comment by CendioOssman** [comment]
Git will help you quite a bit though. Have a look at the `git bisect` command.

**Comment by asim-richierich** [comment]
>>Well, since you ask.. If you are up to it, you can checkout commit by commit since the release and see when the problem starts happening. It's quite tedious however


>>Git will help you quite a bit though. Have a look at the git bisect command.

Thank you for the help guys.
I will check and revert.

**Comment by CendioOssman** [comment]
No response. Closing.
