### ISSUE TITLE
Win+space on Windows10 leads to incorrect keyboard work

### ISSUE THREAD

**Issue by hard8candy** [novnc/noVNC#1136]
Hello everybody!
We are using noVNC library inside of our application and I noticed an issue with a keyboard on Windows 10.

**Describe the bug**
My host system is Windows 10 and I open noVNC console in the browser to get access to remote Windows 10. After I press Win+space a keyboard stops to type normally and any key pressing leads to launching programs or just ignored.

**To Reproduce**
In my environment I do the following steps:
1. Open noVNC console in the browser on Windows 10. Remote machine is running Windows 10 as well.
2. Open Notepad on remote machine, start typing something. Everything is ok.
3. Press Win+space and continue typing.
4. You can't type normally, some keys are ignored, other keys run different Windows programs.
5. But if you click somewhere outside noVNC tab and then return back to remote machine, you can type normally again.

**Expected behavior**
As Win+space is default shortcut to change keyboard layout (for Windows10) I expect it to change keyboard layout on remote Windows10 as well.

**Client (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox
 - Browser version: Chrome 69.0.3497.81, Firefox 62.0

**Server (please complete the following information):**
 - noVNC version: Master downloaded from Sep 6
 - VNC server: QEMU
 - WebSocket proxy: websockify-like
 
**Additional context**
Firefox logs:

`onmousebutton down, x: 385, y: 196, bmask: 1 mouse.js:98:9`
`onmousebutton up, x: 385, y: 196, bmask: 1 mouse.js:98:9`
`onkeyevent down, keysym: 115 , code: KeyS keyboard.js:54:9`
`Sending key (down): keysym 115, scancode 31 rfb.js:374:13`
`onkeyevent up, keysym: 115 , code: KeyS keyboard.js:54:9`
`Sending key (up): keysym 115, scancode 31 rfb.js:374:13`
`onkeyevent down, keysym: 115 , code: KeyS keyboard.js:54:9`
`Sending key (down): keysym 115, scancode 31 rfb.js:374:13`
`onkeyevent up, keysym: 115 , code: KeyS keyboard.js:54:9`
`Sending key (up): keysym 115, scancode 31 rfb.js:374:13`
`onkeyevent down, keysym: 65515 , code: MetaLeft keyboard.js:54:9`
`Sending key (down): keysym 65515, scancode 57435 rfb.js:374:13`
`onkeyevent down, keysym: 1753 , code: KeyS keyboard.js:54:9`
`Sending key (down): keysym 1753, scancode 31 rfb.js:374:13`
`onkeyevent up, keysym: 1753 , code: KeyS keyboard.js:54:9`
`Sending key (up): keysym 1753, scancode 31 rfb.js:374:13`
 `Keyboard.allKeysUp keyboard.js:295:9`
 `Keyboard.allKeysUp keyboard.js:299:9`
 `Keyboard.allKeysUp keyboard.js:295:9`
`onkeyevent up, keysym: 65515 , code: MetaLeft keyboard.js:54:9`
`Sending key (up): keysym 65515, scancode 57435 rfb.js:374:13`
 `Keyboard.allKeysUp`

So, I pressed s,s,Win+spase,s.
The last 's' started windows search assistant.
What I can see from logs is that when I press Win+space only 'down' signal for keysym: 65515 is received. Like button was pressed and wasn't released. But when I click outside the noVNC tab (for example somewhere on developer tools or on my desktop) 'up' signal for 65515 is immediately received (see the end of logs). If I return cursor back to remote machine, keyboard starts type normally.

**Comment by CendioOssman** [comment]
Yeah, this behaviour would result in a stuck Win key. I think this is just a shitty behaviour by Windows. I suppose we'll have to do a workaround like we do for Firefox' stuck Alt bug.

First we should probably do some debugging and see if there is some stray `blur` event we've overlooked.

I'd also like to compare with TigerVNC's client to see how the raw system events look like. It might be some bad behaviour by the browsers here.

**Comment by CendioOssman** [comment]
Just to be clear though, you won't be getting Win+Space in your remote machine since we never see the event for Space. Such is the nature of the browser or OS grabbing keys.

**Comment by CendioOssman** [comment]
Alright, so I tested with TigerVNC and it confirms the behaviour here. Windows only sends a single event (Windows key down). There are no focus events or anything useful we can trigger on.

I'm afraid I don't see any decent fix here. So I think well have to live with this until Microsoft improves the behaviour. :disappointed:

**Comment by hard8candy** [comment]
Ah, I see. Thank you for your investigation.
Do you think it makes sense to report this bug to Microsoft somehow?

**Comment by CendioOssman** [comment]
Feel free. Although I wouldn't even know where. :)

**Comment by samhed** [comment]
Aight, as @CendioOssman wrote, there's not much we can do here. I'm closing this issue.
