### ISSUE TITLE
scaling of display inside of an iframe seems not to work.

### ISSUE THREAD

**Issue by jeffforbes** [novnc/noVNC#1137]
We have a div like shown below:

    <div id="virtuals">
      <div id="virt17143" width="834" height="634" class="clvmEntry clVMvisible">
         <h1 id="vmStatusMsg17143" class="clvmStatusMsg"></h1>
         <div id="vmViewerCont17143">
             <div style="display: flex; width: 100%; height: 100%; overflow: auto; background-color: rgb(40, 40, 40);">
                 <canvas style="margin: auto; outline: currentcolor none medium; flex-shrink: 0; width: 1440px; height: 900px; cursor: none;" width="1440" height="900" tabindex="-1"></canvas>
             </div>
         </div>
      </div>
    </div>

The HTMLElement target is, in this case, vmViewerCont17143.
The width and height of the canvas is coming from the size of the screen in the VNC server.
Previously we used the display scaling functions. In the new internal API definitions this should be:
 rfb._display.scale = scaleFac;
where scaleFac is 1.0 or less.
I have not been able to get this to work with noVNC 1.0

I also tried the external resize method with no change.
When I turn on the scale method, there is no screen output.

Please advise.

**Comment by samhed** [comment]
Does it work if you don't have the display in an iframe?

PS: I edited your post to mark the HTML as code to make it visible on github.

**Comment by CendioOssman** [comment]
I guess that code is a dump from the browser's inspector? What does it look like with the scaling enabled?

And you must do `rfb.scaleViewport = true;`. Accessing `rfb._display` is unsupported.

**Comment by jeffforbes** [comment]
When 
rfb.scaleViewport = true;
there is not screen output.
That is why I tried the unsupported rfb._display.scale method which worked in version 0.7.
I am testing in a display outside of an iframe and will report the results.

**Comment by jeffforbes** [comment]
I think that the problem was that I had rfb.resizeSession = true;
When I set rfb.resizeSession = false and rfb.scaleViewport = true, then
 rfb._display.scale = scaleFac works as expected. If I don't set  rfb._display.scale
to some value, then there is no screen output.

The target HTML Element in the example above is vmViewerCont17143.
Do I need to explicitly set the width and height of this div to get the scaling to work without
setting  rfb._display.scale?

**Comment by CendioOssman** [comment]
Actually, yes you do. The `<div>` needs to have some size enforced in order for scaling to work. Without that the `<div>` will be resized to the content, and with scaling the content tries to resize to the `<div>`. So you get a feedback loop there that cannot work.

**Comment by samhed** [comment]
Right, the RFB object don't provide any API for display.scale(), only display.autoscale(). I was wrong

**Comment by jeffforbes** [comment]
I was able to get the scaling to work when I put the height and width in the style for the vmViewerCont17143 element. It also works better than using the _display.scale variable.
Thanks
