### ISSUE TITLE
CopyRect wrong results

### ISSUE THREAD

**Issue by clbr** [novnc/noVNC#1139]
**Describe the bug**
When a frame sends many CopyRects, the results in noVNC are wrong. Standalone VNC clients do not show the issue. I wonder if packets were dropped, or somehow processed wrong.

I made a recording using the Python websockify proxy, seeing if I can attach it here.

Master is broken in Firefox as of 9881899 so I had to go back a bit to find a working version, these were from ce6287574.

**To Reproduce**
1. Go to tests/vnc_playback.html?data=new.js (with new.js in recordings/)
2. Realtime, 1 run
3. Click start, scroll down to watch

**Expected behavior**
The text should not be corrupted.

**Screenshots**
TBA

**Client (please complete the following information):**
 - OS: Xubuntu 18.04
 - Browser: Firefox
 - Browser version: 61

**Server (please complete the following information):**
 - noVNC version: ce6287574
 - VNC server: Modified TigerVNC
 - WebSocket proxy: python websockify, git master, but also happens using the C version

**Additional context**
-

**Comment by clbr** [comment]
I couldn't attach it here. Uploaded to https://anonfile.com/YaZ992h5b1/new.js_xz

**Comment by CendioOssman** [comment]
Odd. But I cannot see anything wrong with our processing. The data from the recording shows some very odd CopyRect rectangles and it's difficult to tell the proper stuff from the noise.

Just to clarify, the server is TigerVNC's Xvnc? The patterns do not match the behaviour of that server. How is it modified?

Can you describe how to reproduce this?

**Comment by clbr** [comment]
Yes, Xvnc, but the modifications are proprietary. Targeting bandwidth savings, it prefers to copy existing data whenever the resulting stream would be smaller.

When I connect to the same session as in the recording via TigerVNC's vncviewer or Remmina, and do the same scrolling with the mouse wheel, the text is not corrupted. It's possible there's bugs in the server logic, but given the two standalone clients work and novnc shows issues, I'm lead to think it's the client, or possibly the websocket proxy.

So I gather it's uncertain whether the recording is correct? Is there any way to play it back on any standalone client to compare, or otherwise verify it separately from novnc, so that it could be used as "ground truth"?

**Comment by CendioOssman** [comment]
No, I'm afraid I'm not aware of any parser for these recordings.

TigerVNC is GPL, so if you are distributing that Xvnc then those modifications are also licensed under the GPL. It should be no issue sharing them.

And given the description it sounds like those modifications are the source of the issue. It will be difficult for us to diagnose things without them.

**Comment by clbr** [comment]
Server-side issue after all. As for why only noVNC and not the standalone clients, noVNC was sufficiently slow to cause update backlog, which hadn't been sufficiently tested.
