### ISSUE TITLE
Uncaught RangeError: Source is too large

### ISSUE THREAD

**Issue by jeremypmann** [novnc/noVNC#1141]
TightVNC server 1.8.0-5-el7
Latest pull of noVNC from GitHub
CentOS 7.5

When connecting via latest versions of Chrome/Firefox/Edge I receive this message after entering my VNC password:

noVNC encountered an error:

Uncaught RangeError: Source is too large
http://10.11.8.7:6080/core/util/cursor.js:104:22
RangeError: Source is too large
    at Uint8ClampedArray.set (<anonymous>)
    at Cursor.change (http://10.11.8.7:6080/core/util/cursor.js:104:22)
    at RFB._handleCursor (http://10.11.8.7:6080/core/rfb.js:1541:22)
    at RFB._handleRect (http://10.11.8.7:6080/core/rfb.js:1501:29)
    at RFB._framebufferUpdate (http://10.11.8.7:6080/core/rfb.js:1481:23)
    at RFB._normal_msg (http://10.11.8.7:6080/core/rfb.js:1397:28)
    at RFB._handle_message (http://10.11.8.7:6080/core/rfb.js:700:31)
    at Websock._recv_message (http://10.11.8.7:6080/core/websock.js:287:33)

**Comment by dinki** [comment]
I'm getting the exact same error but I'm running in a Docker under Debian.  Also connecting to TightVNC server

**Comment by al3x609** [comment]
![image](https://user-images.githubusercontent.com/4086644/45645580-8a17ce00-ba86-11e8-9bbe-bc9330eb171b.png)

same bug

**Comment by LicoMonch** [comment]
Git almost the same with the latest git pull a few minutes before this post:
(Server is TigerVNC 1.9 & other clients still work on the same connection)

RangeError: invalid array length
http://localhost:6080/core/util/cursor.js:104:13
change@http://localhost:6080/core/util/cursor.js:104:13
_handleCursor@http://localhost:6080/core/rfb.js:1541:9
_handleRect@http://localhost:6080/core/rfb.js:1501:24
_framebufferUpdate@http://localhost:6080/core/rfb.js:1481:18
_normal_msg@http://localhost:6080/core/rfb.js:1397:23
_handle_message@http://localhost:6080/core/rfb.js:700:26
_recv_message@http://localhost:6080/core/websock.js:287:13

**Comment by CendioOssman** [comment]
Should be fixed as of 679535ec29deec544b24f8b214a18f517e29c625.

**Comment by LicoMonch** [comment]
works for me

**Comment by al3x609** [comment]
bug fixed for me too.
