### ISSUE TITLE
Source is too large at Uint8Array

### ISSUE THREAD

**Issue by omertombul** [novnc/noVNC#1143]
Hi I have this weird error when I move the cursor , I tried it on 2 other servers and it works fine but I would like to know what is the cause.

<img width="537" alt="screen shot 2018-09-19 at 2 02 59 pm" src="https://user-images.githubusercontent.com/14808977/45772048-bfeabd00-bc14-11e8-9f6e-8a750deb1dbf.png">

**Comment by CendioOssman** [comment]
This was recently fixed, so please upgrade and it should go away. See #1141 for more details.
