### ISSUE TITLE
Unable to connect to QEMU websockets via TLS self signed certificates - noVNC TLS configuration error

### ISSUE THREAD

**Issue by abraunegg** [novnc/noVNC#1144]
**Describe the bug**
Prior to QEMU 2.5.x, it was possible to use noVNC to connect to QEMU instances where websockets was enabled & via TLS, by passing the following into the QEMU initialisation:
```
tls,websocket,x509=<path to pki server cert & CA cert>
```
In doing this, noVNC happily connected to QEMU via websockets.

In QEMU 2.5.x and above (tested with all versions up to 2.12.1), noVNC no longer connects to QEMU via websockets. If `tls,websocket,x509=<path to pki server cert & CA cert>` is used to configure websockets on 2.5.x and above, it is internally reconfigured to request a peer (client) certificate. This can be changed by creating the correct authentication objects as per https://qemu.weilnetz.de/doc/qemu-doc.html:
```
-object tls-creds-anon,id=tls0,endpoint=server,dir=</path/to/cert>,verify-peer=off
or
-object tls-creds-x509,id=tls0,endpoint=server,dir=</path/to/cert>,verify-peer=off
```
then calling the object with the following:
```
-vnc websocket,tls-creds=tls0
```

Depending on the websocket initialisation, 2 different error messages are generated from QEMU:
**via tls-creds-anon**
```
vnc_set_share_mode/0x562cbf8f8340: undefined -> connecting
Handshake failed TLS handshake failed: Could not negotiate a supported cipher suite.
Closing down client sock: protocol error
vnc_set_share_mode/0x562cbf5d6f00: connecting -> disconnected
```
**via tls-creds-x509**
```
vnc_set_share_mode/0x562a139bf680: undefined -> connecting
Handshake failed TLS handshake failed: A TLS packet with unexpected length was received.
Closing down client sock: protocol error
vnc_set_share_mode/0x562a136632c0: connecting -> disconnected
```

The console logs for noVNC are less than helpful in diagnosing this:
**via tls-creds-anon**
```
WebSocket connection to 'wss://<ip.address>:<port>/websockify' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
```
**via tls-creds-x509**
```
WebSocket connection to 'wss://<ip.address>:<port>/websockify' failed: WebSocket opening handshake was cancelled
```

Simply reverting QEMU back to 2.2.1 (and using the 2.2.1 websocket invocation) resolves the issue (but introduces a whole host of other issues due to QEMU 2.2.1).

**To Reproduce**
1. Generate a self signed certificate & place CA and cert in a directory for access
2. Build QEMU & enable websockets
3. Start a QEMU VM, with the following options:
```
-object tls-creds-x509,id=tls0,endpoint=server,dir=</path/to/cert>,verify-peer=off -vnc websocket,tls-creds=tls0
```
4. Connect with noNVC
```
https://ip.address/novnc/vnc_lite.html?&host=ip.address&port=5700&password=<mypwd>&encrypt=true&logging=debug
```

**Expected behavior**
Websocket connection to QEMU using TLS self signed certificates should work

**Client (please complete the following information):**
 - OS: Linux / Windows 
 - Browser: Chrome
 - Browser version: 69.x

**Server (please complete the following information):**
 - noVNC version: master
 - VNC server: QEMU 2.2.1 -> 2.12.1
 - WebSocket proxy: none - qemu connection

**Additional context**
Running the following on a separate system to validate the CA & certfile:
```
openssl s_client -CAfile </path/to/AC> -connect ip.address:port
```
Shows that there are no issues with the self signed certificate, as this could be a cause for TLS not working. The logs from the `openssl s_client` operation below:
```
Client sioc=0x558ca23b0280 ws=1 auth=2 subauth=0
New client on socket 0x558ca23b0280
vnc_set_share_mode/0x558ca23b0280: undefined -> connecting
TLS handshake complete, starting websocket handshake
Websock handshake failed Cannot read from TLS channel: Input/output error
Closing down client sock: protocol error
vnc_set_share_mode/0x558ca1be0e40: connecting -> disconnected
```
The websock handshake failing is to be expected, but the TLS handshake completes.

Connecting via tigervnc & enabling TLS security, the connection to the QEMU VNC port complete's successfully without issue.

**Comment by samhed** [comment]
You write 

> Depending on the websocket initialisation, 2 different error messages are generated from QEMU:

but the only initialisation you mention is "**via tls-creds-anon**". Which was the other one?

Anyway, an upgrade of QEMU caused the issue. I'm thinking this could be a clue:

> Handshake failed TLS handshake failed: Could not negotiate a supported cipher suite.

Perhaps your webserver doesn't support that TLS version?

**Comment by abraunegg** [comment]
Updated above - second set of -anon should have been x509

There is no issue with the web server as openssl / webserver uses cert and ca without issue.

**Comment by CendioOssman** [comment]
Unfortunately there isn't much we can do to help you. noVNC isn't involved in the TLS stuff. Whatever goes wrong is some incompatibility between Chrome and QEMU. So I'm afraid I'll have to ask you to file a bug with either of them. I would suggest you start with QEMU as it seems they've changed something.

**Comment by abraunegg** [comment]
Thanks. Trying all avenues at the moment to work out where this 'issue' lies.

**Comment by minexew** [comment]
@abraunegg Hi, have you been able to resolve the issue? I am trying to figure out how to set-up QEMU for encrypted websocket VNC myself

**Comment by abraunegg** [comment]
@minexew 
Never was able to solve this or work out where it was breaking down - which is a real shame given it 'should' work.

**Comment by minexew** [comment]
@abraunegg Maybe it will 'just work' again in QEMU 5.0: https://github.com/novnc/noVNC/issues/1304#issuecomment-586493390

Personally, I went for https://github.com/novnc/websockify. It does the job well.
