### ISSUE TITLE
Server disconnects unexpectedly

### ISSUE THREAD

**Issue by Gonsalo** [novnc/noVNC#1145]
I have noVNC successfully installed and working on Ubuntu 16.04. It connects smoothly and works very well (great work guys 👍), however after a few minutes the connection drops, it just gives me the 1006 error. As per other issues 1006 error, does not provide the reason of disconnection, so I kindly ask for your help.

Python : 2.7.12
Websockify : 0.8.0
Vnc server : vnc4server/Xvnc4.1

Certificate : Self signed for domain **vm.some_domain.net** (_some_domain_ just reference)  for the server hosting VNC.
**The Vnc server and the App are hosted in different servers** 

== ON THE SERVER ==

runs the following from launch.sh

`python /opt/websockify/run --cert /opt/certs/fullchain1.pem 9080 localhost:8900`

WebSocket server settings:
  - Listen on :9080
  - SSL/TLS support
  - proxying from :9080 to localhost:8900
Press Ctrl-C to exit

localhost - - [02/Oct/2018 14:41:03] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
localhost - - [02/Oct/2018 14:41:03] 127.0.0.1: Path: '/vms/9080'
localhost - - [02/Oct/2018 14:41:03] connecting to: localhost:8900

=== THE APP ==

connecting to wss://vm.some_domain.net/vms/9080
app.js:9492 Server choose sub-protocol: binary
app.js:7050 Server ProtocolVersion: 003.008
app.js:7448 Screen: 1366x768, bpp: 32, depth: 24, big_endian: 0, true_color: 1, red_max: 255, green_max: 255, blue_max: 255, red_shift: 16, green_shift: 8, blue_shift: 0
app.js:8888 Data URI scheme cursor supported
app.js:7753 First FBU latency: 656
app.js:7812 Timing of full FBU, curr: 52, total: 52, cnt: 1, avg: 52
app.js:7819 full FBU round-trip, cur: 718, total: 718, cnt: 1, avg: 718
app.js:6690 Encoding stats for this connection:
app.js:6694     [unknown encoding 5]: 3 rects
app.js:6694     [unknown encoding -239]: 1 rects
app.js:6698 Encoding stats since page load:
app.js:6701     [unknown encoding 5]: 3 rects
app.js:6701     [unknown encoding -239]: 1 rects 

Im using Nginx redirect non-SSL to SSL, then on Server listen 443 Im doing the following to get the correct port

```
location ~ ^(/vms/[^/]+) {
        if ($request_uri ~* "([^/]*$)" ) {
          set  $uri_port  $1;
        }
        proxy_pass http://127.0.0.1:$uri_port;
    } 
```

Is it a normal/correct to have the app connection to **wss://** and websockify showing as **Plain non-SSL (ws://) WebSocket connection**?

Any help is much appreciated.

**Comment by CendioOssman** [comment]
> Is it a normal/correct to have the app connection to **wss://** and websockify showing as **Plain non-SSL (ws://) WebSocket connection**?

You stated that you are using nginx to do precisely that, so I would assume that is expected?

As for the disconnect, there isn't any clue in the logs given. What does the VNC server say in its logs?

**Comment by Gonsalo** [comment]
Hi, Im not super familiar with websockets and assumed that could be the issue.

As for the logs unfortunately they were disabled (my bad). I'm gonna get back here once I have proper logging.

Thank you for the help.

**Comment by CendioOssman** [comment]
The certificate is only used in the initial handshake, so it doesn't affect anything after that. But it could be that you have some firewall or such getting upset with the traffic and cutting the connection. Does things work better if you are on the same network as the server?

And could you paste the server log here so we can see exactly what it is saying? Small details can be important.

**Comment by Gonsalo** [comment]
Hi, It is successfully working, seems that nginx loses things on the way when upgrading the connection (very strange) even forcing the appropriate headers, so just using a direct setup with no proxy_pass seems to work perfectly (the server has been running for 3 hours without disconnections) on a SSL environment .

Basic nginx setup that might save some time (do not use **proxy_pass**)
```
server_tokens off; # for security-by-obscurity: stop displaying nginx version

# HTTPS server
server {
    listen 443 ssl;
    server_name __DOMAIN_NAME__;

    root html; # irrelevant
    index index.html; # irrelevant

    ssl on;
    ssl_certificate __CTR_PATH__;
    ssl_certificate_key __KEY_PATH__;
    ssl_prefer_server_ciphers on;
    
    ... Do your stuff ... 
}
```

Thank you for all the support!! 👍
