### ISSUE TITLE
local scaling results in a very thin screen repeated multiple times

### ISSUE THREAD

**Issue by VidJa** [novnc/noVNC#1147]
local scaling results in a very thin screen repeated multiple times on master.
remote scaling or none results in a 'normal' looking screen with the top repeated multiple times at the bottom on FF 62.0, Chromium Version 69.0.3497.81 on Ubuntu and Safari on MacOS 10.13.6

For what its worth, I'm tracking the master branch with x11vnc as vncserver

![screenshot from 2018-10-03 08-34-23](https://user-images.githubusercontent.com/6108142/46393922-81aace80-c6e7-11e8-89b2-82e696a64a0a.png)

**Comment by CendioOssman** [comment]
I'm afraid that is per x11vnc's design. It is using that extra space as a form of cache. Please look at the `-ncache` argument to x11vnc to see how to disable it.

**Comment by VidJa** [comment]
Thanks. I would also be happy to use another vnc server, any best practices?

**Comment by CendioOssman** [comment]
We don't have any official recommendations, but we here at Cendio use TigerVNC in our packaging.
