### ISSUE TITLE
Shift modifier not working in Steam in-game web browser

### ISSUE THREAD

**Issue by CyberShadow** [novnc/noVNC#1148]
The Shift modifier doesn't seem to be working when attempting to use a noVNC instance from Steam's in-game web browser.

**To Reproduce**
1. Launch any game from [Steam](https://store.steampowered.com/about/) on Windows.
2. Press Shift+Tab to open the in-game overlay.
3. Click "Web browser".
4. Navigate to a running noVNC instance.
5. Connect to the VNC.
6. Try to type some shifted characters (e.g. "ABC").

**Expected behavior**
The VNC server receives the shifted characters ("ABC").

**Actual behavior**
The VNC server receives un-shifted characters ("abc").

**Client (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: Steam's Chromium-based in-game browser
 - Browser version:
    - Steam build from Sep. 8 2018, at 12:24:24
    - User agent: Mozilla/5.0 (Windows; U; Windows NT 10.0; en-US; Valve Steam GameOverlay/1536436120; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Server (please complete the following information):**
 - noVNC version: git commit d1050405813412a684636522f8daddb5ad913fe2
 - VNC server: TigerVNC (`vncserver`) running on Arch Linux x64
 - WebSocket proxy: websockify, as set up by `utils/launch.sh`

**Additional context**
My first guess was that the Steam browser was intercepting or simply not supporting the Shift modifier in the reported JavaScript key events (perhaps to ensure Shift+Tab closes the overlay), and that would be that. However, a test page (e.g. https://unixpapa.com/js/testkey.html (reuploaded [here](http://thecybershadow.net/testkey.html) to fix black-on-black text in Steam)) showed that the Shift modifier is indeed being sent to the web page.

Unfortunately I can't provide logs as I have no idea on how to access the Steam web browser's development console, assuming it even has one.

**Comment by CyberShadow** [comment]
Comparing the output of the event test page on Chromium and Steam yields:

```diff
--- chromium.txt	2018-10-03 21:38:10.575625491 +0000
+++ steam.txt	2018-10-03 21:37:54.670362575 +0000
@@ -1,10 +1,10 @@
 keydown  keyCode=16        which=16        charCode=0        
          shiftKey=true  ctrlKey=false altKey=false metaKey=false
-         key=Shift char=undefined location=1 repeat=false
+         key=Shift char=undefined location=0 repeat=false
          keyIdentifier=undefined keyLocation=undefined
 keydown  keyCode=65  (A)   which=65  (A)   charCode=0        
          shiftKey=true  ctrlKey=false altKey=false metaKey=false
-         key=A char=undefined location=0 repeat=false
+         key=a char=undefined location=0 repeat=false
          keyIdentifier=undefined keyLocation=undefined
 keypress keyCode=65  (A)   which=65  (A)   charCode=65  (A)  
          shiftKey=true  ctrlKey=false altKey=false metaKey=false
@@ -12,9 +12,9 @@
          keyIdentifier=undefined keyLocation=undefined
 keyup    keyCode=65  (A)   which=65  (A)   charCode=0        
          shiftKey=true  ctrlKey=false altKey=false metaKey=false
-         key=A char=undefined location=0 repeat=false
+         key=a char=undefined location=0 repeat=false
          keyIdentifier=undefined keyLocation=undefined
 keyup    keyCode=16        which=16        charCode=0        
          shiftKey=false ctrlKey=false altKey=false metaKey=false
-         key=Shift char=undefined location=1 repeat=false
+         key=Shift char=undefined location=0 repeat=false
          keyIdentifier=undefined keyLocation=undefined
```

It looks like Chromium's `key` field is pre-shifted, but not Steam's.

**Comment by CyberShadow** [comment]
OK, after digging in some deeper, I have reached the conclusion that keyboard events in the Steam browser are completely FUBAR. To illustrate:

| field                      | a (Firefox) | a (Steam) | A (Firefox) | A (Steam) | F1 (Firefox) | F1 (Steam) |
| -------------------------- | ----------- | --------- | ----------- | --------- | ------------ | ---------- |
| key                        | a           | a         | A           | a/A       | F1           | F1         |
| keyCode                    | 65/0        | 65/97     | 65/0        | 65/65     | 112/112      | 112/-      |
| which                      | 65/97       | 65/97     | 65          | 65/65     | 112/0        | 112/-      |
| charCode                   | 0/97        | 0/97      | 0/65        | 0/65      | 0            | 0/-        |
| code                       | KeyA        | F7/""     | KeyA        | F7        | F1           | KanaMode/- |

`a/b` means keydown/keyup is a, keypress is b.

Note how:

- The `code` field is complete garbage.
- `keydown` / `keyup` always receive the unshifted version of all fields (though `shiftKey` is still true there).
- Any field can change between `keydown` and `keypress` for the same key.

The last one means we can't reuse the existing logic for discarding `keydown` data and waiting for `keypress`.

After spending a few hours trying to find a "proper" fix, I settled on the following hack:

https://github.com/CyberShadow/noVNC/commit/14ded978b54ea76ec6443f6ac727a141b2652b35

I could clean that up into a PR, but I don't see much prospect in supporting such a broken browser in mainline.

**Comment by CyberShadow** [comment]
Steam bug report: https://steamcommunity.com/groups/SteamClientBeta/discussions/0/1729837292627879747/

**Comment by CendioOssman** [comment]
Yeah, that is a rather blatant bug in their browser. I don't think we want to add a workaround for that. Hopefully they'll roll out a fix quickly. It's odd that they have this bug if they are based on Chromium (which works well).
