### ISSUE TITLE
[question] How to enable continuous update frame-rate ?

### ISSUE THREAD

**Issue by al3x609** [novnc/noVNC#1149]
I need to adapt noVNC for low latency networks. 4.2[ ms]

As you can see, the server where I intend to provide a HPC remote rendering service , has the ability to deliver high values ​​in FPS, but using the Chrome debugging tool, it shows a very low frame-rate.

![image](https://user-images.githubusercontent.com/4086644/46537445-ec3e4480-c876-11e8-874a-5a2f5c16f5e9.png)

I found this [thread](https://github.com/novnc/noVNC/issues/221) which talks about performance in different networks, but it's a comment from many years ago, the latest version of noVNC, how can I enable the constant sending of FramebufferUpdate?

my setup.
noVNC = github source version
turbovnc = 2.2
nginx proxy.

If you have any comments on how I could deliver a more fluid service, I thank you in advance.

**Comment by CendioOssman** [comment]
That is already happening, so there is nothing you need to change. So if you are getting poor performance then there must be something else that is wrong.

First off, do you get good performance with another VNC client?

**Comment by al3x609** [comment]
Yes, with the turbovnc-java client the animation is more fluid, even with the interaction of mouse events. approximately 10 fps, more.

**Comment by CendioOssman** [comment]
So from 5 fps to 15? That's still very slow so I have to wonder if something isn't quite right.

Can you check CPU usage on the server and client? Start a video or some animation so that it is constantly updating things, and see how much CPU each process is using.

**Comment by samhed** [comment]
Closing due to no response
