### ISSUE TITLE
[Feature request]compression level and quality options

### ISSUE THREAD

**Issue by al3x609** [novnc/noVNC#1150]
It would be good to allow users to modify the compression level from noVNC, to adapt it to the characteristics of their connection.
not only default Compression Level 2 and Quality Level 6, maybe...
https://github.com/novnc/noVNC/blob/d1050405813412a684636522f8daddb5ad913fe2/core/rfb.js#L1242-L1243

**Comment by CendioOssman** [comment]
Please see #396 for tracking this feature request.
