### ISSUE TITLE
Uncaught Error: rQwait cannot backup 8 byte

### ISSUE THREAD

**Issue by lgw8186** [novnc/noVNC#1152]
windows server 2008 + UltraVnc + novnc

When click on the link, sometimes report 'Uncaught Error: rQwait cannot backup 8 bytes' , and I have a report 'Sorry, loopback connections are not enabled'.

noVNC 遇到一个错误：

Uncaught Error: rQwait cannot backup 8 bytes
http://xx:9000/core/websock.js:142:27
Error: rQwait cannot backup 8 bytes
at Websock.rQwait (http://xx:9000/core/websock.js:142:27)
at RFB._handle_security_failure (http://xx:9000/core/rfb.js:914:28)
at RFB._negotiate_security (http://xx:9000/core/rfb.js:852:29)
at RFB._init_msg (http://xx:9000/core/rfb.js:1274:29)
at RFB._handle_message (http://xx:9000/core/rfb.js:709:22)
at Websock._recv_message (http://xx:9000/core/websock.js:287:33)

Sorry, loopback connections are not enabled

i have choose 'allow loopback connections ' on server-setting

please help me...

**Comment by CendioOssman** [comment]
Do you think you could get a recording of this? Use the `--record` option to `launch.sh` and it will store a file with the data sent between noVNC and the server. Please attach that file here and we can have a look.

**Comment by lgw8186** [comment]
sorry, i execute commd failed ;  i search this error and i not find like this.  can you help me ？

commd: 
node C:\Users\Administrator\node_modules\websockify-master\other\js\websockify.js --web C:\Users\Administrator\node_modules\novnc-noVNC-9881899 9000 xx:5900 --record c:\

error image:

![image](https://user-images.githubusercontent.com/14970166/47006856-76d14e80-d169-11e8-8678-9bd217ce5eda.png)

**Comment by lgw8186** [comment]
i also get this error, please help me.

![image](https://user-images.githubusercontent.com/14970166/47007833-aa14dd00-d16b-11e8-8138-e565ce2b640d.png)

**Comment by CendioOssman** [comment]
That's an unrelated error. Please file a new issue and describe what steps were taken to provoke the bug.

**Comment by CendioOssman** [comment]
> sorry, i execute commd failed ; i search this error and i not find like this. can you help me ？

Hmmm... Odd error for that. Perhaps you don't have the proper permissions to write directly in the root directory? Could you try setting up a special directory for this and point it at that instead?

**Comment by CendioOssman** [comment]
Hang on, `:` is an invalid filename character on Windows. So the recording feature is probably not compatible with Windows right now. Let me try and get a fix in place.

**Comment by lgw8186** [comment]
> Alright, I have a patch committed to websockify. Please try again using the latest commit.

I try and it work .This is record file.

**Comment by CendioOssman** [comment]
Both of those recordings show a successful session. Your initial report shows a failure to connect. Was this really the correct file?

**Comment by samhed** [comment]
> When click on the link, sometimes report 'Uncaught Error: rQwait cannot backup 8 bytes' , and I have a report 'Sorry, loopback connections are not enabled'.

Sounds like this error isn't always happening for you. You need to keep making recordings until you encounter the error, then send that recording to us.

**Comment by secureinfo** [comment]
rQwait goback 4 bytes

**Comment by samhed** [comment]
No response.

**Comment by et-hh** [comment]
i face the problem too, and i fix it

just check this

![image](https://github.com/novnc/noVNC/assets/11864722/73526a93-656d-4093-b53e-8b229202c1d2)
