### ISSUE TITLE
Touch Screen Devices Using Remote Mouse

### ISSUE THREAD

**Issue by DMoneigh** [novnc/noVNC#1153]
**Describe the bug**
It appears that touch screen devices are forcing noVNC clients to use the remote mouse. Is there anyway to force all touch screen clients to use the local mouse instead?

**Comment by samhed** [comment]
Because many touch devices doesn't have a local mouse cursor.

No, there is no setting or way in the GUI to achieve what you want. But you could always modify this line in your code:

https://github.com/novnc/noVNC/blob/master/core/util/cursor.js#L9
