### ISSUE TITLE
Local Scaling Broken

### ISSUE THREAD

**Issue by Queuecumber** [novnc/noVNC#1155]
**Describe the bug**
When I use the "local scaling" setting, I get a long thin strip in the middle of the page with a very small area used for the VNC display. 

**To Reproduce**
1. Open the side menu on the left
2. Click the gear
3. Change the scaling mode to "Local Scaling"

**Expected behavior**
The entire web page is able to be used for VNC display

**Screenshots**
![screenshot from 2018-10-18 19-09-56](https://user-images.githubusercontent.com/5865387/47189192-6f48ab80-d309-11e8-88c8-98d1b08cff0a.png)

The black strip in the center is what is being used for VNC display  but since thats a nonsense aspect ratio it ends up being only that small area in the top. 

![screenshot from 2018-10-18 19-11-11](https://user-images.githubusercontent.com/5865387/47189230-969f7880-d309-11e8-8719-6ccd467ccfaf.png)

Heres another one that might be clearer.

**Client (please complete the following information):**
 - Ubuntu 18.04 
 - Browser: Chromium 
 - Browser version: 71.0.3551.3

**Server (please complete the following information):**
 - noVNC version: 1.0.0
 - VNC server: x11vnc
 - WebSocket proxy:  websockify

**Comment by CendioOssman** [comment]
I'm afraid that's not a bug, but rather a misfeature in x11vnc. It creates that odd sized session in some attempt to use the lower parts for a cache. Please have a look at its `-ncache` parameter.

**Comment by CendioOssman** [comment]
Local scaling does indeed do scaling in the browser. However x11vnc creates a session with those ridiculous dimensions that you are seeing. And yes, #525 is about the same thing.
