### ISSUE TITLE
proxy to many vnc servers

### ISSUE THREAD

**Issue by porjo** [novnc/noVNC#116]
I have a scenario where my clients do not have direct network connectivity to the VNC servers. They will need to be pass through a proxy of some kind. One way I can see to solve this would be to setup a gateway server that connects to the client network and the server network, and run multiple instances of websockify there. This would be rather cumbersome to maintain. Instead, what I was hoping is that the proxy server would dynamically map client to server (similar to how a HTTP proxy works)

Is this possible with noVNC/websockify ?

**Comment by FlorianHeigl** [comment]
Commenting from the future, yes, obviously that would have been interesting :+1:
