### ISSUE TITLE
[question] reverse proxy to multiple devices

### ISSUE THREAD

**Issue by leonardpitzu** [novnc/noVNC#1161]
i have a number of raspberry pi's all running noVNC
i have a nginx reverse proxy

setup:
```
router ---- pi (nginx reverse proxy) ---- pi1
                                     |----pi2
                                     |----pi3
                                     |____pi4
```

url "setup":
domain.com/pi1
domain.com/pi2
domain.com/pi3
domain.com/pi4

all pi's have websockify on the same url so my problem is how to proxy traffix to the correct pi basd on the accessed url?
any help is appreciated as this is my first time to work on conditional reverse proxying...

**Comment by CendioOssman** [comment]
Unfortunately you need to do some special work to get this running. The default setup will always use the same websocket path, so the proxy will not know which machine to forward to. There was an attempt to solve this in #1058, but we failed to find something reliable.

We don't have a recommended setup for this scenario, besides manually specifying `path` for each URL. I would suggest you ask on our mailing list to see if any other user has gotten such a setup working.
