### ISSUE TITLE
No password entry

### ISSUE THREAD

**Issue by clive-hetzner** [novnc/noVNC#1162]
**Describe the bug**
Theres no place to enter a password, as per the documentation "enter a password if the VNC server has one configured" - where would this be entered, there's nothing that can be entered anywhere.

**To Reproduce**
1. Navigate to the local URL exposed on the console
2. Attempt to enter a password, notice there's nothing and nowhere to do this 

**Expected behavior**
There should be a password field available to enter the password.

**Screenshots**
![image](https://user-images.githubusercontent.com/40467910/48775281-48e5a980-ecd5-11e8-9898-baee2cc835d9.png)

**Client (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Browser version: 70.0.3538.77 (Official Build) (64-bit)

**Server (please complete the following information):**
 - noVNC version: Cloned `master`
 - VNC server: Any
 - WebSocket proxy: websockify

**Additional context**
I first tried the iKVM fork ( https://github.com/kelleyk/noVNC ) which led me here

**Comment by samhed** [comment]
It should prompt you for a password after pressing connect if your server requires one. Does that not work?

**Comment by samhed** [comment]
This is the full sentence from the README:

> Hit the Connect button, enter a password if the VNC server has one configured, and enjoy!

**Comment by samhed** [comment]
You wrote in your initial post that you used noVNC master, were you in fact using kelleyk/noVNC?

You also wrote "VNC server: Any". What server were you actually using?

**Comment by clive-hetzner** [comment]
@samhed I alternated between kellyk/noVNC (several branches) and followed the source code upstream to your master branch which is why I eventually posted here.

The only servers I attempted to connect to, and I realize now in retrospect the ambiguity of my statement, were iKVM "vnc" servers. I have about 7 of them internally, but they were all not true "vanilla" VNC servers.

I'm sorry about the confusion.

**Comment by samhed** [comment]
In our experience, most of these iKVM "VNC" servers are broken and doesn't follow the RFB protocol in one way or other. It is generally very difficult to support such servers.

Have you been able to get things working with other VNC clients?

**Comment by clive-hetzner** [comment]
@samhed I really appreciate your support here however I genuinely feel I'm wasting your time you could better spend elsewhere.

No, I've not managed to get it to work with anything I've since tried, in fact I'm looking at completely different solutions to the problem I was trying to solve now rather than iKVM/VNC which I've marked as "broken" (for our purposes).

Thank you very much but I'm confident this can just be closed as a lesson learned for me, and again thank you for your time and I'm sorry I (ab)used it where it was not required.

**Comment by samhed** [comment]
No worries. Good luck!
