### ISSUE TITLE
Setting up the websockets proxy

### ISSUE THREAD

**Issue by DavDaBomb21** [novnc/noVNC#1163]
I'm new to noVNC but have faced a couple issues so far. 
I am running a windows 10 PC and am running python 3.2.5, Note: David is the user name.
1. I cloned the repository using GitHub Desktop program
2. I used git bash to run the command that was available on the quick start guide  which was:
./utils/launch.sh --vnc localhost:5901
This originally didn't work as python.exe wasn't being found by git bash. But this solved it [https://stackoverflow.com/questions/13091522/bin-env-python-no-such-file-or-directory-windows-through-git-bash-trying-to](stackoverflow)
3. After running the command again in git bash, it still didn't work and I'm not sure what to do now.
The first time I tried to run the command again, this happened:
![error1](https://user-images.githubusercontent.com/45212780/48798707-1d76b500-ecfd-11e8-83fd-e28863110363.PNG)
4. And every successive time I try to run the command, I get this:
![error2](https://user-images.githubusercontent.com/45212780/48798815-60d12380-ecfd-11e8-846e-1b3c1645ff07.PNG)
 Both of these errors talk about both the resource module and the numpy module, but I don't really know how to get past this issues. It also says that windows is not supported, but I am pretty sure I read somewhere that it is supported (correct me if I am wrong).

**Comment by DavDaBomb21** [comment]
Edit 1: After doing research, it seems that resource is a unix only module.

**Comment by DavDaBomb21** [comment]
Edit 1: After doing some research, the python module "research" is a Unix-only module.

**Comment by al3x609** [comment]
> Edit 1: After doing some research, the python module "research" is a Unix-only module.

Numpy is multiplatform, If you can install python over windows, also you can install all modules for python.
. Try with [pip](https://pypi.org/project/numpy/)

**Comment by samhed** [comment]
The python version of websockify will not work on Windows I'm afraid. This means you can't use the launch script that is included in noVNC. We have had some reports that the javascript version of Websockify, from NPM works somewhat on Windows.

For more questions regarding websockify, I would advice you to post in the websockify repository.
