### ISSUE TITLE
Can someone explain, please? (Demo question)

### ISSUE THREAD

**Issue by krosoftware** [novnc/noVNC#1164]
I posted question about demo and someone marked it as "duplicate". I do not see any description so can someone answer - does demo work or not? Thank you.

**Comment by samhed** [comment]
The demo works perfectly for me. What problem are you seeing?

**Comment by deef0000dragon1** [comment]
I get a "failed to connect to server" header warning whenever I try to click the connect button. The same happens on my personal site as well. 

output from chrome console if that helps. 
```
websock.js:210 WebSocket connection to 'wss://novnc.com/websockify' failed: Error during WebSocket handshake: Unexpected response code: 404
open @ websock.js:210
_connect @ rfb.js:403
_updateConnectionState @ rfb.js:648
rfb.js:245 WebSocket on-error event
(anonymous) @ rfb.js:245
(anonymous) @ websock.js:230
error (async)
open @ websock.js:228
_connect @ rfb.js:403
_updateConnectionState @ rfb.js:648
setTimeout (async)
RFB @ rfb.js:250
connect @ ui.js:1018
rfb.js:688 Failed when connecting: Connection closed (code: 1006)
_fail @ rfb.js:688
(anonymous) @ rfb.js:222
(anonymous) @ websock.js:225
```

**Comment by krosoftware** [comment]
Here is my error from console:
`connecting to wss://novnc.com:443/websockify
websock.js:210 WebSocket connection to 'wss://novnc.com/websockify' failed: Error during WebSocket handshake: Unexpected response code: 404
open @ websock.js:210
_connect @ rfb.js:403
_updateConnectionState @ rfb.js:648
rfb.js:245 WebSocket on-error event
(anonymous) @ rfb.js:245
(anonymous) @ websock.js:230
error (async)
open @ websock.js:228
_connect @ rfb.js:403
_updateConnectionState @ rfb.js:648
setTimeout (async)
RFB @ rfb.js:250
connect @ ui.js:1018
rfb.js:688 Failed when connecting: Connection closed (code: 1006)
_fail @ rfb.js:688
(anonymous) @ rfb.js:222
(anonymous) @ websock.js:225
rfb.js:452 Encoding stats for this connection:
rfb.js:460 Encoding stats since page load:`

**Comment by samhed** [comment]
You have to specify where the demo can find your websocket proxy. noVNC can not be used without such a proxy or alternatively with a VNC server with a built in websocket proxy.

**Comment by krosoftware** [comment]
Could you please explain what that means? What I need to do? I just wanted to see how demo works. Thank you.

**Comment by deef0000dragon1** [comment]
@krosoftware noVNC itself does not act as a virtual desktop server. You require a service such as tightvncserver to connect to. Then, you are able to connect through noVNC, as you would through any other vnc client like realVNC. 

The largest difference between noVNC and realVNC/others is that noVNC requires **no** client program other than an html5 web browser as the client itself runs in the browser. 


This means, unfortunatly, that noVNC is unable to provide the service that I require, which is a client that can act as localhost for the server it is on. (I am limited to 80, 443, and 22 ) It is however, a very useful tool if you dont want to have to download a vnc client.

The "and an application built on top of that library" part of the readme lead me to believe that it did perform the server tasks. The readme in general could do to be better formatted, ie putting in the quick start "install xyz VNC server by ..., or use a server you have already installed." that or put a more detailed starter guide in the wiki.

**Comment by krosoftware** [comment]
OK I understand that part but noVNC demo should work (to connect) to some VNC server? I understand that noVNC is client part, but demo purpose is to show how demo work, right?
