### ISSUE TITLE
Input broken on Android (defaultKeyboardinputLen)

### ISSUE THREAD

**Issue by knnnrd** [novnc/noVNC#1169]
I'm using noVNC through a webview on an Android 4.4 device. This device also has a built-in barcode scanner and this is also used to input text. 

When using the barcode scanner: Previously scanned text is added to the currently scanned text. If I keep scanning it incrementally adds more and more previously scanned text along with the currently scanned text.
When using a virtual keyboard: After inputting some text with the keyboard, the backspace doesn't work.

It seems I cannot exactly pinpoint when this is happening, changing the "defaultKeyboardinputLen" from 100 to 0 fixes it for a while. Then it happens again, I change the value back to 0 and it's fixed again. And so on.

My webview component is configured to never use cache so the new defaultKeyboardinputLen value should be fetched everytime. I validated this by making use of USB debugging.

**Client:**
 - OS: Android 4.4
 - Browser: Webview
 - Browser version: Chrome 30

**Server:**
 - noVNC version: 1.0.0
 - VNC server: Xtightvnc - Xvnc version 3.3.tight1.2.9
 - WebSocket proxy: websockify 0.8.0

**Comment by CendioOssman** [comment]
That is an absolutely ancient browser. I don't think we can really debug or support that.

Does the same issue occur on something more recent?

**Comment by knnnrd** [comment]
@CendioOssman Hi, thanks for your response.

In the meanwhile I figured out that the "defaultKeyboardinputLen" property is used for backspace handling and backspaces can't work if it's set to 0. Not sure what happened there during my testing but  for now the backspace problem seems to be solved by setting it back to the default value (100).

The problem also occurs on newer webviews. Android 6.0 and up.
I think I forgot to mention that the repeated input doesn't happen 100% of the time.

Also, why or how was the default value of 100 chosen? Is it related to replacing text by pasting text that is shorter than the replaced text?

**Comment by CendioOssman** [comment]
I'm not sure why it is 100. Might be completely arbitrary. @kanaka, do you know?

**Comment by samhed** [comment]
I believe I am guilty of defaultKeyboardInputLen and it's default value. The value is indeed arbitrary, long enough to not have to reset all the time and short enough to not have a large buffer of text.

Anyway the keyboard input code in Chrome on Android is very special. Chrome on Android when using the virtual keyboard is the only browser/platform combination that uses this code path that I'm aware of. It's setup to be a fallback from when regular keyboard input events are not fired.

All other browsers (even Firefox on Android) fires regular keyboard input events.

**Comment by CendioOssman** [comment]
To emulate what was described I tried the latest Chrome on Android and used the clipboard feature of the Swiftkey keyboard. I could not see any issue and each "paste" got me a single copy.

@knnnrd, could you try this on your device and see if you can provoke the bug that way? We need to find a test case that we can compare with here.

**Comment by knnnrd** [comment]
The problem is that I haven't been able to reproduce this issue my self. Users have been reporting it.

I added some logging in the android-Chrome specific fallback code and I'm working on getting a device log from the users that are having this issue.

**Comment by CendioOssman** [comment]
Any luck getting some logs?

**Comment by samhed** [comment]
No response.
