### ISSUE TITLE
[Question] How to configure reverse proxy nginx + token plugin?

### ISSUE THREAD

**Issue by al3x609** [novnc/noVNC#1170]
I have multiple vnc servers on the same machine, 
websockify with token plugin for redirect to all.

How I can configure nginx reverse proxy for this situation?

```
websockify/run --web=/Users/alex/Test/noVNC/ --token-plugin=TokenFile --token-source=./websockify/tokens/ -v  6080
```

___
```
    server {
       listen 9090;
       server_name localhost;

       location / {
		proxy_http_version 1.1;
 		proxy_pass "http://127.0.0.1:6080";
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
       }

    }


```
for example, only show the default "it works" from Nginx
`http://localhost:9090/?path=?token=1234`

what am I doing wrong?

**Comment by CendioOssman** [comment]
Not sure, and that sounds like a generic nginx issue.

But do you even need nginx here? If you use tokens then a single websockify can handle all your hosts.

**Comment by al3x609** [comment]
sure, a single websockify can handle all vnc servers, but, novnc/websockify run over a node in a cluster. Then, the master node with public IP need set a reverse proxy (nginx) for public access to the vnc web service.
 I need redirect i.e 

`www.sc3uis.com/?path=/token=xxxx `

this is my methodology to evade the need for ssh tunnels towards the VNC node

**Comment by CendioOssman** [comment]
I'm sorry, but I still don't understand your need for nginx. What goes wrong if you put websockify on the machine with the public IP and let it handle both the WebSockets and the noVNC files?

**Comment by al3x609** [comment]
I will try, thanks.

**Comment by dxianping** [comment]
> I will try, thanks.

Hey bro. Did you solved it?
