### ISSUE TITLE
Unable to view the screen of the remote machine. Instead, it's an empty box.

### ISSUE THREAD

**Issue by MedhaPujari** [novnc/noVNC#1171]
Hi! 
I've followed all the instructions right (as per the video: https://www.youtube.com/watch?v=Ec2PD4WRdew), but when I try to connect to the final URL for remote access, it shows a blank box with no screen of the machine I intend to access remotely.  I've also attached an image for a clear picture of what's happening. 

Help is highly appreciated! Please help me resolve the issue. 

Thanks much!

![novnc_image](https://user-images.githubusercontent.com/35552309/49181164-a48ee300-f324-11e8-898b-71d564796aa6.PNG)

**Comment by samhed** [comment]
No response.
