### ISSUE TITLE
Ability to change dot cursor

### ISSUE THREAD

**Issue by oxfordian-2** [novnc/noVNC#1173]
The new "dot cursor" feature is very handy.  However there is one big problem with it - it is a "dot" and very hard to see especially when clients are not super duper computer literates.

It would be of great help if you could publish how to create or configure a custom cursor - maybe a small image file or base64 encoded image string so that we can provide a slightly more visible "dot cursor" to our users

I have been trying to figure this out as to how to give a customer cursor, but without much luck

Thanks much for introducing the "dot cursor" - it has been a life saver in cases where there is no remote cursor (HMI devices)

**Comment by CendioOssman** [comment]
I would prefer not to add even more settings, but I can agree that the one that was added is rather small. It is 3x3, whilst the one seen in RealVNC based implementations is 5x5.

It is implemented here if you want to change it:

**Comment by oxfordian-2** [comment]
Okay.  Shall give that a shot.

Thank You.
