### ISSUE TITLE
Memory leaks while resizing the session

### ISSUE THREAD

**Issue by MarcusWichelmann** [novnc/noVNC#1176]
**Describe the bug**
When using the novnc resize method to change the size of a small vnc-server session to a high resolution like 3000x2000 px there is a big memory leak. A second or so after doing this it normalizes to a value nearly as big as before even though the resolution is still high.

**To Reproduce**
1. Connect to a vnc server
2. Create a memory snapshot
3. Use the resize-method of novnc to set the session size to a high value (the desktop on the vnc-server resizes)
4. Create one more memory snapshot
-> The second snapshot is way bigger
5. Wait a few seconds. The memory-usage shrinks to a value like in the first snapshot.

**Expected behavior**
The memory usage stays low.

**Screenshots**
![bildschirmfoto vom 2018-12-17 01-00-00](https://user-images.githubusercontent.com/5501487/50060773-5e48d900-0198-11e9-9bb5-488a3f8ace99.png)

**Client (please complete the following information):**
 - OS: Linux
 - Browser: chrome
 - Browser version: 70.0.3538.110

**Server (please complete the following information):**
 - noVNC version: 1.0.0
 - VNC server: TigerVNC
 - WebSocket proxy: websockify

**Comment by samhed** [comment]
Hi Marcus, this looks normal to me, that's usually how the garbage collector works. Are you seeing any practical problems due to this?

**Comment by MarcusWichelmann** [comment]
@samhed Ah okay. But I probably didn't capture the actual issue in this report.

A friend pointed me to this because of his computer freezing after a few Gigabytes of additional RAM usage caused by resizing a noVNC session.
But it looks like I didn't properly reproduce this and captured a wrong (far less big) memory usage increasement instead.

I'll continue trying to reproduce the *actual* issue and do a new memory snapshot to determine what causes this.

**Comment by samhed** [comment]
Ok I see. Yes, that sounds good, thank you.

**Comment by CendioOssman** [comment]
No response. Closing for now.
