### ISSUE TITLE
Add support for Super key, or add custom key map options

### ISSUE THREAD

**Issue by ssebs** [novnc/noVNC#1178]
Add support for Super/Windows key.

Something like the CTRL + ALT + DEL Buttons, but for the Super(Windows) key, so we can send that to the VNC host.

**Comment by samhed** [comment]
Agreed, and thanks for the PR.

>... add custom key map options ... A config file for these mappings would be a nice to have as well.

Did you get a chance to look at any of these things?

**Comment by ssebs** [comment]
I didn't, it might be worth splitting this issue.
