### ISSUE TITLE
Official .min.js dist?

### ISSUE THREAD

**Issue by lucafabbian** [novnc/noVNC#1180]
It would be great to have an official `dist/noVnc.min.js` file generated with rollup and ready for browser embedding.
I know about the use_require script, but I would like to embed it using jsDelivr cdn (which is only possible if the dist file is is inside npm package) or another cdn without having to build it by myself.

**Comment by CendioOssman** [comment]
I don't think that is something that is really possible as we're built on modules so our files need to be in some module format to be useful. So people are expected to do their own rollups of our modules and their front end code that uses those modules.
