### ISSUE TITLE
Changing the width and height of RFB

### ISSUE THREAD

**Issue by vishkumar** [novnc/noVNC#1181]
Hello All,

I hope you all are doing well. We are currently working on adding a VNC support to our web portal. I have been successful in making the connection through `novnc-node` but the RFB that I get is of default size which is about 800px by 480px. I have put it in a modal in our React portal. The problem is that I can't really resize the VNC screen. I want it to take the full modal width and resize on window resize as the Modal would do. 
I have tried to play with the rfb.js file but have not had good luck with that either. I see there are some `resize` related things in the rfb.js file but don't really know how to use those to accomplish this task. 

Is it even possible to set it's width dynamic as in take the full width of your parent div? If yes, how can I do that?

Thanks

**Comment by samhed** [comment]
So you have two options:

1. Resizing the actual remote screen
2. Client-side scaling

For the first option you will need a VNC server that supports the ExtendedDesktopSize extension, one example of such a server is TigerVNC. Then you have to use vnc.html and change "Scaling Mode" to "Remote Resizing".

The second option should work out of the box if you are using vnc.html, just change the "Scaling Mode" to "Local Scaling".

**Comment by samhed** [comment]
No response.

**Comment by Jousboxx** [comment]
@samhed I'm having a similar problem. Could you please elaborate on how to adjust vnc.html so that Remote Resizing is used by default? I'm able to set it manually once I'm in a NoVNC session, but I'd prefer it started out that way.

**Comment by samhed** [comment]
You can't do that by simply modifying vnc.html. You'd have to change `app/ui.js`. It will hopefully be easier in the future, see #1428

**Comment by Jousboxx** [comment]
Thanks for pointing me in the right direction, I got it working.

For those finding this thread from Google:
There's a section in `ui.js` that has a bunch of `initSetting` lines. One of them is
```UI.initSetting('resize', 'off');```.
This is where the default scaling setting is defined. If you change `off` to `remote`, that will be the new default.

Since I'm using NoVNC as part of a container that will be set up automatically, I needed to do this from Bash. I used the following command:
```sed -i "s/UI.initSetting('resize', 'off');/UI.initSetting('resize', 'remote');/g" /usr/share/novnc/app/ui.js```

**Comment by maniac-tech** [comment]
@samhed : Cant we achieve what @aerobinsonIV is trying to do while initialising RFB ?

**Comment by samhed** [comment]
```
rfb = new RFB(...)
rfb.resizeSession = true;
```

**Comment by maniac-tech** [comment]
So I have enabled both scaling and resize, but the stream seems broken when I do so:

```
this.rfb.scaleViewport = true;
 this.rfb.clipViewport = true;
this.rfb.resizeSession = true;

**Comment by maniac-tech** [comment]
> So I have enabled both scaling and resize, but the stream seems broken when I do so:
> 
> ```
> this.rfb.scaleViewport = true;
>  this.rfb.clipViewport = true;
> this.rfb.resizeSession = true;
> ```

So what I noticed is whenever I set the Scale property to true, the target childrens height is being set to 0, if I manually set the height once, the stream works just fine, and honors the resize too.

**Comment by maniac-tech** [comment]
> > So I have enabled both scaling and resize, but the stream seems broken when I do so:
> > ```
> > this.rfb.scaleViewport = true;
> >  this.rfb.clipViewport = true;
> > this.rfb.resizeSession = true;
> > ```
> 
> So what I noticed is whenever I set the Scale property to true, the target children's height is being set to 0, if I manually set the height once, the stream works just fine, and honors the resize too.

Apparently, the scale property within display is being set to 0 when setting scale to true 🤔
