### ISSUE TITLE
Reverse proxy Apache on WAN 

### ISSUE THREAD

**Issue by rendsolve** [novnc/noVNC#1193]
We have an Apache reverse proxy working.  

Our VNC server is 10.0.0.2 Proxied to www.web.com/vncws/vnc.html
We can connect to machines with www.web.com/vncws/vnc.html??host=10.0.0.3&port=6080 only locally.

The browser is looking for { IP } on local network of browser.  

We want to have the webpage access local machines over WAN. 
Is there a way to achieve this? Without proxing every client obviously.

We want all connections to be through 10.0.0.2 basically 

Working config below:
```
# VNC
ProxyPass /vncws                http://10.0.0.2:6080/
ProxyPassReverse /vncws         http://10.0.0.2:6080/
ProxyPass /websockify           wss://10.0.0.2:6080/websockify retry=3
ProxyPassReverse /websockify    wss://10.0.0.2:6080/websockify retry=3
#
```

**Comment by CendioOssman** [comment]
No. The browser needs to be able to reach every client somehow. Either by Apache proxying things to multiple websockify instances, or with a websockify as the proxy on the gateway machine and using tokens:

https://github.com/novnc/websockify/wiki/Token-based-target-selection

**Comment by CendioOssman** [comment]
You can also do a double proxy system by having Apache proxy to an internal websockify that uses tokens to proxy to each VNC server.
