### ISSUE TITLE
vnc_auto.html no focus to enter username + password

### ISSUE THREAD

**Issue by llelectronics** [novnc/noVNC#1194]
**Describe the bug**
The keyboard and mouse focus is not set to the novnc input after loading vnc_auto.html. 
So I need to first click into the window before I can enter the username and password to login.

**To Reproduce**
1. Go to 'vnc_auto.html'
2. Try start typing in your username
3. See that it does not work

**Expected behavior**
Like in the old version 0.4 (used in Debian Stable) onload it should auto focus so I can type in username and password without needing to click into the window first. 

**Client (please complete the following information):**
 - OS: Debian Linux
 - Browser: Chromium / Firefox
 - Browser version: 71 / 64

**Server (please complete the following information):**
 - noVNC version: 1.0.0
 - VNC server: x11vnc
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
`vnc_lite.html` now uses `prompt()`, which should grab focus. But it is an example file, so I would suggest using `vnc.html`. It also moves focus to the password dialog when it pops up. So please try the current `master`, or upgrade to 1.1.0 once we have it out.
