### ISSUE TITLE
Handle connection errors/incorrect password

### ISSUE THREAD

**Issue by OJ7** [novnc/noVNC#1195]
**Is your feature request related to a problem? Please describe.**
I'm using the [npm module](https://www.npmjs.com/package/@novnc/novnc) and I would like to handle the case where connection to a server fails and/or the user enters an incorrect password so I can present a message to the user. 
Currently I have no way of knowing if a connection failed to establish (I do have a way knowing if it was successful using the `connect` event though). I have tried the `disconnect` event and `securityfailure` event mentioned in [the API](https://github.com/novnc/noVNC/blob/master/docs/API.md) but those do not get fired on connection error.

**Describe the solution you'd like**
Below is how I'm creating the object currently. Either point me to the proper method of being notified of an error or add an error callback/event when creating a new RFB object. 
`new RFB(targetElement, 'ws://12.34.56.78:5900', { 'credentials': { password: 'password' } });`

**Comment by CendioOssman** [comment]
The `disconnect`even should always fire whenever the connection fails or is dropped. You'll also get a `securifyfailure` before that if the reason for the disconnect was some form of authentication problem.

How are you setting up the object and your event handlers?

**Comment by OJ7** [comment]
```
const password = ... // user enters password
const rfb = new RFB(targetElement, 'ws://12.34.56.78:5900', { 'credentials': { password } });

rfb.addEventListener('securityfailure', (detail) => {
    console.log('[securityfailure] -' + detail);
});

rfb.addEventListener('disconnect', (detail) => {
    console.log('[disconnect] -' + detail);
});

rfb.addEventListener('connect', () => {
    console.log('[connect]');
});
```

When entering a correct password, the VNC session works and I get `[connect]` printed in the logs.

When entering an incorrect password, I get `Failed when connecting: Connection closed (code: 1006)` and `[disconnect] -[object CustomEvent]` printed in the logs. (I previously wasn't getting the disconnect log because I was using `disconnected` instead). This gets me closer to my goal but the `securityfailure` event still is not firing.

**Comment by CendioOssman** [comment]
I am unable to reproduce the issue using your code. I get the following in my browser console:
```
[securityfailure] -[object CustomEvent] vnc_lite.html:183:5
Failed when connecting: Security negotiation failed on security result (reason: Authentication failure) rfb.js:666:17
[disconnect] -[object CustomEvent] vnc_lite.html:187:5
```
Your error message suggests a server issue where the server simply drops the connection rather than telling the client it failed to authenticate. Which server are you using?

**Comment by OJ7** [comment]
x11vnc version: 0.9.13, lastmod: 2011-08-10

**Comment by samhed** [comment]
Can we dismiss this as bad behavior from the x11vnc server?

**Comment by OJ7** [comment]
I've tried the native Mac VNC viewer and RealVNC Viewer and they both are able to detect incorrect passwords properly when connecting to the x11vnc server.

**Comment by CendioOssman** [comment]
I was able to reproduce it here. It only happens when using x11vnc's own WebSocket implementation, not when going via websockify.

The issue is that we have bugs when a message is split out over the WebSocket transport. Apply this patch and see things break left and right:

```diff
diff --git a/tests/fake.websocket.js b/tests/fake.websocket.js
index 2e1a3b9..1eef5d3 100644
--- a/tests/fake.websocket.js
+++ b/tests/fake.websocket.js
@@ -63,7 +63,10 @@ export default class FakeWebSocket {
     }
 
     _receive_data(data) {
-        this.onmessage(make_event("message", { 'data': data }));
+        for (let i = 0;i < data.length;i++) {
+            let buf = data.subarray(i, i+1);
+            this.onmessage(make_event("message", { 'data': buf }));
+        }
     }
 }
 
```

We need to go through the failed tests and fix things.
