### ISSUE TITLE
failed: Error during WebSocket handshake: Unexpected response code: 500

### ISSUE THREAD

**Issue by lansysnet** [novnc/noVNC#1196]
I'm using noVNC for Citrix XenServer'vm console. It works fine all the time utill I wanted to access the latest XenServer 7.1.2 using noVNC a few days ago, I got this error. Who can help me to fix the problem? Thanks very much!

**Comment by CendioOssman** [comment]
That code means "internal server error". So I'm afraid it's not something we can help you with.

I would suggest checking the server logs and see if you can find any more info about what went wrong. Perhaps there is some log settings you can also tweak. Other than that I'm afraid I'll have to point you towards XenServer's support forum.

**Comment by lansysnet** [comment]
Thanks all!

It is confirmed this is Citrix Xenserver's problem. I have tested XenServer 7.6 successfully today, it's OK! I can submit this issuse to Citrix for help.

Thanks again!
