### ISSUE TITLE
Add support for UltraVNC MS-Logon II credentials

### ISSUE THREAD

**Issue by rgl** [novnc/noVNC#1197]
UltraVNC as an extended credentials/security type called [MS-Logon II](http://www.uvnc.com/features/authentication.html). It lets one use local or domain account credentials with an username and password instead of the tradicional VNC password.

This would be a nice addition to noVNC.

**Comment by CendioOssman** [comment]
Agreed, that would be nice. Someone needs to figure out the protocol details first though and add them to @rfbproto. Hopefully it should be fairly simple to implement after that.

**Comment by CendioOssman** [comment]
There is also the VeNCrypt "Plain" authentication method that also supports username and password, as well as the XVP auth (which noVNC already supports).

**Comment by rgl** [comment]
It seems there's no formal documentation about the format, only the vncviewer code. From reading it, it seems to work like this:

```
server sends DH parameters and its A public value:
    U64 g (aka generator)
    U64 p (aka modulus)
    U64 A

client sends its DH B public value and the user plain-text username/password encrypted with the shared key (from the DH exchange):
    U64 B
    byte[256] DES(username, s)
    byte[64] DES(password, s)
```

I'm not sure if the DH and DES implementations are standard... but the rabbit hole starts at:

[void ClientConnection::AuthMsLogonII()](https://sourceforge.net/p/ultravnc/code/HEAD/tree/UltraVNC%20Project%20Root/UltraVNC/vncviewer/ClientConnection.cpp#l3291)
[void vncEncryptBytes2(unsigned char *where, const int length, unsigned char *key)](https://sourceforge.net/p/ultravnc/code/HEAD/tree/UltraVNC%20Project%20Root/UltraVNC/vncviewer/vncauth.c#l181)
[void deskey(unsigned char *key, short edf)](https://sourceforge.net/p/ultravnc/code/HEAD/tree/UltraVNC%20Project%20Root/UltraVNC/vncviewer/d3des.c#l72)
[void des(unsigned char *inblock, *outblock)](https://sourceforge.net/p/ultravnc/code/HEAD/tree/UltraVNC%20Project%20Root/UltraVNC/vncviewer/d3des.c#l152)

Can you guide me to where should I start implementing this on noVNC?

**Comment by rgl** [comment]
the MS-Logon II authentication is somewhat working at https://github.com/rgl/vnc2video but I had to take a detour and use the actual code from vnc to make it work... I'm scratching my head on why the normal DES implementation (from Go) does not work. Do you known why?

The [code that should have worked](https://github.com/rgl/vnc2video/commit/06bfc06929d47aee1cabcc497f2053784fff072c#diff-55103b8d471ccd5af796f97a27033629R150) is commented:

```go
func encrypt(cipherTextLength int, plainText []byte, key []byte) ([]byte, error) {
	out, err := exec.Command(
		"./ultra-ms-logon-2-encrypt",
		hex.EncodeToString(key),
		strconv.Itoa(cipherTextLength),
		string(plainText)).Output()
	if err != nil {
		return nil, err
	}
	return hex.DecodeString(strings.TrimSpace(string(out)))

	// XXX so the following code should have worked... but the vnc des
	//     implementation does not seem to be standard... so I had to
	//	   create an external application that uses the same C code as
	//     TightVNC/UltraVNC and that works... any idea why?
	// // create zero-padded slice.
	// cipherText := make([]byte, cipherTextLength)
	// copy(cipherText, plainText)

	// block, err := des.NewCipher(key)
	// if err != nil {
	// 	return nil, err
	// }

	// mode := cipher.NewCBCEncrypter(block, key)
	// mode.CryptBlocks(cipherText, cipherText)

	// return cipherText, nil
}
```

once this is cleared up I think we have enough to write this down on @rfbproto and implement it in noVNC.

**Comment by rgl** [comment]
For reference, some discussion about this was also started at https://forum.ultravnc.net/viewtopic.php?f=4&t=34796

**Comment by CendioOssman** [comment]
It might be that they are using the same DES implementation that is used for the classical VNC authentication. It uses a reverse bit order compared to most other DES implementations. There is a comment about it here:

https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#vnc-authentication

You should be able to test that theory by shifting the bits around before you give the data to Go's DES functions.

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by Neustradamus** [comment]
@pdlan: Thanks for your PR!
- https://github.com/novnc/noVNC/pull/1731
