### ISSUE TITLE
Port number limitations?

### ISSUE THREAD

**Issue by larryathey** [novnc/noVNC#1198]
Just wondering if there is a port number limitation that prevents noVNC from connecting.

For example, I have a whole bunch of Macs that establish reverse SSH tunnel connections to a Linux box. So, in the case of my Mac, port 5900 shows up as port 30001 on localhost of my Linux box that noVNC is running on.

If I telnet to localhost:30001 on the Linux box, I get the following:

$ telnet localhost 30001
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
RFB 003.889

From what I've read online, that is most definitely my VNC server on my Mac.

On the Linux box, there is no console output indicating anything other than the initial startup info, there is no output when I pull up the noVNC page. I'm using the following command to start noVNC:

$ ./launch.sh --cert ~/self.pem --ssl-only

Using local websockify at /home/ec2-user/noVNC/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080
/home/ec2-user/noVNC/utils/websockify/websockify/websocket.py:30: UserWarning: no 'numpy' module, HyBi protocol will be slower
  warnings.warn("no 'numpy' module, HyBi protocol will be slower")
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /home/ec2-user/noVNC
  - SSL/TLS support
  - Deny non-SSL/TLS connections
  - proxying from :6080 to localhost:5900

Navigate to this URL:

    https://ip-172-31-31-62:6080/vnc.html?host=ip-172-31-31-62&port=6080

Press Ctrl-C to exit

Then I go to https://172.31.31.62:6080/vnc.html?host=127.0.0.1&port=30001 which is my Linux box and the noVNC page loads just fine (still no console output on the Linux box indicating a browser connection).

I click on the Connect button in the middle of the page and I get the banner up at the top saying that it failed to connect to the server.

Here is the output in the Google Chrome console:

WebSocket connection to 'wss://127.0.0.1:30001/websockify' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
open @ websock.js:184
_connect @ rfb.js:398
_updateConnectionState @ rfb.js:628
rfb.js:230 WebSocket on-error event
RFB._sock.on.e @ rfb.js:230
_websocket.onerror @ websock.js:204
error (async)
open @ websock.js:202
_connect @ rfb.js:398
_updateConnectionState @ rfb.js:628
setTimeout (async)
RFB @ rfb.js:234
connect @ ui.js:1014
rfb.js:666 Failed when connecting: Connection closed (code: 1006)
_fail @ rfb.js:666
RFB._sock.on @ rfb.js:208
_websocket.onclose @ websock.js:199

**Comment by samhed** [comment]
I may be completely misunderstanding your setup here, but shouldn't you be starting websockify to proxy to port 30001 instead of 5900?

And the port in noVNC should be the port on which your Websocket proxy is running, not the port of your VNC server.

**Comment by larryathey** [comment]
Honestly, I don't know how websockify works since launch.sh is starting the whole thing, but I have tried that and it didn't change anything. Honestly, I thought that the host and port parameters included in the URL query string was an over-ride to the launch.sh host:port.

Perhaps noVNC isn't going to work for my purpose because I have over 100 Macs creating a reverse tunnel to this Linux box and need to connect to any of them at will. All of those Macs create listening ports on localhost starting at 30000. So I was hoping that noVNC would allow me to specify the desired port in the URL query string.

**Comment by CendioOssman** [comment]
noVNC cannot talk directly to VNC servers as it only speaks the WebSocket protocol. websockify is there to translate things. So I'm afraid you cannot point it directly at port 30001.

For your use case you need to either start one websockify per machine, or you need to use websockify's token system and modify the WebSocket path in noVNC instead:

https://github.com/novnc/websockify/wiki/Token-based-target-selection
