### ISSUE TITLE
noVNV how to connect Xenserver's vm?

### ISSUE THREAD

**Issue by LookingDreamer** [novnc/noVNC#1200]
vncview can do this,but noVNC is faild!

![image](https://user-images.githubusercontent.com/11344104/52828331-50dc9c00-30c0-11e9-9649-cc6ca7882c16.png)

![image](https://user-images.githubusercontent.com/11344104/52828280-1246e180-30c0-11e9-9ec7-2bda87c90327.png)

**Comment by CendioOssman** [comment]
Please fill out the fields from the issue template so we can know the details of your setup.

**Comment by LookingDreamer** [comment]
**Describe the bug**
noVNV cann't to connect Xenserver's vm

**To Reproduce**
Xenserver's ipaddress:  192.168.1.100
Xenserver version: 6.1
1. get Xenserver vm's vnc port
```
xenstore-read /local/domain/67/console/vnc-port
```
![image](https://user-images.githubusercontent.com/11344104/52923293-14c86600-3362-11e9-8cda-3e8ce37189bc.png)

2. start noVnc
```
cd noVNC
./utils/launch.sh --vnc 192.168.1.100:5926
```
![image](https://user-images.githubusercontent.com/11344104/52923325-3d506000-3362-11e9-8d36-c8c0f3f72138.png)

3. open chrome
![image](https://user-images.githubusercontent.com/11344104/52923352-58bb6b00-3362-11e9-91b2-8d1786c5c746.png)

4. See error
![image](https://user-images.githubusercontent.com/11344104/52923390-86a0af80-3362-11e9-9f2b-2bbe550b0f0e.png)

**Expected behavior**
noVNC can connect Xenserver's vm console successful

**Client (please complete the following information):**
 - Browser: chrome
 - Browser version: 72.0.3626.109

**Server (please complete the following information):**
 - noVNC version: 1.0.0
 - VNC server: QEMU
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
The line numbers don't match noVNC 1.0.0. Are you sure this is the version you are using? Have you made any modifications to it?

Could you start websockify with the recording feature and attach a recording here? Then we can test here and see what goes wrong.

**Comment by LookingDreamer** [comment]
Maybe it's my problem. I tried to reinstall,It has worked again. thanks !
