### ISSUE TITLE
The standard Error object is incorrectly overriden in the logging module

### ISSUE THREAD

**Issue by mykola-mokhnach** [novnc/noVNC#1202]
[Here](https://github.com/novnc/noVNC/blob/9e03a98182afe2db7197a6bbf936810eb24724da/core/util/logging.js#L43) we are trying to throw an error, but the corresponding variable is overridden before: https://github.com/novnc/noVNC/blob/9e03a98182afe2db7197a6bbf936810eb24724da/core/util/logging.js#L27

Also, I don't see any reason to use `bind` on `window.console`. For us this was breaking the Sentry integration.

**Comment by CendioOssman** [comment]
Thanks. Fixed in 47c66517ae3047dcc45877f8716e78fef143a3aa.

Using `bind()` is necessary to follow the specification as `window.console` is defined as an object. So calling any of its methods should include the object in `this`.
