### ISSUE TITLE
`this` context is not used properly inside clientCutText

### ISSUE THREAD

**Issue by mykola-mokhnach** [novnc/noVNC#1203]
https://github.com/novnc/noVNC/blob/9e03a98182afe2db7197a6bbf936810eb24724da/core/rfb.js#L1832

Here we are trying to invoke the `_fail` method of `RFB` class, but `this` points to the different context when `clientCutText ` method is called:

https://github.com/novnc/noVNC/blob/9e03a98182afe2db7197a6bbf936810eb24724da/core/rfb.js#L388

**Comment by CendioOssman** [comment]
Thanks. Fixed in b00a608af7a5e42c819a6cd15bb2ff7b8cce9f65.
