### ISSUE TITLE
Error reporting when launching.sh is executed

### ISSUE THREAD

**Issue by bj-white** [novnc/noVNC#1208]
[root@world noVNC]# ./utils/launch.sh --vnc  192.168.1.10:5900
No installed websockify, attempting to clone websockify...
Initialized empty Git repository in /root/noVNC/utils/websockify/.git/
error:  while accessing https://github.com/novnc/websockify/info/refs

fatal: HTTP request failed
Unable to locate /root/noVNC/utils/websockify/run after downloading

**Comment by samhed** [comment]
Closing duplicate issue.
