### ISSUE TITLE
Multiuser VNC Idea

### ISSUE THREAD

**Issue by dmonty2** [novnc/noVNC#121]
School District 73 deploys Linux desktops for Students/Staff at about 50 schools.  We offer them NX access to their desktops.  NX is proven very useful for home use as well as in-school mobile Windows and Mac devices.  However some users have difficulty getting the NX Client to work so I've always wondered about a web-based VNC type solution.  Below is the general idea for a multi-user vnc server:
1. End user browses to a web site ( like noVNC page ) and enters their username and password.
2. End user Is presented with their Linux desktop fitting nicely within the browser window.
## Back-end implementation.
1. Client Browser sends - username, password, and window dimensions to server.
2. Server (vnclauncher or vncdm):
   - Authenticates & logs in as that user.
   - Launches headless vncserver as that user using the client browser's dimensions.
   - Captures the listening port for their vnc session.
3. Server & Client negotiate the encrypted vnc session ( just like noVNC does already )
4. Cleanup/kill vncserver after user logs out or disconnects.

vnclauncher is like a display manager except instead of negotiating X sessions it negotiates vncserver sessions. (vncdm like a headless kdm gdm)

So far it is only an idea - I'm just happy to see noVNC code already does over half of what is needed to make it work.

**Comment by marcelobeckmann** [comment]
Hi, 
First of all thanks for your great job with noVNC.

Now we are in 2015, do you know some advance in this subject. Now does noVNC project aim to provide multiple users support?

Even if we have a multi-user vncserver, the noVNC screen will be able to handle this now?

Thanks in advance,

**Comment by DirectXMan12** [comment]
I'm unsure as to what you mean, in this case, by multi-user.  noVNC itself will certainly support multiple connections to the same desktop (I've done this myself when testing performance across different browsers simultaneously), but it works best if all connections but one are in read-only mode.

As for connecting to different desktops based on authentication, noVNC currently supports the standard VNC authentication (password only), as well as the XVP Authentication method (used with XVP).  Hypothetically, you could differentiate based on passwords, use the password field as both a username and password field (e.g. 'username:password').  If you have another security type that is supported by a common server, we'd be willing to accept a patch to support that.
