### ISSUE TITLE
[help] nginx proxy ->> websockify/novnc + token plugin 

### ISSUE THREAD

**Issue by al3x609** [novnc/noVNC#1210]
Hi, I have a problem with the configuration nginx/noVNC/websockify/token plugin

this is my configuration

case 1:

only noVNC/websockify + token plugin

` python run --token-plugin=TokenFile --token-source=/Users/alex/Devel/noVNC/websockify/tokens/  -v  --web=/Users/alex/Devel/noVNC/  localhost:6080`

my URL request:

`http://localhost:6080/vnc.html?path=?token=1234/`

token:
`1234/: localhost:5900`

> _this works fine_

____

case 2
 nginx + noVNC/websockify  without token, 
```
nginx config:

    server {
        listen       80;
        server_name  localhost;

        location /yaje/ {
            rewrite ^/yaje/(.*) /$1  break;
            proxy_pass http://localhost:6080/;

        }
 }
```

websockify setup.

` python run  localhost:6080  localhost:5900`

url request:

`http://localhost/yaje`

> this work fine.

____
case 3. 

nginx + noVNC/websockify + token plugin. 

 _when i launch websockify with token plugin/path_file as the case 1,  fail_ 

my url request in this case:

`http://localhost/yaje/?path=?token=1234/`

![image](https://user-images.githubusercontent.com/4086644/53295269-9d615f00-37c5-11e9-83c6-a73c6493ee3a.png)

I think that the issue is the proxy to port:6080...  nginx proxy no change the port in the URL.

![image](https://user-images.githubusercontent.com/4086644/53300204-f8b93e80-3811-11e9-9b9c-32066d35e0af.png)

but I do not know how to correct it

How I can to configure nginx for proxy to websockify + token plugin?

 noVNC/websockify version = 1.0.0

nginx version: nginx/1.15.8

OS: macOS 10.14

**Comment by al3x609** [comment]
I want this configuration because:

on production this is the config

internet  -->     [A] ---> [B]

machien [A] 
 - public ip, nginx 

machine [B]
 - noVNC/websockify + token plugin

I can not to move noNVC/websockify to [A], because:

in [B], I have multiple containers [app/vnc]  for micro services through a container with [novnc/websockify]

**Comment by CendioOssman** [comment]
This is a nginx question, so it is a bit outside what we can help you with. That said, your path argument looks wrong as you've dropped the `websockify` portion of it. I would guess that `http://localhost/yaje/?path=websockify?token=1234/` would work better.
