### ISSUE TITLE
Image failed to load

### ISSUE THREAD

**Issue by vast0906** [novnc/noVNC#1212]
**Describe the bug**

**To Reproduce**
1. start novnc
2. open the chrome and to novnc
3. See error

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: [e.g. iOS]  debian9
 - Browser: [e.g. chrome, safari] chrome
 - Browser version: [e.g. 22]  71.0.3578.98

**Server (please complete the following information):**
 - noVNC version: [e.g. 1.0.0 or git commit id] 1.0
 - VNC server: [e.g. QEMU, TigerVNC]  QEMU
 - WebSocket proxy: [e.g. websockify]  websockify-0.8.0

**Additional context**

![image](https://user-images.githubusercontent.com/18095287/53557885-dca2fd80-3b81-11e9-8373-5ed7ed9485b7.png)
![image](https://user-images.githubusercontent.com/18095287/53557942-fe03e980-3b81-11e9-932a-8dba78a311d4.png)

I see the log not found 404
![image](https://user-images.githubusercontent.com/18095287/53557989-14aa4080-3b82-11e9-9e34-30fc941e9782.png)

Sorry, my English is very bad.

**Comment by samhed** [comment]
Are you browsing to the URL presented by websockify or are you using your browser to view the html files directly? Does everything else work as expected, like connecting to the VNC server using noVNC?

**Comment by vast0906** [comment]
browser to view the html @samhed

**Comment by samhed** [comment]
If we understand each other correctly then that is likely the issue.

Things will not work if you browse directly to the files on your machine. You will need to browse to the URL provided by websockify.
