### ISSUE TITLE
Keyboard not captured on reconnect

### ISSUE THREAD

**Issue by mholzel** [novnc/noVNC#1213]
Issue:

I start a container with `xvfb` and `x11vnc` in a Docker container. Inside the Docker container, I have something running which requires keyboard input (e.g. either `xterm` or I start `xfce`). When I connect to this container on the host machine the first time, everything works fine. However, when I either refresh or  close and reopen the tab running `vnc.html` on the host machine, the keyboard no longer works, and I cannot figure out how to recapture the keyboard.  

I thought that this was an x11vnc problem, but I have tried playing around with the `shared` vs `nevershared` flags for that with no effect on the output. So I believe that the issue lies with noVNC. 

Is this a known bug? I am not 100% sure that this is actually a noVNC problem, so if there are some steps you could suggest to isolate the issue, I am all ears... 

Running the host on Ubuntu 18.04. Trying to run a Debian 9.7-slim image in Docker.

**Comment by samhed** [comment]
Does it work if you click in the session after refreshing the browser tab? The noVNC_container needs focus in your browser.

**Comment by mholzel** [comment]
I am giving the noVNC container focus.

**Comment by samhed** [comment]
Ok.

In your remote session, in for example xterm, are you getting mouse input? What does the output from the command `xev` say when you try to send keyboard/mouse?

I haven't heard about this issue before and I would say that it's likely that it's a server side issue. Do you have an opportunity to test with a different VNC client?

**Comment by mholzel** [comment]
I was getting mouse output. Sorry. The issue turned out to be `x11vnc`. It seems that running `x11vnc` with the `-noxkb` options fixed the problem for me.

**Comment by samhed** [comment]
Good to hear that you found a solution.
