### ISSUE TITLE
vnc.html badly formatted

### ISSUE THREAD

**Issue by devnullpointer** [novnc/noVNC#1214]
**Describe the bug**
Badly formatted vnc.html is causing issues when trying to embed novnc into web applications.

**To Reproduce**
1. Use your favorite text editor and open vnc.html
2. notice all the <link> tags have no closing </link> tag or don't end with />

**Expected behavior**
A properly formatted html document, maybe use a strict dtd reference?

**Client (please complete the following information):**
 - OS: ALL
 - Browser: ALL
 - Browser version: ALL

**Comment by samhed** [comment]
You are right, `vnc.html` needs to be looked at.

**Comment by devnullpointer** [comment]
thanks for looking at it and placing it in the next milestone. vnc_lite.html should also be included in that as well.

**Comment by samhed** [comment]
Should be fixed now.
