### ISSUE TITLE
An undefined behaviour is observed due to zero division in autoscale method

### ISSUE THREAD

**Issue by mykola-mokhnach** [novnc/noVNC#1216]
https://github.com/novnc/noVNC/blob/9a823732a01af080357669d12d355cdc8e7e099c/core/display.js#L498

Both `containerHeight` and `containerWidth` arguments could be zero in `autoscale` method, which causes division to zero. Such situation is currently "handled" by javascript forgiveness, but I assume it could be processed better by adding an explicit condition there (or/and a warning log).

**Comment by samhed** [comment]
Thanks, fixed in 6e7e6f9c9ed3367ecaa80f78a512187a7ae95eb4
