### ISSUE TITLE
[helpful] add discreet version number in side menu

### ISSUE THREAD

**Issue by pm-pm** [novnc/noVNC#1222]
**Is your feature request related to a problem?
Not really.

**Describe the solution you'd like**
Please add a version number in side menu. (discreet would be fine) :-)

This is helpful when testing new versions in parallel. In the moment you can differentiate 1.0.0 vs. 1.1.0 easily by the new "window key icon" .

**Comment by samhed** [comment]
It's not a bad idea. What if it showed when you hovered the noVNC logo in the side menu?

**Comment by pm-pm** [comment]
Hello samhed,

that would be a cool Feature, but hovering is "to difficult" if you do (family) telephone support and ask "whats the number on your display." ;-) You have to explain where to put the mouse, etc. ... 

I would prefer something like this:
![nv110](https://user-images.githubusercontent.com/47995430/55838425-bd09d800-5b24-11e9-910f-3ee21ba095a9.png)

Of course you can decide what you like. :-)

Thanks

**Comment by CendioOssman** [comment]
Maybe we should have an About dialog? We could have a button that opens in on the bar in that case.

**Comment by samhed** [comment]
@pm-pm, I see what you mean. @CendioOssman yes, perhaps that would be the best solution.

**Comment by pm-pm** [comment]
Just keep it simple. ;-)

**Comment by samhed** [comment]
Fixed with #1265

**Comment by samhed** [comment]
As a side note - we should probably mark development versions of noVNC as X.Y.Zpost or something similar. Since right now, if you learn to depend on that version number in the settings you can't differentiate the proper 1.1.0 release from the current master for example.
