### ISSUE TITLE
Novnc not refreshing quickly.

### ISSUE THREAD

**Issue by springware** [novnc/noVNC#1223]
I am highly satisfied with NoVNC and I love it.
But I have faced in technical issues here.
NoVNC & RealVNC server is working perfectly.
But for Ultra & Tight VNC, novnc is not working properly.
That means novnc does not get clean screen.
for example when I drag the mouse to show rectangle area, it does so many lines including that rectangle.
Does this concern with framerate?

anyone can help me?

**Comment by CendioOssman** [comment]
Unfortunately issues with updates are usually server problems. The fact that noVNC works will with RealVNC further suggest that this is the case.

Could you get a screen shot or video of what you are seeing?

**Comment by samhed** [comment]
No response
