### ISSUE TITLE
too many js files, is it possible to compress all js into one ?

### ISSUE THREAD

**Issue by di3663** [novnc/noVNC#1224]
**Is your feature request related to a problem? Please describe.**
too many js files

**Describe the solution you'd like**
one compressed js file ?

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by di3663** [comment]
and I hava written a go proxy, not sure if it's right but it seems working.

https://raw.githubusercontent.com/di3663/noVNC-1.1.0-modify/master/main.go

**Comment by pm-pm** [comment]
I am against using compressed files. I need to modify the js files and this is only possible with uncompressed files.

**Comment by di3663** [comment]
> I am against using compressed files. I need to modify the js files and this is only possible with uncompressed files.

of course you are, i means a mthod to generate one compress js file so it's simple to deploy noVNC.
