### ISSUE TITLE
Write additional quick-start documentation

### ISSUE THREAD

**Issue by peteroupc** [novnc/noVNC#1225]
**Is your feature request related to a problem? Please describe.**
Besides the Quick Start section in the README, there is very little information on how a user can get started quickly on connecting to a remote desktop from another computer using noVNC and their VNC server of choice.

**Describe the solution you'd like**
Here is an example scenario I would like the documentation to cover:

- Assume the existence of two computers (Server and Client), which may run different operating systems. Both Server and Client are located in the same room.
- The user wishes to install their favorite VNC server on Server.
- The user wishes to use noVNC on Client to access Server's desktop via the VNC server.
- The user wishes to establish a secure VNC connection between Server and Client.

Given the scenario above, I would like to see documentation that answers the following questions:

- What steps have to be taken to set up a secure connection between Server and Client? (The quick start script sets up an insecure connection by default and there is no documentation on what steps are required to use a secure connection instead.)
- What information does Client need to access Server?  If Client can't readily use Server's computer name, can it use Server's IP address instead?  If so, how can the user get Server's IP address?
- The quick start script requires knowing the "location of a running VNC server".  How can the user get that information from their favorite VNC server?
- What other information does the user need to know to use noVNC smoothly with their favorite VNC server?

This issue thread is not the place to answer these questions; rather, you should write additional documentation that does so.

**Comment by samhed** [comment]
> What steps have to be taken to set up a secure connection between Server and Client? (The quick start script sets up an insecure connection by default and there is no documentation on what steps are required to use a secure connection instead.)

The answer here depends on the WebSocket proxy that you use. The quick start script uses Websockify, but that isn't part of noVNC, and there are VNC servers that has a built in WebSocket proxy.

Here's documentation for Websockify regarding encrypted connections: https://github.com/novnc/websockify/wiki/Encrypted-Connections

> What information does Client need to access Server? If Client can't readily use Server's computer name, can it use Server's IP address instead? If so, how can the user get Server's IP address?

This doesn't really seem noVNC related, could you elaborate on why you think this is necessary?

> The quick start script requires knowing the "location of a running VNC server". How can the user get that information from their favorite VNC server?

Using virtually any client requires knowing the address of a server. But perhaps we could include the default ports on which the most popular VNC servers run.

**Comment by peteroupc** [comment]
> 
> > What information does Client need to access Server? If Client can't readily use Server's computer name, can it use Server's IP address instead? If so, how can the user get Server's IP address?
> 
> This doesn't really seem noVNC related, could you elaborate on why you think this is necessary?
> 
Consider the case where Websockify is installed on Server.  The URL that Websockify will output will have the following form: `http://Host:0000/ ... host=Host ...`, but depending on the circumstances, it may not be as trivial for Client to access Server by the computer name `Host` than if `Host` (in the URL just given) were replaced with Server's IP address instead.

**Comment by peteroupc** [comment]
> 
> 
> > What steps have to be taken to set up a secure connection between Server and Client? (The quick start script sets up an insecure connection by default and there is no documentation on what steps are required to use a secure connection instead.)
> 
> The answer here depends on the WebSocket proxy that you use. The quick start script uses Websockify, but that isn't part of noVNC, and there are VNC servers that has a built in WebSocket proxy.
> 
> Here's documentation for Websockify regarding encrypted connections: https://github.com/novnc/websockify/wiki/Encrypted-Connections
> 
> > What information does Client need to access Server? If Client can't readily use Server's computer name, can it use Server's IP address instead? If so, how can the user get Server's IP address?
> 
> This doesn't really seem noVNC related, could you elaborate on why you think this is necessary?
> 
> > The quick start script requires knowing the "location of a running VNC server". How can the user get that information from their favorite VNC server?
> 
> Using virtually any client requires knowing the address of a server. But perhaps we could include the default ports on which the most popular VNC servers run.

**Comment by samhed** [comment]
> That would be good to note in the README to this repository.

The section just above the "Quick Start" already mention the requirement of a WebSocket proxy:
https://github.com/novnc/noVNC#server-requirements

If you are talking about a link to setting up encrypted connections for websockify, I disagree. That is a different project, and details for configuring websockify belong in it's wiki, like it is now.

> Consider the case where Websockify is installed on Server. The URL that Websockify will output will have the following form: http://Host:0000/ ... host=Host ..., but depending on the circumstances, it may not be as trivial for Client to access Server by the computer name Host than if Host (in the URL just given) were replaced with Server's IP address instead.

If you can't use the hostname, your server isn't set up properly, that's why it can't be used from a different machine.

In most cases `hostname` should, locally on the server, be set to the same name as it will be reachable as from other machines. Then you need to map the server ip to the hostname in your DNS or in `/etc/hosts` on your client.

If you also want to use TLS to get encrypted connections you will run into problems. TLS doesn't work with IP addresses.

**Comment by samhed** [comment]
I believe these questions have been answered.

With regards to adding more information to the README - these things are not suitable for that document in my opinion. I'm closing this.
