### ISSUE TITLE
token in cookies

### ISSUE THREAD

**Issue by xiaoqianghaochi** [novnc/noVNC#1228]
How to use token in cookies，not in url query;

**Comment by al3x609** [comment]
The token isn't for user authentication or client session data storage, instead is for server side traduction Ip:port vnc session.

**Comment by xiaoqianghaochi** [comment]
bug，our project use token as sessionId；so want to use cookies。

**Comment by CendioOssman** [comment]
That is really a question for websockify, not noVNC. But I'm afraid it does not support tokens via cookies right now. Feel free to submit a patch though.
