### ISSUE TITLE
?token=fubar no longer works in 1.1.0

### ISSUE THREAD

**Issue by braincow** [novnc/noVNC#1232]
**Describe the bug**
Using version 1.0.0 release passing ?token=fubar in GET variables passes it along to websockify. When using 1.1.0 release ZIP this no longer seems to work and websockify is called without token.

**To Reproduce**
Use ?token= with version 1.1.0 to not pass token to websockify.

**Expected behavior**
Using ?token= in GET variables for example in vnc_lite.html or vnc.html will call websockify with ?token= variable as well.

**Server (please complete the following information):**
 - noVNC version: 1.1.0
 - VNC server: tightvnc
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
I'm afraid support for that method has been removed as it was not standardised. You can still get the same functionality by specifying an appropriate `path` value in the URL.

**Comment by braincow** [comment]
@CendioOssman but how to parse the token information at Websockify end from the path component? Websockify's token plugin architecture expects to find the token.

**Comment by CendioOssman** [comment]
No changes are needed in websockify. You can include any query variables you need in the path. You just need to escape them. E.g. `https://example.com/vnc.html?path=/websockify%3Ftoken%3Dfoobar`.

**Comment by braincow** [comment]
@CendioOssman, ok thank you for quick reply. It seems "a lot of" people are using this functionality and this change and your fix proposal should be documented somewhere.
