### ISSUE TITLE
Is noVNC 1.1.0 working with Edge Browser on W10?

### ISSUE THREAD

**Issue by pm-pm** [novnc/noVNC#1233]
**Describe the bug**
On Windows 10 with **Edge Browser** only the 3 point running on the screen. No connection/password window. Same Windows 10 computer with IE11 is working!!

**To Reproduce**
Try to connect to noVNC with working configuration. (Working wit IE11 and FF)

**Expected behavior**
Should connect and show password box

**Client (please complete the following information):**
 - OS: Windows 10 with Edge.
About Information:
_Microsoft Edge 41.16299.1004.0
Microsoft EdgeHTML 16.16299_

Note: Same Windows 10 computer with IE11 is working!!

**Server (please complete the following information):**
 - noVNC version: 1.1.0
 - VNC server: tigervnc 1.8

**Summary:**
noVNC 1.**0**.0 + W10: FF ok, IE ok, Edge ok
noVNC 1.**1**.0 + W10: FF ok, IE ok, Edge **NOT** ok

**Can someone please verify this. **
Thanks

**Comment by CendioOssman** [comment]
I'm not seeing any issue when testing here. I have a somewhat newer Edge though, version 44. Could you make sure everything is fully upgraded and see if that helps?

If not, please open the web console before loading the page and see if you get some errors.

**Comment by pm-pm** [comment]
No, i can not upgrade the company computer, i have to wait until the update is released. :-/
But interesting to read that noVNC 1.1.0 + Edge +W10 work.

I will check here again.
Thanks.

**Comment by samhed** [comment]
noVNC 1.1.0 on Edge 44 works well for me too.

**Comment by samhed** [comment]
no response

**Comment by pm-pm** [comment]
I have still the problem on W10 with Edge 41.16299.1419.0
Until today there is no offcial update on our company computer.
Today i tested with latest novnc "master" release. Still the same problem: No connect.

Edge Browser
1.0.0: ok
1.1.0: not working
master: not working.

With IE11 browser everything works.

Has some a hint how to debug this problem?

**Comment by CendioOssman** [comment]
I'd advise checking the browser console and see if there are any errors. Other than that I'm afraid you need to look at how you can get that machine upgraded. There are two major updates to Edge since then, and an even bigger one coming any day now. We don't have the resources to maintain support for the older versions as well.

**Comment by pm-pm** [comment]
Hello CendioOssman,
of course you should not maintain this old Edge version. :-)
Unfortunately Updating is not an option. This company is too big to force a decision. We have to live with what the IT department rolls out. The computer is more or less "locked up".

In the Edge console i only see some proxy errors, BUT these errors are the same with working version 1.0.0 and not working version 1.1.0. That doesn't seem to be the problem.

Other errors i can not see. I'll keep trying to find the problem. If you still have good ideas please write here. :-)

Thanks.

**Comment by samhed** [comment]
Those are almost the exact same versions of Edge you mentioned in your first post. And that version is almost 3 years old. Recent versions of Edge works perfectly fine for us.

**Comment by pm-pm** [comment]
Now my PC received W10 **1809** Build 17763.107
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

noVNC works fine in all versions. :-)
Version 1.0, 1.1 and pre1.2 work as aspected. :-)

Now I can say that it is not a problem of special company configuration, but a problem of the edge browser. Why this is the case remains in the dark.

_This post is just for documentation purposes._

Many thanks to all who develop this great program. :-)

**Comment by samhed** [comment]
Ok - so Edge had some bug. Good to hear that things are working for you now!
