### ISSUE TITLE
Rich cursor feature makes the cursor to blink randomly if the remote server is TightVNC

### ISSUE THREAD

**Issue by mykola-mokhnach** [novnc/noVNC#1235]
I don't quite understand the reason for that, but TightVNC server on Windows 10 machines regularly (like once per 3-4 seconds) resets the cursor dimensions to zero, which makes the local cursor in noVNC client to blink by changing its shape to nothing (or dot-cursor if enabled) and back. My first idea was to disable cursor shape refresh in https://github.com/novnc/noVNC/blob/2b2b6073dd6e9b6b3bef0d65797bbe16b026f362/core/rfb.js#L1683 if `rgba.length` is zero to avoid such behaviour, but maybe there is a better way to handle such behaviour?

https://github.com/DukeyToo/tightvnc-server/blob/a48d6f6f96449a591c4c15589cb1877d5e2a991c/fb-update-sender/CursorUpdates.cpp#L124
https://github.com/DukeyToo/tightvnc-server/blob/a48d6f6f96449a591c4c15589cb1877d5e2a991c/desktop/WinDxgiOutputDuplication.cpp#L190

![screen](https://user-images.githubusercontent.com/7767781/57127792-c12abd80-6d91-11e9-8896-5b04a859b004.png)

**Comment by samhed** [comment]
Are you sure the issue is noVNC specific? Maybe noVNC is doing exactly what the server asks it to do. Did you test with different VNC viewer?

Or are you thinking this is a server bug and are asking for a way work around it?

**Comment by mykola-mokhnach** [comment]
This might be a server bug, although I cannot confirm it. Also, having such workaround will not break anything in the current client logic, but will rather just make it more stable.

**Comment by CendioOssman** [comment]
The workaround will break the ability of the server to hide the cursor, so unfortunately it's not really something we can add.

If that workaround works then it would confirm that the server is indeed sending a bogus update. So I'm afraid I'll have to point you to file a bug with TightVNC. This is really something they need to fix in their end.

**Comment by CendioOssman** [comment]
Both methods exists. I think it largely depends on how the operating system on the server behaves.
