### ISSUE TITLE
Question: noVNC as proxy to several VNC instances

### ISSUE THREAD

**Issue by andreisusanu** [novnc/noVNC#1237]
Here is my scenario:

1. The web application is embedding noVNC.
2. A set of remote machines with VNC server installed.
3. The VNC machines firewall allows only the web application (not the clients) to connect. So the client has no direct access to the VNC machine, only the machine holding the web application has access to the VNC machines.
4. From the web application, the clients should be able to connect to the remote VNC machines via noVNC.

Is this doable?
Thanks!

**Comment by samhed** [comment]
Yes it should be - easiest would probably be if you used a VNC server with a built in WebSocket proxy like Qemu or libvncserver. If you were using a different VNC server with Websockify for example you would need to have a separate instance of Websockify per VNC server.

As you have probably seen in noVNC's vnc.html, you can then point out different WebSocket proxies to which you will connect.
