### ISSUE TITLE
something went wrong ,connection is closed when I use the novnc

### ISSUE THREAD

**Issue by axuwanquan** [novnc/noVNC#1238]
Now I am playing openstack with two pods.

I use "nova --os-region-name=RegionOne get-vnc-console vm1 novnc" to launch VNC console. 

I get the url for connect my vm1 and I copy this URL in Firefox.But it shows that something went wrong ,connection is closed.

Please help me .I feel confused now.

Thanks a lot!!!!!

**Comment by samhed** [comment]
Please use our issue template.

**Comment by samhed** [comment]
We need more information in order to be able to help you @axuwanquan. I'll be closing this issue now, but feel free to re-open if you want to provide more info.
