### ISSUE TITLE
Failed to start WebSockets proxy

### ISSUE THREAD

**Issue by MortZx** [novnc/noVNC#1239]
I have a small embedded device running Linux armv71. My goal is to remotely access the screen through a web browser with a mobile device. I have x11vnc running which I thought supported access through web browsers but I couldn't get it to work until I was told I needed a proxy for web access. I was recommended noVNC so here I am trying to get this to work :p 

I first startup x11vnc (I have a copy of the output if it helps) and then I launch novnc which gives the following output:
![image](https://user-images.githubusercontent.com/36338032/57927438-f3fea680-78a5-11e9-9473-0ff3ede09539.png)

I thought typing in my web browser (chrome) the URL given by novnc (< remoteIP>:5900) would connect  but I just get an invalid response. However, if I type "< remoteIP>/vnc.html", I get to the noVNC login screen and from there I have access to my screen! 

My (Windows) computer and my remote device are on the same networks so that probably helps. when I try to access the noVNC login page with my iPhone6 using Safari, I don't get a response from the server. I guess the problem is with the WebSockets proxy failing to start ...

Any help with this would be much appreciated!

**Comment by MortZx** [comment]
I feel a bit foolish now but the simple fix was making sure the remote and local devices were on the same network.  👍 
However I'm still not sure why WebSockets proxy failed to start and what it should do ..

**Comment by samhed** [comment]
Just to clarify for posterity, noVNC is not a WebSocket proxy, noVNC's launch script makes use of the proxy called 'Websockify'.
