### ISSUE TITLE
Connecting to a Windows Container

### ISSUE THREAD

**Issue by mukulagrawal78** [novnc/noVNC#1240]
I have an application running on Windows Server container.
Can I get the graphics generated in the container to a remote client using novnc ? 

I can control how to start the container but prefer not to install anything inside container.
I can install anything required on host that is running the container.

**Comment by samhed** [comment]
noVNC is just a VNC client. In order to do what you're asking you would need a VNC server and a WebSocket proxy on your windows machine.
