### ISSUE TITLE
Tunnelling web and file links with a bilateral communication mechanism

### ISSUE THREAD

**Issue by robertpetry** [novnc/noVNC#1241]
I'm putting together a Linux virtual machine image that my students can use that will contain an open textbook I create that contains links to files served locally on the system and the ancillary software to work with them.  Such files would include multimedia files (videos, podcasts, etc.) as well as computer code, spreadsheets, etc.

For students who do not have computer hardware that can run the virtual machine I want to serve the distribution myself and allow them to connect via noVNC through their browsers to a Linux session.  This would work fine for a spreadsheet or code example.  However due to the limitations of VNC with regard to sound and video transfer quality the latter experience would be poor for multimedia files.  Since such students are using a browser to connect to noVNC already, it makes more sense that multimedia files would be rendered directly via their browser plugins with the files being pulled directly from a web server I am running on the backend.  So instead of running the multimedia player locally students connected via noVNC should instead have their browsers redirected (open a popup or a new tab or whatever) with a URL to the multimedia file on my webserver. Thus what I would like is for my remote Linux machine to be able to pass a link to noVNC that would direct the connected browser to open that link, thereby serving the multimedia file through the student's browser.

It would also be convenient if, when connecting via noVNC I could pass information the other way too, namely from noVNC to the Linux machine running the VNC server.  As a simple example of this I could pass along a path to a file on the Linux system via a query variable in my noVNC connection.  Then my Linux backend could identify the mime-type and automatically run the appropriate application on the local file when the connection was completed.

One method to facilitate this bilateral communication from noVNC to the backend machine running the VNC server would be through the clipboard.  Essentially one could temporarily save the clipboard contents and then inject the desired command (web link or file path or indeed whatever information) preceded by some noVNC magic characters into the clipboard.  The magic characters would indicate that this was for such special communication.   Both sides would monitor the clipboard accordingly looking for these commands and, once received acknowledge this back into the clipboard so that whatever side made the request could restore the original clipboard contents.  Potentially the acknowledgement could include information as to whether the command was successfully executed.  (So for instance if the popup was blocked by the connected browser a failure could be returned so the backend could act accordingly.  Similarly if the browser did not have support for the mime-type this could somehow be detected and communicated back as a failure.)

There may be better ways to implement this bilateral communication than the clipboard.  I am largely ignorant of the VNC protocol capabilities but the idea of using the clipboard appealed to me because I know there is a Python library as well as other executables on a Linux system that easily allow for clipboard manipulation and I know on the noVNC side of things the clipboard is actively monitored already.  Also I imagine most VNC servers would support clipboard communication.  One drawback may be limitations of character set supported by the clipboard for some web links, but even there I imagine there would be ways to encode the request into whatever characters are supported by suitably packing or unpacking the communication stream on either end.

So as a minimal implementation that would meet my requirements I would imagine the following:
1) An internal variable in noVNC to enable/disable the bilateral communication
2) A variable that could be set upon connection to noVNC via a query to pass a file link (or indeed any other information) to the VNC server backend via the clipboard.
3) A set of actions that the noVNC application would support.  For now just opening a new tab/popup or perhaps redirect for a weblink injected into the clipboard by the machine running the server.
4) A sample daemon written in Python for the server side for monitoring communication such as for opening a file link as I suggested or perhaps running an actual command.  Obviously the user can write this but a minimum working example would be useful to illustrate the implementation.
5) Perhaps if one wished to implement this communication through various methods other than just the clipboard, there could be a protocol variable that could be set in noVNC as well to identify the method used.

Thanks in advance for thinking about this.  noVNC as a browser based interface admits for these interesting possibilities.  If there is already some way to do this in noVNC or some other mechanism I should be considering I would appreciate the advice.  I imagine the implementation of such a bilateral communication mechanism could have broader application than my own and likely should be designed by your team if you think the idea has merit.

**Comment by samhed** [comment]
> If there is already some way to do this in noVNC or some other mechanism I should be considering I would appreciate the advice.

Nope, no such mechanism exist.

> I imagine the implementation of such a bilateral communication mechanism could have broader application than my own and likely should be designed by your team if you think the idea has merit.

Hm, it sounds like quite a specialized solution to me. Besides, not myself nor any other member of the noVNC team will likely have time to work on something like this I'm afraid.

**Comment by samhed** [comment]
I think you're on your own for this one. We would be happy to help by answering questions about noVNC along the way.

**Comment by CendioOssman** [comment]
To add to this, we are just a client project. Improvements like this would also need server support. So generally it's not something we can do. But if a server adds support for new features, we can look at adding the client side of things in noVNC.

**Comment by robertpetry** [comment]
Hi folks,
Thanks for considering my suggestion.  I'm not sure I entirely understand Cendio's last comment.   The mechanism I am suggesting for communication to the backend machine uses the clipboard which is already presumed to be supported by the VNC server.  On the backend one has to be running some process on the machine looking for these messages appearing in the clipboard to act on them.  Similarly  the injecting of web links into the clipboard would need to be done by processes on the machine running the VNC server.  However none of this involves the VNC server itself other than the latter has to support the clipboard protocol and presumably have it turned on.  I admit my suggestion is a bit of a hack and that there might be a better mechanism even within the current VNC protocol that could be adopted for this communication (say a secondary clipboard or somesuch).  However the suggestion (I think) is completely doable now with the clipboard mechanism suggested and a few changes to the noVNC frontend that were proposed.

With regard to the actual utility of the idea largely being one that would of only be of use to me, I guess my thinking was motivated by other comments I had read about people wrestling with how they could transfer sound or better video quality through VNC.  What's so interesting about your project is that because the connection is browser-based it makes possible (I think) the ability to facilitate web connections to other web-based services (such as a multimedia file server sitting on the backend) for some of the situations where the VNC connection has limitations.  (Also from a service perspective it allows one to push the work onto the web browser - in this case the processing of the multimedia file.)   While my immediate application was to get some of this multimedia material served better to students, one can imagine other scenarios where having the backend connect the browser to other services could be of use to people.  Indeed ANY weblink that was to be opened on the backend should more naturally be being opened on the actual browser connected to noVNC than in a browser on the server side.  I think this mechanism would allow for that possibility.  

Since I'm here again, I just wanted to thank you all for creating this project.  I have to say I was mildly astounded the first time I tried it out.  If nothing else I think our discussion may help others solve similar problems to mine using your code base.

Thanks again!
