### ISSUE TITLE
Connect to remote device only using IP as URL?

### ISSUE THREAD

**Issue by MortZx** [novnc/noVNC#1242]
I don't know if this is possible but ideally I'd like to connect to my shared screen using only its IP address in the URL bar. 

I found in a separate issue that by adding the command option `--listen 80` you do not have to add the port number to the URL to access it. This opens the web page with the directory listings for all items in the root directory of noVNC. Normally I would instead use `remoteIpAddr/vnc.html OR remoteIpAddr/vnc_lite.html".

Is there a file I can edit, or another method, to automatically open the "vnc.html" or "vnc_lite.html" link when I reach the directory listing page?

**Comment by samhed** [comment]
Yes, just rename the .html file to index.html. That should do the trick.

**Comment by MortZx** [comment]
Thanks, that worked like a charm!
