### ISSUE TITLE
red shift is not 16 & blue shift is not 0

### ISSUE THREAD

**Issue by springware** [novnc/noVNC#1246]
I am really appreciate noVNC producers.
I used novnc with server from windows/linux/osx systems and it pretty works well.
But I have a problem with android vnc server. I am using droidvncserver.
I am getting following errors:
red shift is not 16
blue shift is not 0
can you help me?

**Comment by CendioOssman** [comment]
Those are just warnings that there might be some conversion overhead for the server and do not indicate any kind of error.

What problem are you seeing?

**Comment by springware** [comment]
I only can see black screen.

**Comment by springware** [comment]
I am using novnc 1.1.0(latest version). But I am not sure where the problem is.. droidVncServer or novnc.

**Comment by springware** [comment]
I saw that MouseEvent is working but screen still black screen.

**Comment by CendioOssman** [comment]
So first we need to establish that this is a noVNC issue. What other VNC clients have you tried?

**Comment by samhed** [comment]
No response.
