### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by zwick88** [novnc/noVNC#1248]
Hi there, 

i'm using a lot of embedded Linux devices for several jobs. Some devices are connected via LTE Mobile Routers and other devices only with 3G or 2G. 
Now my problem is that i could not connect to the server via noVnc. Error message: Failed to connect to server. When i try to connect with realvnc viewer, the connection will established.

Here is a Debug log

>> RFB.constructor util.js:38:55
>> Display.constructor util.js:38:55
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0 util.js:38:55
Browser: gecko 19 util.js:38:55
Setting viewport to full display region util.js:38:55
<< Display.constructor util.js:38:55
>> Keyboard.allKeysUp util.js:38:55
<< Keyboard.allKeysUp util.js:38:55
Using native WebSockets, render mode: canvas rendering util.js:40:55
<< RFB.constructor util.js:38:55
New state 'connecting', was ''. util.js:38:55
>> RFB.connect util.js:38:55
connecting to ws://live1.power-dog.eu:1492/websockify util.js:40:55
Detected binaryType support in WebSockets util.js:40:55
<< RFB.connect util.js:38:55
GEThttp://live1.power-dog.eu:1492/websockify
Firefox kann keine Verbindung zu dem Server unter ws://live1.power-dog.eu:1492/websockify aufbauen. websock.js:278:30
>> WebSock.onerror: [object Event] util.js:38:55
WebSocket on-error event util.js:42:55
<< WebSock.onerror: [object Event] util.js:38:55
>> WebSock.onclose util.js:38:55
WebSocket on-close event util.js:42:55
Failed when connecting: Failed to connect to server( (code: 1006)) util.js:44:55
New state 'disconnecting', was 'connecting'. util.js:38:55
>> RFB.disconnect util.js:38:55
>> Keyboard.allKeysUp util.js:38:55
<< Keyboard.allKeysUp util.js:38:55
Encoding stats for this connection: util.js:40:55
Encoding stats since page load: util.js:40:55
    COPYRECT: 0 rects util.js:40:55
    TIGHT: 0 rects util.js:40:55
    TIGHT_PNG: 0 rects util.js:40:55
    HEXTILE: 0 rects util.js:40:55
    RRE: 0 rects util.js:40:55
    RAW: 0 rects util.js:40:55
    JPEG_quality_med: 0 rects util.js:40:55
    compress_hi: 0 rects util.js:40:55
    DesktopSize: 0 rects util.js:40:55
    last_rect: 0 rects util.js:40:55
    Cursor: 0 rects util.js:40:55
    QEMUExtendedKeyEvent: 0 rects util.js:40:55
    ExtendedDesktopSize: 0 rects util.js:40:55
    xvp: 0 rects util.js:40:55
    Fence: 0 rects util.js:40:55
    ContinuousUpdates: 0 rects util.js:40:55
<< RFB.disconnect util.js:38:55
New state 'disconnected', was 'disconnecting'. util.js:38:55
Clearing disconnect timer util.js:38:55
<< WebSock.onclose util.js:38:55

Somebody know this issue?

Thanks for helping

**Comment by samhed** [comment]
Hi,

Do you have a WebSocket proxy up and running on your server? noVNC requires a WebSocket to TCP proxy in order to work.

Some VNC servers like QEMU and libvncserver come with a built in proxy, otherwise you can have a look at our sister-project [websockify](https://github.com/novnc/websockify).

**Comment by zwick88** [comment]
Hi, 

yes we use libvncserver. If the connection is good enough, i can connect to the VNC Server. Only by a bad connection i cant connect via novnc

**Comment by CendioOssman** [comment]
I'm afraid the log only shows that the browser fails to connect. As such there isn't much we can do. It's either an issue in Firefox, or libvncserver, or that your network is simply not working well enough to establish a connection.

I'd advise to check the network tab in Firefox' developer tools. It might give you more details. Also check the logs for libvncserver. Other than that I'm afraid I'll have to ask you to fill a bug with either of those projects.

**Comment by zwick88** [comment]
I think the Problem ist a connection timeout. Now i have tested with guacamole an with RealVNC Client and it works perfect. I can connect to the Clients which with noVNC dosnt work.

Is it Possible that a timeout val is the Problem? Can someone give me a help to find the right line in the code?
