### ISSUE TITLE
How to setup a https server with dynamic port?

### ISSUE THREAD

**Issue by wufeng87** [novnc/noVNC#1249]
I am sorry to ask the question here.
I got a noVNC service with ip and port to access, and the port is dynamic.
I wonder how to convert http(ws) to https(wss) with dynamic port. (Becouse my website is using https.)
Thanks.

**Comment by CendioOssman** [comment]
I'm afraid I don't quite understand the issue you are having. Could you give us a bit more details on what you are doing and what you'd like to happen?

**Comment by samhed** [comment]
No response.
