### ISSUE TITLE
Mobile-friendly interface

### ISSUE THREAD

**Issue by anarkiVan** [novnc/noVNC#1253]
Hi! Are there any plans to improve mobile UX?

f.e. can `user-scalable=no` be switched to `yes` in `vnc.html`? Will it break something?

**Comment by CendioOssman** [comment]
We'd like to think our interface is mobile friendly right now. It sounds like you want better zooming functionality. Is perhaps #1054 what you are after?

(and yes, disabling `user-scalable` will break things as it means the UI would scale as well and not just the session)

**Comment by anarkiVan** [comment]
Thanks, #1054 may be helpful.
Is there a way to make indent around console smaller for mobile devices?
Also swipe on canvas element mostly does not work, but sometimes it does. Couldn't figure out the reason. I've recorded screen video, with not working swipe.

https://youtu.be/McmVEP5vAzw

I have canvas element with fixed width of 1024px. Is there a way to make it 100% to fit the screen width for mobiles?

**Comment by anarkiVan** [comment]
and another question :)
How to enable mobile keyboard ? The default is very small :(

![image](https://user-images.githubusercontent.com/16408935/59691444-3997f180-920d-11e9-857c-67626956a7fa.png)

**Comment by CendioOssman** [comment]
Ah. I see you are using `vnc_lite.html`. That is just a small example for programmers that want to use the API. Please use the normal `vnc.html`. It is the one that has gotten all the work for features and usability. It should hopefully be more what you are looking for. :)

**Comment by anarkiVan** [comment]
thank for answer! :) I will try
