### ISSUE TITLE
vnc.html only works with private browsing.

### ISSUE THREAD

**Issue by burnsjake** [novnc/noVNC#1254]
**Describe the bug**
Browsing to http://localhost:8080/vnc.html says it failed to connect to server.
If I browse to the same page in private or incognito mode, the server is able to connect.

**To Reproduce**
1. I run this to start my vnc server and novnc: 
tigervncserver -geometry 1920x1280 -localhost no -xstartup /usr/bin/blackbox -SecurityTypes none --I-KNOW-THIS-IS-INSECURE -verbose -cleanstale && /usr/share/novnc/utils/launch.sh --listen 8080 --vnc localhost:5901 &
2. Open a regular browsing session and click connect.
3. An error bar shows up along the top saying: "Failed to connect to server."
4. If I open vnc_auto.html in a regular browsing session, it works.
5. If I open vnc.html in an incognito(chrome) or private(firefox) browsing session, it works. 

**Expected behavior**
I would expect vnc.html to work in a regular browsing session.

**Client (please complete the following information):**
 - OS: osx mojave
 - Browser: firefox and chromium
 - Browser version: latest

**Server (please complete the following information):**
 - noVNC version: ubuntu 19.04 noVNC 1.0.0-1
 - VNC server: ubuntu 19.04 TigerVNC 1.9.0
 - WebSocket proxy: I believe websockify?

**Comment by CendioOssman** [comment]
Sounds like you might have something in your cache that is messing things up. Perhaps a changed websocket address? Have you checked the settings in noVNC?

Could you open the browser console and see what it says?

**Comment by seasick** [comment]
Could also be because of a browser plugin/addon which is not loaded while private browsing (like an ad blocker). Most browsers offer a setting to allow/disable certain plugins/addons while private browsing (at least Chrome and Firefox do). Hope this helps

**Comment by samhed** [comment]
No response
