### ISSUE TITLE
Start novnc error

### ISSUE THREAD

**Issue by songyanren** [novnc/noVNC#1257]
[root@BI utils]# ./launch.sh --vnc localhost:5901
No installed websockify, attempting to clone websockify...
Initialized empty Git repository in /root/noVNC/utils/websockify/.git/
error:  while accessing https://github.com/novnc/websockify/info/refs

fatal: HTTP request failed
Unable to locate /root/noVNC/utils/websockify/run after downloading

os is6.7x64，python3.6

**Comment by CendioOssman** [comment]
Hmm... It seems github has changed something and the URL needs to be changed.

**Comment by CendioOssman** [comment]
Or maybe not... It works fine for me from git, but not a browser. I guess they require the smart protocol.

Are you sure your git is up to date? Which version are you using?

**Comment by samhed** [comment]
Yeah, googling the issue suggests that this can happen if you try to use an old version of git.

**Comment by samhed** [comment]
No response
