### ISSUE TITLE
Static code analysis issue by HP fortify

### ISSUE THREAD

**Issue by PrashantKaradiguddi** [novnc/noVNC#1258]
# Load the JSON data from the file
data = json.loads(file(filename).read()) --> line number 86 

**issue detail by HP fortify** 
Attackers are able to control the file system path argument to __init__() at json2graph.py line 86, which allows them to access or modify otherwise protected files.

Explanation:

Path manipulation errors occur when the following two conditions are met:

1. An attacker is able to specify a path used in an operation on the file system.

2. By specifying the resource, the attacker gains a capability that would not otherwise be permitted.

For example, the program may give the attacker the ability to overwrite the specified file or run with a configuration controlled by the attacker.

Example 1: The following code uses input from an HTTP request to create a file name. The programmer has not considered the possibility that an attacker could provide a file name such as "../../tomcat/conf/server.xml", which causes the application to delete one of its own configuration files.

rName = req.field('reportName')
rFile = os.open("/usr/local/apfr/reports/" + rName)
...
os.unlink(rFile);

**Comment by CendioOssman** [comment]
I'm afraid this is a false positive. That is a tool run by the user, so there is always full control over what path is used. It is not code that is run remotely.
