### ISSUE TITLE
Clipboard Support

### ISSUE THREAD

**Issue by BiatuAutMiahn** [novnc/noVNC#1260]
**Is your feature request related to a problem? Please describe.**
Clipboard sharing does not seem to work.

**Describe the solution you'd like**
I would like to utilize clipboard sharing feature.

**Describe alternatives you've considered**
Client/Host configuration options.

**Additional context**
N/A

**Comment by CendioOssman** [comment]
Clipboard sharing is a feature we already have, so if it is not working for you then there is some bug. Could you add a comment using the "Bug report" template instead?

**Comment by BiatuAutMiahn** [comment]
ok, I will double check my config, and change template is necessary, ty

**Comment by samhed** [comment]
Note that clipboard is only available using `vnc.html` not `vnc_lite.html`

**Comment by BiatuAutMiahn** [comment]
I was using auto
