### ISSUE TITLE
Packed as a separate file

### ISSUE THREAD

**Issue by goldencolor** [novnc/noVNC#1263]
**I have a requirement that is allowed in index. html. It's local. I need to pack all JS into a JS file of es5. Can I provide this file?
Because I'm going to put it in the WebView in app to allow, not rush to the server, just run locally, and then connect to the remote server's IP control.**###

**Comment by samhed** [comment]
Not entirely sure I understand what you are asking for, but perhaps this is what you are asking for:

    utils/use_require.js --as commonjs --with-app --only-legacy

This will output all javascript into one `app.js` file, does that work for you?

**Comment by juanjoDiaz** [comment]
You can also just use webpack/rollup/<insert_favourite_packaging_tool> to package your code and import noVNC from NPM like any other dependency. Then you can control the exact transpilation that you want, you'll get tree-shaking of things that you don't need, etc.

**Comment by samhed** [comment]
No response.
