### ISSUE TITLE
Connection closed (code: 1011, reason: Failed to connect to downstream server)

### ISSUE THREAD

**Issue by hll321** [novnc/noVNC#1270]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Browser version: [e.g. 22]

**Server (please complete the following information):**
 - noVNC version: [e.g. 1.0.0 or git commit id]
 - VNC server: [e.g. QEMU, TigerVNC]
 - WebSocket proxy: [e.g. websockify]

**Additional context**

**Comment by samhed** [comment]
Please fill in information in the fields above.

**Comment by CendioOssman** [comment]
No response. Closing.
