### ISSUE TITLE
Snap installation doesn't work

### ISSUE THREAD

**Issue by larryathey** [novnc/noVNC#1271]
Tried "sudo snap install novnc" on both an Ubuntu 16.04 and 18.04 machines, package not found. I need to daemonize this and need your snap implementation to do so.

**Comment by samhed** [comment]
We haven't gotten around to submitting the snap package to the store yet. We added the snap package to the master branch just a week ago.

**Comment by tkedwards** [comment]
Sorry about the dealy with this. I created the Snap package (see snap/ directory in the source) and I'm trying to get it into Ubuntu's Snap store. For some reason the name 'novnc' is reserved, so I've submitted a request and am waiting to hear back from Canonical.

In the meantime you can build the Snap package locally with:
```
git clone https://github.com/novnc/noVNC.git
cd noVNC
snapcraft snap # Add --use-lxd if using a virtual machine which itself can't run other VMs (no VT-X extensions)
sudo snap install --dangerous novnc_*.snap
```

**Comment by tkedwards** [comment]
So the Snap package is now in the store and released. Unfortunately it's affected by https://github.com/novnc/noVNC/issues/1276 so it will only currently work in Opera, but not in Firefox or Chrome. When that bug is fixed I'll probably need to update the Snap again

**Comment by tkedwards** [comment]
Snap package (latest-20190813) is released on the store, it uses the latest Websockify so should no longer be affected by #1276. I think this issue can be closed

**Comment by franciscoprin** [comment]
I am getting this error, any clue?

$ snapcraft snap
Issues while validating snapcraft.yaml: The 'version' property does not match the required schema: '@VERSION@' is not a valid snap version. Snap versions consist of upper- and lower-case alphanumeric characters, as well as periods, colons, plus signs, tildes, and hyphens. They cannot begin with a period, colon, plus sign, tilde, or hyphen. They cannot end with a period, colon, or hyphen

**Comment by tkedwards** [comment]
Hi, what do the logs show:
`sudo snap logs novnc -n 200`
