### ISSUE TITLE
noVNC browser client fails to connect with an WebSocket handshake error, when using Apache wstunnel websockets proxy

### ISSUE THREAD

**Issue by tokariu** [novnc/noVNC#1275]
**problem:**
noVNC is unable to make connections with apache websocket tunnel module due to websocket handshake errors.

**overview:**
I'm trying to get noVNC working on my local windows computer. I have xampp/apache which is remotely only accessible over port80/443 with loaded proxy modules (config details below). I have TightVNC running on port 5900. The apache is serving noVNC on `https://localhost/novnc`. I open the novnc-URL with Firefox and Opera (Opera shows more details in the debug console than firefox).

**Client:**
 - OS: Win7
 - Browser: Firefox 68.0.1 + Opera 62.0.3331.72

**Server:**
 - httpd: xampp / apache v2.4.39 (running on win7)
 - noVNC version: 1.1.0
 - VNC server: TightVNC port 5900
 - WebSocket proxy:
    xampp/apache -> mod_proxy.so + mod_proxy_wstunnel.so loaded.
   for testing I also tried: node-websockify.

**Setup**
I enabled websockets modules in the apache conf like this:
```
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
```
my relevant ssl apache config for setting up the websockets proxy looks like this:
```
<VirtualHost _default_:443>
DocumentRoot "C:/xampp/htdocs"
ServerName localhost:443
ServerAdmin admin@localhost
ErrorLog "C:/xampp/apache/logs/error.log"
TransferLog "C:/xampp/apache/logs/access.log"
SSLEngine on
SSLCertificateFile "ssl/server.crt"
SSLCertificateKeyFile "ssl/server.key"
## noVNC proxy websockets adjustments:  
SSLProxyEngine on
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
ProxyRequests off
ProxyPreserveHost on
<Location /websockify>
    ProxyPass wss://127.0.0.1:5900
    ProxyPassReverse wss://127.0.0.1:443
</Location>
## end noVNC proxy additions
</VirtualHost>
```

**To Reproduce**
with the above setup, try opening `https://localhost/novnc` and hit connect with the according host, port and path and it won't connect due to an websocket handshake error. see this screenshot with all the details: 
![opera-errorlog](https://user-images.githubusercontent.com/7195846/62707725-2d9d0480-b9f2-11e9-9fed-c091db699d35.png)

on the left side, you can see the noVNC connection configuration. on the right side the error messages when trying to connect. This happens with both, Firefox and Opera browsers. However, only Opera is showing the detailed websocket errors.

**Expected behavior**
The websockets proxy from apache should actually work the same way node-websockify does and thus the client should connect like it.

**further info:**
I also installed node-websockify for testing purposes (https://www.npmjs.com/package/node-websockify) and run it with settings like this:
```
node websockify.js
WebSocket settings:
    - proxying from 127.0.0.1:443 to 127.0.0.1:5900
    - Web server active. Serving: ./novnc
    - Running in encrypted HTTPS (wss://) mode using: server.crt, server.key
```
websockify opens a webserver to serve the novnc html/js files on `https://localhost`. Note that I used port 443 because other ports won't work for me remotely, but the result is the same as with other ports (like localhost:8080). when I try to connect to `https://localhost` with opera or firefox  i just get an error:
![opera-errorlog2](https://user-images.githubusercontent.com/7195846/62708945-aef59680-b9f4-11e9-869e-29143e2810a9.png)
so node-websockify as websocket proxying isn't working for me either.

**ALSO NOTE:**
the **windows service** version that needs to be compiled with portable python still doesn't work

the readme:
https://github.com/novnc/websockify/blob/master/Windows/Windows%20Service%20Readme.txt
points to the manual here:
https://github.com/novnc/websockify/wiki/Compiling-Websockify-as-Windows-Executable-%28not-working-nowadays%29
and it is still not working! due to the issue here:
https://github.com/novnc/websockify/issues/108

I wasted so much time just to find out!

Finally, the best way would be to make the apache websockets proxy work with noVNC but somehow the websockets handshake doesn't work. Is someone able to get more details for the reason and is able to provide a fix either for noVNC or for this setup to make it work?

**Comment by tokariu** [comment]
I'm not entirely sure if I'm doing something wrong conceptual, because I thought the apache reverse proxy would be enough to make it work. But after some further experiments I think it needs websockify to handle vnc-to-tcp traffic additionally. However, I was unable to get the things on windows together correctly for the time being.

In the meantime I was able to achieve my goal with a self hosted apache guacamole docker image, which was quite challenging, but it actually worked out. I want to emphasize that I like the noVNC project idea and I'd have stayed with it if it had worked out for windows.

as for this issue: if someone still wants to add some notes how to make it work, go ahead, I'm still listening. If there is nothing to fix, at least keep the notes in mind to improve some other things!

**Comment by CendioOssman** [comment]
I'm unfortunately not familiar with mod_proxy_wstunnel, but I'm reading the document for it and it does not seem to be a WebSocket to TCP proxy. It seems to just proxy WebSocket to WebSocket.

So I'm afraid you'll need some other module to get Apache working, and I don't have any idea if such a module exists and what it might be called.

**Comment by pm-pm** [comment]
I think i have nearly the same setup and it works very well here.
I will have a look at my configuration and try to give you a hint.

One difference is, that i use tigervnc. Server is Debian 9 and Debian 10 with latest apache.

**Comment by pm-pm** [comment]
Here my apache configuration. I am NOT an apache expert.
One point is that the proxy should **not** use WSS between apache and websockify, because SSL is already handled by apache. (Or do you need secure SSL/WSS inside localhost?)
So no SSL/WSS configuration in within novnc/websockify. :-)

Is it allowed to add ":443" at servername? Already ist in <virtualhost>.

Note: Serving the novnc files is NOT done by websockify in my setup. 
The files are on a different public webserver. Try this to avoid conflicts.

It took me weeks to make a well working setup, but now i will never miss is. :-)

It is quied simple, isn´t it? ;-)

```
<VirtualHost *:443>
        ServerName xxx
        ServerAdmin xxx

         SSLEngine on
         SSLCertificateFile      xxx
         SSLCertificateKeyFile   xxx

        DocumentRoot /xxx
        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory /xxx>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Require all granted
        </Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
                AllowOverride None
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Require all granted
        </Directory>

ProxyRequests On
ProxyVia On

        ProxyPass        /websockify ws://127.0.0.1:9999/websockify retry=3
        ProxyPassReverse /websockify ws://127.0.0.1:9999/websockify retry=3
        ProxyPass        /               !

# Logfiles

</VirtualHost>
```

**Comment by tokariu** [comment]
Thanks for your feedback @CendioOssman, @pm-pm.

@CendioOssman you seem right, it still requires additionally the websockify ws-to-tcp proxy. the apache module is just the additional reverse proxy.

@pm-pm i did another try with adjustments towards your config. but I still have no luck.

I'm running node-websockify (from npm, not the one from the github websockify 0.8.0 release. the just released 0.9.0 release is btw missing a node version of websockify).
Additionally I made some changes to the apache proxy config.

See all in this screenshot:

![websockify](https://user-images.githubusercontent.com/7195846/63027851-fa54ec80-bead-11e9-890d-93b03762f2c2.jpg)
on the left side the noVNC connection config: unencrypted, localhost:9500, /websockify path.
on the right, the browser console log with the error message.
below the error message from node-websockify (version undefined ...)
at the bottom the relevant apache proxy configuration.
I've installed tigerVNC with default port for testing purposes.

yet I can't get it working.

still any ideas?

**Comment by tokariu** [comment]
Ah I got it going!

The Problem was now only the TigerVNC security configuration.
In the Security-Tab you have 3 options for session encryption. 
- "None"
- "anonymous TLS"
- "TLS with X.509 certificates"

i had only ticked "anonymous TLS" because I wanted to allow only encrypted vnc connections. But as it's restricted to localhost, there is no need for TLS actually. (would be nice nevertheless though.. )

having both "none" and "anonymous TLS" checked worked!

Finally I got noVNC to work.


Now, having used the apache guacamole client a lot, I was very much used to the pinch-zoom feature there. That's the first thing that comes into my mind that's missing when using noVNC. I need to get used to it without pinch zoom.. having either fullscreen or just a little part of the screen.

**Comment by pm-pm** [comment]
You have a valid SSL certificate for your apache Server, right? Ok.

NoVNC -> [Port 443] -> Apache -> [websockifyPORT] -> websockify -> [vncPORT] ->VNCserver

In the noVNC windows you must set:

> [x] Verschluesset (=yes)
> Server: localhost (When your browser is on the same system as apache server)
> Port: 443 (you want to access the ssl port of apache)
> Pfad: websockify (when you only have one vnc target)

Use this connection to connect to the Apache server.

Then the apache reverse proxy forwards the data to winsockify and winsockify forwards data to vnc server.

This setup works. ;-)

Have a try. Good luck. :-)

**Comment by pm-pm** [comment]
What is  "pinch-zoom"?

Use "local scaling" in noVNC config with tigervnc. Then you can resize the browser and the vncserver does the same.

Using "Auf Fenster begrenzen" keeps 100% in the windows even when you strech it.

Play around.

**Comment by tokariu** [comment]
pinch zoom is when you use a mobile device like a smartphone and use two fingers on the display to zoom:
![serveimage](https://user-images.githubusercontent.com/7195846/63033924-b6b3b000-beb8-11e9-97d9-c011de3bf50c.jpg)

there's also an open issue about pinch zooming here: https://github.com/novnc/noVNC/issues/1054
would be cool to have that in the future. if you ever tried guacamole, you will miss that, at least on mobile devices.

**Comment by pm-pm** [comment]
Ok, Mobile devices. ;-)

When using a Computer (hard and heavy) with Browser "local scaling" does the same or?

BTW; Nice to see that it works now for you. :thumbsup:

**Comment by tokariu** [comment]
yes..

I'm still working on it.. trying to run both guacamole and novnc. also testing the setup from remote hosts instead of localhost.. not everything is working right now, but I'm confident it will work soon.

**Comment by tokariu** [comment]
now all seems to work as intended.. 
however the TigerVNC security settings are a bit strange...
![sec](https://user-images.githubusercontent.com/7195846/63041419-24b3a380-bec8-11e9-9783-b9bbbbf2b871.png)
as seen here, for noVNC to work "none" has to be ticked. if only "none" is ticked, guacamole doesn't work. 
and vice versa, if only "Anonymous TLS" is ticked, only guacamole works, noVNC can't connect.

to make both work, one needs to check both options.

**Comment by tokariu** [comment]
and one more thing... 
using noVNC + TigerVNC on windows, the option "server side scaling" doesn't seem to work. any idea why? local scaling works finde, the desktop adjusts to the browser-window size... however, server side scaling would be better. I thought TigerVNC supports it.. or maybe only on linux? any help on that?

**Comment by pm-pm** [comment]
On a **virtual** Linux VNC session server side scaling works very well. :-)

Maybe the problem is that you have a fix/hardware screen on windows machine?
As far as i know the server side scaling works on virtual windows machines (running e.g. in a virtual box)? But don´t ask  me for details.

I have never used "server side scaling" on a Linux "hardware IP:0" screen. 

if you have more information please put it here. ;-)

**Comment by tokariu** [comment]
not yet, but it seems scaling is problem, esp. on windows. see this tracking issue here:
https://github.com/TigerVNC/tigervnc/issues/274

the whole remote/serverside sclaing is not working with noVNC/TigerVNC. If I use a smartphone I get to see a tiny bit of the screen and have to scroll to death to come from one corner to the other. the scaling is unnecessary large by default. it looks like every pixel is double the size. 
and always switching between local scaling and none/serverside isn't really an option on mobile devices... 

so currently I'm still struggling with noVNC.. the pinch-zoom feature that works flawlessly in Guacamole offers a superior handling of remote-desktop on mobile devices.

I tried quite some tricks with dpi/resolution/browser-scaling and stuff on smartphone and remote-desktop, but it seems it's stuck with the current state.

**Comment by pm-pm** [comment]
I can not confirm this.

Using "Firefox Klar/Focus" on Adndroid i have normal Desktop with servers side resize. The desktops fits to the screen. 1:1 Pixel. Of course the resolution of the Desktop is the same resolution of the mobile phone.

To see the "original" full screen on Android is tricky/difficult. (Additional touching vnc desktop with a computer browser. Tricky, not useful)

Maybe we talk about slighty about different things, because i do not know guacamole.

**Comment by tokariu** [comment]
I think this is a TigerVNC windows issue. the serverside scaling isn't working regardless of the viewer  device. (also see: https://github.com/TigerVNC/tigervnc/issues/274#issuecomment-191488681)

e.g. TigerVNC server running on windows,  opening noVNC on a firefox-/opera-desktop browser -> still the server side scaling isn't working - the same issues as described above for smartphones. it isn't resizing to the windowsize and pixel scaling is like double the size. with "local scaling" selected, it adjusts to the window size, ..but without reducing the traffic.

So I think it's an issue with the windows-tightvnc server. Obviously it needs some bugfixing/enhancing.

BTW, it's no problem to see the original fullscreen on android: just by using local scaling in noVNC and it is rendered beautifully the complete desktop.. but you can't use it then, the icons are too small etc. 
That's where Guacamole scores. you can pinch-zoom in if you need it, to click on some little icons and just pinch-zoom out afterwards to see the whole desktop again.
But I don't think Guacamole reduces the traffic when zoomed-in, I think the whole desktop is send, but just a part of it is viewed. i.e. there is no traffic improvement. But at least you can handle large desktops very comfortable that way on mobile devices.

**Comment by pm-pm** [comment]
Hello tokariu,

thanks for the information and explanation. I got your point. :-)
Unfortunately guacamole is not lean and the installation is not recommended for a vserver on the internet, nevertheless i will have a look at the software.

I use noVNC for many years an i am verify satisfied with it, because it is very reliable as remote desktop access tool!. :-)

Good luck.
