### ISSUE TITLE
400 Client must support 'binary' or 'base64' protocol

### ISSUE THREAD

**Issue by BruceGujinhe** [novnc/noVNC#1276]
**Describe the bug**
1. It works ok in local environment, such like: 
```
http://localhost:6080/vnc.html?host=cb0pek3c.xxx.com&port=10147&password=ODKY35Xuaf3IwpNNaSDZW&autoconnect=true
```
We got the web desk normally. and the websockify response is ok:
```
Request URL: wss://cb0pek3c.xxx.com:10147/websockify
Request Method: GET
Status Code: 101 Switching Protocols
```
2. But we got something unexpected in our server.
```
https://vnc.xxxx.vip/vnc.html?host=cb0pek3c.xxx.com&port=10147&password=WODKY35Xuaf3IwpNNaSDZW&autoconnect=true
```
We got the `websockify ` response like that:
```
Request URL: wss://cb0pek3c.xxx.com:10147/websockify
Request Method: GET
Status Code: 400 Client must support 'binary' or 'base64' protocol
```

**Client (please complete the following information):**
 - OS: centos 6.8
 - Browser: chrome
 - Browser version: the latest

**Server (please complete the following information):**
 - noVNC version:  latest
 - VNC server: none
 - WebSocket proxy: websockify

**Comment by BruceGujinhe** [comment]
try lots of different methods, I found that the latest master code can't work correctly. 
the code I clone two weeks ago works fine at present.

**Comment by tkedwards** [comment]
Same problem here, except I found that this issue doesn't happen when using the Opera browser, but does when using Chrome or Firefox (latest versions). I've tested on different computers - a Mac and a Chromebook and the issue happens in Chrome or Firefox. Changing the Websockify settings (e.g. replacing 'localhost' with 127.0.0.1) in the Novnc config on the browser does not help.

**Comment by therevoman** [comment]
Ran into this error while trying to use it in a docker container today.

**Comment by CendioOssman** [comment]
I'm afraid your websockify is too old and you need to upgrade it. It requires a non-standard behaviour that we recently removed from noVNC.

**Comment by tkedwards** [comment]
I saw your latest (0.90) release of Websockify just before. I'm working on updating the Snap and should be done soon

**Comment by tkedwards** [comment]
This is now 'fixed' in the Snap package version latest-20190813, in that the Snap package now uses the latest Websockify version

**Comment by working-name** [comment]
sorry, it's not, getting the same error on 19.04

**Comment by tkedwards** [comment]
Can you provide output of:

`snap list novnc`

and:

`/snap/bin/novnc --listen 6082 vnc localhost:5902`

(replace the port numbers above with the ones you're using). Note that the output should show the websockify path as something like:
Using local websockify at /snap/novnc/3/utils/websockify/run

**Comment by buster742** [comment]
Solved editing file /novnc/core/websock.js
Locate line:
`this._websocket = new WebSocket(uri, protocols);`
replace with
`this._websocket = new WebSocket(uri, ['binary', 'base64']); //protocols);`
+[info](https://stackoverflow.com/questions/15962359/websockify-error-client-must-support-binary-or-base64-protocol)

**Comment by Minobi** [comment]
Solved this issue by sending `wsProtocols: ['binary', 'base64']` parameter to RFB constructor, e.g.:
```
const rfb = new RFB(document.getElementById('screen'), url, {
  qualityLevel: quality,
  compressionLevel: compression,
  wsProtocols: ['binary', 'base64'],
});
```

**Comment by iamrekas** [comment]
Hello,
I want to suggest make possible that protocols get from uri params, because i was spent lot of time to figure out what wrong in my situation.
Then i would like to upgrade this code to latest will must change it in code.

**Comment by connected201** [comment]
i have same problem and solution for @buster742 not working anymore because `this._websocket = new WebSocket(uri, protocols);` don't exist anymore in `file /novnc/core/websock.js`

also solution for @Minobi, how to use it?
```
sending wsProtocols: ['binary', 'base64'] parameter to RFB constructor, e.g.:

const rfb = new RFB(document.getElementById('screen'), url, {
  qualityLevel: quality,
  compressionLevel: compression,
  wsProtocols: ['binary', 'base64'],
});

```

**Comment by mteam88** [comment]
Same problem on raspberry pi 3, but I can't seem to figure out how to update websockify. Can someone please tell me how to update from upstream?

**Comment by mteam88** [comment]
> Solved editing file /novnc/core/websock.js Locate line: `this._websocket = new WebSocket(uri, protocols);` replace with `this._websocket = new WebSocket(uri, ['binary', 'base64']); //protocols);` +[info](https://stackoverflow.com/questions/15962359/websockify-error-client-must-support-binary-or-base64-protocol)

Line is no longer present. Is there an alternative?

**Comment by mteam88** [comment]
Nevermind! I solved my problem by installing websockify with the instructions here: https://github.com/novnc/websockify (Installing Websockify). Worked ezpz.
