### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by darkdragon-001** [novnc/noVNC#1284]
Add python 3 support. The Debian maintainers already created a [patch (`debian/patches/fix-for-python3.patch`)](http://deb.debian.org/debian/pool/main/n/novnc/novnc_1.0.0-1.debian.tar.xz).

**Comment by samhed** [comment]
From what I can see, this is the patch you're talking about?

    --- novnc-1.0.0.orig/utils/img2js.py
    +++ novnc-1.0.0/utils/img2js.py
    @@ -11,12 +11,12 @@ import sys, base64
     try:
         from PIL import Image
     except:
    -    print "python PIL module required (python-imaging package)"
    +    print("python PIL module required (python-imaging package)")
         sys.exit(1)
     
     
     if len(sys.argv) < 3:
    -    print "Usage: %s IMAGE JS_VARIABLE" % sys.argv[0]
    +    print("Usage: %s IMAGE JS_VARIABLE" % sys.argv[0])
         sys.exit(1)
     
     fname = sys.argv[1]
    @@ -27,7 +27,7 @@ if   ext == "png":            mime = "im
     elif ext in ["jpg", "jpeg"]:  mime = "image/jpeg"
     elif ext == "gif":            mime = "image/gif"
     else:
    -    print "Only PNG, JPEG and GIF images are supported"
    +    print("Only PNG, JPEG and GIF images are supported")
         sys.exit(1)
     uri = "data:%s;base64," % mime
     
    @@ -36,5 +36,5 @@ w, h = im.size
     
     raw = open(fname).read()
     
    -print '%s = {"width": %s, "height": %s, "data": "%s%s"};' % (
    -        var, w, h, uri, base64.b64encode(raw))
    +print('%s = {"width": %s, "height": %s, "data": "%s%s"};' % (
    +        var, w, h, uri, base64.b64encode(raw)))
    --- novnc-1.0.0.orig/utils/json2graph.py
    +++ novnc-1.0.0/utils/json2graph.py
    @@ -13,53 +13,53 @@ import matplotlib.pyplot as plt
     from matplotlib.font_manager import FontProperties
     
     def usage():
    -    print "%s json_file level1 level2 level3 [legend_height]\n\n" % sys.argv[0]
    -    print "Description:\n"
    -    print "level1, level2, and level3 are one each of the following:\n";
    -    print "  select=ITEM - select only ITEM at this level";
    -    print "  bar         - each item on this level becomes a graph bar";
    -    print "  group       - items on this level become groups of bars";
    -    print "\n";
    -    print "json_file is a file containing json data in the following format:\n"
    -    print '  {';
    -    print '    "conf": {';
    -    print '      "order_l1": [';
    -    print '        "level1_label1",';
    -    print '        "level1_label2",';
    -    print '        ...';
    -    print '      ],';
    -    print '      "order_l2": [';
    -    print '        "level2_label1",';
    -    print '        "level2_label2",';
    -    print '        ...';
    -    print '      ],';
    -    print '      "order_l3": [';
    -    print '        "level3_label1",';
    -    print '        "level3_label2",';
    -    print '        ...';
    -    print '      ]';
    -    print '    },';
    -    print '    "stats": {';
    -    print '      "level1_label1": {';
    -    print '        "level2_label1": {';
    -    print '          "level3_label1": [val1, val2, val3],';
    -    print '          "level3_label2": [val1, val2, val3],';
    -    print '          ...';
    -    print '        },';
    -    print '        "level2_label2": {';
    -    print '        ...';
    -    print '        },';
    -    print '      },';
    -    print '      "level1_label2": {';
    -    print '        ...';
    -    print '      },';
    -    print '      ...';
    -    print '    },';
    -    print '  }';
    +    print("%s json_file level1 level2 level3 [legend_height]\n\n" % sys.argv[0])
    +    print("Description:\n")
    +    print("level1, level2, and level3 are one each of the following:\n")
    +    print("  select=ITEM - select only ITEM at this level")
    +    print("  bar         - each item on this level becomes a graph bar")
    +    print("  group       - items on this level become groups of bars")
    +    print("\n")
    +    print("json_file is a file containing json data in the following format:\n")
    +    print('  {')
    +    print('    "conf": {')
    +    print('      "order_l1": [')
    +    print('        "level1_label1",')
    +    print('        "level1_label2",')
    +    print('        ...')
    +    print('      ],')
    +    print('      "order_l2": [')
    +    print('        "level2_label1",')
    +    print('        "level2_label2",')
    +    print('        ...')
    +    print('      ],')
    +    print('      "order_l3": [')
    +    print('        "level3_label1",')
    +    print('        "level3_label2",')
    +    print('        ...')
    +    print('      ]')
    +    print('    },')
    +    print('    "stats": {')
    +    print('      "level1_label1": {')
    +    print('        "level2_label1": {')
    +    print('          "level3_label1": [val1, val2, val3],')
    +    print('          "level3_label2": [val1, val2, val3],')
    +    print('          ...')
    +    print('        },')
    +    print('        "level2_label2": {')
    +    print('        ...')
    +    print('        },')
    +    print('      },')
    +    print('      "level1_label2": {')
    +    print('        ...')
    +    print('      },')
    +    print('      ...')
    +    print('    },')
    +    print('  }')
         sys.exit(2)
     
     def error(msg):
    -    print msg
    +    print(msg)
         sys.exit(1)
     
     
    @@ -156,7 +156,7 @@ if [L1, L2, L3].index("group") < [L1, L2
         bar_vals = zip(*bar_vals)
         bar_sdvs = zip(*bar_sdvs)
     
    -print "bar_vals:", bar_vals
    +print("bar_vals:", bar_vals)
     
     #
     # Now render the bar graph

**Comment by CendioOssman** [comment]
I don't think we use these scripts. Do they even still work? Perhaps we should just remove them?

**Comment by kanaka** [comment]
Memory is fuzzy but I think this was used to generate some of the UI elements so that they could be encapsulated as data URIs directly on the page without requiring round-trips to the server. Good times.

**Comment by samhed** [comment]
Thanks for clarifying @kanaka. The scripts have been removed in cbf090fe701adc7776270be6725f886e185d2b85

This makes the debian patch irrelevant.
