### ISSUE TITLE
Rasbian Buster (July 2019) Code 404 File not found

### ISSUE THREAD

**Issue by Blacksmurf-GF** [novnc/noVNC#1286]
Installed on a fresh Rasbian Buster (Pi4 4GB)
VNC Server is the default RealVNC server. Connecting with a vnc client works fine.

Start noVNC with 
`sudo ./launch.sh --vnc 127.0.0.1:5901 --listen 80`

Consoloe output is:
`Warning: could not find self.pem
Using installed websockify at /usr/bin/websockify
Starting webserver and WebSockets proxy on port 80

Navigate to this URL:

    http://TESTPI:80/vnc.html?host=TESTPI&port=80

Press Ctrl-C to exit

WebSocket server settings:
  - Listen on :80
  - Flash security policy server
  - Web server. Web root: /home/pi/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :80 to 127.0.0.1:5901
`

If I connect the URL, I get in the Browser "Failed to connect to server"

In console I get:
`localhost - - [03/Sep/2019 09:07:14] code 400, message Client must support 'binary' or 'base64' protocol
localhost - - [03/Sep/2019 09:07:14] code 404, message File not found`

Is this a Bug or whats wrong?

regards Frank

**Comment by CendioOssman** [comment]
Yes, in websockify. You need to upgrade to a newer version of it. After that it should connect just fine.
