### ISSUE TITLE
Websocket doesn't connect in Chrome but works in Firefox

### ISSUE THREAD

**Issue by JKJameson** [novnc/noVNC#1291]
**Describe the bug**
Connecting to a VNC websocket. Works in Firefox. Connection refused in Chrome.

**To Reproduce**
Reproducable using live demo.

**Expected behavior**
The websocket connection is established in Chrome.

**Server (please complete the following information):**
 - noVNC version: 9886d59
 - VNC server: QEMU
 - WebSocket proxy: websockify

Failed when connecting: Connection closed (code: 1006)
_fail @ rfb.js:668
(anonymous) @ rfb.js:210
_websocket.onclose @ websock.js:199

WebSocket connection to 'wss://dev-srv1.virtpanel.com:7007/websockify' failed: WebSocket opening handshake was canceled

**Comment by CendioOssman** [comment]
Could you tell us what version of websockify was used? And what did the websockify log say?

**Comment by JKJameson** [comment]
I have zero logs on either side. Chrome seems to drop the connection before it's even established.
It has something to do with using a certificate on a different domain than the web page.
This is my exact issue: https://bugs.chromium.org/p/chromium/issues/detail?id=993907
