### ISSUE TITLE
websockify is a package and cannot be directly executed

### ISSUE THREAD

**Issue by hechangqin** [novnc/noVNC#1292]
I used 1.1.0 to quick start with: ./utils/launch.sh --vnc localhost:5901. My python version is 2.6.6. The error log is as follow:

Warning: could not find self.pem
No installed websockify, attempting to clone websockify...
Initialized empty Git repository in /root/noVNC-1.1.0/utils/websockify/.git/
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 4150 (delta 3), reused 5 (delta 1), pack-reused 4138
Receiving objects: 100% (4150/4150), 4.57 MiB | 23 KiB/s, done.
Resolving deltas: 100% (2734/2734), done.
Using local websockify at /root/noVNC-1.1.0/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080
/usr/bin/python: websockify is a package and cannot be directly executed
Failed to start WebSockets proxy

**Comment by samhed** [comment]
Seems like a regression in python 2.6:

https://bugs.python.org/issue2751

Do you have the option of upgrading to python 2.7?

**Comment by hechangqin** [comment]
@samhed Thanks, I will try it.

**Comment by hechangqin** [comment]
@samhed I used Anaconda to create python2.7 env and tried. 
It work well now.
Thanks a lot.

**Comment by samhed** [comment]
Good to hear, thanks for confirming.

**Comment by CendioOssman** [comment]
We still want to support RHEL 6 which has Python 2.6, so I think we want to have a look at this.

**Comment by samhed** [comment]
This is a websockify issue: https://github.com/novnc/websockify/issues/420
