### ISSUE TITLE
How to change the path of /websockify on startup? 

### ISSUE THREAD

**Issue by parthmishra** [novnc/noVNC#1293]
I see that you can change the path of the `/websockify` request by navigating to `/vnc.html` and then clicking `Settings > WebSocket > Path`  and modifying it there. My question is, how can I get that value prepopulated with a different path so that I don't have to change it manually?

My use case is I'm hosting VNC servers at `https://example.com/vnc_server_uuid/` but they all use the same `https://example.com/websockify` URI to initiate the WebSocket.  Changing it manually as stated above solves my problem, I just need this to be automatic and I don't see a configuration option for it.

**Comment by samhed** [comment]
Changing it manually in the GUI settings should save it in your browser's web storage - this means that if you connect to the same server again with the same browser, it should remember your settings.

If you're looking at something more permanent that will have an effect for any user and any browser you will have to modify the code on this line in your copy of noVNC:

https://github.com/novnc/noVNC/blob/master/app/ui.js#L165

Does that answer your question?

**Comment by samhed** [comment]
No response
