### ISSUE TITLE
Create Typescript Type Definitions

### ISSUE THREAD

**Issue by juanjoDiaz** [novnc/noVNC#1294]
**Is your feature request related to a problem? Please describe.**
Not strictly a problem but, if integrating noVNC into a TypeScript, it's not possible to benefit from type checks since there are no type definitions.

**Describe the solution you'd like**
Create a Type Definition file and upload to DefinitelyTyped.

There is https://www.npmjs.com/package/@types/novnc-core but it's unofficial and obsolete.

**Comment by samhed** [comment]
So that's basically like writing header files? For all our modules?

**Comment by CendioOssman** [comment]
I don't think this is realistic right now. None of the core developers are using noVNC with TypeScript, so such a file would not get maintained properly here either.

For now I think an unofficial one like that is the best option. Perhaps you can submit patches to get it up to date?
