### ISSUE TITLE
WebSockets support in QEMU

### ISSUE THREAD

**Issue by primalmotion** [novnc/noVNC#13]
I've red on an interview that you are working with QEMU team to make it support your client. Do you have any information about the progress of this ?

At this time I have to build a proxy for each virtual machine so each VM needs to port, it's VNC port and its VNC proxy port. I'd like to remove this :)

**Comment by ewiger** [comment]
I would be happy to integrate this into my [picostack](https://github.com/ewiger/picostack) project. How does the command line option for KVM looks like? Or do I simply have to compile from source with "--enable-vnc-ws" option??
