### ISSUE TITLE
QEMU websocket server no longer working

### ISSUE THREAD

**Issue by dmbasso** [novnc/noVNC#1304]
**Describe the bug**
The `README.md` mentions the internal QEMU VNC websocket server as compatible with noVNC, but it seems it is not currently working.

**To Reproduce**
1. launch a VM with websocket VNC enabled, e.g.: `qemu-system-x86_64 -vnc :0,websocket freedos.qcow2`
2. launch a webserver in noVNC root, e.g.: `python3 -m http.server`
3. open the url `http://localhost:8000/vnc.html`
4. open noVNC advanced config, use port 5700, empty path
5. click connect
6. in Chromium's developer tools / network you can see the server returns a "400 Bad Request"; it seems Firefox does not receive a response

**Expected behavior**
The VNC connection should be established.

**Client:**
 - OS: Linux Mint, Linux 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Browser: Chromium Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on LinuxMint 19.1 (64-bit), Firefox Quantum 68.0.2 (64-bit)

**Server:**
 - noVNC version: d39e0d124487fb85522e929909d3a9d34261cc57 (Tue Sep 24 16:00:05 2019)
 - VNC server: QEMU
 - WebSocket proxy: QEMU internal

**Comment by dmbasso** [comment]
Ok, I found when it stopped working: c912230309806aacbae4295faf7ad6406da97617

> Remove the default value of wsProtocols
> Using the 'binary' protocol by default is very non-standard.

The previous 21387f9c240b316a10457b333ca6a8f97e2dc2d1 worked just fine.
Is there a way to configure it to use the binary protocol?

**Comment by dmbasso** [comment]
I've written a quick patch to add the option to the UI: [binary.patch.txt](https://github.com/novnc/noVNC/files/3688203/binary.patch.txt)
If it is more convenient, I can submit a PR.
But I wonder, what is the problem leaving binary as the default option?

**Comment by samhed** [comment]
As the commit message states - setting subprotocol to use 'binary' by default isn't compatible with the WebSocket protocol standard.

I believe a few initial versions of the WebSocket standard included this, and that's the reason web apps, that were early adopters of WebSockets, were written like this.

Both noVNC and Websockify have been modified to no longer include 'binary' and ideally, QEMU should as well. @CendioOssman, what do you think is the best way to handle this?

**Comment by CendioOssman** [comment]
I thought QEMU had already dropped that requirement. Didn't you test with QEMU?

Unfortunately I don't see a good fix besides QEMU updating their end. We cannot optionally support the non-standard `"binary"`, and we don't want to add back a hard requirement for it.

@dmbasso, could you report this to QEMU?

**Comment by dmbasso** [comment]
Thank you @samhed and @CendioOssman for taking the time to look into this issue.

> Didn't you test with QEMU?

I did, it is described in the bug report.

> We cannot optionally support the non-standard "binary"

Why can't the option be there (as I provided in my patch, which makes noVNC work with QEMU), with a note like:
[ ] Binary (*non-standard, **use at your own risk, ***if you use a herd of goats might attack you and eat your pets)

Providing the option will allow more servers to be used, I don't see any drawback besides a slight increase in UI complexity (although it is already hidden in the advanced options).

Anyway, for now perhaps the fix would be to remove QEMU from the servers in the `README.md`.

**Comment by samhed** [comment]
> Didn't you test with QEMU?

I guess this question was directed at me. You are right @CendioOssman, I did test QEMU + trunk noVNC ~2 weeks ago, and everything worked fine for me.

@dmbasso are you sure you're not running an old version of QEMU? I believe I was using version 3.1.1.

**Comment by dmbasso** [comment]
Sorry for the delay, I took my time to check and recheck, to make sure I was not making any mistakes.
> @dmbasso are you sure you're not running an old version of QEMU?

In fact I was, I was using version 3.1.0. But now I've tried versions up to 4.1.0 (from Debian unstable), and none of them worked with current HEAD (412d93060dd26a69dd02debe8074364bbb1937e8). I have not tried to compile QEMU myself though.

Hard-coding 'binary' (or using my patch) still makes it work.

> You are right @CendioOssman, I did test QEMU + trunk noVNC ~2 weeks ago, and everything worked fine for me.

Are you sure you didn't use websockify?

The full version string of the latest QEMU I used is: QEMU emulator version 4.1.0 (Debian 1:4.1-1+b2)

**Comment by samhed** [comment]
> Are you sure you didn't use websockify?

I probably used websockify. I don't recognize having used the "websocket" option for qemu that you used

> qemu-system-x86_64 -vnc :0,websocket

The ideal way forward would be if QEMU would fix this in their end, would you mind reporting to them @dmbasso?

**Comment by samhed** [comment]
I reported a bug to QEMU:

https://bugs.launchpad.net/qemu/+bug/1849644

Everyone who encounters this problem should write on that bug that you wish QEMU to fix this. 

> Providing the option will allow more servers to be used, I don't see any drawback besides a slight increase in UI complexity (although it is already hidden in the advanced options).

The biggest drawback with this is that noVNC will continue to promote bad behaviors. noVNC is working like intended and we do not want to add code for being compatible with broken servers.

Hopefully QEMU will fix their code soon enough.

**Comment by undefinedd** [comment]
> > Are you sure you didn't use websockify?
> 
> I probably used websockify. I don't recognize having used the "websocket" option for qemu that you used
> 
> > qemu-system-x86_64 -vnc :0,websocket
> 
> The ideal way forward would be if QEMU would fix this in their end, would you mind reporting to them @dmbasso?

Sorry to bother you, is the official qemu websocket available now? I tried to use it for him, but it didn't work. I use him in the kvm virtual machine.
this is my kvm virtual machine xml config file：
`<graphics type='vnc' port='-1' autoport='yes' websocket='8999'>
      <listen type='address'/>
    </graphics>
`

**Comment by samhed** [comment]
QEMU has not fixed their code yet. A patch was sent to them 4 weeks ago, but there hasn't been any reaction as far as I can tell.

**Comment by dmbasso** [comment]
For the record, the patch has been queued to be merged [into QEMU 5.0](https://lists.nongnu.org/archive/html/qemu-devel/2019-12/msg00264.html). Thank you for your assistance, @samhed.

**Comment by samhed** [comment]
Glad to hear it!
