### ISSUE TITLE
getting stuck displaying "connecting" after connection to server

### ISSUE THREAD

**Issue by timoklingenhoefer** [novnc/noVNC#1305]
Hi 
I am using the demo application (the one used for enbedding (vnc.html)) to connect to a x11vnc server. 

It appears as if noVNC gets stuck displaying 'connecting' after the connection to the server has been established. 

This is the log of the x11vnc server:
 
    The VNC desktop is:      odroid:1
    PORT=5901
    10/10/2019 11:13:58 Got connection from client 192.168.1.159
    10/10/2019 11:13:58   other clients:
    10/10/2019 11:13:58 Got 'ws' WebSockets handshake
    10/10/2019 11:13:58   - webSocketsHandshake: using base64 encoding
    10/10/2019 11:13:58   - WebSockets client version hybi-13
    10/10/2019 11:13:58 Disabled X server key autorepeat.
    10/10/2019 11:13:58   to force back on run: 'xset r on' (3 times)
    10/10/2019 11:13:58 incr accepted_client=1 for 192.168.1.159:49535  sock=12
    10/10/2019 11:13:59 created   xdamage object: 0x4800040
    10/10/2019 11:13:59 copy_tiles: allocating first_line at size 61
    10/10/2019 11:14:08 created selwin: 0x4800041
    10/10/2019 11:14:08 called initialize_xfixes()
    10/10/2019 11:14:12 cursor_noshape_updates_clients: 1
    10/10/2019 11:14:14 selection_send: no send: uninitialized clients

The console output in chrome:

    >> RFB.constructor
    >> Display.constructor
    User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)  
    Chrome/77.0.3865.90 Safari/537.36
    << Display.constructor
    << RFB.constructor
    New state 'connecting', was ''.
    >> RFB.connect
    connecting to ws://192.168.1.195:5901/websockify
    << RFB.connect
    >> WebSock.onopen
    Starting VNC handshake
    << WebSock.onopen
    Ignoring empty message

**Client:**
 - OS: win 7
 - Browser: chrome 
 - Browser version: 77.0.3865.90

**Server:**
 - noVNC version: 412d93060dd26a69dd02debe8074364bbb1937e8
 - VNC server: x11vnc 0.9.13 lastmod: 2011-08-10
![not that interesting...](https://user-images.githubusercontent.com/39903601/66755778-f9820c00-ee98-11e9-8356-9e2215e2178d.png)

The HTML is served from an apache server with the no-cache header set.

    10/10/2019 11:14:14 selection_send: no send: uninitialized clients

x11 displays this message when the connecting client is not yet initialized. 
So it looks like noVNC gets stuck in the initializing phase. 
The line "Starting VNC handshake" should be followed by the negotiation of the RFB protocol version (_rfb_init_state is set to "ProtocolVersion"). This doesn´t seem to be happening. 
I tried setting the rfb-version in x11 to 3.3 (-rfbversion 3.3 argument) but this also does nothing.

Looking into the connection process I found that the 'protocols' attribute in websock.js:open are empty. This is caused by calling the RFB constructor without a wsProtocols option.
 I am not sure is this is intended or even related to my problem.

**Comment by samhed** [comment]
Please fill in our issue template completely, what version of noVNC are you using? With "the demo application" do you mean vnc.html?

Could you show a screenshot of the problem?

**Comment by juanjoDiaz** [comment]
This might be related to something that I'm noticing lately as well which is that RFB is not always emitting the `connect` event when connecting. No idea why.

**Comment by samhed** [comment]
@timoklingenhoefer I didn't notice until now that you did fill in more information, sorry.

This is probably the 'binary' subprotocol issue again, see #1304 and #1310. As far as I know x11vnc uses libvncserver, and libvncserver had a bug that caused it to stop working with noVNC master. This bug has been fixed in libvncserver master 2 weeks ago.

Either you use the very latest master of libvncserver or you can downgrade your noVNC to version 1.1.0 which should be compatible with the broken old server.
