### ISSUE TITLE
Occasionally the mouse cursor disappears when connecting remotely

### ISSUE THREAD

**Issue by Master0711** [novnc/noVNC#1307]
**Describe the bug**
Under the Windows platform，mouse cursor disappears.
But in read-only mode, the mouse cursor does not disappear.
Is there anyone else experiencing this kind of situation?

**Comment by samhed** [comment]
Yes, we've seen this too. Does the cursor disappear after a click? And then reappear after moving the mouse again? And I'm guessing you're using Chrome or Edge? I believe this problem doesn't exist on Firefox.

@CendioNiko could you fill in your findings here?

**Comment by Master0711** [comment]
In fact, when this problem occurs with a client, the problem can be reproduced no matter what browser is used.**At some point，for a specific client.**And once the mouse enters the connection window cursor disappears.Move the mouse again and the cursor will not appear.

**Comment by samhed** [comment]
Then this is something completely different, it is likely it's not even a bug in noVNC.

Are you sure the mouse is supposed to be shown?

And please could you fill in the complete issue form so that we get all the info we need?

**Comment by Master0711** [comment]
@samhed Thank you for your reply.This phenomenon does not occur by replacing the client.The next time this phenomenon occurs, I will record it in detail.

**Comment by samhed** [comment]
Ok. If the problem doesn't happen with a different VNC client, then it might be worth looking into.

We have recently done some fixes with regards to cursors on some platforms, it might be worth pull in the latest changes.

Get back to us if you see the problem again.

**Comment by Master0711** [comment]
@samhed No problem.
