### ISSUE TITLE
clipboardPasteFrom does not work

### ISSUE THREAD

**Issue by Vorob-Astronaut** [novnc/noVNC#1308]
**Describe the bug**
When I use clipboardPasteFrom it does not work, so for now I handled that in this way:
```
      const clipboardData = e.clipboardData || window.clipboardData;
      const pastedData = clipboardData.getData('Text');

      const str = String(pastedData);
      // this.rfb.clipboardPasteFrom(str); does not work
      
       setTimeout(() => {
         for (let i = 0, len = str.length; i < len; i++) {
           this.rfb.sendKey(str.charCodeAt(i));
         }
       }, 100);
```
**Client (please complete the following information):**
 - OS: MAC iOS
 - Browser: Chrome
 - Browser version: 71 / Version 76.0.3809.132 (Official Build) (64-bit)

**Server (please complete the following information):**
 - noVNC version: commit id 8acadd9e
 - VNC server: xtigervnc 1.3.1
 - WebSocket proxy: websockify

**Context**
the server logs does not show any output about that action

**Comment by Vorob-Astronaut** [comment]
What I'm doing wrong?

**Comment by CendioOssman** [comment]
TigerVNC includes two different servers, but only one of them has clipboard support. How did you start it?

**Comment by Vorob-Astronaut** [comment]
@CendioOssman 
thnx for the reply, I do that in this way:

`/usr/bin/Xtigervnc :0 -geometry 1280x768 -depth 24 -desktop vnc -SecurityTypes None -nolisten tcp`

**Comment by pm-pm** [comment]
When using old tigervnc server version (1.7) you have to start "vncconfig" to have copy&paste support.
Later version (1.8 or 1.9) have copy&paste integrated.

**Comment by samhed** [comment]
I'm curious, what makes you run such an old version of TigerVNC as 1.3.1?

**Comment by gicuuu3** [comment]
We didn't have a good opportunity/reason to upgrade so far. And since our last attempt didn't go smoothly(some seemingly random crashes here and there on some of the applications running on top of it) we decided to stay on 1.3 until we get more time to investigate an update path.

**Comment by samhed** [comment]
I think noVNC correctly sends the clipboard data but I suspect that your server doesn't handle it. I'd recommend testing with a newer version.

Otherwise, I'm unsure what TigerVNC 1.3.1 has as far as features go, but did you try what @pm-pm said to start vncconfig?

**Comment by gicuuu3** [comment]
@samhed We've tested it with the latest version of xvnc(1.9) and it does work as expected. Thanks for the help guys.

**Comment by samhed** [comment]
Good to hear!
