### ISSUE TITLE
Mouse pointer position

### ISSUE THREAD

**Issue by meong-congkok** [novnc/noVNC#131]
I'm using OpenNebula Sunstone on openSUSE 12.1 using browser chrome 16 and firefox 10. I created guest hosts running Debian 6 and windows XP. The problem annoying me is the cursor position of local mouse and remote mouse (in guest hosts) are not the same position. It's very annoying because if the local mouse moves out of the box, the remote mouse cannot accept the mousemove event. Whereas the target is near the edge, so it's very difficult to reach the target.
Am I missing something or is it really a bug? How to cope with it?

**Comment by centerorbit** [comment]
@andrew-azarov In the off chance that you're still trying to get this to work 6 years later. I solved this by foregoing the VNC server, and instead used the `-vnc :0` flag on qemu itself. Qemu has its own built-in VNC server, and using that has given me excellent results.
