### ISSUE TITLE
Nginx+novnc don't work

### ISSUE THREAD

**Issue by obla4ko** [novnc/noVNC#1313]
Hello!
Today i was install novnc on my Centos 7. NoVNC worked perfect, in my local network. But when i try use it from Internet with Nginx I can't connect to my vnc and always had error message "Server disconnected (code: 1006)"

My nginx config:
```
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;
    #keepalive_timeout  0;
    keepalive_timeout  65;
    #gzip  on;

upstream vnc_proxy {
    server 127.0.0.1:6080;
}

server {

  listen 80 ssl http2;
  listen [::]:80 ssl http2;

  server_name test.my.cloud;

 location /websockify {
          proxy_http_version 1.1;
          proxy_pass http://127.0.0.1:6080;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";

          # VNC connection timeout
          proxy_read_timeout 61s;

          # Disable cache
          proxy_buffering off;
}

 location /vncws {
            index vnc.html;
            alias http://127.0.0.1:6080;
            try_files $uri $uri/ /vnc.html;
    }

#location / {
#                    proxy_pass http://127.0.0.1:6080;
#  }

  ssl_certificate /etc/ssl/certs/server.crt;
  ssl_certificate_key /etc/ssl/private/server.key;
  ssl_client_certificate /etc/ssl/certs/ca.crt;
  ssl_verify_client on;

  keepalive_timeout 70;
  fastcgi_param SSL_VERIFIED $ssl_client_verify;
  fastcgi_param SSL_CLIENT_SERIAL $ssl_client_serial;
  fastcgi_param SSL_CLIENT_CERT $ssl_client_cert;
  fastcgi_param SSL_DN $ssl_client_s_dn;

  ssl_protocols TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POL128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;

}

}
```
When i try next link : https://test.my.cloud/vncws/vnc.html  i have error message
`2019/11/03 21:56:44 [error] 4997#4997: *4 open() "/etc/nginx/html/vnc.html" failed (2: No such file or directory), client: 192.168.1.3, server: test.my.cloud, request: "GET /vncws/vnc.html HTTP/2.0", host: "test.my.cloud:80"`

I don’t understand what I have to add to the file for it to start working.

**Comment by samhed** [comment]
I don't have any experience with nginx myself. Have you looked at our wiki page for nginx?

I believe some of these people have used noVNC with nginx: @johnmarcou, @tfinke, @commodo, @tdp100, @s00ner, @ebuildy, anyone of you guys have the time to look at this?

**Comment by tfinke** [comment]
you should try to configure your nginx according https://github.com/novnc/noVNC/wiki/Proxying-with-nginx. 

It seems your traffic runs through port 80 and maybe is not encrypted. Be sure to use https (best on it's well known port 443).

**Comment by juanjoDiaz** [comment]
I'm using NGINX without a problem.
As mentioned, you might want to review your config.

```
# Redirect HTTP traffic to HTTPS
server {
    listen 80 http2 default_server;
    listen [::]:80 http2 default_server;

    server_name _;

    return 301 https://$host$request_uri;
}

# Server HTTPS
server {
  listen 443 ssl http2 default_server;
  listen [::]:443 ssl http2 default_server;
  
  # Rest of the config ....
}
```

**Comment by commodo** [comment]
It's been a while since I used it. And I don't have any configs at hand.
Can't offer much input.

Alex

**Comment by salderma** [comment]
I'm not an nginx expert, but I'm pretty sure you can't use the `alias` directive with URL paths, the nginx doc shows it's for file paths on the fileystem underneath nginx.

**Comment by samhed** [comment]
Thanks for the help guys, much appreciated.

@obla4ko hasn't responded, I'm closing this.
