### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by zwick88** [novnc/noVNC#1315]
Hi there,

i'm using a lot of embedded Linux devices for several jobs. Some devices are connected via LTE Mobile Routers and other devices only with 3G or 2G.
Now my problem is that i could not connect to the server via noVnc. Error message: Failed to connect to server. When i try to connect with realvnc client or guacamole, the connection will established.
I think the Problem ist a connection timeout. 

I can connect to the Clients with RealVNC or Guacamole which with noVNC dosnt work.

Is it Possible that a timeout val is the Problem? Can someone give me a help to find the right line in the code?

**Comment by CendioOssman** [comment]
I'm afraid we have no control over such things. It is entirely up to the browser. What does your browser console say?

**Comment by zwick88** [comment]
Why does it work with the same Browser and guacomole? 

> Gewechselt zu http://vnc.power-dog.eu/?host=live2.power-dog.eu&port=1692&password=50512&true_color=0
Firefox kann keine Verbindung zu dem Server unter ws://live2.power-dog.eu:1692/websockify aufbauen. websock.js:278:30
WebSocket on-error event util.js:42:55
WebSocket on-close event util.js:42:55
Failed when connecting: Failed to connect to server( (code: 1006)) util.js:44:55
    Error http://vnc.power-dog.eu/core/util.js:44
    _fail http://vnc.power-dog.eu/core/rfb.js:579
    RFB http://vnc.power-dog.eu/core/rfb.js:234
    onclose http://vnc.power-dog.eu/core/websock.js:306

**Comment by pm-pm** [comment]
Can you connect directly when you are in the same location?

**Comment by zwick88** [comment]
> Hi there,
> 
> i'm using a lot of embedded Linux devices for several jobs. Some devices are connected via LTE Mobile Routers and other devices only with 3G or 2G.
> Now my problem is that i could not connect to the server via noVnc. Error message: Failed to connect to server. When i try to connect with realvnc client or guacamole, the connection will established.
> I think the Problem ist a connection timeout.
> 
> I can connect to the Clients with RealVNC or Guacamole which with noVNC dosnt work.
> 
> Is it Possible that a timeout val is the Problem? Can someone give me a help to find the right line in the code?

Of course I can connect if I'm local, otherwise I can not connect with Guacamole or a VNC client

**Comment by pm-pm** [comment]
Can you also connect with noVNC when you are local?

**Comment by anzyelay** [comment]
i cannt connect to vncserver by firefox, ie or chrome when i use websockify-other instead of websockify, but i can do  that by using v1.1.0. what's wrong?

**Comment by CendioOssman** [comment]
I'm afraid this is some browser issue and it isn't much we can do about it. Please report this to Firefox and hopefully they can help out.
