### ISSUE TITLE
Empty Password not allowed to connect

### ISSUE THREAD

**Issue by chrisjdev** [novnc/noVNC#1317]
**Describe the bug**
I have a VNC where you can configure an empty password. I am then able to connect to it with RealVNC, but unable to connect to it with noVNC. noVNC says credentialsrequired.

**To Reproduce**
1. Configure a VNC server with no username and an empty password
2. Attempt to connect with noVNC
3. See error

**Expected behavior**
Connects to the VNC server with an empty-string password without issue.

**Client (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Browser version: 78

**Server (please complete the following information):**
 - noVNC version: 1.1
 - VNC server: x11vncserver

**Additional context**
I think it comes down to this check in rfb.js, "if (!this._rfb_credentials.password)", since an empty password is falsy, it doesn't accept it as potentially valid. I found by changing it to "if (this._rfb_credentials.password === undefined)", it then worked as I expected.

**Comment by samhed** [comment]
Could you share the command used to start x11vncserver?

**Comment by chrisjdev** [comment]
Looks like it's `/usr/bin/x11vnc -quiet -passwdfile /tmp/.vncpass -forever -shared -rotate +90 ~` and the contents of /tmp/.vncpass is `__EMPTY__`

**Comment by samhed** [comment]
Thanks, I can reproduce the issue.

**Comment by samhed** [comment]
Fixed in #1318
