### ISSUE TITLE
Procotol error: Frame not masked

### ISSUE THREAD

**Issue by al3x609** [novnc/noVNC#1323]
**Describe the bug**
Hi, Im working with novnc on last github version, websockify (token directory)

when I go to connect to the server , in the web console i got "**Procotol error: Frame not masked**"

**Expected behavior**
a connection successful,
note: with the turbovnc client on macOS, i have not any problem .

**Screenshots**
<img width="706" alt="image" src="https://user-images.githubusercontent.com/4086644/68702801-6a2f4d80-0557-11ea-9b4c-b5df3e591ead.png">

**Client (please complete the following information):**
 - OS: MacOS 10.15
 - Browser: firefox, safari etc..
 - Browser version: firefox 71 (developer version), safari : 13.04

**Server (please complete the following information):**
  turboVNC server 2.2.3
  virtualgl   2.6.3
  centos 7.7

**Comment by CendioOssman** [comment]
I'm afraid that looks like a bug in websockify, not noVNC. Are you using the latest version of websockify?

**Comment by al3x609** [comment]
noVNC and websockify, both  installed from git master repo 
(websockify with git clone, then python setup.py install ) , 
python 2.7,
pip 19.3 
noVNC 1.1.0

pip show websockify:
```
Name: websockify
Version: 0.9.0
Summary: Websockify.
Home-page: https://github.com/novnc/websockify
Author: Joel Martin
Author-email: github@martintribe.org
License: LGPLv3
Location: /usr/lib/python2.7/site-packages/websockify-0.9.0-py2.7.egg
```

one more thing, Im working behind apache reverse proxy,  with the mod_proxy_wstunnel enabled

**Comment by CendioOssman** [comment]
Ah. I'm afraid this is a bug in `mod_proxy_wstunnel` then as that is what is communicating with the browser.

Please have a look at filing a bug with them. Hopefully they can help you out.
