### ISSUE TITLE
Connecting Error

### ISSUE THREAD

**Issue by opcoderpro** [novnc/noVNC#1324]
I dont know if this is a bug or if something is wrong on my side but when I hit the connect button in the demo it shows up with this error 
![image](https://user-images.githubusercontent.com/35740552/68814609-dfc21900-063e-11ea-8e87-282ab7190906.png)

1. Go to the demo
2. Click on hit connect
3. See error

I thought it was going to work

**Client (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Browser version: 

**Server (please complete the following information):**
 - noVNC version: Demo
 - VNC server: clearvnc
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
That's definitely a bug. We'll have a look.

**Comment by CendioOssman** [comment]
Should be fixed in 9f557f5280063b6e194da4541db75c568d27a901. Thanks for reporting.
