### ISSUE TITLE
Flicker on auto resize window 

### ISSUE THREAD

**Issue by GogoAkira** [novnc/noVNC#1325]
Not sure if bug. 

Using latest version on latest Debian to view VM from proxmox via latest stable chrome. When box auto resize window is checked it just stays in place and whole screen flickers, turning compositor on and off makes no difference. When box not selected it's pretty awesome because it works :).

Is this just me? I'm using bspwm, novnc pops up in a terminal, is it just trying to scale every half second but it can't because the window size is preset?

**Comment by samhed** [comment]
Please fill in our issue template.

Are you using noVNC or some project that makes use of noVNC? What version?

What VNC server are you using? What version?

Could you provide a screenshot or video of the problem?

**Comment by GogoAkira** [comment]
Sorry I was away. I'm back now.

Using a project 'proxmox' that makes use of noVNC

Proxmox machine comes with:
```bash
ii  novnc-pve                            1.0.0-60                    all          HTML5 VNC client
ii  vncterm                              1.6-1                       amd64        VNC Terminal Emulator
```
My debian comes with:
```bash
ii  gir1.2-gtk-vnc-2.0:amd64             0.9.0-1.1                       amd64        GObject introspection data for GTK-VNC

ii  libgtk-vnc-2.0-0:amd64               0.9.0-1.1                       amd64        VNC viewer widget for GTK+3 (runtime libraries)

ii  libgvnc-1.0-0:amd64                  0.9.0-1.1                       amd64        VNC GObject wrapper (runtime libraries)
```
Also I have ```virt-manager 2.0``` but don't know if that is of consequence.
[Video link on google drive](https://drive.google.com/file/d/1u9REAUlq8DaG6oNKCgWHo9l81F0ELUaP/view?usp=sharing)
![1](https://user-images.githubusercontent.com/9360410/70127553-e2fa6480-1640-11ea-8862-dab460d6af3d.jpg)

**Comment by samhed** [comment]
What version of noVNC is proxmox using, 1.0.0? Version 1.1.0 has been out for many months.
Also, that noVNC GUI looks modified and some of this auto-resize logic is part of the GUI, we can't help with code that isn't noVNC code.

**Comment by samhed** [comment]
Have you asked the proxmox people about this?

**Comment by GogoAkira** [comment]
Oh ok thanks, I did not ask but I will, I didn't actually know to ask them until you just told me now :)

**Comment by samhed** [comment]
I think that's a good place to start. Feel free to reopen this if it turns out to be noVNC's fault.
