### ISSUE TITLE
GPU offload where possible?

### ISSUE THREAD

**Issue by BloodyIron** [novnc/noVNC#1328]
I can't reliably tell from the docs/etc, if noVNC does any GPU offloading, but in the areas I use noVNC it seems to cause video playback in other windows to not run as well.

Is there any feasibility to GPU offloading of the noVNC client viewing?

**Comment by CendioOssman** [comment]
It depends on what you mean. noVNC is written in JavaScript, so it isn't particularly hardware centric. The browser till generally use the GPU to accelerate our draw operations though.

Can you describe your issue in more detail?

**Comment by BloodyIron** [comment]
I don't know how to describe my situation better than I have in a way that would give more detail.

**Comment by samhed** [comment]
It's largely up to the browser, and as @CendioOssman said most browsers should be using the GPU to do drawing in noVNC. Is this not happening in your case?

**Comment by BloodyIron** [comment]
I am unsure how to tell if the noVNC windows are drawn by my CPU or my GPU, but I have a plenty beefy rig. Ryzen 5 2600, and RX 580, so either way plenty of horse power. It was concerning when having multiple noVNC windows (like 2 or 3) open meant video playback on the same system was starting to chug.

**Comment by samhed** [comment]
And did you verify that the bottleneck was CPU? Most browsers have some sort of resource monitoring.

**Comment by samhed** [comment]
No response.

**Comment by BloodyIron** [comment]
In this case I'm not sure how to verify if noVNC is GPU offloading or not, could use some additional instruction please. Sorry I didn't respond earlier, missed the alerts.

**Comment by samhed** [comment]
Well, for example if you use Chrome's performance recording you get a "GPU" section in the result which shows how much the GPU was used.

My question was if you have verified that your bottleneck was CPU or not. That would be fairly easy to see, if you just check 'top' on the machine running your browser. If, when watching a movie through noVNC, your CPU is around 100% most of the time on the machine running the browser, then that's the bottleneck and GPU offloading could help.

**Comment by BloodyIron** [comment]
I'm not really finding any bottleneck info, but I don't recall exactly what I had open when I was having the issue. Let's just close this for now and if I encounter it again I'll try to see if I can collect more info from the aspect you mentioned. Thanks though!
