### ISSUE TITLE
图片不能加载

### ISSUE THREAD

**Issue by litongjava** [novnc/noVNC#1330]
![image](https://user-images.githubusercontent.com/31761981/69052492-1a162680-0a42-11ea-8640-fb2489fb1d2a.png)
问题
1.不能加载
2.终端 2个汉字应该正为 '中断'
在CentOS-7服务器上,中文环境下安装,安装过程如下
```
wget -O noVNC-1.1.0.tar.gz https://codeload.github.com/novnc/noVNC/tar.gz/v1.1.0
tar -zxf noVNC-1.1.0..tar.gz -C /opt/
cd /opt/noVNC-1.1.0/utils/
./launch.sh --vnc localhost:5901
```
启动服务进行连接,连接成功之后就出现了上面的问题

**Comment by CendioOssman** [comment]
I'm afraid none of the core developers understand Chinese. Do you think you could explain your issue in English?

**Comment by bhzhu203** [comment]
He said  :
1. The picture were not be  loaded. (Maybe it is html/css problem)
2. Wrong translation. The right translation is "中断连接" not "终端链接”

**Comment by samhed** [comment]
The problem with the pictures is related to the webserver that you use, you should be able to see some errors there.

With regards to the translation error, please pitch in at #1337

**Comment by CendioOssman** [comment]
The picture error is commonly cause by the web server not setting the correct mime types. For websockify that usually means you don't have the system mime packages installed. Please have a look there and you should hopefully get it working.

**Comment by samhed** [comment]
Note that the translation for "Disconnect" was updated in 274652d11916cf9b904caeaebc845419791296f1
