### ISSUE TITLE
Polite hint: TigerVNC 1.10.0 is released

### ISSUE THREAD

**Issue by pm-pm** [novnc/noVNC#1331]
Hello.

i hope it's not too impolite to point out that tigervnc was released with [release 1.10.0](https://github.com/TigerVNC/tigervnc/releases). After 16 month.

Since Tigervnc works very well with noVNC (remote resize) I wanted to give you the hint here.

If this is undesirable, please delete it.

Thanks 

pm-pm

**Comment by CendioOssman** [comment]
Thanks. It's not something we pay much attention to here though. We try to make sure we're generally compatible with all VNC servers. :)

**Comment by diederikvanbochove** [comment]
Am I missing something, or is CendioOssman the one who released TigerVNC 1.10.0, and at the same time is one of the core developers of noVNC?

**Comment by samhed** [comment]
@diederikvanbochove That is correct 🙂

Cendio's development team works actively with both noVNC and TigerVNC.
