### ISSUE TITLE
Animations cause high CPU usage and freezing

### ISSUE THREAD

**Issue by andrewmcewen** [novnc/noVNC#1332]
**Describe the bug**
When connecting to a VNC server that has Google Chrome tab open with the Figma home page loaded, there are lots of animations which causes high CPU usage on the VNC client machine. If I click away from the tab with the VNC client, the tab freezes.

**To Reproduce**
1. Create a VNC client using NoVNC and connect to a VNC server
2. Open up Google Chrome and go to Figma's homepage
3. Wait 10 seconds
4. Experience high CPU

**Client:**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Browser version: 78.0.3904.97

**Server:**
 - noVNC version: 1.1.0
 - VNC server: TigerVNC
 - WebSocket proxy: websockify

**Comment by samhed** [comment]
Are you seeing the same behavior any time you're getting a lot of graphics updates from the server? Like if you're watching a movie over VNC?

Have you tested other VNC viewers?

**Comment by andrewmcewen** [comment]
Yes I am seeing the same behaviour, when I went to Youtube the same thing happened. I haven't tested other VNC viewers but it happens on both Tiger and X11 VNC.

**Comment by samhed** [comment]
Would you mind testing a different VNC viewer on the same macOS client machine? TigerVNC has a viewer for macOS for example.

**Comment by CendioOssman** [comment]
More importantly, do you see this with other browsers?

**Comment by samhed** [comment]
No response.
