### ISSUE TITLE
novnc screen goes blank on Windows 10 Chrome

### ISSUE THREAD

**Issue by samgoud** [novnc/noVNC#1333]
We are using the novnc version https://github.com/novnc/noVNC/commit/2b4c655405e2f9cffad881341053c3d4a7270cce

On chrome multiple mouse clicks or drag operations on the novnc rendered ui is clearing html canvas.  We see a blank screen which gets reset only after reloading the browser page.

This issue is seen only on chrome (we are using Version 78.0.3904.97 (Official Build) (64-bit))
The issue was not reproducible Firefox.

**Comment by samgoud** [comment]
Update:

We observed uptick in chrome memory and finally leading to crash
![image](https://user-images.githubusercontent.com/32926439/69418845-724e7080-0d41-11ea-8ede-67a750f5ee0f.png)

**Comment by CendioOssman** [comment]
Could you describe your case in more detail so we can try to reproduce it?

**Comment by samgoud** [comment]
We are rendering a rich UI framework built around Qt. What we observed is that when we have multiple clicks or drag on UI objects within the UI, we start seeing this spike in memory. It'll stay that way, until the browser tab is closed/refreshed.

**Comment by samhed** [comment]
Are you sure the memory leaks come from the noVNC code?

**Comment by samgoud** [comment]
Yes, for following reasons:
1. noVnc is the only ui element we are rendering in the browser window. We do not have any other tabs or ui contributing to leak
2. We were using a older novnc version (checked out in late 2016) and that does not have any memory issues. We started seeing this issue, only when we moved to the latest novnc

**Comment by samhed** [comment]
Ok, well then as @CendioOssman said, we will need more details if we're going to be able to reproduce the issue.

* What VNC server are you using?
* Multiple clicks or drag on UI objects? What do you mean with this?
* Could you make a video recoding of this?

**Comment by samgoud** [comment]
1. We could see this on both tigervnc 1.7 and tigervnc 1.8
2. We have a qt app where we enabled mouse drag, drop. We are viewing this app in browser using novnc. When we do multiple mouse clicks on this app in random places or do a drag of QSplitter inside the qt windows, we see at one point the browser memory start increasing and continues to increase on every mouse click.
3. Unfortunately its a proprietary tool and we cannot make a video recording of this.

**Comment by samgoud** [comment]
We could see this on both tigervnc 1.7 and tigervnc 1.8
We have a qt app where we enabled mouse drag, drop. We are viewing this app in browser using novnc. When we do multiple mouse clicks on this app in random places or do a drag of QSplitter inside the qt windows, we see at one point the browser memory start increasing and continues to increase on every mouse click.

**Comment by samgoud** [comment]
The newer version of chrome i.e 79.0.3945.79 (Official Build) (64-bit), doesn't reflect the memory uptick reported above. We have tried it a couple of times and can now confirm that the memory uptick is only seen on Version 78.0.xxxx.yy (Official Build) (64-bit))
Hopefully, this information will come-in handy in the debug.

**Comment by CendioOssman** [comment]
In that case I'd say it's one of the upstream Chrome bugs we've seen on other issues. If 79 is fine then we'll just let everyone upgrade and solve things that way.

Thanks for testing!
