### ISSUE TITLE
noVNC is not compatible with the websocket code in libvncserver anymore

### ISSUE THREAD

**Issue by patrakov** [novnc/noVNC#1334]
**Describe the bug**
noVNC no longer connects to the websocket server provided by libvncserver. The connection just hangs.

**To Reproduce**
1. If your distribution has libvncserver 0.9.12, please downgrade to 0.9.11 due to an unrelated bug. Compiling and LD_PRELOAD'ing libvncserver.so and libvnccclient.so, or using a version from Arch Linux Archive is OK on Arch Linux, but Ubuntu 19.10 still has an old-enough version.
2. Run: x11vnc -forever
3. On a different PC, serve noVNC with nginx over HTTP (do not proxy the websocket) and load it in a browser.
4. In the browser, set websocket details as follows: set the server to the IP address of the PC running x11vnc, port to 5900.
5. Click "connect".
6. Wait, wait, wait. It just hangs and eventually times out.

**Expected behavior**
x11vnc should display the remote desktop to the browser. In fact, that's what happens before commit c912230.

**Client (please complete the following information):**
 - OS: Arch Linux on the client, tested with buth Arch Linux and Ubuntu 19.10 on the servers.
 - Browser: Tested both in Chromium 78.0.3904.108 and Firefox 70.0.1
 - Browser version: see above

**Server (please complete the following information):**
 - noVNC version: The issue is introduced by commit c912230
 - VNC server: x11vnc 0.9.13 (Ubuntu) or 0.9.16 (Arch)
 - WebSocket proxy: no proxy, no websockify, use built-in websocket support in libvncserver 0.9.11.

**Additional context**
It is important that you use libvncserver 0.9.11, because 0.9.12 has an unrelated bug, to be reported separately.

**Comment by patrakov** [comment]
That libvncserver 0.9.12 bug is actually already reported, https://github.com/LibVNC/libvncserver/issues/297

**Comment by CendioOssman** [comment]
Please see #1310. Please use an older noVNC (or patch it) if you need to use an older libvncserver.
