### ISSUE TITLE
Some good suggestions

### ISSUE THREAD

**Issue by QQ2017** [novnc/noVNC#1336]
**Is your feature request related to a problem? Please describe.**
1. Support to modify the transmission encoding such as tight or raw;
2, support to modify the color depth, such as 24 bit or 256 color bit, which can save a lot of traffic, and can improve the user experience when the network conditions are bad.

**Comment by samhed** [comment]
See #396

**Comment by QQ2017** [comment]
> See #396

Yes, like many people who use novnc, I also hope that novnc can support setting 256 colors and encoding methods. People often want to use 256 colors in a poor network environment, and use true colors when the network is better.
