### ISSUE TITLE
Chinese translation correction

### ISSUE THREAD

**Issue by QQ2017** [novnc/noVNC#1337]
`{
    "Connecting...": "连接中...",
    "Disconnecting...": "正在断开连接...",
    "Reconnecting...": "重新连接中...",
    "Internal error": "内部错误",
    "Must set host": "请提供主机名",
    "Connected (encrypted) to ": "已加密连接到",
    "Connected (unencrypted) to ": "未加密连接到",
    "Something went wrong, connection is closed": "发生错误，连接已关闭",
    "Failed to connect to server": "无法连接到服务器",
    "Disconnected": "已断开连接",
    "New connection has been rejected with reason: ": "连接被拒绝，原因：",
    "New connection has been rejected": "连接被拒绝",
    "Password is required": "请提供密码",
    "noVNC encountered an error:": "noVNC 遇到一个错误：",
    "Hide/Show the control bar": "显示/隐藏控制面板",
    "Move/Drag Viewport": "拖放显示范围",
    "viewport drag": "显示范围拖放",
    "Active Mouse Button": "启动鼠标按鍵",
    "No mousebutton": "禁用鼠标按鍵",
    "Left mousebutton": "鼠标左鍵",
    "Middle mousebutton": "鼠标中鍵",
    "Right mousebutton": "鼠标右鍵",
    "Keyboard": "键盘",
    "Show Keyboard": "显示键盘",
    "Extra keys": "额外按键",
    "Show Extra Keys": "显示额外按键",
    "Ctrl": "Ctrl",
    "Toggle Ctrl": "切换 Ctrl",
    "Alt": "Alt",
    "Toggle Alt": "切换 Alt",
    "Send Tab": "发送 Tab 键",
    "Tab": "Tab",
    "Esc": "Esc",
    "Send Escape": "发送 Escape 键",
    "Ctrl+Alt+Del": "Ctrl-Alt-Del",
    "Send Ctrl-Alt-Del": "发送 Ctrl-Alt-Del 键",
    "Shutdown/Reboot": "关机/重新启动",
    "Shutdown/Reboot...": "关机/重新启动...",
    "Power": "电源",
    "Shutdown": "关机",
    "Reboot": "重新启动",
    "Reset": "重置",
    "Clipboard": "剪贴板",
    "Clear": "清除",
    "Fullscreen": "全屏幕",
    "Settings": "设置",
    "Shared Mode": "分享模式",
    "View Only": "仅查看",
    "Clip to Window": "限制/裁切窗口大小",
    "Scaling Mode:": "缩放模式：",
    "None": "无",
    "Local Scaling": "本地缩放",
    "Remote Resizing": "远程调整大小",
    "Advanced": "高级",
    "Repeater ID:": "中继站 ID",
    "WebSocket": "WebSocket",
    "Encrypt": "加密",
    "Host:": "主机：",
    "Port:": "端口：",
    "Path:": "路径：",
    "Automatic Reconnect": "自动重新连接",
    "Reconnect Delay (ms):": "重新连接间隔 (ms)：",
    "Logging:": "日志级别：",
    "Disconnect": "断开连接",
    "Connect": "连接",
    "Password:": "密码：",
    "Cancel": "取消"
}`

**Comment by QQ2017** [comment]
Please replace the language file "app\locale\zh_CN.json"

**Comment by samhed** [comment]
Thank you!

Fixed in 94c89284fc1f4e4c41c0cf949fb6ef4c6e8eb332

**Comment by CendioOssman** [comment]
What about 9653598af7935540c98b4b375d49ca1273762564? We seem to be changing the same things over and over. @wavezhang, what do you think?

**Comment by samhed** [comment]
Good eye @CendioOssman! The strings that seem to be conflicting between @QQ2017 and @wavezhang's translations are these:

### "Connected (encrypted) to "
original: "已加密链接到"
@wavezhang: "已连接到（加密）"
@QQ2017: "已加密连接到"

### "Connected (unencrypted) to "
original: "未加密链接到"
@wavezhang: "已连接到（未加密）"
@QQ2017: "未加密连接到"

### "Disconnected"
original: "链接已中断"
@wavezhang: "连接已中断"
@QQ2017: "已断开连接"

### "Hide/Show the control bar"
original: "显示/隐藏控制列"
@wavezhang: "显示/隐藏控制栏"
@QQ2017: "显示/隐藏控制面板"

### "Fullscreen"
original: "全屏幕"
@wavezhang: "全屏"
@QQ2017: "全屏幕"

### "Disconnect"
original: "终端链接"
@wavezhang: "中断连接"
@QQ2017: "断开连接"

**Comment by wavezhang** [comment]
> Good eye @CendioOssman! The strings that seem to be conflicting between @QQ2017 and @wavezhang's translations are these:
> 
> ### "Connected (encrypted) to "
> original: "已加密链接到"
> @wavezhang: "已连接到（加密）"
> @QQ2017: "已加密连接到"
> 
> ### "Connected (unencrypted) to "
> original: "未加密链接到"
> @wavezhang: "已连接到（未加密）"
> @QQ2017: "未加密连接到"

`未加密连接到` may be a little confusing, it can mean `not connected (encrypted) to` 
> 
> ### "Disconnected"
> original: "链接已中断"
> @wavezhang: "连接已中断"
> @QQ2017: "已断开连接"
no much difference
> 
> ### "Hide/Show the control bar"
> original: "显示/隐藏控制列"
> @wavezhang: "显示/隐藏控制栏"
> @QQ2017: "显示/隐藏`控制面板`"
`控制面板` usually refer to `control panel` ，`control bar` is more close to `控制栏` 
> 
> ### "Fullscreen"
> original: "全屏幕"
> @wavezhang: "全屏"
> @QQ2017: "全屏幕"
no much difference，but usually use `全屏`
> 
> ### "Disconnect"
> original: "终端链接"
> @wavezhang: "中断连接"
> @QQ2017: "断开连接"
no much difference

**Comment by samhed** [comment]
Do you have anything else to fill in @QQ2017 ? Otherwise we will go with @wavezhang's translations.

**Comment by QQ2017** [comment]
> Do you have anything else to fill in @QQ2017 ? Otherwise we will go with @wavezhang's translations.

You can use his translations

**Comment by samhed** [comment]
Ok :+1:

**Comment by samhed** [comment]
Fixed in 208e34bc3431ab3352b501783b420dc811c02dcb thanks to both of you for helping out!

**Comment by samhed** [comment]
Note that the changes won't be used in vnc.html until the next release.
