### ISSUE TITLE
noVNC on https ?

### ISSUE THREAD

**Issue by streki** [novnc/noVNC#134]
I think the title is explicit!

It's because I would like the vnc password to be protected!

**Comment by drui9** [comment]
2024 Update:
Available on nginx with let's encrypt certificate.
`
server {

        server_name www.yourdomain-here.com;

        location / {
                proxy_pass http://localhost:6080;
        }
        location /websockify {
                proxy_pass http://localhost:6080;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_read_timeout 600s;
                proxy_buffering off;
        }
        server_tokens off;
        gzip off;
}
`
Then run `sudo certbot --nginx`
