### ISSUE TITLE
noVNC connect to Unix Socket

### ISSUE THREAD

**Issue by hakasapl** [novnc/noVNC#1340]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I could be missing something, as I am new to using noVNC, but I'm trying to create a noVNC client running on an apache server (which I was able to get running), and I want the noVNC client and the vnc server to not listen to any ports other than apache's 80 and 443 (because of the many users that will be using this system at the same time). I was able to get the vnc server running on a socket file using tigervnc 1.10. I was also able to connect to that using noVNC with the websockify command `websockify --web ./ 6080 --unix-target=[PATH TO SOCKET]`. However, this still has the issue of listening on a port for each socket file, which defeats the purpose. It there any way to pass a socket file location in the query string?

**Describe alternatives you've considered**
Simply using a port for each user's vnc session, less than ideal.

**Additional context**
No

**Comment by samhed** [comment]
This is a websockify question and should be in that repo, but I believe the answer is no - you can't do that at the moment.

**Comment by kohlschuetter** [comment]
If it helps someone: I've found a simple workaround. We can trick noVNC into thinking it's setting up inet sockets but actually use Unix domain sockets instead.

See my "unsock" library here: https://github.com/kohlschutter/unsock
I've also [documented some instructions](https://github.com/kohlschutter/unsock/blob/main/doc/novnc.md) on how to set everything up.
