### ISSUE TITLE
credentialsrequired event not firing in vnc_lite.html

### ISSUE THREAD

**Issue by NoseyNick** [novnc/noVNC#1343]
**Describe the bug**

commit 01d4514deed5e61d849c6f720b6f165a88f2e106 appears to break `vnc_lite.html`'s ability to call `credentialsAreRequired` via `rfb.addEventListener("credentialsrequired", credentialsAreRequired);`
Is this because `const password = readQueryVariable('password', '');` ?
In any case, I think vnc_lite.html needs fixing to match?

**To Reproduce**
1. Go to 'vnc_lite.html` with no ?password=foo
2. See error "Something went wrong, connection is closed"

**Expected behavior**

`rfb.addEventListener("credentialsrequired", credentialsAreRequired);` fires. `password = prompt("Password Required:");` prompts for a password.

**Screenshots**

**Client (please complete the following information):**
 - OS: OpenSUSE, Mac, various
 - Browser: firefox (but also tested on chromium)
 - Browser version: 70.0.1 (64-bit) (and others)

**Server (please complete the following information):**
 - noVNC version: 80b078c469465f1ec45a5251a40eee51f13c5a1d works. 01d4514deed5e61d849c6f720b6f165a88f2e106 broke.
 - VNC server: x11vnc
 - WebSocket proxy: websockify

**Additional context**

Can workaround by `rfb = new RFB(document.getElementById('screen'), url, {});` but obviously then `readQueryVariable('password', ...)` doesn't read `?password=Passw0rd123`

**Comment by CendioOssman** [comment]
Fixed in 06a8f7d91a1555f9309791b6cda662cbb4539aa6.

**Comment by NoseyNick** [comment]
I beg to differ.
vnc_lite.html with no params should fire `credentialsAreRequired` (assuming a password is required) and still doesn't. It says "Loading", "Connecting", and nothing.
My own personal workaround - you may find something neater:
```
sed -i~ -E '/credentials:/ s/\{/!password ? {} : {/'           ~/www/vnc_lite.html
```

**Comment by CendioOssman** [comment]
Crap. I didn't notice that an `undefined` would be converted to a `null`. Should work as of d507d1415eff9fce16fb67963f34a1aa1ecb1fe4. Thanks for testing.

**Comment by NoseyNick** [comment]
Confirmed fixed, many thanks!
