### ISSUE TITLE
no image

### ISSUE THREAD

**Issue by aiifan** [novnc/noVNC#1344]
![微信图片_20191214160749](https://user-images.githubusercontent.com/24599746/70845660-4fb8fe80-1e8c-11ea-91d7-40646624c42c.png)
![微信图片_20191214160912](https://user-images.githubusercontent.com/24599746/70845661-55aedf80-1e8c-11ea-9745-4bf9f2ce0d38.png)

**Comment by CendioOssman** [comment]
Please see #1330.
