### ISSUE TITLE
Xlib: extension "RANDR" missing on display

### ISSUE THREAD

**Issue by xidianzhuxi** [novnc/noVNC#1345]
**Xlib: extension "RANDR" missing on display**
I try to use opencv in novnc or use vlc to play mp4 but an error occurs like this : `Xlib: extension "RANDR" missing on display`
i'd like to know that if novnc can only use tighvncserver ?how about vnc4server?

**Comment by samhed** [comment]
You can use any VNC server with noVNC. I suspect that your error will stay the same no matter which VNC client you use. I think it's a server-side problem you're having.

A quick search on google suggest that there might be something wrong with your LD_LIBRARY_PATH.
