### ISSUE TITLE
i can't write in azerty with my french keyboard 

### ISSUE THREAD

**Issue by Alterjerof** [novnc/noVNC#1349]
When i changed the Line on the file "/etc/libvirt/qemu/vm-name.xml"
From:
graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1'
To:
graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1' keymap='fr'

But i will change line when i create VM.

What is the file that generate /etc/libvirt/qemu/vm-name.xml for automate?
thx for help

**Comment by Alterjerof** [comment]
Is when i installed kimchi with :
http://www.ubuntuboss.com/ubuntu-server-18-04-as-a-hypervisor-using-kvm-and-kimchi-for-vm-management/

**Comment by samhed** [comment]
You should probably ask QEMU och Kimchi this question, this is the noVNC issue tracker.
