### ISSUE TITLE
noVNC throws an exception in IE11

### ISSUE THREAD

**Issue by shahasachin** [novnc/noVNC#1350]
Down load and build noVNC latest version.
In IE11 it throws "Map is undefined" exception.

Please let me know how to resolve the above issue.
![noVNC_IE11 Issue](https://user-images.githubusercontent.com/20108917/71306195-91edbd00-2403-11ea-8c28-6b94e60ab9bb.jpg)

**Comment by CendioOssman** [comment]
I'm afraid I can not reproduce the issue with IE here.

Your screenshot shows `vnc_auto.html`. That file was renamed a long time ago. Exactly what commit or version of noVNC are you using?

**Comment by shahasachin** [comment]
Can you please let me know the steps to build the noVNC?

**Comment by CendioOssman** [comment]
noVNC doesn't need to be built. It can be used without any extra steps. You can pre-convert things to improve load speed on IE, but that's it. Details are in the documentation:

https://github.com/novnc/noVNC/blob/master/docs/EMBEDDING.md#pre-conversion-of-modules

**Comment by shahasachin** [comment]
Already followed the steps defined in pre conversion of modules, getting above exception. 
NOTE - Loading vnc_auto.html (renamed vnc_lite.html to vnc_auto.html) in the child window through the application.

We are using latest version of noVNC.

**Comment by CendioOssman** [comment]
I'm afraid I can't really you help you more than that. `Map` is definitely supported by Internet Explorer, so there is something broken in your installation. Perhaps you've triggered some compatibility mode that makes it behave like an older browser?

You'll have to check your IE settings or see if there is some Microsoft forum that can help you out.

**Comment by samhed** [comment]
Yes, I believe this is the behavior you get when IE11 is running in compatibility mode. It seems IE for some reason has "Display intranet sites in compatibility view" enabled by default.

However, it also seems we can override this by using the `X-UA-Compatible` meta tag which we removed a while back. We must've missed this detail when removing it. Restored the tag in 
3a64043f28f704b9a1b6e7f85e1bc230e4ff8bc2 and 78bbf6bad2b3f18198f851908eb30633390b9938.

**Comment by shahasachin** [comment]
Thanks Samhed, issue is resolved.
