### ISSUE TITLE
Stuck on connecting

### ISSUE THREAD

**Issue by EvilDeadBlues** [novnc/noVNC#1353]
I have deployed a 0.9.12 libvncserver and tried connecting novnc to it but it didn't work. It worked with the deployed examples, so there is a problem with my implementation..

LibVNC server logs:
```
04/01/2020 16:23:44 Listening for VNC connections on TCP port 5900
04/01/2020 16:23:44 Listening for VNC connections on TCP6 port 5900
04/01/2020 16:23:45 Got connection from client 127.0.0.1
04/01/2020 16:23:45   other clients:
04/01/2020 16:23:45 Got 'ws' WebSockets handshake
04/01/2020 16:23:45   - webSocketsHandshake: using base64 encoding
04/01/2020 16:23:45   - WebSockets client version hybi-13
```

Additionally, how can I run it if I have socket.io running on the server?

![image](https://user-images.githubusercontent.com/52632251/71767668-b91db180-2f0e-11ea-80fa-d089bd220106.png)

**Comment by samhed** [comment]
See #1310

**Comment by samhed** [comment]
Old libvncserver versions doesn't work with new noVNC versions. Either upgrade libvncserver or downgrade noVNC.
