### ISSUE TITLE
Is it possible to "reset" the server's keyboard? (all keys up)

### ISSUE THREAD

**Issue by almightykiwi** [novnc/noVNC#1354]
Hi there,

We use novnc to connect to a TurboVNC server, and we are encountering an issue where a modifier key can be badly stuck in a "pressed" state on the server in certain conditions (loss of focus from the client, multiple connections).

(By "badly stuck", I mean that a non-intuitive combination of keys is required to unblock the situation.)

The issue is not in anyway specific to novnc, but I'm wondering: is there any way I can "reset" the keyboard state from novnc? (I'm not very familiar with RFB.)

(Or is there any novnc trick that can help us workaround this issue?)

**Comment by CendioOssman** [comment]
I'm afraid not. We only send events (press and release) and we have no idea what keys are pressed on the server.

It's also not possible to just send a bunch of release events for every key as there is a level of abstraction in the protocol that means we cannot get everything.

So I'm afraid this is an issue that needs to be resolved in the server.
