### ISSUE TITLE
../package.json error 404

### ISSUE THREAD

**Issue by andreymal** [novnc/noVNC#1355]
I tried to use noVNC from the master branch and run it in a subdirectory at http://127.0.0.1/novnc/vnc.html

But when I open this url, the `ui.js` script tries to download the http://127.0.0.1/package.json file which obviously does not exist. http://127.0.0.1/novnc/package.json exists instead.

https://github.com/novnc/noVNC/blob/2d53a785d521b29dbed9fbe0ec686ad2a34516bf/app/ui.js#L64

Is it a bug, am I doing something wrong, or subdirectory is not supported by design?

**Comment by CendioOssman** [comment]
Sub directories should be fine. It was probably just overlooked when testing that feature. Someone will have to debug it and see what can be done.

**Comment by alvintownsend** [comment]
Looks like a bug to me, and have made a patch that seems to work:

`WebUtil.fetchJSON('../package.json')` -> `WebUtil.fetchJSON('./package.json')`.

Please see the above pull request.

**Comment by samhed** [comment]
Fixed with #1361
