### ISSUE TITLE
No mouse cursor when integrating novnc-core lib

### ISSUE THREAD

**Issue by RufusK** [novnc/noVNC#1356]
I have novnc-core build into my website. i successfully established a connection and see the screen but i dont see the mouse cursor although the mouse events (move, click, drag...) are all broadcasted correctly.
if i use "this.mRFB.showDotCursor = true" i can see the dotcursor.
I would prefer to just show the client cursor. Can anybody point me in a direction how that would be possible. Thanks a lot.

I'm using v. 1.1.0 and tried connecting to a windows VM and a Mac computer with the same results

here is my code:

    this.mRFB = new RFB(target, url, {
                credentials: {
                    password
                }
            });
     this.mRFB.viewOnly = true;
     this.mRFB.resizeSession = true;
     this.mRFB.scaleViewport = true;
     this.mRFB.showDotCursor = true; // shows dotCursor, if its false i see no cursor

**Comment by CendioOssman** [comment]
I'm afraid it seems your server is not sending any cursor in that case. The dot cursor setting is specifically for such servers that do not have proper handling of cursors. I'm afraid you'll have to report the issue to them and hopefully they can resolve it.

What server is it you are using?
