### ISSUE TITLE
Problem connecting to VNC server

### ISSUE THREAD

**Issue by klanoberlin** [novnc/noVNC#1357]
I installed noVNC (V 1.1.0) for remote control of devices, coming with VNC server. I have no info about these servers except their names: they are either BR06 or BR16. Communication is via VPN - therefore no VNC encryption is used.
I use Chrome 79.0.3945.117 (newest available) on Windows 10. Websockify services are installed for a couple of the devices (using different ports per device for noVNC respectively).
Connections to BR16 servers work well, for BR06 I get always the error 1006 (debugging in Chrome) and the connection is closed immetiately after reaching the state connected (a test with version 0.6.2 of noVNC shows the opposite behavior: BR06 is connected, BR16 not). Visually, the servers deliver quite different view panels: The BR16 is large and true color, the BR06 has 320x240 pixels only and restricted colors.
Any idea how can I handle both servers from one version?
Thank you in advance!

For a BR06 device the websockify console comes with almost no info:
```
   69: 127.0.0.1: ignoring socket not ready
   70: 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
   70: 127.0.0.1: Version hybi-13, base64: 'False'
   70: connecting to: 10.0.1.150:5900
   70: handler exception: [Errno 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen (Translated: existing connection closed by remote host)
```

Except the last line the output is the same also for BR16 devices.

The debug-level console output of Chrome is:
```
    connecting to ws://localhost:40602/websockify           rfb.js:396
    Server choose sub-protocol: binary                              websock.js:191
    Server ProtocolVersion: 003.003                                   rfb.js:793 
    Server asked for a password                                         ui.js:1146
             credentials                               @ ui.js:1146
             (anonymous)                           @ eventtarget.js:32
             dispatchEvent                          @ eventtarget.js:32
            _negotiate_std_vnc_auth          @ rfb.js:953
            _negotiate_authentication        @ rfb.js:1083
            _init_msg                                   @ rfb.js:1272
            _handle_message                      @ rfb.js:713
            (anonymous)                             @ rfb.js:186
            _recv_message                          @ websock.js:278
    Screen: 320x240, bpp: 8, depth: 8, big_endian: 0, 
    true_color: 0, red_max: 7, green_max: 7, blue_max: 3,
    red_shift: 0, green_shift: 3, blue_shift: 6                       rfb.js:1174 
    Server native red-shift is not 16                                  rfb.js:1190 
            _negotiate_server_init               @ rfb.js:1190
            _init_msg                                   @ rfb.js:1286
            _handle_message                      @ rfb.js:713
            (anonymous)                             @ rfb.js:186
            _recv_message                          @ websock.js:278
    Server native blue-shift is not 0                                   rfb.js:1194 
            _negotiate_server_init               @ rfb.js:1194
            _init_msg                                   @ rfb.js:1286
            _handle_message                      @ rfb.js:713
            (anonymous)                             @ rfb.js:186
            _recv_message                          @ websock.js:278
```

**Comment by CendioOssman** [comment]
I'm afraid it is common for such devices to have broken VNC servers that only support some parts of the protocol. They then tend to kick out any client that uses anything more.

I don't suppose there is a log on these things where you can see what goes wrong?

If you have the time you could try using `git bisect` to figure out what change in noVNC broke things. But it is likely it won't by anything we can adjust.

**Comment by klanoberlin** [comment]
Thank you. You are right, I can't see what goes wrong. I can only debug at Chrome level where everything goes well. The error source is somewhere in the VNC server (or websockify?). Unfortunately, I am not familiar with them and have no tools to debug. Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [novnc/noVNC] Problem connecting to VNC server (#1357)Von: "Pierre Ossman (Work account)" An: novnc/noVNC Cc: klanoberlin ,Author I'm afraid it is common for such devices to have broken VNC servers that only support some parts of the protocol. They then tend to kick out any client that uses anything more.
I don't suppose there is a log on these things where you can see what goes wrong?
If you have the time you could try using git bisect to figure out what change in noVNC broke things. But it is likely it won't by anything we can adjust.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/novnc/noVNC/issues/1357?email_source=notifications\u0026email_token=AOKZTSFDGDSBOI4GCRZXG3DQ7FIUZA5CNFSM4KKCCRJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJWSJNY#issuecomment-577578167",
"url": "https://github.com/novnc/noVNC/issues/1357?email_source=notifications\u0026email_token=AOKZTSFDGDSBOI4GCRZXG3DQ7FIUZA5CNFSM4KKCCRJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJWSJNY#issuecomment-577578167",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by CendioOssman** [comment]
Unfortunately there isn't much more we can do in our end in that case. See if you can make the vendor aware of these issues. Perhaps they can improve things in the future.
