### ISSUE TITLE
Multiple pointers on the screen on iPad

### ISSUE THREAD

**Issue by juanjoDiaz** [novnc/noVNC#1358]
**Describe the bug**
Running noVNC on an iPad for a while I end up with a bunch of mouse pointers all over the screen:

```html
<canvas style="position: fixed; z-index: 65535; pointer-events: none; left: 740px; top: 280px;" width="16" height="16"></canvas>
<canvas style="position: fixed; z-index: 65535; pointer-events: none; left: 446px; top: 521px;" width="16" height="16"></canvas><canvas style="position: fixed; z-index: 65535; pointer-events: none; visibility: hidden;" width="0" height="0"></canvas>
<canvas style="position: fixed; z-index: 65535; pointer-events: none; visibility: hidden;" width="0" height="0"></canvas>
<canvas style="position: fixed; z-index: 65535; pointer-events: none; left: 765px; top: 461px;" width="10" height="16"></canvas>
<canvas style="position: fixed; z-index: 65535; pointer-events: none; visibility: hidden;" width="0" height="0"></canvas><canvas style="position: fixed; z-index: 65535; pointer-events: none; visibility: hidden;" width="0" height="0"></canvas>
```

It seems to have to do with fast touches or multitouches.

Should the mouse pointer show at all when using touch devices?
Can it be hidden?

**To Reproduce**
I haven't tested in the noVNC UI since I'm embedding the library in my own UI.

**Expected behavior**
Only one pointer is visible at a time.

**Screenshots**

**Client (please complete the following information):**
 - OS: iOS
 - Browser: safari
 - Browser version: latest

**Server (please complete the following information):**
 - noVNC version: 1.1.0
 - VNC server: TigerVNC
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
> Should the mouse pointer show at all when using touch devices?

Yes. We respect the wishes of the remote side if a cursor should be shown or not. (We can't really fully enforce anything anyway)

> Can it be hidden?

Nope.

Do you think you could set up a test with the standard `vnc.html`? So we can pinpoint if it's a general issue, or if it's just the specific way you are using the library. Given the elements it seems to be something with the local cursor emulation that gets confused.

**Comment by juanjoDiaz** [comment]
Ok. I think I just found the issue.
It's not really a bug but a design problem (or just me missing something).

The problem is that `Rfb` doesn't have a public `connect` method. Instead, it automatically connects when it's instantiated.
Each `Rfb` instance includes and instance of `Cursor` which creates a new canvas that is never cleaned is up.
In my application, this causes problems when the connection flickers and I reconnect by re-instantiating `Rfb`. The new `Rfb` instance creates a new `Cursor` instance which creates a new canvas. If the connection starts flickering a lot, I end up with a bunch of canvas (not sure of why some are hidden and some not).

A possible solution, and possibly better design, would be to add a public `connect` method, so the `Rfb` instance can be reused.

Basic example:
```js
const rfb = new Rfb(...);

this.rfb.addEventListener('disconnect', e => {
  setTimeout(() => rfb.connect(), 1000); // wait 1 second and reconnect
});
```

I guess that we could even pass the url and options to the `connect` method, so you could change the server without having to re-instantiate `Rfb`.

There is already a `disconnect` method in `Rfb`. But it seems to really leave the `Rfb` instance in a state where it can't reconnect.

Wdyt?
Would this something that you'd be happy to accept if I make a PR?

**Comment by CendioOssman** [comment]
Having the constructor connect is per design as we want each object to represent a single connection (much like a WebSocket object is just a single connection). It avoids a lot of potential issues that would arise if we allowed reuse of the object.
