### ISSUE TITLE
Detect parent element resize to redraw canvas (instead of window.onresize)

### ISSUE THREAD

**Issue by baleeds** [novnc/noVNC#1364]
**Is your feature request related to a problem? Please describe.**
Currently, the canvas element resizes perfectly to its parent container when it detects a `window.onresize`.  However, when the size of the container changes without a window change, like a user resizable `div`, the canvas fails to redraw.

[See this youtube video](https://youtu.be/k9yhnoncuJ8)

**Describe the solution you'd like**
Could we consider switching the implementation of using `window.onresize` to instead use a [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) polyfill?  This would work when the container size changes, whether it's from a window event or not.

**Describe alternatives you've considered**
Another option is to expose a function that will allow the consumer to indicate that the canvas should be redrawn.  Something like `rfb.redrawCanvas()`?

**Comment by CendioOssman** [comment]
The problem with that is that neither Edge nor IE supports that. So it would have to be changed to somehow support both.

Should be doable, but might require some extra work.

**Comment by baleeds** [comment]
[This polyfill](https://github.com/que-etc/resize-observer-polyfill) is supported back to IE8.  I've used it successfully in the past.

**Comment by CendioOssman** [comment]
Nice. Worth having a look at then I guess.

Out of curiosity, what is you are integrating noVNC in?

**Comment by baleeds** [comment]
My company is creating a remote monitoring and management platform.  https://level.tech/

I see you have a `FixMe` in there.  
![image](https://user-images.githubusercontent.com/9682964/74038003-6b70ea80-498d-11ea-807e-52641825e7d2.png)

If you'd like, I can open a PR for it.

**Comment by CendioOssman** [comment]
A PR would be very welcome. So go right ahead.

**Comment by baleeds** [comment]
https://github.com/novnc/noVNC/pull/1365
