### ISSUE TITLE
Clipboard does not hide when server terminates connection

### ISSUE THREAD

**Issue by CendioNiko** [novnc/noVNC#1367]
When having the clipboard visible, if the server for some reason terminates connection the clipboard does not get hidden as it should. The server termination can happen e.g. when we send clipboard data not supported by server or if you connect to the same port from another tab.  
Writing in this clipboard will crash with the error: "UI.rfb is undefined".

1. Initiate noVNC connection.
2. Open clipboard from the menu.
3. Shut down server.
4. See that the clipboard is still visible.

This clipboard should not be visible.
![Screenshot from 2020-02-17 13-57-58](https://user-images.githubusercontent.com/54897152/74655975-99281180-518d-11ea-8584-31dd057888e4.png)

Should be same problem in all browsers, but found this using:
 - Fedora 30
 - Firefox 72
 - noVNC version: Master
 - VNC server: TigerVNC
 - WebSocket proxy: websockify

**Comment by samhed** [comment]
Fixed in c12e5b2b544aff6f662c7f61f82ce40d132e14df
