### ISSUE TITLE
The clipboard fades out while scrolling it

### ISSUE THREAD

**Issue by CendioAlex** [novnc/noVNC#1369]
If you scroll within the clipboard by using the scroll wheel or the scrollbars the clipboard will fade out. This results is transparent text in the clipboard which is hard to read.

1. Make sure the clipboard contains enough text for scrollbars to appear
2. Scroll the clipboard with the scrollbars without releasing the mouse or using the mouse wheel
3. Observe that the clipboard fades out just like it does when it loses focus. 

This behavior seems unnatural since you still want to be able to read the text while you scroll without any difficulties.

**Comment by CendioOssman** [comment]
Maybe we should also stop fading if the toolbar has focus?

**Comment by samhed** [comment]
Fixed in 8df281cce6822b534ad43edc9efb18a5292e8e60
