### ISSUE TITLE
Question: proper implementation of autoscaling on vnc_lite?

### ISSUE THREAD

**Issue by Kreyren** [novnc/noVNC#1370]
#### Disclaimer: There are issues about this, but none of them seems to work and i am unable to find anything helpful in documentation.

**Question:** What is the proper way to implement auto-scaling on vnc_lite?

Expecting fullscreen apps to scale with the resolution on the local system connecting on the server i.e Local Scaling on `vnc.html` as mensioned in https://github.com/gitpod-io/gitpod/issues/1239#issuecomment-588456477 assuming usage in theia alike: 
![image](https://user-images.githubusercontent.com/11302521/74876439-f5dd2500-5363-11ea-9329-636d30c16a00.png)

Thanks for any relevant info

### References
- Gitpod Issue https://github.com/gitpod-io/gitpod/issues/1239
- Gitpod upstream tracking https://github.com/gitpod-io/gitpod/issues/303
- relevant issue https://github.com/novnc/noVNC/issues/763
  - neither of resize/autoscale suffixes are working as mensioned in https://github.com/gitpod-io/gitpod/issues/1239#issuecomment-588450969
(other references suspended for reasons above)

**Comment by JesterOrNot** [comment]
Also possibly a command-line option for this so it could be automated

**Comment by CendioOssman** [comment]
It has a query option called `scale` that can do this. Simply append `?scale=true` to the URL.

**Comment by CendioOssman** [comment]
Note that `vnc_lite.html` is a developer example, so it does not get much in the way of features or documentation. Please use the regular `vnc.html` for production.
