### ISSUE TITLE
Hide sidebar for vnc.html

### ISSUE THREAD

**Issue by JesterOrNot** [novnc/noVNC#1371]
**Is your feature request related to a problem? Please describe.**
See https://github.com/gitpod-io/workspace-images/pull/170
We find it distracting
**Describe the solution you'd like**
A way to remove the sidebar

**Comment by samhed** [comment]
When connected it should fold away automatically, in this state it only shows a small handle that shouldn't be obtrusive.

If you want to get rid of it completely you should set `display: none` on "noVNC_control_bar_anchor" in your CSS. That should do the trick.

**Comment by CendioOssman** [comment]
This is a commonly discussed when integrating noVNC in to other systems, so I think this is worth having open and investigating further.

@JesterOrNot, the toolbar is needed for many user interactions (e.g. touch, clipboard). Is this something you've considered? Perhaps there are other ways than just completely removing the toolbar.

**Comment by samhed** [comment]
In that case, @JesterOrNot what were you expecting? Documentation in the wiki?

**Comment by JesterOrNot** [comment]
The option to completely remove it possibly as something that could be dynamically toggled so that we could create a configuration for it on a per-user basis

**Comment by samhed** [comment]
When you say "dynamically toggled", how do you envision doing that? Could you elaborate a bit?

When thinking about integrating and modifying noVNC, changing the html and css seems like the most natural path to me. But that doesn't feel like "dynamically toggling on a per-user basis".

**Comment by JesterOrNot** [comment]
You're probably right currently our VNC looks like this
![image](https://user-images.githubusercontent.com/50386709/75049084-31284280-548f-11ea-8611-e0e96c7d10a6.png)

and a lot of the time this is just distracting as we currently have very little preview space as is (unless opened in the browser)
![image](https://user-images.githubusercontent.com/50386709/75049387-b6abf280-548f-11ea-82e2-9043e98225bc.png)

**Comment by JesterOrNot** [comment]
> This is a commonly discussed when integrating noVNC in to other systems, so I think this is worth having open and investigating further.
> 
> @JesterOrNot, the toolbar is needed for many user interactions (e.g. touch, clipboard). Is this something you've considered? Perhaps there are other ways than just completely removing the toolbar.

**Comment by CendioOssman** [comment]
How about when it is hidden? Is it still in the way with just the handle?

Have you thought about styling it in a different way? We might be able to make that easier if we know what you need/want.

**Comment by samhed** [comment]
No response.
