### ISSUE TITLE
No installation performed

### ISSUE THREAD

**Issue by nikosT** [novnc/noVNC#1377]
When running for the first time:
`sudo snap install novnc`

I get the following error, with no installation performed:
`- Mount snap "novnc" (app description field 'command' contains illegal "snap/command-chain/snapcraft-runner $SNAP/command-novnc.wrapper" (legal: '^[A-Za-z0-9/. _#:-]*$'))`

**Comment by samhed** [comment]
I don't have time to get acquainted with Snaps right now. @tkedwards any idea what the problem can be here?

**Comment by tkedwards** [comment]
@nikosT  What version of Ubuntu are you running? What version of snap?

```
lsb_release -a
snap --version
```

**Comment by samhed** [comment]
No response.
