### ISSUE TITLE
Default websockify port conflict

### ISSUE THREAD

**Issue by knnnrd** [novnc/noVNC#1378]
The default port when starting websockify is port 6080. When I use tightvncserver to start a VNC session with number 80, it reserves both port 5980 and 6080. As a result websockify cannot start with the default port.

I think it would be better to choose a default port for websockify which doesn't conflict with any of the possible vnc session numbers?

**Comment by CendioOssman** [comment]
For a simple installation where the defaults are relevant there shouldn't regularly be 80 displays used. So I don't think it is warranted to start changing it quite yet. :)
