### ISSUE TITLE
Code 400 and 404 when connecting to tightvnc server on rpi 4

### ISSUE THREAD

**Issue by LateralLines** [novnc/noVNC#1379]
I'm attempting to connect to my raspberry pi 4b via a tightvnc server and novnc + websockify. Whenever I attempt to connect on my pc, I get an error code 400 and 404:

192.168.0.233 - - [08/Mar/2020 21:38:24] code 400, message Client must support 'binary' or 'base64' protocol
192.168.0.233 - - [08/Mar/2020 21:38:24] code 404, message File not found

Full output:
pi@raspberrypi:~ $ vncserver :1

New 'X' desktop is raspberrypi:1
Starting application specified in /home/pi/.vnc/xstartup
Log file is /home/pi/.vnc/raspberrypi:1.log

pi@raspberrypi:~ $ noVNC./utils/launch.sh --vnc localhost:5901
Warning: could not find self.pem
Using installed websockify at /usr/bin/websockify
Starting webserver and Websockets proxy on port 6080
WebSocket server settings:
  - Listen on :6080
  - Flash security policy server
  - Web server. Web root: /home/pi/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5901

Navigate to this URL:

    http://raspberrypi:6080/vnc.html?host=raspberrypi&port=6080

Press Ctrl-C to exit

192.168.0.233 - - [08/Mar/2020 21:38:24] code 400, message Client must support 'binary' or 'base64' protocol
192.168.0.233 - - [08/Mar/2020 21:38:24] code 404, message File not found

Client:
 - OS: Windows
 - Browser: Chrome
 - Browser version: 80 (80.0.3987.132)

Server:
 - noVNC version: latest (installed via git yesterday)
 - Server: tightvnc
 - WebSocket proxy: websockify

If it makes any difference, I'm trying to run the tightvnc and novnc server while I'm connected my pi from vnc viewer on my pc so that I have access to the cli. I have also restarted my pi and accessed it through ssh while still getting the exact same errors. VNC is enabled in raspi-config and have the enabled desktop-auto login on boot. Otherwise, a clean flash of raspbian desktop (plus recommended software) version 02-13-2020 is installed with no other special configurations on my rpi.

**Comment by CendioOssman** [comment]
I'm afraid your websockify is too old. See e.g. #1276.
