### ISSUE TITLE
Release a new version to NPM

### ISSUE THREAD

**Issue by mofux** [novnc/noVNC#1381]
Hi there, first of all thanks for this amazing project and the well documented and easy to read source code. I'm interested in https://github.com/novnc/noVNC/pull/1373 but noticed that the npm package @novnc/novnc has seen its last npm release almost a year ago. Are there any plans for publishing a new version to npm soon?

**Comment by CendioOssman** [comment]
My best guess would be in a month or two. We have some development going on right now that we are trying to focus on. Once that is done we should have time to look at a release.
