### ISSUE TITLE
Add ability to set compression setting

### ISSUE THREAD

**Issue by ericfranz** [novnc/noVNC#1382]
**Is your feature request related to a problem? Please describe.**

Quality and compression are two values that can affect latency. In the past these have been hardcoded values. Giving users the ability to control these when they start NoVNC gives them the power to work around latency issues, so we modified our local copy of NoVNC to support this and would like to add this upstream.

**Describe the solution you'd like**

https://github.com/novnc/noVNC/pull/1373 added the ability to control quality. I'd like to add the same for compression. Happy to do the work if it will be approved.

**Comment by samhed** [comment]
This is fixed now.
