### ISSUE TITLE
NumLock is inverted 

### ISSUE THREAD

**Issue by tk421** [novnc/noVNC#1383]
**Describe the bug**
When using the NumLock in the keyboard it is inverted in NoVNC. If the NumLock's keyboard is ON the numbers in the keypad don't work, if in the NumLock's keyboard is off the numbers of the keyboard works. 

**To Reproduce**
1. Access to a remote desktop with NoVNC web application. 
2. Enable NumLock in your keyboard
3. Type numbers using the keyboard's number pad 

**Expected behavior**
I would expect to see the numbers that I am typing using the number pad.

**Client (please complete the following information):**
 - OS: Linux and Windows
 - Browser: Chrome and Firefox
 - Browser version: 74

**Server (please complete the following information):**
 - noVNC version: 1.1.0
 - VNC server: x11vnc 0.9.13-1.2build1
 - WebSocket proxy: websockify-0.9.0

**Additional context**
Help would be appreciated to debug and fix this issue. I am using a customized application based on [vnc.html](https://github.com/novnc/noVNC/blob/master/vnc.html).

While Numlock is problematic, Capslock works as expected.

**Comment by CendioOssman** [comment]
Likely a server bug unfortunately as we don't really care about NumLock in noVNC. We just send what the browser gives us.

Do you think you could test a different server?

You could also enable debug logging. noVNC should then log the keysyms sent and we can verify if they are correct.

**Comment by samhed** [comment]
No response.

**Comment by tk421** [comment]
@samhed sorry for the delay replying to this forum. And thanks for your quick response.

We do experience the same issue if we connect directly to the VNC server. This problem has nothing to do with noVNC.
