### ISSUE TITLE
预览环境挂了

### ISSUE THREAD

**Issue by vueCcc** [novnc/noVNC#1386]
![image](https://user-images.githubusercontent.com/31615589/77407213-c2713880-6df0-11ea-9682-7cd1b9cd5346.png)
http://210.32.1.254:6080/vnc.html?host=210.32.1.254&port=6080

**Comment by CendioOssman** [comment]
Sorry, but I'm afraid we can only provide help in English. Do you think you could fill out the bug report form?

**Comment by vueCcc** [comment]
> 抱歉，但是我们只能以英语提供帮助。您认为您可以填写错误报告表格吗？

this address "http://210.32.1.254:6080/vnc.html?host=210.32.1.254&port=6080" can,t login?
the environment is as same as the picture

**Comment by CendioOssman** [comment]
I'm afraid we cannot proceed without the bug form filled out so that we have the details of your setup.
