### ISSUE TITLE
Running on Apache server other than port 80

### ISSUE THREAD

**Issue by SourceCodeZone** [novnc/noVNC#1387]
I am trying to run noVNC on Apache server on Ubuntu. Everything works fine if I used the default port 80 for my webserver, like http://localhost/noVNC/vnc.html

But if I changed the port to 8085 and and used the url like http://localhost:8085/noVNC/vnc.html

I am getting error like, 

```
websock.js:185 WebSocket connection to 'ws://192.168.15.63:8085/websockify' failed: Error during WebSocket handshake: Unexpected response code: 404
open @ websock.js:185
_connect @ rfb.js:465
_updateConnectionState @ rfb.js:702

rfb.js:255 WebSocket on-error event
(anonymous) @ rfb.js:255
_websocket.onerror @ websock.js:205
error (async)
open @ websock.js:203
_connect @ rfb.js:465
_updateConnectionState @ rfb.js:702

setTimeout (async)
RFB @ rfb.js:259
connect @ ui.js:1023
rfb.js:740 Failed when connecting: Connection closed (code: 1006)

```

That is the url `ws://192.168.15.63:8085/websockify` and previously it was like `ws://192.168.15.63:5900/websockify`

**Comment by SourceCodeZone** [comment]
I replace the code on ui.js 
 `let port = window.location.port;`   to `let port = 5900;`  5900 is the server listening port.
And the problem resolved.

**Comment by CendioOssman** [comment]
The problem is that you generally need a WebSocket proxy, which is not included in Apache. It seems your VNC server understands WebSocket so you can connect directly to it, but most do not. By default noVNC assumes the web server used is also the WebSocket proxy, that's why it uses the same host and port.
