### ISSUE TITLE
Novnc with nginx proxy freeze/hang/disconnect every few minutes

### ISSUE THREAD

**Issue by johnwmail** [novnc/noVNC#1388]
When I access novnc/websockify with nginx proxy, it freeze/hang/disconnect every few minutes.
If I access novnc/websockify directly(http://10.20.10.102:6901), I can use it over hour without any problem.
please advise.

upstream novnc_proxy {
        server 10.20.10.102:6901;
}

server {
        listen          443 ssl;
        server_name     mydomain.com;

        ssl_certificate         /etc/nginx/acme/mydomain.com/fullchain.pem;
        ssl_certificate_key     /etc/nginx/acme/mydomain.com/private/privkey.pem;

        access_log off;
        log_not_found off;
        #error_log /dev/null crit;

        location /websockify {
                include proxy_params;
                proxy_pass http://novnc_proxy/;

                proxy_http_version 1.1;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                # VNC connection timeout
                #proxy_connect_timeout 61s;
                proxy_read_timeout 61s;
                #proxy_send_timeout 61s;

                # Disable cache
                proxy_buffering off;
        }

        location / {
                include proxy_params;
                proxy_pass http://novnc_proxy/;
        }
}

**Comment by CendioOssman** [comment]
I'm afraid this is more of a question for nginx than us. I can see you have some timeout settings in that conf though. Are they perhaps the reason things get disconnected?

I would suggest checking with nginx, or using our mailing list if you want to ask how other peoples noVNC setups look like.

**Comment by johnwmail** [comment]
> I'm afraid this is more of a question for nginx than us. I can see you have some timeout settings in that conf though. Are they perhaps the reason things get disconnected?
> 
> I would suggest checking with nginx, or using our mailing list if you want to ask how other peoples noVNC setups look like.

Sorry, would you please point me out, the mailing list address/url? 
https://www.google.com/search?q=novnc+mailing+list
seems to no office mailing list for novnc ??
Thanks.

**Comment by samhed** [comment]
https://groups.google.com/forum/#!forum/novnc
