### ISSUE TITLE
Selection of 8 bit depth or disable true color

### ISSUE THREAD

**Issue by AchuthSankar** [novnc/noVNC#1389]
**Is your feature request related to a problem? Please describe.**
Yes, NOVNC turns out to be very slow when the bandwidth is < 56 kbps. So either turning it to 8 bit or disabling true color would be good option.

**Describe the solution you'd like**
Like the vnc viewers it would be better to have 8 bit depth selection checkbox.

**Describe alternatives you've considered**
I tried to disable true color, but not seeing any ways to disable true color as it is hardcoded as true in the sendPixelFormat function, changing it to false is disconnection the vnc client with an unknown exception.

**Comment by AchuthSankar** [comment]
One more thing is except for 24 depth, all other depth has only raw encoding. This also will make 8 bit depth slower.

**Comment by CendioOssman** [comment]
I'm afraid this is not something we have any intention of supporting in noVNC. It adds way too much complexity for us to maintain.

**Comment by AchuthSankar** [comment]
Thanks for updating me, so could you tell me what is the minimum bandwidth required for the noVNC along with websockify to work ?

**Comment by CendioOssman** [comment]
There is no fixed lower requirement. It very much depends on what you are trying to show. But in most cases I'd say you want a couple of Mbps at least.
