### ISSUE TITLE
Duplicated mouse cursor on the screen

### ISSUE THREAD

**Issue by juanjoDiaz** [novnc/noVNC#1391]
**Describe the bug**
I get 2 mouse cursors, the remote and the local one.
The local one is quite bigger (I guess that's #1128) and the remote one can be seen lagging behind.

I don't recall having this problem previously. Not sure of what has changed.

**Expected behavior**
Only one pointer is shown. Either the remote or the local one.

**Client (please complete the following information):**
 - OS: Mac
 - Browser: chrome, safari, firefox
 - Browser version: latest

**Server (please complete the following information):**
 - noVNC version: 1.0.0 and 1.1.0
 - VNC server: QEMU (I think, I don't controll it)
 - WebSocket proxy: custom-made

**Comment by samhed** [comment]
Does it only happen on macOS? Could you make a screenshot?

**Comment by CendioOssman** [comment]
And does it happen with `master`? We did some fixes on this theme. Not sure if it was after 1.1.0 though.

**Comment by juanjoDiaz** [comment]
I did a fix for the local canvas-based mouse being duplicated. Not sure if you are referring to that. But this is different. There aren't multiple local cursors but a local and a remote one.

If you are referring to some other fix, I need to test with master.

Btw, 1.1.0 was released 1 year ago and 1.0.0 more than 2 years ago. Is there any reason to have such long release cycles? It prevents users that use this through NPM to get the latest fixes timely.

**Comment by samhed** [comment]
A couple of fixes was done on #1309 (it wasn't only about disappearing cursors). If anything the cursor code behaves differently on master.

The only reason for long release cycles is lack of time really. But I agree, it would be nice to have new releases more often.

**Comment by webpolis** [comment]
Yes, same here. Duplicate cursors: local (browser's) and remote (vnc host)

**Comment by samhed** [comment]
And neither of you tested with master?

**Comment by webpolis** [comment]
@samhed ... master is the default repo when installing this package via npm

**Comment by webpolis** [comment]
@samhed I use it via npm

**Comment by CendioOssman** [comment]
That is the stable release then. Please try downloading the current code directly here from github and see if that has the same issue.

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by juanjoDiaz** [comment]
Hi @CendioOssman ,

I haven't had time to test master since I'm working on some other stuff nowadays.

In any case, I wouldn't consist the issue resolved even if the fix is in unless there is a release to npm. Is there any plan for the next release? Or is there any reason to don't do small incremental releases instead of bigbang releases ever 1.5 years?

Thanks for the good work on noVNC! I don't want to just complain about the release cycle but actually improve the library.

**Comment by CendioOssman** [comment]
I'm afraid we can't keep issues open until there is a release as that just confuses things when trying to develop.

As for a new release, I'm trying to put that together now. Doing it more often would be nice, but we here at Cendio are generally busy with our own stuff. So it would be by someone else helping out and putting those releases together.

**Comment by juanjoDiaz** [comment]
Can you elaborate a bit on what's taking so much time about releasing?
Putting the changelog together?
The actual publishing step?

How could someone help to get to a better release cadence?
Setting up a GitHub action to automatically publish when a Git tag matching vX.Y.Z is pushed?
Scheduling releases?
Something else?

**Comment by CendioOssman** [comment]
> Can you elaborate a bit on what's taking so much time about releasing?
> Putting the changelog together?
> The actual publishing step?
> 

It's mostly just the fact that we are usually so focused on ThinLinc work here at Cendio that it is difficult to even start thinking about making a noVNC release.

> How could someone help to get to a better release cadence?
> Setting up a GitHub action to automatically publish when a Git tag matching vX.Y.Z is pushed?
> Scheduling releases?
> Something else?

We already have actions for publishing. Everything else is detailed here:

https://github.com/novnc/noVNC/wiki/Development:-Making-a-release

Most of the work is going through commits to write the release notes. And fixing any release blocking bugs (although we try to make sure few such ever hit `master`).

So any help with what's on that page would make things easier.
