### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by amdjml** [novnc/noVNC#1392]
Hi All,

I've been googling for a while and I am not finding a solution for this. Could someone help out here?

I have an **Ubuntu 18.04 LTS Desktop** installed in my vSphere environment. Everything is default, I have not installed anything extra. It has an IP of 192.168.1.10. I have used the instructions on README file to install novnc via snap. I am using root user.

`# sudo snap install novnc`

Then, I run this command: 

`# novnc --listen 6081 --vnc localhost:5901`

I get the following message in terminal:

```
Warning: could not find self.pem
Using local websockify at /snap/novnc/3/utils/websockify/run
Starting webserver and WebSockets proxy on port 6081
websockify/websocket.py:30: UserWarning: no 'numpy' module, HyBi protocol will be slower
  warnings.warn("no 'numpy' module, HyBi protocol will be slower")
WebSocket server settings:
  - Listen on :6081
  - Web server. Web root: /snap/novnc/3
  - No SSL/TLS support (no cert file)
  - proxying from :6081 to localhost:5901

Navigate to this URL:

    http://ubuntu:6081/vnc.html?host=ubuntu&port=6081

Press Ctrl-C to exit
```
I also installed both of the following packages after seeing this message above: 

"... UserWarning: no 'numpy' module ..."

```
# apt install python-numpy
# apt install python3-numpy
```

I open Chrome on my Mac and go to: http://192.168.1.10:6081/vnc.html?host=ubuntu&port=6081

I click on Connect and I get "Failed to connect to server"

I see these messages on the terminal:

```
192.168.1.2 - - [09/Apr/2020 15:54:00] 192.168.1.2: Plain non-SSL (ws://) WebSocket connection
192.168.1.2 - - [09/Apr/2020 15:54:00] 192.168.1.2: Path: '/websockify'
192.168.1.2 - - [09/Apr/2020 15:54:00] connecting to: localhost:5901
192.168.1.2 - - [09/Apr/2020 15:54:00] Failed to connect to localhost:5901
```
Any help is appreciated.

**Comment by samhed** [comment]
Do you have a VNC server running on port 5901 of the ubuntu machine?

**Comment by cenosito** [comment]
Yes I had same error an the solution was check listening ports and run againt. Work for my in tightvncserver and chrome browser.

Now, I try with realVNC server and have an connection error when access with chrome say:
**Failed to connect to server**

```

tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      2607/vncserver-x11- 
tcp        0      0 0.0.0.0:5901            0.0.0.0:*               LISTEN      2338/Xvnc-core      
tcp        0      0 0.0.0.0:5902            0.0.0.0:*               LISTEN      2717/Xvnc-core      
tcp        0      0 0.0.0.0:6001            0.0.0.0:*               LISTEN      2338/Xvnc-core      
tcp        0      0 0.0.0.0:6002            0.0.0.0:*               LISTEN      2717/Xvnc-core          
tcp6       0      0 :::5900                 :::*                    LISTEN      2607/vncserver-x11- 
tcp6       0      0 :::5901                 :::*                    LISTEN      2338/Xvnc-core      
tcp6       0      0 :::5902                 :::*                    LISTEN      2717/Xvnc-core      
tcp6       0      0 :::6001                 :::*                    LISTEN      2338/Xvnc-core      
tcp6       0      0 :::6002                 :::*                    LISTEN      2717/Xvnc-core      

sudo ./utils/launch.sh --vnc localhost:5901

Warning: could not find self.pem
Using local websockify at /home/pi/VNC/noVNC/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /home/pi/VNC/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5901


Navigate to this URL:

    http://raspberrypi:6080/vnc.html?host=raspberrypi&port=6080

Press Ctrl-C to exit


192.168.0.200 - - [12/Apr/2020 23:28:36] 192.168.0.200: Plain non-SSL (ws://) WebSocket connection
192.168.0.200 - - [12/Apr/2020 23:28:36] 192.168.0.200: Path: '/websockify'
192.168.0.200 - - [12/Apr/2020 23:28:36] connecting to: localhost:5901

```

**Comment by CendioOssman** [comment]
@cenosito, please don't hijack issues unless you are sure you are seeing the same issue. Please use the mailing list for initial setup questions as they are rarely bugs in noVNC.

@amdjml, as @samhed said, please check if you have a VNC server up and running. noVNC is merely a VNC client, so you still need a server for it.

**Comment by amdjml** [comment]
> Do you have a VNC server running on port 5901 of the ubuntu machine?

I do not see anything running on port 5901

```
sudo netstat -ltnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:6081            0.0.0.0:*               LISTEN      8026/python
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      542/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      754/sshd
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      7018/cupsd
tcp6       0      0 :::22                   :::*                    LISTEN      754/sshd
tcp6       0      0 ::1:631                 :::*                    LISTEN      7018/cupsd
```

> @cenosito, please don't hijack issues unless you are sure you are seeing the same issue. Please use the mailing list for initial setup questions as they are rarely bugs in noVNC.
> 
> @amdjml, as @samhed said, please check if you have a VNC server up and running. noVNC is merely a VNC client, so you still need a server for it.

So, what do I use if I don't have a server installed? And I am guessing the 2 items below are not related to what we are discussing here.

```
dpkg -l | grep vnc
ii  libvncclient1:amd64                        0.9.11+dfsg-1ubuntu1.1                           amd64        API to write one's own VNC server - client library
ii  remmina-plugin-vnc:amd64                   1.2.0-rcgit.29+dfsg-1ubuntu1                     amd64        VNC plugin for Remmina
```

**Comment by samhed** [comment]
libvncclient and remmina are also clients. You will need to install a VNC server, have a look at TigerVNC for example, I think it's available in Ubuntu's repos:

 `sudo apt install tigervnc-standalone-server`

Then start it:

 `vncserver`

**Comment by amdjml** [comment]
> libvncclient and remmina are also clients. You will need to install a VNC server, have a look at TigerVNC for example, I think it's available in Ubuntu's repos:
> 
> `sudo apt install tigervnc-standalone-server`
> 
> Then start it:
> 
> `vncserver`

I installed tigervnc-standalone-server and it is running, then i ran noVNC and it is running but I am still receiving an error below:

```
sudo netstat -ltnp
[sudo] password for sigitlocal:
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5901          0.0.0.0:*               LISTEN      1478/Xtigervnc
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      565/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      770/sshd
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      636/cupsd
tcp        0      0 0.0.0.0:6081            0.0.0.0:*               LISTEN      1887/python
tcp6       0      0 ::1:5901                :::*                    LISTEN      1478/Xtigervnc
tcp6       0      0 :::22                   :::*                    LISTEN      770/sshd
tcp6       0      0 ::1:631                 :::*                    LISTEN      636/cupsd
```

![Screen Shot 2020-04-14 at 10 46 29 AM](https://user-images.githubusercontent.com/875782/79238414-57d67a00-7e3d-11ea-8386-7dc8074508cd.png)

**Comment by amdjml** [comment]
Never mind, after I rebooted the VM, all is working fine. Thank you for your help!

**Comment by giuliohome** [comment]
> libvncclient and remmina are also clients. You will need to install a VNC server, have a look at TigerVNC for example, I think it's available in Ubuntu's repos:
> 
> `sudo apt install tigervnc-standalone-server`
> 
> Then start it:
> 
> `vncserver`

Thank you! It resolved my issue
