### ISSUE TITLE
Qemu websocket URI changed

### ISSUE THREAD

**Issue by Akilesh1597** [novnc/noVNC#1393]
**Describe the bug**
The websocket URI to connect to qemu has changed
from : 'ws://host:vnc websocket port/websockify'
to : 'ws://host:vnc websocket port/'

**To Reproduce**
1. launch a Qemu VM with websocket option for VNC like below
`-vnc :1,websocket=15901`
2. In a browser navigate to the VNC url for the host. 
3. Open the web developer options. Under the 'Network' tab, you will see 404 for the request made to 'ws://<host>:<web socket port>/websockify'
4. The VNC will not be loaded

**Expected behavior**
The VNC page should have been loaded without errors and should have been usable. 

**Screenshots**
```
Firefox can’t establish a connection to the server at ws://localhost:15901/websockify. websock.js:217:26
WebSocket on-error event rfb.js:226:13
WebSocket on-close event rfb.js:193:13
Failed when connecting: Failed to connect to server ( (code: 1006)) rfb.js:573:2
```

```
Request URL:ws://localhost:15901/websockify
Request Method:GET
Remote Address:127.0.0.1:15901
Status Code:
404
Version:HTTP/1.1
```

**Client (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Browser version: 75.0

**Server (please complete the following information):**
 - noVNC version: 1.1.0  (Commit : a1015d8db569fcdd681039c4c0872879c8af0292 )
 - VNC server: Qemu 1:2.11
 - WebSocket proxy: Qemu 1:2.11
-  OS : Ubuntu 18.04

**Comment by Akilesh1597** [comment]
https://github.com/novnc/noVNC/pull/1394

**Comment by CendioOssman** [comment]
I'm afraid noVNC is not specific to QEMU, so we do not follow their default WebSocket path. You will need to configure noVNC with the path that QEMU requires.

**Comment by Akilesh1597** [comment]
> I'm afraid noVNC is not specific to QEMU, so we do not follow their default WebSocket path. You will need to configure noVNC with the path that QEMU requires.

is the websocket uri path configurable in noVNC ?

**Comment by CendioOssman** [comment]
Yes. You can change it from the settings or by specifying `path` as a query variable on the URL.
