### ISSUE TITLE
rgb333 support

### ISSUE THREAD

**Issue by QQ2017** [novnc/noVNC#1400]
This is a rare and awesome project. I have been using it for a long time. I hope to increase the color level setting, especially support rgb333. It reduces the transmission screen as much as possible while maintaining the screen color and screen image integrity The bandwidth required for data is very useful in areas where bandwidth is tight.
Thank you developers for your contributions, you are really great.

**Comment by CendioOssman** [comment]
Sorry, I'm afraid we've decided that this use case is not common enough for the complexity it brings. Please try using the new compression and quality settings instead to reduce bandwidth usage.
