### ISSUE TITLE
Recaptcha to prevent "too many authentification failures" error?

### ISSUE THREAD

**Issue by arthursw** [novnc/noVNC#1401]
I use noVNC with TurboVNC and I am often burtforced by bots ; so I get a ""too many authentification failures" error which prevent me to connect to my machine.

One solution would be to integrate a [recaptcha](https://www.google.com/recaptcha/intro/v3.html) on the noVNC connection page.

I'll try to implement this, but I'm not sure it's doable, safe and sufficient yet.

**Comment by CendioOssman** [comment]
Sounds sensible, but it also requires server support so I'm afraid it falls outside our project. We are only a client project. This would need to be a local modification on your site.
