### ISSUE TITLE
vmware esxi connection problem

### ISSUE THREAD

**Issue by altinsoft** [novnc/noVNC#1404]
Hi,

I want to connection virtual machine console (on vmware esxi)

Connection Url ;
http://xxx.xxx.xxx.xxx:6080/vnc.html?host=esxi_host_address&port=5900&password=password

Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE

How can I connect to virtual servers on VMware esxi.

Thank you for help.

**Comment by CendioOssman** [comment]
I don't think ESXi supports WebSocket connections (which noVNC requires), so you need to have a proxy between noVNC and ESXi. E.g. websockify (although it isn't really built for large scale production use).

Please have a look at adding that to your setup and it should work fine.
