### ISSUE TITLE
Clipboard not reliable when connecting to Windows 10

### ISSUE THREAD

**Issue by abulhol** [novnc/noVNC#1405]
The clipboard sometimes does not work with Windows 10 machines I am connecting to.
I.e. the clipboard is not updated. E.g. I copy text from my machine to the Clipboard, but it does not get forwarded to the VNC machine. 

This happens seemingly randomly. However, it can be triggered almost reliably when using the "Clear" below the Clipboard text field. 
If I then continue pasting back and forth a bit, it starts working again. 
With Windows 7, I haven't seen this issue. 

Using noVNC version 1.1.0 in Chrome, with TightVNC server. 
Windows 10 x64 version 1903.

**Comment by CendioOssman** [comment]
Unfortunately it is likely a server issue in that case. Do you think you could test some other server than TightVNC on that same machine?

**Comment by abulhol** [comment]
No, unfortunately not.

**Comment by samhed** [comment]
See if you can get some logs from TightVNC, perhaps you can find out if the clipboard messages are received when expected or not. Perhaps the logs even tell you the reason you aren't getting the desired behavior.

**Comment by CendioOssman** [comment]
We also have some logging in noVNC. Could you enable debug logging in the noVNC settings and see what it says in the browser console when you update the clipboard?

**Comment by abulhol** [comment]
@samhed @CendioOssman thanks for the debugging tips! I will try these out and post udpates here.

**Comment by abulhol** [comment]
Using the `logging=debug` parameter, I get an output like shown below.
This was when I first copied some text from my host to the clipboard field, then copied it to Notepad in the VNC machine. Then I wrote something else in Notepad and tried to copy it back to the clipboard box (which pretty consistenly does not work). 

```
Sending keysym (down): 65507
rfb.js:378 Sending keysym (down): 97
rfb.js:378 Sending keysym (up): 65507
rfb.js:378 Sending keysym (up): 97
rfb.js:378 Sending keysym (down): 65507
rfb.js:378 Sending keysym (down): 118
rfb.js:378 Sending keysym (up): 65507
rfb.js:378 Sending keysym (up): 118
rfb.js:378 Sending keysym (down): 65507
rfb.js:378 Sending keysym (down): 97
rfb.js:378 Sending keysym (up): 65507
rfb.js:378 Sending keysym (up): 97
rfb.js:378 Sending keysym (down): 104
rfb.js:378 Sending keysym (down): 97
rfb.js:378 Sending keysym (up): 104
rfb.js:378 Sending keysym (up): 97
rfb.js:378 Sending keysym (down): 104
rfb.js:378 Sending keysym (up): 104
rfb.js:378 Sending keysym (down): 97
rfb.js:378 Sending keysym (up): 97
rfb.js:378 Sending keysym (down): 65507
rfb.js:378 Sending keysym (down): 97
rfb.js:378 Sending keysym (up): 65507
rfb.js:378 Sending keysym (up): 97
rfb.js:378 Sending keysym (down): 65507
9rfb.js:378 Sending keysym (down): 65507
rfb.js:378 Sending keysym (down): 99
rfb.js:378 Sending keysym (up): 65507
rfb.js:378 Sending keysym (up): 99
```
I am not sure what to make of this output, can you guide me?

**Comment by CendioOssman** [comment]
I'm afraid that means you have not gotten debug logging fully working. Likely your browser is filtering things. Chrome has a button labeled "Default levels" that probably needs to be tweaked.

You should be getting lines like:
```
>> UI.clipboardSend: dsfsfsd...
```

**Comment by samhed** [comment]
No response
