### ISSUE TITLE
Cannot use TurkishQ keyboard effectivly

### ISSUE THREAD

**Issue by emirefek** [novnc/noVNC#1407]
**Describe the bug**
Turkish keyboard not works well. I can't even push some latin chracters.

**To Reproduce**
For example we have "I, İ" word which I can use capital I but not normal i. Just ı(down letter) or I(capital). Turkish letters are not working anyway(Ü, Ğ, Ö, Ç, Ş). And keyboard mappings are wrong too. I cannot use the top stuff at keyboard like (!'ˆ+%&/()=?_;,-*>£<#$½{[]}\\ˋ,)

**Expected behavior**
If you manage to add them I'll be glad. If you can share your address to me I can donate Turkish keyboard to you :)

**Screenshots**
No needed I think.

**Client (please complete the following information):**
 - OS: [Linux,Windows,Android]
 - Browser: [Chrome,Chromium]
 - Browser version: [latest stable at 22.05.20]

**Server (please complete the following information):**
 - noVNC version: [Included at FreeNAS. Don't know version sorry]
 - VNC server: [Included at FreeNAS latest stable]
 - WebSocket proxy: [Included at FreeNAS latest stable]

**Comment by CendioOssman** [comment]
I'm afraid this works absolutely fine here with TigerVNC's Xvnc and the latest noVNC. I tried in both Firefox and Chrome. So it would seem there is something wrong with the packages included in FreeNAS.

Unfortunately we can't do much about their packages, so I'll have to direct you to file a bug with them about fixing this.
