### ISSUE TITLE
no Num Lock sync (Windows guest)

### ISSUE THREAD

**Issue by republicus** [novnc/noVNC#1408]
Num Lock appears to be in exact opposite sync with my desktop when the guest is a Windows client.

It seems to be effecting Windows systems (maybe Win 10 only?) 
I opened two noVNC consoles, where one was a Windows 10 VM and the other Linux Mint.

I verified by switching between the two noVNC console windows repeatedly testing the Num Lock.
The Linux VM syncs properly every time. Win 10 Num Lock was **always opposite**.

**Windows 10:**
1) Turned client desktop Num Lock OFF
2) Started VM
3) Opened VM console in noVNC.
4) Tested Num pad: Num Lock was ON in VM
5) Closed noVNC console window
6) Turned client desktop Num Lock ON
7) Opened VM console in noVNC
8) Tested Num pad: Num Lock was OFF in VM

I also verified the same from a Linux Mint client using Firefox with the same results.

**Client (please complete the following information):**
 - OS: Windows 10
 - Browser: Latest chromium based browsers (Brave, Chrome, Edge, etc)

 - OS: Linux Mint
 - Browser: Firefox 76.0

**Server (please complete the following information):**
 - noVNC version: novnc-pve: 1.1.0-1
 - VNC server: QEMU (Proxmox 6.2)
 - WebSocket proxy: Websockify

**Comment by CendioOssman** [comment]
Unfortunately this is likely a server issue as we don't do anything special with NumLock (the browser doesn't tell us if it's on or not). But let's verify that.

Could you enable debug logging in noVNC's settings and see what it prints in the browser console when you press numpad keys with NumLock on or off?

**Comment by republicus** [comment]
The output is identical on both Linux and Windows guests whether the host PC Num Lock is active or not.

Num Lock both ON and OFF on both guests' console displays when pressing Numpad keys 1,2,3:
```
onkeyevent down, keysym: 65436 , code: Numpad1
Sending key (down): keysym 65436, scancode 79
onkeyevent up, keysym: 65436 , code: Numpad1
Sending key (up): keysym 65436, scancode 79
onkeyevent down, keysym: 65433 , code: Numpad2
Sending key (down): keysym 65433, scancode 80
onkeyevent up, keysym: 65433 , code: Numpad2
Sending key (up): keysym 65433, scancode 80
onkeyevent down, keysym: 65435 , code: Numpad3
Sending key (down): keysym 65435, scancode 81
onkeyevent up, keysym: 65435 , code: Numpad3
Sending key (up): keysym 65435, scancode 81
```

When the noVNC guest has focus, the output is the same on both guests Lum Lock ON or OFF:

```
onkeyevent down, keysym: 65407 , code: NumLock
Sending key (down): keysym 65407, scancode 69
onkeyevent up, keysym: 65407 , code: NumLock
Sending key (up): keysym 65407, scancode 69
```

If noVNC window _does not_ have focus, and pressing Num Lock ON or OFF on host, no messages appear in the browser Console as they are pressed for both guests. Neither is there any additional text printed to the Console once focus returns to the noVNC guests..... Yet, somehow the guests both still know to switch Num Lock ON or OFF within each guest. 

How does it know to do that if there is no sync?

I'm not sure how relevant this is, but I did come across this information when trying to find a solution:

https://www.cendio.com/bugzilla/show_bug.cgi?id=400

> Problem found!
> 
> The issue has to do with the fact that we are really doing two syncs on connect:
> 
> 1. When the server first announces it supports LED states
> 
> 2. When we get the first focus when the window is created
> 
> If these two happen quickly enough then there will not be time for the server to push an update of its state between the two syncs. And since we sync by toggling, not by setting, we end up toggling twice because we haven't realised the server has already been updated (the client just isn't informed yet).
> 
> 
> There are two ways of solving this, with their own drawbacks:
> 
> a) Avoid the first sync. It is only really needed if the server announces support when we already have focus, so we could limit it to that case. That would solve this case, but it would not solve a similar case where focus is quickly toggled back and forth without the server having time to respond. That will probably not happen because of user interaction, but it might be a side effect of e.g. a window quickly popping up and going away.
> 
> b) Keep track of when we are already trying to sync. The problem is we don't really know if the sync is done as the server might ignore some states (e.g. ScrollLock in most cases). So we might block future, legitimate syncs of other keys. Fences could be an option, but that is complex and not supported by all servers.
> 
> 
> I think a) might be good enough, even if it leaves a theoretical corner case.

**Comment by CendioOssman** [comment]
I'm afraid that Cendio issue has no bearing on noVNC as it concerns TigerVNC.

What does the console output look like when you toggle NumLock on the **host** and press some numpad keys?

**Comment by samhed** [comment]
No response.
