### ISSUE TITLE
Close tab confirmation dialog

### ISSUE THREAD

**Issue by rajeevn1** [novnc/noVNC#1410]
Pressing Control-w key combination closes the tab without any confirmation dialog. This is an issue when the user is used to the key combination and  the browser does not allow managing the shortcuts (like ChromeOS).

Will it be possible to display a confirmation dialog before closing the tab.  That should resolve the issue. Thanks.

**Comment by samhed** [comment]
Hm, I agree that this could be useful for some users. However, users who use noVNC for brief amounts of time would probably be annoyed.

Perhaps we could show such a confirmation dialog if a connection has been active for more than a minute or something..? 

Thoughts @CendioOssman

**Comment by rajeevn1** [comment]
Maybe a toggle under advanced settings to enable the confirmation dialog will enhance the user experience for some users, without degrading it for others.

**Comment by CendioOssman** [comment]
We had one of those, but support in browsers was generally spotty (they don't want to block user actions like this) so we removed it.

**Comment by rajeevn1** [comment]
I understand the need for consistency.

**Comment by samhed** [comment]
Ah I had forgotten about that
