### ISSUE TITLE
connect noVNC,error message SyntaxError: Identifier 'originalPrompt' has already been declared

### ISSUE THREAD

**Issue by highboy168** [novnc/noVNC#1412]
Centos

connect noVNC still show error message,
but function is work,please help me how to fix it,ths.

Uncaught SyntaxError: Identifier 'originalPrompt' has already been declared
chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/prompt.js:1:1
SyntaxError: Identifier 'originalPrompt' has already been declared

**Comment by CendioOssman** [comment]
I'm afraid that is not part of noVNC, so there isn't much we can do. It looks like it comes from some extension. Try to find out which and report this issue to the developers of that extension.
