### ISSUE TITLE
How can I send XK_ISO_Left_Tab to the server

### ISSUE THREAD

**Issue by juanjoDiaz** [novnc/noVNC#1413]
Hi all,

I am using noVNC to access a server running some applications.

To manage the applications in a certain way, I need to be able to send a backtab (XK_ISO_Left_Tab, code 0xFE20). If I connect directly to the application I can send it just pressing SHIFT + TAB.

From noVNC, I tried:
```js
      rfb.sendKey(XK_Shift_L, null, true);
      rfb.sendKey(XK_Tab);
      rfb.sendKey(XK_Shift_L, null, false);
```
But it doesn't seem to do the trick.

Any idea of what am I missing?

I checked `input/keysym.js` and XK_ISO_Left_Tab is missing along with may other Keyboard (XKB) Extension function and modifier keys (and all many others if comparing with https://www.cl.cam.ac.uk/~mgk25/ucs/keysymdef.h).
I don't really understand how this whole key mapping works, so any help is very appreciated. 🙂

**Comment by CendioOssman** [comment]
You can't unfortunately. This is a corner case where the specification explicitly states to never send XK_ISO_Left_Tab:

> There is no universal standard for "backward tab" in the X Window System. On some systems shift+tab gives the keysym "ISO Left Tab", on others it gives a private "BackTab" keysym and on others it gives "Tab" and applications tell from the shift state that it means backward-tab rather than forward-tab. In the RFB protocol the latter approach is preferred. Viewers should generate a shifted Tab rather than ISO Left Tab. However, to be backwards-compatible with existing viewers, servers should also recognise ISO Left Tab as meaning a shifted Tab.

https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#744keyevent

So this is up to your server to do the right thing if it sees XK_Tab whilst shift is pressed.

**Comment by juanjoDiaz** [comment]
Understood!

Thanks for the quick response! 🙂
