### ISSUE TITLE
How to makefile for language file（noVNC/po/Makefile）

### ISSUE THREAD

**Issue by QQ2017** [novnc/noVNC#1416]
How to makefile for language file（noVNC/po/Makefile）?
What makefile environment do I need to build?

**Comment by CendioOssman** [comment]
I'm not sure exactly what you are asking. You need to have the gettext tools installed, as well as xgettext. You also need to have all the noVNC dependencies installed (standard `npm install` in the top directory).

Some more details can be found here:

https://github.com/novnc/noVNC/wiki/Translations
