### ISSUE TITLE
No "Sec-WebSocket-Protocol" header

### ISSUE THREAD

**Issue by TclHttpd** [novnc/noVNC#1418]
**Describe the bug**
In Realease 1.1.0 there is a "Sec-WebSocket-Protocol binary" header but in the latest Master the "Sec-WebSocket-Protocol" header is removed

**To Reproduce**
Checked sent headers on both Firefox and Chrome.

**Expected behavior**
Backwards compatible with version 1.1.0

**Screenshots**

**Client (please complete the following information):**
 - OS: Windows
 - Browser: Firefox 
 - Browser version: 77.0.1 (64-bit)

**Server (please complete the following information):**
 - noVNC latest Master
 - VNC server: TigerVNC
 - WebSocket proxy: CloudTk (Tcl websocket proxy)

**Additional context**

**Comment by CendioOssman** [comment]
I'm afraid that is on purpose. The "binary" sub-protocol was non-standard, so it was removed.

Please update your server to not require it, or make sure the RFB constructor is called with the subprotocol you need.
