### ISSUE TITLE
Mouse cursor is displayed only after a while

### ISSUE THREAD

**Issue by MagnaboscoL** [novnc/noVNC#1419]
**Describe the bug**
noVNC is running in an embedded device with a touchscreen. When I load the webpage handled by noVNC from Chrome, running in my PC, the cursor is initially hidden and shows up only after a while or as soon as I blindly hit an editable field.

**Expected behavior**
As a temporary fix I just set `showDotCursor = true` but ideally the cursor should show up immediately.

**Client:**
 - OS: browser running on Windows and noVNC running on linux
 - Browser: chrome
 - Browser version: 83.0.4103.97

**Server:**
 - noVNC version: 1.1.0
 - VNC server: QT QVncIntegration (QT QPA Plugin qvnc)
 - WebSocket proxy: websockify

**Additional context**
To me it looks like the issue can be related to "Initial cursor issue" https://github.com/novnc/noVNC/blob/master/core/rfb.js#L183.
If it is the case, would make sense to add an option to force the initial cursor to show up?

**Comment by CendioOssman** [comment]
This is something we've seen before with the TightVNC server. It was (is) a bug in the server where it doesn't send the cursor on connect, only when it changes. I wonder if QT's server has the same issue.

Do you see the problem with other server as well on this machine?

**Comment by MagnaboscoL** [comment]
Hi,

well I cannot try other servers at the moment, but I have just tried other VNC clients.

With both _Ultra VNC viewer_  and _Real VNC viewer_ there is the same issue, so it is definitely a server issue.

In your opinion would make sense to add an option to force the use of a local cursor at the beginning if no cursor is detected?

Regards

**Comment by CendioOssman** [comment]
That is what the "dot cursor" setting is for. We do something minimal instead of showing a normal cursor as we don't know why things are going wrong.

I suggest you report the issue to Qt and hopefully they can fix it in their end and you'll get the correct cursor right away.

**Comment by forlayo** [comment]
I've reported this on TightVNC, just in case anyone is wondering if bug exists on their tracker: https://sourceforge.net/p/vnc-tight/bugs/1512/

**Comment by MagnaboscoL** [comment]
I've just reported the bug to Qt, see [QTBUG-85006](https://bugreports.qt.io/browse/QTBUG-85006).
Just in case someone is interested, attached to the bug there is also a patch that, at least in my case, seems to fix the issue.
