### ISSUE TITLE
Second connection attempt takes a lot of time to complete.

### ISSUE THREAD

**Issue by forlayo** [novnc/noVNC#1421]
**Describe the bug**
Connecting first to my UltraVNC is quite fast and good, however second attempt (refresh on browser for example) takes a lot of time. 

I've checked that if I keep something running on the device that does screen changes ( like a webpage with an stopwatch ), the problem does not exists. Then for me is a question of not getting video until next refresh.

**To Reproduce**
1. Connect to UltraVNC server.
2. See video and all works as expected.
3. Refresh browser to connect again to same server.
4. Black screen until next screen update, that can take a lot of time.

**Expected behavior**
Same behavior on connecting on all connection attempts.

**Screenshots**

**Client (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 
 - Browser version: 83.0.4103.97

**Server (please complete the following information):**
 - noVNC version: 1.1.0
 - VNC server: UltraVNC
 - WebSocket proxy: Websockify

**Additional context**
While connection works as expected I can see quickly a message on logs that says:
`Screen: 1024x768, bpp: 32, depth: 32, big_endian: 0, true_color: 1, red_max: 255, green_max: 255, blue_max: 255, red_shift: 16, green_shift: 8, blue_shift: 0`
While the problem happens, that message isn't appearing until receiving the video.

**Comment by samhed** [comment]
Sounds like a server issue. Could you try with a different VNC viewer and see if the problem only happens with noVNC?

**Comment by forlayo** [comment]
@samhed you're right, I've been able to reproduce same using even UltraVNC client; for this and other issues at the end I moved to TightVNC. 

And this issue isn't reproducible anymore with TightVNC server.
