### ISSUE TITLE
Can't set rfb.showDotCursor = true

### ISSUE THREAD

**Issue by tofutree23** [novnc/noVNC#1422]
**Describe the bug**

**To Reproduce**
1. import core/rfb module. ( on React.js with typescript )
2. Do these things when you initialize module.
![image](https://user-images.githubusercontent.com/44552838/85249821-bea48f00-b48f-11ea-8278-3bbdce8d5818.png)
3. Then TypeError: Cannot read Property 'style' of null. will be appear.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44552838/85249720-869d4c00-b48f-11ea-830e-8bd78aba2270.png)

**Client (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Browser version:  83.0.4103.106

**Server (please complete the following information):**
 - noVNC version: 1.1.0
 - VNC server: UltraVNC
 - WebSocket proxy: RFB

**Additional context**

**Comment by CendioOssman** [comment]
Thank you for your bug report. This issue has been fixed in 1f2bb528503d7222ec123f00f55e25659d4d2624 and will be included in the next release. You can also try using the `master` branch directly.
