### ISSUE TITLE
[Question] What is the meaning of prefix no in noVNC?

### ISSUE THREAD

**Issue by levelrin** [novnc/noVNC#1429]
The prefix `no` sounds like it's NOT a VNC, but in fact, it is.

I wonder what that prefix means and why the creator chose such a confusing (at least for me) name?

Anyways, thank you guys for making this excellent product!

**Comment by samhed** [comment]
I think @kanaka is the best one to answer this one :)

**Comment by kanaka** [comment]
@levelrin sorry, for the really slow reply. The "no" in "noVNC" is a reference to the fact that it's completely web based so there is no client software or plugins that you have to install. I.e. it's a VNC client with no VNC client. I had previously been fighting with and fixing bugs in a previous Flash-based VNC client. HTML 2D Canvas and WebSockets had just started to arrive in many browsers and so I had the thought of trying to make a VNC client entirely with web technologies and no plugins. After proving that it was possible, I was then searching for a name to distinguish it from the multiple of other VNC clients in existence at the time and settled on "noVNC" which is both eminently googleable and communicates in some way what it's about.
