### ISSUE TITLE
mouse not shown when connecting to OSX-Catalina with remote management enabled

### ISSUE THREAD

**Issue by jonsito** [novnc/noVNC#1430]
When I try to connect with a remote mac OSX-Catalina ( with remote control enabled ) cursor is not shown. If enable "show dot cursor when no cursor available" dot appears. Click events work fine

No problem connecting Ubuntu-18.04 Linux machines running Xvnc as vnc server

Tested with:
- Fedora 32 Linux client with latest Firefox/Chrome/Brave
- Windows 10 with latest Edge
- Mac-OSX Catalina with Safari

Using noVNC from github repository (commit id: 90ead24, 2 days ago)

**To Reproduce**
- Enable remote management in mac ( need remote mngmt, screen sharing is not an option because i need multiple non-shared session logins ) and then enable remote control in inner options
- Connect via novnc
- Enter mac access password

**Expected behavior**
Mac login screen appears, mouse cursor is visible

**Obtained behavior**
Mac login screen appears, but no mouse is rendered. Need to enable "show dot cursor when no cursor available" to get an idea about mouse position

Using TigerVNC, Remmina, an other non-html vnc clients instead of noVNC everything work as expected and mouse cursor is properly shown
Notice that this issue only appears when mac is set up to handle remote control. with share screen there is no problem... but that is not an option for me as need multiuser remote login on mac

**Comment by samhed** [comment]
Thanks for testing with other viewers. Are you getting any errors in the browser console for noVNC?

**Comment by jonsito** [comment]
By enableing debug (adding &logging=debug to url ) i get nothing relevant:
```
>> Keyboard.allKeysUp keyboard.js:308:13
<< Keyboard.allKeysUp keyboard.js:312:13
>> RFB.constructor rfb.js:177:13
>> Display.constructor display.js:31:13
User Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0 display.js:61:13
<< Display.constructor display.js:69:13
<< RFB.constructor rfb.js:288:13
New state 'connecting', was ''. rfb.js:760:13
>> RFB.connect rfb.js:505:13
connecting to wss://acceso.lab.dit.upm.es:6234/l134.lab.dit.upm.es rfb.js:507:13
<< RFB.connect rfb.js:554:13
>> WebSock.onopen websock.js:189:17
Starting VNC handshake rfb.js:242:21
<< WebSock.onopen websock.js:195:17
Server ProtocolVersion: 003.889 rfb.js:1220:13
Sent ProtocolVersion: 003.003 rfb.js:1260:13
Authenticating using scheme: 2 rfb.js:1322:13
Server asked for credentials ui.js:1180:13
Authentication OK rfb.js:1645:17
Screen: 1920x1080, bpp: 32, depth: 24, bigEndian: 0, trueColor: 1, redMax: 255, greenMax: 255, blueMax: 255, redShift: 16, greenShift: 8, blueShift: 0 rfb.js:1719:13
Setting viewport to full display region display.js:155:17
New state 'connected', was 'connecting'. rfb.js:760:13
>> Keyboard.allKeysUp keyboard.js:308:13
<< Keyboard.allKeysUp  keyboard.js:312:13
```
Log shows no diff if I enable "show dot cursor when cursor is not available"
Note: shared mode enabled, view only disabled and using local scaling

**Comment by CendioOssman** [comment]
I've tested this here and can reproduce it. Unfortunately it seems to be a macOS bug that we cannot do much about. :/

I can see the exact same issue in TigerVNC, but not Remmina. After some poking around it turns out that if the client supports VMware's extension for mouse cursors then the macOS server stops sending any cursor update.

Some more oddities is that a) it works if the user is logged on locally, and b) if a client **not** supporting the VMware extension connects then the cursor works for noVNC as well until the user logs out.

Unfortunately there isn't much we can do here. Apple needs to fix their server so it doesn't break when a client supports this VMware extension. So I'm afraid you'll have to report it to Apple and hope they fix it.
