### ISSUE TITLE
Gray screen

### ISSUE THREAD

**Issue by srinvias8in** [novnc/noVNC#1432]
Hi,
I am able to login no vnc,after login i am getting gray screen.I restarted the service also,but not success. Please suggest.

**Comment by CendioOssman** [comment]
The most likely reason is that the server is simply showing just a gray screen.

Could you please fill out the bug form so we get some details about your setup.

**Comment by srinvias8in** [comment]
thanks for your support,it is resolved after restart the server.But due to which service it is happens i am not understanding.

please guide which service related for this vnc.

**Comment by samhed** [comment]
You will have to provide substantially more information if you want help. @CendioOssman already asked you to fill out the bug form.
