### ISSUE TITLE
Question: how touch events are transmitted ?

### ISSUE THREAD

**Issue by webpolis** [novnc/noVNC#1433]
I'd like to know, since I see in the code that touch events are handled, how are those transmitted to the remote VNC server? Are these events converted to MOUSE input events somehow?

Pardon if the question sounds noob, but I really don't have much time to dig deeper.

**Comment by CendioOssman** [comment]
This has recently changed on `master`, but this is how it works right now:

`GestureHandler` from `core/input/gesturehandler.js` listens to touch events from the browser. It then tries to detect various gestures and generates new gesture events based on that.

These gesture events are caught by `RFB` in `core/rfb.js` which maps them to mouse events for the server. There is no touch support in the VNC protocol.

Hope this helps.
