### ISSUE TITLE
Failed while connected: Error decoding rect: TypeError

### ISSUE THREAD

**Issue by brathering82** [novnc/noVNC#1436]
The connection works. For a split second I can see the remote screen. Then the connection closes.

The browser log is as follows:

> User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
> display.js:69 << Display.constructor
> rfb.js:288 << RFB.constructor
> rfb.js:760 New state 'connecting', was ''.
> rfb.js:505 >> RFB.connect
> rfb.js:507 connecting to ws://192.168.15.89:6080/websockify
> rfb.js:554 << RFB.connect
> websock.js:190 >> WebSock.onopen
> rfb.js:242 Starting VNC handshake
> websock.js:196 << WebSock.onopen
> rfb.js:1220 Server ProtocolVersion: 003.003
> rfb.js:1260 Sent ProtocolVersion: 003.003
> rfb.js:1322 Authenticating using scheme: 2
> ui.js:1180 Server asked for credentials
> credentials @ ui.js:1180
> (anonymous) @ eventtarget.js:32
> dispatchEvent @ eventtarget.js:32
> _negotiateStdVNCAuth @ rfb.js:1470
> _negotiateAuthentication @ rfb.js:1621
> _initMsg @ rfb.js:1804
> _negotiateSecurity @ rfb.js:1324
> _initMsg @ rfb.js:1801
> _handleMessage @ rfb.js:856
> (anonymous) @ rfb.js:236
> _recvMessage @ websock.js:283
> rfb.js:1645 Authentication OK
> rfb.js:1719 Screen: 1024x768, bpp: 32, depth: 32, bigEndian: 0, trueColor: 1, redMax: 255, greenMax: 255, blueMax: 255, redShift: 16, greenShift: 8, blueShift: 0
> rfb.js:760 New state 'connected', was 'connecting'.
> **rfb.js:808 Failed while connected: Error decoding rect: TypeError: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': Value is not of type 'long'.**
> _fail @ rfb.js:808
> _handleDataRect @ rfb.js:2473
> _handleRect @ rfb.js:2208
> _framebufferUpdate @ rfb.js:2160
> _normalMsg @ rfb.js:2076
> _handleMessage @ rfb.js:847
> (anonymous) @ rfb.js:236
> _recvMessage @ websock.js:283
> rfb.js:760 New state 'disconnecting', was 'connected'.
> rfb.js:558 >> RFB.disconnect
> keyboard.js:308 >> Keyboard.allKeysUp
> keyboard.js:312 << Keyboard.allKeysUp
> websock.js:214 Closing WebSocket connection
> rfb.js:587 << RFB.disconnect
> rfb.js:760 New state 'disconnected', was 'disconnecting'.
> rfb.js:763 Clearing disconnect timer
> **websock.js:185 WebSocket connection to 'ws://192.168.15.89:6080/websockify' failed: Received a broken close frame containing a reserved status code.**
> open @ websock.js:185
> _connect @ rfb.js:511
> _updateConnectionState @ rfb.js:773
> websock.js:204 >> WebSock.onerror: [object Event]
> rfb.js:282 WebSocket on-error event
> (anonymous) @ rfb.js:282
> _websocket.onerror @ websock.js:205
> error (async)
> open @ websock.js:203
> _connect @ rfb.js:511
> _updateConnectionState @ rfb.js:773
> setTimeout (async)
> RFB @ rfb.js:286
> connect @ ui.js:1026
> websock.js:206 << WebSock.onerror: [object Event]
> websock.js:199 >> WebSock.onclose
> websock.js:201 << WebSock.onclose

I attach a record-file.
[log.log](https://github.com/novnc/noVNC/files/4891002/log.log)

edit:
Browser version: Chrome Version 83.0.4103.116 (64-Bit)
OS Client: Windows 10 Pro 1909
noVNC Version: 1.1.0, 1.2.0-beta, and git pull 2020-07-08
VNC server name/version: unknown. It's included in the firmware of the Keyence XG-X controller
I can connect with RealVNC Viewer and UltraVNC Viewer

**Comment by samhed** [comment]
Please fill out the issue template, we're missing essential information such as noVNC version, VNC server, browser and more...

**Comment by CendioOssman** [comment]
Thank you. We need to pinpoint this further though. Could you apply this patch and see what you get in the browser console:

```diff
diff --git a/core/rfb.js b/core/rfb.js
index f35d503..3bb3547 100644
--- a/core/rfb.js
+++ b/core/rfb.js
@@ -2471,6 +2471,9 @@ export default class RFB extends EventTargetMixin {
                                       this._fbDepth);
         } catch (err) {
             this._fail("Error decoding rect: " + err);
+            if (err.stack) {
+                Log.Error("Decode error stack:\n", err.stack);
+            }
             return false;
         }
     }
```

**Comment by brathering82** [comment]
Here is the output:

> rfb.js:2475 Decode error stack:
>  TypeError: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': Value is not of type 'long'.
>     at Display._bgrxImageData (http://192.168.15.89:6080/core/display.js:561:35)
>     at Display.blitImage (http://192.168.15.89:6080/core/display.js:448:18)
>     at RawDecoder.decodeRect (http://192.168.15.89:6080/core/decoders/raw.js:47:17)
>     at RFB._handleDataRect (http://192.168.15.89:6080/core/rfb.js:2468:28)
>     at RFB._handleRect (http://192.168.15.89:6080/core/rfb.js:2208:29)
>     at RFB._framebufferUpdate (http://192.168.15.89:6080/core/rfb.js:2160:23)
>     at RFB._normalMsg (http://192.168.15.89:6080/core/rfb.js:2076:28)
>     at RFB._handleMessage (http://192.168.15.89:6080/core/rfb.js:847:31)
>     at Object.message (http://192.168.15.89:6080/core/rfb.js:236:18)
>     at Websock._recvMessage (http://192.168.15.89:6080/core/websock.js:283:33)

**Comment by CendioOssman** [comment]
Thank you. Unfortunately it wasn't quite enough to figure out what goes wrong.

Please apply this diff as well so we can see what the Raw decoder is up to as it crashes.

```diff
diff --git a/core/decoders/raw.js b/core/decoders/raw.js
index 4d84d7d..e9884e6 100644
--- a/core/decoders/raw.js
+++ b/core/decoders/raw.js
@@ -13,6 +13,7 @@ export default class RawDecoder {
     }
 
     decodeRect(x, y, width, height, sock, display, depth) {
+        console.log(x, y, width, height);
         if (this._lines === 0) {
             this._lines = height;
         }
@@ -44,6 +45,7 @@ export default class RawDecoder {
             index = 0;
         }
 
+        console.log(x, curY, width, currHeight);
         display.blitImage(x, curY, width, currHeight, data, index);
         sock.rQskipBytes(currHeight * bytesPerLine);
         this._lines -= currHeight;
```

**Comment by c4pQ** [comment]
Have you tried ctrl + f5? I've just faced js TypeError and _fixed_ it with cleaning the cash.

**Comment by brathering82** [comment]
Here is the output.
```
console.log(x, y, width, height):               0 0 0 0 raw.js:16:17
console.log(x, curY, width, currHeight):    0 0 0 NaN raw.js:48:14
```

If I add a condition to skip execution if currHeight is NaN then I can see and interact with vnc.
```
if(! isNaN(currHeight)) {
        display.blitImage(x, curY, width, currHeight, data, index);
        sock.rQskipBytes(currHeight * bytesPerLine);
        this._lines -= currHeight;
}
```

**Comment by samhed** [comment]
When calculating currHeight, the `sock.rQlen / bytesPerLine` can result in 0 divided by 0, which gives `NaN`.

**Comment by samhed** [comment]
This should be fixed in master now @brathering82

**Comment by vinitkrb** [comment]
I am getting the following error when playing youtube video in high resolution(1600*1200).

rfb.js:810 Failed while connected: Error decoding rect: Error: Illegal hextile subencoding (subencoding: 64)
_fail @ rfb.js:810
_handleDataRect @ rfb.js:2260
_handleRect @ rfb.js:2122
_framebufferUpdate @ rfb.js:2080
_normal_msg @ rfb.js:1804
_handle_message @ rfb.js:849
(anonymous) @ rfb.js:232
_recv_message @ websock.js:284

can someone help? Thanks in advance.
