### ISSUE TITLE
How do you get it to build standalone?

### ISSUE THREAD

**Issue by bencromwell** [novnc/noVNC#1437]
I'm following the docs here: https://novnc.com/noVNC/docs/LIBRARY.html

but am struggling. I've done the commonjs output step. But then I am trying to get it to build with Gulp to use in a browser as part of an app that used window.RFB in the older version that just directly attached to window.

This is my gulp task:

```

    src('**/*.js', { cwd: 'frontend-src/js/noVNC-1.1.0/lib', sourcemaps: true })
        .pipe(babel({}).on('error', console.error))
        .pipe(concat('novnc.js'))
        .pipe(browserify().on('error', console.error))
        .pipe(dest('public/js'))
        .pipe(uglify().on('error', console.error))
        .pipe(rename({ suffix: '.min' }))
        .pipe(sourcemaps.write('./'))
        .pipe(dest('public/js'));
```

Is there an established method of doing this/something like this? I have tried various combinations with and without babel/browserify but am at a loss as to what the required method of conversion actually is. Even if not gulp-specific, in principle what do you do with the commonjs output in /lib?

**Comment by CendioOssman** [comment]
It's not something we use ourselves, so I'm afraid the npm package is a bit more of a "best effort" thing.

What error are you seeing when running this?

**Comment by bencromwell** [comment]
https://gist.github.com/bencromwell/d015ad3bec935011c893638336118cc3

So the above gulp task produces the results in the gist there^ 

Trying to load that in a browser with script type="module" produces 

Uncaught SyntaxError: redeclaration of function _interopRequireWildcard

There are indeed multiple declarations but they should be namespaced into different modules, I'd have thought.

The question really is which files are supposed to be built to create a single js file to include on a page and use noVNC?

**Comment by CendioOssman** [comment]
Ah. A converted js file should not be included as a module. You need to include it as a classical file in that case. AFAIK there is no way to combine modules and still keep them as a module.

Does it work fine if you remove `type=module`?

**Comment by bencromwell** [comment]
Ah, I was using `type=module` because I was getting this error - https://stackoverflow.com/questions/42237388/syntaxerror-import-declarations-may-only-appear-at-top-level-of-a-module

`Uncaught ReferenceError: exports is not defined`

is what I get now including it as a normal file

**Comment by CendioOssman** [comment]
CommonJS is indeed not supported by the browsers. That is what browserify is supposed to fix.

Have you tried just running just browserify on the output from our require script? You have a lot of tools in that chain and at this point it is unclear which one is broken.

**Comment by bencromwell** [comment]
Yeah I ended up with the above because I was trying all these combinations to see what works (obviously nothing does so far!)

At the moment I have this:

- noVNC-1.1.0$ ./utils/use_require.js --as commonjs
- gulp task src from the lib dir of noVNC - i.e. the outputted commonjs
- fails on browserify at 'module "./util/logging.js" not found

If we XY problem it- 

- `./utils/use_require.js --as commonjs` produces some output
- ??? missing step here
- `<script src="novnc.js"></script>` (?)
- later application code is able to call `let rfb = new RFB({})`

So to take it back a step the root question is how to get from that commonjs output to something usable.

**Comment by CendioOssman** [comment]
> * ??? missing step here

I just tested things here and running plain old `browserify` using our converted output works just fine. So unfortunately it must be one of your other many steps that don't work correctly.

This is not really something we can support as we are not familiar with all of those tools. I suggest you test which step breaks things and ask that project for further help.
