### ISSUE TITLE
wsProtocols missing from new RFB() parameters

### ISSUE THREAD

**Issue by edwinvuw** [novnc/noVNC#1439]
**Describe the bug**
NoVNC version 1.2.0 fails to connect and the console shows this error:  Status Code: 400 Client must support 'binary' or 'base64' protocol

**To Reproduce**
1. In a command line session, start NoVNC using:  launch.sh --listen '46901' --vnc 'hostname_goes_here:5900' --cert /path/to/self.pem --ssl-only
2. In a browser, navigate to the URL shown in the console (where it says "Navigate to this URL:"
3. Click "Connect"
4. The browser will fail to connect.
5. In the command line window, the error is shown:  Status Code: 400 Client must support 'binary' or 'base64' protocol

**Expected behavior**
After Step 3 the VNC session should start, and the command line window should not show any error messages.

**Client (please complete the following information):**
 - OS: Debian for command line session, macOS for browser
 - Browser: Safari
 - Browser version: 10.15.5

**Server (please complete the following information):**
 - noVNC version: 1.2.0 Beta
 - VNC server: TightVNC
 - WebSocket proxy: websockify

**Additional context**
I fixed this myself by adding the wsProtocols parameter when calling new RFB().  So lines 1026-1029 changed from:

        UI.rfb = new RFB(document.getElementById('noVNC_container'), url,
                         { shared: UI.getSetting('shared'),
                           repeaterID: UI.getSetting('repeaterID'),
                           credentials: { password: password } });

to:

        UI.rfb = new RFB(document.getElementById('noVNC_container'), url,
                         { shared: UI.getSetting('shared'),
                           wsProtocols: ['binary','base64'],
                           repeaterID: UI.getSetting('repeaterID'),
                           credentials: { password: password } });

**Comment by CendioOssman** [comment]
I'm afraid this is per design. `"binary"` and `"base64"` protocols were non-standard so they have been removed from noVNC. Please update your websockify to something that doesn't require these.
