### ISSUE TITLE
Locales: app/ui.js:1118 is not covered in all languages.

### ISSUE THREAD

**Issue by D0n1elT** [novnc/noVNC#1441]
**Describe the bug**
The error message "Failed to connect to server" is not localized in some languages (like german, spanish...) 
The error message is in the file:
https://github.com/novnc/noVNC/blob/9142f8f0f7b4a53447f5cfec3a797cbf0d6204a9/app/ui.js#L1118

**To Reproduce**
Make your browser for example german and give noVNC invalid server parameters.

**Expected behavior**
Error message should be translated.

**Comment by CendioOssman** [comment]
I'm afraid we don't have people that know all our languages so we rely on people volunteering. This round unfortunately no one contributed to our translations. Hopefully people will do so in the future. Until then there isn't much we can do.
