### ISSUE TITLE
[Question]How to get response status from NoVNC (CORS) - 1000 or 1006

### ISSUE THREAD

**Issue by slideroh** [novnc/noVNC#1447]
How can I get response status [ noVNS_status div]  from noVNC on another site (CORS issue) as a div on main page or JSON/XML?
In 99% everything works fine, however sometimes I've got error 1000 or 1006 - Server disconnected (code: 1000, reason: Target closed). In this scenario I want to create another WS and give user a working one.

It's client side and gives an answer after some time (JS - on the fully loaded page). At the beginning it will only give me `<div id="noVNS_status"></div>`, so I cannot just parse URL HTML link, when it get full load I'll see:
`<div id="noVNS_status">Server disconnected (code: 1000, reason: Target closed</div>`
Link looks like: site.com/vnc.html?path=?token=1b3b8585e967289af433ae5cc2239c8ae7e680e0&password=vz240di4

I know I can create iframe and `document.getElementById('frame').contentWindow.window.getElementById('noVNC_status')` but it returns _CORS issue SecurityError: Permission denied to access property "getElementById" on cross-origin object_ even when iframe is with link: _http://allow-any-origin.appspot.com_

I would like to get a JSON/XML respond - just with noVNS_status - it's title on a bar. Server disconnected (noVNC)
I have access to noVNC server-side and to another site - where I want to check STATUS.

**How can I determine if the connection is correct - working or not (error 1000/1006) not going into it?**

https://i.stack.imgur.com/eRS1z.png

**Comment by CendioOssman** [comment]
I'm afraid the full application is not designed with such integration in mind. It only accepts some initial settings. So the short answer is you can't.

If you want more advanced integration you'll have to look at using the library instead. But that means writing your own UI for it. It has a `disconnect` event that contains a flag if there was an error or not.
