### ISSUE TITLE
failed on Chrome and firebox but okay on Edge

### ISSUE THREAD

**Issue by hy04** [novnc/noVNC#1450]
Hi, I tried to run novnc on chrome and firefox, it always throw me an error: 
![jssssss](https://user-images.githubusercontent.com/46552584/89507731-7c48ce80-d7ff-11ea-940c-cac5e9abf161.PNG)

and the page show like this:
![ggggg](https://user-images.githubusercontent.com/46552584/89507764-8d91db00-d7ff-11ea-90c9-217c9d51ecf9.PNG)

but it works on Edge though, can anyone help me out？ Much thanks!

**Comment by samhed** [comment]
I'm afraid this is a problem in your web server, not in noVNC. So make sure your server is serving our files correctly and things will work fine for you.
