### ISSUE TITLE
Right Shift key not working in version 1.2.0

### ISSUE THREAD

**Issue by kayechica** [novnc/noVNC#1453]
I upgraded noVNC from 0.5.1 to v1.1.0 and Right Shift key does not work (it does not make the letters display in upper case).  I upgraded again to the latest v1.2.0 and I encountered the same problem. This was working well in the last version I used which is v0.5.1.

 - OS: Windows 10
 - Browser: Firefox, Chrome
 - Browser version: 
       Firefox: 79.0 (64-bit)
       Chrome: Version 84.0.4147.105 (Official Build) (64-bit)
 - noVNC version: v1.2.0 (commit fed92ca0b5199ff9f6bc5da88c2d225439c8934d)
 - VNC server: LibVNCServer

Note:
Left Shift key works fine. In all the noVNC versions I have used including the latest v1.2.0, there is no problem with the LEFT Shift key. Only the RIGHT Shift.
I also tried other client like 'VNC Viewer' and Right shift key works fine.

**Comment by samhed** [comment]
Works for me. I'm using noVNC 1.2.0 and Windows 10 connecting to a TigerVNC running on Fedora 32. Perhaps it's related to LibVNCServer?

Are you seeing any errors in the VNC server logs or in the browser console?

If you have the opportunity to test a different VNC server, that would also make things easier.

**Comment by kayechica** [comment]
I'll try to check on the server side. It's just weird though that with the same server I have, and with the new NoVNC version, the right shift key does not work.

**Comment by samhed** [comment]
Ok, good.

noVNC has changed a lot from 0.5.1, it's difficult to say what the cause can be so far.

**Comment by CendioOssman** [comment]
Likely a server bug unfortunately. We added support for the right shift key after 0.5.1. Before that we always sent a left shift.

So again, we'll need you to test another server. You can also test the latest TigerVNC client. It should also support right shift properly.

**Comment by kayechica** [comment]
Thank you for the replies. Sorry I forgot to update this one. I already tried in other servers and it is indeed working fine. Thanks.
