### ISSUE TITLE
Version 1.2.0 not working, older versions do work

### ISSUE THREAD

**Issue by velobarplus** [novnc/noVNC#1454]
**Describe the bug**
Updated to version 1.2.0 and it stopped connecting to the vnc server.

**To Reproduce**
Try to connect to a vnc server.

**Expected behavior**
To connect and see a remote desktop connection.

**Client (please complete the following information):**
 - OS: macOS
 - Browser: Chrome, Firefox
 - Browser version: latest (84/79)

**Server (please complete the following information):**
 - noVNC version: 1.2.0
 - VNC server: vmware (don't know what they have)
 - WebSocket proxy: nginx

**Additional context**
Using build from this command: `node ./utils/use_require.js --as amd --with-app --only-legacy --clean`
Was using 1.0.0 and everything worked fine, no issues.
Updated to 1.1.0 and everything still worked fine, no issues.
Updated to 1.2.0 and when trying to connect there is an error:
 - WebSocket connection to '...' failed: Error during WebSocket handshake: Unexpected response code: 502
```
open | @ | websock.js?_=26627614:216
_connect | @ | rfb.js?_=26627614:453
_updateConnectionState | @ | rfb.js?_=26627614:758
```
 - Failed when connecting: Connection closed (code: 1006)
```
_fail | @ | rfb.js?_=26627614:806
(anonymous) | @ | rfb.js?_=26627614:274
_websocket.onclose | @ | websock.js?_=26627614:235
```
 - nginx error.og: `upstream prematurely closed connection while reading response header from upstream` - this only happens after updating to 1.2.0

**Comment by velobarplus** [comment]
I figured out what the problem was.
In rfb.js `_this._wsProtocols = options.wsProtocols || []; // Internal state` will always be an empty array, when `this._sock.open(this._url, this._wsProtocols);` and the connection will fail.

If I set a default of `binary` like `_this._wsProtocols = options.wsProtocols || ['binary']; // Internal state` everything works fine.

Am I missing something?

**Comment by samhed** [comment]
This is a bug in vmware's WebSocket proxy which they need to fix.

See #1304 #1305 and #1310 

It seems vmware has the same issue as libvncserver and QEMU did.

**Comment by velobarplus** [comment]
@samhed what else can I do if I don't have control over the server/code?

**Comment by samhed** [comment]
Is VMware the provider of your websocket proxy?
You also posted on our mailing list didn't you? On there you wrote that you used QEMU's VNC server?

If you're using QEMU it should just be a matter of upgrading to v5+.

If you're using VMware I'd recommend reporting the issue to them so they can get it fixed. And use noVNC 1.0 in the meanwhile.

**Comment by CendioOssman** [comment]
You can also put another proxy in front of your VMware server, provided the VNC port is also open.
