### ISSUE TITLE
vnc playback for recordings doesn't seems to be working

### ISSUE THREAD

**Issue by sonisrje** [novnc/noVNC#1458]
I created the recordings directory and move one of the recordings to it. Thereafter I am trying to access the URL as follows: https://macc02vk4lrg8wn:6090/tests/vnc_playback.html?data=record.2

But still it gives the below error:

Loading record.2...
Error loading recording: ReferenceError: vncFrameData is not defined

Can you please help me with this? I am also attaching the screenshot herewith.
<img width="737" alt="Screenshot 2020-08-27 at 3 17 21 PM" src="https://user-images.githubusercontent.com/44198033/91481254-bdde0e00-e8c1-11ea-8b84-96fa5690c849.png">

This is how I am recording the session:

./utils/launch.sh --vnc ..*.:5900 --ssl-only --listen 6090 --record session

**Comment by bitskri3g** [comment]
Edit record.2 in a text editor and change VNC_Frame_Data (should be the first line) to vncFrameData and that error should go away.  You will probably have another error talking about a missing function, however.

**Comment by samhed** [comment]
Fixed in ecdd075672073410f65a7c8ceec9fd9951c9ffde and 7ce1b071ecb542efe26c5042e61d52dc5af138f5
