### ISSUE TITLE
https problem

### ISSUE THREAD

**Issue by zhoushengsheng-droid** [novnc/noVNC#1459]
How to access NOVNC through HTTPS, because my docker is used through the port mapped out by NOVNC, but it is a pity. Because my platform webpage is HTTPS, I have a same origin error when I bring this NOVNC container into it. I cannot nest HTTP NOVNC on HTTPS web pages.

**Comment by samhed** [comment]
If you're using Websockify (or noVNC's launch script) I'd recommend checking out this page:

https://github.com/novnc/websockify/wiki/Encrypted-Connections
