### ISSUE TITLE
server not working

### ISSUE THREAD

**Issue by ooops4** [novnc/noVNC#1461]
i downloaded and i run on windows platform via vs code and git bash

but server error is occurred.

**Expected behavior**
am trying offline in locally to access. although am trying to access my laptop from running the server on my laptop itself. do i need another laptop or what ?

![error](https://user-images.githubusercontent.com/18586441/92123549-689e8100-ee1a-11ea-9de7-5e6895cb5fbb.jpg)

 - OS: Windows 10 1909v
 - Browser: chrome
 - Browser version: [e.g. 84]

 - noVNC version: 1.2.0
 - VNC server: UltraVNC Server
 - WebSocket proxy: websockify

**Comment by samhed** [comment]
Are you getting any more details in the browser console? Is UltraVNC Server logging something?

**Comment by ooops4** [comment]
is everything correct ??

![image](https://user-images.githubusercontent.com/18586441/92222241-52490180-eebc-11ea-8a46-c7817fa4e4b3.png)

**Comment by samhed** [comment]
It looks like your UltraVNC server is running on port 5900 not 5901? Try changing the launch script to point to that instead

**Comment by ooops4** [comment]
still the problem is same.
can we anydesk?

**Comment by samhed** [comment]
No, no time, sorry.

You have the "Encrypt" box ticked in noVNC but you are not running websockify with TLS. Try disabling "Encrypt".

**Comment by ooops4** [comment]
getting this error
Failed when connecting: Connection closed (code: 1000, reason: Target closed)

**Comment by ooops4** [comment]
its working now. 👍 
thank you so much. 💯 
can i ask you one more question?
can we deploy this to server and use it to connect to my friends laptop?
can you guide me ?

**Comment by CendioOssman** [comment]
I'm afraid the issue tracker is for specific problems. Please use our mailing list and there might be someone who can provide more general guidance.
