### ISSUE TITLE
how to use --auth-plugin and --atuth-source?

### ISSUE THREAD

**Issue by swinsome** [novnc/noVNC#1465]
I want to use auth plugin.Exec like this
 --auth-plugin=BasicHTTPAuth --auth-source='user1:passwd' and url like http://localhost:6902/vnc.html?host=localhost&port=6902?Authorization=user:passwd.But it does not work.Could you  give an example？
It is better give an example for token_plugin.

**Comment by CendioOssman** [comment]
The syntax for such auth is http://user:passwd@localhost:6902/vnc.html?host=localhost&port=6902. Hopefully that should work better for you.
