### ISSUE TITLE
Alt in Firefox

### ISSUE THREAD

**Issue by CJWbiu** [novnc/noVNC#1466]
When using novnc in Firefox, the ctrl+alt or altGr key combination is invalid. Check the source code and find that there is a special treatment for the alt key in Firefox. When the alt is pressed, other events will be triggered to simulate the alt bounce first, which causes the key combination to fail. It is not clear what problem this processing is meant to solve. If this logic is removed, what impact will it have?
```
_checkAlt(e) {
        if (e.skipCheckAlt) {
            return;
        }
        if (e.altKey) {
            return;
        }

        const target = this._target;
        const downList = this._keyDownList;
        ['AltLeft', 'AltRight'].forEach((code) => {
            if (!(code in downList)) {
                return;
            }

            const event = new KeyboardEvent('keyup',
                                            { key: downList[code],
                                              code: code });
            event.skipCheckAlt = true;
            target.dispatchEvent(event);
        });
    }
```

**Comment by CendioOssman** [comment]
Could you fill out the bug form so we get a picture of what your environment is like?

**Comment by CJWbiu** [comment]
> Could you fill out the bug form so we get a picture of what your environment is like?

**Describe the bug**
When using the `alt` key combination in FireFox, the sending order is wrong.

**To Reproduce**
Steps to reproduce the behavior:
1. Use Italian keyboard and set the keyboard language of both virtual machine (window10) and physical machine to Italian.
2. Connect to the virtual machine using `novnc`.
3. Press `ctr+alt+[`.
4. View the console log.

**Expected behavior**
Print out sequently:
```
Sending key (down): keysym 65507, scancode 29
Sending key (down): keysym 65513, scancode 56
Sending key (down): keysym 91, scancode 26
Sending key (up): keysym 91, scancode 26
Sending key (up): keysym 65513, scancode 56
Sending key (up): keysym 65507, scancode 29
```

**Actual behavior**
Print out sequently:
```
Sending key (down): keysym 65507, scancode 29
Sending key (down): keysym 65513, scancode 56
Sending key (up): keysym 65513, scancode 56
Sending key (down): keysym 91, scancode 26
Sending key (up): keysym 91, scancode 26
Sending key (up): keysym 65507, scancode 29
```
**Screenshots**
![Uploading 51600698813_.pic_hd.jpg…]()


**Client (please complete the following information):**
 - OS: Windows10
 - Browser: Firefox
 - Browser version: 79

**Server (please complete the following information):**
 - noVNC version: v1.2.0
 - VNC server: QEMU
 - WebSocket proxy: unknown

**Comment by CendioOssman** [comment]
It seems Firefox has tweaked their handling of AltGr at some point and are no longer setting the "Alt" state for it. This is tripping up a workaround we have for an old Firefox bug.

Fortunately that bug got fixed in Firefox 63:

https://bugzilla.mozilla.org/show_bug.cgi?id=1335347
https://bugzilla.mozilla.org/show_bug.cgi?id=1435717

So I guess we can drop this workaround now.

**Comment by CendioOssman** [comment]
Fixed in 20e4f1b3f8a6b90fef7f520002b81ea4ad3b5c6f.

**Comment by samhed** [comment]
Great news!

**Comment by Fantu** [comment]
Hi, I'm not sure if the issue I'm having is the same or different.
I have major of keys that use altgr not working (I need at least "@" working if will be possible)
The server is debian 11 with kvm (qemu+libvirt) virtual machines, novnc 1.3.0, I'm unable to have "@" (that need altgr) working in all cases I tested: (on client side) both firefox and chrome (latest stable version), both linux and windows, 2 different notebook but always italian keyboard.
Opening firefox debug console I don't found the key events like the image above, what is the procedure to have it so I'll post the result?
Thanks for any reply and sorry for my bad english
