### ISSUE TITLE
kick out older connections

### ISSUE THREAD

**Issue by changsijay** [novnc/noVNC#1467]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
if it is possible when a new connection passed the authentication can let other older connection dropped?
which limit at most only 1 connection is controlling the server.

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by CendioOssman** [comment]
This feature is actually already available. It's the setting called "Shared Mode". Simply disable that and other clients will get kicked out when you connect.
