### ISSUE TITLE
With local scaling, Windows display becomes blocky / blurry

### ISSUE THREAD

**Issue by abulhol** [novnc/noVNC#1469]
I am using noVNC to connect to TightVNC server running on Windows 7 an 10 machines. 
I have local scaling enabled by default. 
Recently, I noticed that the picture is very blocky. If I move folders around on the desktop, the blurriness goes away, but then reappears. 
If I set scaling to "None", the picture is absolutely crispy. 
happen. 

Here is a screenshot: 
![image](https://user-images.githubusercontent.com/4851778/93984910-b0af2480-fd84-11ea-94eb-d855c774b3eb.png)

I had recently been using noVNC 1.1.0 and tried to solve the issue by upgrading to 1.2.0, but it persists. 
Maybe there has been a change in Chrome recently that causes this?

**Client:**
 - OS: Windows 10 version 2004
 - Browser: Chrome
 - Browser version: 85.0.4183.102

**Server:**
 - noVNC version: 1.2.0 (same issue on 1.1.0)
 - VNC server: TightVNC
 - WebSocket proxy: WebsocketSharp

**Comment by CendioOssman** [comment]
That does indeed look like a browser bug.

Can you test Edge or Firefox?

And does it happen with other VNC servers?

**Comment by abulhol** [comment]
@CendioOssman I have tried with Firefox 81.0 now, and the picture is normal there. 
So it seems to be related to Chrome. 
I don't have any other VNC servers running on Windows currently, so I haven't tested that.

**Comment by abulhol** [comment]
On Microsoft Edge the picture is also normal.

**Comment by abulhol** [comment]
Do you have any suggestions how to tackle the issue?
Can you reproduce it on your side?

**Comment by danielsmd** [comment]
Connection to Armbian via x11vnc. Appears on Chrome, and IE.
Compression @min, quality @max. 
noVNC - master branch 
![Capture](https://user-images.githubusercontent.com/23436369/94361146-7ca07000-00b2-11eb-807e-85aeef79d288.PNG)

**Comment by samhed** [comment]
Could we get a side-by-side comparison of chrome (with the bug) and firefox (that works)?

Historically I remember that we had issues with CSS transforms with non-integer numbers in some browsers. But iirc the local scaling mode just sets a different width and height on the canvas?

**Comment by samhed** [comment]
The initial screenshot quite clearly shows the blurry-ness, but @danielsmd your image wasn't as obvious

**Comment by CendioOssman** [comment]
I can reproduce this with Chrome on Linux as well. Unfortunately it is a Chrome bug with no really good workaround:

https://bugs.chromium.org/p/chromium/issues/detail?id=1126590

I'm afraid we'll just have to wait for Chrome to fix this.

**Comment by abulhol** [comment]
@CendioOssman Thanks a lot for looking into it! I hope the Chrome devs fix it soon.

**Comment by abulhol** [comment]
@CendioOssman Would this workaround be worth a try to add to noVNC?
https://bugs.chromium.org/p/chromium/issues/detail?id=1126590#c17
Or does it have other side effects that cause issues again?

**Comment by CendioOssman** [comment]
Given their description it will likely cause things to be a lot slower, which we really want to avoid. So let's wait and see a bit.

**Comment by patrakov** [comment]
For those who disagree with (or want to validate the reasoning behind) the upstream decision not to apply a workaround, here is a patch. Yes it slows everything down at least by a factor of 4, so anything above 1920x1080 does become unusable.

[display.js.diff.txt](https://github.com/novnc/noVNC/files/5508370/display.js.diff.txt)

**Comment by patrakov** [comment]
Thanks to the suggestion in https://bugs.chromium.org/p/chromium/issues/detail?id=1126590#c22, we now have a better-performing (tolerable even on 4K!) workaround: disable damage tracking, always update the full target canvas, and clear it before each update. @CendioOssman maybe we should consider something based on the attached patch, but with browser detection, so that non-buggy browsers don't suffer?

[display.js.diff.txt](https://github.com/novnc/noVNC/files/5520143/display.js.diff.txt)

**Comment by abulhol** [comment]
@patrakov I tried out your latest patch, but it seems to have no effect. Is this the only change necessary, or does it come on top of your previous patch?

**Comment by patrakov** [comment]
This is the only change necessary. However, if you have not configured the web server correctly (to disable automatic caching of JS files), you should do a Shift+Reload in order to apply it.

**Comment by abulhol** [comment]
@patrakov thanks. Web server configured correctly, but I had missed the first line of the patch (`this._targetCtx.clearRect ...`). 
Indeed this patch seems to work fine.

**Comment by abulhol** [comment]
The issue is fixed in Chrome 88, see https://bugs.chromium.org/p/chromium/issues/detail?id=1126590#c31
