### ISSUE TITLE
Improve performance of canvas.toDataURL

### ISSUE THREAD

**Issue by vbabenko** [novnc/noVNC#1470]
**Is your feature request related to a problem? Please describe.**
`novn/core/display.js`
`canvas.toDataURL` - takes too much time (for us ~500ms);

**Describe the solution you'd like**
One of the possible alternatives is `canvas.toBlob` https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by CendioOssman** [comment]
Ehm... There is no use of that API in `Display`. What issue are you seeing?

**Comment by vbabenko** [comment]
Not relevant. I am using an outdated version
