### ISSUE TITLE
Black page after a few clicks

### ISSUE THREAD

**Issue by Venom1p** [novnc/noVNC#1472]
As the title suggests, after opening the novnc page 'vnc.html' and clicking a few times, the page at first blocks, I disconnect and reconnect but the remote desktop is no longer accessible,Everything remains on a black page, to make the page accessible again you have to restart. 

I'm using ubuntu18 and websockify for proxy
Some idea?

**Comment by CendioOssman** [comment]
Please use the bug issue form so we can get a better picture of your setup.

**Comment by CendioOssman** [comment]
Replaced by #1474.
