### ISSUE TITLE
Black page

### ISSUE THREAD

**Issue by Venom1p** [novnc/noVNC#1474]
Black page

After opening the novnc 'vnc.html' page and clicking a few times such as a google page, the page first crashes. I log out and reconnect but the remote desktop is no longer accessible and you have a black screen with the message at the top that the desktop is there but you can't see it so everything stays on a black page (see screenshot whit message "connect (unencrypted) to xxxxxxxx:1"),

to make the page accessible again you have to restart everything and for a few clicks the page remains online, but as mentioned above everything will return to black.

![Screenshot_2](https://user-images.githubusercontent.com/60289036/95455710-93767a80-096e-11eb-936c-f0da970f272c.jpg)

![Screenshot_1](https://user-images.githubusercontent.com/60289036/95455761-a25d2d00-096e-11eb-8038-55e1ac7badb3.jpg)

- OS: ubuntu 18.04
- Browser: chrome, firefox
- VNC server: noVNC
- WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
noVNC is a client, not a server. And which version are you running of things?

Please fill out the form properly. We have those questions for a reason.

**Comment by Venom1p** [comment]
I am not an expert I am approaching this now, I think I am using the latest version

**Comment by samhed** [comment]
Perhaps you could link the instructions you used to set things up? That probably contains the information we need

**Comment by Venom1p** [comment]
sure, if you tell me what you need I attach everything here, thanks!

**Comment by Venom1p** [comment]
hi, i'm using 
websockify 0.9.0 
i have downloaded from 
https://github.com/novnc/websockify/archive/master.tar.gz

**Comment by Venom1p** [comment]
here in this image I show that the time I write "google.com" freezes and remains so

![Screenshot_3](https://user-images.githubusercontent.com/60289036/95566320-aeee8d80-0a21-11eb-9395-3738c07b0415.jpg)

someone who had the same problem and solved it? could you give me some information?

**Comment by samhed** [comment]
What VNC server are you using? Websockify isn't a VNC server, it's simply a proxy between TCP and WebSockets, and as Pierre said, noVNC is a client.

**Comment by Venom1p** [comment]
i have "x11vnc".

**Comment by samhed** [comment]
I suspect it's a server-side issue, the best way to verify this is to try connecting using a different VNC client. If you do that, are you seeing the same problem? Examples of other VNC clients are TigerVNC's 'vncviewer' and Remmina.

Furthermore I'd recommend checking for errors in the browser log and the x11vnc log.

**Comment by Venom1p** [comment]
no I have not changed because at the moment I am not able to understand how to change, I am recently approaching this system, would you like to connect to the server to understand where the problem is possibly?

**Comment by Venom1p** [comment]
have this error if can help "destroyed xdamage object: 0x20002c"

**Comment by Venom1p** [comment]
hi, I tried on another server which is the easiest thing at the moment, but I found the same problem with another server and with another vps

![Screenshot_3](https://user-images.githubusercontent.com/60289036/95686610-3a714580-0bff-11eb-95c4-5e1e8cf32fdd.jpg)

![Screenshot_1](https://user-images.githubusercontent.com/60289036/95686612-3ba27280-0bff-11eb-9808-bb1730d5fb32.jpg)

in both cases the server used is x11vnc.

**Comment by Venom1p** [comment]
I am trying what you recommended but at the moment i have not been successful here either

root@ns3022246:~# systemctl status vncserver@1.service
● vncserver@1.service - Start TightVNC server at startup
   Loaded: loaded (/etc/systemd/system/vncserver@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-10-12 17:25:01 CEST; 2h 43min ago
  Process: 7485 ExecStart=/usr/bin/vncserver -depth 24 -geometry 1280x800 :1 (code=exited, status=200/CHDIR)
  Process: 7484 ExecStartPre=/usr/bin/vncserver -kill :1 > /dev/null 2>&1 (code=exited, status=200/CHDIR)

Oct 12 17:25:01 ns3022246 systemd[1]: Starting Start TightVNC server at startup...
Oct 12 17:25:01 ns3022246 systemd[7484]: vncserver@1.service: Changing to the requested working directory failed: No such file or directory
Oct 12 17:25:01 ns3022246 systemd[7484]: vncserver@1.service: Failed at step CHDIR spawning /usr/bin/vncserver: No such file or directory
Oct 12 17:25:01 ns3022246 systemd[7485]: vncserver@1.service: Changing to the requested working directory failed: No such file or directory
Oct 12 17:25:01 ns3022246 systemd[7485]: vncserver@1.service: Failed at step CHDIR spawning /usr/bin/vncserver: No such file or directory
Oct 12 17:25:01 ns3022246 systemd[1]: vncserver@1.service: Control process exited, code=exited status=200
Oct 12 17:25:01 ns3022246 systemd[1]: vncserver@1.service: Failed with result 'exit-code'.
Oct 12 17:25:01 ns3022246 systemd[1]: Failed to start Start TightVNC server at startup.

**Comment by Venom1p** [comment]
no reply?
