### ISSUE TITLE
ubuntu 18 noVNC black screen

### ISSUE THREAD

**Issue by Venom1p** [novnc/noVNC#1476]
When you login on noVNC after some time it becomes black screen and you can no longer have the desktop remotely

1. http://ip:20001/
2. vnc.html
3. add password
4. after few second have (Something went wrong, connection is closed)

![immagine](https://user-images.githubusercontent.com/60289036/96006912-45fe7f80-0e3e-11eb-9a57-f8d36773da4b.png)

 - Ubuntu 18.04.5 LTS
 - Crome, Firefox
 - All brouser last versione used

 - noVNC last version
 - VNC server: x11vnc
 - WebSocket proxy: last version

I tried two different machines with the same operating system or "ubuntu 18" and it always gives me the same problem with this configuration, how can I solve always leaving this configuration?

**Comment by CendioOssman** [comment]
What do the logs say? We'd like to see the browser console, the websocket proxy log and x11vnc's log.

**Comment by Venom1p** [comment]
Wed Oct 14 13:07:05 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019,
Wed Oct 14 13:07:05 2020 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10,
Wed Oct 14 13:07:05 2020 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.,
Wed Oct 14 13:07:05 2020 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts,
Wed Oct 14 13:07:05 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]86.107.98.194:1194,
Wed Oct 14 13:07:05 2020 Attempting to establish TCP connection with [AF_INET]86.107.98.194:1194 [nonblock],
Wed Oct 14 13:07:06 2020 TCP connection established with [AF_INET]86.107.98.194:1194,
Wed Oct 14 13:07:06 2020 TCP_CLIENT link local: (not bound),
Wed Oct 14 13:07:06 2020 TCP_CLIENT link remote: [AF_INET]86.107.98.194:1194,
Wed Oct 14 13:07:06 2020 [vpnserver] Peer Connection Initiated with [AF_INET]86.107.98.194:1194,
Wed Oct 14 13:07:07 2020 TUN/TAP device tun0 opened,
Wed Oct 14 13:07:07 2020 /sbin/ip link set dev tun0 up mtu 1500,
Wed Oct 14 13:07:07 2020 /sbin/ip addr add dev tun0 10.8.0.3/24 broadcast 10.8.0.255,
Wed Oct 14 13:07:07 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,
Wed Oct 14 13:07:07 2020 Initialization Sequence Completed,
W: [pulseaudio] main.c: This program is not intended to be run as root (unless --system is specified).,
14/10/2020 13:07:10 passing arg to libvncserver: -passwd,
14/10/2020 13:07:10 x11vnc version: 0.9.13 lastmod: 2011-08-10  pid: 51,
14/10/2020 13:07:10 Using X display :1,
14/10/2020 13:07:10 rootwin: 0x388 reswin: 0x200001 dpy: 0x9172b5e0,
14/10/2020 13:07:10 ,
14/10/2020 13:07:10 ------------------ USEFUL INFORMATION ------------------,
14/10/2020 13:07:10 X DAMAGE available on display, using it for polling hints.,
14/10/2020 13:07:10   To disable this behavior use: '-noxdamage',
14/10/2020 13:07:10 ,
14/10/2020 13:07:10   Most compositing window managers like 'compiz' or 'beryl',
14/10/2020 13:07:10   cause X DAMAGE to fail, and so you may not see any screen,
14/10/2020 13:07:10   updates via VNC.  Either disable 'compiz' (recommended) or,
14/10/2020 13:07:10   supply the x11vnc '-noxdamage' command line option.,
14/10/2020 13:07:10 ,
14/10/2020 13:07:10 Wireframing: -wireframe mode is in effect for window moves.,
14/10/2020 13:07:10   If this yields undesired behavior (poor response, painting,
14/10/2020 13:07:10   errors, etc) it may be disabled:,
14/10/2020 13:07:10    - use '-nowf' to disable wireframing completely.,
14/10/2020 13:07:10    - use '-nowcr' to disable the Copy Rectangle after the,
14/10/2020 13:07:10      moved window is released in the new position.,
14/10/2020 13:07:10   Also see the -help entry for tuning parameters.,
14/10/2020 13:07:10   You can press 3 Alt_L's (Left "Alt" key) in a row to ,
14/10/2020 13:07:10   repaint the screen, also see the -fixscreen option for,
14/10/2020 13:07:10   periodic repaints.,
14/10/2020 13:07:10 ,
14/10/2020 13:07:10 XFIXES available on display, resetting cursor mode,
14/10/2020 13:07:10   to: '-cursor most'.,
14/10/2020 13:07:10   to disable this behavior use: '-cursor arrow',
14/10/2020 13:07:10   or '-noxfixes'.,
14/10/2020 13:07:10 using XFIXES for cursor drawing.,
14/10/2020 13:07:10 GrabServer control via XTEST.,
14/10/2020 13:07:10 ,
14/10/2020 13:07:10 Scroll Detection: -scrollcopyrect mode is in effect to,
14/10/2020 13:07:10   use RECORD extension to try to detect scrolling windows,
14/10/2020 13:07:10   (induced by either user keystroke or mouse input).,
14/10/2020 13:07:10   If this yields undesired behavior (poor response, painting,
14/10/2020 13:07:10   errors, etc) it may be disabled via: '-noscr',
14/10/2020 13:07:10   Also see the -help entry for tuning parameters.,
14/10/2020 13:07:10   You can press 3 Alt_L's (Left "Alt" key) in a row to ,
14/10/2020 13:07:10   repaint the screen, also see the -fixscreen option for,
14/10/2020 13:07:10   periodic repaints.,
14/10/2020 13:07:10 ,
14/10/2020 13:07:10 Client Side Caching: -ncache mode is in effect to provide,
14/10/2020 13:07:10   client-side pixel data caching.  This speeds up,
14/10/2020 13:07:10   iconifying/deiconifying windows, moving and raising,
14/10/2020 13:07:10   windows, and reposting menus.  In the simple CopyRect,
14/10/2020 13:07:10   encoding scheme used (no compression) a huge amount,
14/10/2020 13:07:10   of extra memory (20-100MB) is used on both the server and,
14/10/2020 13:07:10   client sides.  This mode works with any VNC viewer.,
14/10/2020 13:07:10   However, in most you can actually see the cached pixel,
14/10/2020 13:07:10   data by scrolling down, so you need to re-adjust its size.,
14/10/2020 13:07:10   See http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching.,
14/10/2020 13:07:10   If this mode yields undesired behavior (poor response,,
14/10/2020 13:07:10   painting errors, etc) it may be disabled via: '-ncache 0',
14/10/2020 13:07:10   You can press 3 Alt_L's (Left "Alt" key) in a row to ,
14/10/2020 13:07:10   repaint the screen, also see the -fixscreen option for,
14/10/2020 13:07:10   periodic repaints.,
14/10/2020 13:07:10 X FBPM extension not supported.,
Xlib:  extension "DPMS" missing on display ":1".,
14/10/2020 13:07:10 X display is not capable of DPMS.,
14/10/2020 13:07:10 --------------------------------------------------------,
14/10/2020 13:07:10 ,
14/10/2020 13:07:10 Default visual ID: 0x21,
14/10/2020 13:07:10 Read initial data from X display into framebuffer.,
14/10/2020 13:07:10 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120,
Failed to read: session.ignoreBorder,
Setting default value,
Failed to read: session.forcePseudoTransparency,
Setting default value,
Failed to read: session.colorsPerChannel,
Setting default value,
Failed to read: session.doubleClickInterval,
Setting default value,
Failed to read: session.tabPadding,
Setting default value,
Failed to read: session.styleOverlay,
Setting default value,
Failed to read: session.slitlistFile,
Setting default value,
Failed to read: session.appsFile,
Setting default value,
Failed to read: session.tabsAttachArea,
Setting default value,
Failed to read: session.cacheLife,
Setting default value,
Failed to read: session.cacheMax,
Setting default value,
Failed to read: session.autoRaiseDelay,
Setting default value,
14/10/2020 13:07:10 ,
14/10/2020 13:07:10 X display :1 is 32bpp depth=24 true color,
14/10/2020 13:07:10 ,
14/10/2020 13:07:10 Autoprobing TCP port ,
14/10/2020 13:07:10 Autoprobing selected TCP port 5900,
14/10/2020 13:07:10 Autoprobing TCP6 port ,
14/10/2020 13:07:10 Autoprobing selected TCP6 port 5900,
14/10/2020 13:07:10 listen6: bind: Address already in use,
Failed to read: session.ignoreBorder,
14/10/2020 13:07:10 Setting default value,
Not listening on IPv6 interface.,
Failed to read: session.forcePseudoTransparency,
Setting default value,
Failed to read: session.colorsPerChannel,
Setting default value,
Failed to read: session.doubleClickInterval,
Setting default value,
Failed to read: session.tabPadding,
Setting default value,
Failed to read: session.styleOverlay,
Setting default value,
Failed to read: session.slitlistFile,
Setting default value,
Failed to read: session.appsFile,
Setting default value,
Failed to read: session.tabsAttachArea,
Setting default value,
Failed to read: session.cacheLife,
Setting default value,
Failed to read: session.cacheMax,
Setting default value,
Failed to read: session.autoRaiseDelay,
Setting default value,
14/10/2020 13:07:10 ,
14/10/2020 13:07:10 Xinerama is present and active (e.g. multi-head).,
14/10/2020 13:07:10 Xinerama: number of sub-screens: 1,
14/10/2020 13:07:10 Xinerama: no blackouts needed (only one sub-screen),
14/10/2020 13:07:10 ,
14/10/2020 13:07:10 fb read rate: 1233 MB/sec,
14/10/2020 13:07:10 fast read: reset -wait  ms to: 10,
14/10/2020 13:07:10 fast read: reset -defer ms to: 10,
14/10/2020 13:07:10 The X server says there are 10 mouse buttons.,
14/10/2020 13:07:10 screen setup finished.,
14/10/2020 13:07:10 ,
,
The VNC desktop is:      f465f3106d16:0,

**Comment by Venom1p** [comment]
This is the correct log?

**Comment by Venom1p** [comment]
is there anyone who has had this problem and somehow managed to solve it?

**Comment by Venom1p** [comment]
hi, i still have this problem can someone tell me something?

**Comment by CendioOssman** [comment]
I'm afraid we're a bit swamped with other things right now. We'll try to get back to you soon and see what we can do next.

**Comment by Venom1p** [comment]
ok thanks
