### ISSUE TITLE
noVNC embedded in HTTPS 

### ISSUE THREAD

**Issue by cihantunc** [novnc/noVNC#1478]
Hi. My problem/request might be a bit different. I have multiple VMs with dynamic IPs and I am trying to reach them through noVNC embedded inside a webpage. I can access them through noVNC if the browser has the certificate. However, since they have dynamic IPs and noVNC is embedded within a website with HTTPS, it never asks for the certificate exception. Therefore, I cannot access the machines. Is there a possibility that I can have noVNC (with websockify) working embedded?

**Comment by CendioOssman** [comment]
I'm afraid I don't quite understand what you mean. Are you trying to use HTTPS using just IPs? That's generally a bad idea and will never work reliably. One example is that there is no way to add exceptions for just WebSocket connections. Exceptions also mean you lose most of the point of HTTPS so you might as well just skip encryption.

I would suggest using the server you are serving noVNC from as a proxy for the other machines so you can have a stable name and certificate.

**Comment by kosmasgiannis** [comment]
Hi @cihantunc,

if your VMs get their IP from a predefined range, register them in your DNS for example like vm-NNN-NNN-NNN-NNN.yourdomain.com and get and install a wildcard certificate. It worked for me on a similar situation.

I hope it helps.
