### ISSUE TITLE
websock.js:185 WebSocket connection to<server> failed: Received a broken close frame containing a reserved status code.

### ISSUE THREAD

**Issue by hdijkema** [novnc/noVNC#1479]
**Describe the bug**

I'm running Xtightvnc and the websockify proxy behind an apache proxy.  It works find when I work local, however, when I try to connect from an other location (I tried multiple), I often get the following connection problem:

![Naamloos](https://user-images.githubusercontent.com/745693/96895903-3a8a0480-148d-11eb-9e2d-1bf132cd0354.png)

**To Reproduce**
1. Go to the website that proxies to the server in the backend
2. Click on connect
3. It produces the error

**Expected behavior**
I'd expect a normal connection to my VNC desktop.

**Screenshots**
See above.

**Client:**
 - OS: Windows 10 / Server 
 - Browser: Chrome
 - Browser version: 86.0.4240.75 (Officiële build) (64-bits)

**Server (please complete the following information):**
 - noVNC version: 1.2.0
 - VNC server: Xvnc version TightVNC-1.3.9
  (/usr/bin/vncserver :1 -geometry 1600x900 -depth 24)
 - WebSocket proxy: websockify
  (utils/launch.sh --vnc localhost:5901 )

**Additional context**

_Apache configuration:_

```conf
<VirtualHost *:80>
    ServerName vnc.domain.org
    ServerAdmin hans@domain.org

    ErrorLog ${APACHE_LOG_DIR}/vnc-error.log
    CustomLog ${APACHE_LOG_DIR}/vnc.log combined

    Redirect permanent / https://vnc.domain.org/
</VirtualHost>

<VirtualHost *:443>
    ServerName vnc.domain.org
    ServerAdmin hans@domain.org
    SSLEngine On
    SSLCertificateFile  /etc/letsencrypt/live/vnc.domain.org/cert.pem
    SSLCertificateKeyFile  /etc/letsencrypt/live/vnc.domain.org/privkey.pem
    ErrorLog ${APACHE_LOG_DIR}/vnc-error.log
    CustomLog ${APACHE_LOG_DIR}/vnc.log combined

    ProxyPreserveHost On
    ProxyRequests Off

    #RewriteEngine On
    #RewriteCond %{HTTP:Upgrade} =websocket [NC]
    #RewriteRule /(.*)           ws://backend.server.home:6080/$1 [P,L]
    #RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    #RewriteRule /(.*)           http://backend.server.home:6080/$1 [P,L]

    DocumentRoot /data/www/vnc
    <Directory "/data/www/vnc">
            AllowOverride All
            Require all granted
            Options -Indexes
    </Directory>

    ProxyPass "/ssh" "http://localhost:4200/"  retry=3 flushpackets=on
    ProxyPassReverse "/ssh" "http://localhost:4200/" retry=3

    ProxyPass "/vnc" "http://backend.server.home:6080/"  retry=3 flushpackets=on
    ProxyPassReverse "/vnc" "http://backend.server.home:6080/" retry=3

    ProxyPass "/websockify" "ws://backend.server.home:6080/websockify" retry=3 flushpackets=on
    ProxyPassReverse "/websockify" "ws://backend.server.home:6080/websockify" retry=3
</VirtualHost>
```

**Comment by CendioOssman** [comment]
If it works without Apache as a proxy then unfortunately it's not something we can help you with. We do not have any expertise in how Apache should be set up. So either ask on our mailing list if there is some other user that knows, or contact Apache and see if they can help.

**Comment by JialuZhang** [comment]
@hdijkema @CendioOssman 

In your configuration file,
```
#RewriteEngine On
#RewriteCond %{HTTP:Upgrade} =websocket [NC]
#RewriteRule /(.*)           ws://backend.server.home:6080/$1 [P,L]
#RewriteCond %{HTTP:Upgrade} !=websocket [NC]
#RewriteRule /(.*)           http://backend.server.home:6080/$1 [P,L]
```
is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".

This would be a possible solution:

```
RewriteEngine Off
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           ws://backend.server.home:6080/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           http://backend.server.home:6080/$1 [P,L]
```

Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
