### ISSUE TITLE
Clipboard How to use, config always fails

### ISSUE THREAD

**Issue by xiongchao902** [novnc/noVNC#1480]
Clipboard sent successfully. Virtual machine (KVM) cannot be used

**Comment by CendioOssman** [comment]
Please fill out the issue bug report properly or we cannot help you out.

**Comment by xiongchao902** [comment]
OS: win10
Browser: chrome
Browser version: 56

Server (please complete the following information):
noVNC version: 1.0.0
VNC server: [e.g. QEMU,]
WebSocket proxy: [e.g. websockify]

**Comment by xiongchao902** [comment]
> Please fill out the issue bug report properly or we cannot help you out.

Does KVM require special configuration

**Comment by CendioOssman** [comment]
I'm afraid QEMU/KVM doesn't have any clipboard support AFAIK. Please have a word with them and see if that is something that is in the plans.
