### ISSUE TITLE
local scaling mode flickers

### ISSUE THREAD

**Issue by rgl** [novnc/noVNC#1484]
**Describe the bug**

When I enable the local scaling mode, the image flickers as can be seen bellow.

Please note that when the scaling mode is disabled, there is no flicker.

**Screenshots**

![novnc-flicker](https://user-images.githubusercontent.com/43356/97536952-dfd53900-19b5-11eb-8677-4cb5129715a7.gif)

**Client (please complete the following information):**

 - OS: Ubuntu 20.04
 - Browser: chrome
 - Browser version: 86.0.4240.111

**Server (please complete the following information):**

 - noVNC version: 1.1.0 (as bundled in proxmox 6.2-12)
 - VNC server: QEMU
 - WebSocket proxy: no idea, sorry.

**Comment by CendioOssman** [comment]
I'm afraid that is a chrome bug that we can do nothing about (see #1469). Please add your vote to the Chrome bug and unfortunately you'll have to use another browser until they can fix it.

**Comment by rgl** [comment]
Sorry for the duplicate issue... I did search in the closed issue, but failed to find #1469.

I voted on the chrome issue.

Thank you!
