### ISSUE TITLE
Incosistent timeout

### ISSUE THREAD

**Issue by nikosp77** [novnc/noVNC#1486]
When the connection to the vnc server is interrupted there is a difference in the behaviour based on the type of interruption.

If there is somewhere a parameter (or possibly a hack) to change timeout it would help a lot!

The problem is that if the Wi-Fi fails (you can simulate it by turning off your wifi router) then the timeout takes about 17 minutes (it seems to be 1038 seconds). If on the other hand I suddenly close the web-browser tab, or I turn off the laptops wifi then it's a matter of a few seconds. It also takes seconds, if you have a network cable plugged in and you suddenly pull it off. This is a problem because it looks like Gnome 3 does not allow a user to login twice, so users are forced to wait 17 minutes to continue working.

Is there a timeout parameter?

The installation is CentOS 8, with Gnome 3 classic, novnc-1.1.0-6, python3-websockify-0.9.0-1.
running via Xvnc
Browser Firefox 82

Below is the output of /var/log/messages in each of these cases (I have striped time stamps and pids) and you can see that websockify is reporitng a timeout.

when closing browser tab:
----------------------------------
	dbus-run-session: X connection to 127.0.0.1:1 broken (explicit kill or server shutdown).
	journal: gnome-shell: Fatal IO error 11 (Resource temporarily unavailable) on X server 127.0.0.1:1.
	journal: gsd-keyboard: Fatal IO error 11 (Resource temporarily unavailable) on X server 127.0.0.1:1.
	gnome-session-binary[511082]: WARNING: App 'org.gnome.SettingsDaemon.Keyboard.desktop' exited with code 1
	MyApp.desktop: X connection to 127.0.0.1:1 broken (explicit kill or server shutdown).

laptop disconnect (go to settings and choose disconnect):
----------------------------------------------------------------------------
	websockify: handler exception: [Errno 104] Connection reset by peer
	journal: gnome-shell: Fatal IO error 11 (Resource temporarily unavailable) on X server 127.0.0.1:1.
	MyApp.desktop: X connection to 127.0.0.1:1 broken (explicit kill or server shutdown).

wifi failure (e.g. turn off the wifi router):
--------------------------------------------------
	websockify: handler exception: [Errno 110] Connection timed out
	journal: gnome-shell: Fatal IO error 11 (Resource temporarily unavailable) on X server 127.0.0.1:0.
	gnome-session-binary: WARNING: App 'org.gnome.SettingsDaemon.Keyboard.desktop' exited with code 1
	gnome-session: gnome-session-binary: WARNING: App 'org.gnome.SettingsDaemon.Keyboard.desktop' exited with code 1
	gnome-session: gnome-session-binary: WARNING: App 'org.gnome.SettingsDaemon.Color.desktop' exited with code 1
	gnome-session: gnome-session-binary: WARNING: App 'org.gnome.SettingsDaemon.MediaKeys.desktop' exited with code 1
	gnome-session: gnome-session-binary: WARNING: App 'org.gnome.SettingsDaemon.Power.desktop' exited with code 1
	gnome-session: gnome-session-binary: WARNING: App 'org.gnome.SettingsDaemon.Clipboard.desktop' exited with code 1
	gnome-session: gnome-session-binary: WARNING: App 'org.gnome.SettingsDaemon.Wacom.desktop' exited with code 1
	journal: gsd-keyboard: Fatal IO error 11 (Resource temporarily unavailable) on X server 127.0.0.1:0.
	gnome-session-binary: WARNING: App 'org.gnome.SettingsDaemon.Color.desktop' exited with code 1
	journal: gsd-color: Fatal IO error 11 (Resource temporarily unavailable) on X server 127.0.0.1:0.
	gnome-session-binary: WARNING: App 'org.gnome.SettingsDaemon.MediaKeys.desktop' exited with code 1
	journal: gsd-media-keys: Fatal IO error 11 (Resource temporarily unavailable) on X server 127.0.0.1:0.
	gnome-session-binary: WARNING: App 'org.gnome.SettingsDaemon.Power.desktop' exited with code 1
	journal: gsd-power: Fatal IO error 11 (Resource temporarily unavailable) on X server 127.0.0.1:0.
	gnome-session-binary: WARNING: App 'org.gnome.SettingsDaemon.Clipboard.desktop' exited with code 1
	journal: gsd-clipboard: Fatal IO error 11 (Resource temporarily unavailable) on X server 127.0.0.1:0.
	gnome-session-binary: WARNING: App 'org.gnome.SettingsDaemon.Wacom.desktop' exited with code 1
	journal: gsd-wacom: Fatal IO error 11 (Resource temporarily unavailable) on X server 127.0.0.1:0.
	journal: gsd-xsettings: Fatal IO error 11 (Resource temporarily unavailable) on X server 127.0.0.1:0.
	MyApp.desktop: X connection to 127.0.0.1:0 broken (explicit kill or server shutdown).

**Comment by CendioOssman** [comment]
I'm afraid this is a server issue, not a noVNC one. We can't affect what the server does if the network is down.

That said, this is generally an operating system issue. You don't normally want to drop connection just because the network has some (hopefully temporary) problems. You'll have to check if you can force a TCP heartbeat for all connections.

If you have something updating the screen contents on the server that should also help. It is much faster at detecting network issues if there is actually some data sent.
