### ISSUE TITLE
Korean Keyboard not working

### ISSUE THREAD

**Issue by holamisa** [novnc/noVNC#1489]
**Describe the bug**
When I try to "change the language of keyboard?" like first using english then changing to korean stuff...
When I press the button is doesn't change and only way to change to Korean is to press the button on the window task bar.

**To Reproduce**
1. Just press the language change button "한/영" key.

**Expected behavior**
When pressing that key, it should allow me to type english to korean and vise versa

**Screenshots**
![ㅁ](https://user-images.githubusercontent.com/22790193/98611748-e066bb80-2335-11eb-99da-2f7c596b911e.jpg)

**Client (please complete the following information):**
 - OS: Window
 - Browser: Chrome
 - Browser version: 86.0.4240.111

**Server (please complete the following information):**
 - noVNC version: 1.2.0
 - VNC server: UltraVNC
 - WebSocket proxy: Websockify

**Additional context**
I've searched for some solutions for this problem,, some people say change XK_Kanji to XK_Hangul but still doesn't work for me.

**Comment by CendioOssman** [comment]
Input methods and remote desktops is a bit of a mess unfortunately, so we need to understand your case a bit better.

When you say you press a button on the window task bar, is that on the client or in the session? Could you attach a screen shot?

And how is the keyboard configured on the client, and how is it configured in the session?

**Comment by CendioOssman** [comment]
No response. Closing.
