### ISSUE TITLE
Snap returns 404 for --web options due to missing snap file interface

### ISSUE THREAD

**Issue by ZainlessBrombie** [novnc/noVNC#1491]
**Describe the bug**
The novnc-snap `--web` option does not work at all.

**To Reproduce**
Install snap novnc and download a version you would like to serve. This may sound redundant, but one may want to add files to the web-root.

**Expected behavior**
novnc uses the directory that was provided.

**Client (please complete the following information):**
Does not apply

**Server (please complete the following information):**
 - noVNC version: 1.2.0
 - VNC server: does not apply
 - WebSocket proxy: websockify

**Additional context**
The websockify server only serves a 404 not found. strace shows that it is getting Permission Denied for the dir access.
This is because the snap confines it to its own directory.

**Comment by CendioOssman** [comment]
The snap is meant to be used self contained and not as a general web server. So I don't think this is something that is suitable to change, unfortunately.

**Comment by ZainlessBrombie** [comment]
Alright :)
