### ISSUE TITLE
same domain, multiple nonvc tabs with different websocket paths issue

### ISSUE THREAD

**Issue by desix75** [novnc/noVNC#1494]
Hi I am using a particular setup with websockify novnc + reverse proxy with nginx
so I can handle multiple vnc sessions to different devices, each url is in the form

https://domain.tld/randomString/vnc.html?path=/randomString/websockify

If I connect to two different urls in the same browser opening a tab like:

1. Session1  ->`https://domain.tld/randomString1/vnc.html?path=/randomString1/websockify`
2. Session2 ->`https://domain.tld/randomString2/vnc.html?path=/randomString2/websockify`

I can successfully connect to both devices
in nginx for each  SessionX and /randomStringX/  I avoid any kind of cache
with settings like the following:
```
location  /randomStringX/ {
	proxy_pass https://novnc.internal:590X/;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "Upgrade";
	proxy_read_timeout 61s;
	proxy_no_cache 1;
	proxy_cache_bypass 1;
	proxy_buffering off;
	proxy_cache off;
        add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        expires off;
}
```

The problem arise if click on disconnect in both sessions keeping the browser tabs opened, the latest disconnected **path** parameter is than used in both sessions/tabs, so when I reconnect I am forwarded to the wrong session,  if I reload both tab the path is correct, closing and reopening the tab is fine too..

**Expected behavior**
The path parameter in the path should be honored unless **human override** within the toolbar, each tab has to be independent.

**Server (please complete the following information):**
 - noVNC version: Ubuntu 20.04 with novnc  1.0.0-2
 - VNC server: TightVNC
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
This should already be fixed in 1.1.0 so please try an updated noVNC and you should be fine.
