### ISSUE TITLE
Question : noVNC without websocket (http get/post only)?

### ISSUE THREAD

**Issue by Adnaram** [novnc/noVNC#1497]
Hi, 

I'm looking for a software like noVNC that do not use websocket. The firewall of my company is very restrictive and only allow http request (get, post, ect). Every other communication protocol is blocked. How can I acces a VNC server from a web browser with these conditions?

Thanks,

**Comment by CendioOssman** [comment]
I'm not aware of any current system that doesn't use WebSockets. Using normal requests is very inefficient and messy. WebSockets **is** HTTP though, so perhaps your firewall can be configured so this works?
