### ISSUE TITLE
Documentation is wrong. 

### ISSUE THREAD

**Issue by asavah** [novnc/noVNC#1506]
**Describe the bug**
Documentation https://github.com/novnc/noVNC/blob/master/docs/EMBEDDING.md states that in order to prebuild noVNC one has to run
```
Run ./utils/use_require.js --with-app --as commonjs
```
Which is no longer true 
```
./utils/use_require.js --with-app --as commonjs
error: unknown option '--with-app'
```

**To Reproduce**
1. Try building this project ...

**Expected behavior**
No errors

**Screenshots**

**Client (please complete the following information):**
- N/A
- 
**Server (please complete the following information):**
 - noVNC version: current master

**Additional context**
Additionally  no `build` directory is produced after running `./utils/use_require.js` and the documentation states that it should be there.

Please update the documentation to match the current state of the code.

**Comment by CendioOssman** [comment]
Ah, right. This should have been adjusted in #1477. Fixed with #1508.
