### ISSUE TITLE
Using certificate is problematic on encryption

### ISSUE THREAD

**Issue by etmpoon** [novnc/noVNC#1507]
**Is your feature request related to a problem? Please describe.**
Yes, it's related to a problem. Browser does not prompt to accept certificate when noVNC web client connects to a noVNC service that may have different certificate. For example, the noVNC client web page can be https://y.y.y.y:443 but the noVNC connection is x.x.x.x:4430. As a simple use case, the noVNC web client and service are host on the same server, they must have different ports. Another use case is that when you use the web client on novnc.com to connect another noVNC service. When a browser opens a noVNC web client, it only stores the certificate of that web page. When you try to connect a noVNC service using another certificate from the web client, it could fail if the certificate is self-signed or requires manual exception. In order to use encrypted connection, most likely you need a web server to host the noVNC client to get the browser save the correct certificate by visiting the web page before you can connect the noVNC service. It could also cause problem on renewing a certificate which the browser must visit a web page having the same address and certificate of the noVNC service to get it stored before the browser can connect the service.

**Describe the solution you'd like**
Many VNC products in the market support certain self implemented encryption methods not require certificate. Please provide encryption options not require certificate for secure connection.

**Describe alternatives you've considered**
Encrypted connection is necessary for nowadays. The simplest solution would be the Javascript client trigger the browser to use and store the noVNC service certificate on making a connection but seems not possible. All the other alternative solutions like the noVNC service itself provides the web client page are too complicated.

**Additional context**
No

**Comment by CendioOssman** [comment]
I'm assuming these are pages with broken certificates where you need to tell your browser to make an exception, as otherwise everything should work perfectly fine even with different hosts and port.

Unfortunately the browsers do indeed not provide any way of handling this and will just reject such connections. Have you tried filing a feature request with them for this?

Encryption does not give much security without some way of authenticating that it's the correct server we're connecting to. Generally this means a trusted certificate. What alternatives have you seen that we could look at?

**Comment by etmpoon** [comment]
I am not very familiar with how the browser identifies certificates. I
tried free SSL certificate authority like zerossl. The certificate uses IP
as the domain which is also the noVNC connection URL. I don't know why it
needs an exception. I think you are correct that the problem only happens
when exception is needed. I understand that certificates also prove the
destination in addition to encryption. However, for not formal uses like
remoting a personal desktop, it could be too complex for many people to set
up a certificate. That's why a simple encryption option could work for
certain cases.

Encryption can't do signing and no proof of destination. It can't replace
the current SSL connection method and it's not an alternative for the
current method. I mean it can be an additional feature for certain cases
when people only need to encrypt the connection.

**Comment by etmpoon** [comment]
Another reason to have non SSL encryption is that most companies enforce
SSL runs on port 443. To use noVNC encryption, the service must be
listening to port 443 and the router must be set up to route traffic to the
port 443. That seems to conflict sometimes when you want to remote a
computer that is also used to access HTTPS sites. HTTPS sites load very
slowly and frequently timeout on the remote computer.

Thanks,
Eric

**Comment by CendioOssman** [comment]
> However, for not formal uses like remoting a personal desktop, it could be too complex for many people to set up a certificate. That's why a simple encryption option could work for certain cases.

Encryption can also provide a false sense of security for users that don't know the details, which is often worse than no security at all.

Unfortunately I don't see much we can do here. noVNC is fundamentally a browser application. So we have to go along with what the browsers think is best. And they are heavily pushing HTTPS with valid certificates for everything to work correctly. We're not really in a position to go against that. :/

I agree that it can be difficult for users to get going with certificates. But it's more feasible to attack that difficulty instead. We could include more guides and links to relevant information in our wiki.

(We're also not a web server, so it's unclear how much of setting up certificates falls under this project.)
