### ISSUE TITLE
Bug with broken dependence

### ISSUE THREAD

**Issue by exe01** [novnc/noVNC#1513]
You have '*' versions in package.json. Please set strict versions.

There was a problem with the package 'commander' (doesn't parse options). Works fine with version '6.2.1'.

> ./utils/use_require.js --as commonjs --with-app
> Error: you must specify an import format to generate compiled noVNC libraries

It is also necessary to notify the developers "commander".

**Comment by CendioOssman** [comment]
We don't specify the versions as we don't want to start lagging behind.

It is working fine here for me with the current code and commander 7.0.0. Which commit of noVNC are you using? And does it work if you use the current `master`?

**Comment by exe01** [comment]
I check out master and its working fine. 
But if i use tag v1.2.0 it isn't working

git checkout tags/v1.2.0

**Comment by CendioOssman** [comment]
Since that is already tagged and released there isn't much we can do about it, unfortunately. Once a new release is out it should work fine right away.
