### ISSUE TITLE
very long screen

### ISSUE THREAD

**Issue by connected201** [novnc/noVNC#1514]
hi, i installed tiger vnc server (latest version) on kali linux, and install novnc on kali too, but when i connect, i see very long screen , how to fix it?.
p.s, sorry for my english.

![jq7RuZO3Nv](https://user-images.githubusercontent.com/20506433/105483439-862d9380-5cb2-11eb-92f5-865caaa7855c.png)

**Comment by CendioOssman** [comment]
That looks like x11vnc and their peculiar caching feature. Are you really sure that is TigerVNC?
