### ISSUE TITLE
Regarding the previously reported bug (mouse cursor blink)

### ISSUE THREAD

**Issue by tofutree23** [novnc/noVNC#1516]
**Describe the bug**
follow the previous issue #1440 
Mouse cursor blink

**To Reproduce**
Use noVNC with UltraVNC server

**Expected behavior**
Just show through Server's mouse cursor.

**Screenshots**

**Client (please complete the following information):**
 - OS: Windows / MacOS
 - Browser: chrome
 - Browser version: 83

**Server (please complete the following information):**
 - noVNC version: recent
 - VNC server: UltraVNC 1.2.2.4
 - WebSocket proxy: DataChannel

**Additional context**
I think I found a solution to the problem I reported before.

I commented the [entire line](https://github.com/novnc/noVNC/blob/5a0cceb8156926fe125ca541adae60754ecd3698/core/rfb.js#L1767) and the server's mouse cursor began to appear through noVNC as it was.

Is it necessary? how can I turn off that line of fuction, without modify your codes?

Sincerely yours.

**Comment by CendioOssman** [comment]
Removing that line removes support for client side cursor. So you're side-stepping any bugs that exist in the server.

We have no options for that, and I'm afraid we never will. It isn't really feasible for us to have settings to work around other people's bugs as there simply would be no end to that. So we're still at the same place where you'd need to report this to @UltraVNC. Their maintainer seems responsive so you should be able to get help there.
