### ISSUE TITLE
RFB "003.005" connection error

### ISSUE THREAD

**Issue by furkan-kara** [novnc/noVNC#1517]
**Describe the bug**
I try to connect [LS eXP60](https://www.ls-electric.com/products/view/Smart_Automation_Solution/HMI/XGT_Panel/eXP_Series). 
This device RFB version is "003.005" and it uses UltraVNC. If I try to connect to device via RealVNC, it gives warning  as 
```
This VNC-compatible Server software is non-standard, and may fail to
work.
```
 but it connect. And I try add this RFB version to rfb.js file as 
```
             case "003.005":
                this._rfbVersion = 3.3;
                break; 
```
after this change, connection is success but screen is not totaly shown.

Any ideas what might have caused it?
Thank you.

**Screenshots**
![noVNCScreen](https://user-images.githubusercontent.com/31926140/106737119-5aea6300-6627-11eb-948c-8d6412962994.png)

**Client **
 - OS: Ubutu
 - Browser: Chrome, Firefox
 - Browser version: [ `87.0.4280.141 ` ,`84.0.2`]

**Server:**
 - noVNC version: master
 - VNC server: UltraVNC
 - WebSocket proxy:  websockify

**Comment by CendioOssman** [comment]
Unfortunately what RealVNC tells you is correct. That is an invalid version number. So this device is likely not properly compatible with VNC. If you can find some documentation on what protocol it expects it might be possible to support, but until then I'm afraid there isn't much we can do.

**Comment by furkan-kara** [comment]
> So this device is likely not properly compatible with VNC.

But this device works with RealVNC properly. Doesn't it then mean that there is no problem with VNC?

**Comment by CendioOssman** [comment]
It's possible but given history it is highly unlikely. We've seen devices like this before and at best they make sure they work with one specific client without actually supporting the protocol properly. The fact that it sends and invalid version number is enough to say that it is not a VNC compliant device and trying to figure out exactly how broken it is is unfortunately not practical for us.
