### ISSUE TITLE
Special characters from non-US keyboards are not working

### ISSUE THREAD

**Issue by anaich** [novnc/noVNC#1518]
Special characters from non-US keyboards are not working. For example, Ö from turkish keyboard doesn't work, even though keymap on the virtual machine are configured correctly.

**Comment by CendioOssman** [comment]
Please fill out the bug report form properly so we can see what your environment looks like.

**Comment by anaich** [comment]
_#### Issue description_

Special characters from non-US keyboards are not working. For example, Ö from turkish keyboard doesn't work, even though keymap on the virtual machine are configured correctly.

_#### Steps to reproduce the issue_

1. Create a RHEL7 VM on Xen Hypervisor with keymap=tr in vm.cfg file
2. Open a VNC session for the VM (NoVnc 1.1.0 is embedded in our application and works using RFB)
3. Hit a special characters from non-US keyboard e.g. set local keyboard layout to Turkish
4. Nothing get entered on the VM


_#### What's the expected result?_

- Characters from non-US keyboards, should work on NoVnc 1.1.0


_#### What's the actual result?_

- Nothing get printed on the VM, when special characters from non-US keyboard are hit from local keyboard


_Please note, it works perfectly for US English keyboard._

**Comment by CendioOssman** [comment]
Hypervisors usually have problems dealing with keyboards over VNC, so this is likely an issue there unfortunately. But let's have a look in the logs and see what it says.

Please turn up the logging in noVNC and you should get some text in the browser console for each key event. What does it say for the misbehaving key?

**Comment by anaich** [comment]
[console-export-2021-2-19_14-30-0.log](https://github.com/novnc/noVNC/files/6008739/console-export-2021-2-19_14-30-0.log)

The debug logs are attached herewith.

In the above logs if you see, for keysym-220 it shows as BracketRight(though correct for a Mac keyboard) and doesn't print anything on the VM prompt. But it's actually ü in a Turkish keyboard.

**Comment by CendioOssman** [comment]
Unfortunately it seems like noVNC is doing the correct thing. `BracketRight` is the name of the physical key, so that is correct. And 220 is "Ü", so that is also correct.

This means the bug is in your server, and not in noVNC. I'm afraid you'll have to report the issue to them and they'll have to take over here.
