### ISSUE TITLE
noVNC pepboys van mobile 6660 stgr105

### ISSUE THREAD

**Issue by fcasasola** [novnc/noVNC#1524]
Hi I'm Fernando the mobile manager for the pepboys mobile. We use the noVnc to run shop x which is essentially were we write our work orders and parts catalog. We been having issues for the last three days been calling pepboys IT to fix this but not avail. Error codes show password auth is a issue and disconnect or fail. Please we need up and running any advice would be greatly appreciated thanks

**Comment by CendioOssman** [comment]
If you don't have access to the servers, then I'm afraid it is unlikely we can be of much help. But let's have a look.

To start with I'd like you to fill you the form you bypassed so we can get an idea of what your environment looks like. Please copy that form in to a new comment here, or edit your original comment.

**Comment by CendioOssman** [comment]
No response. Closing.
