### ISSUE TITLE
resource suggestion

### ISSUE THREAD

**Issue by Slender1808** [novnc/noVNC#1526]
hello, it would be interesting to have the option of transmitting only a program window

**Comment by TclHttpd** [comment]
Check out Cloudtk https://wiki.tcl-lang.org/page/CloudTk. It uses novnc to display single X11 program in a browser. It runs on Linux64 or Raspberry Pi.

**Comment by Slender1808** [comment]
> Check out Cloudtk https://wiki.tcl-lang.org/page/CloudTk. It uses novnc to display single X11 program in a browser. It runs on Linux64 or Raspberry Pi.

thank you very much it was very useful, I didn't know this project
