### ISSUE TITLE
novnc fails with error: "The path /usr/bin/websockify exists, but /usr/bin/websockify/run either does not exist or is not executable."

### ISSUE THREAD

**Issue by cmonty14** [novnc/noVNC#1531]
**Describe the bug**
Starting novnc fails with error message pointing to websockify.
```
/usr/bin/novnc_server --listen 6080 --vnc localhost:5901
Warning: could not find self.pem
The path /usr/bin/websockify exists, but /usr/bin/websockify/run either does not exist or is not executable.
If you intended to use an installed websockify package, please remove /usr/bin/websockify.

```

**To Reproduce**
1. Install packages "novnc" and "xorg-x11-Xvnc-novnc" and all its dependencies
2. Execute command `/usr/bin/novnc_server --listen 6080 --vnc localhost:5901`
3. See error

**Expected behavior**
Starting novnc works w/o problems.

**Client (please complete the following information):**
 - OS: SUSE Linux Enterprise Server 15 SP2
 
**Server (please complete the following information):**
 - noVNC version: 1.0.0-1.17
 - VNC server: x11vnc 0.9.13-bp152.3.30
 - WebSocket proxy: python3-websockify 0.8.0-9.3.1

**Comment by CendioOssman** [comment]
Ehm... I don't recognize those packages, so I'm not sure it's something we can support. Where did you find them?

**Comment by cmonty14** [comment]
Any package is installed from official SUSE repository.

**Comment by CendioOssman** [comment]
Unfortunately there is something broken with their packaging. We have no idea how they indented for things to work, so we unfortunately can't really help out debugging it.

Please file a bug with SUSE and they can hopefully figure out what has gone wrong.
