### ISSUE TITLE
Keyboard layout not recognizing alt-gr

### ISSUE THREAD

**Issue by AndiLeni** [novnc/noVNC#1538]
**Describe the bug**
I have access to a proxmox based vm which I access via novnc.
Unfortunately, all keys which rely on `alt-gr` are not recognized. 
F.e. I press `alt-gr` and the `9`-key I expect to get `]`. Instead I get `9`.

Is it possible to change this behavior?

 - OS: Windows
 - Browser: Firefox
 - Browser version: 87.0

**Server (please complete the following information):**
 - noVNC version: can not say for sure, from firefox web tools: requests app.js version 1.1.0
 - VNC server: QEMU
 - WebSocket proxy: -

**Comment by samhed** [comment]
This usually works. Perhaps its a problem with your server. Could you try if this works with a different VNC viewer?

**Comment by Minor-Kontor** [comment]
We are having the same problem. It only occurs in Firefox. Sometimes it does work (about one in 30 times) but only intermittently.

The console shows an infinite recursion error in _checkAlt:

```
_checkAlt https://10.2.0.52:8006/novnc/app.js?ver=1.1.0-1:3429
_checkAlt https://10.2.0.52:8006/novnc/app.js?ver=1.1.0-1:3437
_checkAlt https://10.2.0.52:8006/novnc/app.js?ver=1.1.0-1:3429
_checkAlt https://10.2.0.52:8006/novnc/app.js?ver=1.1.0-1:3437
_checkAlt https://10.2.0.52:8006/novnc/app.js?ver=1.1.0-1:3429
```

3429 is `['AltLeft', 'AltRight'].forEach((code) => {`
and 3437 is `target.dispatchEvent(event);`

**Comment by CendioOssman** [comment]
Indeed. Please try the latest version and see how things work there. If there are still issues we can dig further, but let's try to avoid spending time on problems that hopefully are already fixed.

**Comment by Minor-Kontor** [comment]
@CendioOssman I was mistaken, the issue actually occurs in 1.2.0-3 too. There are no error messages in console.

**Comment by CendioOssman** [comment]
Okay. Please file a new issue and fill out the form so we get a clear picture of what you are using. Then we can continue from there.
