### ISSUE TITLE
Novnc lite keyboard event is not working initially

### ISSUE THREAD

**Issue by manuvakery1** [novnc/noVNC#1541]
**Is your feature request related to a problem? Please describe.**
Once we connect to an `OpenStack` instance using novnc (vnc_auto.html), one has to explicitly click on the terminal area before typing. This is little confusing

**Describe the solution you'd like**
Once novnc is connected user must be able to type immedialty

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by samhed** [comment]
That feels like an issue with how OpenStack have implemented noVNC, you should file an issue with them.
