### ISSUE TITLE
send ShiftLeft will open Caps Lock on

### ISSUE THREAD

**Issue by five00miles** [novnc/noVNC#1543]
**Describe the bug**
I want to send the ShiftLeft key to the server,but it will let the Caps Lock on,I dont know why?

this is my code:
```js
            rfb.sendKey(KeyTable.XK_Shift_L, "ShiftLeft", true);
            rfb.sendKey('a'.charCodeAt(0));
            rfb.sendKey(KeyTable.XK_Shift_L, "ShiftLeft", false);
```
After executing once,then refresh the page, the Caps Lock is on

**Client (please complete the following information):**
 - OS:  window10   64
 - Browser: chrome  
 - Browser version: 90.0.4430.72   64

**Server (please complete the following information):**
 - OS: CentOS 7.6 64
 - noVNC version: 1.2.0

**Comment by CendioOssman** [comment]
I'm afraid that must be an issue in your VNC server. We don't adjust the sent keys in any way, so if your code specified Shift then only that will be sent to the server.

Unfortunately I can't really say what might be going on the server as you skipped the details about what you're running there. Please try asking for help in the community for the server you are using.

**Comment by five00miles** [comment]
> I'm afraid that must be an issue in your VNC server. We don't adjust the sent keys in any way, so if your code specified Shift then only that will be sent to the server.
> 
> Unfortunately I can't really say what might be going on the server as you skipped the details about what you're running there. Please try asking for help in the community for the server you are using.

Ok,thank you very much!
And i also want to know that if my VNC server is right,when i use the following code, should it show 'A' ?
```js
rfb.sendKey(KeyTable.XK_Shift_L, "ShiftLeft", true);
rfb.sendKey('a'.charCodeAt(0));
rfb.sendKey(KeyTable.XK_Shift_L, "ShiftLeft", false);
```

**Comment by CendioOssman** [comment]
I'd say it should show a lower case "a" since that is what you are sending. VNC/RFB is very symbol oriented rather than keys. So it will assume that you want the upper/lower case that the client is sending. If you want an "A" I suggest you also send that.
