### ISSUE TITLE
The online demo version of the noVNC client shows an error: "Failed to connect to server".

### ISSUE THREAD

**Issue by ricardoreis** [novnc/noVNC#1546]
**Bug**
The official website https://novnc.com/ offers a link for demonstrating noVNC, but this is not working.

The online demo version of the noVNC client shows an error: "Failed to connect to server".

**To Reproduce**
1. Go to 'https://novnc.com/noVNC/vnc.html'
2. Click on 'Connect'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/104947/117152825-c364ef80-ad90-11eb-83f7-c1a19f396562.png)

**Comment by CendioOssman** [comment]
You need to provide your own WebSocket proxy and VNC server to use the demo. It's not something we have the possibility to provide any hosting for unfortunately. So please open the settings and specify your WebSocket proxy and it should be able to connect.

**Comment by xianshenglu** [comment]
Really sad. Actually, you can use vercel serverless functions to build a mock WebSocket. And it's free.
