### ISSUE TITLE
german keyboard issue

### ISSUE THREAD

**Issue by Jevingala** [novnc/noVNC#1548]
Hi,

Characters such as Ö, Ä, Ü, altgr+Q or umsch+3 do not work in a Linux vps even when vnc keymap is set to de or de-ch or en-us.
But they work fine when using the vps via SSH.

Client (please complete the following information):
 - OS: Windows 10
 - Browser:  Chrome (Version 90.0.4430.93) , Firefox (87)

Server (please complete the following information):
 - noVNC version: 1.1.0 
 - VNC server: QEMU
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
Please fill out the issue form completely so we can understand your setup.

**Comment by CendioOssman** [comment]
This is usually some issue with QEMU. Have you specified the `-k` argument to QEMU? If I remember correctly that causes more issues than it solves. So if it is enabled could you try without it? Only very old versions of noVNC require it.

**Comment by Jevingala** [comment]
We are using libvirt(4.5.0) to create kvm (Qemu 2.12) vps.
Vps config holds keymap='de' and the vps process on server shows that vps is started with -k de.
Removing keymap from vps config file is also not helpful.

**Comment by CendioOssman** [comment]
Can you confirm the QEMU command line when keymap setting is removed? What does it look like?

Please enable debug logging in noVNC settings dialog. Then you'll get output in your browser's web console for each key press. Please let us know what those say.

**Comment by Jevingala** [comment]
Hi,

Can you confirm the QEMU command line when keymap setting is removed? What does it look like?

>>   /usr/libexec/qemu-kvm -name guest=v1058,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-2116-v1058/master-key.aes -machine pc-i440fx-rhel7.6.0,accel=kvm,usb=off,dump-guest-core=off -cpu host,host-cache-info=on,l3-cache=off -m 500 -realtime mlock=off -smp 4,sockets=4,cores=1,threads=1 -uuid 3665889e-8ffc-46fd-a6f3-24851768bf9f -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=67,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -boot menu=on,strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -drive file=/dev/vg0/vsv1058-d81esacwbhkt2cga-npz1k2eool8uwybf,format=raw,if=none,id=drive-virtio-disk0,cache=none -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x5,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1,write-cache=on -netdev tap,fd=69,id=hostnet0,vhost=on,vhostfd=71 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=00:16:3e:da:e8:3d,bus=pci.0,addr=0x3 -device usb-tablet,id=input0,bus=usb.0,port=1 -vnc 127.0.0.1:569,password -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device AC97,id=sound0,bus=pci.0,addr=0x4 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x6 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on

No Keymap set in libvirt conf while Virtual keyboard was set to German(Germany) in my Windows 10 and tried with Chrome browser :

ö
Sending key (down): keysym 246, scancode 39
Sending key (up): keysym 246, scancode 39

ü
Sending key (down): keysym 252, scancode 26
Sending key (up): keysym 252, scancode 26

ä
Sending key (down): keysym 228, scancode 40
Sending key (up): keysym 228, scancode 40

Is this enough ?

**Comment by CendioOssman** [comment]
Yes, that is enough. Thank you.

Those log lines show that noVNC is sending both the correct keysym and scan code. So unfortunately that means the issue must be somewhere in the server. That is not something we can help out with though, so I'm going to have to ask you to get in touch with QEMU and see if they can help you out.
