### ISSUE TITLE
mailto handler proxy

### ISSUE THREAD

**Issue by rajeevn1** [novnc/noVNC#1549]
**Is your feature request related to a problem? Please describe.**
It is hard to share a website url, or sending a mail using the preferred email client by clicking on a mailto link.

**Describe the solution you'd like**
It will be nice to be able to email a url, or click on a mailto link and launching the mailto handler on the vnc server.

**Describe alternatives you've considered**
Currently I use cut and paste.

**Comment by samhed** [comment]
I'm not quite sure I understand.. Do you wish mailto links on your client to open noVNC and start the mail client on the VNC server? Or are we talking about applications on the server side?

**Comment by rajeevn1** [comment]
I wish mailto links on the browser to open noVNC and start the registered mailto handler on the server side, displaying the window in the noVNC tab.

**Comment by CendioOssman** [comment]
Alright. Unfortunately quite a few pieces are missing outside of noVNC to make that happen. There would need to be a way to associate mailto links with a web page, and there needs to be a VNC server that supports being told what command to run. Neither of which exist at the moment.

Unfortunately that means I'm going to close this issue for now as it is very uncertain when (or even if) those preconditions might be met. So for now I'm afraid you'll have to continue using the clipboard.
