### ISSUE TITLE
NoVnc Nginx Proxy Not Working

### ISSUE THREAD

**Issue by ommikadam** [novnc/noVNC#1550]
Unable to proxy via nginx for public network, the NoVnc page does not appear and it says vnc.html not found and there are no logs in 

Below are the details of stack
Nginx - 1.16.1
NoVnc - 1.2.0

Nginx Config

upstream vnc_proxy {
    server xxx.xxx.xxx.xxx:6081;
}

server {
    listen 80; # consider using 443, see below
    server_name abc.example.com;

    location /websockify {
          proxy_http_version 1.1;
          proxy_pass http://vnc_proxy/;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";

          # VNC connection timeout
          proxy_read_timeout 61s;

          # Disable cache
          proxy_buffering off;
    }

    location /vncws {
            index vnc.html;
            alias http://xxx.xxx.xxx.xxx:6081;
            try_files $uri $uri/ /vnc.html;
    }
}

Nginx Access logs:

159.89.166.119 - - [15/May/2021:16:46:11 +0530] "GET /_ignition/execute-solution HTTP/1.1" 404 3650 "-" "python-requests/2.18.4" "-"
170.130.187.2 - - [15/May/2021:17:21:05 +0530] "GET / HTTP/1.1" 200 4833 "-" "https://gdnplus.com:Gather Analyze Provide." "-"
103.25.170.146 - - [15/May/2021:17:40:09 +0530] "GET / HTTP/1.1" 200 4833 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" "-"
103.25.170.146 - - [15/May/2021:17:40:09 +0530] "GET /img/centos-logo.png HTTP/1.1" 200 3030 "http://abc.example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" "-"
103.25.170.146 - - [15/May/2021:17:40:09 +0530] "GET /img/html-background.png HTTP/1.1" 200 1801 "http://abc.example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" "-"
103.25.170.146 - - [15/May/2021:17:40:09 +0530] "GET /img/header-background.png HTTP/1.1" 200 82896 "http://abc.example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" "-"
103.25.170.146 - - [15/May/2021:17:40:09 +0530] "GET /favicon.ico HTTP/1.1" 404 153 "http://abc.example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" "-"
103.25.170.146 - - [15/May/2021:17:40:14 +0530] "GET /vnc.html HTTP/1.1" 404 153 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0" "-"

Nginx Error logs:

2021/05/15 17:40:09 [error] 17244#0: *4 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 103.25.170.146, server: abc.example.com, request: "GET /favicon.ico HTTP/1.1", host: "abc.example.com", referrer: "http://abc.example.com/"
2021/05/15 17:40:14 [error] 17244#0: *4 open() "/usr/share/nginx/html/vnc.html" failed (2: No such file or directory), client: 103.25.170.146, server: abc.example.com, request: "GET /vnc.html HTTP/1.1", host: "abc.example.com"

**Comment by CendioOssman** [comment]
I'm afraid we are not experts with nginx, so this isn't really something we can help you with. Please ask the nginx people what might be wrong with the setup.

**Comment by sergei202** [comment]
@ommikadam: Did you ever find a solution to this?

**Comment by sergei202** [comment]
For anyone else who runs into this problem and finds this page:

I got it to work by following this page: https://github.com/novnc/noVNC/wiki/Proxying-with-nginx

This is what my config looks like:

```
upstream vnc_proxy {
        server 127.0.0.1:6080;
}

server {
        server_name example.com;

        index index.html;

        gzip on;
        gzip_proxied any;
        gzip_types text/plain text/xml text/css application/x-javascript application/javascript;
        gzip_vary on;
        proxy_connect_timeout       300;
        proxy_send_timeout          300;
        proxy_read_timeout          300;
        send_timeout                300;
        location ~ /\.  {return 403;}

        root /apps/client/dist;
        location / {
                try_files $uri $uri/ /index.html;
        }
      

        location /vnc {
            index vnc.html;
            alias /home/sergei/noVNC/;
            try_files $uri $uri/ /vnc.html;
        }
        location /websockify {
                proxy_pass https://vnc_proxy;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_read_timeout 61s;
                proxy_buffering off;
        }

       listen 443 ssl;
       # SSL certs and stuff
}
```

**Comment by piwawa** [comment]
![image](https://github.com/novnc/noVNC/assets/46926496/c56c3b4b-8895-43e1-be61-6ec1705b5665)

![image](https://github.com/novnc/noVNC/assets/46926496/028e428b-9879-4057-acd8-9f00b4c78644)

```
upstream novnc {
    ip_hash; # 如果使用负载均衡，建议使用ip_hash
    server localhost:6080 max_fails=3 fail_timeout=10;
}

server {
    listen 443 ssl http2;
    server_name vnc.example.com;
    include ssl.conf;

	location /vnc {
		index vnc.html;
		alias /root/noVNC/;
		try_files $uri $uri/ /vnc.html;
    }

    location /websockify {
		proxy_http_version 1.1;
		proxy_pass http://novnc;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		# VNC connection timeout
		proxy_read_timeout 61s;
		# Disable cache
		proxy_buffering off;
    }
```
`example.com` is replaced by my domain

Not working for me...

**Comment by piwawa** [comment]
> @ommikadam: Did you ever find a solution to this?你有没有找到解决办法？

Hi, can u help me?
