### ISSUE TITLE
Mouse button selector in side bar does not work anymore

### ISSUE THREAD

**Issue by Joker13579** [novnc/noVNC#1553]
**Describe the bug**
In the side bar there was 1 button to select which mouse button should be used in an old version of novnc. This worked. You could toggle through left, middle, right and no button.

In the new version there are several buttons to select which mouse button should be used but none works. The left mouse button is always used.

**To Reproduce**
Use a touch screen not a physical mouse.
Use opera browser for android or privacy browser for android.

**Comment by Joker13579** [comment]
I just noticed, that if I make a long press on the same spot then this is interpreted as a right click.

**Comment by CendioOssman** [comment]
We are now using gestures to emulate the mouse on touch devices. I'm afraid no one has written up any documentation for it yet, but we use noVNC in our product ThinLinc so the documentation there should be valid for noVNC as well:

https://www.cendio.com/resources/docs/tag/client_gestures.html

**Comment by Joker13579** [comment]
Even if you have gestures now, the side bar is still not working, is it?

**Comment by CendioOssman** [comment]
The gestures are not configurable so the side bar no longer has any button related to this. Everything else in the side bar should work just as before though. So no, it is not possible to get the old behaviour.

**Comment by Joker13579** [comment]
@CendioOssman: Do you have a different side bar than I have? On my side bar there are 4 new buttons for controlling the mouse button.

**Comment by CendioOssman** [comment]
Then I'm afraid you must be running some modified version. The only thing in noVNC now is the panning button in the event that the session is larger than the browser window.
