### ISSUE TITLE
Mic/Speaker Support

### ISSUE THREAD

**Issue by sumeshir26** [novnc/noVNC#1555]
**Describe the bug**
Mic and Speaker cannot be accesed
**To Reproduce**

1. Go to any app which has audio and play it
2. Use mic in any mic app

**Expected behavior**
Mic/Speaker to work as usual

**Client (please complete the following information):**
 - OS: Chrome OS
 - Browser: Chrome
 - Browser version: 91

**Additional context**
Using noVNC on Gitpod

**Comment by CendioOssman** [comment]
Please see #302.
