### ISSUE TITLE
release v1.2.1 to fix regression in 1.2.0

### ISSUE THREAD

**Issue by JanZerebecki** [novnc/noVNC#1558]
**Is your feature request related to a problem? Please describe.**
Shortly after 1.2.0 a regression was fixed in it: https://github.com/novnc/noVNC/issues/1458
It would be useful to have a release that has no regression and doesn't have any backward incompatible changes.

A few commits later Internet Explorer support was dropped with other clean-ups and removals following. So a version before that would fit. All the commits before that fix bugs.

**Describe the solution you'd like**
Create release `v1.2.1` based on 499eee4d069c34bb986324771ff95d391550ac31

**Describe alternatives you've considered**
1) just let people live with the regression, there is a workaround
2) using a patched novnc version

**Comment by CendioOssman** [comment]
The playback tool is for development and testing, so I'm afraid I don't think we have time for making a bug fix release of just that. Developers are expected to be able to work with git to get the version they need.

A 1.3.0 is probably due though, so once there is some extra time we should probably get that sorted out.
