### ISSUE TITLE
No Connection, error 1006

### ISSUE THREAD

**Issue by zwick88** [novnc/noVNC#1561]
Hi, 

can someone help me pleas?

I habe a problem with noVNC. With noVNC i cannt connect do the VNC Server, but with RealVNC APP  i can. Here is a log. What's the problem?

```
>> RFB.constructor util.js:38:55
>> Display.constructor util.js:38:55
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0 util.js:38:55
Browser: gecko 19 util.js:38:55
Setting viewport to full display region util.js:38:55
<< Display.constructor util.js:38:55
>> Keyboard.allKeysUp util.js:38:55
<< Keyboard.allKeysUp util.js:38:55
<< RFB.constructor util.js:38:55
New state 'connecting', was ''. util.js:38:55
>> RFB.connect util.js:38:55
<< RFB.connect util.js:38:55
GETws://xxxxxxxxxx:yyyy/websockify
Firefox kann keine Verbindung zu dem Server unter ws://xxxxxxxxxx:yyyy/websockify aufbauen. websock.js:278:30
>> WebSock.onerror: [object Event] util.js:38:55
<< WebSock.onerror: [object Event] util.js:38:55
>> WebSock.onclose util.js:38:55
Failed when connecting: Failed to connect to server( (code: 1006)) util.js:44:55
New state 'disconnecting', was 'connecting'. util.js:38:55
>> RFB.disconnect util.js:38:55
>> Keyboard.allKeysUp util.js:38:55
<< Keyboard.allKeysUp util.js:38:55
<< RFB.disconnect util.js:38:55
New state 'disconnected', was 'disconnecting'. util.js:38:55
Clearing disconnect timer util.js:38:55
<< WebSock.onclose util.js:38:55
```

Alex

**Comment by CendioOssman** [comment]
Please fill out the complete issue form so we can understand your setup. Please also check what the logs in your WebSocket proxy and your VNC server say when this happens.

**Comment by zwick88** [comment]
Im sorry, 

where i can found the logs? Im only a user, no expert

**Comment by CendioOssman** [comment]
I'm afraid I can't really give you any suggestions as I don't know what servers you are running. If you're not the one who set them up then I'm afraid you might need to involve whoever manages them.

Given your errors your noVNC is also very ancient (pre-1.0). So I'm afraid it's not really something we can help you out with. Please try using something more current and hopefully things will work better, or at least give a more telling error message.

**Comment by zwick88** [comment]
I have installed the server. Ubuntu 18. On the other side is a embedded linux device with framebuffer vnc.

no i have installed a new VM with noVNC v 1.2.0. With this verison i cant connect to any server

![grafik](https://user-images.githubusercontent.com/23308452/124466116-91730800-dd96-11eb-83c6-e04c2343361e.png)

I have one cental noVNC server. From this Server i would connect do my VNC Servers.

**Comment by CendioOssman** [comment]
Might your servers perhaps be something old? We dropped support for non-standard stuff some versions ago, which unfortunately broke some older servers. If you check the server logs then there should hopefully be some error messages. You can also configure more logging in noVNC under settings.
