### ISSUE TITLE
vnc playback for recordings doesn't seems to be working 

### ISSUE THREAD

**Issue by Shuchivrat-M** [novnc/noVNC#1564]
I created the recordings directory and move one of the recordings to it. Thereafter I am trying to access the URL as follows: http://localhost:6080/tests/vnc_playback.html?data=testrecording.24

**Output -**
Loading testrecording.24...
Loaded 1146 frames
Converting...
Ready
Starting performance playback (fullspeed) [3 iteration(s)]
noVNC sent disconnected during iteration 1 frame 0

**Browser console shows following error -** 
Firefox can’t establish a connection to the server at wss://test/. websock.js:231:20

@samhed - When looked at the code written in playback.js, it has a run function with hardcoded websocket url "wss://test", not sure what is the exact purpose of this?
```
    run(realtime, trafficManagement) {
        // initialize a new RFB
        this._rfb = new RFB(document.getElementById('VNC_screen'), 'wss://test');
        this._rfb.viewOnly = true;
        this._rfb.addEventListener("disconnect",
                                   this._handleDisconnect.bind(this));
        this._rfb.addEventListener("credentialsrequired",
                                   this._handleCredentials.bind(this));
        this._enablePlaybackMode();

        // reset the frame index and timer
        this._frameIndex = 0;
        this._startTime = (new Date()).getTime();

        this._realtime = realtime;
        this._trafficManagement = (trafficManagement === undefined) ? !realtime : trafficManagement;

        this._running = true;
    }
```

**Comment by CendioOssman** [comment]
Sorry about that. It got broken in dbd519558c1efd98afd08126594efc334eb88dd6. Should be fixed in 7485e82b72d4d1356d95ecca2d109cbf49908b9d.
