### ISSUE TITLE
Installing snap packages on armhf

### ISSUE THREAD

**Issue by masrurakif62** [novnc/noVNC#1570]
Attempted to install noVNC 1.2.0 snap packages on Raspberry Pi (Debian 9) with the armhf architecture. Resulted to this error message: 'error: snap "novnc" is not available on stable for this architecture (armhf) but exists on other architectures (amd64).'

What I did so far (https://snapcraft.io/install/novnc/debian):
sudo apt update
sudo apt install snapd
sudo snap install core
sudo snap install novnc

**Screenshots**
![ScreenShot](https://user-images.githubusercontent.com/84686155/128043365-3bbecf93-d19f-4b4a-b4dd-3228001da217.png)

**Additional context**
Tried adding a foreign architecture (sudo dpkg --add-architecture amd64), did not result to any difference.

Must hold back some packages to prevent bricking the Raspberry Pi:
> sudo apt-mark hold raspbeerypi-bootloader
> sudo apt-mark hold raspbeerypi-kernel
> sudo apt-mark hold raspbeerypi-sys-mods

Additional details of the Raspberry Pi: https://www.element14.com/gateway

**Comment by MegaTKC** [comment]
> Attempted to install noVNC 1.2.0 snap packages on Raspberry Pi (Debian 9) with the armhf architecture. Resulted to this error message: 'error: snap "novnc" is not available on stable for this architecture (armhf) but exists on other architectures (amd64).'
> 
> What I did so far (https://snapcraft.io/install/novnc/debian):
> sudo apt update
> sudo apt install snapd
> sudo snap install core
> sudo snap install novnc
> 
> **Screenshots**
> ![ScreenShot](https://user-images.githubusercontent.com/84686155/128043365-3bbecf93-d19f-4b4a-b4dd-3228001da217.png)
> 
> **Additional context**
> Tried adding a foreign architecture (sudo dpkg --add-architecture amd64), did not result to any difference.
> 
> Must hold back some packages to prevent bricking the Raspberry Pi:
> 
> > sudo apt-mark hold raspbeerypi-bootloader
> > sudo apt-mark hold raspbeerypi-kernel
> > sudo apt-mark hold raspbeerypi-sys-mods
> 
> Additional details of the Raspberry Pi: https://www.element14.com/gateway

I am not sure / I have never tried running noVNC on Raspberry Pi OS or on a 32 bit operating system. But, I have tried it on Ubuntu Server arm64. If you want it to work you must install it without snap. `https://quicknotepadtutorial.blogspot.com/2020/04/installing-novnc-on-ubuntu-2004-lts.html`

**Comment by masrurakif62** [comment]
Thank you for assisting @MegaTKC , I appreciate it. I installed it without snap and was able to make progress.
