### ISSUE TITLE
NoVNC not working at all

### ISSUE THREAD

**Issue by FOREVEREALIZE** [novnc/noVNC#1574]
**Describe the bug**
NoVNC just connects to my TightVNC server but then it just does not show anything on the display nor do the keys or mouse work.

**To Reproduce**
1. Run TightVNC
2. Run NoVNC
3. Log into NoVNC
4. Voila

**Expected behavior**
NoVNC shows the display and allows me to use the mouse and keyboard.

**Client (please complete the following information):**
 - OS: Linux Mint Cinnamon
 - Browser: Firefox
 - Browser version: 91.0.1

**Server (please complete the following information):**
 - noVNC version: newest release @ 1/9/2021
 - VNC server: TightVNC
 - WebSocket proxy: Websockify

**Comment by samhed** [comment]
What exactly happens when "it does not show anything"? Perhaps a screenshot could be helpful, or a description of the state you end up in.

Are you getting any error messages? Please check both the VNC server logs and the browser console in Firefox.

**Comment by felixgames097** [comment]
The browser tells me that 192.168.1.102 took to long to respond

**Comment by vital987** [comment]
> **Describe the bug**
> NoVNC just connects to my TightVNC server but then it just does not show anything on the display nor do the keys or mouse work.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Run TightVNC
> 2. Run NoVNC
> 3. Log into NoVNC
> 4. Voila
> 
> **Expected behavior**
> NoVNC shows the display and allows me to use the mouse and keyboard.
> 
> **Client (please complete the following information):**
> 
> * OS: Linux Mint Cinnamon
> * Browser: Firefox
> * Browser version: 91.0.1
> 
> **Server (please complete the following information):**
> 
> * noVNC version: newest release @ 1/9/2021
> * VNC server: TightVNC
> * WebSocket proxy: Websockify

Mine works with x11vnc, try with it. And check your direct vnc connection before socketing it to novnc.

**Comment by CendioOssman** [comment]
@FOREVEREALIZE, can you describe your setup in a bit more detail? Which machines are involved, and with what IP addresses?

And could you share complete logs from a test?

**Comment by CendioOssman** [comment]
No response. Closing.
