### ISSUE TITLE
Duplicated mouse cursor

### ISSUE THREAD

**Issue by YongQiangKuang** [novnc/noVNC#1579]
Describe the bug
I get 2 mouse cursors, the remote and the local one .
The local one is quite bigger and The local one is a bigger black block.

Maybe the same as #1391...
my 'scaleViewport' is true
![noVnc-cursor-block](https://user-images.githubusercontent.com/23253908/133047291-44757fe3-ad57-4ae9-9a90-be8d37482c6c.png)
Expected behavior

Only one pointer is shown. Either the remote or the local one but not a black block...

Client (please complete the following information):

OS: Win10
Browser: chrome, edge
Browser version: latest
Server (please complete the following information):

noVNC version: 1.2.0
VNC server: UltraVnc Server 1.3.4
WebSocket proxy: websockify.js

**Comment by samhed** [comment]
Hi, the first thing I'd like to recommend in this case would be to check if you see the same issue with a different VNC client? I believe UltraVNC has their own viewer you can use.

**Comment by CendioOssman** [comment]
No response. Closing.
