### ISSUE TITLE
Support setting the pixel format to 16bpp rgb333

### ISSUE THREAD

**Issue by QQ2017** [novnc/noVNC#1580]
**Is your feature request related to a problem? Please describe.**
When the network quality is poor, especially if you use novnc to connect to vncserver through an external network, this pixel format will only transmit a small amount of data, which ensures smoothness. At least I do this in both realvnc and tightvnc. The effect is very good and the fluency is greatly improved. I suggest it as an option.

**Describe the solution you'd like**
Support setting the pixel format to 16bpp rgb333,I suggest it as an option.

**Additional context**
![image](https://user-images.githubusercontent.com/23667705/134493626-f9bfd3ac-7d17-4199-83c8-dc9819d90698.png)

If you can’t provide functional support, can you tell me where I can modify it to achieve this effect, thank you!

**Comment by CendioOssman** [comment]
Handling different pixel format is unfortunately a massive pain that we really want to avoid. I would suggest using another method of reducing bandwidth, e.g. reducing the quality setting. That method also allows some servers to fix up any quality issues once bandwidth is available.
