### ISSUE TITLE
remote Cursor  isn't shown in noVNC.

### ISSUE THREAD

**Issue by JB-DX** [novnc/noVNC#1581]
I'm using v1.3.0 beta along with UltraVNC 1.3.4.1

The remote Cursor (server) isn't shown in noVNC.

With UltraVNC-viewer it can be turned on by checking:
  "Track remote cursor locally"

So it has to be done on the viewer side.
Is there a similar option in noVNC ?  I can't find any.

When doing a presentation it's annoying that our clients can's see where I'm pointing to.

**Comment by CendioOssman** [comment]
This is a bug/limitation in UltraVNC (see ultravnc/UltraVNC#24). A workaround is to enable the "Show dot when no cursor" in the noVNC settings.

**Comment by JB-DX** [comment]
When enabling "Show dot when no cursor" it shows the local cursor, but when moving the mouse at the server PC, that new cursor position is not seen in noVNC. And that's what is needed here.
When UltraVNC-viewer enabling "Track remote cursor locally"
then the server-cursor follows the dot.

So why can't noVNC turn it on and thus tell the server to send the position?

**Comment by CendioOssman** [comment]
I'm afraid the VNC protocol does not have a way for the server to tell the client to move its cursor (and noVNC wouldn't be able to anyway as the browser won't allow it). What you are describing is something that UltraVNC needs to fix. It should enable that setting dynamically whenever the client and server mouse cursor are out of sync.

Please report the issue to UltraVNC and they can hopefully have a look at it.
