### ISSUE TITLE
The demo doesn't work

### ISSUE THREAD

**Issue by CharlesGodwin** [novnc/noVNC#1583]
I tried the demo at https://novnc.com/noVNC/vnc.html and I get "Failed to connect to server" error

**To Reproduce**
1. Go to '.https://novnc.com/noVNC/vnc.html'
2. Click on 'Connect'
3. Error shows as red bar at top of page

**Expected behavior**
I expected to see a VNC server.

**Screenshots**

**Client (please complete the following information):**
 - OS:  Windows 10.
 - Browser: Chrome, Edge and Firefox
 - Browser version: 

**Server (please complete the following information):**
no idea, it's your site.

**Additional context**

**Comment by CendioOssman** [comment]
I'm afraid we don't provide any actual server for you to test with. The demo is just the noVNC client itself. You'll need to provide your own VNC server and WebSocket proxy. You can specify the address for that in the settings.

**Comment by war59312** [comment]
I'd suggest telling the user that on the page.
