### ISSUE TITLE
[prepublish hooks] [v1.2.0] npm i failed caused by breaking changes of commander

### ISSUE THREAD

**Issue by mulongjiangliu** [novnc/noVNC#1584]
**Describe the bug**
It throws error after `npm i` for v1.2.0.

Error logs:
![image](https://user-images.githubusercontent.com/16498016/135013930-01aef7c7-31a4-4d9d-89ea-925642671b89.png)

**To Reproduce**
1. Get source code of 1.2.0 version;
2. run `npm i`.
3. See error

**Expected behavior**
`npm i` runs successfully.

**Environment**

![image](https://user-images.githubusercontent.com/16498016/135014169-ad4c1333-1a74-441d-98b1-57dbc87970e4.png)

**Server (please complete the following information):**
 - noVNC version:  1.2.0

**Additional context**
As I researched, the `commander` version specified in `pacakge.json` is `*`, so it get latest version 8.2.0. 
While there is a [breaking change](https://github.com/tj/commander.js/pull/1409) in [commander](https://github.com/tj/commander.js/releases) version 7.0.0, it nolonger supports access option directly on `program`. So all paramters passed to `makeLibFiles` function are `undefined`.

![image](https://user-images.githubusercontent.com/16498016/135015113-5ced4122-edca-4809-bb53-e76e2cb54866.png)

As a workround, I specified the `commander` version to `^8.0.0`, and modified the code in `use_requre.js` as below:

![image](https://user-images.githubusercontent.com/16498016/135016463-e3cd3959-ed33-490e-9d49-de92415fdd82.png)

![image](https://user-images.githubusercontent.com/16498016/135016563-91d2d20d-b7d6-4898-8aa3-d2b164ce6974.png)

**Comment by CendioOssman** [comment]
Thanks for letting us know. Fixed in a85c85fb5f34a47c0f79865252ef9dad8f257441.
