### ISSUE TITLE
demo broken on mac

### ISSUE THREAD

**Issue by kpetrow** [novnc/noVNC#1588]
got to the demo on the main page. does not work. Works on old macs and windows no issue

We have seen the same issue only on macs wit the new certify the web root Expired DST Root CA X3

![image](https://user-images.githubusercontent.com/18248938/135925897-1715bb8b-702f-4b86-aa7a-1c8a47a1f99f.png)
![image](https://user-images.githubusercontent.com/18248938/135925911-50dffb0e-6ebc-4b6c-962d-97b16e89f553.png)

**Comment by CendioOssman** [comment]
The screenshot shows that it is trying to connect to `wss://novnc.com/websockify`. I'm afraid we don't provide any WebSocket proxy or VNC server, so you need to go into the options and change the hostname for the WebSocket proxy to a server that you provide.
