### ISSUE TITLE
Add a way to install noVNC without snapd

### ISSUE THREAD

**Issue by Sly-Little-Fox** [novnc/noVNC#1592]
**Is your feature request related to a problem? Please describe.**
I'm trying to run noVNC in a Docker container, where snapd doesn't work.

**Describe the solution you'd like**
I want noVNC to be available via a PPA or something like that.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by CendioOssman** [comment]
I'm afraid distribution packaging is outside of the scope of our project. Please check with Ubuntu if they can start packaging noVNC for you.
