### ISSUE TITLE
Failed to connect. . . . .

### ISSUE THREAD

**Issue by aaron-is-the-best2114** [novnc/noVNC#1594]
**Describe the bug**
Gives me a 'failed to connect on client (my phone) and on the host (raspberry pi 4)

**To Reproduce**
1. Ran ./utils/novnc_proxy --vnc localhost:5901 in terminal on raspberry pi OS.
2. Went to http://raspberrypi:6080/vnc.html?host=raspberrypi&port=6080 on my phone.  I just replaced the word 'raspberrypi' with my Pis internal IP address
3. Clicked connect on my phone and gave me failed to connect error.
4. Went over to my pi and saw these lines popup in the terminal where noVNC Is running:

192.168.1.xxx - - [11/Oct/2021 07:28:49] 192.168.1.xxx: Plain non-SSL (ws://) WebSocket connection
192.168.1.xxx - - [11/Oct/2021 07:28:49] 192.168.1.xxx: Path: '/websockify'
192.168.1.xxx - - [11/Oct/2021 07:28:49] connecting to: localhost:5901
192.168.1.xxx - - [11/Oct/2021 07:28:49] Failed to connect to localhost:5901: [Errno 111] Connection refused

**Expected behavior**
I expected for me to be able to run noVNC in the terminal on my raspberry pi and connect via my phone or PC.  

**Screenshots**
N/A

**Client (please complete the following information):**
 - OS: Android 11
 - Browser: Chrome
 - Browser version: 94.0.4606.71

**Server (please complete the following information):**
 - noVNC version: 1.2.0
 - VNC server: RealVNC
 - WebSocket proxy: Websockify

**Additional context**
[noVNC-Terminal-Contents.TXT](https://github.com/novnc/noVNC/files/7322324/noVNC-Terminal-Contents.TXT)

**Comment by CendioOssman** [comment]
No response. Closing.
