### ISSUE TITLE
Changing qualityLevel or compressionLevel has no effect

### ISSUE THREAD

**Issue by OrfeasZ** [novnc/noVNC#1595]
**Describe the bug**
Changing the quality or compression levels appears to have no visible effect.

**To Reproduce**
I am running noVNC 1.2.0 with the `utils/launch.sh` script (also tried on `master`). I have tried two things:

1. Using the `vnc.html` sample, and setting the quality and compression level from the UI. I have also tried restarting the connection with those preconfigured.

2. Using the `vnc_lite.html` sample, with `rfb.qualityLevel = 0` and `rfb.compressionLevel = 9`.

**Expected behavior**
I would expect the image quality to be degraded or the used bandwidth to be reduced.

**Client:**
 - OS: Windows
 - Browser: Chrome, Firefox
 - Browser version: 94, 93

**Server:**
 - noVNC version: 1.2.0, master
 - VNC server: RealVNC
 - WebSocket proxy: websockify

**Comment by OrfeasZ** [comment]
Oops, my inbox wasn't showing this reply. Will give TigerVNC a try and report back, but in my test with RealVNC I played a video, adjusted the quality / compression settings, and looked for any changes in image quality and bandwidth. Quality was basically lossless and bandwidth remained about the same, so probably RealVNC just doesn't support these like Pierre suggested.

**Comment by MHM98** [comment]
Hello
I'm facing the same issue with @OrfeasZ .
Instead, I'm using tigervnc and noVNC.
I'm playing a video and try to change the Compression level and expected it to decreased bandwidth.I'm monitoring bandwidth but nothing happened. can anyone help me?
