### ISSUE TITLE
jq not found after upgrade to 1.3.0 using snap

### ISSUE THREAD

**Issue by Astagor** [novnc/noVNC#1598]
I'm using the snap version of novnc and after the update today, the service will not run. I get:
novnc.novncsvc[14698]: /snap/novnc/7/svc_wrapper.sh: line 14: jq: command not found

What should I do? In snap the previous version is not available.

**Comment by CendioOssman** [comment]
I've had a look at the snaps, and for some reason `jq` is not included in the snap anymore, despite it being listed as a requirement. Will have to dig a bit more in to the build process to see what goes wrong...

**Comment by CendioOssman** [comment]
Argh... The issue is some brain dead design where it screws up your dependencies if you try to filter what files you want included from your source. I'll get a fix up.

**Comment by CendioOssman** [comment]
This should be fixed now. It is also uploaded as `latest/edge`. Could someone test and see if it works? If it does I'll promote it to stable.

**Comment by arjunguha** [comment]
latest/edge works for me! Thanks for the fix.

**Comment by CendioOssman** [comment]
Thanks for testing. I've moved it up to stable now, so everyone should get the fixed version as an update.
