### ISSUE TITLE
noVnc not working with snap set after 1.3.0

### ISSUE THREAD

**Issue by pagner** [novnc/noVNC#1600]
Platform: Ubuntu 18.0.4 And 20.0.4. Broken on both machines.

I used snap to install noVnc and have been running it as a service for 8 months successfully. Since the latest update 1.3.0 snap set no longer works.

If I start noVnc this way, it works fine. I can visit the url and log right into my container.
novnc --listen 6081 --vnc localhost:32768

If I start noVnc using snap set, it does not work! The service details show up when I run sudo snap get novnc services.n6081, but the service is not started or it's blowing up. vnc.html is not available.

not working => sudo snap set novnc services.n6081.listen=6081 services.n6081.vnc=localhost:32768

**Comment by CendioOssman** [comment]
Let's try to keep the discussion in one place, so hop over to #1598 and we'll continue there.
