### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by valia0906** [novnc/noVNC#1604]
**Describe the bug**
When use Fullscreen give an error: ResizeObserver loop completed with undelivered notifications

**To Reproduce**
1. Go to Firefox 94
2. Click on Fullscreen
3. See error ResizeObserver loop completed with undelivered notifications
![Знімок екрана з 2021-11-09 10-19-18](https://user-images.githubusercontent.com/20279809/140887672-c212fe7d-e1a4-44a9-ad75-6fb040c14849.png)

**Expected behavior**
No error

**Client (please complete the following information):**
 - OS: Ubuntu 20.04

 - Browser: Firefox 94
 - Browser version: 94.0

**Server (please complete the following information):**
 - noVNC version: 1.3.0
 - VNC server: x11vnc
 - WebSocket proxy: websockify

**Comment by samhed** [comment]
I can't reproduce using TigerVNC server and Firefox 94. Could you check the browser console and see if there are more details in there?

**Comment by valia0906** [comment]
No more datails in console. Did you use fullscreen button or simple F11 key?

**Comment by samhed** [comment]
I also get the `setCapture()` deprecation warning. I tried using both methods, no errors. Might be something that x11vnc does that causes it. Does the issue occur when using any other browsers?

Do you have the possibility of testing a different VNC server?

**Comment by valia0906** [comment]
In Google Chrome 95.0.4638.69-1 the problem does not exist. I am not able to try in different VNC server.

**Comment by CendioOssman** [comment]
I'm not able to reproduce this either. Tested with Firefox 94 on Ubuntu 20.04.

Does this happen every time for you?

**Comment by valia0906** [comment]
Every time when I use noVNC Fullscreen button on the left panel, when I press F11 key problem problem does not appear.

**Comment by CendioOssman** [comment]
Hmm... I wonder what is so special about your system in that case. I don't suppose you have any other machines you can use and see if you see the same issue?

**Comment by valia0906** [comment]
In other mashines problem exists too. Which VNC server did you use?

**Comment by CendioOssman** [comment]
It was a TigerVNC server here as well. I'll try to get a x11vnc up and running and see if I see the issue there. What command line did you specify for x11vnc?

**Comment by valia0906** [comment]
x11vnc -inetd -nolookup -quiet -nocursorshape -nocursorpos -timeout 10 -clear_mods -clear_all

**Comment by CendioOssman** [comment]
Still nothing unfortunately...

Which desktop environment are you running on the server? And on the client machines you've tested?

**Comment by valia0906** [comment]
gnome shell and gnome flashback

**Comment by CendioOssman** [comment]
gnome shell is what I've been using here, so apparently that is not the trigger either... I'm not sure what else to try.

**Comment by samhed** [comment]
Could it be some setting in your Firefox @valia0906? Are you seeing the same issue if you connect from a private browsing tab? Firefox from a different client computer?

**Comment by valia0906** [comment]
I have tried in fresh installed Firefox 94 on Ubuntu the problem still exists. Also tried on Windows the same error. In private browsing tab the same error ocurred.

**Comment by CendioOssman** [comment]
And you are using noVNC 1.3.0 without any modifications?

How did you go about downloading it?

**Comment by valia0906** [comment]
Yes noVNC 1.3.0 which I`ve downloaded from git tar.gz archive and extracted it. Previous version works fine.

**Comment by CendioOssman** [comment]
Still nothing unfortunately. I tried downloading a fresh copy of the 1.3.0 tar.gz, but no error message. :/

**Comment by CendioOssman** [comment]
Did you check the browser console for more details? I'm hoping it might tell us which object it thinks is resizing.

**Comment by valia0906** [comment]
In console I get only warning Element.setCapture() is deprecated. Use Element.setPointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/setPointerCapture.

**Comment by CendioOssman** [comment]
That's very odd. I would expect every error to be logged. :/

Unfortunately we need some more clue here to what is triggering things. I looked at the code and I don't see anything that could reasonably cause this.

**Comment by valia0906** [comment]
I use and open my novnc page inside iframe. I think that iframe causes this problem.

**Comment by CendioOssman** [comment]
Can you share how that page is constructed so we can test here?

**Comment by valia0906** [comment]
This is html code.
[novnc.txt](https://github.com/novnc/noVNC/files/7578978/novnc.txt)

**Comment by valia0906** [comment]
This is my html.
[novnc.txt](https://github.com/novnc/noVNC/files/7579263/novnc.txt)

**Comment by CendioOssman** [comment]
Alright, I'm able to reproduce it now. It only happens randomly though, so it seems like there is some race here. I'll see if I can dig up more.

**Comment by CendioOssman** [comment]
Apparently this is a known bug in Firefox:

https://bugzilla.mozilla.org/show_bug.cgi?id=1685038

No real details, and unfortunately the error event contains absolutely no useful data.

I'll try to hack together a workaround.

**Comment by CendioOssman** [comment]
Workaround in 2f602da96145f02b7765916ac8abfb5022097c29.

Thanks for reporting!

**Comment by valia0906** [comment]
Thank you so much for help. Could you please add this code to noVNC 1.3.0 version.

**Comment by CendioOssman** [comment]
That release is already out, so there isn't anything we can do about that. It will be included in the next version of noVNC.
