### ISSUE TITLE
NoVNC dies on sudden remote resizing

### ISSUE THREAD

**Issue by ii-Python** [novnc/noVNC#1607]
**Describe the bug**
Running `xrandr --output VGA-1 --size 1024x768` in an attempt to make the screen the size as the browser, kills the VNC connection. Attempting to reconnect will fail, however the server is still up.

**To Reproduce**
1. Setup NoVNC using x11vnc
2. Login to a Linux Mint desktop (might not be specific)
3. Change the screen resolution using `xrandr`
4. Get disconnected

**Expected behavior**
For the display to resize and NoVNC to adapt accordingly.

**Screenshots**
Running under ChromeOS and I cannot reconnect, so no screenshots.

**Client (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome
 - Browser version: 94.0.4606.114

**Server (please complete the following information):**
 - noVNC version: 30171492
 - VNC server: x11vnc
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
I'm afraid that seems to be some issue in x11vnc. I can try the same thing with Ubuntu 20.04 as the server, and resizing the screen causes x11vnc to terminate.

I'm afraid I'll have to direct you to file a bug with them and see if they can see why their server is terminating.
