### ISSUE TITLE
Distortion / tearing of display

### ISSUE THREAD

**Issue by riban-bw** [novnc/noVNC#1614]
**Describe the bug**
There is frequently tearing or distortion of the display shown within noVNC which is not evident within RealVNC viewer. The effect persists throughout the noVNC session but may disappear or change with a subsequent client session to the same server session. The same effect occurs in each concurrent noVNC session but is not evident in concurrent RealVNC sessions.

**To Reproduce**
1. Run x11vnc on a Linux (Raspberry Pi Debian Buster) host
2. Run noVNC server on same host
3. Connect with browser, e.g. Chome

**Expected behavior**
Clean, undistorted image consistently displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/3158323/143763295-d8f6a128-2fa1-4d8a-802d-27a3b9789f16.png)

**Client (please complete the following information):**
 - OS: Windows 10 1909 (also observed in Windows 10 20H2, Linux, Android, etc.)
 - Browser: Chrome (Also seein in Firefox and Edge with slightly different severity on concurrent connection)
 - Browser version: 96.0.4664.45 (Official Build) (64-bit)

**Server (please complete the following information):**
 - noVNC version: git commit id: 8ab18125f943533d4bef6198bf53a2e2012b8b50
 - VNC server: x11vnc: 0.9.13
 - WebSocket proxy: None

**Additional context**
This seems to only happen with x11vnc and not with Xtigervnc server. The distortion does not change when noVNC is restarted but it does change when x11vnc is restarted suggesting the issue may be a compatibility issue between x11vnc and noVNC. There is never any such distortion when connecting RealVNC viewer directly to the same x11vnc.

I appreciate this has been discussed before [here](https://groups.google.com/g/novnc/c/ZgPeXqLuLf4?pli=1) and possibly [here](https://github.com/novnc/noVNC/issues/571) but I believe I am using later version of noVNC than was discussed in those posts and the issue may be a compatibilty between x11vnc and noVNC specifically.

**Comment by CendioOssman** [comment]
That is an ancient version of x11vnc, and as mentioned in one of the previous threads it turned out to be some bug in x11vnc/libvncserver. Please try the latest versions of those and the bug is hopefully resolved.

**Comment by riban-bw** [comment]
I am seeing the same behaviour with x11vnc: 0.9.16 which I just compiled from source.

**Comment by CendioOssman** [comment]
Great. Let us know how the testing goes.

**Comment by riban-bw** [comment]
Odd results! I reinstalled the default Debian Buster versions of libvncserver1 and x11vnc and now it seems to work. I will test on a virgin device to see how it behaves and report back.
