### ISSUE TITLE
noVNC is slow on newer version

### ISSUE THREAD

**Issue by HarD-BR** [novnc/noVNC#1618]
**Describe the bug**
noVNC is really slow when navegating

**To Reproduce**
1. Just connect on VNC server

**Expected behavior**
Was expecting to connect and use on a decent framerate like 25+ fps

**Screenshots**
![Screenshot_4](https://user-images.githubusercontent.com/19240666/146045953-38e2a888-6626-4725-9a71-a5d2db5f5063.png)
Video: https://drive.google.com/file/d/17Hstd89mbX7h-G5PR6ZASVqKMMI7hJlO/view?usp=sharing

**Client**
 - OS: Windows 10
 - Browser: Chrome
 - Browser version: Versão 96.0.4664.110 64 bits

**Server**
 - noVNC version: 1.3.0
 - VNC server: QEMU/KVM
 - WebSocket proxy: websockify 0.10.0 with SSL/HTTPS

**Additional context**
2 years ago I was using noVNC on a project, version 0.6.2 or 1.0. dont recall and the fps was really nice, just double mouse bug. Tried the newer version on another project and is really lag even with quality and compression on either 0 or 9. Theres a solution or this is the default?

**Comment by samhed** [comment]
Could you try an older version of noVNC? Are you using the same setup as 2 years ago? The "fps" will likely depend a lot on what's shown on the screen as well as how powerful your server and clients are.

In general, I'd not expect you to get worse performance. But I can't say we have done any real measurements comparing versions.

**Comment by CendioOssman** [comment]
Please also try using another client. This might be a server issue rather than in noVNC.

**Comment by samhed** [comment]
No response.
