### ISSUE TITLE
Please rebuild noVNC Snap

### ISSUE THREAD

**Issue by tkedwards** [novnc/noVNC#1623]
Hi @ossman ,

Please rebuild the noVNC snap. I got an email from Ubuntu saying that it contains some outdated Python packages, and that simply rebuilding the Snap (and releasing that) will pull in the updated Python packages automatically. I don't have access to do this as far as I know.

Merry Christmas!
Tim

**Comment by tkedwards** [comment]
> A scan of this snap shows that it was built with packages from the Ubuntu
> archive that have since received security updates. The following lists new
> USNs for affected binary packages in each snap revision:
> 
> Revision r20 (amd64; channels: edge)
>  * libpython3.6-minimal: 5199-1
>  * libpython3.6-stdlib: 5199-1
>  * python3.6: 5199-1
>  * python3.6-minimal: 5199-1
> 
> Revision r8 (amd64; channels: stable, candidate)
>  * libpython3.6-minimal: 5199-1
>  * libpython3.6-stdlib: 5199-1
>  * python3.6: 5199-1
>  * python3.6-minimal: 5199-1
> 
> Simply rebuilding the snap will pull in the new security updates and
> resolve this. If your snap also contains vendored code, now might be a
> good time to review it for any needed updates.
> 
> Thank you for your snap and for attending to this matter.
> 
> References:
>  * https://ubuntu.com/security/notices/USN-5199-1/

**Comment by CendioOssman** [comment]
We don't have a simple way of rerunning the publishing on an older commit, unfortunately. But from what I can see those issues shouldn't affect us?

**Comment by tkedwards** [comment]
Ok, no worries, I wasn't sure if they'd affect novnc so wanted to check
