### ISSUE TITLE
Russian locale doesn't work properly

### ISSUE THREAD

**Issue by ar2-de2** [novnc/noVNC#1624]
**Description:**
All English language chars typing normally (from "Q" to "P", from "A" to "L", from "Z" to "M"), but part of Russian language chars I can't type almost always. Sometimes after noVNC's page reload that trouble automatically fixes, but page reload not always helps. I'm using noVNC's clipboard for Russian typing as a workaround, but that way don't looks comfortable.

**Client:**
 - Any OS
 - Any browser

**Server:**
 - noVNC version: 1.3.0-g99cf540 (snap)
 - VNC server: TigerVNC 1.10.1+dfsg-3

**Comment by ar2-de2** [comment]
P.S. I don't discovered any dependencies of that trouble with any other factors.

**Comment by CendioOssman** [comment]
Can you see this with other client? It sounds like https://github.com/TigerVNC/tigervnc/issues/93.

**Comment by ar2-de2** [comment]
> TigerVNC/tigervnc#93

BIG THANX!!! PROBLEM SOLVED!!!
