### ISSUE TITLE
Failed to connect, new install with snap on 18.04

### ISSUE THREAD

**Issue by ForceConstant** [novnc/noVNC#1625]
**Describe the bug**
I get failed to connect and " code 404, message File not found" in output. I do see vino-server at port 5900. and can connect using vnc client to that port also.

>novnc --listen 1251 --vnc localhost:5900

**Client (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser: chrome

**Server (please complete the following information):**
 - noVNC version: snap 1.3.0-g99cf540
 - VNC server: vino-server

**Additional context**

**Comment by CendioOssman** [comment]
The 404 is likely a red herring. You usually get that when browsers try to grab favicon.ico.

What other log messages do you get? Both websockify and the browser console are relevant.

**Comment by CendioOssman** [comment]
No response. Closing.
