### ISSUE TITLE
Sample at https://novnc.com/noVNC/vnc.html not working - failed to connect.

### ISSUE THREAD

**Issue by matwell-dev** [novnc/noVNC#1626]
Console output (Edge):

websock.js:231 
        
       WebSocket connection to 'wss://novnc.com/websockify' failed: 
open @ websock.js:231
_connect @ rfb.js:469
_updateConnectionState @ rfb.js:790
RFB @ rfb.js:246
connect @ ui.js:1027
rfb.js:604 
        
       WebSocket on-error event
_socketError @ rfb.js:604
_websocket.onerror @ websock.js:268
error (async)
attach @ websock.js:266
open @ websock.js:231
_connect @ rfb.js:469
_updateConnectionState @ rfb.js:790
RFB @ rfb.js:246
connect @ ui.js:1027
rfb.js:828 
        
       Failed when connecting: Connection closed (code: 1006)

**Comment by CendioOssman** [comment]
I'm afraid we cannot host a WebSocket proxy so you have to specify your own in the settings when using the demo.

**Comment by matwell-dev** [comment]
Thanks for the quick response! As per the other bug-report - this was non-obvious - at least to me! :o(

I'll try and write up some beginners' notes for noVNC, to help others in the future.

**Comment by samhed** [comment]
No need to modify the URL, you should specify the host and port of your own proxy in the noVNC settings, under Advanced->WebSocket.
