### ISSUE TITLE
Failed when connecting: Unsupported security types (types: 13,5,6,130,192)

### ISSUE THREAD

**Issue by matwell-dev** [novnc/noVNC#1627]
Fails to connect to a VNC Server running on Raspberry Pi 4 running Linux rasp-pi3 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux

VNC Server version: VNC(R) Server 6.7.2 (r43081) ARMv8-A (Sep 21 2020 00:15:42)

The security-type failure is (obviously) not innately a bug... Or is it? Should at least one of these types be supported?

Either way, I don't believe that the cause of the failure to connect should be buried away in the console. (I tracked it down the hard way by strace-ing the proxy and decoding the RFB protocol! :o)

**Comment by CendioOssman** [comment]
I'm afraid Raspbian includes RealVNC which is proprietary and all of those security types are secret. As such we generally cannot support them.

Fortunately @pdlan was able to reverse engineer some of them, so they will be supported once #1351 is merged.

**Comment by matwell-dev** [comment]
Thanks for the response. Though given that the platforms (all of them) are far-from rare, it would be good if those restrictions were made more obvious? :o)

Either way, could the error-message be made more visible?

**Comment by matwell-dev** [comment]
Update: one way to get around this is to install another VNC implementation such as Tight VNC. Instructions found here: https://raspi.tv/2012/install-and-use-tightvnc-remote-desktop-on-raspberry-pi-through-windows-android-or-ios

In my case, the install failed, possibly because it couldn't successfully kill the running Real VNC instances (that it wants to remove and replace). In the end, I rebooted and followed the process in the link above.

**Comment by matwell-dev** [comment]
That's a very fair point, though I have to admit, until now, I wasn't aware
of RealVNC's divergence from the others!

Regarding technical details fair point about duming too much info on normal
users, but perhaps it could have a 'More Details' button, or say: see the
browser console for details?
