### ISSUE TITLE
U2F 

### ISSUE THREAD

**Issue by Greenwolf** [novnc/noVNC#1633]
**Is your feature request related to a problem? Please describe.**
It would be great to know if it is possible to pass a USB yubikey through to the VNC Desktop so users can authenticate fully.

**Describe the solution you'd like**
For noVNC to work with FIDO U2F Yubikeys so users can authenticate.

**Describe alternatives you've considered**
N/A

**Additional context**
I'm also coming at this from a security perspective, in that if it is technically possible to support this, it would be great to prove it on an open source project and bring awareness to this, rather than wait for malicious groups to self develop it. Some groups have already started to use noVNC for phishing to bypass proxy protections implemented by Gmail and Facebook.

**Comment by CendioOssman** [comment]
I'm afraid noVNC is just a client, so this is a bit out of scope for us. To consider things that also require server support we want an existing server implementation to interoperate with.
