### ISSUE TITLE
White screen and cross cursor

### ISSUE THREAD

**Issue by Nuckerr** [novnc/noVNC#1639]
**Describe the bug**
Well I get this screen
![image](https://user-images.githubusercontent.com/62883418/160172149-dd300d9d-fda3-4d44-84b2-8ecaf29d1eef.png)

**To Reproduce**
I just followed a guide online to set this all up

**Expected behavior**
To be able to see my screen

**Screenshots**
![image](https://user-images.githubusercontent.com/62883418/160172247-833f6abb-1446-42d7-928c-9de97e6e51f9.png)

**Client (please complete the following information):**
 - OS: windows
 - Browser: Brave
 - Browser version: 1.36.119

**Server (please complete the following information):**
 - noVNC version: [7730814](https://github.com/novnc/noVNC/commit/7730814b8d43d24db0894b641317be4b9f683da4)
 - VNC server: vncserver (I think?)
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
That is the default background and cursor in X, so it looks like your environment didn't start correctly. I'm afraid that is not a noVNC issue, but rather some problem in your server.

Please open an issue with your distribution or VNC server and they can hopefully help you out.
