### ISSUE TITLE
touch hold can't send pointer envent each GH_LONGPRESS_TIMEOUT ms

### ISSUE THREAD

**Issue by chutingxia** [novnc/noVNC#1646]
when I long press on my mobile phone, it can't send pointer event every GH_LONGPRESS_TIMEOUT ms，it happens in many times, i want to send pointer event  every GH_LONGPRESS_TIMEOUT ms，how can i achieve it

![图片](https://user-images.githubusercontent.com/29997858/163754134-24004ef7-1871-4c22-9a46-07195e371fb0.png)

 - Browser:chrome

 - noVNC version: 1.3.0

**Comment by CendioOssman** [comment]
I'm afraid I don't understand what it is you are trying to achieve. That timeout is how it tells the difference between a tap and a long press. It has nothing to do with repeating pointer events.

Could you describe what it is you are trying to do?

**Comment by chutingxia** [comment]
thank you for answer!  what I want to do is when I long press the screen, it can send the pointer event every 200ms，since vnc server do hold action periodic . In fact it doesn't send periodic unless I move my finger on the mobile phone, can I hold on the phone and it send pointer event whether finger move on not

**Comment by chutingxia** [comment]
when I hold on screen and don't move ,some mobile phones can send pointer event periodic, but some can't ,I wonder if it is related to operating system or screen

**Comment by CendioOssman** [comment]
I'm afraid that is now how noVNC is supposed to work. Pointer events are only sent when something has actually changed. If the finger remains in the same place, then it is normal that you don't get more than one event.

**Comment by chutingxia** [comment]
thank you for answer very much, I understand now!
