### ISSUE TITLE
Does onVNC support left-right mouse sliding？

### ISSUE THREAD

**Issue by Clssrie** [novnc/noVNC#1648]

**Comment by CendioOssman** [comment]
Yes. As long as we get horizontal mouse wheel events, then those will be passed on to the server.

**Comment by Clssrie** [comment]
> Yes. As long as we get horizontal mouse wheel events, then those will be passed on to the server.

my host is Mac M1，docker  environment is ubuntu 18.04，start 
1、Xvfb :0 -screen 0 1920x1080x24 
2、usr/bin/x11vnc
3、./utils/novnc_proxy --vnc localhost:5900
4、firefox
but swiping left and right with two fingers on my console's touch screen resulted in swiping up and down

**Comment by CendioOssman** [comment]
macOS doesn't have any native touch support, so that must be a third party product that handles it. You should have a look at that and see how it can be configured to send the proper wheel events.
