### ISSUE TITLE
Cannot read properties of undefined (reading 'importKey')

### ISSUE THREAD

**Issue by zhanghuid** [novnc/noVNC#1649]
**Describe the bug**
in my centos system, i clone the noVNC project, and then run `./utils/novnc_proxy --vnc 6080`, visit the browser, and see like 

<img width="752" alt="image" src="https://user-images.githubusercontent.com/12711819/167896160-a5209621-2c73-4417-ad54-7caab56a8971.png">

**Client (please complete the following information):**
 - OS: centos
 - Browser: chrome
 - Browser version: 100.0.4896.60

**Server (please complete the following information):**
 - noVNC version: 1.3
 - WebSocket proxy: [websockify

may i do some wrong step?
thanks for you help

**Comment by pdlan** [comment]
ARD Authentication can only be used in secure contexts (i.e., a TLS-enabled host or localhost).

**Comment by zhanghuid** [comment]
> ARD Authentication can only be used in secure contexts (i.e., a TLS-enabled host or localhost).

it works, thanks
