### ISSUE TITLE
Abnormal desktop screen after send Credentials 

### ISSUE THREAD

**Issue by LemonAniLabs** [novnc/noVNC#1650]
**Describe the bug**
My os is Popos 22.04.
After I install tigerVNC and launched.
I start noVNC on my terminal.

```
novnc --listen 6081 --vnc localhost:5902
Warning: could not find self.pem
Using installed websockify at /snap/novnc/8/bin/websockify
Starting webserver and WebSockets proxy on port 6081
WebSocket server settings:
  - Listen on :6081
  - Web server. Web root: /snap/novnc/8
  - No SSL/TLS support (no cert file)
  - proxying from :6081 to localhost:5902


Navigate to this URL:

    http://pop-os:6081/vnc.html?host=pop-os&port=6081

Press Ctrl-C to exit


127.0.0.1 - - [12/May/2022 11:40:56] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
127.0.0.1 - - [12/May/2022 11:40:56] 127.0.0.1: Path: '/websockify'
127.0.0.1 - - [12/May/2022 11:40:56] connecting to: localhost:5902
127.0.0.1 - - [12/May/2022 11:46:51] code 404, message File not found
127.0.0.1 - - [12/May/2022 11:46:52] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
127.0.0.1 - - [12/May/2022 11:46:52] 127.0.0.1: Path: '/websockify'
127.0.0.1 - - [12/May/2022 11:46:52] connecting to: localhost:5902


```

Then I open my chrome broswer and go to ***http://pop-os:6081/vnc.html?host=pop-os&port=6081***
After send Credentials, I got a screen like bellow.
![image](https://user-images.githubusercontent.com/6212976/167988156-09265986-1510-41f9-8be3-32af98dfd0dd.png)

is there any idea about that?
Thank you.

**Comment by CendioOssman** [comment]
It looks like your desktop environment failed to start correctly. I'm afraid that is a server issue, and noVNC is working fine. So please report this to PopOS, and they can hopefully help you out.

**Comment by LemonAniLabs** [comment]
Yup, I replace tigherVNC to x11vnc server. And it's work.
Thank you.
