### ISSUE TITLE
Cannot read properties of undefined (reading 'digest')

### ISSUE THREAD

**Issue by K1ttyKat** [novnc/noVNC#1653]
**Describe the bug**
When I click 'Connect' to view the user interface of a Raspberry Pi I get the error "Cannot read properties of undefined (reading 'digest')"

**To Reproduce**
(Based on the process given at [)](https://youtu.be/CWs88VPBJ94)
1. Create image of Raspberry Pi OS (2022-04-04 version).
2. Start the Pi and download latest updates.
3. Start VNC on the Pi (from Preferences/Raspberry Pi Configuration/Interfaces)
4. Change the VNC security settings to 'Encryption: Prefer off' and 'Authentication: VNC password' and give it a password to use.
5. Install noVNC using `git clone https://github.com/novnc/noVNC.git`
6. From the noVNC directory type `./utils/novnc_proxy --vnc localhost:5900.`  This gives you an address to type into a browser.
7. Enter the address into a browser (replacing 'raspberrypi' with its IP address)
8. The noVNC page served by the Pi is now displayed.
9. Click 'Connect'.
10. At this point it gives you an error (Cannot read properties of undefined reading 'digest').

**Expected behavior**
At this point I would have expected the UI of the Raspberry Pi to be displayed.

**Screenshots**
![noVNC Error](https://user-images.githubusercontent.com/97441638/168638984-66fe2c1e-60c9-4bba-aab4-246d60453646.png)

**Client (please complete the following information):**
 - OS: Windows 10 and 11
 - Browser: Edge and Chrome
 - Browser version: Edge Version 101.0.1210.47 (Official build) (64-bit) / Chrome Version 101.0.4951.67 (Official Build) (64-bit)

**Server (please complete the following information):**
 - noVNC version: 1.3.0
 - VNC server: (Don't know)
 - WebSocket proxy: websockify

**Additional context**
I read somewhere that it might be a certificate issue and tried running:

`openssl req -new -x509 -days 365 -nodes -out self.pem -keyout self.pem`

...but this made no difference.

**Comment by pdlan** [comment]
RealVNC servers (that raspi uses) are only supported in secure contexts (i.e., TLS-enabled hosts or localhost). You need to set TLS for websockify. (You generated the key cert but seem not to be using them. It’s still http:// in the error message)

**Comment by K1ttyKat** [comment]
pdlan, thank you so much for that - it was the one thing I missed!  I just tried https and it worked fine!

**Comment by imnotonehanded** [comment]
> RealVNC servers (that raspi uses) are only supported in secure contexts (i.e., TLS-enabled hosts or localhost). You need to set TLS for websockify. (You generated the key cert but seem not to be using them. It’s still http:// in the error message)

Hey, how would I go about enabling TLS

**Comment by pdlan** [comment]
> > RealVNC servers (that raspi uses) are only supported in secure contexts (i.e., TLS-enabled hosts or localhost). You need to set TLS for websockify. (You generated the key cert but seem not to be using them. It’s still http:// in the error message)
> 
> Hey, how would I go about enabling TLS

I think websockify has some documentation about that.

**Comment by minystreem** [comment]
I was having the same problem on my pi but when I use https it says the page could not be reached and I get this error in the host terminal: SSL connection but '/home/minystreem/noVNC/utils/websockify/self.pem' not found. I have not been able to find out why it wont make the self.pem file.

**Comment by minystreem** [comment]
I am following the same video

**Comment by minystreem** [comment]
I got this problem on my pi 3 and I was able to generate a self.pem file put them I get this error: handler exception:  [SSL] PEM lib (_ssl.c:4043) any sugestions?

**Comment by Adaaks** [comment]
> I got this problem on my pi 3 and I was able to generate a self.pem file put them I get this error: handler exception: [SSL] PEM lib (_ssl.c:4043) any sugestions?

did u figure it out
