### ISSUE TITLE
Webbrowser can access files in novnc folder and no logging

### ISSUE THREAD

**Issue by freebrowser1** [novnc/noVNC#1655]
When I open `http://server/vnc.html`, everything works correctly.

But when I do `http://server/`, I see a directory listing which is probably a security leak. And other files in that folder can be opened as well, which is not needed and wanted. 

Moreover I cannot find any logging, so I cannot see why e.g. on a given server VNC cannot be accessed. I tried it on a Raspberry Pi (succesful), on Android Termux / Andronix (a Ubuntu subsystem under Android), also successfully. Works great !
In both cases I installed it by unzipping the zip file and started from the novnc folder:
`./utils/novnc_proxy --vnc localhost:5901` .

But when I forward the 6080 port of either one of these via reverse SSH tunneling on a VPS, it goes wrong 'cannot connect to server'. Probably due to my setup and not due to novnc, but cannot check it as I don't know what cannot connect in novnc as it lacks logging.

**Comment by CendioOssman** [comment]
> But when I do `http://server/`, I see a directory listing which is probably a security leak. And other files in that folder can be opened as well, which is not needed and wanted.

The helper script will use websockify, which is written to make it quick and easy to test things. I'm afraid that production use was never a design criterion, so if you need good control of things like this, then you should probably look at a more robust web server. However, the specific issue of listing directories is tracked in novnc/websockify#466.

> But when I forward the 6080 port of either one of these via reverse SSH tunneling on a VPS, it goes wrong 'cannot connect to server'. Probably due to my setup and not due to novnc, but cannot check it as I don't know what cannot connect in novnc as it lacks logging.

Both noVNC and websockify has logging, so we need more details here. To start with, please fill out the issue form properly and don't bypass it.

**Comment by freebrowser1** [comment]
Well, I hope you understand my goal.

**Client (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Firefox
 - Browser version: 100

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - noVNC version: 1.3.0
 - VNC server: TigerVNC and TightVNC
 - WebSocket proxy: websockify

**Additional context**
When I tunnel port 6080 from the server (a Raspberry Pi 4) to a frontend server (an external VPS running Apache), I run first `vncserver start` which starts TightVNC. 

First I start, just running noVNC, which works successfully.

`novnc/utils/novnc_proxy --vnc localhost:5901`

which outputs :
````
pi@raspberry-pi:~$ Warning: could not find self.pem
Using local websockify at /home/pi/novnc/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080

Navigate to this URL:

    http://raspberry-pi:6080/vnc.html?host=raspberry-pi&port=6080

Press Ctrl-C to exit
````
From the Mac I start in Firefox `http://pi:6080/vnc.html` (pi is the name of the raspberry pi). That works fine, 'host' and 'port' parameters are not needed as it is handled by the server (Raspberry Pi).

On the VPS I have installed a frontend for my local devices to share it occasionally. It proxies port 81 from a local device to the 'front end' which is standard https port 443 of the VPS to a browser.
So I can forward any web interface to the public internet this way. E.g. when I want to forward the local webserver of my Mac (which runs Apache on port 80), I do a reverse SSH tunnel in a macOS terminal:
`ssh -R 81:localhost:80 user@VPS` 
That shows the local website on my VPS site https://forward.example.com. Any sub-URL is just as if it is shown as http://localhost/suburl in a browser on my Mac.

To forward noVNC I do the same trick on the Raspberry Pi (obviously one forward tunnel at a time): 
`ssh -R 81:localhost:6080 user@VPS` 
which forwards port 6080 (noVNC) to port 81 of the VPS which should be proxied on my VPS site https://forward.example.com/vnc.html.

But then, the noVNC web interface opens normally, but it says in red text on top: 'Failed to connect to server'.

Weird, as this is all handled by Raspberry Pi where VNC server and noVNC is active. The VPS is only a front end of the noVNC 'website' forwarded to the VPS.
As I have no logging (or don't know where I can find it), what can be wrong here in the chain ?
Probably not a bug in noVNC, but in my way of thinking.

**Comment by CendioOssman** [comment]
I would guess your proxy configuration in Apache on your VPS is insufficient and fails to proxy WebSocket requests. So the three places I would suggest to look are:

1. The Firefox browser console on your mac. It should hopefully have more details about why the WebSocket request failed.
2. The Apache logs on the VPS, to see the details of what it tried to forward, and how that went.
3. The output from websockify on the RaspberryPi to see what requests actually made it all the way there.

Hopefully that should shed more light on what is happening.

**Comment by freebrowser1** [comment]
I finally found the solution, thanks to this [Apache documentation](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) and [this 8 year old post on this subject](https://github.com/novnc/websockify/issues/149).


This is a section of `ssl.conf` of the VPS for the domain forward.example.com:
```

    # https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html
    ProxyPass / http://localhost:81/
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/?(.*) "ws://localhost:81/$1" [P,L]

```
Then I had to enable mod-proxy-wstunnel by `a2enmod proxy-wstunnel` and kick Apache 'apachectl restart`.

Now when I run `novnc/utils/novnc_proxy --vnc localhost:5901` from the Raspberry Pi (or whatever device with VNC) and then run `ssh -R 81:localhost:6080 user@VPS` from the same device I can get noVNC working on the site https://forward.example.com/vnc.html.

That makes screen sharing to colleagues darn easy without privacy infringing tools like Google Meet or Microsoft Teams as I can IP filter (or take other security rectrictions) the access to the site myself. And the other doesn't need to install VNC viewer apps.

**Comment by CendioOssman** [comment]
Glad you found how to configure Apache for this. Since everything seems to be working now, I'll go ahead and close this issue.
