### ISSUE TITLE
Screensharing on macOS does not work properly with noVNC

### ISSUE THREAD

**Issue by freebrowser1** [novnc/noVNC#1656]
When running `novnc/utils/novnc_proxy --vnc localhost:5900` on a Mac, it does start, but a browser on another device does login to VNC but the screen remains black and sometimes parts of the screen appear slowly.

**To Reproduce**
1. Enable 'Screen sharing' (which is the builtin VNC server of macOS.
2. Open a terminal and cd to the novnc folder and run `./utils/novnc_proxy --vnc localhost:5900` (vnc runs on port 5900). 
3. Start a browser (Firefox in my case) on another device and open http://<indoor IP address of Mac>/vnc.html.
4. Enter the VNC password (which is actually the password of the current user of macOS)
5. See error (almost black screen)

**Expected behavior**
An image of the screen of the Mac.

**Screenshots**

Firefox on Ubuntu
![Screenshot_20220525-220325](https://user-images.githubusercontent.com/26625141/170359348-f468c51b-9124-4e30-a5c5-ef880fdd2998.jpg)

Brave on localhost (to show errors)
<img width="824" alt="Screenshot 2022-05-25 at 22 01 13" src="https://user-images.githubusercontent.com/26625141/170359377-b95aa8d9-0ba6-406f-92ae-528000117606.png">

**Client (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Browser version: 100

**Server (please complete the following information):**
 - noVNC version: 1.3.0
 - VNC server: macOS Screen sharing
 - WebSocket proxy: novnc-proxy.
 - OS version: macOS Monterey 12.3 on an M1.

**Additional context**
When I start X11vnc on macOS on port 5901 and restart `novnc/utils/novnc_proxy --vnc localhost:5901` then the client does log in, but shows a black screen. Probably an X11VNC issue which is installed by Homebrew. Other servers (Ubuntu) serve the VNC screen properly, both on a direct VNC viewer or in a browser via noVNC in the client.

**Comment by tiennguyen1293** [comment]
I have faced the same issue.
![image](https://user-images.githubusercontent.com/26110369/170644094-79cd43d1-ec0c-44e8-87dc-8b3fa47ea8fa.png)

**Comment by CendioOssman** [comment]
Fortunately, this issue has already been reported and fixed over in #1635. Please try the development version of noVNC until we can make a new, stable release.
