### ISSUE TITLE
Can't reach noVNC from interent with wss problem while working fine in LAN

### ISSUE THREAD

**Issue by huyun0** [novnc/noVNC#1657]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Why noVNC can not be reached from internet

**Screenshots**

**Client (please complete the following information):**
chrome

**Server (please complete the following information):**
 - noVNC version: [e.g. 1.0.0 or git commit id]
 - WebSocket proxy: [e.g. websockify]

**Additional context**

I am a beginner for noVNC, my objectvie to learn noVNC is to visit my office docker application from internet.

So, my visit path to docker is:

domain:80 -> nginx transfer (public ip) -> DDNS -> office router to transfer port to local server ip+port -> server transfer to docker host+port -> noVNC application docker+port

Specfically,

internet: xxx.xxx.xxx.cn:80 -> internet: xxx.xxx.xxx.xxx -> office router (WAN: DDNS, LAN: 192.168.2.1)-> windows server: 192.168.2.123:12301 -> docker host: 192.168.3.132:8084 -> docker application 172.6.127.1:8083

my problem is:

when I visit the noVNC from LAN, it works fine,

but when I try from internet, the loading takes a minute, and it shows only a connection button, when I click the button, it responses with "could not connect to server " (might not accurate because I have only Chinese version). and in chrome the error is:

websock.js:184 WebSocket connection to 'wss://xxx.xxx.xxx.cn:80/core' failed: open @ websock.js:184 _connect @ rfb.js:398 _updateConnectionState @ rfb.js:628

Failed when connecting: Connection closed (code: 1006) _fail @ rfb.js:666 （匿名） @ rfb.js:208 _websocket.onclose @ websock.js:199

then I try to setup ssl certificate, I use

openssl req -new -x509 -days 365 -nodes -out self.pem -keyout self.pem

to generate a self.pem in ./noVNC/utils, unfortunately no luck.

the screenshots here are demostration for LAN and WAN visit:

visit in Lan is all right: 
![image](https://user-images.githubusercontent.com/27984520/170932843-1318cffd-cc6a-408f-9436-31788057d6c4.png)

visit from WAN is not working:  
![image](https://user-images.githubusercontent.com/27984520/170932822-7fff7a00-a699-4209-ad76-7fe6e57d8d4f.png)

Any suggestions are greatly appreciated, thank you in advance,

Ming

**Comment by CendioOssman** [comment]
Please don't spam our forums. You've sent three messages to our discussion group already. If someone has some suggestions, you'll get a response there.

**Comment by huyun0** [comment]
Sorry for the spam, my internet connection went wrong when I sent the questions.

 

发件人: Pierre Ossman (Work account) ***@***.*** 
发送时间: 2022年5月30日 15:35
收件人: novnc/noVNC ***@***.***>
抄送: huyun0 ***@***.***>; Author ***@***.***>
主题: Re: [novnc/noVNC] Can't reach noVNC from interent with wss problem while working fine in LAN (Issue #1657)

 

Please don't spam our forums. You've sent three messages to our discussion group already. If someone has some suggestions, you'll get a response there.

**Comment by mrli868** [comment]
anyone know how fix this issue? I met the same issue. 

as the WebUI still visible, so the Reviser Proxy should be working already.

but NoVNC do not allow me to connect, looks like NoVNC or the VNC server behind do not allow remote connect.   or the passwd is not passed to the VNC server correctly.

**Comment by mrli868** [comment]
as the WebUI still visible, so the Reviser Proxy should be working already.

but NoVNC do not allow me to connect, looks like NoVNC or the VNC server behind do not allowed remote connect.   or the passwd is not passed to the VNC server correctly.

> anyone know how fix this issue? I met the same issue.
> 
> as the WebUI still visible, so the Reviser Proxy should be working already.
> 
> but NoVNC do not allow me to connect, looks like NoVNC or the VNC server behind do not allow remote connect. or the passwd is not passed to the VNC server correctly.

Just tried, after change the Reviser Proxy rule, do not use https, just use http， noVNC can connect properly.
