### ISSUE TITLE
First column getting chopped off from tty display

### ISSUE THREAD

**Issue by darose** [novnc/noVNC#1658]
**Describe the bug**
My Lantronix Spider uses noVNC for its remote admin capabilities, and generally works great.  However it has always suffered from one rather annoying issue:  when my (linux) server is in tty/console mode, the first column always gets chopped off.  The attached screenshot shows an example of this:  it should be saying "Arch Linux" and the server name "darsys22"

**To Reproduce**
1. Use the Spider's built-in noVNC to remotely access the server.
2. Click ctrl-alt-f2 to get to a console.
3. See the console display, with the first column chopped off.

**Expected behavior**
The console should display all 80 columns, not just columns 2 - 80.

**Screenshots**

![Screenshot 2022-06-08 at 10-24-28 Spider KVM](https://user-images.githubusercontent.com/507237/172643264-600974b3-5340-412e-9d8c-b08fc0f4219c.png)

**Client (please complete the following information):**
 - OS:  linux
 - Browser: Firefox
 - Browser version: 101.0

**Server (please complete the following information):**
 - noVNC version: unknown - whatever version is bundled into Lantronix Spider firmware 04.03.02 (V4.3_2022-01-24)
 - VNC server: unknown
 - WebSocket proxy: unknown

**Additional context**

**Comment by samhed** [comment]
It's very unlikely this is a noVNC issue, I'd bet it's something with the VNC server. Have you tried connecting with different VNC viewers?

**Comment by CendioOssman** [comment]
I'm afraid this is not something we can really help with since it is some custom bundling. I would suggest contacting Lantronix and see if they can help.

(This also doesn't look like a VNC issue. It looks more like the device hasn't synced properly to the video signal.)
