### ISSUE TITLE
When will it be published to npm? i need RFB.approveServer() , plz

### ISSUE THREAD

**Issue by notthistrain** [novnc/noVNC#1661]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CendioOssman** [comment]
I'm afraid we don't have a fixed plan for when we'll do another release. Hopefully soon though.

But we also publish the development version to npm, so you can use that if you want. Simply switch to the `dev` tag instead.

**Comment by notthistrain** [comment]
ok thank you bro
