### ISSUE TITLE
Failed while connected: unsupported encoding (encoding 29)

### ISSUE THREAD

**Issue by digitalirony** [novnc/noVNC#1663]
server starts, connects works fine for about 3-5 seconds.
Then it just fails. No errors in the server/linux console(I am not sure how to turn on debug logging on server side). 
If I enable debug logging in browser and check browser console I do get some errors:
rfb.js:808 Failed while connected: Unsupported encoding (encoding: 29)
websock.js:214 Closing WebSocket connection
websock.js:185 WebSocket connection to 'ws://192.168.50.97:8081/websockify' failed: Received a broken close frame containing a reserved status code.
open @ websock.js:185
vnc.html:1 The resource http://192.168.50.97:8081/app/images/warning.svg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

This is using latest release of both websockify and novnc installed from github/manually (the debian packages were version 1.2.X, and were missing package.json)

**Comment by CendioOssman** [comment]
Please fill out the bug report form.

**Comment by digitalirony** [comment]
where is that? I just clicked file a bug button on your site and it brought me here, I didnt see any form.

**Comment by CendioOssman** [comment]
When you click the bug button, it gives you a template to fill out in the edit box.
