### ISSUE TITLE
right part of webpage is blank sometimes

### ISSUE THREAD

**Issue by nomadicsun** [novnc/noVNC#1664]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5955508/179267362-77ebfb9a-cc49-4d27-8b51-bab78f3cfc08.png)
sometimes, when i open the vnc.html, the left part is blank, and it can restore after resizing the browser window size.
the resize setting is 'remote' and i am using tigervnc for the vncserver.
this issue only occur sometimes, not always.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: [e.g. iOS] window 10
 - Browser: [e.g. chrome, safari] edge
 - Browser version: [e.g. 22] 

**Server (please complete the following information):**
 - noVNC version: [e.g. 1.0.0 or git commit id]
![image](https://user-images.githubusercontent.com/5955508/179267825-dd1b269b-784c-42b6-9943-695b802c6fb6.png)

 - VNC server: [e.g. QEMU, TigerVNC] tigervnc
 - WebSocket proxy: [e.g. websockify] websockify

**Additional context**

**Comment by samhed** [comment]
Looks like a server-side issue to me, have you tried TigerVNC's viewer to see if you get the same issue there?

**Comment by CendioOssman** [comment]
This is clearly a server-side issue, as you can see the task bar extending the full width. So, I'm afraid you'll have to report this bug to your distribution. There is something buggy in that version of KDE that isn't resizing the background properly.

**Comment by nomadicsun** [comment]
i bypass this issue by setting a longer width when starting the vncserver process, and it will scale in when opening with novnc, Thanks very much for your information! ;)

**Comment by nomadicsun** [comment]
BTW，what X11 desktop do you recommend to use? what about Xfce? especially for the case when multi users use the same Linux server? Thanks!

**Comment by CendioOssman** [comment]
noVNC should work well with everything.

From personal experience, though, lightweight desktops such as Xfce or MATE generally work better as they don't require GPU acceleration. I would also suggest disabling compositing in those environments for even more performance.
