### ISSUE TITLE
Terminal clipboard support (copy/paste/text select) (2nd issue)

### ISSUE THREAD

**Issue by okaeiz** [novnc/noVNC#1666]
**Describe the bug**
I have installed Proxmox 7.2-3 and I have created two virtual machines. One of them is an Ubuntu Server 22.04 and the another one is a Windows Server 2022. I need to be able to copy (select) text from outside of the virtual machine and paste it in the virtual machine (in my case, the Linux terminal or Windows command prompt) but it doesn't work in noVNC.

**To Reproduce**
1. Go to the Proxmox web interface.
2. Power on your deb-based linux virtual machine.
3. Try to copy something from the outside of the VM and paste it into the VM, or vice versa.
4. See? You cannot.

**Expected behavior**
I expect to be able to copy and past between outside of the VM and the terminal in VM.

**Client (please complete the following information):**
 - OS: Ubuntu Server 22.04
 - Browser: Chrome
 - Browser version: Version 103.0.5060.134

**Server (please complete the following information):**
 - noVNC version: 1.3.0-3
 - VNC server: QEMU
 - WebSocket proxy: [e.g. websockify]

**Additional context**

**Comment by samhed** [comment]
I have no idea what kind of interface proxmox has implemented for noVNC, but this is accessible in our library API, and also in our example app vnc.html.

You will have to file an issue with proxmox if this isn't possible.
