### ISSUE TITLE
screen size can become more flexible

### ISSUE THREAD

**Issue by notthistrain** [novnc/noVNC#1669]
I use the novnc to display a fullscreen canvas,
when another tabs which are in the same chrome window download a file,
the bar will appear at the bottom of broswer,
the scroll bar will appear at the same time all right,
so the appearance is after i close the bar,
the scorll bar is still exist.

i find the code at core/rfb.js line 200,
        this._screen.style.width = '100%';
        this._screen.style.height = '100%';
is Is it better to change to 100vw 100vh?
i try it,the scroll will hiden.

Thanks for your hard work bro!

**Comment by CendioOssman** [comment]
I'm afraid that would break cases where noVNC is not using the entire window.

This sounds like a browser bug. noVNC should resize when the browser adjusts the available space.

Please fill out the bug template properly so we get a better idea of your setup.
