### ISSUE TITLE
Add header in websockify request

### ISSUE THREAD

**Issue by sinbargit** [novnc/noVNC#1671]
**Is your feature request related to a problem? Please describe.**
Set token in url is illegal with our security regular, Any way can add it in http header?

**Describe the solution you'd like**
Can set http headers is options 

**Describe alternatives you've considered**
Any tricky way can workaround to set header?

**Comment by CendioOssman** [comment]
No, I'm afraid there is no way to control the headers sent. The only thing you can control directly is the URL. The request does include cookies, though, so you may be able to do something there.
