### ISSUE TITLE
change Compression level have no effect.

### ISSUE THREAD

**Issue by MHM98** [novnc/noVNC#1673]
Hello
I'm facing the same issue with @OrfeasZ .
Instead, I'm using tigervnc and noVNC.
I'm playing a video and trying to change the Compression level and expected it to decrease bandwidth. I'm monitoring bandwidth but nothing happened. can anyone help me out why changing the Compression level has no effect??

_Originally posted by @MHM98 in https://github.com/novnc/noVNC/issues/1595#issuecomment-1214141829_

**Comment by CendioOssman** [comment]
I'm afraid the setting is just a request and the server is free to ignore it. So changing those sliders may or may not have a noticeable effect.

In TigerVNC's case, it should respect the setting. However, the compression setting has very little effect on bandwidth. It is only some data that is affected by it, and unfortunately the difference between the different steps is very minor.

For TigerVNC, the quality setting will likely have a much larger impact on the used bandwidth.
