### ISSUE TITLE
Not working on Edge 18

### ISSUE THREAD

**Issue by chantzish** [novnc/noVNC#1674]
**Describe the bug**
Not working on Edge 18 (latest classic Edge).
The loading dots are spinning endlessly and the "connect" button is not showing.

**To Reproduce**
Open vnc.html in edge 18

**Expected behavior**
The spinning dots are supposed to disappear after a few seconds and the noVNC logo with the "connect" button to show instead.

**Screenshots**
I think the problem is clear enough (see the additional context for detailed technical explanation/solution).
I will make screenshot if requested.

**Client (please complete the following information):**
 - OS: Windows 10 (version 1909)
 - Browser: Edge
 - Browser version: 18.18363

**Server (please complete the following information):**
 - noVNC version: cdfb336 (latest commit)
 - VNC server: TigerVNC
 - WebSocket proxy: websockify

**Additional context**
Apparently Edge 18 doesn't support BigInt (even though some sites claim it should).
I can confirm that after deleting the BigInt constructors and the n suffix from numbers in core/ra2.js and core/rfb.js the problem is fixed and the connect button apears after a few seconds.
(By doing so I actually converted the numbers back to normal numbers, It would probably be better to use a folyfill library for big numbers)
Additionally Edge 18 doesn't support ResizeObserver wich causes the connection to fail after clicking the connect button.
This can be fixed by using a polyfill library for ResizeObserver - I confirmed with the resize-observer-polyfill from npm - after the above BigInt "fix" and the importing of resize-observer-polyfill noVNC works as expected.

**Comment by chantzish** [comment]
I can submit a PR patch to add polyfill libraries if you want.

**Comment by CendioOssman** [comment]
Yes, I'm afraid dropping support for old Edge was an explicit choice, as it is pretty much EOL.

Is there any reason why you aren't using the current Edge?
