### ISSUE TITLE
noVNC Firefox iOS Script Error

### ISSUE THREAD

**Issue by steveji2021** [novnc/noVNC#1675]
I used noVNC in Safari normally. But when I use Firefox, it said “noVNC encountered an error: Script error.”
![BBA7BEB1-0281-4A7F-AD91-1F959E03DD36](https://user-images.githubusercontent.com/88028845/184525403-f8bda469-eb67-4cb7-93b8-0e589c46dd52.png)
![EFA36931-7F43-41E1-BD6F-820DBE80E9A9](https://user-images.githubusercontent.com/88028845/184525406-ab6492ed-022e-459a-88e8-2ed3a784de24.png)

**Comment by CendioOssman** [comment]
Please fill out the bug issue template properly, so we get a better picture of your setup.

**Comment by CendioOssman** [comment]
We briefly saw this here, but it seems to have gone away in some update.
