### ISSUE TITLE
Unable to send " Window + L " keyEvent to windows from noVNC client

### ISSUE THREAD

**Issue by vivek1997warjurkar** [novnc/noVNC#1683]
I am trying to send " Window + L " keyEvent but I am unable to do that. Basically I want to lock my computer on clicking of connect button on  vnc.html

* When I am trying to send "Windows + tab " keyEvent , this is working. tabs are getting minimized.

I am using below code :

                   a. for windows + L (Not working)    : **UI.sendKey(KeyTable.XK_Super_L, "MetaLeft", true);		
		                                                                UI.sendKey(KeyTable.XK_l,"KeyL");
		                                                                UI.sendKey(KeyTable.XK_Super_L, "MetaLeft", false);**
                    ( Whenever I am sending this event : L is getting printed on the notepad )

                    b. for windows + tab ( Working ):   **UI.sendKey(KeyTable.XK_Super_L, "MetaLeft", true);	
                                                                               UI.sendKey(KeyTable.XK_Tab, "Tab");
		                                                                UI.sendKey(KeyTable.XK_Super_L, "MetaLeft", false);**	
                       ( Whenever I am sending this event : tabs are getting minimized )

* I want to know, Does VNC blocks some of the keyEvents ? Or I am missing something in this code ?
* Or is there any otherway where this can be achieved ?

*Your inputs will be valuable . Thanks in Advance 

* I am using : TightVNC as a server.
* Browser : Chrome

**Comment by CendioOssman** [comment]
A discussion is already ongoing in the noVNC group, so let's avoid splitting things over multiple places and continue the discussion there.

(and no, there is no filtering of events)
