### ISSUE TITLE
Running novnc from git on kubuntu fails in browser

### ISSUE THREAD

**Issue by lnee94** [novnc/noVNC#1685]
**Describe the bug**
Running novnc from git on kubuntu fails in browser

**To Reproduce**
1. first I started a kubuntu 22.04 vm
2. then i did `git clone https://github.com/novnc/noVNC.git`
3. then I installed tightvncserver python3-numpy
4. then I started tightvncserver
5. next I ran `./utils/novnc_proxy --vnc hostname:1`
6. when i open the web page it gives me it says failed to connect to server and outputs 
```127.0.0.1 - - [07/Sep/2022 18:48:48] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
127.0.0.1 - - [07/Sep/2022 18:48:48] 127.0.0.1: Path: '/websockify'
127.0.0.1 - - [07/Sep/2022 18:48:48] connecting to: crashcorse:1
127.0.0.1 - - [07/Sep/2022 18:48:48] Failed to connect to crashcorse:1: [Errno 111] Connection refused
```

**Expected behavior**
when I ran those commands for it to connect

**Screenshots**

**Client (please complete the following information):**
 - OS: kubuntu
 - Browser: firefox
 - Browser version: 104.0.2

**Server (please complete the following information):**
 - noVNC version: 
 - VNC server: tight vnc server
 - WebSocket proxy:  websockify i think

**Additional context**
the snaps works

**Comment by CendioOssman** [comment]
I'm afraid the script doesn't support display numbers, only TCP ports. So if you specify `--vnc hostname:5901` then things will likely work better.

**Comment by lnee94** [comment]
I tried it using krfb on port 5900 still does not work

**Comment by CendioOssman** [comment]
What error are you getting in that case? And how was krfb started/configured?
