### ISSUE TITLE
Can compileing instutions be provied for snap 

### ISSUE THREAD

**Issue by lnee94** [novnc/noVNC#1686]
**Is your feature request related to a problem? Please describe.**
Can compileing instutions be provied for snap 
**Describe the solution you'd like**
A set of commands to added to the readme that say how to compile the snap

**Describe alternatives you've considered**
Na

**Additional context**
I want to compile for ubuntu(22.04) server for rassberry pi

**Comment by CendioOssman** [comment]
It should just be a matter of running `snapcraft`. We want to avoid duplicating their documentation, so please check there for how to get snapcraft set up.
