### ISSUE TITLE
Auth error while failing server side with "reading version failed: not an RFB"

### ISSUE THREAD

**Issue by Utopiah** [novnc/noVNC#1687]
**Describe the bug**
Can't connect but can connect with noVNC with other clients e.g KRDC and Remmina.

**To Reproduce**
1. Go to http://192.168.0.229:6080/vnc.html?host=localhost&port=5900
2. Click on Connect
3. Enter credentials (as copy-paste to be 100% sure)
4. Get "New connection has been rejected with reason: password check failed!"

**Expected behavior**
Connect.

**Screenshots**

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/1076655/189089633-61954ff6-36c9-414b-b309-df2b08bd5bd9.png">

**Client (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Browser version: 104.1 (64bits)

**Server (please complete the following information):**
 - noVNC version: current git as time of issue (edc7520)
 - VNC server:  x0vncserver for Arch (TigerVNC Server version 1.12.0, built Nov 13 2021 18:03:45)
 - WebSocket proxy: websockify

**Additional context**
Used `./utils/novnc_proxy --vnc localhost:5900`. 

While checking on the VNC server log I don't see any error message or connection even attempt, unlike when I use other clients.

If I try to connect to http://steamdeck:6080/vnc.html?host=steamdeck&port=6080 it fails right away yet when I fix to http://steamdeck:6080/vnc.html?host=localhost&port=5900 it does prompt for a password.

Finally when I try locally, on the same machine I get `VNCSConnST:  closing 127.0.0.1::39730: reading version failed: not an RFB`

**Comment by Utopiah** [comment]
Might be related to https://github.com/novnc/noVNC/issues/36

**Comment by CendioOssman** [comment]
Yeah, TigerVNC does not support WebSockets, so you need to use a proxy with that server.

I checked the TigerVNC source, and it does not contain the message "password check failed". So I'm afraid the server must be something else.

I can find it in libvncserver though, so I'm guessing you are connecting to x11vnc or vino or something similar.

So please try to figure out what server is actually responding on port 5900, and hopefully you can find the logs and what is going wrong.

I don't see any noVNC issue here as noVNC connects and sends over the credentials properly. So I'll go ahead and close this issue.

**Comment by Utopiah** [comment]
Thanks for the clarification. Any recommendation from https://archlinux.org/packages/?q=vnc ?

**Comment by CendioOssman** [comment]
It depends on what you are trying to do. If you are trying to access your local console, then I would probably suggest x11vnc as that is what gets the most attention for that use case. If you are trying to start a separate session from your local login, then TigerVNC would be my recommendation.

**Comment by Utopiah** [comment]
As TigerVNC seems to cause problems due to the lack of WebSocket support and because I don't specifically need a separate session I'll try x11vnc then and report back. Thanks for the work on noVNC and the prompt reply, sincerely appreciated.

**Comment by Utopiah** [comment]
Works with x11vnc.

**Comment by CendioOssman** [comment]
Glad to hear it. :)
