### ISSUE TITLE
snapcraft does not compile novnc

### ISSUE THREAD

**Issue by lnee94** [novnc/noVNC#1688]
**Describe the bug**

**To Reproduce**
1. git clone https://github.com/novnc/noVNC.git
2. cd noVNC
3. snapcraft
4. then it prints this Issues while validating snapcraft.yaml: The 'version' property does not match the required schema: '@VERSION@' is not a valid snap version string. Snap versions consist of upper- and lower-case alphanumeric characters, as well as periods, colons, plus signs, tildes, and hyphens. They cannot begin with a period, colon, plus sign, tilde, or hyphen. They cannot end with a period, colon, or hyphen.

**Expected behavior**
for a snap file to be out puted
**Screenshots**

**Client (please complete the following information):**
 - OS: ubuntu server 22.04
 - Browser: N.A.
 - Browser version: N.A.

**Server (please complete the following information):**
 - noVNC version: 
 - VNC server: na
 - WebSocket proxy: na
**Additional context**

**Comment by lnee94** [comment]
Note, I get the same error in the 1.3.0 release

**Comment by CendioOssman** [comment]
Ah. I was hoping snapcraft would accept that. The procedure used by the build system is to replace that version. You should be able to do the same manually.

I'll see if I can get something in place that snapcraft accepts without modification.

**Comment by CendioOssman** [comment]
Should be fixed as of d5b8425d42ae0e383010354b6c88197b5b5d407b. You'll get an automatically generated version number now when building directly from the tree.
