### ISSUE TITLE
Can’t connect after few hours

### ISSUE THREAD

**Issue by Jaydenha09** [novnc/noVNC#1694]
**Describe the bug**

**To Reproduce**
1. Start novnc server
2. Connect to server and disconnect and wait few hours 
3. 

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - Browser: Safari
 - Browser version: [e.g. 22]

**Server (please complete the following information):**
 - noVNC version:1.3.0
 - VNC server: Realvnc
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
I'm afraid we're going to need a bit more details. What error are you seeing?

**Comment by CendioOssman** [comment]
No response. Closing.
