### ISSUE TITLE
MacOS meta key (⌘) with a different key has unreliable keyup event

### ISSUE THREAD

**Issue by m1k1o** [novnc/noVNC#1695]
When pressing any combination on MacOS with `⌘` key, keyup event for the second key is not sent.

**To Reproduce**

1. Press `⌘` key.
2. Press and release `V` key.
3. Release `⌘` key.
4. You notice that `V` key is repeatedly written on the screen because keyup event had never been sent.

https://user-images.githubusercontent.com/7534274/192346291-1f4156aa-1a38-44af-8b7f-69b576376719.mov

In logs you can see, that keyup event was not sent, because browser did not trigger that.
![image](https://user-images.githubusercontent.com/7534274/192345114-bc1bbac4-7fea-4286-a6c6-d4a407d0e3f2.png)

**Expected behavior**
Since I released the key I would expect that keyup event is sent.

**Client:**
 - OS: MacOS 12.5
 - Browser: Chrome 105, Firefox 104, Safari 15.6

**Server:**
 - noVNC version: from master c101a31520aba083a85edcb2f3269a826471007a, but the part of the code that handles this was not touched for 2 years.
 - VNC server / WebSocket proxy: n/a, because client sends (not or wrong) information.

**Additional context**
Guacamole client fixes exacly this problem [here](https://github.com/apache/guacamole-client/blob/165bd413c0ab9c55b0c0e3614fcb829ef5f8ca95/guacamole-common-js/src/main/webapp/modules/Keyboard.js#L286-L289) by marking those events as unreliable and sends keyup together with keydown:

**Comment by CendioOssman** [comment]
I can reproduce this here. Odd that we haven't seen this issue in all these years. Thanks for reporting!

This is clearly a browser bug, and ideally something we want them to fix. Do you think you could make sure there is an open bug report with each of the browsers? I could see this in all the major browser (Safari, Chrome, Firefox, Edge).

It doesn't seem to be an OS level bug, as this works fine in TigerVNC. I guess it is a common bug when handling menu accelerators.

**Comment by m1k1o** [comment]
There is this [old archived issue](https://bugs.chromium.org/p/chromium/issues/detail?id=108404) on chromium. It is also very suspicious that it is consistently not working on all broswers. So it rather look like [OS Level](https://stackoverflow.com/a/57153300) limitation/bug or just expected behavior (as with CapsLock). 

Maybe TigerVNC handles it the same way as CapsLock? Although I couldn't find anything relevant in the code.

**Comment by CendioOssman** [comment]
No, TigerVNC gets both the press and release events. I suspect the issue is with how the browsers handles menu shortcuts, something TigerVNC has very little of. The menu code probably steals all release events, even if they are used or not.

That chromium issue should be resurrected. Or a new one added. And WebKit and Firefox should also be informed. I doubt the browsers share any code in this area, unfortunately.

**Comment by CendioOssman** [comment]
I'd ideally still like to make sure we poke the browsers as well. #1698 was a workaround, not a fix, as there might be use cases where it is important to get the real key release events.

**Comment by CendioOssman** [comment]
I've reported the issue to the browsers now:

https://bugzilla.mozilla.org/show_bug.cgi?id=1802465
https://bugs.chromium.org/p/chromium/issues/detail?id=1393524
https://bugs.webkit.org/show_bug.cgi?id=55291

I didn't find any way to report the issue to Edge. Hopefully, they'll get whatever fix Chrome puts in.
