### ISSUE TITLE
Wrong MacOS meta key (⌘) keysym

### ISSUE THREAD

**Issue by m1k1o** [novnc/noVNC#1696]
When pressing `⌘` key on mac os, `XK_Alt_L` and `XK_Super_L` are sent instead of `XK_Meta_L` and `XK_Meta_R`.
![image](https://user-images.githubusercontent.com/7534274/192354707-10b9dca0-0e65-43b9-95d2-6f75668d27ef.png)

They are registered as `XK_Super_L` and `XK_Super_R` despite the name says `Meta`.
https://github.com/novnc/noVNC/blob/c101a31520aba083a85edcb2f3269a826471007a/core/input/domkeytable.js#L46

There is also placeholder for the `Super` keys, where I would say they should be registered.
https://github.com/novnc/noVNC/blob/c101a31520aba083a85edcb2f3269a826471007a/core/input/domkeytable.js#L53

And they are here converted from `XK_Super_L` and `XK_Super_R` to XK_Alt_L` and `XK_Super_L`.
https://github.com/novnc/noVNC/blob/c101a31520aba083a85edcb2f3269a826471007a/core/input/keyboard.js#L135-L140

What is the reason for not seding correct `XK_Meta_` keys?

**Expected behavior** is to send `XK_Meta_L` and `XK_Meta_R`.

**Client:**
 - OS: MacOS 12.5
 - Browser: Chrome 105, Firefox 104, Safari 15.6

**Server:**
 - noVNC version: from master c101a31520aba083a85edcb2f3269a826471007a, but the part of the code that handles this was not touched for 2 years.
 - VNC server / WebSocket proxy: n/a, because client sends (not or wrong) information.

**Additional context**
Guacamole client sends correct `XK_Meta_L` and `XK_Meta_R`, tested on their [test page](https://guacamole.apache.org/pub/tests/guac/keyboard-test.html).
![image](https://user-images.githubusercontent.com/7534274/192354168-d367d818-6de5-4cf0-9e08-370c272248aa.png)

[w3 docs](https://www.w3.org/TR/uievents-key/#keys-modifier) states, that Meta is used for `Apple Command or ⌘ key` and Windows key.

<details>
<summary> Testing on other platforms (click for details). </summary>

**Windows 11**
Testing on Windows reveals, it sends `XK_Super_L` and `XK_Super_R` as expected.
![image](https://user-images.githubusercontent.com/7534274/192357038-c8f90837-1349-4483-a32b-e009f2d63996.png)

Guacamole client sends the same on Windows as on MacOs:
![image](https://user-images.githubusercontent.com/7534274/192357245-138d6d60-ac35-4501-9bc1-347d2536a53f.png)

**Linux: Ubuntu 20.02**
Does not send anything for left Meta, only right.

 `XK_Super_R` as expected.
![image](https://user-images.githubusercontent.com/7534274/192357862-0e84a4fd-8801-4b78-b1e5-dde43b1a156c.png)

Guacamole sends both `XK_Super_R` and `XK_Meta_R`:
![image](https://user-images.githubusercontent.com/7534274/192357715-816be727-ea4d-448f-a0d4-b86cfe9e4026.png)

</details>

This issue blocks #1695. Only once we know what is the correct valid value for meta key, then it can be mocked.

**Comment by CendioOssman** [comment]
I'm afraid the current code is correct, and w3's choice of naming this "Meta" is unfortunate, as it is not the same thing as "Meta" on X11.

The reference case is what would happen on a "normal" X11 system (which mean Linux these days) when these keys are pressed, and the result there is the XK_Super_* keysyms.

Your bug report doesn't mention what practical issues you are seeing, though. What problem is it you are trying to solve here?

**Comment by m1k1o** [comment]
Thanks for the clarification. I was not aware about the naming confusion between w3 and x11, that `Meta` key in w3 is `Super` key in X11. In that case yes, current implementation in [domkeytable is correct](https://github.com/novnc/noVNC/blob/c101a31520aba083a85edcb2f3269a826471007a/core/input/domkeytable.js#L46).

I was confused by _hijacking the left command key as an Alt replacement_, as it is not clearly explained in the code and it is only in [mentioned implementation in TigerVNC](https://github.com/TigerVNC/tigervnc/blob/0a3d464b5662a2be6297eeb64bac2bf8302e17f7/vncviewer/Viewport.cxx#L847-L867). In that case I guess, it is fully expected that the wrong key is sent for MacOs CMD key.

My use-case is to add custom CMD to CTRL translation and I was getting unexpected values for CMD keys.

**Comment by CendioOssman** [comment]
Yeah, it's unfortunately a bit confusing. However, not having it was even more confusing.

It would be nice if it could be documented somewhere, but I'm not sure where we can put it where it would be seen.
