### ISSUE TITLE
noVNC Show disconnect 

### ISSUE THREAD

**Issue by qwas368** [novnc/noVNC#1699]
**Describe the bug**
noVNC  Show disconnect  after enter password.

**To Reproduce**
1. Run ''websockify --web D:\nodejs\node_modules\noVNC-master 9000 10.33.102.33:5900"
2. Open Chrome and go to 127.0.0.1:9000/vnc.html
3. Enter password
4. See Record Log
```
var VNC_frame_data = [
'{15{RFB 003.006\n',
'}17}RFB 003.003\n',
'{18{\x00\x00\x00\x02',
'{18{\xad\xc7\xa64\xf8\x8d\x9d\xb4\x8e\xd0\x06!\x8bL~8',
'}5264}S\xc1\x11\x87d\x94PN+\x06\x8ff\x8c\x9cE\x06',
'{5279{\x00\x00\x00\x00',
'}5279}\x01',
'{5295{\x04\x00\x03\x00  \x00\x01\x00\xff\x00\xff\x00\xff\x10\x08\x00\x00\x00\x00\x00\x00\x00$fccrs1p ( 10.33.33.1, 10.33.102.33 )',
'}5300}\x00\x00\x00\x00 \x18\x00\x01\x00\xff\x00\xff\x00\xff\x00\x08\x10\x00\x00\x00',
'}5300}\x02\x00\x00\x15\x00\x00\x00\x01\x00\x00\x00\x07\xff\xff\xfe\xfc\x00\x00\x00\x10\x00\x00\x00\x15\x00\x00\x00\x05\x00\x00\x00\x02\x00\x00\x00\x00\xff\xff\xff\xe6\xff\xff\xff\x02\xff\xff\xff!\xff\xff\xff \xff\xff\xfe\xfe\xff\xff\xfe\xcc\xff\xff\xfe\xcb\xff\xff\xfe\xc8\xff\xff\xfe\xc7\xff\xff\xfe\xcd\xc0\xa1\xe5\xceWMVd\xff\xff\xff\x11',
'}5300}\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00',
'EOF'];
```

**Screenshots**
![image](https://user-images.githubusercontent.com/26789196/193959590-618ebc2f-fcc1-4419-a6a0-da79f5797c1b.png)

**Client (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Browser version: 106.0.52

**Server (please complete the following information):**
 - noVNC version: 1.3.0
 - VNC server: Ultra Vnc 1.0 on Windows XP
 - WebSocket proxy: websockify 0.10.0

**Additional context**
Ultra VNC Client works, but noVNC doesn't. My VNC Server Setting is 
![image](https://user-images.githubusercontent.com/26789196/193960060-01f93cd7-6771-4b9e-8025-f7c9b5b0b30f.png)

**Comment by CendioOssman** [comment]
I'm afraid the traffic log shows that the server just disconnects after the initial handshake messages. So unfortunately it is impossible to tell what the problem is from the noVNC side of things.

What does the log from websockify say? And can you get a log from UltraVNC?

**Comment by CendioOssman** [comment]
No response. Closing.
