### ISSUE TITLE
Documentation for installing the noVNC client needs to be more complete and inclusive

### ISSUE THREAD

**Issue by gwhizoftv** [novnc/noVNC#1701]
Currently, the documentation to install noVNC client requires snap.
There should be other options to install the noVNC client for MacOS and Windows.
The article pointed to, when trying to install snap for MacOS:

https://forum.snapcraft.io/t/install-snapcraft-on-macos/9607

is from 2019 and implies that snap is not up to date for MacOS.

Also, installing a real cert instead of a self signed cert should be explained
(e.g. Let'sEncrypt) on both the client side and the server side.

Also, when following the snap install instructions for MacOs, as a prerequisite for installing noVNC, we get the following pseudo-error:
sudo snap install novnc
Password:
Interacting with snapd is not yet supported on darwin.
This command has been left available for documentation purposes only.

**Comment by cebas** [comment]
+1

**Comment by CendioOssman** [comment]
noVNC isn't really a stand-alone service, so I'm afraid it's unlikely anything like a snap will show up for other platforms. The snap is a bit of an exception, as it is a quick way to get the test and development setup with websockify up and running. It's not really a production thing, given websockify's limited nature.

The "normal" deployment of noVNC should be using a more classical web server. I.e. noVNC should just be copied in to some web directory somewhere.
