### ISSUE TITLE
Lack of versioning on the dependencies causes trouble

### ISSUE THREAD

**Issue by juanjoDiaz** [novnc/noVNC#1705]
**Describe the bug**
Lack of versioning on the dependencies:
* makes downloads idempotent (2 downloads might not yield the same result)
* makes imposible to run `npm audits`
* doesn't let GitHub's dependabot automatically create a PR to update a version whenever a vulnerability is found

This is a request to revert #1278 and reset specific versions in package.json and add a package-lock.json.

I know that it adds a bit of a maintenance.
But dependabot will take care of the crucial stuff, it's not so hard to every now and then do a general update of dependencies (in my own OSS packages I do so before cutting new releases) and it will provide great benefits.

I'm happy to set all the latests versions and create the package-lock.json, and create a PR if it would be welcomed.

**To Reproduce**
Steps to reproduce the behavior on a MacBook with Node 18.0.0:
1. npm install
2. npm test

**Expected behavior**
The tests run successfully.
Which only happens after manually reinstalling the latest Karma version.

**Screenshots**
When running `TEST_BROWSER_NAME=ChromeHeadless npm test` I get:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/3322485/196517194-e635b36f-2b45-41af-94b5-2f6e36f7ef84.png">

When running `npm test` and opening the browser I get the same:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/3322485/196519186-423ca1c6-009a-43d1-b5b4-7d986c608eaf.png">

**Client (please complete the following information):**
 - OS: MacOS
 - Browser: All browsers
 - Browser version: [e.g. 22]

**Server (please complete the following information):**
 - noVNC version: latests
 - VNC server: not relevant
 - WebSocket proxy: not relevant

**Comment by CendioOssman** [comment]
I'm afraid I don't understand the issue. Or rather, how it is related to the problem you are seeing.

What exactly is triggering those problems? Because I cannot reproduce it here. And how would a package lock help?

**Comment by juanjoDiaz** [comment]
Hi Pierre,

>  Because I cannot reproduce it here

That's exactly the problem 😅
npm installs are not deterministic without a `package-lock.json`.
The install that I get, is not the same that I get and it's not the same that some other contributor or user might get.

Since npm 7 they went further and they are not only deterministic on the versions being installed but also on the directory structure (see [blog post](https://blog.npmjs.org/post/621733939456933888/npm-v7-series-why-keep-package-lockjson.html)).


> how it is related to the problem you are seeing.
What exactly is triggering those problems?

When I do a clean `npm install`, Karma resolves to an old version.
This is probably due to some internal dependency requiring that all version and noVNC requiring any (`*`) version.
So I get an old Karma version that doesn't work.

The solution is to run `npm install karma` after `npm install` which installs the latest version of Karma and solves the issue.


> And how would a package lock help?

A package lock will make installs deterministic and will indicate exactly which dependencies have been proven to work.
Everyone will get the exact same dependency tree and folder directory and there will never be an "it works in my machine" type of issue. Regardess of how uncommon this type of issue might be.

As additional benefits:

Having strict dependencies would allow contributors to run `npm audit` and identify vulnerabilities in the library and would allow that github dependabot automatically create PRs when vulnerabilities are found. Dependabot runs automatically in all GitHub public repos. See an [example](https://github.com/juanjoDiaz/serverless-plugin-warmup/pull/238) in one of my projects.

Having a package lock also would allow us to use `https://docs.npmjs.com/cli/v8/commands/npm-ci` which guarantees 100% that you get what the lock file says whereas npm install simple installs whatever is missing in the `node_modules` folder.

**Comment by CendioOssman** [comment]
> When I do a clean `npm install`, Karma resolves to an old version.
This is probably due to some internal dependency requiring that all version and noVNC requiring any (`*`) version.
So I get an old Karma version that doesn't work.

Ok, so that's a more specific issue. I assume it can be a bit random which order npm traverses the dependency tree. I would have hoped that `'*'` meant "latest", not "any old version you happened to have lying around". Does npm have a way of specifying "latest"?

That is still a bit different than the use case for the package lock. The lock is extremely specific and is for 100% reproducible deployments. We¹ don't do deployments. We do development of a component.

What we want here is a Karma which is new enough to support what we need. Which admittedly isn't `'*'`. But it also isn't `'6.4.1'`. It's rather `'>= 5'`, or whatever version it is, that we are currently implicitly assuming. I have no objections to adding something like that. It would be similar to how we try to keep track of which browser versions we require.

¹ And neither does our users as we only use nodejs/npm for development stuff

> Having strict dependencies would allow contributors to run `npm audit` and identify vulnerabilities in the library and would allow that github dependabot automatically create PRs when vulnerabilities are found. Dependabot runs automatically in all GitHub public repos. See an [example](https://github.com/juanjoDiaz/serverless-plugin-warmup/pull/238) in one of my projects.

This is a problem caused by the lock file, so not a missing benefit. If we don't block updates, then we won't block security fixes.

**Comment by CendioOssman** [comment]
> Does npm have a way of specifying "latest"?

It seems you can use tags, so I think what we want is:

```diff
diff --git a/package.json b/package.json
index 15d6be5..5dc8772 100644
--- a/package.json
+++ b/package.json
@@ -38,36 +38,36 @@
   },
   "homepage": "https://github.com/novnc/noVNC",
   "devDependencies": {
-    "@babel/core": "*",
-    "@babel/plugin-syntax-dynamic-import": "*",
-    "@babel/plugin-transform-modules-commonjs": "*",
-    "@babel/preset-env": "*",
-    "@babel/cli": "*",
-    "babel-plugin-import-redirect": "*",
-    "browserify": "*",
-    "babelify": "*",
-    "core-js": "*",
-    "chai": "*",
-    "commander": "*",
-    "es-module-loader": "*",
-    "eslint": "*",
-    "fs-extra": "*",
-    "jsdom": "*",
-    "karma": "*",
-    "karma-mocha": "*",
-    "karma-chrome-launcher": "*",
-    "@chiragrupani/karma-chromium-edge-launcher": "*",
-    "karma-firefox-launcher": "*",
-    "karma-ie-launcher": "*",
-    "karma-mocha-reporter": "*",
-    "karma-safari-launcher": "*",
-    "karma-script-launcher": "*",
-    "karma-sinon-chai": "*",
-    "mocha": "*",
-    "node-getopt": "*",
-    "po2json": "*",
-    "sinon": "*",
-    "sinon-chai": "*"
+    "@babel/core": "latest",
+    "@babel/plugin-syntax-dynamic-import": "latest",
+    "@babel/plugin-transform-modules-commonjs": "latest",
+    "@babel/preset-env": "latest",
+    "@babel/cli": "latest",
+    "babel-plugin-import-redirect": "latest",
+    "browserify": "latest",
+    "babelify": "latest",
+    "core-js": "latest",
+    "chai": "latest",
+    "commander": "latest",
+    "es-module-loader": "latest",
+    "eslint": "latest",
+    "fs-extra": "latest",
+    "jsdom": "latest",
+    "karma": "latest",
+    "karma-mocha": "latest",
+    "karma-chrome-launcher": "latest",
+    "@chiragrupani/karma-chromium-edge-launcher": "latest",
+    "karma-firefox-launcher": "latest",
+    "karma-ie-launcher": "latest",
+    "karma-mocha-reporter": "latest",
+    "karma-safari-launcher": "latest",
+    "karma-script-launcher": "latest",
+    "karma-sinon-chai": "latest",
+    "mocha": "latest",
+    "node-getopt": "latest",
+    "po2json": "latest",
+    "sinon": "latest",
+    "sinon-chai": "latest"
   },
   "dependencies": {},
   "keywords": [
```

**Comment by juanjoDiaz** [comment]
> That is still a bit different than the use case for the package lock. The lock is extremely specific and is for 100% reproducible deployments. We¹ don't do deployments. We do development of a component.

I would't say that it's for reproducible deployment.
It's for deterministic installs.
And that is important for your 2 user groups: end users of noVNC (i.e. people that use solutions based on noVNC) and developer of noVNC (people, like me, that contribute to the project and most likely building solutions for users using noVNC).

Your end users do deployments of (solutions that include) noVNC and they want to know what they are deploying.
They want to generate a BOM of their solution and check if there are known vulnerabilities.
E.g., A couple of years ago I used noVNC on a project while I was working in a highly regulated industry.
We build a no-VNC solution to manage testing environments. This solution included noVNC and it was mandatory to control the versions of all library and validate them (we couldn't even pull directly from npm). So, I ended up forking the project and having to spend the double effort to offer deterministic dependencies to the end user since the project itself doesn't.

I understand that Cendio as a company, sells its own noVNC-based solution to it's customers and that's your priority. That's totally fair and I totally support this. I'm sure that when you package your solution to deliver it, you know exactly which versions of dependencies are going in and do your security checks.
However, noVNC is an open-source projects, so you should keep in mind the end users that are not direct Cendio customers. I think that it's a responsible thing to make it as safe as posible for other consumers of noVNC as well as for the Cendio client.

Your developers, like me, download the repo and work on it locally.
Without having the concrete dependencies, thinks like what happen to me might happen.
E.g., Karma release version 7 which is incompatible with 6. All the sudden, I run an install and things don't work.
Until someone creates a PR fixing the config, the solution won't work unless you manually change the version back to 6.


> What we want here is a Karma which is new enough to support what we need. Which admittedly isn't '*'. But it also isn't '6.4.1'. It's rather '>= 5', or whatever version it is, that we are currently implicitly assuming. I have no objections to adding something like that. It would be similar to how we try to keep track of which browser versions we require.

If you see my example just above. I don't think that it's exactly like that.
You don't need an exact version. But you don't always need the latest.
Let me give you another example.
Karma 6.4.1 is found to have a severe vulnerability. You could simply set 6.4.0 and make sure that your users are safe (or dependabot might do it for you). However, if you simply use `latest`, this won't be the case.

> This is a problem caused by the lock file, so not a missing benefit. If we don't block updates, then we won't block security fixes.

Not really.
You might have a vulnerability present in all packages newer than 6.4.1 where the latest is 6.4.5.
While the team solves the issue, you might be able to simply use 6.4.0. However, if you simply get latests and the dependency team doesn't fix the issue for a while. You are stuck with the vulnerability.

Also, if I run `npm install` and get a specific version. Even if in the future I run it again, npm detects that there ir already a valid package in `node_modules` and doesn't update.

> It seems you can use tags, so I think what we want is

npm tags are tricky.
If a library with a latests 7.5.1 releases a vulnerability fix for it as 7.5.2 and then back-port the fix for version 6.8.2 so users of v6 can still get the fix in, the latest tag will point to 6.8.2 unless the maintainer manually changes it.
This is something that I have seen in a few cases.


Sorry for the very long response.
I just wanted to make it very clear that this is not about me having to manually update some dependencies.
It's about compliance and about making things easier for developers and end users that rely on noVNC.

**Comment by samhed** [comment]
I understand your point @juanjoDiaz, and I agree that it could help some people if we would get this type of workflow. However, I'm uncertain if this is practically feasible. As I see it, this would mean more work for the noVNC team. As always, we don't have much time to spare until the noVNC team grows in numbers.

Personally, I'm fine with leaving this responsibility to the developers and the users who integrate noVNC into their products.

**Comment by juanjoDiaz** [comment]
Hi guys,

I really don't think that keeping dependencies up-to-date is such a big effort.
It's a matter of having a recurring task to run
```sh
// See outdated dependencies
npm outdated
// Automatically update all minor/patch version
npm update
// Fix vulnerabilities updating minor/patch versions
npm audit fix
```

It could be put in a scheduled action or even I or some other contributor could put something in my calendar and do a PR once a month or so.

From my point of view, one of the main advantages of open-sourcing a project is that you get a bunch of eyes on the code and you benefit from the crowd to identify vulnerabilities, bugs, etc.
Leaving this to individual developers removes that benefit and forces each and every developer to play around with dependencies to get things to work (if something like my karma issue happens) and to lock dependencies and do a full round of testing to ensure that everything works and there are no vulnerabilities.

That said, I've tried to explain why I think that this is a good idea and an improvement to the project.
But at the end of the day, you guys are the owners.
So it's up to you...
