### ISSUE TITLE
Garbled Chinese characters on the clipboard

### ISSUE THREAD

**Issue by lnden** [novnc/noVNC#1708]
**Describe the bug**
There is no problem using the clipboard in English, but garbled characters appear in Chinese

**To Reproduce**

1.RFB.addEventListener("clipboard", (e) => {
      console.log(e.detail.text)  // 测试 => ²âÊÔ
 });

2.When you press Ctrl + C to copy the Chinese "test" on the remote desktop, garbled " ²âÊÔ" is displayed

**Expected behavior**

Should output Chinese "test"

**Screenshots**

**Client (please complete the following information):**
 - os: window
 - Browser: chrome,
 - Browser version: 98.0.4758.10

**Server (please complete the following information):**
 - noVNC version: master /1.3
 - VNC server: tightVNC
 - WebSocket proxy: [e.g. websockify]

**Additional context**

**Comment by lnden** [comment]
Okay, thank you very much

**Comment by xianshenglu** [comment]
@CendioOssman  Hi, I tested in TightVNC Viewer with TightVNC server, it works with Chinese characters.

**Comment by CendioOssman** [comment]
Ah, I see that TightVNC has their own extension for Unicode clipboard support. Unfortunately, it requires a lot of TightVNC specific infrastructure. I don't think it is something we'll be able to integrate cleanly in to TigerVNC, unfortunately.

**Comment by Zephylaci** [comment]
@CendioOssman hi，i use UltraVNC 1.4.3.6，Accessing windows from a browser on a MAC, I used the Clipboard tool on the left to copy and paste text, which worked well when it was in English. When using Chinese, copying text from windows to the clipboard is normal, but not the other way around.Even text copied from windwos becomes "?? "when modified on a MAC. Any suggestions? thank you

**Comment by CendioOssman** [comment]
That sounds like a different issue than the one described here. Please open a new issue with all the details of your setup.
