### ISSUE TITLE
When use tab keyboard to control web page，When use enter the canvas in vnc，it will not tab out of this area

### ISSUE THREAD

**Issue by lovertommorrow** [novnc/noVNC#1711]
**Describe the bug**
When use tab keyboard to control web page，When use enter the canvas in vnc，it will not tab out of this area

**To Reproduce**
1. use keyboard tab to control web Page 
2. When focus on the vnc area, it will loop in the vnc area, can not jump out of this area.

**Expected behavior**
When go down of this vnc area, we use this tab can jump this area, and then we can control others area of this web page.

**Screenshots**

**Client (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Browser version: [e.g. 22]

**Server (please complete the following information):**
 - noVNC version: [e.g. 1.0.0 or git commit id]
 - VNC server: [e.g. QEMU, TigerVNC]
 - WebSocket proxy: [e.g. websockify]

**Additional context**

**Comment by CendioOssman** [comment]
Tab is a popular key to use inside the session, so I don't think we want to stop sending that. But there might be other ways to break the focus that we can explore.

Could you give more context to your setup and use case, though? The default application doesn't really have much else you want to move the keyboard focus to.

**Comment by xianshenglu** [comment]
![image](https://user-images.githubusercontent.com/23273077/200163090-3dd4fff0-3960-4a9e-8b05-6b731fab0881.png)

Once the focus was switched from buttons out of VNC to the VNC by tab key, users can not get out of the VNC with the keyboard anymore. The focus will always be limited in the VNC.

**Comment by CendioOssman** [comment]
Thank you. I think I understand your use case a bit better now.

Have you modified noVNC, though? We set `tabIndex` to `-1`, which means it shouldn't be possible to tab to it.

**Comment by CendioOssman** [comment]
No response. Closing.
