### ISSUE TITLE
Is there a way to send a parameter via URL?

### ISSUE THREAD

**Issue by lucasmc20** [novnc/noVNC#1714]
@TrumanGao, would like to pass a parameter via URL so that my DEBIAN/Mate Desktop can read this new parameter.

Example: URL.com/novnc/?custom=https://google.com.br

With this I want to open chrome and run with the parameter passed.

**Comment by CendioOssman** [comment]
No, I'm afraid there is no mechanism in VNC to send arbitrary things like that.
