### ISSUE TITLE
Red and Blue colours appear swapped when connecting to the Qt embedded VNC server

### ISSUE THREAD

**Issue by dgtrapeze** [novnc/noVNC#1715]
**Describe the bug**
I wanted to see if it was possible to get novnc to connect to a standard QT5 application running under the QT embedded VNC server.  QT 5.8 and later allows any QT application to be presented via VNC via a command line argument.

To get going, I just ran the QT application as "application -platform vnc" which starts a VNC server on port 5900 by default.  I then connected to this server with TightVNC and Gnome Remote Desktop Viewer (Vinagre) and both connected fine to the application and everything looked good.

So I started websockify to proxy port 5900 and then used https://novnc.com/noVNC/vnc.html to connect to localhost:6080.

I immediately saw the application - but the colours were off.  Green seems OK, but blues were appearing as shades of orange.

**To Reproduce**
1. Find a QT 5 application.
2. Run it with -platform vnc command line option
3. Connect to it via novnc+websockify

I tried a couple of different QT5 applications as well as a couple of platforms (I tried centos7 and debian 11) and a couple of QT versions (tried 5.9 and 5.15 of QT).  All seem to have the Red and Blue colours reversed.

**Expected behavior**
See the same colours as you get when accessing the QT VNC server via other clients.

**Screenshots**
For these screen shots I used qt5ct on centos7 using QT 5.9
This first image is of the application running as a standard application
![image](https://user-images.githubusercontent.com/93233114/201604480-536d87ba-1f88-46ca-b926-c942f3cf81cb.png)

This is the same application as seen inside gnome's remote desktop viewer
![image](https://user-images.githubusercontent.com/93233114/201604628-ae64f6bb-2816-4638-9cc4-4605b317968a.png)

And this is inside novnc running in firefox
![image](https://user-images.githubusercontent.com/93233114/201604770-89bd5fb8-6cc4-4a44-85b4-8baa4b626236.png)

I realize I didn't pick the most colorful application for this test, but the tab highlighter is supposed to be blue and the preview is supposed to be a brown colour.  But novnc shows the tab highlighter as orange and the preview as a grey/blue colour.

**Client (please complete the following information):**
 - OS: Centos 7
 - Browser: firefox
 - Browser version: 91.13

**Server (please complete the following information):**
 - noVNC version: 1.3.0
 - VNC server: QT Embedded VNC server
 - WebSocket proxy: websockify

**Additional context**
I went back through novnc release notes and saw that there was a change to the pixel order in 0.6.1.  So I setup novnc 0.5.1 and tried it and, it worked but was extremely slow.

Unfortunately, I'm not proficient enough at VNC to know why other clients can work out the colour order while novnc cannot.  I manually changed the latest novnc code and switched the Red and Blue colours and things worked for my use case, but that doesn't seem like a fix.

**Comment by CendioOssman** [comment]
That very much looks like a bug in QT, unfortunately. In VNC the client decides the colour order, and the server has to respect that. It seems like QT doesn't. :/

noVNC chooses a different colour order compared to most other clients, which explains why you only see the issue with noVNC. The reason we do this is that browsers want a different colour order compared to most other graphics APIs.

I'm afraid there likely isn't much we can do in our end as the colour order is fixed in noVNC. I'm going to have to ask you to file a bug with CentOS or QT for this.

What exactly was it you changed in noVNC to get it working?

**Comment by dgtrapeze** [comment]
To get novnc working, we reverted the changes to core/display.js done in https://github.com/novnc/noVNC/commit/6a19390baafedbc2729597fe244010a2aaadc068.  Specifically we returned the _bgrxImageData method (although with modifications to work on the latest code - specifically to use 
`let img = new ImageData(width, height);`
rather than
`const img = this._drawCtx.createImageData(width, height);`
and changed the _setFillColor method back.

In terms of protocol, it appears the server sends its preference for pixel format first in the server init message.  novnc seems to read this request in https://github.com/novnc/noVNC/blob/master/core/rfb.js#L1974 but basically ignores it.  It then sends back its pixel format in a setPixelFormat message which is https://github.com/novnc/noVNC/blob/master/core/rfb.js#L3165.

Novnc asks for 32 bits per pixel, little endian, true color, with a red shift of 0, green shift of 8 and blue shift of 16.

Qt's VNC server code is available publicly so it is easy to see how the QT side works.  It is only 2 main classes.

The place where they seem to read the pixel format from the client is 
https://github.com/qt/qtbase/blob/5.15.2/src/plugins/platforms/vnc/qvncclient.cpp#L461
which then goes into 
https://github.com/qt/qtbase/blob/5.15.2/src/plugins/platforms/vnc/qvnc.cpp#L265
to read the request from the wire.  So it seems to try to read the client's requested pixel format and honor it

Where they use that to create the pixel data is 
https://github.com/qt/qtbase/blob/5.15.2/src/plugins/platforms/vnc/qvncclient.cpp#L100

At first glance everybody seems to be doing the correct thing.  But somewhere the bytes are being reversed....

**Comment by CendioOssman** [comment]
Thanks for the detective work. That unfortunately clearly shows that the bug is in Qt.

That other clients work is more luck than design. E.g. TigerVNC will change the colour order depending on the graphics card. It does not respect the server format in any way.

Unfortunately, that means that there isn't much we can do except ask you to file a bug report with Qt. We want to avoid adding and maintain a lot of extra handling in noVNC just because of bugs in Qt, so reverting 6a19390baafedbc2729597fe244010a2aaadc068 is not an option.

**Comment by dgtrapeze** [comment]
I understand.

While I'll raise the Qt bug, I suspect it will be many years for the fix to end up on a significant number of devices via OS packages.  Qt5 is no longer supported and Qt6 is only available on the latest and greatest OS versions.

However, now that I know what the issue is, changing noVNC to work with Qt isn't that hard.  Qt only supports raw encoding it appears (they have the code for Hextile on their end but it appears to be never used) and noVNC already has a loop where it goes through all the data for raw mode at https://github.com/novnc/noVNC/blob/master/core/decoders/raw.js#L53, so adding the 3 lines extra lines to switch byte 0 and byte 2 in this loop when the server is Qt is only an extra couple of lines.

For your own interest, or others that may trip over this same issue in the future, here is my patch to add the Qt support
[patch.zip](https://github.com/novnc/noVNC/files/10027233/patch.zip)

**Comment by dgtrapeze** [comment]
For reference, QT bug I raised is https://bugreports.qt.io/browse/QTBUG-108558

**Comment by CendioOssman** [comment]
Unfortunately, I don't think we have any way of detecting that the other end is Qt.

I would also suspect that the bug depends on the server hardware. E.g. this bug will not appear if the server is big endian.

Perhaps there is some way you can force Qt to do some conversion. E.g. force a 16-bit screen depth.

**Comment by dgtrapeze** [comment]
As per the patch I supplied I just look at the name returned by the server to detect it is Qt.  I could look at the endian returned by the server in the negotiation message, but I doubt there are many big endian Qt deployments - at least not as many as are little endian.  x86 and arm should all be little endian.

Qt does allow the colour depth to be set on the command line (via the -platform vnc:depth=16 option) so I can see if that 'bypasses' the bug.

**Comment by dgtrapeze** [comment]
It worked!  

Running the Qt app in 16 bit colour made noVNC work.  I used the websockify and novnc supplied by debian 11 packages for the test

```
http://deb.debian.org/debian bullseye/main amd64 python3-websockify amd64 0.9.0+dfsg1-3 [44.1 kB]
http://deb.debian.org/debian bullseye/main amd64 novnc all 1:1.0.0-3 [820 kB]
```

And ran the qt app with 
`-platform vnc:depth=16`

And it displayed with the correct color order.

**Comment by CendioOssman** [comment]
Great! Glad to hear there's a workaround!

**Comment by dgtrapeze** [comment]
I'd try running the Qt app with

-platform vnc:depth=16

to confirm you did have the same issue.  In 16 bit mode, Qt works correctly.  If that works, then you are likely having the same issue.

As for why the patch might not have worked, I cannot really say.  It works for me.  It does look for the server name of "Qt for Embedded Linux VNC Server" to enable the 'workaround' (see [https://github.com/qt/qtbase/blob/dev/src/plugins/platforms/vnc/qvncclient.cpp#L331](https://github.com/qt/qtbase/blob/dev/src/plugins/platforms/vnc/qvncclient.cpp#L331)), so maybe your version uses a different name for the server.
