### ISSUE TITLE
caught signal: 11 

### ISSUE THREAD

**Issue by NoAccount1** [novnc/noVNC#1716]
**Describe the bug**
When I try to connect to the VNC server with noVNC.com, the server exit with error code 11 and the website show "Échec de connection au server" (in french)

**To Reproduce**
1. Run `x11vnc`
2. Connect with noVNC.com

**Expected behavior**
Connection to the VNC server

**Client (please complete the following information):**
 - OS: Linux 6.0.8-arch1-1 (EndeavourOS)
 - Browser: Safari IPadOS 15.5
 - Browser version: Safari 15.5 I guess ?

**Server (please complete the following information):**
 - noVNC version: 1.3.0
 - VNC server: x11vnc
 - WebSocket proxy: I don't know

**Additional context**
When I try to connect without encryption it doesn't connect to anything
Running `x11vnc -ssl` and trying to connect with encryption doesn't work neither but doesn't stop VNC server
log : 
```log
18/11/2022 11:40:33 SSL: accept_openssl(OPENSSL_VNC)
18/11/2022 11:40:33 SSL: spawning helper process to handle: 192.168.242.144:61613
18/11/2022 11:40:33 SSL: helper for peerport 61613 is pid 43501: 
18/11/2022 11:40:33 connect_tcp: trying:   127.0.0.1 20000
18/11/2022 11:40:34 check_vnc_tls_mode: waited: 0.000065 / 1.40 input: SSL Handshake
18/11/2022 11:40:34 SSL: ssl_init[43501]: 10/10 initialization timeout: 20 secs.
18/11/2022 11:40:34 SSL: ssl_helper[43501]: SSL_accept() *FATAL: -1 SSL FAILED
18/11/2022 11:40:34 SSL: error:0A000126:SSL routines::unexpected eof while reading
18/11/2022 11:40:34 SSL: ssl_helper[43501]: Cipher: TLSv1.3 TLS_AES_128_GCM_SHA256 Proto: unknown
18/11/2022 11:40:34 SSL: accept_openssl: cookie from ssl_helper[43501] FAILED. 0
18/11/2022 11:40:35 SSL: accept_openssl(OPENSSL_VNC)```

**Comment by NoAccount1** [comment]
#1539

**Comment by NoAccount1** [comment]
Already reported by #1539

**Comment by NoAccount1** [comment]
I also tried on my phone (Android 12.1 with Firefox Focus 107.1.0 AND Chrome 107.0.5304.105) and got the same error

**Comment by NoAccount1** [comment]
Forgot to say that x11vnc is working with VNC Viewer on Android

**Comment by NoAccount1** [comment]
After that I tried to use websockify alongside to x11vnc (even if I think x11vnc already support websocket) and now I get this error :
```log
handler exception: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1091)
```

**Comment by CendioOssman** [comment]
Like #1539, I'm afraid this is a bug in your server that will need to be reported to them. It's not something that noVNC can fix.

The error from websockify seems consistent with what would happen if x11vnc would crash.

So, unfortunately, it seems like noVNC is provoking some bug in x11vnc. Please report the issue to them, and hopefully they can provide a fix.
