### ISSUE TITLE
Blue and Red components exchanged connecting an embedded linux server

### ISSUE THREAD

**Issue by alemaccaferri** [novnc/noVNC#1718]
Connecting (via websockify) to a linux embedded server the colors appear wrong: the blue and red RGB components are exchanged.
Using the regular VNC client (via TCP) the colors are good.

server OS is a embedded linux on a imx6ul-var-dart board ver.5.4.142

Browser: Chrome Ver. 107.0.5304.107

**Comment by CendioOssman** [comment]
This unfortunately sounds like #1715, which means that it is a bug in the VNC server. Do you know what VNC server is used on that board?

**Comment by alemaccaferri** [comment]
> This unfortunately sounds like #1715, which means that it is a bug in the VNC server. Do you know what VNC server is used on that board?

Exactly the same issue. Solved with the diff patch.
Thank You.
