### ISSUE TITLE
script ended when closing terminal

### ISSUE THREAD

**Issue by projetosfsi** [novnc/noVNC#1719]
I followed the step by step and got everything working.

But I have 2 requests if these resources do not exist.

1) First Question

I'm using NOVNC to open directly through the WEB

sudo ./utils/novnc_proxy --vnc localhost:5901 --listen 8443

https://fqdn.com:8443/vnc.html?host=fqdn.com&port=8443&resize=scale&password=123456

Everything is working perfectly

But when I close the terminal it stops working.
How could I keep it running even with the terminal closed?

2) Second Question

I would like to have several users, each connected to different areas, is there a place where I can create these other users?

**Comment by CendioOssman** [comment]
I see you've also sent the same question to the group, so I'll go ahead and close this issue so that we don't get duplicate discussions.
