### ISSUE TITLE
Login Error with System Users

### ISSUE THREAD

**Issue by projetosfsi** [novnc/noVNC#1721]
**Describe the bug**
I have an Ubuntu Server 20.04 and I installed the following packages.

tightvncserver

tigervnc-standalone-server tigervnc-xorg-extension tigervnc-viewer

numpy

websockify

Then I downloaded noVNC and ran the server, everything worked perfectly on my FQDN domain

https://share.mydomain.org.br:8443/vnc.html?autoconnect=true&host=share.mydomain.org.br&port=8443&encrypt=1&resize=scale&password=123456

But when I try to connect with another system user I always open the same desktop

https://share.mydomain.org.br:8443/vnc.html?autoconnect=true&host=share.mydomain.org.br&port=8443&encrypt=1&resize=scale&username=user002&password=123456

**Expected behavior**
According to the documentation the expected result would be for me to connect in another session, having a clean desktop to use.
I noticed in the browser that the connection message is always a text saying that I am logged in as root.

But the correct thing would be for me to connect with the Linux system user that I put in the URL

**Server (please complete the following information):**
  - noVNC version: [1.3.0]
  - VNC server: [TigerVNC]
  - WebSocket proxy: [websockify]

**Comment by CendioOssman** [comment]
I'm afraid that is a server issue, as noVNC has no control over what desktop the server will present. Most server will unfortunately not give you different desktops depending on what user you use for authentication.

The usual way for VNC is to use different ports for different users. websockify also has a mechanism to select different VNC servers based on the websocket URL:

https://github.com/novnc/websockify/wiki/Token-based-target-selection

**Comment by projetosfsi** [comment]
> 

The command I use to start the vnc server is this one.

./utils/novnc_proxy --vnc localhost:5901 --listen 8443 --cert /etc/letsencrypt/live/share.mydomain.org.br/fullchain.pem --key /etc/letsencrypt/live/

And that's it, I can log in perfectly using my URL

Following the tip I tried changing the command to

./utils/novnc_proxy --vnc localhost:5902 --listen 8444 --cert /etc/letsencrypt/live/share.mydomain.org.br/fullchain.pem --key /etc/letsencrypt/live/

When I access the url with the new port I have the following message in the terminal

handler exception: [Errno 21] Is a directory

And when I try to open the url on port 8444 it does not open

**Comment by projetosfsi** [comment]
would anyone know how to make noVNC obey the command?
