### ISSUE TITLE
keystrokes repeating

### ISSUE THREAD

**Issue by gopalsidleghatta** [novnc/noVNC#1723]
**Describe the bug**
Hello Team, We have the noVNC client on Windows Laptop , connected to VNC server running on Linux and sharing a X Application.
We observe that when we type a number, it gets repeated several times as if like the keydown is not released. We have set the auto repeat off 
xset -r r off
xset q | grep repeat
  auto repeat:  off    key click percent:  0    LED mask:  00000000 

**To Reproduce**
1. noVnc client on windows connect to X Application on Linux
2. in the browser open the Developer tools --> sources -> event listener and choose keydown event listener in the keyboard event
3. type a number in the browser , the keydown event is seen and then continue the application, the number repeats forever

**Expected behavior**
One key press event , should reflect only one character and not repeat that character forever

**Server (please complete the following information):**
 - noVNC version: 1.3.0
 - VNC server: tightvnc on linux
 - WebSocket proxy: [websockify]

**Comment by CendioOssman** [comment]
Keyboard repeat is a tricky area where there have historically been some bugs.

Would you mind enabling debug mode in noVNC, and see what log entries you get in the browser console when key repeats are happening?

Could you also try using TigerVNC as a server? It's a server we know handles key repeat correctly.

**Comment by funnykanth** [comment]
Hi @CendioOssman,

The issue reported by @gopalsidleghatta is happening only for numbers, for alphabets its working fine.

For any number associated keyboard event, we get the following:
 keydown event -->  we are getting keycode as 231 and key as the user typed key
 keyup event --> we are getting keycode as 231 and key as undefined

Following are the log event:
**keydown:**
{
  "isTrusted": true,
  "altKey": false,
  "bubbles": true,
  "cancelBubble": false,
  "cancelable": true,
  "charCode": 0,
  "code": "",
  "composed": true,
  "ctrlKey": false,
  "defaultPrevented": false,
  "detail": 0,
  "eventPhase": 2,
  "isComposing": false,
  **"key": "3",
  "keyCode": 231,**
  "location": 0,
  "metaKey": false,
  "repeat": false,
  "returnValue": true,
  "shiftKey": false,
  "type": "keydown",
  "which": 231
}


**keyup:**

{
  "isTrusted": true,
  "altKey": false,
  "bubbles": true,
  "cancelBubble": false,
  "cancelable": true,
  "charCode": 0,
  "code": "",
  "composed": true,
  "ctrlKey": false,
  "defaultPrevented": false,
  "detail": 0,
  "eventPhase": 2,
  "isComposing": false,
  **"key": "Unidentified",
  "keyCode": 231,**
  "location": 0,
  "metaKey": false,
  "repeat": false,
  "returnValue": true,
  "shiftKey": false,
  "type": "keyup",
  "which": 231
}

**Comment by CendioOssman** [comment]
Which browser is that from? I'm afraid those events look broken (at least `code` is incorrect), so that might be the cause of the issue.

**Comment by CendioOssman** [comment]
No response. Closing.
