### ISSUE TITLE
Simple building in Docker

### ISSUE THREAD

**Issue by AlexanderZhirov** [novnc/noVNC#1724]
I want to integrate VNC into my website for remote connection to various hosts, so I'm trying to build a Docker image.
I'm trying to build my own build. The image starts, but I can't connect to any remote host. Tell me, please, what did I miss?

```dockerfile
FROM alpine:latest
RUN apk add --no-cache bash python3 py3-numpy
ADD vnc /var/vnc
EXPOSE 6080
CMD ["bash", "-c", "/var/vnc/utils/novnc_proxy --listen 6080"]
```

```sh
$ docker run --name myvnc --rm -p 6080:6080 vnc:latest
Warning: could not find self.pem
Using local websockify at /var/vnc/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /var/vnc
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5900


Navigate to this URL:

    http://620c4b745c72:6080/vnc.html?host=620c4b745c72&port=6080

Press Ctrl-C to exit
```

![изображение](https://user-images.githubusercontent.com/37277056/206122377-bf6360d8-f958-4887-961b-f0b2df948a8d.png)

Or am I doing something completely wrong? Or do I need to open other ports? I don't quite understand how it works yet.

**Comment by AlexanderZhirov** [comment]
In general, my goal, knowing the IP address, port and password, is to connect via a browser to a remote computer via VNC. To do this, I want to run noVNC in Docker. The simplest build.

**Comment by AlexanderZhirov** [comment]
In general, as I understand it, if I want to connect remotely, I need to do it through a proxy websocket. At the same time, I need to specify the `--vnc` key for a specific PC. And if I want to dynamically generate a connection path via a GET request, how can I do this?

![изображение](https://user-images.githubusercontent.com/37277056/206145805-62852019-33bd-4927-8b3c-6e38baf00c0f.png)

To avoid specifying each PC when running the script. If I run it in Docker, I need to run the script 1 time. And in the GET request, generate a connection to a particular PC.

**Comment by CendioOssman** [comment]
I see you've asked the same question in the noVNC group, which is also a better place for deployment questions like these. So I'll go ahead and close this issue so we don't have multiple discussions for the same thing.
