### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by sulfatchlorid** [novnc/noVNC#1725]
**Describe the bug**

Starting novnc results in the error: PermissionError: [Errno 1] Operation not permitted

**To Reproduce**
1. snap install novnc
2. novnc --listen 6080 --vnc 10.0.2.1:5901 

**Expected behavior**
novnc running

**Screenshots**

root@master:~> novnc --listen 6080 --vnc 10.0.2.1:5901
/snap/novnc/8/bin/bash: warning: setlocale: LC_ALL: cannot change locale (de_DE.UTF8)
Warning: could not find self.pem
Using installed websockify at /snap/novnc/8/bin/websockify
Starting webserver and WebSockets proxy on port 6080

Navigate to this URL:

    http://master:6080/vnc.html?host=master&port=6080

Press Ctrl-C to exit

WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /snap/novnc/8
  - No SSL/TLS support (no cert file)
Traceback (most recent call last):
  File "/snap/novnc/8/bin/websockify", line 33, in <module>
    sys.exit(load_entry_point('websockify==0.9.0', 'console_scripts', 'websockify')())
  File "/snap/novnc/8/lib/python3.6/site-packages/websockify/websocketproxy.py", line 726, in websockify_init
    server.start_server()
  File "/snap/novnc/8/lib/python3.6/site-packages/websockify/websockifyserver.py", line 742, in start_server
    tcp_keepintvl=self.tcp_keepintvl)
  File "/snap/novnc/8/lib/python3.6/site-packages/websockify/websockifyserver.py", line 489, in socket
    sock.listen(100)
PermissionError: [Errno 1] Operation not permitted

Terminating WebSockets proxy (1676056)
/snap/novnc/8/novnc_proxy: line 67: kill: (1676056) - No such process

**Client (please complete the following information):**
 uname -a
Linux master 5.3.0-0.bpo.2-amd64 #1 SMP Debian 5.3.9-2~bpo10+1 (2019-11-13) x86_64 GNU/Linux

**Server (please complete the following information):**
 - noVNC version: snap
 - VNC server: tigervnc
 - WebSocket proxy: snap

**Comment by CendioOssman** [comment]
Sounds like the snap has got extra restrictions somehow. @tkedwards, do you know what might be going on here?

**Comment by tkedwards** [comment]
It looks like that the cert files need to be somewhere the Snap has access to:
If you want to use certificate files, due to standard Snap confinement restrictions you need to have them in the /home/<user>/snap/novnc/current/ directory. If your username is jsmith an example command would be:

novnc --listen 8443 --cert ~jsmith/snap/novnc/current/self.crt --key ~jsmith/snap/novnc/current/self.key --vnc ubuntu.example.com:5901

**Comment by sulfatchlorid** [comment]
Ok, i found it:
=> snap install core
This will update snap (in my case to version 2.57.6) and then novnc starts.

The issue can be closed. Thanks.

**Comment by sulfatchlorid** [comment]
newer version of snapd needed. Instruction how to create key/cert as documentation update could be added in the README.
