### ISSUE TITLE
noVNC through SSH tunneling

### ISSUE THREAD

**Issue by hl01** [novnc/noVNC#1726]
Hi, 

I realize this is a longshot but maybe someone has done it. 

I'm running an SSH tunnel with the help of https://github.com/boringproxy/boringproxy in order to reach the machine noVNC is running on. The noVNC 1.3.0 setup works over local IP, however it seems to be stuck at "connecting" once I forward everything. 

There's nothing in the logs (it just hangs on connecting). 

Could anyone steer me in the right direction?

**Comment by CendioOssman** [comment]
I suspect boringproxy only supports regular HTTP, and not things like WebSockets. I suggest you ask them if it is possible to tunnel WebSockets, and how that should be configured. I'm afraid we don't have any expertise with boringproxy.
