### ISSUE TITLE
Moving hardware mouse without drag ignored on Chrome Android

### ISSUE THREAD

**Issue by yousefamar** [novnc/noVNC#1727]
**Describe the bug**

Ok, this is a bit of a weird one and has me scratching my head, so please bear with me!

I'm on the latest Chrome for Android, with a hardware mouse connected to my phone. I'm using Samsung DeX to use the browser on a larger monitor, but I doubt this is relevant.

On Chrome Android, mouse movements are not detected by noVNC, _unless_ mouse buttons are pressed (e.g. dragging).

However, other browsers (Brave, Kiwi) _do_ detect all mouse movements just fine. Not sure what's different about Chrome.

You can't reproduce this with touch events because every movement with touch is a "drag".

**To Reproduce**

1. Open Chrome on Android (in my case, fresh install)
2. Connect a hardware mouse (in my case, wired, but Bluetooth will probably behave the same)
3. Go to a noVNC session, move mouse without clicking any buttons
4. The movement will only update the host when you click

**Expected behavior**

That the mouse movement moves the VNC mouse.

**Client (please complete the following information):**
 - OS: Android 13, Samsung Galaxy S22 Ultra (SM-S908B/DS)
 - Browser: Chrome Android
 - Browser version: 108.0.5359.79

**Server (please complete the following information):**
 - noVNC version: 1.3.0-g99cf540
 - VNC server: TigerVNC
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
Unfortunately, it sounds like a Chrome bug, rather than a noVNC one.

Could you try out this page and see if you get any events when you move the mouse around using Chrome:

https://domeventviewer.com/mouse-event-viewer.html

**Comment by yousefamar** [comment]
Thanks for the link, I was looking for something like that! `mousemove` only fires on click indeed. I've narrowed this down even further -- it seems specific to Chrome on Samsung devices (or at least my S22, with or without DeX). I tried Chrome on an old Pixel 4, and it registers `mousemove` just fine. By coincidence, I found the same happens with the Gyroscope API (only sends orientation event on mouse click).

For now I've set my default browser to Kiwi, since that somehow doesn't have the same problem, while investigate any workarounds (internet seems oddly silent about this, wondering if it's just my device in particular). Setting it as default makes my noVNC PWA use Kiwi instead of Chrome (with an annoying title bar, but at least I can switch to fullscreen).

I'll close this issue then and update the thread with any solutions for the future googler. Thanks!

**Comment by yousefamar** [comment]
A note for anyone who might run into this thread in the future: Kiwi seems to now have the same bug as Chrome and Brave (it seems they updated the version of Chromium they use), however Firefox still works properly. So use Firefox!

**Comment by Cateners** [comment]
Many Android tablets (such as OPPO, vivo, Huawei) have the same issue when using noVNC in WebView.

**Comment by avelops** [comment]
> Thanks for the link, I was looking for something like that! `mousemove` only fires on click indeed. I've narrowed this down even further -- it seems specific to Chrome on Samsung devices (or at least my S22, with or without DeX). I tried Chrome on an old Pixel 4, and it registers `mousemove` just fine. By coincidence, I found the same happens with the Gyroscope API (only sends orientation event on mouse click).
> 
> For now I've set my default browser to Kiwi, since that somehow doesn't have the same problem, while investigate any workarounds (internet seems oddly silent about this, wondering if it's just my device in particular). Setting it as default makes my noVNC PWA use Kiwi instead of Chrome (with an annoying title bar, but at least I can switch to fullscreen).
> 
> I'll close this issue then and update the thread with any solutions for the future googler. Thanks!

this happens to me too on galaxy s21 5g inside dex with chrome and with KIWI
