### ISSUE TITLE
Can we get rid of using the escape key to exit full screen mode?

### ISSUE THREAD

**Issue by n3gwg** [novnc/noVNC#1736]
I run ProxMox and novnc is the manner by which you can gain a "console" on a running virtual machine. However, when the novnc is placed in full screen mode and you hit escape it then is exited from full screen mode. Now, if you happen to be a vi user (as I am) then you hit escape constantly when using vi on Linux!

I would be fine with remapping the escape key in novnc so it was like "alt-q" or something like that, just anything but a function key or escape.

Thanks in advance!

**Comment by CendioOssman** [comment]
Please see #923.
