### ISSUE TITLE
sudo: ./utils/novnc_proxy: command not found

### ISSUE THREAD

**Issue by DirefulBelt6803** [novnc/noVNC#1738]
**Describe the bug**

**To Reproduce**
1. Git clone <noVNC git link>
2. sudo ./utils/novnc_proxy
3. See error

**Expected behavior**
Novnc should run

**Client (please complete the following information):**
 - OS: SteamOS
 - Browser: Firefox
 - Browser version: 108.0.1 (64-bit)

**Server (please complete the following information):**
 - noVNC version: 1.3.0
 - VNC server: TigerVNC

**Additional context**
SteamDeck, TigerVNC installed via pacman, read-only filesystem

**Comment by CendioOssman** [comment]
Something basic must be missing on that system. My first guess would be that there is no bash installed?

**Comment by CendioOssman** [comment]
I see that you've written to the group as well. I'll close this issue here so we don't have duplicate discussions.
