### ISSUE TITLE
Unsupported encoding (encoding: 2049777704)

### ISSUE THREAD

**Issue by AHWSWTYCL** [novnc/noVNC#1743]
**Describe the bug**
I tried to upgrade noVNC but encounter "Unsupported encoding (encoding: 2049777704)" issue

**To Reproduce**
1. Use noVNC version: 1.4.0-beta  can connect UtralVNC Server 1.3.8.1
2. But use noVNC version: 1.4.0-beta connect UltraVNC Win32 Server 1.0.2.Release failed

**Expected behavior**
Expected behavior: Use noVNC version: 1.4.0-beta can connect UltraVNC Win32 Server 1.0.2.Release.
Actual behavior: Use noVNC version: 1.4.0-beta connect UltraVNC Win32 Server 1.0.2.Release failed.
is this issure caused by RFB protocol version

**Screenshots**
This is my debugging information, hope it will be helpful
![图片](https://user-images.githubusercontent.com/31296264/211446727-fef75381-a5c3-4c8a-9314-672233e24635.png)

**Client (please complete the following information):**
 - OS: Win10
 - Browser: chrome
 - Browser version:  108.0.5359.125 (Official Build) (64-bit)

**Server (please complete the following information):**
 - noVNC version: 1.4.0-beta
 - VNC server: UltraVNC Win32 Server 1.0.2.Release
 - WebSocket proxy: websockify

**Additional context**

**Comment by CendioOssman** [comment]
Does this also happen with older versions of noVNC?

Is there any version that works?

**Comment by AHWSWTYCL** [comment]
Work well in older version of noVNC to connect UltraVNC Win32 Server 1.0.2 Release.
I don't know the exact version in my project, but this one uses pre-ES6 syntax.
I also tried to ugrade noVNC (V1.0.0 ~ V1.3.0-beta), but it failed to connect older version of UltralVNC (1.0.2 Release)

**Comment by AHWSWTYCL** [comment]
So I think there is a problem with the new version of noVNC connecting UtralVNC to the old version,
the older viersion of noVNC in my project can both connect older and latest version of UtralVNC

**Comment by CendioOssman** [comment]
Oh, that's a very ancient UltraVNC version. I'm afraid this is likely a bug in UltraVNC that has been fixed in newer versions.

Please upgrade your server and it should hopefully work much better.

**Comment by AHWSWTYCL** [comment]
Thank you very much for your advice

**Comment by ao-apps** [comment]
We are communicating RFB 3.3 to various infrastructure-level devices, please support protocols before 3.7.
