### ISSUE TITLE
how to use local cursor?

### ISSUE THREAD

**Issue by RyanCode** [novnc/noVNC#1744]
hi,I use novnc to connect a XVncserver drawn by other programs,but I notice there is no cursor,I wonder if novnc has disabled the local cursor?how to fix it,sorry about I don't good at js but c.here is my demo:
```vue
<template>
  <div id="screen" style="width: 100%; height: 100%"></div>
</template>

<script>
import RFB from "@novnc/novnc/core/rfb";
export default {
  mounted() {
    this.connectVnc();
  },
  data() {
    return {
      path: "ws://192.168.1.125:12345",
    };
  },
  methods: {
    disconnectedFromServer(msg) {
      if (msg.detail.clean) {
        this.connectVnc();
      } else {
        setTimeout(() => {
          this.connectVnc();
        },5000);
      }
    },
    connectedToServer(msg) {
      // console.log('success', msg)
    },
    connectVnc() {
      const PASSWORD = "admin";
      let rfb = new RFB(document.getElementById("screen"), this.path, {
        credentials: { password: PASSWORD },
        showDotCursor:false,
      });
      rfb.addEventListener("connect", this.connectedToServer);
      rfb.addEventListener("disconnect", this.disconnectedFromServer);
      rfb.scaleViewport = false; 
      rfb.resizeSession = false; 
      console.log(rfb);
      this.rfb = rfb;
    },
  },
};
</script>
```
and I install novnc by npm,macbook pro m1,chrom browser.version @novnc/novnc@1.3.0

**Comment by CendioOssman** [comment]
Which server are you using? Please fill out the issue template properly.

**Comment by CendioOssman** [comment]
Again, please feel out the template, so we have the details we need.

**Comment by RyanCode** [comment]
> Again, please feel out the template, so we have the details we need.

There is no cursor when I connect TigerVnc server.

xvnc version:
```shell
Xvnc TigerVNC 1.12.0 - built Jun 11 2022 00:00:00
Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12011000, The X.Org Foundation
```
**Steps to reproduce the behavior**
just move the cursor to the canvas of novnc

**Expected behavior**
The local cursor should be displayed in the canvas

**Screenshots**
![image](https://user-images.githubusercontent.com/61410262/215707860-44114ac5-90be-4952-a5ac-f7a85afc6902.png)

**Client (please complete the following information):**
 - OS: macOS Monterey M1
 - Browser: chrome
 - Browser version: [e.g. 22]

**Server (please complete the following information):**
 - noVNC version: 1.2.0(npm view novnc versions)
 - VNC server: TigerVNC
 - WebSocket proxy: no

**Additional context**
Clipboard also not work,I test on macOS and Windows with chrome(same version).I press `ctl+v`,and not recieved `TextCut` event.

**Comment by CendioOssman** [comment]
Thank you.

Have you tried any other VNC client for this server, to make sure it's not a server issue?

Could you check if the `cursor` property is set on the `<canvas>` element at all?

**Comment by samhed** [comment]
In your first post, you said you were using "@novnc/novnc@1.3.0", but later you referred to "npm view novnc versions". Note that "novnc" on npm is not the correct one, it corresponds to https://github.com/kasmtech/noVNC. "@novnc/novnc" is the one you want, and the latest version is 1.4.0.

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by g105b** [comment]
So how do you use a local cursor? The default behaviour is the browser's cursor is hidden. Nothing to do with the server's cursor. There's `showDotCursor = true` but that's a 3px grey dot. I just want the normal browser cursor to display, and it sounds like that's all @RyanCode was asking too.

Edit: for anyone who finds this thread like I did, the answer is to use `!important` in CSS. noVNC goes out of its way to hide the browser's cursor, so you have to have high specificity in CSS to cancel that.

```css
[data-vnc-output] canvas {
    cursor: default !important; /* or whatever cursor you want */
}
