### ISSUE TITLE
Allow CAC certificate passthrough

### ISSUE THREAD

**Issue by jeffreybarrows** [novnc/noVNC#1746]
Users require Two-Factor Authentication (2FA) and are using CAC and PIN. Need to allow noVNC to be able to use local machine CAC reader, and pass through the CAC cert and credentials through to the Machine that VNC is connecting to.

![Drawing](https://user-images.githubusercontent.com/121771783/212559638-c0d60da8-21a7-4e4e-8332-e1800d7925b2.jpg)

**Comment by CendioOssman** [comment]
I'm afraid I'm not aware of any VNC server that supports smart card pass-through, so I'm afraid there isn't anything noVNC can do to help you here. :/

(I also don't think the browsers allows direct access to smart cards at the moment, so it probably wouldn't be possible even if such a server existed.)
