### ISSUE TITLE
Scaling viewport upwards doesn't work in the JS library

### ISSUE THREAD

**Issue by hades5a** [novnc/noVNC#1747]
I have a new rfb session and have attached the object to a div. Also I set the scaleViewport to true. Then when I minimize the browser width and increase it again, the actual screen stays tiny while the grey canvas scales upwards again. The embedded tool works somehow. Does anyone have an idea?

Used on Angular 15.

**Comment by CendioOssman** [comment]
Please fill out the issue template. And some more details on how the container is constructed.

**Comment by hades5a** [comment]
I resolved the issue by specifying a container height. Seems like the container has to have max viewport height to rescale properly. Would be nice if it would be documented somewhere because I was on the issue for 3 days 🗡️
