### ISSUE TITLE
NoVNC Remote Resizing selection results in scrollbars right side and bottom side of the screen

### ISSUE THREAD

**Issue by jpnaidu07** [novnc/noVNC#1749]
**Describe the issue**

When Changing the scaling mode from Local Scaling to Remote Resizing the browser window scroll bars appear (right and bottom) around.

**To Reproduce**

Install novnc with Tight VNC as Server in windows 10 enterprise.

Change the scaling mode from local to remote resizing

**Expected behavior**

Browser window should come without scroll bars and i would be able to see entire windows screen at once (I should not be scrolling down to see the taskbar and click windows button)

Please Help.

**Comment by CendioOssman** [comment]
Please fill out the issue template with the details of your setup.

**Comment by jpnaidu07** [comment]
@CendioOssman Updated. Please Help

**Comment by CendioOssman** [comment]
The description is still lacking some details, such as the versions used.

You have added that the server is TightVNC, though.  I'm afraid that server doesn't support remote resizing, so you'll always get scrollbars there.

It sounds like local scaling is what you want. So why the switch to remote resizing?

**Comment by jpnaidu07** [comment]
Yes. The version of NoVNC is **1.3.0** and TightVNC is **2.8.63**.

Local Resizing is consuming empty space on right and left looks like (800px by 480px.) but we need a full browser screen to view windows system.

If there is any option to remove that greyed spaces on the left and right of the browser windows then it would be really helpful

**Comment by CendioOssman** [comment]
I'm afraid I don't quite understand what you mean. Could you include a screenshot that shows the problem?
