### ISSUE TITLE
unable to zoom-in or zoom-out

### ISSUE THREAD

**Issue by hubbertsmith** [novnc/noVNC#1751]
**Describe the bug**
unable to zoom-in or zoom-out.  ctl(-) and ctl(+) do not work

**To Reproduce**
run novnc -- localhost:6080
attempt to zoom in ctl(+) no result
attempt to zoom out ctl(-) no result
use zoom settings in browser no result

**Expected behavior**
when running any browser, ctl(-) and ctl(+) zoom the display/in/out
when running novnc in a broswer no sauce

**Screenshots**

**Client (please complete the following information):**
Ubuntu 20.04 - Brave 1.47.171 (latest)

**Server (please complete the following information):**
novnc/focal,focal 1:1.0.0-2 all
qemu/focal-updates,focal-security 1:4.2-3ubuntu6.24 amd64
websockify/focal 0.9.0-0ubuntu2 amd64

**Additional context**

same symptoms on windows11 brave browser

**Comment by CendioOssman** [comment]
Do you only see this issue with Brave? Because I cannot reproduce the problem with Firefox or Chrome.

Also note that 1.0.0 is an old release. Please try with the current version, i.e. 1.4.0.

**Comment by CendioOssman** [comment]
I'm afraid we don't have any packaging for Ubuntu, so you'll have to file an issue with them if you want an updated version in a .deb package.

You can find .zip or .tar.gz archives on our release page that you can simply unpack in to an appropriate directory.

**Comment by hubbertsmith** [comment]
I am pretty sure root cause is old version, 
I will give the zip unpack a try. sounds like its as simple as putting the files in the right directory? (I think I can manage that).
if you happen to think of any apt magic, please keep me in mind
H
