### ISSUE TITLE
Customisations in vnc.html 1.3.0 do not work in  vnc.html 1.4.0

### ISSUE THREAD

**Issue by TclHttpd** [novnc/noVNC#1752]
**Describe the bug**
Customisations in vnc.html 1.3.0 do not work in  vnc.html 1.4.0

**To Reproduce**
With noVNC 1.3.0 I could adjust vnc.html to customise the Control Tab to display only the icons I needed. With noVNC 1.4.0 those same customisations are ignored and the full number of icons are shown. I followed a suggestion in https://github.com/novnc/noVNC/issues/941 but adjusted it to suit my needs

I added the following code to only show the “Fullscreen” icon in the Control Tab just above </head> tag

   ```
<style>
            #noVNC_view_drag_button {
                                     display: none;
            }
            #noVNC_toggle_extra_keys_button {
                                             display: none;
            }
            #noVNC_power_button {
                                 display: none;
            }
            #noVNC_clipboard_button {
                                     display: none;
            }
            #noVNC_settings_button {
                                    display: none;
            }
            #noVNC_disconnect_button {
                                      display: none;
            }
   </style>
```

For examples of

Only “Fullscreen” go to -  https://wiki.tcl-lang.org/page/TkPool
“Fullscreen and Clipboard” go to -  https://wiki.tcl-lang.org/page/Tcl+Playground

However, following the suggestion in https://github.com/novnc/noVNC/issues/941 to hide/ remove the Control Tab works in both vnc.html 1.3.0 and 1.4.0 using the following code

    <style>
          #noVNC_control_bar {
                               display: none;
          }
    </style>
</head>

For an example go to - https://wiki.tcl-lang.org/page/Scotch+Yoke

**Expected behavior**
Is there anything I can further adjust in vnc.html 1.4.0 so I can only get “Fullscreen” and “Fullscreen and Clipboard” icons working again as per the examples?

**Client (please complete the following information):**
 - OS: Windows and Linux (only tested)
 - Browser: Chrome and Firefox (only tested)
 - Browser version: Firefox 109.0 Chrome 109.0.5414.74

**Server (please complete the following information):**
 - noVNC version: 1.4.0
 - VNC server: TigerVNC
 - WebSocket proxy: CloudTk

**Additional context**

**Comment by CendioOssman** [comment]
It's likely commit 88ccfdc193b11b114bd6b1aad266237716cf52f5 that is forcing you to be more specific in your styling. Add `!important` to your rules and you should be able to get rid of those buttons.
