### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 403 trying to open novnc behind the azure app gateway

### ISSUE THREAD

**Issue by jpnaidu07** [novnc/noVNC#1754]
**Describe the bug**
Everything works fine locally. But we configured an azure app gateway and connected the vm where Novnc is placed it is able to open the vnc.html page after that when we clicked on connect button websockets connection failed with this error **Error during WebSocket handshake: Unexpected response code: 403**

**Expected behavior**
I should be able to vnc server data on the browser

**Screenshots**
![image](https://user-images.githubusercontent.com/44135328/216020143-4b70fbbb-9ebe-4d86-a7e8-a2a8d789cb78.png)

**Client (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Browser version:108.0.1462.42

**Server (please complete the following information):**
 - noVNC version: 1.4.0
 - VNC server: TightVnc
 - WebSocket proxy: Websockify

**Comment by CendioOssman** [comment]
That message means the server denied the connection, so I'm afraid it's not something we can help you with. You'll have to look at the Azure end of things and see why it is rejecting connections.

**Comment by jpnaidu07** [comment]
@CendioOssman Curios to know if can set/change allowed origins from NoVNC side.

**Comment by CendioOssman** [comment]
No, I'm afraid there is extremely little that we can change about the HTTP request for the WebSocket connection. This is per design so that JavaScript is properly sandboxed.
