### ISSUE TITLE
cannot zoom in/out of webpage  -- control+mousewheel does not work on novnc, does work on firefox

### ISSUE THREAD

**Issue by hubbertsmith** [novnc/noVNC#1755]
**Describe the bug**
cannot zoom in/out of webpage

**To Reproduce**
localhost:6080
control+mousewheel doesnot zoom in or out

**Client (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.04 (focal) both bare metal and docker image
 - Browser: Ubuntu Brave and Ubuntu firefox 
 - Browser version: [e.g. 22]  brave 1.47.186   firefox 109.0

**Server (please complete the following information):**
 - noVNC version: [e.g. 1.4.0 or git commit id]
 - VNC server: [e.g. QEMU, TigerVNC]
 - WebSocket proxy: [e.g. websockify]

**Additional context**

per earlier conversation --- I extracted zip 1.4 version and copied files into the novnc directory (ran without complaint)

thanks Pierre, I really appreciate the help (and your patience with me)
cheers
Hubbert

**Comment by samhed** [comment]
To me, it works if I hover the mouse outside the remote screen while Ctrl+scrolling (easiest if it's smaller than the browser window). Tested both in Firefox and Chrome.

So, I assume you're Ctrl+scrolling while focusing the remote? And in that case, I expect both keyboard and mouse input to be sent to the remote. It's then up to the remote to decide how to handle that input.

Could you explain what you're after?

**Comment by hubbertsmith** [comment]
Hi Sammuel, thank you so much for the help. and thanks for suggesting I better explain (NP)
and with your help we are narrowing it down

zoom in/zoom out on anaconda navigator does not work
the attached screen shot >>> I call up anaconda navigator (see attached screen shot) ... does not zoom
I cannot see or use buttons at the bottom, if I simply want to "X" out of the program, I must move the screen to see th "X"
highly inconvenient, border line unusable

BUT, firefox does zoom as expected , and vscode zooms as expected for me --- baremetal ubuntu, docker ubuntu image+novnc

![Screenshot_20230204_091025](https://user-images.githubusercontent.com/52464327/216777849-e95a9b2e-8410-484a-a2c5-02b202593e3f.png)

thanks for the help, we are getting closer. I am guessing we will take this up with anaconda? 
what might I do from my end?

**Comment by hubbertsmith** [comment]
Perhaps it is a resolution problem ? 
perhaps I should adjust settings/configs?

**Comment by CendioOssman** [comment]
What you are describing sounds like it is simply an application issue. Firefox and vscode support zooming using ctrl+wheel, but it sounds like anaconda does not.

The fact that you cannot reach the buttons at the button is also an application issue, unfortunately. It seems like anaconda doesn't support such a small session and creates too tall windows.

This would be no different from running anaconda on a small monitor, so I'm afraid it is out of scope of what noVNC tries to handle.
