### ISSUE TITLE
noVNC screen resolution

### ISSUE THREAD

**Issue by hubbertsmith** [novnc/noVNC#1756]
![anaconda_Screen_noVNC](https://user-images.githubusercontent.com/52464327/218330017-f8161e83-9ec9-4a55-b680-c31a62f7a4c6.png)
**Describe the bug**
run noVNC - call anaconda-navigator -- it shows up zoomed -- unusable
anaconda-navigator does not appear this way on bare metal (screen captures attached)

**To Reproduce**
1. run docker and noVNC
2. install anaconda-navigator in docker instance
3. run anaconda-navigator

**Expected behavior**
display anaconda-navigator from noVNC the same as it displays on bare metal

**Screenshots**

**Client (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser: brave (but also similar behavior on firefox)
 - Browser version: latest

**Server (please complete the following information):**
 - noVNC version: [e.g. 1.4 or git commit id]
 - VNC server: TigerVNC
 - WebSocket proxy:  websockify]

**Additional context**
![anaconda_Screenshot_1](https://user-images.githubusercontent.com/52464327/218330013-ed01487f-bff0-4633-9ef5-fbb84e1e8836.png)

**Comment by CendioOssman** [comment]
It looks like noVNC is configured to scale the screen, rather than tell the server to resize it.

What is chosen for the "Scaling mode" setting?

**Comment by hubbertsmith** [comment]
thanks for your help. - I tried setting to none, remote resizing, local scaling (all same result)

**Comment by hubbertsmith** [comment]
Hi, thanks, I should have been clearer -- they do look different, the scaling issue remained the same. 
I grepp'd for both tiger and tight (see attached)
![console](https://user-images.githubusercontent.com/52464327/219403032-c57062d3-90b6-403b-8094-da9b11b025c9.png)
![local](https://user-images.githubusercontent.com/52464327/219403063-71a5ae44-8fd9-4e4b-98fb-1f3df1fce51d.png)
![none](https://user-images.githubusercontent.com/52464327/219403085-eb252bd2-13e6-4ade-b6a2-a708c934f14f.png)
![remote](https://user-images.githubusercontent.com/52464327/219403117-c819b7a6-0bf5-4f9f-a6f8-17aa60680ddc.png)

**Comment by CendioOssman** [comment]
So you seem to have both TigerVNC and TightVNC installed. This behaviour is expected with TightVNC, but unexpected with TigerVNC. So it's important we determine what you are running.

What does the log for the session say? It should be in `$HOME/.vnc`.

**Comment by hubbertsmith** [comment]
hi, I found no .vnc log file ... I looked in /home/hubbert and /root on bare metal, and inside container
I am happy to start with a new install of Ubuntu on baremetal. or uninstall (whatever)
thanks a ton for your help, deeply appreciated

**Comment by CendioOssman** [comment]
Let's uninstall TightVNC then to make sure that isn't used. Restart the system after that and retest everything.

**Comment by hubbertsmith** [comment]
I notice wayvnc --- if wayland is possible, that does good things for our use case. LMK

**Comment by CendioOssman** [comment]
I'm afraid we can't really provide much help if you cannot provide log files, much less determine what VNC server you are running.

I just noticed you are running `apt list`. That won't tell you what is installed. That will tell you what _is possible_ to install. Please run `dpkg-query -l` instead, and see what that says.

**Comment by hubbertsmith** [comment]
thanks so much for your patience with me and willingness to help
tightvncserver is installed, tigervnc is not installed
I found the log (attached). apologies I do not know why they eluded me earlier

dpkg-query -l | grep vnc
ii  libvncclient1:amd64                           0.9.13+dfsg-4                            amd64        API to write one's own VNC server - client library
ii  remmina-plugin-vnc:amd64                      1.4.27+dfsg-2                            amd64        VNC plugin for Remmina
ii  tightvncpasswd                                1:1.3.10-5                               amd64        virtual network computing password tool
ii  tightvncserver                                1:1.3.10-5                               amd64        virtual network computing server software
[u7_1.log](https://github.com/novnc/noVNC/files/10826167/u7_1.log)

**Comment by hubbertsmith** [comment]
I will uninstall tightVNC
and install tigerVNC and report results

**Comment by CendioOssman** [comment]
No response. Closing.
