### ISSUE TITLE
Video Chat and Messaging Chat Feature

### ISSUE THREAD

**Issue by rohansukhdeo** [novnc/noVNC#1759]
NoVNC is great, but would be amazing if there was some sort of video chat and chatroom feature built into it.

It should be able to communicate to other noVNC clients on the same IP (for example, I am running multiple noVNC clients on my localhost - I should be able to videochat or message the other VNC client users that are running

Would be a game-changer!

**Comment by CendioOssman** [comment]
I'm afraid noVNC is only a client, so a VNC server would need to implement those features first. After that, we could look at getting noVNC support.

Unfortunately, I'm not aware of any VNC server with those features. That also means I'll close this feature request for now. Please don't hesitate to re-request this if a server shows up in the future with the desired functionality.
