### ISSUE TITLE
noVNC encountered an error: document.getElementById(...) is null

### ISSUE THREAD

**Issue by D3vil0p3r** [novnc/noVNC#1760]
**Describe the bug**
I'm setting noVNC in a docker container on an Arch Linux distro and when I run noVNC, I can access to the files related to the server by the browser but when I visit `vnc.html`, I get the following message error on the browser:
```
noVNC encountered an error:

document.getElementById(...) is null
addConnectionControlHandlers@http://localhost:8080/app/ui.js:327:18
start@http://localhost:8080/app/ui.js:108:12
prime/<@http://localhost:8080/app/ui.js:48:27
```
![image](https://user-images.githubusercontent.com/83867734/220181585-1e521b14-9294-4817-9255-82d899873154.png)

Then, I just waited 1 minute, and I updated the browser and I got the correct browser page with the "Connect" button. When I click on it, it stucks on "Connecting":
![image](https://user-images.githubusercontent.com/83867734/220182349-8a0cc844-27c6-4821-83d9-82bfa4057363.png)

How can I solve this issue?

**Client (please complete the following information):**
 - OS: Arch Linux distro
 - Browser: Firefox and Brave
 - Browser version: latest

**Server (please complete the following information):**
 - noVNC version: 1.4.0
 - other related installed packages: libvncserver (0.9.14-2), x11vnc (1:0.9.16-7), xorg-server-xvfb (21.1.7-1)

**Comment by samhed** [comment]
The most common reasons for those JavaScript errors are all related to browser cache. But you've seen the same crash in both Firefox and Brave? Would you mind clearing all cache and testing again?

Have you made any modifications to the code?

**Comment by D3vil0p3r** [comment]
Hey @samhed I didn't touch the code. I'm starting to test it in a docker container. I think that the issue on my first screenshot above it was only because I needed novnc service to be started.

The problem that remains is that "Connecting..." in my last screen above.

Now I did the same test by clearing browser cache from Firefox and Brave but I still get that "Connecting...". In practice, when I run the docker container by
```
sudo docker run --rm -p 8080:8080 -dti --name ba-test -e DISPLAY=:0.0 test/test
```
I visit `http://localhost:8080/vnc.html` and I land in the correct page:

![image](https://user-images.githubusercontent.com/83867734/220203900-9e5a55af-82f4-4baf-ba24-3fb635a5c04f.png)

Then, if I click on "Connect" button, it stucks in the following manner again:

![image](https://user-images.githubusercontent.com/83867734/220203992-70e7d10e-8870-43e1-9116-29bf23b770ac.png)

**Comment by CendioOssman** [comment]
Sounds like there is some issue reaching the WebSocket proxy, or the VNC server, in that case.

What do the logs say? We'd like to see the browser console, as well as the log from the WebSocket proxy and the VNC server.

**Comment by D3vil0p3r** [comment]
> Sounds like there is some issue reaching the WebSocket proxy, or the VNC server, in that case.
> 
> What do the logs say? We'd like to see the browser console, as well as the log from the WebSocket proxy and the VNC server.

Usually in which files the logs of WebSocket proxy and VNC server are stored?

**Comment by CendioOssman** [comment]
x11vnc doesn't have a specific log location as far as I know, so it very much depends on how you've started it. You'll need to check the details of your startup. 

You haven't specified which WebSocket proxy you are using, but if it's websockify then the situation is the same as for x11vnc.
