### ISSUE TITLE
Add ability to pass options to getContext

### ISSUE THREAD

**Issue by johrstrom** [novnc/noVNC#1761]
**Is your feature request related to a problem? Please describe.**

There are many options that can be passed to [getContext](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext).  One I'm looking to use specifically is `willReadFrequently`. However there doesn't seem to be a way to pass them through the RFB object down to this line

https://github.com/novnc/noVNC/blob/edc7520e273fa1b2cbd0abac6a9fe2c1bd2680d5/core/display.js#L43

**Describe the solution you'd like**

Somehow when creating the RFB object, I'd like to be able to pass options that will eventually make their way to the `Display` object and be used when the `getContext` call above is called (in the Display's constructor).

**Describe alternatives you've considered**

I haven't considered any alternatives. Perhaps I'm not that imaginative, but I don't believe there are any.  I also did not see any other issues that seem to be similar.

**Additional context**

Thanks for everything!

**Comment by CendioOssman** [comment]
The display context is a very internal detail that shouldn't be of interest to users of the RFB object. Exactly what problem is it you are trying to solve?

**Comment by johrstrom** [comment]
I have some users seeing this message in their console and thought that setting could help.

```
display.js:216 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently 
```

**Comment by CendioOssman** [comment]
That must be something else, as we never call `getImageData()` on the target canvas. And very rarely on the back buffer canvas.

Which browser is this? And do you know what users are doing when they get that message?

**Comment by johrstrom** [comment]
> That must be something else, as we never call getImageData() on the target canvas. 

We're still on v1.1.0. It appears to from be this line (not sure why it's line 216 for us).

https://github.com/novnc/noVNC/blob/9fe2fd04d4eeda0d5a360009453861803ba0ca84/core/display.js#L219

> Which browser is this? And do you know what users are doing when they get that message?

They've tried a bunch of browsers and indeed a bunch of machines. It's a full desktop and they're trying open this application (Maestro).

Here - I'm showing what's working for me. The light blue molecule with the highlight is attached to my cursor. (my cursor would be the highlighted bit). Being attached to the cursor - it follows it around and moves where it move, creating new molecules (the black structures) on a click.

The user does not have this at all. They still have a cursor, of course, but no light blue let's say 'next molecule' portion following it.

![image](https://user-images.githubusercontent.com/4874123/221199311-152b4941-d267-4fb6-8ef3-0f3f670ac9f4.png)

It's a bit esoteric, so I don't expect you to replicate (Indeed I can't even replicate when I open that same application).  That's just the only clue I have to go on as to why this user is unable to interact with this application correctly.

Feel free to close as a `won't do` - I just thought I'd try as I'm surprised it's never happened to anyone else.  In any case, it's just the only clue I have to go on and thought a ticket is worth the shot.

**Comment by CendioOssman** [comment]
Thanks for the extra details.

That call is only done when the display resizes. I.e. very rarely. So this is clearly some bad behaviour in Chrome. Firefox does not seem to do this.

I've filed a bug with them here:

https://bugs.chromium.org/p/chromium/issues/detail?id=1420258

This is unfortunately not something we can do much about. We will not be setting that flag as it will reduce performance. And I don't see any other way to silence the nagging.

We'll just have to hope that Chrome fixes this in their end.
