### ISSUE TITLE
Selecting Local Scaling Option in NoVNC results in very small screen

### ISSUE THREAD

**Issue by jpnaidu07** [novnc/noVNC#1762]
**Describe the bug**
The Local Scaling option in NoVnc is showing very small screen

**To Reproduce**
1. Go to options in novnc screen
2. Change the scaling to local scaling

**Expected behavior**
The scaling at least should fit in the screen 

**Screenshots**
![image](https://user-images.githubusercontent.com/44135328/220840504-9b084919-b74c-4eee-bea0-f1aa4cea457b.png)

**Client (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Browser version:   110.0.5481.177

**Server (please complete the following information):**
 - noVNC version: 1.4.0
 - VNC server: UltraVNC
 - WebSocket proxy: websockify

**Additional context**
The remote resizing option anyway not working as expected its giving right and bottom scrollbars to reach the ends of the screen

**Comment by CendioOssman** [comment]
Hmm... Odd. Sounds like the server is simply giving a too large session size. That's something we've seen with x11vnc. But I would have expected the right side to be black in that case.

Could you please enable debug logging in noVNC's settings, and share the browser console log with us?
