### ISSUE TITLE
NoVNC (inexplicably) somehow manages to not respect the hardware keyboard layout

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [novnc/noVNC#1775]
**Describe the bug**
Hitting keys on my (Colemak) keyboard produces random-ish input, unrelated to the actual keys I'm hitting — and in particular, there seems to be no key whatsoever that produces a 'Return' the way it's supposed to:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/200/232926154-755c2dd5-faa2-4525-af3d-b7495efe8fb6.png">

Similarly, even when I break out the physical laptop under the desk and use its built-in keyboard (similar problem, by the way, but for completely different reasons — the software-remapped Colemak keyboard is being completely ignored, as are my [Karabiner](https://karabiner-elements.pqrs.org/) remappings. Dear god.), I'm unable to produce a <kbd>Ctrl</kbd>+<kbd>C</kbd>, and thus unable to input the root password provided by my VPS provider:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/200/232926475-e85772d6-5232-4e67-8fd6-db06b3e5f3fe.png">

**Expected behavior**
1. Hitting keys on my physical keyboard should ... result in that text being typed into the remote machine?
2. Sending keys to my OS should ... result in those keys being fed into the remote machine, as they would in literally any other application, environment, website, etc etc etc? 😅
3. <kbd>Ctrl</kbd>+<kbd>C</kbd> should paste contents from the system clipboard into the remote machine

**Client (please complete the following information):**
 - OS: macOS Ventura **13.2.1**
 - Browser: Firefox **112.0.1**

**Server (please complete the following information):**
 - noVNC version: how do I obtain this information?
 - VNC server: how do I obtain this information?
 - WebSocket proxy: how do I obtain this information?

**Additional context**
Apologies if this is the incorrect location for this post, I didn't have much luck figuring out where to report my experience with this interface. 😓

**Comment by CendioOssman** [comment]
We need the server details to have some hope of diagnosing this. How did you set up the server?

**Comment by ELLIOTTCABLE** [comment]
Hm. A bit over my head, to be honest — Vultr, my VPS provider, seems to use noVNC — it must be installed automatically on their machines?

If it's helpful ("pay money to debug this issue" sounds pretty undesirable to me as a fellow OSS maintainer, but also I'm not sure how else to help out 😓), I put in a lil' time to assemble a script to provision the cheapest Vultr VPS. Sign up and [enable the API](https://my.vultr.com/settings/#settingsapi) on this page, then paste that key below:

```sh
export VULTR_API_KEY="replaceme"

json_result="$(op run -- curl "https://api.vultr.com/v2/instances" \
   -X POST \
   -H "Authorization: Bearer ${VULTR_API_KEY}" \
   -H "Content-Type: application/json" \
   --data "$(cat << EOF
      {
         "region": "ord",
         "plan": "vhp-1c-1gb-intel",
         "os_id": 1743
      }
EOF
)")"

printf 'View boot console: https://my.vultr.com/subs/vps/novnc/?id=%s' \
   "$(echo $json_result | jq -r '.instance.id')"
```

It'll print out the url to the noVNC interface they provide, which may take a moment or two to boot, something like this:

```console
$ create_instance.sh
######################################### 100.0%
View boot console: https://my.vultr.com/subs/vps/novnc/?id=851c5086-33ac-4657-82b7-23f95997ecfa
```

----

That said, I won't be offended if you close this as not-enough-information. I can always complain to the VPS support if it's annoying enough, perhaps they'll be able to upstream the issue back to y'all with more information about their config. 😅

**Comment by CendioOssman** [comment]
I'm afraid that I think just that is the best way forward here; talk to Vultr and have them have a look at the issue. Any debugging of this will likely need their involvement anyway. We are always available if they require some expertise in the details.
