### ISSUE TITLE
"window.crypto.subtle is undefined" connecting to macOS

### ISSUE THREAD

**Issue by rptb1** [novnc/noVNC#1781]
**Describe the bug**
Attempting to connect to macOS built-in VNC server gives an error "window.crypto.subtle is undefined" and a backtrace (see screenshot).

**To Reproduce**
1. Install macOS Ventura.
2. Enable System Preferences -> General -> Sharing -> Remote Management and Remote Login.
3. From Ubuntu, log in to macOS and tunnel to the VNC with e.g. `ssh -L 15900:localhost:5900 you@your-mac`
4. On the Ubuntu box, `sudo snap install novnc`
5. Run noVNC with e.g. `novnc --listen 8080 --vnc localhost:15900`
6. Open browser as directed
7. Press connect.
8. Enter Mac login credentials.
9. Observe error message.

**Expected behavior**
I expected the Mac desktop to appear after entering the login credentials.

**Screenshots**
![Screenshot from 2023-06-03 09-52-03](https://github.com/novnc/noVNC/assets/419807/a91022ef-e294-45c1-b9e3-19cbcc657059)

**Client (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox (run with bare profile, no addons)
 - Browser version:  113.0.2

**Server (please complete the following information):**
 - noVNC version: 1.4.0 (via `snap list`)
 - VNC server: macOS

**Additional context**
The same configuration works in the Remmina VNC client.

**Comment by CendioOssman** [comment]
Some features now require you to use HTTPS and won't work over HTTP. noVNC should warn you about this fact when you connect to it using just HTTP.

Please configure HTTPS for websockify and it should work better. There is some discussion in #1763 about how to do this in a snap.
