### ISSUE TITLE
File directories at two different addresses yesterday and today allow staff to connect to access token and remote computer

### ISSUE THREAD

**Issue by beksem35** [novnc/noVNC#1783]
I sent this question to your gmail address, but I did not receive any information.

I do not share the link addresses publicly because the problem may be critical
![Ekran Görüntüsü (62)](https://github.com/novnc/noVNC/assets/115663585/1e57e2f5-d2d9-4098-9d8c-115a8708c712)
![Ekran Görüntüsü (58)](https://github.com/novnc/noVNC/assets/115663585/afeebf68-60fd-4b8b-ab46-fb0671347071)

**Comment by CendioOssman** [comment]
I'm afraid those are just users of noVNC, so it's not something we have any control over. You'll need to report the issue to them and warn them that they have publicly available VNC servers.

**Comment by CendioOssman** [comment]
Again, these are not our files or our systems. We have no control over them, so you'll have to report this issue to the owners of those systems.
