### ISSUE TITLE
Bail out after certain reconnect attempts

### ISSUE THREAD

**Issue by messede-degod** [novnc/noVNC#1784]
NoVNC offers auto reconnects  which are great, but a option to stop retries after a few failed attempts would be even better. When a server goes down NoVNC goes into a continuous loop, hammering the server with connection attempts.
I admit reconnect_delay could be used to  reduce the intensity but it still does not solve the problem completely.

Proposed Solution:
A `max_reconnects` query parameter which tells NoVNC to bail out after certain attempts would be great.

(I'll be happy to submit a patch if the maintainers/project leaders agree.)

**Comment by samhed** [comment]
Sure, that would feel reasonable to me.

**Comment by CendioOssman** [comment]
Ideally, we can avoid more settings that the user has to fiddle with.

@messede-degod, what rate did you have configured in this scenario? Perhaps we can look at some back off algorithm if it fails to reconnect in a reasonable time.

**Comment by messede-degod** [comment]
> what rate did you have configured in this scenario

i had `reconnect` set to true with the default delay.

**Comment by messede-degod** [comment]
> Perhaps we can look at some back off algorithm if it fails to reconnect in a reasonable time.
yes , this is a good idea, also avoids adding an extra tunable.

**Comment by CendioOssman** [comment]
The default delay is five seconds, which isn't particularly fast. Was that rate a problem in your setup?

**Comment by messede-degod** [comment]
rate wasn't the problem, the problem is that it whenever a program starts a continuous loop a mechanism to stop/control it would be nice 🙂, what do you think, sounds fair ?

**Comment by CendioOssman** [comment]
I'd say the infinite loop is a feature, not a bug. The purpose of the mechanism is "keep me connected at all times", not just protection for a quick glitch. So I don't think we need to automatically break or degrade that unless there is a practical issue.

We have a cancel button on the reconnect screen if the user wants to stop the loop, right?

**Comment by messede-degod** [comment]
Perhaps this is feature would only benefit my use case  🙂 ,  thank you for you time though  👍, i'm closing this issue for now.
