### ISSUE TITLE
If Server only support depth 16 bpp 16, noVNC client not work

### ISSUE THREAD

**Issue by yangxd-ah** [novnc/noVNC#1785]
**Describe the bug**
There is depth parameter in RawDecoder.decodeRect() functoin, If server only supports depth 16 , then it can not work with noVNC since only supports depth 8, 24.

**Comment by CendioOssman** [comment]
If the server only supports 16 bit depth, then I'm afraid that server is buggy.

What server is it that is giving you this issue?

**Comment by yangxd-ah** [comment]
Siemens 808D advance CNC system server

**Comment by CendioOssman** [comment]
Are you certain that the colour depth is the issue? What errors are you seeing?

**Comment by CendioOssman** [comment]
No response. Closing.
