### ISSUE TITLE
SSL issue with noVNC

### ISSUE THREAD

**Issue by spaceshiptrooper** [novnc/noVNC#1787]
Hello,
I am trying to include the noVNC URL in an iframe, but I keep getting a `mixed block` most likely meaning there's some stuff in the noVNC window that keeps redirecting to SSL. I don't know how my VPS host was able to get noVNC captured on their website, but I'm trying to do something similar.

I also notice when I attempt to use `https://`, the SSL certificate URL is always broken even though I have legit self-assign certificates I generated hot off the press. Also, whenever I try to access the `https://` portion of noVNC and I keep getting a `handler exception: [Errno 13] Permission denied` error.

I've looked through the issues and I have not found a single person having this issue. All I'm trying to do is embed the noVNC URL in an iframe. If someone can help me get SSL up and working on the noVNC, that's perfect. One thing to also note, I'm already using nginx within the noVNC to launch that vnc server domain. So I'm currently working on `develop.local`.

I've already looked at [this page](https://github.com/novnc/noVNC/wiki/Advanced-usage) and it's of no help at all. I've attempted to open up an SSL port other than 443 and I come up to 2 issues. 1, either the "custom" port is now being used after `develop.local` i.e. (`develop.local:8443`), but now the noVNC site can't be accessed because that's not the port noVNC runs on. Or 2, open up the "custom" port (8443 in this example) and then attach the **actual** port that the i.e. (`develop.local:6081`) *however* now the "custom" port isn't even being recognized at all.

I'm getting a bit frustrated because all I just want to do is embed the darn noVNC URL in an iframe or what have you not so that I can then have it displayed on my admin panel for me to monitor and switch through.

EDIT: Before you ask, yes, I've already attached a "perfectly" generated SSL certificate as well as the key to the flags before starting up the noVNC command.

Here's noVNC running on just `http://`.

![Screen Shot 2023-07-13 at 1 38 51 AM](https://github.com/novnc/noVNC/assets/22463623/8b56cb7c-ca17-4e99-b7e9-5d624cb40d92)

And now here's me attempting to run it on `https://` **even** though I have generated a `self.pem` certificate and the key and have attached them both to the command line.

![Screen Shot 2023-07-13 at 1 39 03 AM](https://github.com/novnc/noVNC/assets/22463623/e8a49bb2-b1bd-44f1-8eba-8a8dc75b6f38)

On the noVNC server itself, I see that error message

`handler exception: [Errno 13] Permission denied`

When I attempt to access the `https://` version of it. Also I'm using `root` just to "confirm" I have root access to those files.

![Screen Shot 2023-07-13 at 1 43 07 AM](https://github.com/novnc/noVNC/assets/22463623/f5c6bb9f-8176-46dc-8368-5dfd0c4446f1)
![Screen Shot 2023-07-13 at 1 44 33 AM](https://github.com/novnc/noVNC/assets/22463623/84b4c275-2465-47d3-af70-19562c9f71f3)

**Comment by S4nfs** [comment]
@spaceshiptrooper  Did your issue get fixed? I am having the same.

**Comment by lopesg** [comment]
Hello @spaceshiptrooper and @S4nfs

I got the same issue! 

When novnc was installed using snap, the documentation stated that both certificate and key need to be stored inside the snap folder. Here is an extract of the documentation:

> If you want to use certificate files, due to standard Snap confinement restrictions you need to have them in the /home/<user>/snap/novnc/current/ directory. If your username is jsmith an example command would be:
> `novnc --listen 8443 --cert ~jsmith/snap/novnc/current/self.crt --key ~jsmith/snap/novnc/current/self.key --vnc ubuntu.example.com:5901` 

In short, you need to copy your certificate and your key inside the snap folder. noVNC cannot access the files stored outside this folder.

On my side I resolved the issue. Hope it helps.
