### ISSUE TITLE
Trouble importing RFB: "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by RossAddinall** [novnc/noVNC#1792]
**Description**
I'm looking at the noVNC Javascript library for the first time, I'm looking at integrating it into my Svelte project.  I have followed [this](https://www.nasserboukehil.com/angular-vnc-client/) blog article, but I end up with a message something like this:
```shell
(node:26372) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
15:41:31 [vite] Error when evaluating SSR module /src/routes/vnc/+page.svelte: failed to import "@novnc/novnc/core/rfb"

Internal server error: Cannot use import statement outside a module
      at internalCompileFunction (node:internal/vm:73:18)
      at wrapSafe (node:internal/modules/cjs/loader:1176:20)
      at Module._compile (node:internal/modules/cjs/loader:1218:27)
      at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
      at Module.load (node:internal/modules/cjs/loader:1117:32)
      at Module._load (node:internal/modules/cjs/loader:958:12)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
      at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
Y:\MyProject\frontend\node_modules\.pnpm\@novnc+novnc@1.4.0\node_modules\@novnc\novnc\core\rfb.js:10
import { toUnsigned32bit, toSigned32bit } from '@novnc/novnc/core/util/int.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```
I was really quite surprised to see this, because the description in [LIBRARY.md](https://github.com/novnc/noVNC/blob/master/docs/LIBRARY.md) specifically states that "noVNC is written using ECMAScript 6 modules".  I have fixed the issue by adding the ```"type": "module"``` entry in the ```package.json``` file.

**To Reproduce**
Starting with a module based project:
1. ```npm install @novnc/novnc```
2. Create an entry in one of the files that uses RFB in some way and add ``` import RFB from '@novnc/novnc/core/rfb';``` at the top of the file
3. Cause the code to be re-evaulated (HMR/restart or whatever) look for above error.

**Expected behavior**
I expected the import would work out of the box.

**Screenshots**
Not applicable - full error output pasted above

**Client (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Browser version: 114.0.5735.248 (Official Build) (64-bit)

**Server (please complete the following information):**
Not got that far yet !!

**Additional context**
As mentioned I'm using Svelte, but I don't believe that is relevant

**Comment by RossAddinall** [comment]
@samhed Yes exactly.  Though I make no claims about having tested it though from experience and StackOverflow, this should do the trick.

Now have noVNC running inside my browser in a Svelte page.  When I'm a bit further through I'll file a discussion topic to show the code I used, if that is appropriate.

**Comment by CendioOssman** [comment]
It sounds like you've tried to use noVNC directly out of the repo, rather than from npm?

noVNC needs to be converted first if used in node.js, so if you want to run a local build you need to run `npm install` and use the contents of the `lib/` directory.

**Comment by RossAddinall** [comment]
@CendioOssman no, I don't think I did.

I recall installing it with ```pnpm``` (I use pnpm rather than npm, but that shouldn't make a difference).  To verify that, I have checked and ```@novnc/novnc``` appears in my ```package.json``` and the installation is inside my ```node_modules``` folder. 

I'm using it in a Svelte project with Typescript, so maybe something in my development environment is being particularly strict.  When I build the Docker container, I also do a ```pnpm install```, pulling everything that is in my ```package.json "dependencies"``` and that builds fine, though I do think that if it is an ES6 distribution, the ```package.json``` should have a ```type: module``` statement.

Previously, when I have developed ```npm``` packages that needed to support both ES6 and CommonJS, I have found a way.  I could dig that out if required.  Personally, I would just rather that everyone move to ES6.

Thanks for your response.

**Comment by CendioOssman** [comment]
Ah, I see the problem. It seems like we've always accidentally included the `core/` folder. That should never have been in there, only the `lib/` directory.

Supporting both ES6 and CommonJS would be interesting. So any suggestions you have would be very welcome.

**Comment by quimey** [comment]
I'm running into a similar problem:
```
[commonjs--resolver] Failed to resolve entry for package "@novnc/novnc". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "@novnc/novnc". The package may have incorrect main/module/exports specified in its package.json.
```
It's also a svelte project running with vite.

**Comment by CendioOssman** [comment]
The primary issue should be addressed in b35cf6dd1253142267f68f052986d0560f7a495c, where the incorrectly packaged files are now excluded.

If we want to have ES6 versions in npm, then that would need to be a new issue to explore how that can be resolved without errors and confusion.

**Comment by nwalters512** [comment]
This should have been considered a breaking change; we were relying on the ability to import `core/rfb.js` directly since we don't use a bundler. In fact, the official example for showing how to use the library in the browser _also_ uses ESM imports: https://github.com/novnc/noVNC/blob/master/vnc_lite.html. Since you no longer publish ESM code, it is impossible for a consumer of this package to replicate that example.

**Comment by CendioOssman** [comment]
The npm packaging is just for CommonJS usage. If you want to use the standard modules format, then the official packages are the ones you find on our release page:

https://github.com/novnc/noVNC/releases

**Comment by nwalters512** [comment]
By "official packages", you're referring to the ZIP archives? I've never seen a JS library distribute itself via ZIP files before. Why not publish ESM to npm as well?

**Comment by CendioOssman** [comment]
Yes, that is correct.

Please start a discussion on the novnc group/mailing list, or open a feature request for any such changes to the npm packaging. This issue here has been resolved, so it's not a good place for further discussion.
