### ISSUE TITLE
Automate integration of cert in snap version

### ISSUE THREAD

**Issue by profetik-777** [novnc/noVNC#1793]
THe beatiful thing about the snap is that it pulls everything in. 

Has anyone considered going a step further and integrating certs automatically (let's encrypt, eg. yunohost does this). 

This way users have 1 less thing to configure.

Thoughts?

**Comment by samhed** [comment]
I don't think this is a good idea. The snap will use the `utils/novnc_proxy` script, which is not intended to be used in production environments. Including things like certificate handling might give the wrong impression.
