### ISSUE TITLE
tailscale integration

### ISSUE THREAD

**Issue by profetik-777** [novnc/noVNC#1794]
Even with the best effort, it can be tricky to lock down a system. 

Would it be possible to change a config and replace the ip in use to read the tailscale vpn ip (or nm interface) for default? 

NO reall problem, but more of a significant hardening enhancement that takes some of the technical lifting off of vnc, since its is leveraging tailscale.

**Comment by samhed** [comment]
Can you explain a bit more what your noVNC-related question is? You want to have some sort of config file for an IP? I'm afraid I don't follow.

And just to clarify, we can't help with tailscale-specific questions here.

**Comment by CendioOssman** [comment]
No response. Closing.
