### ISSUE TITLE
Specifying a bind address does not work

### ISSUE THREAD

**Issue by VA1DER** [novnc/noVNC#1798]
**Describe the bug**
The instructions given for binding to a specific address (--listen \<address\>:\<port\>) do not appear to work. 

From the [Quick Start instructions](https://github.com/novnc/noVNC):
- **"If you don't need to expose the web server to public internet, you can bind to localhost:"**
\
`./utils/novnc_proxy --vnc localhost:5901 --listen localhost:6081`"

It does not bind to that address, and the resulting URL given when it is used this way doesn't make sense.

**Server:**
 - noVNC version: 1.4, and git
 - WebSocket proxy: websockify

**Comment by namper** [comment]
I believe you want this 
```./utils/novnc_proxy --vnc localhost:5901 --listen 6081```

You can check novnc_proxy file, it is just command line tool wrapper for websockify. 
I believe README should be updated.

**Comment by VA1DER** [comment]
> I believe you want this
> `./utils/novnc_proxy --vnc localhost:5901 --listen 6081`

That tells what address for the client to _connect_ to.  That doesn't specify the address for the wrapper script to tell websockify to _bind_ to.  In your example, the script tells websockify to bind to all adapters.

I was wrong about websockify not binding to the right address when using the README syntax.  In that case websockify IS correctly instantiated.  The problem is only in the sample connection string given by the script in its output:  For example:

`./utils/novnc_proxy --vnc localhost:5901 --listen localhost:6081`

gives this as output:

```
Navigate to this URL:

    http://HOSTNAME:localhost:6080/vnc.html?host=HOSTNAME&port=localhost:6080
```
Where HOSTNAME is the `hostname` output for whatever machine it is run on.

The script just needs to be updated to correctly parse its command line and give the right connection URL in its output.

**Comment by namper** [comment]
@VA1DER --listen only takes PORT, there is no option to change hostname. Feel free to submit PR for it.

**Comment by afbjorklund** [comment]
Patch added, for  `--listen localhost:6800`
