### ISSUE TITLE
Inflate constructor doesn't set windowBits 

### ISSUE THREAD

**Issue by symbalis** [novnc/noVNC#1802]
**Describe the bug**

In inflator.js use of  "inflateInit(this.strm, this.windowBits);" but inflateInit only uses the first argument. Therefore default DEF_WBITS = 15 is used as windowBits instead of the set '5' in constructor.

**Comment by CendioOssman** [comment]
Fixed in b40a45a11b98c2a2dac24f9b6151722f1e3115be.
