### ISSUE TITLE
v1.4.0: Unsupported Security Types (13, 5) with RealVNC

### ISSUE THREAD

**Issue by ShatteredDisk** [novnc/noVNC#1804]
**Describe the bug**
Trying to connect to VNC server results in the following error:
`Failed when connecting: Unsupported security types (types: 13,5)`

**To Reproduce**
1. Run noVNC 1.4.0 using `novnc/utils/novnc_proxy`
2. Navigate to the host and port specified locally or through another device on the same network
3. Click "Connect"
4. See error in developer console

**Expected behavior**
noVNC should correctly connect to RealVNC

**Screenshots**
<img width="1639" alt="Screenshot 2023-09-05 at 8 30 57 PM" src="https://github.com/novnc/noVNC/assets/73539907/20e9341e-f38d-4c93-9ea6-1320ee68aea2">

**Client (please complete the following information):**
 - OS: Raspbian OS (Debian, Raspberry PI)
 - Browser: Chrome
 - Browser version: 113

**Server (please complete the following information):**
 - noVNC version: 1.4.0
 - VNC server: RealVNC
 - WebSocket proxy: websockify (via the version provided in noVNC 1.4.0)

**Additional context**
Another error thrown at the same time as the main error is shown below:
`WebSocket connection to 'ws://127.0.0.1:6080/websockify' failed: Received a broken close frame containing a reserved status code.`

**Comment by CendioOssman** [comment]
I'm afraid those security types are kept secret by RealVNC, so it's not something we can support in noVNC. Please reconfigure your RealVNC server to an open security type, or one of the RSA-AES types we've reverse-engineered.

**Comment by ShatteredDisk** [comment]
I was able to fix the problems today by setting the "Encryption" option to "AlwaysOff" in the "Expert" tab of the settings. Thank you so much for your help!

**Comment by carylewis** [comment]
@ShatteredDisk  Can you provide more details as to how you set the Encryption option?

I am running into the same problem trying to use noVNC to connect to a raspberry pi running vncserver-virtual

**Comment by ShatteredDisk** [comment]
@carylewis If I recall correctly, the option “AlwaysOff” was not in the drop-down list, and I had to type it in manually. You should be able to find it in the GUI for RealVNC (Settings > Expert tab). Unfortunately I cannot confirm because the Raspberry Pi I was using is long gone.

**Comment by carylewis** [comment]
Thanks for your reply, I found the option:

`vncserver-virtual -Encryption AlwaysOFF`
