### ISSUE TITLE
Server disconnected (code: 1015). Open developer tools (F12/Ctrl+Shift+I on Windows, Option+Command+I on Mac OS) and switch to "Console" for details

### ISSUE THREAD

**Issue by zhiduopc** [novnc/noVNC#1807]
Server disconnected (code: 1015/1006).
Open developer tools (F12/Ctrl+Shift+I on Windows, Option+Command+I on Mac OS) and switch to "Console" for details，websockify WSS keeps failing to connect, how do I configure this certificate and how do I issue a certificate to an IP?NoVNC keeps failing to connect!

**Comment by CendioOssman** [comment]
Please don't open duplicate issues. I see you've already opened https://github.com/novnc/websockify/issues/563.
