### ISSUE TITLE
Support QOI

### ISSUE THREAD

**Issue by symbalis** [novnc/noVNC#1808]
**Is your feature request related to a problem? Please describe.**
I would like a lossless compression format.

**Describe the solution you'd like**
Support QOI format as an alternative too RAW for lossless.

**Describe alternatives you've considered**
Support JPEG-LS

**Additional context**
N/A

**Comment by CendioOssman** [comment]
I'm afraid noVNC is just the server, so we cannot create new VNC extensions on our own.

Do you know of any server that implements this format?

**Comment by CendioOssman** [comment]
No response. Closing.
