### ISSUE TITLE
Colors are Inverted

### ISSUE THREAD

**Issue by bafranco10** [novnc/noVNC#1812]
I am using NoVNC to access a PLC and control it remotely through an Industrial PLC that is connected to each of my systems. We use B&R technologies, however when using their gatemanager tool which is also configured through your noVNC tool the colors are fine. This vnc tool that I am setting up has the colors inverted which I wouldn't care too much about should my big red stop buttons not change color. We cannot have the stop buttons show as red since they will not meet industry standards if this is the case. How can I change the colors to reflect their true colors? These should be blue. 
![image](https://github.com/novnc/noVNC/assets/104641779/1e7fb8c4-4853-4a06-ada0-4e4ea1dd02a0)

**Comment by CendioOssman** [comment]
I'm afraid that is a somewhat common bug on embedded VNC servers. noVNC requests a more uncommon pixel format, and many servers mishandle that request and send the colours in the wrong order.

You'll need to report the issue to the vendor of that PLC and hopefully, they can fix the bug.
