### ISSUE TITLE
Using QUIC instead of TCP

### ISSUE THREAD

**Issue by nEghbal** [novnc/noVNC#1814]
Is it possible to run noVNC inside a browser which is connected to the HTTP server over QUIC like chromium?

**Comment by CendioOssman** [comment]
Such low-level details are up to the browser and server, and it is not something we have control over in noVNC. No browser seems to have implemented it yet, though, and I would suspect that few servers have as well.

I don't think it will really matter if noVNC goes over QUIC or TPC, though, as we just have the single long-lived connection.
