### ISSUE TITLE
Support sending uft8 characters to tightVNC server in clipboardPasteFrom

### ISSUE THREAD

**Issue by xianshenglu** [novnc/noVNC#1818]
**Is your feature request related to a problem? Please describe.**

I'm trying to send non-ascii text to tightVNC server. It doesn't work. 

But when I'm doing it in the tightVNC viewer, it is supported. And the [source code](https://www.tightvnc.com/download/2.8.81/tightvnc-2.8.81-src-gpl.zip) is public.

![image](https://github.com/novnc/noVNC/assets/23273077/6ce3af4e-099e-4dea-bee8-00a4fc3abc6b)

**Describe the solution you'd like**
So, can we support sending uft8 characters to tightVNC server?

**Comment by CendioOssman** [comment]
Probably not. That extension requires using the TightVNC capabilities handshake, which is not something that plays well with other extensions.

noVNC supports Unicode clipboard through UltraVNC's extension. Perhaps their server could be an alternative?

**Comment by xianshenglu** [comment]
@CendioOssman  If I can provide a PR, will you accept it?

**Comment by CendioOssman** [comment]
We can certainly look at it. I cannot guarantee it will be accepted, though. The implementation needs to play nice with other VNC servers and not just TightVNC.

**Comment by CendioOssman** [comment]
No update here. Closing for now.
