### ISSUE TITLE
copy and paste

### ISSUE THREAD

**Issue by 464hee** [novnc/noVNC#1819]
I don't know how to reproduce the error as it happened by accident, when I tried to paste kmeans_cls.labels_ I accidentally got ^[[200~kmeans_cls.labels_~but it exists in 1.4.0, has it happened to anyone else like me?
![image](https://github.com/novnc/noVNC/assets/100740023/1591c384-6c95-4e39-ba05-a4dc4425a5b9)

**Comment by CendioOssman** [comment]
I'm afraid that is some issue with your terminal, not noVNC. Those characters are part of something called "bracketed paste mode". They should not be visible to the user like that.

Please report the issue to the terminal software you are using and hopefully they can help you out.
