### ISSUE TITLE
VNC-Clipboard: Cannot send text from noVNC client to QEMU VNC-Server

### ISSUE THREAD

**Issue by MarkusF42** [novnc/noVNC#1820]
**Bug description**
It is currently not possible to send text via clipboard to QEMU VMs.
However it is possible to send text from VM to VNC-Client.

According to the qemu developers the fix should be to flush the streams with Z_FINISH
https://lists.nongnu.org/archive/html/qemu-devel/2023-11/msg05722.html

**To Reproduce**
1. Start a VM with 
-chardev 'qemu-vdagent,id=vdagent,name=vdagent,clipboard=on' -device 'virtserialport,chardev=vdagent,name=com.redhat.spice.0'
2. Connect to VM with noVNC
3. Click on Clipboard button
4. Insert text in Clipboard field
5. VM will start to hang when trying to paste this text

**Expected behavior**
Send text via vnc clipboard to QEMU VMs.

**Client:**
 - OS: Debian 12
 - Browser: Firefox
 - Browser version: 115.4.0esr

**Server:**
 - noVNC version: 1.4.0
 - VNC server: QEMU 8.1.2

**Comment by CendioOssman** [comment]
This extension has been deployed for some time now, so I think that ship has sailed. Compatible implementations will need to be able to deal with a lack of an end marker, as there are many noVNC and TigerVNC deployments out there already. :/

I also checked the original UltraVNC implementation, and it also omits an end marker. So I'm afraid this is simply how this protocol works and QEMU will need to adapt.

**Comment by foxmox** [comment]
Hi,
FYI, a change for QEMU 8.2 to revert to the previous behavior when there is no end marker has already been picked up: https://lists.nongnu.org/archive/html/qemu-devel/2023-12/msg00423.html

**Comment by CendioOssman** [comment]
Glad to hear it. That means the issue should be resolved for users in the next upgrade.

I'll go ahead and close this issue then.
