### ISSUE TITLE
Clipboard not transparent

### ISSUE THREAD

**Issue by freebrowser1** [novnc/noVNC#1822]
**Is your feature request related to a problem? Please describe.**
Clipboard can only be used with an intermediate clipboard popup and not direct, which is very time consuming. Most direct VNC clients allow direct copy / paste into / from the VNC server.
<img width="632" alt="Screenshot 2023-12-10 at 13 12 23" src="https://github.com/novnc/noVNC/assets/26625141/9303af44-78ad-4bc5-ab7d-890ed16b4508">

**Describe the solution you'd like**
Direct copy / paste to / from VNC server.

**Comment by samhed** [comment]
See #1511 and #1347

**Comment by Neustradamus** [comment]
This ticket has been solved by @tobfah PR:
- https://github.com/novnc/noVNC/pull/1993

Linked to:
- https://github.com/juanjoDiaz/noVNC/pull/1
- https://github.com/novnc/noVNC/issues/1961
- https://github.com/novnc/noVNC/issues/1902
- https://github.com/novnc/noVNC/pull/1900
- https://github.com/novnc/noVNC/pull/1899
- https://github.com/novnc/noVNC/pull/1831
- https://github.com/novnc/noVNC/issues/1822
- https://github.com/novnc/noVNC/pull/1817
- https://github.com/novnc/noVNC/pull/1562
- https://github.com/novnc/noVNC/issues/1511
- https://github.com/novnc/noVNC/pull/1347
- https://github.com/novnc/noVNC/pull/1301
- https://github.com/novnc/noVNC/pull/1174
