### ISSUE TITLE
Nginx Config does Not work.

### ISSUE THREAD

**Issue by decyphertek-io** [novnc/noVNC#1823]
NGINX Config does not work
---------------------------------------
Reference: https://github.com/novnc/noVNC/wiki/Proxying-with-nginx
OS: Debian 12
VNC Server: Tigervnc
Novnc + Websocikify
Knowns: Works perfectly without nginx . 
When running nginx I run novnc on 127.0.0.1:6080
nginx Config:
    
    upstream vnc_proxy {
        server 127.0.0.1:6080;
    }
    
    server {
        listen 443 ssl;
        server_name localhost;
        ssl_certificate      /etc/ssl/certs/self-signed-crt.pem;
        ssl_certificate_key  /etc/ssl/private/self-signed-key.pem;
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;
        ssl_protocols        TLSV1.2 TLSV1.3;
        ssl_ciphers          HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
    
    location /websockify {
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:5901/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        # VNC connection timeout
        proxy_read_timeout 61s;
        # Disable cache
        proxy_buffering off;
        }
    
    location /vncws {
        index vnc.html;
        alias /usr/share/novnc/;
        try_files $uri $uri/ /vnc.html;
        }
    }

https://ip-of-server/vncws/vnc.html

Nginx Install
----------------
    
    # https://decyphertek.readthedocs.io/en/latest/technotes/Nginx/
    # Modified to work with Debian 12
    $ sudo vim /etc/apt/sources.list.d/nginx.list
    deb https://nginx.org/packages/debain/ bookworm nginx
    deb-src https://nginx.org/packages/debian/ bookworm nginx
    $ sudo su -c "curl -O https://nginx.org/keys/nginx_signing.key && apt-key add ./nginx_signing.key"
    $ sudo mv /etc/apt/trusted.gpg /etc/apt/trusted.gpg.d/nginx.gpg
    $ sudo apt update && sudo apt -y install nginx 
    $ sudo systemctl enable nginx
    $ sudo unlink /etc/nginx/conf.d/default.conf
    $ sudo openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -keyout /etc/ssl/private/self-signed-key.pem -out /etc/ssl
      /certs/self-signed-crt.pem -subj "/C=US/ST=Any/L=Anytown/O=decyphertek-io/OU=adminotaur/CN=decyphertek"
    $ sudo vim /etc/nginx/conf.d/custom.conf
    
    # EXAMPLE NGINX CONFIG , NOVNC NGINX CONFIG REFERENCED ABOVE.
    server {
        listen 443 ssl;
        server_name localhost;
        ssl_certificate      /etc/ssl/certs/self-signed-crt.pem;
        ssl_certificate_key  /etc/ssl/private/self-signed-key.pem;
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;
        ssl_protocols        TLSV1.1 TLSV1.2 TLSV1.3;
        ssl_ciphers          HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host $host;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        }
    }
    
    $ sudo nginx -t
    $ sudo systemctl start nginx
    $ sudo systemctl reload nginx

VNC Config
-------------------------

    #  ~/.vnc/config
    session=xfce4
    geometry=1920x1080
    depth=24
    localhost=yes
    rfbauth=/home/admin/.vnc/passwd

Xstartup Config
------------------------

    # ~/.vnc/xstartup
    #!/bin/sh
    export XKL_XMODMAP_DISABLE=1
    export XDG_DATA_DIRS="/var/lib/flatpak/exports/share:/home/admin/.local/share/flatpak/exports
    /share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
    unset SESSION_MANAGER
    unset DBUS_SESSION_BUS_ADDRESS
    xfce4-session

TigerVNC.service
-----------------------

    [Unit]
    Description=TigerVNC Server
    
    [Service]
    Type=forking
    User=admin
    Group=admin
    WorkingDirectory=/home/admin
    ExecStart=/usr/bin/vncserver :1
    ExecStop=/usr/bin/vncserver -kill :1
    
    [Install]
    WantedBy=multi-user.target

Novnc.service
-------------------

    [Unit]
    Description=Websockify for noVNC
    
    [Service]
    ExecStart=/usr/bin/websockify --web=/usr/share/novnc/ --cert=/home/admin/.certs/novnc.pem localhost:6080 localhost:5901
    
    [Install]
    WantedBy=multi-user.target

Install guide
-----------------

    # Install xfce4 , novnc , websockify , and tigervnc. 
    sudo apt install xfce4 xfce4-goodies xfce4-panel-profiles dbus-x11 novnc websockify tigervnc-standalone-server -y
    
    # Set VNC password (replace 'your_password' with the actual password)
    printf "password\npassword\n\n" | vncpasswd
    
    # Make a .cert directory
    mkdir ~/.certs
    
    # Generate SSL certificate for noVNC
    openssl req -x509 -nodes -newkey rsa:3072 -keyout ~/.certs/novnc.pem -out ~/.certs/novnc.pem -days 3650 -subj "/C=US/ST=Any/L=Anytown/O=decyphertek/OU=adminotaur/CN=decyphertek"
    
    # Give permissions to novnc.pem so websockify can read it
    chmod 600 ~/.certs/novnc.pem

**Comment by CendioOssman** [comment]
In what way doesn't it work? What errors are you getting?

The `proxy_pass` line doesn't match what is documented, which might be the issue.

**Comment by decyphertek-io** [comment]
@CendioOssman . I am not getting any errors. Traffic from novnc is not being forwarded to Nginx. What should the proxy_pass be? http://127.0.0.1:6080/;  OR http://127.0.0.1:5901/; ? I clearly wrote out all my entire setup, so should be easy to replicate and provide realistic feedback.

**Comment by CendioOssman** [comment]
I'm afraid these are nginx questions, not noVNC ones, and that is not our expertise. I can only not that your listed config does not match what's in the wiki.

Since this is about configuring nginx, there isn't anything we can really help you with. You could try our mailing list if some other noVNC user has any ideas, but otherwise I would suggest some nginx forum for help.
