### ISSUE TITLE
Compatibility with wayvnc on Raspberry Pi OS/Debian Bookworm and its default security type 262

### ISSUE THREAD

**Issue by cRoCx** [novnc/noVNC#1824]
**Is your feature request related to a problem? Please describe.**
Raspberry Pi OS Bookworm, which is based upon Debian Bookworm, for the Raspberry Pi 4 and 5 ships now with wayvnc as the default VNC server. Many other VNC servers are incompatible with Wayland, according to [this thread on the Raspberry Pi forum](https://forums.raspberrypi.com/viewtopic.php?t=358458). Wayvnc server works very well and I can connect using TigerVNC client easily, but noVNC throws the following error:
> connecting to wss://vncserverip:443/websockify?token=exampletoken [rfb.js:550:17](https://vncserverip/vncws/core/rfb.js)
> 19:29:43.669 << RFB.connect [rfb.js:601:13] (https://vncserverip/vncws/core/rfb.js)
> 19:29:43.669 << RFB.constructor [rfb.js:281:13] (https://vncserverip/vncws/core/rfb.js)
> 19:29:43.702 >> WebSock.onopen [websock.js:271:17] (https://vncserverip/vncws/core/websock.js)
> 19:29:43.703 Starting VNC handshake [rfb.js:641:17] (https://vncserverip/vncws/core/rfb.js)
> 19:29:43.703 << WebSock.onopen [websock.js:277:17] (https://vncserverip/vncws/core/websock.js)
> 19:29:43.703 Server ProtocolVersion: 003.008 [rfb.js:1385:13] (https://vncserverip/vncws/core/rfb.js)
> 19:29:43.703 Sent ProtocolVersion: 003.008 [rfb.js:1427:13] (https://vncserverip/vncws/core/rfb.js)
> 19:29:43.708 Server security types: 19,129,5 [rfb.js:1462:17] (https://vncserverip/vncws/core/rfb.js)
> 19:29:43.708 Authenticating using scheme: 19 [rfb.js:1494:13] (https://vncserverip/vncws/core/rfb.js)
> 19:29:43.722
> Failed when connecting: Unsupported security types (types: 262) [rfb.js:941:21] (https://vncserverip/vncws/core/rfb.js)
> 19:29:43.722 New state 'disconnecting', was 'connecting'. [rfb.js:890:13] (https://vncserverip/vncws/core/rfb.js)
> 19:29:43.722 >> RFB.disconnect [rfb.js:605:13] (https://vncserverip/vncws/core/rfb.js)
> 19:29:43.722 Closing WebSocket connection [websock.js:297:21] (https://vncserverip/vncws/core/websock.js)
> 19:29:43.722 << RFB.disconnect [rfb.js:634:13] (https://vncserverip/vncws/core/rfb.js)
> 19:29:43.722 New state 'disconnected', was 'disconnecting'. [rfb.js:890:13] (https://vncserverip/vncws/core/rfb.js)
> 19:29:43.722 Clearing disconnect timer [rfb.js:893:17] (https://vncserverip/vncws/core/rfb.js)

**Describe the solution you'd like**
It seems that wayvnc uses a different authentication, hence the error message `Failed when connecting: Unsupported security types (types: 262)` above. It would be great if support for this security type could be added. More info here: https://github.com/any1/wayvnc#encryption--authentication

**Describe alternatives you've considered**
A workaround in the above mentioned forum is to switch back from Wayland to X11 and then setup TightVNC or RealVNC or the like. But I don't want to switch back to X11 in the first place, since it's becoming more and more obsolete in the future and will not be supported by Debian Linux in the long run.

**Additional context**
TigerVNC client works perfectly with all VNC servers I have used so far, which are RealVNC -> TightVNC -> and now TigerVNC and wayvnc).

**Comment by CendioOssman** [comment]
I'm afraid that it is unlikely that we'll ever support a TLS based security type (like 262). The reason is that the browser doesn't give us direct access to the TLS implementation.

Does wayvnc support WebSockets natively? Perhaps it can expose something more compatible with noVNC there?

**Comment by cRoCx** [comment]
I don‘t think wayvnc server supports WebSockets at the moment. It‘s not mentioned anywhere in the documentation.

I see. Then it might be best to wait for VNC servers to become compatible with Wayland and support various security types.

**Comment by cRoCx** [comment]
Yes, I wanted to try that, but it is not configurable at the moment. A few days ago I reported an issue there, regarding their config file, because I couldn't change any of config file entries to other than the default values. Will test it again and report back, when it's possible to change wayvnc's default config...

On the other hand the password of their password authentication is stored as plain text. That's another reason why I was hoping the noVNC implementation might support this security type 262 with wayvnc. wayvnc's implementation of this security type 262 relies on the system's authentication that is also used by SSH and uses the hashed passwords from /etc/passwd. That's nice, security-wise... no plaintext passwords anymore.

**Comment by CendioOssman** [comment]
Classical VNC authentication does indeed require the password to be stored in plain text.

You could poke wayvnc about supporting "Plain" authentication without TLS. That's type 256. That should give you everything you want.

**Comment by hrideshmg** [comment]
If anyone stumbles upon this thread, wayvnc does support websockets in 2026, you have to launch it with the `-w` flag. Here is a working config:
```
address=0.0.0.0
enable_auth=true
port=5900
use_relative_paths=true
username=<user>
password=<pass>
relax_encryption=true
```
the important line is `relax_encryption=true` wayvnc docs state that this enables some security types like Diffie-Helman, considering that noVNC also supports the same i assume that it is what wayvnc is using with this config.

**Comment by brccabral** [comment]
On my Raspberry Pi I was able to connect only with `enable_auth=false` and wayvnc without `-w`.  
Also, if using TLS certificate, then only via `vnc_lite.html`
