### ISSUE TITLE
realVNC on Raspberry Pi

### ISSUE THREAD

**Issue by echogyf** [novnc/noVNC#1826]
**Describe the bug**
On the Raspberry Pi, when installing realVNC and attempting to establish a remote connection via noVNC in the browser, an error is encountered:` "Cannot read properties of undefined (reading 'digest')."`

**To Reproduce**
1. run `./utils/novnc_proxy --vnc localhost:5900`
2. Accessing http://XXXX:6080/vnc.html in the browser.（XXXX is the IP address）
3. click connect
```js
Cannot read properties of undefined (reading 'digest')
TypeError: Cannot read properties of undefined (reading 'digest')
    at RFB.serverVerify (http://172.28.10.1:6080/app/ui.js:1191:58)
    at http://172.28.10.1:6080/core/util/eventtarget.js:32:43
    at Set.forEach (<anonymous>)
    at RFB.dispatchEvent (http://172.28.10.1:6080/core/util/eventtarget.js:32:14)
    at RFB._handleRSAAESServerVerification (http://172.28.10.1:6080/core/rfb.js:1879:14)
    at http://172.28.10.1:6080/core/util/eventtarget.js:32:43
    at Set.forEach (<anonymous>)
    at RSAAESAuthenticationState.dispatchEvent (http://172.28.10.1:6080/core/util/eventtarget.js:32:14)
    at RSAAESAuthenticationState.negotiateRA2neAuthAsync (http://172.28.10.1:6080/core/ra2.js:162:14)
```

**Client (please complete the following information):**
 - OS: Win10
 - Browser: chrome
 - Browser version: 120.0.6099.131

**Server (please complete the following information):**
 - noVNC version: 1.4.0
 - VNC server: realVNC
 - WebSocket proxy: websockify

**Comment by samhed** [comment]
It seems [crypto.subtle](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle) is only available when using HTTPS.

It is an issue in your RSA-AES code @pdlan, it seems we can't assume `crypto.subtle` to always be available.

**Comment by echogyf** [comment]
I saw this, it was my negligence. Thank you for your help.

**Comment by CendioOssman** [comment]
No, I don't think that is worthwhile. Secure context is a requirement for the modern web.

We added both a visual warning and a warning in the log for this case. We could consider making it even more difficult to use noVNC unencrypted, since that will likely often fail.

**Comment by CendioOssman** [comment]
Do you have anything you'd like to do here @samhed?

**Comment by samhed** [comment]
I think it's not very user friendly to crash like this, but is this the result in case of other non-SSL problems you think?

**Comment by samhed** [comment]
True…

The error currently says, “HTTPS is required for full functionality”, perhaps it should include a warning that crashes can occur. The current version sounds to me like things will mostly work.

**Comment by CendioOssman** [comment]
Sure, that could be tweaked

**Comment by samhed** [comment]
Tweaked in e75938b.

Since we understand the issue here, and we have a workaround — I will close it now.
