### ISSUE TITLE
When I introduced Novnc in Vue,  it got stuck when deployed to the server

### ISSUE THREAD

**Issue by zhangziyang960** [novnc/noVNC#1829]
**Describe the bug**

When I introduced Novnc in Vue, it worked fine when debugged locally, but it got stuck when deployed to the server. The error message is as follows:

![ssss](https://github.com/novnc/noVNC/assets/97734477/f7c438b4-7843-4d9d-84db-e93eb6117156)

**Client (please complete the following information):**
 - Browser:chrome&&edge
 - Browser version:120.0.6099.217

**Server (please complete the following information):**
 - noVNC version: 1.4.0

**Comment by CendioOssman** [comment]
I'm afraid those errors do not look like they come from noVNC, so it's unlikely something we can help you with.

Can you describe how to replicate your setup?

**Comment by CendioOssman** [comment]
No response, closing.
