### ISSUE TITLE
fail to install using npm i

### ISSUE THREAD

**Issue by m-a-rahal-os** [novnc/noVNC#1838]
Hello, I just wanted to report some weird behavior I encountered during installation with `npm` : 
when I install novnc from release versions [1.4.0](https://github.com/novnc/noVNC/archive/refs/tags/v1.4.0.zip), [1.3.0](https://github.com/novnc/noVNC/archive/refs/tags/v1.3.0.zip), [1.2.0](https://github.com/novnc/noVNC/archive/refs/tags/v1.2.0.zip) it failed with this an error like this :
```shell
user@Dev01 ~/noVNC-1.4.0> npm i
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

> @novnc/novnc@1.4.0 prepublish
> node ./utils/convert.js --clean

/home/user/Downloads/noVNC-1.4.0/utils/convert.js:10
    .option('-m, --with-source-maps [type]', 'output source maps when not generating a bundled app (type may be empty for external source maps, inline for inline source maps, or both) ')
     ^

TypeError: program.option is not a function
    at Object.<anonymous> (/home/user/Downloads/noVNC-1.4.0/utils/convert.js:10:6)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.11.0
npm ERR! code 1
npm ERR! path /home/user/Downloads/noVNC-1.4.0
npm ERR! command failed
npm ERR! command sh -c node ./utils/convert.js --clean

npm ERR! A complete log of this run can be found in: /home/user/.npm/_logs/2024-02-11T08_18_56_494Z-debug-0.log
```

however this does not happen when I install from main branch ! [(commit 65e9ecd)](https://github.com/novnc/noVNC/commit/65e9ecd5af2d3a1b3bce2bcd730a1de0469b5f3a) with this one installation proceeds normally as expected.

Note that I tried this on windowns and on ubunti (both with and without `sudo` ...).

**To Reproduce**
1. download https://github.com/novnc/noVNC/archive/refs/tags/v1.4.0.zip (or other version)
2. download and unzip
3. run `npm install`

**Expected behavior**
`nmp install` should finish installation

**Client:**
I tried this with two operating systems :
1. first setup in ubuntu virtual machine :
    - node version v20.11.0
    - npm version 10.2.4
    - OS : Linux Dev01 6.5.0-15-generic # 15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
2. second on windows :
    - node version v20.11.0
    - npm version 10.2.4
    - OS :
        Host Name:                 DESKTOP-1MDV3IF
        OS Name:                   Microsoft Windows 11 Pro
        OS Version:                10.0.22631 N/A Build 22631
        OS Manufacturer:           Microsoft Corporation
        OS Configuration:          Standalone Workstation
        OS Build Type:             Multiprocessor Free
        Registered Owner:          dell
        System Manufacturer:       Dell Inc.
        System Model:              Vostro 15 3510
        System Type:               x64-based PC
        Processor(s):              1 Processor(s) Installed.
                                   [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2419 Mhz
        BIOS Version:              Dell Inc. 1.25.1, 10/3/2023

Thanks a lot

**Comment by CendioOssman** [comment]
Thank you for your report., `npm install` is not really something that users should be running. If a npm (CommonJS) version of noVNC is needed, then I suggest downloading it from npm. If the normal (ES6 modules) version is needed, then downloading our releases is the correct way. But in that case, no `npm` command is needed to use noVNC.
