### ISSUE TITLE
Autoconnect with Password doesn't work

### ISSUE THREAD

**Issue by hollysheep** [novnc/noVNC#1839]
**Describe the bug**
I start NoVNC from terminal with "/usr/share/novnc/utils/launch.sh --vnc 192.168.10.21:5900" and connect to the VNC Server with the URL with "firefox http://user-user:6080/vnc.html?autoconnect=true&host=user-user&port=6080&password=PASSWORD" but that doesn't work. The windows i see is the password dialog.

**Expected behavior**
Connecting to the VNC Server directly.

**Client (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Browser version: 123

**Server (please complete the following information):**
 - noVNC version: 1.0.0
 - VNC server: UltraVNC (Windows-Server), TigerVNC (Ubuntu-Server)
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
noVNC is very old. Could you try with the current version of noVNC?

I tried it with TigerVNC here just now, and it connected automatically just fine for me.

**Comment by hollysheep** [comment]
Thats the last version in Ubuntu repo.

How can i install version 1.4? i don't use snap (snap daemon is uninstalled). Is there a ppa? Do i need to compile it from source?

**Comment by samhed** [comment]
No need to compile anything, download the repo and follow these steps:

https://github.com/novnc/noVNC?tab=readme-ov-file#quick-start

**Comment by accetto** [comment]
Hello @CendioOssman ,

I can confirm, that even the version `noVNC 1.4.0` doesn't accept the password from the URL, if you try the **full** client. Interestingly enough, the **lite** client works as it should.

#### How to reproduce

1. Create a container from one of my images, e.g. [accetto/ubuntu-vnc-xfce-g3](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-g3) and bind the `noVNC` as `-p "127.0.0.1:25001:6901"`. The default password is `headless`.

2. Try to access the **full** client using the URL `http://localhost:25001/vnc.html?password=headless`. You'll always get the connection screen.

![noVNC_connect_screen](https://github.com/novnc/noVNC/assets/34798830/74b25c21-7fdb-431e-997a-f74a8202773d)

3. Then try to access the **lite** client using the URL `http://localhost:25001/vnc_lite.html?password=headless`. It will succeed:

![noVNC_lite](https://github.com/novnc/noVNC/assets/34798830/bb493618-e152-4c3d-abd9-66dcb0c99af8)

I hope it helps to fix it soon.

Regards
accetto

**Comment by samhed** [comment]
@accetto you forgot to add `autoconnect=True`. Just adding the password is not enough on the full UI.

**Comment by accetto** [comment]
@samhed Thanks for the hint. It works. I'll update my documentation.

**Comment by samhed** [comment]
Good to hear. That means there is no reason to think recent version has any problems. Closing.
