### ISSUE TITLE
Windows 11 targets do not respect resizeSession

### ISSUE THREAD

**Issue by WillSuitor** [novnc/noVNC#1840]
**Describe the bug**
Windows 11 VMs don't change resolution with container size when RFB object is created with resizeSession as True.

**To Reproduce**

**Expected behavior**
VM resolution changes as the client window resizes when resizeSession is True.

 **Client:**
 - OS: Windows
 - Browser: Chrome (happens in Firefox as well)
 - Browser version: v121

**Server:**
 - noVNC version: 1.4.0
 - VNC server: qemu
 - WebSocket proxy: websockify

**Additional context**
The VM has the latest virtio-win drivers installed (v1.2.4.0) and has virtio video enabled.

The resolution can be resized within the VM itself (i.e., from display settings), just doesn't automatically resize when the viewing window changes. Other VMs created and viewed within the same setup do change with the window resize.

The Chrome console log has a number of `Server did not accept resize request: Unknown reason` errors in it.

**Comment by samhed** [comment]
This feature depends on the VNC server. noVNC can merely request to change the size. If the server doesn't support it, or chooses to ignore the request, there is nothing noVNC can do.

I suggest you ask the QEMU project about this. The extension required is called "ExtendedDesktopSize". Protocol documentation for the pseudo-encoding can be found [here](https://github.com/rfbproto/rfbproto).

**Comment by WillSuitor** [comment]
Ah makes sense, thanks for the quick response!
