### ISSUE TITLE
How to integrate noVNC in Angular 16

### ISSUE THREAD

**Issue by chethan1095** [novnc/noVNC#1842]
Hi, 
 I have been trying to use noVNC in my angular application where I am not able to install the package and use it I tried with https://github.com/nasrob/vnc-client this still not able to use it .
Here are the details on how I am using noVNC:-
```
import * as RFB from "../../../node_modules/novnc/core/rfb.js";
import RFB from '@novnc/novnc/core/rfb';
import { RFB } from 'novnc';
```
`public rfb: RFB;`

tried with all 3 imports but getting error as  
`Module not found: Error: Can't resolve '../../app/ui.js' in 'C:\Chethan\Projects\VM-ware\nexus_gui\node_modules\novnc\lib\input'`

**Comment by samhed** [comment]
`ui.js` is not part of the noVNC library. The npm package only contains the library, not the application. Perhaps you're after the complete application rather than just the library?
