### ISSUE TITLE
In the 2012 version of novnc.js, using the numeric keyboard to input "*" results in "8",and "+"results in "=";

### ISSUE THREAD

**Issue by Jasminff** [novnc/noVNC#1844]
In the 2012 version of novnc.js, using the numeric keyboard to input "*" results in "8",and "+"results in "=";

**Comment by CendioOssman** [comment]
Please fill out the issue template so we can better understand your setup.

**Comment by and-elf** [comment]
Sounds like shift modifier isn't registered properly

**Comment by CendioOssman** [comment]
The original poster is not responding, so I'm going to go ahead and close this issue.

@MorningSage, if you are seeing different results in Librewolf, then yes, it sounds like a browser bug. Please report the issue to them first. If they see some problem with noVNC, then please go ahead and open a new issue here.
