### ISSUE TITLE
Weston VNC server (neatvnc)

### ISSUE THREAD

**Issue by leonardospeca** [novnc/noVNC#1846]
Hi. I'm trying to connect to a neatvnc server over Wayland. The only supported method to connect to this server is thru an X509 certificate. I'm already using websockify to create a bridge from the websocket to the socket of the VNC server. In my scenario, every device will have its own certificate and one instance of websockify that communicate with only that local VNC server.
If I try to connect now, I receive the error:
```
Failed when connecting: Unsupported security types (types: 262)
```
Is there some way to read the X509 local certificate and make the key exchange with Websockify? Is there some other option?

**Comment by CendioOssman** [comment]
I'm afraid we don't support TLS based authentication, and likely won't ever. :/

We cannot access the browser's TLS engine from JavaScript, and I'm not aware of any trustworthy pure-JavaScript implementation of TLS.

I'm afraid I don't know of a good solution for this, except that neatvnc gets native WebSocket support and can handle TLS that way.

**Comment by hiroaki-m966** [comment]
I can connect weston-vnc from noVNC.

1. Use weston-vnc  13.0.91 and above, Disable weston TLS encryption (Use `--disable-tranport-layer-security` option) [commit](https://gitlab.freedesktop.org/wayland/weston/-/commit/58a0abcb587201880a2b7d3d171b4e8bcde09bd1)
2. Use noVNC 1.4.0 and above, [Added support for Apple Remote Desktop authentication](
https://github.com/novnc/noVNC/commit/e21ed2e6898f28f6fb4dc0e94dd3d8e08e99efb0)
