### ISSUE TITLE
Colour Problem

### ISSUE THREAD

**Issue by chrsssssss** [novnc/noVNC#1847]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Hello, I'm experiencing a display problem when connecting to novnc. It looks like the red and blue colours are inverted compared to the way they should normally be represented. I've tried another VNC client to access the server and I don't have this problem, so it's probably coming from novnc anyone have any ideas?

**Screenshots**
![ultravnc](https://github.com/novnc/noVNC/assets/164514190/255570a0-02f2-4785-8861-9fcab4a40d38)
![novnc](https://github.com/novnc/noVNC/assets/164514190/f1ac3881-7b92-4711-9189-9638208e6ddb)

**Client (please complete the following information):**
 - OS: Linux
 - Browser: [e.g. chrome, safari]
 - Browser version: Version 123.0.6312.60 (Offizieller Build) (64-Bit)

**Server (please complete the following information):**
 - noVNC version: 1.4,0
 - VNC server: [ultraVNC]
 - WebSocket proxy: websockify

**Additional context**

**Comment by chrsssssss** [comment]
Sorry the operating system is Linux

**Comment by CendioOssman** [comment]
This is an issue that pops up now and then, and has so far always been a server bug. noVNC requests an uncommon pixel format, which exposes bugs in many servers.

UltraVNC is a popular server, though, so that's unexpected. Are you running the latest version of UltraVNC?

**Comment by chrsssssss** [comment]
Sorry I made another mistake, I actually use QtVNC as server, but when I try to connect with a noVNC client I do have this problem, with an UltraVNC client I don't have it.  The pictures that I attached are from a noVNC client and an UltraVNC client, and the one from the UltraVNC is the one displayed correctly, so it may be a problem with the client don't you think? Furthermore I also saw some VNC clients which have an option that allow us to swap the pixel colour blue and red( may be in prevision of something like that) Doesn't noVNC have a similar feature? 
Thank you

**Comment by CendioOssman** [comment]
In that case, I'm afraid it's a known issue in Qt's VNC server. Please see #1715.

The issue was reported to Qt, but no progress yet:

https://bugreports.qt.io/browse/QTBUG-108558

I would suggest giving them a poke and see if they can make some progress fixing that.
