### ISSUE TITLE
Rewrite page title using 'title' query parameter

### ISSUE THREAD

**Issue by StenaviN** [novnc/noVNC#1848]
**Describe the bug**
I cannot rewrite page title using 'title=MyTitle' query parameter as I could do in version 0.6.1.
Is it intentional change or regression?

**To Reproduce**
1. open 'vnc.html?title=MyTitle' or 'vnc_lite.html?title=MyTitle'

**Expected behavior**
Page title is set to one supplied via 'title' query parameter.

**Client:**
 - OS: Windows 11
 - Browser: Edge
 - Browser version: 123.0.2420.81

**Server:**
 - noVNC version: 1.4.0
 - VNC server: QEMU
 - WebSocket proxy: websockify

**Comment by CendioOssman** [comment]
I'm looking at noVNC 0.6.1, and I cannot find any support for any "title" setting in the normal UI (vnc.html). Are you sure that worked?

For vnc_lite, it was removed in 51f9f0098d306bbc67cc8e02ae547921b6f6585c along with numerous things as part of making vnc_list a better example.

**Comment by StenaviN** [comment]
So, it is intentional. Thanks!
