### ISSUE TITLE
There seems an issue while max browser and shrink browser window

### ISSUE THREAD

**Issue by writePerfectCode** [novnc/noVNC#1854]
I enable scaleViewport, disable resizeSession and clipViewport.
If a resize browser window, the viewer will auto match browser window sizing.
But if a shrink browser then max, there will be a black frame around viewer

**To Reproduce**
1. connect noVnc to host
2.Click browser top-right shrink button to let browser to not use the whole screen
3. Click browser top-right max button to let browser to use the whole screen.
4. There will be a black frame around the viewer
note: if drag the browser to resize, will not have this issue

**Expected behavior**
Viewer can auto match browser size

**Screenshots**
![火狐截图_2024-04-12T14-18-15 878Z](https://github.com/novnc/noVNC/assets/25824140/b346715e-60de-48e4-a16f-11fe5338a7e8)

**Comment by samhed** [comment]
https://groups.google.com/u/1/g/novnc/c/g-WTcgC1mK0
