### ISSUE TITLE
Is there anyway to known user has keyboard/mouse action in the viewer ?

### ISSUE THREAD

**Issue by writePerfectCode** [novnc/noVNC#1861]
I need to activate user session when user has keyboard/mouse action in the viewer

**Comment by CendioOssman** [comment]
I'm unsure what it is you are asking, but it doesn't sound like something that falls within noVNC's domain.

If you want to monitor activity on the web page where you integrate noVNC, then I suggest a normal event listener. If you are interested in the server side of things, you should probably use some generic monitoring tool inside the session.
