### ISSUE TITLE
Django Integration. No action bar

### ISSUE THREAD

**Issue by ArthurMTX** [novnc/noVNC#1863]
**Describe the bug**
I dont have the action bar

**Expected behavior**
I should see the action bar like in the demo.

**Screenshots**
![image](https://github.com/novnc/noVNC/assets/78091139/86f48533-c63b-4748-b0ad-e7fcf3a17188)

**Client (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave, Arc
 - Browser version: v1.66.118

**Server (please complete the following information):**
 - noVNC version: latest
 - VNC server: QEMU/KVM
 - WebSocket proxy: websockify

**Additional context**
I'm using Django to integrate noVNC. Here is my code. Maybe I did something wrong ?
```python
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'noVNC/app/styles/base.css' %}">
<script type="module">
    import RFB from "{% static 'noVNC/core/rfb.js' %}";

    document.addEventListener('DOMContentLoaded', function() {
        const noVNC_screen = document.getElementById('noVNC_screen');
        const rfb = new RFB(noVNC_screen, 'ws://virtuose:6080/websockify');
        
        const scaleViewport = true;
        const resizeSession = true;

        rfb.scaleViewport = scaleViewport;
        rfb.resizeSession = resizeSession;

        addEventListeners(rfb);

        function addEventListeners(rfb) {
            rfb.addEventListener("connect", () => console.log("Connected to the VNC server"));
            rfb.addEventListener("disconnect", () => console.log("Disconnected from the VNC server"));
        }
    });
</script>
<div id="noVNC_screen" style="width:100%; height:100vh;"></div>
{% endblock %}
```

**Comment by ArthurMTX** [comment]
Hi y'all.

Update : by directly connecting to the WebSocket, the action bar appears : 
![image](https://github.com/novnc/noVNC/assets/78091139/2489c801-9cf6-4cca-ad51-f72834846a1e)

I also added the ``ui.js`` file to my code : 
```py
    import "{% static 'noVNC/app/ui.js' %}";
 ```
 
 But it stills don't work. Any ideas why?

**Comment by CendioOssman** [comment]
I'm afraid the toolbar is not part of the noVNC library. It is only part of our main application.

It is not designed to be extended or integrated in another page. You'll need to either make a fork of it and make the changes you want, or reimplement something similar in your own code.
