### ISSUE TITLE
Please document how yarn test works

### ISSUE THREAD

**Issue by gl-yziquel** [novnc/noVNC#1864]
Trying to "rebuild" / package noVNC from source for my own ends, I tend to be rather baffled: how does `yarn test` works ?

It would be nice if it could be documented in the README.md or somewhere near to it.

**Comment by CendioOssman** [comment]
There must be some confusion. We do not use yarn in noVNC, so that command is not expected to do anything.

noVNC also requires to special build step or packaging to be used. The only thing we have is conversion to CommonJS for when people want to use Node.js tools. But that is optional and not the recommended way.

**Comment by samhed** [comment]
> noVNC also requires to special build step or packaging to be used.

Just to clarify, that should be:

"noVNC also requires NO special build step or packaging to be used."

**Comment by gl-yziquel** [comment]
> "noVNC also requires NO special build step or packaging to be used."

I am not trying to use it for now. I am trying to package it...

**Comment by CendioOssman** [comment]
Then it should be sufficient to just put everything in a package. Nothing needs to be generated, or converted, or moved around.

**Comment by gl-yziquel** [comment]
> Then it should be sufficient to just put everything in a package. Nothing needs to be generated, or converted, or moved around.

Nor tested ?

I guess I'm starting to get old...

**Comment by CendioOssman** [comment]
Tests are optional. But we use karma. Usually started as "npm test" so you don't have to remember to specify the config file, as we have an alias set up in `package.json`.
