### ISSUE TITLE
Usage documentation for MacOS

### ISSUE THREAD

**Issue by ogbozoyan** [novnc/noVNC#1865]
Could you please describe steps how to use noVNC with macOS builtin tools
I've been trying to setup connection for straight 6 hours and nothing booted up
I'm trying use noVNC as client on other macbook in local network to connect my other mac - VNC server. After i'll try to expose to wan for remote usage, but before all please help with setting up, i'm completely stack :(

**Comment by CendioOssman** [comment]
Please fill out the bug report template properly so we can understand your problem fully.

**Comment by CendioOssman** [comment]
No response. Closing.
