### ISSUE TITLE
The novnc/novnc plug-in console arm cannot display the currently entered command and cannot see the cursor

### ISSUE THREAD

**Issue by zhaoYSuper** [novnc/noVNC#1866]
**Describe the bug**
The novnc/novnc plug-in console arm cannot display the currently entered command and cannot see the cursor. You need to press enter several times to see the previously entered content. This is normal on x86

**To Reproduce**

**Expected behavior**
I want to be able to see what I type in real time

**Screenshots**
![1f6160a7732dddd30f2868f4aad2c7f](https://github.com/novnc/noVNC/assets/145959880/74a3c8c1-7637-4c76-a6ed-b3e9d95a904e)

**Client (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome,
 - Browser version: 126

**Server (please complete the following information):**
 - noVNC version: 1.4.0
 - VNC server:  QEMU
 - WebSocket proxy:  websockify

**Additional context**

**Comment by CendioOssman** [comment]
I'm afraid that sounds like a server-side issue. noVNC does not behave differently depending on what kind of VM is used. Please report the issue to QEMU and hopefully they can assist you.
