### ISSUE TITLE
How to Set the time of Automatic disconnection without operation

### ISSUE THREAD

**Issue by CarlRelax** [novnc/noVNC#1871]
I use novnc in ubuntu docker.

It will disconnect soon when I have no operation.

So I want to set the time-long,such as 5 or 10 min ago,it can disconnect.

which config file can set the value?

**Comment by CendioOssman** [comment]
I'm afraid noVNC has no automatic disconnection, so you'll need to figure out what is causing your disconnects. It's likely your VNC server, or your firewall.
