### ISSUE TITLE
I want to get the contents of the clipboard, how to use the rfb object,

### ISSUE THREAD

**Issue by yangcheng0111** [novnc/noVNC#1874]
![image](https://github.com/novnc/noVNC/assets/167048233/efe35db9-bd1d-4a64-b25b-753f2be00495)
Is that right?

**Comment by yangcheng0111** [comment]
After checking the api of the official website, I found clipboard event, but my event did not find text attribute and DOMString attribute

**Comment by CendioOssman** [comment]
Almost. The event is of type `CustomEvent`, where the interesting data is always on a member called `detail`. So you need to access the clipboard data using `event.detail.text`.

**Comment by yangcheng0111** [comment]
Thank you
