### ISSUE TITLE
why first connect restart server？

### ISSUE THREAD

**Issue by CarlRelax** [novnc/noVNC#1878]
**Describe the bug**
Why does novnc stop and start the service the first time you connect to it through a browser?

**To Reproduce**
first connect will come

**Screenshots**
![IMG_20240717_114504.jpg](https://github.com/user-attachments/assets/0fcf5b0c-34b7-458d-9649-1b90a7dc75a6)

server and client in one mechine

**Comment by CendioOssman** [comment]
Please fill out the bug template fully so we can better understand your setup.

**Comment by CendioOssman** [comment]
No response. Closing.
