### ISSUE TITLE
Keyboard.allKeysUp is not working as expected

### ISSUE THREAD

**Issue by leedagee** [novnc/noVNC#1880]
**Describe the bug**
`window.onblur` will be triggered before the key down event, if the user hits shortcuts such as Ctrl+T too fast. Thus, the control button is not automatically released.

**To Reproduce**
1. connect to a vnc server
2. hit Ctrl+T as fast as you can
3. switch from new tab back to noVNC tab
4. left control is still down (on both novnc's side and the server side), but the user is not holding it anymore

**Expected behavior**
All keys should be released properly

**Screenshots**
![expected behavior](https://github.com/user-attachments/assets/6966cd13-b632-49d6-b16e-b178c657462e)
^ expected behavior

![onkeyevent down arrived after window.onblur](https://github.com/user-attachments/assets/33a18ca0-fc9d-48a9-b40d-3e91bc6c8b33)
^ onkeyevent down arrived after window.onblur

**Client (please complete the following information):**
 - OS: Windows 11 23H2 build 22631.3880, AMD64
 - Browser:
   - Firefox 128.0.3
   - Google Chrome 126.0.6478.185

**Server (please complete the following information):**
 - noVNC version:
   - 1.3.0, Debian packaged 1:1.3.0-2
   - 1.5.0, last release
   - 1230a4ce738ebccce80fc08ee6172bc3a19fadba, master when issuing this bug report
 - VNC server: TigerVNC, Debian packaged 1.13.1+dfsg-3
 - WebSocket proxy: websockify, Debian packaged 0.12.0+dfsg1-2

**Additional context**
I'm not sure if it is a problem of the browser implementation. One possible workaround could be setting a flag to ignore all incoming key events after `window.onblur` and unset it after `window.onfocus`

**Comment by CendioOssman** [comment]
I'm afraid I would consider that a browser bug, yes. But since it is so widespread, it looks like we might have to do a workaround. :/

Until then, the issue should resolve itself if you just press and release Ctrl once more.

Do you think you could file bug reports with Chrome and Firefox?

**Comment by leedagee** [comment]
It is NOT a browser bug. I'm trying to make a minimal reproduce page, and the events arrives just in right order (keydown{LeftControl}, onblur, onfocus). I turns back to noVNC implementation.

It is the AltGr detection workaround on Windows delaying LeftControl keydown event by 100ms. If window.onblur is triggered within the 100ms timeout, the bug reproduces. We should clear _altGrArmed and `flush' the LeftControl key immediately on window.onblur, just as we do on key events.

I tried RightCtrl+T and Linux Wayland desktop. Both of them are not affected.

**Comment by CendioOssman** [comment]
I guess I owe Chrome and Firefox an apology. :)

Nice find! I'll have a look at the PR!
