### ISSUE TITLE
`privacy.resistFingerprinting = enabled' Prevent Shift Key From Toggling Number Keys to Respective Symbols

### ISSUE THREAD

**Issue by Lonniebiz** [novnc/noVNC#1882]
In the LibreWolf web browser, which is a privacy focused Firefox derivative,  `privacy.resistFingerprinting` is enabled by default.

In the NoVNC Web Console, provided in Proxmox 8.2.4, the shift key doesn't work correctly in conjunction with  `privacy.resistFingerprinting` being enabled in Firefox or LibreWolf.

For example, if you hold down the shift and press `1234567890` you get `1234567890` instead of `!@#$%^&*()` as desired.
This is especially problematic when typing in passwords for login into virtual machines for two reasons:

1. Passwords are often required to have at least one of these special characters mentioned above.
2. When typing a password, the characters you're actually typing are hidden while you're typing them (a bullet symbol is displayed instead of the character you're actually typing).  You can probably imagine the confusion caused by this.

Here are some other places this problem is mentioned:
- https://forum.proxmox.com/threads/unable-to-type-special-characters-symbols-in-novnc-web-console.76136/
- https://bugzilla.mozilla.org/show_bug.cgi?id=1631301

Given that all other web pages I've tried don't have this issue, I'm hoping that the NoVNC Web Console code base can somehow address it.

The easiest way to reproduce the issue is to run the NoVNC Web Console in LibreWolf  (which has `privacy.resistFingerprinting` enabled by default):
https://librewolf.net/

**Comment by CendioOssman** [comment]
I'm afraid I'm unable to reproduce the issue here with Firefox.

I tried Firefox 128 on Fedora 39, in an X11 session. After enabling `privacy.resistFingerprinting`, I opened noVNC and connected. Number keys work just fine with and without Shift.

Can you test with normal noVNC? This might be a Proxmox bug.

**Comment by Lonniebiz** [comment]
Well, the finger was pointed at Firefox. In this issue, I point at noVNC. Now, back to Proxmox:
https://bugzilla.proxmox.com/show_bug.cgi?id=5647

**Comment by flumm** [comment]
Hi, proxmox dev here. I can reproduce it (Debian Linux, Firefox ESR 115.13.0esr), but AFAICS none of our patches touch any code related to input handling (we modify the ui menus and the inital connecting a bit, though) 

When enabling debug logs, i can see that with `privacy.resistFingerprinting` none of the shift(left) keydown/keyup events are logged.

e.g pressing `Shift + 1` without the option:

```
onkeyevent down, keysym: 65505 , code: ShiftLeft, numlock: false, capslock: false 
Sending key (down): keysym 65505, scancode 42
onkeyevent down, keysym: 33 , code: Digit1, numlock: false, capslock: false
Sending key (down): keysym 33, scancode 2
onkeyevent up, keysym: 33 , code: Digit1, numlock: null, capslock: null 
Sending key (up): keysym 33, scancode 2
onkeyevent up, keysym: 65505 , code: ShiftLeft, numlock: null, capslock: null
Sending key (up): keysym 65505, scancode 42
```

with the option enabled: 

```
onkeyevent down, keysym: 33 , code: Digit1, numlock: false, capslock: false
Sending key (down): keysym 33, scancode 2
onkeyevent up, keysym: 33 , code: Digit1, numlock: null, capslock: null
Sending key (up): keysym 33, scancode 2
```

first i thought maybe it's just an old version (we currently package 1.4.0) so i updated it to 1.5.0 but that didn't change anything in that regard.

Do you have any tips on how we can debug this, since we don't touch any input related code AFAIK.

thanks

**Comment by CendioOssman** [comment]
I did a new test with a fresh Firefox profile. I'm now seeing the same thing.

Unfortunately, that means it's a Firefox bug/misfeature. We can't send any events for the Shift keys if we are never informed that the user presses them. :/

We still seem to get the correct symbol for the "1" key, though, so Proxmox could still do the right thing. But perhaps you use the QEMU keyboard extension and only look at the physical keys?

I'm afraid there is nothing we can do on our end here. We can only act on what the browser gives us. If they filter events, then you'll see that filtered result.

**Comment by flumm** [comment]
> We still seem to get the correct symbol for the "1" key, though, so Proxmox could still do the right thing. But perhaps you use the QEMU keyboard extension and only look at the physical keys?

mhmm not sure, we don't do anything special here, is there some setting that we have to enable for this to work?
I thought that this would be the default when pointing novnc to a qemu provided vnc server? (but obviously it isn't?)

**Comment by CendioOssman** [comment]
I'm afraid I'm not an expert on how QEMU works. It might default to the physical key mode. Otherwise, you'd need to specify a keyboard layout for it so it knows which sequence of keys to emulate to produce the expected symbol.

**Comment by flumm** [comment]
ah yes that makes sense, thanks  :+1:
