### ISSUE TITLE
v1.5.0: Keyboard layout of client not respected

### ISSUE THREAD

**Issue by benz0li** [novnc/noVNC#1886]
**Describe the bug**

v1.5.0 does not respect the keyboard layout of the client.

**To Reproduce**

[Docker](https://www.docker.com/get-started/) (or [Podman](https://podman.io/get-started)) is required for reproduction.

1. Set any non-U.S. keyboard layout on your client
2. Run `docker run -it --rm -p 8888:8888 glcr.b-data.ch/jupyterlab/qgis/base:3.38.1-novnc1.5.0 start-notebook.sh --IdentityProvider.token=''`
3. Open http://127.0.0.1:8888/lab in any browser
4. Click `QGIS Desktop`
5. Open the Xfce Terminal Emulator
6. Press the following keys (according to the set keyboard layout on the client):
    * `N`
    * `Q`
    * `W`
    * `Z`
7. Press any `Shift+Number` combination

Do you get the character according to the set keyboard layout on the client?

(If I press `Z` on my Swiss (German) keyboard I get `y`)

**Expected behavior**

The keyboard layout of the client is respected by noVNC.

(Which is the case with v1.4.0 (all versions < 1.5.0?) and is also in JupyterLab Terminal)

**Screenshots**

\-

**Client (please complete the following information):**

 - OS: macOS Sonoma 14.6.1
 - Browser1: Safari
 - Browser1 version: 17.6
 - Browser2: Firefox
 - Browser2 version: 129.0

**Server (please complete the following information):**

 - noVNC version: 1.5.0
 - VNC server: TurboVNC
 - WebSocket proxy: websockify

**Additional context**

Compare with `docker run -it --rm -p 8888:8888 glcr.b-data.ch/jupyterlab/qgis/base:3.38.1 start-notebook.sh --IdentityProvider.token=''` which uses noVNC v1.4.0.

Image source: [JupyterLab QGIS docker stack](https://github.com/b-data/jupyterlab-qgis-docker-stack)

**Comment by benz0li** [comment]
Both images return the same for `setxkbmap -print -verbose 10`:

```text
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc105
layout:     us
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+inet(evdev)
geometry:   pc(pc105)
xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwerty)" };
        xkb_types     { include "complete"      };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+us+inet(evdev)"     };
        xkb_geometry  { include "pc(pc105)"     };
};
```

**Comment by benz0li** [comment]
@CendioOssman With v1.5.0 the keyboard layout must be set explicitly in Xfce with `setxkbmap`.

**Comment by CendioOssman** [comment]
I'm afraid that sounds like you changed the server configuration somewhere along the line. noVNC has had that feature since 1.0.

I can't find the source tree for that noVNC 1.5.0 branch. Is it just a private test?

**Comment by benz0li** [comment]
The `glcr.b-data.ch/jupyterlab/qgis/base:3.38.1` image uses https://github.com/b-data/jupyter-remote-desktop-proxy/tree/QGIS (`HEAD`) which is reverted back to noVNC v1.4.0.

**Comment by benz0li** [comment]
Start Firefox from within `QGIS Desktop`, open https://www.toptal.com/developers/keycode.

Do with both `glcr.b-data.ch/jupyterlab/qgis/base:3.38.1-novnc1.5.0` and `glcr.b-data.ch/jupyterlab/qgis/base:3.38.1`. Compare the output.

**Comment by benz0li** [comment]
To build the images yourself:

```bash
git clone https://github.com/b-data/jupyterlab-qgis-docker-stack.git
```

```bash
cd jupyterlab-qgis-docker-stack
```

Apply the following patch in order to use the releases from this GitHub repository:

```diff
diff --git a/base/Dockerfile b/base/Dockerfile
index d734a08..537abda 100644
--- a/base/Dockerfile
+++ b/base/Dockerfile
@@ -469,6 +469,15 @@ RUN export PIP_BREAK_SYSTEM_PACKAGES=1 \
   && rm -rf /tmp/* \
     ${HOME}/.cache
 
+ARG NO_VNC_VERSION=1.5.0
+
+RUN cd /usr/local/lib/python3.12/site-packages/jupyter_remote_desktop_proxy/share/web \
+  && rm -rf noVNC \
+  && git clone https://github.com/novnc/noVNC.git noVNC \
+  && cd noVNC \
+  && git checkout v${NO_VNC_VERSION} \
+  && sed -i "s/'websockify'/window.location.pathname.replace(\/[^\/]*$\/, \'\').substring(1) + 'websockify'/g" app/ui.js
+
 ## Install QGIS related stuff
 RUN apt-get update \
   ## Install QGIS-Plugin-Manager
```

```bash
cd base
docker build \
  --progress plain \
  --build-arg QGIS_VERSION=3.38.1 \
  --build-arg SAGA_VERSION=9.1.3 \
  --build-arg PROC_SAGA_NG_VERSION=1.0.0 \
  --build-arg PYTHON_VERSION=3.12.5 \
  --build-arg GIT_VERSION=2.46.0 \
  --build-arg NO_VNC_VERSION=1.5.0 \
  -t jupyterlab/qgis/base \
  -f Dockerfile .
```

---

Run the image:

```
docker run -it --rm -p 8888:8888 jupyterlab/qgis/base start-notebook.sh --IdentityProvider.token=''
```

---

Works as expected for `NO_VNC_VERSION=1.4.0` but does not for `NO_VNC_VERSION=1.5.0`.

**Comment by benz0li** [comment]
@CendioOssman This issue first occurs with commit a0b7c0dac5359e4002e7f1d946e60e2eb9b4a54e.

Tested with b-data's/my `jupyterlab/qgis/base` image.

**Comment by CendioOssman** [comment]
I did some digging, and I think I understand what's happening. It seems like TurboVNC doesn't have a setting for this. But it also doesn't enable this feature unless some other features are in place. Specifically, the lock key synchronisation. Which was indeed added in noVNC 1.5.0.

Unfortunately, there are no settings for this in noVNC. We thought it's better to provide the server with as much detail as possible, and it can decide how to best use it. For QEMU, server layout is always preferred, and TigerVNC has a server-side setting to decide what to use.

**Comment by CendioOssman** [comment]
For reference, noVNC behaves the same as TigerVNC, gtk-vnc, wlvncc. So there seems to be some soft concensus that this is best handled at the client.

Have you mentioned the issue to TurboVNC?

From what I can tell, even their client has this enabled unconditionally. Which seems odd, if they don't have a server setting. I might have missed something somewhere.

**Comment by benz0li** [comment]
@CendioOssman I am reverting two commits (and making other modifications) for now: https://github.com/b-data/jupyter-remote-desktop-proxy/commit/554f60bdcd1a779a01df5f81684b2e0df2254855

> Have you mentioned the issue to TurboVNC?
> 
> From what I can tell, even their client has this enabled unconditionally. Which seems odd, if they don't have a server setting. I might have missed something somewhere.
> 
> Edit: Found it. TurboVNC's client has a setting called `ServerKeyMap` that controls this

FYI @dcommander

**Comment by benz0li** [comment]
FYI @manics @consideRatio @yuvipanda because the official [Jupyter Remote Desktop Proxy](https://github.com/jupyterhub/jupyter-remote-desktop-proxy) also supports TurboVNC.

**Comment by benz0li** [comment]
I am closing this, because I can *patch* the release for my use case.

Someone else may reopen it if they want.

**Comment by dcommander** [comment]
Since TurboVNC 3.1 final, we no longer require one of the LED State extensions in order to enable the QEMU Extended Key Event extension.  (That is because wayvnc supports QEMU Extended Key Event but not *LED State.)  So I'm not sure why the problem was triggered by the addition of *LED State in noVNC.  I also cannot reproduce any issues with noVNC v1.5.0 and TurboVNC 3.1.x on Rocky 8.10.  If you feel that this is a TurboVNC issue, then please post an issue on our [tracker](https://github.com/TurboVNC/turbovnc/issues) with more information that might help me reproduce it.

**Comment by dcommander** [comment]
https://github.com/TurboVNC/turbovnc/commit/f683a73b4adaadf04991bc86ba2a6d07472f6452 introduces a new Xvnc command-line option (`-noserverkeymap`) that can be used to disable the QEMU Extended Key Event, QEMU LED State, and VMware LED State extensions.
