### ISSUE TITLE
failure on vnc.html after upgrade

### ISSUE THREAD

**Issue by goerdi** [novnc/noVNC#1889]
Hi !

after upgrading my Ubuntu 22.04 to 24.04 when i call vnc.html i get this message

Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
https://vnc.domain.net/app/ui.js:236:13

TypeError: Cannot read properties of null (reading 'addEventListener')
    at Object.addTouchSpecificHandlers (https://vnc.domain.net/app/ui.js:236:13)
    at Module.start (https://vnc.domain.net/app/ui.js:87:12)
    at Module.initSettings (https://vnc.domain.net/app/webutil.js:122:22)
    at Object.load (https://vnc.domain.net/app/ui.js:56:17)
    at Object.prime (https://vnc.domain.net/app/ui.js:47:16)
    at https://vnc.domain.net/app/ui.js:1660:12
    at req.onload (https://vnc.domain.net/app/webutil.js:215:13)

vnc_lite.html still works....

Ciao Gerd

![2024-08-19_11h32_38](https://github.com/user-attachments/assets/e039a3f3-5b77-43bb-84f8-78eba231003d)
![2024-08-19_11h32_48](https://github.com/user-attachments/assets/b2558eed-9734-47e6-83a7-9b3d9b5347ae)

**Comment by CendioOssman** [comment]
Please fill out the bug template properly so we can better understand your setup.

**Comment by goerdi** [comment]
Uh how and where ?

**Comment by CendioOssman** [comment]
I don't think you can get it back if you removed it whilst filling out the bug. But if you start opening a new issue, then you can copy the template from the description field.

**Comment by goerdi** [comment]
**Describe the bug**
See Picture in the 1st Post


**To Reproduce**
Use it on Ubuntu 24.04

**Expected behavior**
The Picture above appears... the lite version works

**Screenshots**
See 1st Post

**Client (please complete the following information):**
 - newest Edge / Firefox / Chromium Browser


**Server (please complete the following information):**
 - noVNC version: actual git (also version 1.5.0 tried
 - VNC server: x11vncserver
 - WebSocket proxy: websockify

**Additional context**
via Apache reverse Proxy

**Comment by samhed** [comment]
The crash seems to indicate that the JavaScript code can't find any elements with the class `noVNC_expander`. But unless you have removed those elements from vnc.html, it looks like they're still there.

Please clear your browser cache and try again, it's possible the browser is serving you a broken mix of an old and the new version of noVNC.

**Comment by goerdi** [comment]
You were right.... thnx
