### ISSUE TITLE
Copy Chinese One way only

### ISSUE THREAD

**Issue by Zephylaci** [novnc/noVNC#1893]
**Describe the bug**
English copy is normal, once the characters copied to the remote end contain Chinese characters, the Chinese part will become "?"，Copying it back from a remote part is fine。

**To Reproduce**
1.Click the VNC Clipboard to copy the string with Chinese characters
2.Find a text editor on your remote computer and paste it

**Expected behavior**
Chinese can be correctly copied from inside to outside

**Screenshots**
![Snipaste_2024-08-29_09-52-32](https://github.com/user-attachments/assets/9814a723-e23c-4321-9c15-165e0bacb703)
![Snipaste_2024-08-29_09-54-13](https://github.com/user-attachments/assets/a34368e7-d0dd-4df3-87fd-39a29e072286)
![Snipaste_2024-08-29_09-55-57](https://github.com/user-attachments/assets/58d2f590-5369-47c6-bc39-d7568d939d76)

**Client (please complete the following information):**
- OS: MacOS
          windwos11
- Browser:
           edge:127.0.2651.105
           chrome:127.0.6533.122

**Server (please complete the following information):**
 - noVNC version: 1.5.0
 - VNC server:UltraVNC 1.4.3.6
 - WebSocket proxy: websockify

**Additional context**
The remote computer is a Windows 10，Client I have tried Windows 11 and MAC both have this problem。
I'm not sure if it was an UltraVNC problem。
I saw someone say that switching to tigervnc would fix the problem, but I saw in its repository that the windwos version lacks maintenance so I didn't try it。
Asking for advice. Thank you

**Comment by CendioOssman** [comment]
Thank you for the details. It's very strange that it works in one direction but not the other.

Do you think you could do a quick test with TigerVNC's viewer on the client? It also supports Unicode clipboard and could help us see if the problem seems to be on the client side or the server side.

**Comment by Zephylaci** [comment]
@CendioOssman
Well, I just tried tigervnc，relative UltraVNC  screen is too lag，but，clipboard can work well。
It's normal to copy from either side，I went to UltraVNC to make issues。
Thank you for your help
