### ISSUE TITLE
Transfer files out of noVNC

### ISSUE THREAD

**Issue by TigerusLtd** [novnc/noVNC#1896]
**Is your feature request related to a problem? Please describe.**
Yes. I wish to transfer files out of noVNC through the web browser

**Describe the solution you'd like**
A way to recover my files

**Describe alternatives you've considered**
rebuilding rdp, virtual HD.

**Additional context**
So i am connected to an RDP where i stored all my files. I then got a network adapter corrupted and now i am unable to log onto the rdp at all. But when i use the rdps novnc console i can log in and move around but unable to reinstall new drivers so i don't haver internet. i wish to grab the files in the rdp.

**Comment by CendioOssman** [comment]
Which server is this? I'm afraid that I'm not aware of any virtualization VNC server that has a file transfer feature we could add support for.
