### ISSUE TITLE
Mouse clicks are not picked up sometimes

### ISSUE THREAD

**Issue by Oleg-N-Cher** [novnc/noVNC#1897]
Dear noVNC developers,

We have a system built using Linux Ubuntu in Docker, running TurboVNC / websockify and proprietary software under Wine. Clients access this technology stack via noVNC from a browser over HTTPS. It is also apparent that the low-cost VPS has a small amount of memory / disk space.

Customers complain about the problem of missing the mouse clicks (seems that mouse clicks are not picked up sometimes). Its reproducible. Is there any chance to do something?

Could you please explain if there is any buffering of mouse clicks in noVNC? What could the missing of click processing be related to at all? What part of our stack has a bottle neck? Thank you very much for your work.

**Comment by CendioOssman** [comment]
I'm afraid you've not given us much to go on. But no, we do not buffer any mouse clicks. They are always sent immediately.

Have you done any debugging to see where in the chain the events are lost?

**Comment by Oleg-N-Cher** [comment]
Honestly, no. I don't know how to get started.

Thank you for your answer.

**Comment by CendioOssman** [comment]
Mouse events are not normally logged, as it quickly becomes a lot. I would suggest modifying `RFB._handleMouseButton()` and add some logging to it. That should tell if noVNC gets the events, and you could also add logging to see if they are sent to the server.

**Comment by Oleg-N-Cher** [comment]
Thank you. It looks like the problem is not with noVNC. So I'm closing this task.
