### ISSUE TITLE
SaveAs / Upload dialog doesn't open properly

### ISSUE THREAD

**Issue by alidehghan** [novnc/noVNC#1901]
right-click on any image or (ctrl + s on the page) will open SaveAs dialog which doesn't display properly, in fact the dialog shows in the host machine !!!

**Comment by CendioOssman** [comment]
I'm afraid that is how things are supposed to work. noVNC is about controlling a remote session, so mouse clicks and keyboard presses will all be sent to the remote machine. You'll need to use the menus in your browser for such actions.
