### ISSUE TITLE
Clipboard Sharing

### ISSUE THREAD

**Issue by alidehghan** [novnc/noVNC#1902]
the problem of clipboard sharing is resolved in [https://github.com/kasmtech/noVNC](https://github.com/kasmtech/noVNC), ofcourse it has some other issue in which when context-menu is open,  moving mouse toward the menu is not properly handled, but the problem of clipboard sharding is perfectly handled.

**Comment by CendioOssman** [comment]
Duplicate of #1511.

**Comment by Neustradamus** [comment]
This ticket has been solved by @tobfah PR:
- https://github.com/novnc/noVNC/pull/1993

Linked to:
- https://github.com/juanjoDiaz/noVNC/pull/1
- https://github.com/novnc/noVNC/issues/1961
- https://github.com/novnc/noVNC/issues/1902
- https://github.com/novnc/noVNC/pull/1900
- https://github.com/novnc/noVNC/pull/1899
- https://github.com/novnc/noVNC/pull/1831
- https://github.com/novnc/noVNC/issues/1822
- https://github.com/novnc/noVNC/pull/1817
- https://github.com/novnc/noVNC/pull/1562
- https://github.com/novnc/noVNC/issues/1511
- https://github.com/novnc/noVNC/pull/1347
- https://github.com/novnc/noVNC/pull/1301
- https://github.com/novnc/noVNC/pull/1174
