### ISSUE TITLE
canvas display anomalies

### ISSUE THREAD

**Issue by wangyuks** [novnc/noVNC#1905]
**Describe the bug**

**To Reproduce**
1. connet vnc success
2. canvas display anomalies，Sometimes it can't be displayed, sometimes a small box is displayed, and the input content is too laggy

**Screenshots**
<img width="1285" alt="a5e6a33355bebc2a6e5a77878edd9b72" src="https://github.com/user-attachments/assets/46432a54-1a63-4c5e-b04d-f6c44886b4d5">

**Comment by wangyuks** [comment]
The interface looks like there is data returned, but the page is not rendered. Occasionally rendering normally, but unable to input content

**Comment by CendioOssman** [comment]
Please fill out the bug report template completely or we will have a hard time understanding your setup.

**Comment by samhed** [comment]
No response.
