### ISSUE TITLE
Connection closed (code: 1011, reason: Failed to connect to downstream server)

### ISSUE THREAD

**Issue by adelin-b** [novnc/noVNC#1909]
**Describe the bug**
It doesn't connect

**To Reproduce**
1. Go to terminal
2. run this command given from the readme : `docker run --rm -p 6080:6080 ghcr.io/wavyland/novnc 6080 172.17.0.1:5900`
3. Go to page http://localhost:6080 
![image](https://github.com/user-attachments/assets/94b91da5-3b24-43e5-baf9-797c7cd3e038)
```
d run --rm -p 6080:6080 ghcr.io/wavyland/novnc 6080 172.17.0.1:5900
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /usr/local/share/novnc
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to 172.17.0.1:5900
172.17.0.1 - - [27/Oct/2024 14:34:15] 172.17.0.1: Plain non-SSL (ws://) WebSocket connection
172.17.0.1 - - [27/Oct/2024 14:34:15] 172.17.0.1: Path: '/websockify'
172.17.0.1 - - [27/Oct/2024 14:34:15] connecting to: 172.17.0.1:5900
172.17.0.1 - - [27/Oct/2024 14:34:15] Failed to connect to 172.17.0.1:5900: [Errno 111] Connection refused
172.17.0.1 - - [27/Oct/2024 14:37:31] 172.17.0.1: Plain non-SSL (ws://) WebSocket connection
```
4. Click connect
5. See error http://localhost:6080  `Connection closed (code: 1011, reason: Failed to connect to downstream server)` in console
![image](https://github.com/user-attachments/assets/cbd22c54-da1e-49d3-8b5f-322f8dd985f6)
 

**Expected behavior**
Expecting to work

**Screenshots**

**Client (please complete the following information):**
 - OS: archlinux
 - Browser: chrome, chromium
 - Browser version: Version 130.0.6723.69 (Official Build) Arch Linux (64-bit)
 - Desktop env KDE6 (wayland)

**Server (please complete the following information):**
 - noVNC version: latest that get pulled from the docker command
 - VNC server: same
 - WebSocket proxy: no proxy

**Comment by CendioOssman** [comment]
The error message suggests that there is some issue with the VNC server. Have you checked that it is running? Or it might be some problem with that container where it isn't reaching the VNC server properly.

Either way, I'm afraid those are components outside noVNC so it's not something we can help you with here.
