### ISSUE TITLE
Cannot read properties of undefined (reading 'importKey')

### ISSUE THREAD

**Issue by 011V32** [novnc/noVNC#1912]
**Describe the bug**
I use the HA Add-On, which changed from version 1.3.0 to 1.5.0.
After the change, I can no longer establish a connection and get an dialog and afterwards the following error.

**Error message**
> Ein Fehler ist aufgetreten:
> 
> Cannot read properties of undefined (reading 'importKey')
> TypeError: Cannot read properties of undefined (reading 'importKey')
> at AESECBCipher._importKey (http://homeassistant.local:8123/api/hassio_ingress/ESchz347LQg8DJKlC152P9l-Qk_1kL372Wbw_kcDr8w/core/crypto/aes.js:17:48)
> at AESECBCipher.importKey (http://homeassistant.local:8123/api/hassio_ingress/ESchz347LQg8DJKlC152P9l-Qk_1kL372Wbw_kcDr8w/core/crypto/aes.js:12:22)
> at LegacyCrypto.importKey (http://homeassistant.local:8123/api/hassio_ingress/ESchz347LQg8DJKlC152P9l-Qk_1kL372Wbw_kcDr8w/core/crypto/crypto.js:50:20)
> at RFB._negotiateARDAuthAsync (http://homeassistant.local:8123/api/hassio_ingress/ESchz347LQg8DJKlC152P9l-Qk_1kL372Wbw_kcDr8w/core/rfb.js:1737:43)

**To Reproduce**
Changed version 1.3.0 to 1.5.0 without any additional configuration changes.
Connect to my Mac with screen sharing (not ARD) activated.

**Expected behavior**
Normally, the connection was successfully connected with the password only.
(Previously, no additional dialog appeared at all)

**Screenshots**
![image](https://github.com/user-attachments/assets/9df82861-b9e9-43f3-a8e9-1bc85a6cd20c)
![image](https://github.com/user-attachments/assets/46986e48-c962-4f8d-9d4b-3e95773ebb07)

**Client**
 - OS: Windows 11 / Mac 15.1
 - Browser: Edge / Safari
 - Browser version: 129.0.2792.89 / latest

**Server**
 - noVNC version: 1.5.0
 - VNC server: HomeAssistant VNC-Viewer from Poeschl
 - WebSocket proxy: websockify

**Additional context**
[Add any other context about the problem here.](https://github.com/Poeschl-HomeAssistant-Addons/vnc-viewer/issues/4)

**Comment by CendioOssman** [comment]
Modern web features unfortunately do not work without TLS enabled. So you need to set up your noVNC web server to support https. If you are using websockify, then there are some suggestions here:

https://github.com/novnc/websockify/wiki/Encrypted-Connections

**Comment by 011V32** [comment]
@CendioOssman Thx for your reply.
But why it worked with V1.3.0 and no longer with v1.5.0?
Has there been a change that requires the new TLS features in the v1.5.0, or can we switch to the old features?
(I couldn't find any informations in the release notes.)

**Comment by CendioOssman** [comment]
The reason is that noVNC now supports the more advanced authentication methods of ARD. That's also why you got a user entry now.

I'm afraid we don't have any settings to control the authentication used.
