### ISSUE TITLE
COPY PASTE NOT WORKING

### ISSUE THREAD

**Issue by prasaanth2k** [novnc/noVNC#1915]
- noVNC version: latest version
 - VNC server: tightvncserver
 - WebSocket proxy: [e.g. websockify]

when i copy and content from the server it was not copy  to frontend clipboard 

![Screenshot from 2024-11-22 18-39-29](https://github.com/user-attachments/assets/d496c39b-d2c9-4562-bea7-db776c489cda)

when i try to past the content clipboard it not sending to the vnc
![Screenshot from 2024-11-22 18-40-18](https://github.com/user-attachments/assets/19623af8-15ce-4240-b68b-010ac8425987)

i was using docker based vnc

```dockerfile
FROM ubuntu:22.04

# Set noninteractive environment for apt
ENV DEBIAN_FRONTEND=noninteractive
ENV USER=root

# Install basic tools, desktop environment, and noVNC
RUN apt-get update && apt-get install -y \
    xubuntu-desktop \
    tightvncserver \
    novnc \
    websockify \
    xfce4-terminal \
    fonts-dejavu \
    arc-theme \
    papirus-icon-theme \
    xdotool xclip x11vnc \
    && apt-get clean

# Set up VNC server and password
RUN mkdir -p ~/.vnc \
    && echo "password" | vncpasswd -f > ~/.vnc/passwd \
    && chmod 600 ~/.vnc/passwd
RUN rm -rf /usr/share/novnc

COPY novnc /usr/share/novnc
# Copy the custom xstartup file to configure XFCE
COPY xstartup /root/.vnc/xstartup
RUN chmod +x /root/.vnc/xstartup

# Set up noVNC
RUN mkdir -p /root/noVNC \
    && ln -s /usr/share/novnc/vnc.html /root/noVNC/index.html

# Expose necessary ports
EXPOSE 5901 80

# Set default geometry for the VNC server
ENV GEOMETRY=1920x1080

# Command to run VNC server and noVNC server with clipboard support
CMD ["bash", "-c", "vncserver :1 -geometry $GEOMETRY && websockify --web=/usr/share/novnc/ --wrap-mode=ignore 80 localhost:5901"]
```
This is my folder strcture
![image](https://github.com/user-attachments/assets/5fe0e9c8-4d0e-4263-864c-c2e88f482283)

this is the xstartup file
![image](https://github.com/user-attachments/assets/76a85041-74f7-4014-b5e9-e94b35082668)

Bascally i was cloned the repo and customzing with that for my own but iam stuck with this clipboard issue

**Comment by CendioOssman** [comment]
TightVNC requires `vncconfig` to be running as a clipboard helper. So you need to add that command to xstartup as well. Hopefully it should work fine after that.
