### ISSUE TITLE
Division by zero if a 0-width RAW rect is sent

### ISSUE THREAD

**Issue by jalfd** [novnc/noVNC#197]
In display_raw() in rfb.js, the expression `ws.rQlen()/(FBU.width * fb_Bpp)` is problematic if `FBU.width` is zero. 

Obviously, the server should not be sending empty rects in the first place, but we came across a problem where it happened, and currently it causes NoVNC to disconnect entirely.

**Comment by samhed** [comment]
This code doesn't exist anymore.
