### ISSUE TITLE
How to use the clipboard

### ISSUE THREAD

**Issue by pandasonia** [novnc/noVNC#206]
One of the features of noVNC is clipboard copy/paste.
But I don't understand how to use it.
So far, I cannot copy anything from my desktop in the browser, nor could I  paste something in it from my local machine.
Could someone please explain to me how it works?

**Comment by dreyTee** [comment]
Have same problem, autocutsel doesn't help.
Xvnc server started with both -AcceptCutText and -SendCutText options. vncconfig is running.

How could I enable clipboard sync between my pc and browser in vnc-server?
In noVNC ocode I see mentions of clipboard buttons, how could I enable these buttons?
