### ISSUE TITLE
IE9 error - connection timeout

### ISSUE THREAD

**Issue by svscorp** [novnc/noVNC#238]
Hi.

I try to figure out why noVNC doesn't work in IE9. First of all I had a problem when SWF wasn't loaded. Just saw the message: 'canvas is not supported'.

I've found that it is because I didn't use meta tag with IE=9. Probably it will helps someone:
<meta http-equiv="X-UA-Compatible" content="IE=9"/>

But after that I went to the new issue. Connection timeout. With IE10 - it works. With other browsers it works as well. IE9 not.

Here us log. May be someone knows where the trick?

LOG:  Forcing uncached load of WebSocketMain.swf 
LOG:  >> RFB.constructor 
LOG:  >> Display.constructor 
LOG:  User Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0) 
LOG:  Browser: trident 6 
LOG:  No scaling support 
LOG:  Setting viewport to full display region 
LOG:  Prefering javascript operations 
LOG: Data URI scheme cursor not supported 
LOG:  << Display.constructor 
LOG: Using web-socket-js bridge. Flash version: 11 
LOG:  >> Keyboard.allKeysUp 
LOG:  << Keyboard.allKeysUp 
LOG:  No scaling support 
LOG:  Setting viewport to full display region 
LOG: New state 'loaded', was 'disconnected'. Msg: noVNC ready: WebSockets emulation, canvas rendering 
LOG:  << RFB.constructor 
LOG:  >> Keyboard.allKeysUp 
LOG:  << Keyboard.allKeysUp 
LOG: New state 'connect', was 'loaded'. 
LOG:  >> RFB.connect 
LOG:  connecting to wss://host:port/hash
LOG:  << RFB.connect 
LOG:  >> Keyboard.allKeysUp 
LOG:  << Keyboard.allKeysUp 
LOG:  Closing WebSocket connection 
LOG: New state 'failed', was 'connect'. Msg: Connect timeout 
LOG:  Clearing connect timer 
LOG:  >> WebSock.onclose 
LOG: Received onclose while disconnected 
LOG:  << WebSock.onclose 
LOG:  >> Keyboard.allKeysUp 
LOG:  << Keyboard.allKeysUp 
LOG: New state 'failed', was 'failed'.

**Comment by raven7** [comment]
thx infernix .your soloution really worked.:D
