### ISSUE TITLE
Making logging more configurable

### ISSUE THREAD

**Issue by jalfd** [novnc/noVNC#243]
At the moment, the logging functionality in NoVNC is in a bit of an odd place, because it's defined in Util, which is sort of a stateless namespacey object, rather than one created from a (parametrized) constructor like `RFB`, for example. But logging does have state (currently just the log level, but I would like to parametrize it so it can log to other objects than `console`, so it would need to store a target as well).

Currently you work around this by calling `init_logging` immediately after defining the function, so while the logger is in theory configurable, it configures itself implicitly as soon as it's defined.

Of course, I could make a hack to work around this in a dozen different ways, but I'm thinking it would make sense if the logger was explicitly instantiated (probably at the top of `ui.js`, before including all the other files. And for clients which dont use `ui.js`, we can instantiate the logger on our own, and pass custom parameters to it)

I'm wondering how you would like such a change to be structured, though.

I can see basically two approaches:
1. Util is turned into a "proper" object structured like, say, `RFB`, with a constructor and everything. So you have to do something like `window.util = new Util()` in `ui.js` to initialize the object and make it globally visible.
2. Util is left as a "namespace", but the logging functionality is moved out into a separate object, which is given the treatment described in (1).

Of course, if I go with option 1, a side question is about name clashes, since the code already refers to `Util` all over the place and expects to get the object, and not the constructor. Should the global variable keep the name `Util`, or be renamed to `util` (which would require a changes all over NoVNC) or should the constructor `Util` be renamed to something else? (`window.Util = new Utility()` perhaps?)

I've experimented with this a bit already, but I don't want to put too much work into it until I know which approach you'd prefer, so my pull request actually has a chance of being accepted. :)

Thoughts?

**Comment by juanjoDiaz** [comment]
Since #1206 was rejected. I suggest that this is flagged as won't fix and close as well. 🙂
