### ISSUE TITLE
Support for encrypted passwords

### ISSUE THREAD

**Issue by astrand** [novnc/noVNC#247]
Historically, most VNC clients have supported specifying an encrypted password. This is typically used when the password is stored in disk (~/.vnc/passwd). The "vncpasswd" command can create such a file. Some "web" clients also supports this. For example, the SSHVnc applet has a parameter "sshvnc.connection.encryptedVncPassword". 

Of course, since the encryption is done with a fixed key, this does not provide any real security, but it does provide obfuscation. In a noVNC context, it could mean that it is not possible to view the password by simply doing "view source", for example. 

I was able to add support for decoding an encrypted password by adding this to vnc.html:

```
    // Decode encrypted password
    var encrypted = Base64.decode('myvncpassword', 0);
    var decrypted = new Array(8);
    DES.setKeys([23,82,107,6,35,78,88,7]);
    DES.decrypt(encrypted, 0, decrypted, 0);
    $D('noVNC_password').value = String.fromCharCode.apply(null, decrypted);
```

However, decryption support was removed from des.js in this commit:

https://github.com/kanaka/noVNC/commit/12d2e7c192a63f90ad443ca1525083b72d4de74c

I had to revert to this version of des.js:

https://raw.github.com/kanaka/noVNC/d595e65685162f371cba4099045cf7f522c97720/include/des.js

**Comment by CendioOssman** [comment]
We don't have any passwords stored in the noVNC code, so people are free to do whatever obfuscation they like before handing the data over to our code. Closing.
