### ISSUE TITLE
Consider encodings using zlib (zlib, tight, ZRLE)

### ISSUE THREAD

**Issue by kanaka** [novnc/noVNC#25]
Standard tight encoding and ZRLE will require zlib decompression in Javascript. This will probably be pretty slow (based on some initial testing), but having them as (non-default) options might be worthwhile in some cases.

**Comment by leslie-qiwa** [comment]
@kanaka did you merge tight_png part? 
@quicklyfrozen seems like rfb.js has changed a lot. so would you mind to update your tight_png implementation with upstream?

Background, VMware ESXi VNC uses tight_png encoding. It can decode if forcing to use old tight, it can work, but have graphic glitches sometimes. So I'm thinking it would be great if someone can add the support.

**Comment by CendioOssman** [comment]
TightPNG has been in noVNC since c0c20581f5598a7e0b864d20591e7f65f17c3445 and the protocol has not changed since then AFAIK. There might be bugs though since very few servers use that encoding.

**Comment by kanaka** [comment]
@leslie-qiwa Can you point to any documentation showing that VMware ESXi supports tightPNG? I'm not able to find anything with some quick googling but I would be interested to see some evidence if you have it. I developed tightPNG (along with Corentin Chary) and last I knew it was only support by QEMU and libvncserver.

**Comment by leslie-qiwa** [comment]
No document shows that. I found it because noVNC reports error "unknown encoding -260". 

I use https://github.com/amitbet/vncproxy to dump all messages. It shows ESXi returns both Tight and TightPNG.

Please refer this issue https://github.com/novnc/noVNC/issues/1023

**Comment by leslie-qiwa** [comment]
https://github.com/novnc/noVNC/pull/1026 is created. It works in our ESX environment.

**Comment by CendioOssman** [comment]
Ah, I see the problem. I've opened #1027 so we can handle this discussion better.

**Comment by Neustradamus** [comment]
Note: ZRLE support has been added:
- https://github.com/novnc/noVNC/issues/545
- https://github.com/novnc/noVNC/pull/1589
