### ISSUE TITLE
Need a interface for resize the canvas by the size of the documentElement.client size

### ISSUE THREAD

**Issue by zhoumeina** [novnc/noVNC#312]
When the  VM's VNC display is larger than the browser window we only can add scrollbars to the side of the screen. It would be much more user-friendly if we scaled the display to the window size so that the full desktop is always in view.Can we support it?

we need a interface to set the width and height of the RFB.

**Comment by vishkumar** [comment]
Hello,

I am also facing the same issue where I want to set the dynamic width and height of the RFB but can't. By default it gets set to 800px by 480px. Did anyone find the solution?

**Comment by samhed** [comment]
@vishkumar I responded to your issue #1181
