### ISSUE TITLE
failed to connect: code 1006

### ISSUE THREAD

**Issue by Hr46ph** [novnc/noVNC#341]
I have novnc integrated with openqrm, I'm trying to connect to a newly created VM console.

I'm using Chrome browser, I connect via this URL:
http://192.168.1.10:6002/vnc.html?host=192.168.1.10&port=6002&logging=debug

The error is:
New state 'failed', was 'ProtocolVersion'. Msg: Failed to connect to server (code: 1006)
Util.Error
RFB.updateState
(annoymous function)
websocket.onclose

When I try with vncclient I simply get connection refused. From the terminal the window quickly opens and closes again with no message left in console. When I use the wrong password, I get the message authentication failed.

On the openqrm forums it was suggested that novnc is not accepting connections other than from localhost but I'm not sure if that's true or how to confirm if that is the issue here.

I'd appreciate any help, thanks!

**Comment by SaadBinShahid** [comment]
Does anyone found a solution to this ?

**Comment by kanaka** [comment]
@SaadBinShahid 1006 error is a fairly generic websocket error. There are all kinds of things that can cause this (mostly configuration issues that prevent connectivity at some level). So the solution depends on what specifically is causing your problem.

**Comment by SaadBinShahid** [comment]
Starting webserver and WebSockets proxy on port 6080
WARNING: no 'numpy' module, HyBi protocol will be slower
WebSocket server settings:
  - Listen on :6080
  - Flash security policy server
  - Web server. Web root: /home/mrx/src/bitmenow/noVNC
  - SSL/TLS support
  - proxying from :6080 to localhost:5901


Navigate to this URL:

    http://mrx-machine:6080/vnc.html?host=mrx-machine&port=6080

Press Ctrl-C to exit


127.0.0.1 - - [07/Nov/2015 00:17:17] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
127.0.0.1 - - [07/Nov/2015 00:17:17] 127.0.0.1: Version hybi-13, base64: 'False'
127.0.0.1 - - [07/Nov/2015 00:17:17] 127.0.0.1: Path: '/websockify'
127.0.0.1 - - [07/Nov/2015 00:17:17] connecting to: localhost:5901
handler exception: [Errno 111] Connection refused


This is the error on console, port 6080 if forwarded.

**Comment by kanaka** [comment]
@SaadBinShahid that means that websockify was not able to connect to localhost:5901. Are you sure you're VNC server is listening at that address?

**Comment by ooops4** [comment]
how to make sure that it listens to that address??
help me , i am also stuck here.

**Comment by ooops4** [comment]
> @SaadBinShahid that means that websockify was not able to connect to localhost:5901. Are you sure you're VNC server is listening at that address?


how to make sure that it listens to that address??
help me , i am also stuck here.
