### ISSUE TITLE
Error: "Protocol requested tunnels..."

### ISSUE THREAD

**Issue by Jozsef-B** [novnc/noVNC#364]
After some struggling I managed to get websockify (kanaka-noVNC-v0.4-143-gdf6b7d7.zip) to work using python-3.4.0. under Windows XP (SP3 32 bit).
I test the application in a LAN between two computers using TightVNC (2.7.10+mirror driver).

When I connect to the host computer by loading the client from www.novnc.com everything is fine.

Then I serve the whole NoVNC tree from the host using TinyWeb Server (http://itsecuritylab.eu/index.php/2010/09/24/tinyweb-pocket-size-portable-web-server-with-cgi-and-php-support/).

When I load vnc.html from the VNC host and I try to connect I receive this message:
"Protocol requested tunnels, not currently supported. numTunnels: 2"
The upper info bar turns into reddish and no connection is established.

The number following 'numTunnels:' is sometimes 1, sometimes 2

What can be wrong?

**Comment by darkpixel** [comment]
I was hitting this issue too.  Strangely not when connecting, but when running vnc_playback from a recorded session that worked properly.

**Comment by CendioOssman** [comment]
@DirectXMan12, status of this? Close?

**Comment by DirectXMan12** [comment]
Well, we should probably have an option to let people explicitly disable certain protocols.  I think we can put it off for post-1.0, but I would like to have it eventually

**Comment by CendioOssman** [comment]
Might want to consider splitting that off to a new issue as the original issue seems to have been fixed when `NOTUNNEL` was added.

**Comment by DirectXMan12** [comment]
ack, will do

**Comment by cyrilrey** [comment]
I am also having almost identical issue  whit last version `vnc_lite.html ` :

```
13:54:27.984 Navigated to http://192.168.91.26:6080/vnc_lite.html?token=yyyyy&debug=1
13:54:28.656 rfb.js:688 Failed when connecting: Server wanted tunnels, but doesn't support the notunnel type
_fail @ rfb.js:688
_negotiate_tight_tunnels @ rfb.js:1028
_negotiate_tight_auth @ rfb.js:1042
_negotiate_authentication @ rfb.js:1111
_init_msg @ rfb.js:1302
_handle_message @ rfb.js:734
_recv_message @ websock.js:304
```
As infos: I am trying to connect a small hmi panel Siemens running **windows CE 6.0** with a processor **AMD Inc., i486**. As a result this is an embedded industrial device, I have very limited access to VNC server configuration. I could be possible that this system is not totally compliant with standard vnc protocol.  I know that it seems to be an exotic product for IT people, but that kind of product is even widely deployed in almost every industrial facilities.

I get these extra information from UltraVnc connection info : 
```
Host:  192.168.147.10 Port: 5900 
| Port 2089940572

Desktop geometry: 1280 x 800 x 32
Using depth: 32
Line speed estimate: 40 kbits/s
Current protocol version 3.8

Current keyboard name: 0000100C
Using plugin : -
```
I think there is something is wrong while protocol negotiation.

Else, my novnc server can connect without any problem to alternate standards VNC servers and devices, and that really really rocks. So thanks.

Best regards
Cyril

**Comment by CendioOssman** [comment]
Related, but not quite the same. So could you please file a new issue?

**Comment by cyrilrey** [comment]
I did it. 
Should a delete my comment above ?

**Comment by CendioOssman** [comment]
It's alright, you can leave it.
