### ISSUE TITLE
Problems with Chrome 38

### ISSUE THREAD

**Issue by ctekin** [novnc/noVNC#404]
I just tested the demo with Chrome version 38.0.2125.104 m.

When connecting, it can't catch the error during the binary type support detection. This piece ;

```
try {
    if (bt && ('binaryType' in WebSocket.prototype ||
               !!(new WebSocket(ws_schema + '://.').binaryType))) {
        Util.Info("Detected binaryType support in WebSockets");
        wsbt = true;
    }
} catch (exc) {
    // Just ignore failed test localhost connection
}
```

Still logs the error to the console, which must be a problem with Chrome. And luckily it's still able to connect.

However, disconnection doesn't work and times out with v38. Firefox 32.0.3 and 33 stil works.

**Comment by bencromwell** [comment]
This appears to be fixed in Chrome 40, can anyone confirm? Had a look at the changelog but couldn't find anything.

New log output on disconnection:

    New state 'normal', was 'ServerInitialisation'. Msg: Connected (encrypted) to: QEMU (VM1)
    New state 'disconnect', was 'normal'. Msg: Disconnecting
    WebSocket on-close event
    New state 'disconnected', was 'disconnect'. Msg: VNC disconnected (code: 1006)

**Comment by samhed** [comment]
I can confirm that the disconnect seems to be done properly in Chrome now in version 40.
