### ISSUE TITLE
Actually Raise Exceptions

### ISSUE THREAD

**Issue by DirectXMan12** [novnc/noVNC#418]
Currently, we end up just catching and logging most exceptions.  This is great in certain cases, but it means that when running the unit tests, exceptions can get caught and skipped over, meaning certain broken code may pass unit tests (e.g. df89129ff0bcaa5c4c3f02d06b6ed3ebbe4cba40)

The main, AFAICT, is the `catch` clause under `_recv_message` in [include/websock.js](https://github.com/kanaka/noVNC/blob/master/include/websock.js#L355).

One option would be to pass the exception to Util.Error as a second argument, and then override Util.Error in the unit tests to actually reraise the exception.

@kanaka , @samhed , @astrand : thoughts?

**Comment by CendioOssman** [comment]
I vote we just get rid of the catch in websock.js. It has no place being there IMO. It might be what's hiding things like #813.

**Comment by samhed** [comment]
with better fallback for displaying errors now aswell, I agree

**Comment by CendioOssman** [comment]
Fixed in 1678bf860fd0505baa955aeb1bf24cadc166ad2b.
