### ISSUE TITLE
SSL Error with new certificate

### ISSUE THREAD

**Issue by sykosoft** [novnc/noVNC#426]
We have (due to the recent deprecation of SHA1 for SSL certificates) re-keyed our certificates from SHA1 to SHA256 (as Google Chrome is no longer kind to SHA1). With this simple change (and with the most recent build of noVNC), we are unable to use noVNC. With a simple change of switching back to the old certificate, SSL works once more.

The ONLY difference I can find is here:

Signature Algorithm: sha256WithRSAEncryption
Signature Algorithm: sha1WithRSAEncryption

Can you verify?

Thanks,
Michael

**Comment by DirectXMan12** [comment]
Can you provide more details about your environment?  noVNC itself relies on the browser.  However, if you are connecting to websockify to proxy your websocket connections to normal socket connections (the standard setup), SSL support depends on Python, which in turn depends on OpenSSL.  If you have an old enough version of OpenSSL, you may encounter issues: http://bugs.python.org/issue8484.

Can you post relevant logs (websockify, if used, as well as the developer console log from noVNC)?

**Comment by sykosoft** [comment]
We're using novnc in the following environment:

Ubuntu 12.04
Openstack Essex
Python 2.7

We pulled novnc from git (various fixes vs the deb version, which applied to us), and have been using it successfully for a long time. Recently, we were required to re-key our certificates from SHA1 to SHA256. Thus, the only change is in nova.conf where we set cert/key (changing the path). The certificates work fine for the horizon dashboard, but do not work for novnc.

Attempting to view a VNC console of an instance (via even direct URL vs any iframe) has a problem, and testing with openssl s_client, links, curl, etc (with various debugging flags) show a problem in SSL negotiation. The only difference we can find in the certificates is the sha1 vs sha256 signature. I've updated the pieces that seemed to make sense to try (libssl, python, a few others), but so far, no action has resolved this. I'm open to any and all suggestions.

**Comment by kosmasgiannis** [comment]
I experience the same problem in Firefox but not in Chrome (both latest versions on Mac and Linux). 
I try to connect to noVNC via websockify running on a Centos6 machine with latest openssl (1.0.1e) and python installed.
I am not able to establish a connection from Firefox at all through SSL, without SSL it works fine.

**Comment by DirectXMan12** [comment]
Sorry about the slow response time.  I have attempted to reproduce this on my local system, and was unable to.  Can you confirm the exact Python (`python --version`) and OpenSSL (`openssl version`) versions (e.g. Python 2.7.8, OpenSSL 1.0.1i).

Are you able to connect to other Python SSL programs?  For example, try this:
```python
import ssl
import socket
listen_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
listen_sock.bind(('', 8675))
listen_sock.listen(1)
conn_sock, _addr = listen_sock.accept()
ssl_sock = ssl.wrap_socket(conn_sock, keyfile='key.pem', certfile='cert.pem', server_side=True)
```
And then connect with
```bash
$ openssl s_client -connect localhost:8675
```

Where `key.pem` and `cert.pem` are your key and cert files.

If you can't connect to that, it might indicate an issue with your OpenSSL or Python version.

**Comment by kosmasgiannis** [comment]
Here you are : 
```
-bash-4.1$ python --version
Python 2.6.6
```
and 
```
-bash-4.1$ openssl version 
OpenSSL 1.0.1e-fips 11 Feb 2013
```
I used your example code and ``openssl s_client`` connected without problem.

**Comment by sykosoft** [comment]
Unlike Giannis, mine did not work:

First with the new certificates (sha256)

gsc@avl-mvpcsrv01:~$ ./test.py
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    ssl_sock = ssl.wrap_socket(conn_sock,
keyfile='/etc/apache2/ssl/yyy.yyyyy.com.key',
certfile='/etc/apache2/ssl/yyy.yyyyy.com.crt', server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 141, in __init__
    ciphers)
ssl.SSLError: [Errno 336265218] _ssl.c:351: error:140B0002:SSL
routines:SSL_CTX_use_PrivateKey_file:system lib

Then with my older sha1 certificate

gsc@avl-mvpcsrv01:~$ ./test.py
gsc@avl-mvpcsrv01:~$

**Comment by sykosoft** [comment]
I am however able to make it work with this:

ciphers =
"ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS"
ssl_sock = ssl.wrap_socket(conn_sock,
keyfile='/etc/apache2/ssl/yyy.yyyyy.com.key',
certfile='/etc/apache2/ssl/yyy.yyyyy.com.crt', server_side=True,
ciphers=ciphers)

(And, frankly, those are a hardened cipher selection anyway, and is more
appropriate to use). I don't know where this would need to happen however,
or I would submit a patch.

Michael

**Comment by DirectXMan12** [comment]
@sykosoft : Can you provide more specific information about your OpenSSL version (`openssl --version`, etc)?  It strikes me as odd that changing the cipher suite here could make a difference, unless the ciphers that you provided somehow include ciphers not included in the default.

**Comment by sykosoft** [comment]
OpenSSL 1.0.1 14 Mar 2012 according to openssl version. I agree the cipher
selection fix seems a bit odd to me also (though choosing more secure
ciphers is something I would recommend).

Michael

**Comment by CendioOssman** [comment]
It seems like we never properly diagnosed this. Is this still an issue?

**Comment by sykosoft** [comment]
Yes, it is indeed still an issue. I have to use an old (nearly expired) certificate for this to work.

**Comment by CendioOssman** [comment]
Alright, so I had a look around and most other cases seem to indicate you get this error when there is some problem reading the key file. The ciphers thing is odd though, but I do notice a bunch of diffie-hellman stuff in there so it could be explained with you getting it in to some anonymous mode which doesn't use the key.

Please verify that:

 a) The key file has permission bits that allow you to read it (try `cat`)
 b) That the key file isn't password protected.

**Comment by samhed** [comment]
Closing due to no response.
