### ISSUE TITLE
Keypad keys not detected

### ISSUE THREAD

**Issue by surfsara-visualization** [novnc/noVNC#486]
Locally on my (Arch Linux) desktop machine pressing keypad End gives a KP_End (keysym 0xff9c) key event and regular End results in End (keysym 0xff57). Running xev in a VNC session shows novnc sends End (0xff57) for both keys.

**Comment by DirectXMan12** [comment]
If you use `tests/input.html`, does the output look different between keypad end vs normal end?

**Comment by DirectXMan12** [comment]
CC @jalfd

**Comment by surfsara-visualization** [comment]
Nope: 

0: Display initialized
# Normal end
1: raw key event keydown (key: 35, char: 0, which: 35)
2: RFB keypress down keysym: 65367 key name: 65367
3: raw key event keyup (key: 35, char: 0, which: 35)
4: RFB keypress  up  keysym: 65367 key name: 65367
# Keypad end
5: raw key event keydown (key: 35, char: 0, which: 35)
6: RFB keypress down keysym: 65367 key name: 65367
7: raw key event keyup (key: 35, char: 0, which: 35)
8: RFB keypress  up  keysym: 65367 key name: 65367

**Comment by kanaka** [comment]
I think in order to distinguish these keys, you would need to use DOM 3 location or keyLocation attributes: http://unixpapa.com/js/testkey.html

**Comment by CendioOssman** [comment]
The keyboard code has been fixed to handle this now. Closing.
