### ISSUE TITLE
RDP support

### ISSUE THREAD

**Issue by KieranP** [novnc/noVNC#5]
Is this library compatible with VirtualBox's RDP Server? I'm not sure how'd I'd go about checking it, so that's why I'm asking here.

Regards
Kieran

**Comment by dachande** [comment]
Are there any new info about implementing RDP?

**Comment by DirectXMan12** [comment]
No, not really.  You are welcome to submit patches for this yourself, but we haven't had time/interesting to develop this ourselves.

**Comment by guanxianchun** [comment]
Are there support  Spice protocol Now?

**Comment by samhed** [comment]
Nope, only VNC (RFB) for now.

**Comment by z3r0n3t** [comment]
How about now ?

**Comment by samhed** [comment]
Nope, this is likely never going to happen.

**Comment by chenxinlong** [comment]
Any progress here ?
