### ISSUE TITLE
Create Chrome Firefox apps using raw socket APIs that are available

### ISSUE THREAD

**Issue by ghost** [novnc/noVNC#50]
Is there one yet ? is not there should be and easy to do.

**Comment by Lekensteyn** [comment]
@kanaka's W3C link died, this seems to be the latest version: https://www.w3.org/TR/tcp-udp-sockets/ (the group has closed down though according to https://www.w3.org/2012/sysapps/).

Firefox OS has also been retired, its API docs are also no longer relevant.

Chrome apps [are also being removed](https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html).

With that in mind, I guess that this issue can no longer be solved and it is better to close it?

**Comment by samhed** [comment]
It sure looks like it, thanks for the research.
