### ISSUE TITLE
copy&paste does not work?

### ISSUE THREAD

**Issue by monkey-jsun** [novnc/noVNC#509]
I have install noVNC on a remote ubuntu server together with websocket and xvnc about two months ago. 

First off, vnc viewer works fine regarding copy&paste.  That seems to be prove ubuntu vnc setup is correct.

Secondly, when I select a test on the remote ubuntu machine, I do see "ServerCutText" event on javascript console.

Thirdly,  it appears UI.clipReceive() should be called next, but does not seem so. (BTW, I could not figure where function _onClipboard was defined, which might be gap here.)

noVNC is really great! I'd love to get copy&paste work.  Let me know if you need more info to debug.

(I'm also happy to donate to the project if you are taking donations)

**Comment by monkey-jsun** [comment]
Since there is no replies, I dug a little more. :)

Apparently noVNC supports an intermediate clipboard as shown novnc.com demo.  User can copy into this board in order to paste on remote machine.  And user can also see what is on the remote machine's clipboard.  It works, but not very natural.

HTML5 has clipboard API defined in draft. It looks like a lot of browsers already support it. 

http://www.w3.org/TR/clipboard-apis/
https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent#Browser_compatibility

Should we do something like that for noVNC?  Or is this already happening?

Thanks!

**Comment by DirectXMan12** [comment]
Sorry about not getting back to you sooner.  I've been thinking about this recently, but haven't gotten a chance to work on it.  It would be cool to support the clipboard API, with a fallback to the current behavior.

**Comment by samhed** [comment]
There are ways we can improve the clipboard function, sure. But even with the clipboard API we probably will not be able to make it as seamless as with native VNC viewers.

To copy from the server and paste to the client we need to be able to modify the clipboard. The specification says:

> Synthetic cut and copy events must not modify data on the system clipboard.

To copy from the client and paste to the server we need to be able to read the clipboard. The specification says:

> Synthetic paste events must not give a script access to data on the real system clipboard.

**Comment by paulsimon99** [comment]
Is there a way to map copy and paste keyboard shortcuts (Cmd-c, Cmd-v) from Mac in NoVNC?

**Comment by samhed** [comment]
https://groups.google.com/forum/#!topic/novnc/qHBfxVW9jYc

**Comment by DirectXMan12** [comment]
(closing this for now, we can open a more specific bug about using the Clipboard API)

**Comment by schlusslicht** [comment]
Managed to glitch in some 'feels kinda real' clipboard support.

```
<script type="module" crossorigin="anonymous">
    import RFB from './core/rfb.js';

    (function() {
        var rfb = new RFB(document.body, location.href + '/websockify');
        var clipboard = document.getElementById('clipboard');

        rfb.addEventListener('clipboard', function(e) {
            clipboard.value = e.detail.text;
        });

        rfb.addEventListener('connect', function(e) {
            var viewer = document.getElementsByTagName('canvas')[0];

            document.body.addEventListener('paste', function(e) {
                rfb.clipboardPasteFrom(e.clipboardData.getData('text'));
            });

            document.body.addEventListener('keydown', function(e) {
                if (e.keyCode !== 86) e.preventDefault();
                setTimeout(function() {
                    viewer.dispatchEvent(new e.constructor(e.type, e));
                    rfb.focus();
                }, 1);
            });

            document.body.addEventListener('keyup', function(e) {
                if (e.keyCode !== 86) e.preventDefault();
                setTimeout(function() {
                    viewer.dispatchEvent(new e.constructor(e.type, e));
                    rfb.focus();
                }, 1);
            });

            viewer.addEventListener('keydown', function(e) {
                if (e.ctrlKey) document.activeElement.blur();
            });

            viewer.addEventListener('keyup', function(e) {
                if (e.ctrlKey && [67, 88].includes(e.keyCode)) {
                    clipboard.focus();
                    clipboard.select();
                    document.execCommand('copy');
                    rfb.focus();
                }
            });
        });
    })();
</script>

...

<textarea id="clipboard" style="position: fixed; z-index: -1;"></textarea>
```
Paste works something like:
* Press ctrl: blur activeElement (focus falls back to document.body)
  * Release (ctrl-)key: prevent event default behaviour, proxy keyup event to viewer, focus rfb
  * Press (ctrl+)key: prevent event default behaviour, proxy keydown event to viewer, focus rfb
  * Press (ctrl+)v: document.body emits paste event, proxy keydown event to viewer, focus rfb
    * rfb clipboard is set to emitted clipboardData textual representation
    * delayed proxied ctrl+v keydown event triggers paste insite vnc server

Copy works something like:
* Press ctrl+c/x: rfb emits clipboard event, textarea value is set accordingly
* Release ctrl+c/x: focus textarea, select value, exec copy, focus rfb

Works for plaintext on Chromium (67.0.3396.79) and Firefox (60.0.2).

**Comment by darkworks** [comment]
any update on this , please this patch

**Comment by twhitehead** [comment]
If you want to try @schlusslicht's hack, add it in to the `vnc_lite.html` file
```
<!DOCTYPE html>
<html lang="en">
<head>
    ...

    <!-- actual script modules -->
    <script type="module" crossorigin="anonymous">
        ...

        // Add listeners to important events from the RFB module
        rfb.addEventListener("connect",  connectedToServer);
        rfb.addEventListener("disconnect", disconnectedFromServer);
        rfb.addEventListener("credentialsrequired", credentialsAreRequired);
        rfb.addEventListener("desktopname", updateDesktopName);

        ... insert it here starting with the var clipboard = document.getElementById('clipboard') line ...

        ....
    </script>
</head>

<body>
    ... insert the textarea bit here ...

    ...
</body>
```
You can even do this live in chrome with an existing site by enabling the overrides feature in the development console and then updating their copy of the code.

One issue is it depends on the exact keys used to cut and paste. For example, emacs uses `ctrl+y` and `ctrl+w`. These do not trigger this code. Likewise, the terminals frequency use `ctrl+shift+c` and `ctrl+shift+v`, which trigger the events (as it only checks for `ctrl` being pressed, so that is also satisfied with `ctrl+shift` is being pressed) but not the browser's paste interaction with the `textarea`. The net effect is `ctrl+shift+c` works to copy, but pasting requires you to first do a `ctrl+v` so the browser updates the `textarea`, and then `ctrl+shift+v` to insert it into the terminal.

For what it is worth, The [ondemand repo](https://github.com/OSC/ondemand) has put together a much more [advanced version of `vnc_lite.html` (see `vnc.html`)](https://github.com/OSC/ondemand/tree/master/apps/dashboard/public/noVNC-1.3.0) that includes native support for copying and pasting under chrome and an explicit intermediate clipbroad for other browsers. I believe you should just be able to grab this and use it if you want.

**Comment by hsbtr** [comment]
> If you want to try @schlusslicht's hack, add it in to the `vnc_lite.html` file
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>     ...
> 
>     
>     <script type="module" crossorigin="anonymous">
>         ...
> 
>         // Add listeners to important events from the RFB module
>         rfb.addEventListener("connect",  connectedToServer);
>         rfb.addEventListener("disconnect", disconnectedFromServer);
>         rfb.addEventListener("credentialsrequired", credentialsAreRequired);
>         rfb.addEventListener("desktopname", updateDesktopName);
> 
>         ... insert it here starting with the var clipboard = document.getElementById('clipboard') line ...
> 
>         ....
>     </script>
> </head>
> 
> <body>
>     ... insert the textarea bit here ...
> 
>     ...
> </body>
> ```
> 
> You can even do this live in chrome with an existing site by enabling the overrides feature in the development console and then updating their copy of the code.
> 
> One issue is it depends on the exact keys used to cut and paste. For example, emacs uses `ctrl+y` and `ctrl+w`. These do not trigger this code. Likewise, the terminals frequency use `ctrl+shift+c` and `ctrl+shift+v`, which trigger the events (as it only checks for `ctrl` being pressed, so that is also satisfied with `ctrl+shift` is being pressed) but not the browser's paste interaction with the `textarea`. The net effect is `ctrl+shift+c` works to copy, but pasting requires you to first do a `ctrl+v` so the browser updates the `textarea`, and then `ctrl+shift+v` to insert it into the terminal.
> 
> For what it is worth, The [ondemand repo](https://github.com/OSC/ondemand) has put together a much more [advanced version of `vnc_lite.html` (see `vnc.html`)](https://github.com/OSC/ondemand/tree/master/apps/dashboard/public/noVNC-1.3.0) that includes native support for copying and pasting under chrome and an explicit intermediate clipbroad for other browsers. I believe you should just be able to grab this and use it if you want.

In the column you gave, I didn't see any clipboard related use in vnc.html, is it adjusted
