### ISSUE TITLE
Sometimes we don't get a framebuffer update after panning

### ISSUE THREAD

**Issue by samhed** [novnc/noVNC#517]
When clipping and panning we require new data from the server to draw the new parts of the screen. This seems to be working very inconsistently. The result is that you have blank parts of the screen until you do something else which will trigger the update.

It is a lot easier to reproduce on touch devices, where you don't have a mouse cursor. Disabling "Local cursor" can also make it easier to reproduce.

**Comment by DirectXMan12** [comment]
Did you notice this before or after the performance code merge?  I would like to make sure that I didn't cause any issues.

**Comment by samhed** [comment]
Before. I don't think your changes affected this. I have seen the issue for quite a while, just never got to reporting it.

**Comment by samhed** [comment]
Yeah, just verified briefly, the behavior is still the same, no difference from your changes.

**Comment by samhed** [comment]
Fixed now seeing as #699 is merged.
