### ISSUE TITLE
Double buffering

### ISSUE THREAD

**Issue by samhed** [novnc/noVNC#518]
Currently we don't buffer the entire framebuffer in noVNC, the only 'buffer' except for the receive queue we have is the canvas itself, the same canvas we show the user. Additionally, the canvas only contains what is shown in the viewport. In the case of clipping there are parts of the screen which isn't stored client-side.

I would like to discuss the possibilities of a double buffering architecture in noVNC. One buffer which would contain the entire remote framebuffer and the other being the canvas which contains the data  shown in the viewport. It can be worth noting that most native VNC clients use double buffering.

I see the following advantages with double buffering:
- Avoid screen-tearing since we can draw the entire on-screen canvas at the same time through copying the contents from the buffer ( #482 )
- If the viewport is smaller than the remote frame buffer we can resize the viewport or use panning (if clipping) and see the new areas without having to wait for an update from the server.
- We can get more robust code and avoid bugs like #517. It can also make features like zoom easier to implement.

The disadvantages I can come to think of are:
- Rendering will be slightly slower.
- It will use a bit more memory on the client.
- In the case of a smaller viewport, it could use more bandwidth since we could get updates for things happening outside the viewport which we might or might not draw.

---

I'm thinking a second canvas which is off-screen. Canvas context operations like drawImage and getImageData can be used with another canvas as the source. This way we can use the same operations and the restructure doesn't have to be as comprehensive.

Now when @DirectXMan12 has merged the performance improvements from #488, do you think we have enough leeway to handle the hit to the rendering speed?

**Comment by DirectXMan12** [comment]
> I'm thinking a second canvas which is off-screen. Canvas context operations like drawImage and getImageData can be used with another canvas as the source. This way we can use the same operations and the restructure doesn't have to be as comprehensive.

This sounds like the way to do it.  I wonder if there's any performance change due to offscreen or onscreen canvas use.  I think the speed of this really depends on how good the browsers are at redrawing due hiding/showing the canvas.  Can you whip up a prototype so that we can take a look?

**Comment by samhed** [comment]
Will do, I have some other stuff I'm working on at the moment, but this shouldn't take too long so I hope to get to it soon enough.

**Comment by samhed** [comment]
Merged in #699
