### ISSUE TITLE
ZRLE support

### ISSUE THREAD

**Issue by jas8522** [novnc/noVNC#545]
I believe this may be related to the issue here: https://github.com/kanaka/noVNC/issues/528

The Repeater appears to be connecting perfectly, but when it attempts to negotiate with the server (through the repeater), the server indicates that it's using protocol version 003.016. Just like the user in the link above, I added 003.016 (although they were using 003.010) to the supported protocols and received:

Disconnected: unsupported encoding 16

Is there still no information on the type of encoding required to make this protocol version work?

According to Wikipedia encoding type 16 is File Transfer Protocol: https://en.wikipedia.org/wiki/RFB_protocol

**Comment by jas8522** [comment]
Actually it seems the encoding may be ZRLE. I was interpreting 16 incorrectly. 16 corresponds to 0x00000010 hex, which according to the Wikipedia article should be ZRLE

**Comment by DirectXMan12** [comment]
Well, we have a fairly performant zlib library now, so we should be able to support ZRLE.  I probably will not have time to get to it anytime soon, but we'd certainly be willing to accept PRs.

**Comment by jas8522** [comment]
What do you think the chances are that the existing zlib library and this GNU rle encode/decode code can be paired up to implement ZRLE encoding in noVNC? http://www.marklomas.net/ch-egg/articles/rlejs.htm

**Comment by kanaka** [comment]
@jas8522 pretty high if you implement it. ;-) There isn't any chance that I will get to this any time in the reasonable future. I suspect the same is true for @DirectXMan12. However, encodings are independent of each other so there is a good chance we would review and merge it in if there is a clean implementation (follows current coding style, doesn't break other tests, etc)

**Comment by jas8522** [comment]
Hey Kanaka,

I wasn't attempting to have it created for me with that request, but rather to ask if anyone familiar with how RFB encoding typically works could indicate the best way to integrate that RLE code with the existing zlib library in noVNC. In other words, do you think I'm better off trying to build my ZRLE implementation from scratch or attempt to integrate the existing RLE Javascript code found above?

Do you have any tips for debugging an encoding type? In other words, what's best to test whether a section is working or not? I'm familiar with Javascript, but not so much with working with image tiles or display pixels. 

I'm working with the RFB documentation that includes the details of ZRLE. Any tips for how best to interpret their docs? It seems to me like starting with the HEXTILE code's usage of the FBU then modifying as necessary may work well. Thoughts on that?

**Comment by CendioOssman** [comment]
Fixed via #1589.
