### ISSUE TITLE
click NUMPAD_ADD,but show  Equal 

### ISSUE THREAD

**Issue by seanfly** [novnc/noVNC#569]
when I click " + "  in numpad, it shows '' = " on the vnc screen.
![novnc1](https://cloud.githubusercontent.com/assets/13298682/12264727/a56eb70c-b973-11e5-8f29-8c08bf1e3321.png)

And when I click " \* " in numpad ,it shows '' 8 '' on the vnc screen.
![Uploading novnc2.png…]()

who knows how to slove this question ? thanks.

**Comment by DirectXMan12** [comment]
Right now, noVNC has trouble distinguishing between normal keys and numpad keys (I recall seeing a similar bug, but can't find it right now).

We might be able to use the `KeyboardEvent.location` field (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/location) to help here.

**Comment by seanfly** [comment]
I debug the input.js  in the chrome developer tools. The numpad keys's  keycodes  are right. 
" + "  is 107 and " * " is 106. But maybe something is wrong  when the keycode is parsed .

**Comment by samhed** [comment]
Sorry for the late response here, but I can not reproduce your issue in Chrome or Firefox on linux. You were using Chrome I assume, on what platform?
