### ISSUE TITLE
Protocol mismatch base64 != sample

### ISSUE THREAD

**Issue by cavac** [novnc/noVNC#57]
Using the version from the public git repo and a current chromium-browser, i can't get a successfull connection.

The javascript debug output is:

> > RFB.constructor
> > util.js:69>> Display.constructor
> > util.js:69User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Ubuntu/11.04 Chromium/11.0.696.57 Chrome/11.0.696.57 Safari/534.24
> > util.js:69Browser: webkit 534.24
> > util.js:70Canvas supports imageData
> > util.js:70Using Canvas createImageData
> > util.js:70Prefering javascript operations
> > util.js:70Data URI scheme cursor supported
> > util.js:69<< Display.constructor
> > util.js:70Using native WebSockets
> > util.js:71New state 'loaded', was 'disconnected'. Msg: noVNC ready: native WebSockets, createImageData rendering
> > util.js:69<< RFB.constructor
> > util.js:71New state 'connect', was 'loaded'.
> > util.js:69>> RFB.connect
> > util.js:70connecting to ws://planetx:6080/
> > util.js:69<< RFB.connect
> > :6080Error during WebSocket handshake: protocol mismatch: base64 != sample
> > util.js:69>> WebSock.onclose
> > util.js:72New state 'failed', was 'connect'. Msg: Server disconnected
> > util.js:69Clearing connect timer
> > util.js:69<< WebSock.onclose
> > util.js:71New state 'failed', was 'failed'.

Output of the /utils/launch.sh is:

 16: 127.0.0.1: Plain non-SSL (ws://) WebSocket connection (version 76)
 16: connecting to: localhost:5900
 16: 127.0.0.1: Client closed

This should be the relevant TCP/HTTP connection (captured with wireshark & "follow TCP stream"):

GET / HTTP/1.1
Upgrade: WebSocket
Connection: Upgrade
Host: planetx:6080
Origin: http://planetx:6080
Sec-WebSocket-Protocol: base64
Sec-WebSocket-Key1: {3?9R(F345  0MH00[~12DC
Sec-WebSocket-Key2: 3  V1F9MZ60E795wb5~  2
Cookie: logging=debug; stylesheet=default; host=planetx; port=6080; password=; encrypt=false; true_color=true; cursor=false; shared=true; connectTimeout=2

.7...Xj,HTTP/1.1 101 Web Socket Protocol Handshake
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Origin: http://planetx:6080
Sec-WebSocket-Location: ws://planetx:6080/
Sec-WebSocket-Protocol: sample

Hf4..mR...L.W&i.

**Comment by adarwash** [comment]
I am getting same error 

10.1.1.95 - - [19/Oct/2016 21:33:54] 10.1.1.95: Plain non-SSL (ws://) WebSocket connection
10.1.1.95 - - [19/Oct/2016 21:33:54] 10.1.1.95: Version hybi-13, base64: 'False'
10.1.1.95 - - [19/Oct/2016 21:33:54] 10.1.1.95: Path: '/websockify'
10.1.1.95 - - [19/Oct/2016 21:33:54] connecting to: localhost:5900
handler exception: [Errno 57] Socket is not connected

**Comment by samhed** [comment]
How is that the same error? Did you mean to paste the output from the javascript console?

**Comment by adarwash** [comment]
My bad, I will open new issue. Thanks for pointing that out, need to more coffee, brain not functioning right :)
