### ISSUE TITLE
Scrolling with a trackpad is extremely sensitive on OS X and Chrome OS

### ISSUE THREAD

**Issue by samhed** [novnc/noVNC#577]
Scrolling using a trackpad in noVNC running on Safari or Google Chrome (OS X 10.11) is perhaps 10 times as sensitive as when scrolling locally.

The problem does not seem to exist in Firefox on OS X.

**Comment by richtera** [comment]
I also see windows disappearing and reappearing when using the scroll on a trackpad. This happened under chrome OS but I am not sure if it's a OS thing.

**Comment by samhed** [comment]
That's nothing I recognize, could you take a screenshot or video?

**Comment by oneru** [comment]
@richtera Is the server computer a Linux machine?  The disappearing windows sounds like you have virtual desktops enabled, and the scroll wheel is switching virtual desktops.

**Comment by richtera** [comment]
That would make sense. Ok I'll check into it.

**Comment by samhed** [comment]
I'm seeing the same issue with sensitive scrolling when using the touchpad on a Chromebook.

**Comment by TzahiFadida** [comment]
Is there a suggested concept for the fix?

I tried to stop receiving mouse events in device after a storm of events from the touchpad. It is ok but it also affects the mouse. The behavior is that the touchpad immidiately accumulates hundreds of scroll events for the slightest touch. The problems i noticed where that there does not seem to be a way to determine if the scroll came from a touchpad or mouse wheel. Also, when you stop receiving events it affects the entire viewport. I was thinking maybe not using settimeout and instead use a precision now() (for supporting browsers). Then use a sliding window over an array of 100ms. Then average the events for 1 sec. Make it more like a mousewheel.

**Comment by samhed** [comment]
@TzahiFadida that sounds like a good solution

**Comment by samhed** [comment]
I don't think this issue affects enough users to warrant a high priority. I propose to remove this from the 0.7 milestone.

**Comment by alxppp** [comment]
This issue basically affects all macOS users (majority is using Safari or Chrome). To me it sounds quite important.

**Comment by samhed** [comment]
Why does all Mac OS users use a trackpad instead of a mouse?

**Comment by alxppp** [comment]
It happens with mouses too, at least with the Magic Mouse, which ships with all desktop Macs. Maybe it doesn't happen with non-Apple mouses, which have scroll wheels.

**Comment by alxppp** [comment]
I spent some time on this issue today. The problem is the differing `wheelDelta` of different browsers and devices. MacBook trackpads send a lot of very small deltas, whereas mouses with a scroll wheel send a larger delta per scroll stop. Facebook built a small function to normalize these deltas (https://github.com/facebook/fixed-data-table/blob/master/src/vendor_upstream/dom/normalizeWheel.js). I embedded this function into the `_handleMouseWheel` in `devices.js` and it seems to work quite well. I tested it on Chrome, Safari and Firefox with a MacBook trackpad, an Apple Magic Mouse, and a "classic" Logitech Mouse and they all scrolled sanely. Will try to test this on Windows too.

**Comment by samhed** [comment]
Great! Thanks for looking into this @alxppp ! We will gladly accept a PR

**Comment by samhed** [comment]
@alxppp how's it going? Can I assist in any way?

**Comment by alxppp** [comment]
@samhed in which file would you like to have the helper functions (e.g. normalizeWheel)?

**Comment by samhed** [comment]
Probably as a separate file in `core/input/` thank you :)

**Comment by samhed** [comment]
Hi @alxppp, how's it going? Could you share your work or open a PR?

**Comment by samhed** [comment]
Whops, forgot to make a branch

**Comment by samhed** [comment]
Ok, so with regards to the normalizeWheel function, I had a deeper look and that will not make any difference. The problem is not that different browsers/platforms send different deltas. The problem is that we disregard deltas altogether.

My testing has shown that touchpads generally always send many small delta events while regular mouses send fewer events with bigger delta values per event.

I have a suggestion in #896 and would love if everyone in this thread could test that and see if it improves the experience for you @alxppp, @TzahiFadida.

One thing to note is that trackpads I have tested on macOS and Windows have what is sometimes called "inertia scrolling" or "touch mode scrolling". This means that if you do a swipe and release the finger from the trackpad the scrolling effect will continue for a bit and gradually slow down until it eventually stops.
Historically there has been ways to stop this effect by using some CSS rules, but now-a-days there does not seem to be any way to disable this. My testing suggests that it is happening on a OS-level in macOS and Windows.
This behavior does not exist on Linux.
