### ISSUE TITLE
noVNC connectivity for Chromium/Awesomium

### ISSUE THREAD

**Issue by silentcenturion** [novnc/noVNC#586]
I am trying to make the following connection:

Client1 - Win10 x64 - Awesomium (32-bit) browser for Unity-3D (32-bit executable, since Awesomium, which is based on Chromium, does not support x86_64 on Windows)
Client2 - Same machine as above, except using Chrome
Server - Debian running x11VNC and noVNC/utils/launch.sh

Client 2 connects with no problems and similar performance to the dedicated realVNC client.
Client 1 fails with "handler exception: [Errno 107] Transport endpoint is not connected"

I know Awesomium (C# wrapper for Chromium) supports WebSockets (https://github.com/coreyauger/awesomium.ui), but I'm not sure if it supports base64 WebSockets only, or also supports binary WebSockets (http://answers.awesomium.com/questions/4072/does-awesomium-17-supports-websocket-wss-protocol.html). 

Is my guess correct about the possible root of the problem (e.g., lack of binary WebSockets support by my particular HTTP client), or is it a possible noVNC issue?  Does anyone have any experience getting noVNC working with Awesomium and/or Chromium?

**Comment by DirectXMan12** [comment]
Chromium should work fine (I use it and Firefox as my daily drivers). What build of Chromium is your version Awesomium based on?

**Comment by silentcenturion** [comment]
Great question.  I’m not sure; I searched through the entire available source code and meta-data for Awesomium SDK (without reversing the binaries), and saw no mention of the Chormium version it wraps.  However, the Chromium options it supports are listed here: https://gist.github.com/khrona/2999122, and the download link is here: (http://www.awesomium.com/download/).  According to http://answers.awesomium.com/questions/1735/chromium-version.html, as of 2013 it was Chromium 18.0.1003, which was a year behind the latest Chromium release (not very helpful since the Awesomium project may have picked up additional resources since then to keep abreast with the latest Chromium releases).

 

After trying every single Node.js-based solution for RDP/VNC I could get my hands on, and every combination of VNC servers (Tight, Tiger, X11, noVNC, Turbo, real, Java, etc.) and UI (XFCE, Gnu, MATE, Cinnamon, LXDE, KDE, etc.), I finally got Awesomium working with Guacamole (http://guac-dev.org/) and TightVNC on Debian 8 (64-bit) with XFCE running on VBox (Win10 host).

**Comment by silentcenturion** [comment]
Great question.  I’m not sure; I searched through the entire available source code and meta-data for Awesomium SDK (without reversing the binaries), and saw no mention of the Chormium version it wraps.  However, the Chromium options it supports are listed here: https://gist.github.com/khrona/2999122, and the download link is here: (http://www.awesomium.com/download/).  According to http://answers.awesomium.com/questions/1735/chromium-version.html, as of 2013 it was Chromium 18.0.1003, which was a year behind the latest Chromium release (not very helpful since the Awesomium project may have picked up additional resources since then to keep abreast with the latest Chromium releases).

After trying every single Node.js-based solution for RDP/VNC I could get my hands on, and every combination of VNC servers (Tight, Tiger, X11, noVNC, Turbo, real, Java, etc.) and UI (XFCE, Gnu, MATE, Cinnamon, LXDE, KDE, etc.), I finally got Awesomium working with Guacamole (http://guac-dev.org/) and TightVNC on Debian 8 (64-bit) with XFCE running on VBox (Win10 host).

**Comment by DirectXMan12** [comment]
Guacamole works slightly differently -- it effectively runs a noVNC client on the server, and then shoves the full-rendered results to the client.  Can you open a developer console (or make a test page) and check to see if a created WebSocket object has the `binaryType` property, and if it's settable?

**Comment by silentcenturion** [comment]
Thanks for your interest in helping!

I did a string dump of awesomium.dll and had a couple of hits for "binaryType" seemingly in a typedef or #define section.

I made several attempts at making Awesomium work outside of Unity3D (e.g., via Mono Gtk+ and Mono WinForms) but no luck in seeing a developer console or a binaryType object through the MonoDevelop/Xamarin debugger. 

I also captured the awesomium.dll process (and its threads) calls and searched inside the stack/heap variables, but didn't find anything named 'binaryType' (the var names are probably mangled at that level), or perhaps the WebSocket invocation spawns a whole separate process that I missed; I'll do more digging...

I fired up the compiled/executable Unity game (which has the Awesomium browser in it as a game object) and tried stepping through it in the Visual Studio debugger, but ended up with a frozen machine, resulting in a hard reboot with undesired consequences (my bad for not using a dedicated DevOps box for this).  I'll spend more time on it later this week using windbg to track the WebSocket object...

Do you happen to know which function(s) in Chromium would be creating the WebSocket object?

**Comment by silentcenturion** [comment]
...I forgot to mention: I also did a quick search on the Awesomium C++ and C# APIs (http://www.awesomium.com/docs/1_7_2/cpp_api/) (http://docs.awesomium.net/) for certain keywords (e.g., 'WebSocket', 'binaryType'), but no luck.

**Comment by VoidVolker** [comment]
Yes, awesomium have old version of chrome and very poor documentaion - looks like it abandoned. Try to use [NWJS](https://github.com/nwjs/nw.js) - it have latest chromium with full support of web sockets and have nodejs integrated with native sockets.

**Comment by samhed** [comment]
@silentcenturion what is the status on your project? Did you have a chance to test NWJS that was mentioned?
