### ISSUE TITLE
Chrome 1006 issues with noVNC

### ISSUE THREAD

**Issue by markknit** [novnc/noVNC#588]
I have noVNC successfully installed and working on Ubuntu 14. I have tested it with Firefox, IE, Edge, and the native Android browser. All work fine. However, I just discovered that Chrome does not work from any platform. I've tried it from several Windows devices (all using Chrome 49). and 2 android devices with Chrome. In all cases I get an immediate disconnect 1006 error. However, any other browser on the same device works fine. I've checked the syslog and apache logs, but don't see anything there. 

Is there something that needs to be done in setup that is unique to Chrome? 

I just ran debug using the js console. Here's the relevant output:

util.js:220  Msg: Server disconnected (code: 1006)Util.Error @ util.js:220RFB._updateState @ rfb.js:468RFB._fail @ rfb.js:538(anonymous function) @ rfb.js:208(anonymous function) @ websock.js:320
util.js:220 Error while connected.Util.Error @ util.js:220RFB._updateState @ rfb.js:514RFB._fail @ rfb.js:538(anonymous function) @ rfb.js:208(anonymous function) @ websock.js:320
util.js:214 << WebSock.onclose

Thanks, Mark K

**Comment by samhed** [comment]
I'm afraid that 1006 just means the connection was closed without receiving a close frame. It doesn't tell us specifically what went wrong.

I quickly verified that the latest master works for me in Chrome 49 on Linux and Android and Chrome 50 beta on Linux.

What VNC server are you using? Do you see anything in the logs for the server?

**Comment by markknit** [comment]
X11VNC. I didn't see anything in the setup/logs unique to Chrome (AFAIK). I can reinstall or try another VNC install. Which one did you test with?

**Comment by markknit** [comment]
I need to correct what I said previously - I have x11 & vnc4server installed, but vnc4 is being used with novnc. I'll try switching to x11, but would still like to know which one you tested with. 

Thanks, Mark K

**Comment by samhed** [comment]
I mostly use the TigerVNC server

**Comment by lxp** [comment]
I think this might be related to the bug I am experiencing with Chrome.
I am using latest master version (https://github.com/novnc/noVNC/commit/93c4b5caaa1445c49efaccbad5b761ab1c88dc9d) and I'll get the following error, when I connect to my custom WebSocket server that doesn't support WebSocket subprotocol negotiation:
```
WebSocket connection to 'wss://<domain>/<path>' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
open @ websock.js:278
_connect @ rfb.js:387
_updateConnectionState @ rfb.js:547
connect @ rfb.js:282
connect @ ui.js:1079
```
Followed by:
```
Failed when connecting: Failed to connect to server ( (code: 1006))
Util.Error @ util.js:44
_fail @ rfb.js:579
(anonymous) @ rfb.js:234
(anonymous) @ websock.js:306
```

It seems Chrome is the only browser that conforms to the WebSocket API specification (https://html.spec.whatwg.org/multipage/comms.html#network). For example, Firefox ignores that a subprotocol was requested and the server doesn't support subprotocol negotation.
If the server doesn't support subprotocol negotiation, then the only way to connect to it with Chrome is to not supply any protocols (either nothing or empty array). I have a working branch here: https://github.com/novnc/noVNC/compare/master...lxp:workarounds

I would be interested in getting support for WebSocket servers incapable of subprotocol negotiation in noVNC.

Would you prefer an additional flag `wsProtocolNegotiation` or opt for changing the whole handling of the `wsProtocols` option?

PS: I also think that noVNC currently doesn't use WebSocket subprotocols in the correct way. I think it should use subprotocol `rfb`, as specified in https://www.iana.org/assignments/websocket/websocket.xhtml#subprotocol-name.

**Comment by CendioOssman** [comment]
The non-standard protocol stuff is now gone on `master`. Please give it another try.

**Comment by lxp** [comment]
Thank you! It works for me now, when I set the `wsProtocols` option to `[]`.
@markknit: Does this also solve your problem?
