### ISSUE TITLE
Add support for UltraVNCs extended Clipboard

### ISSUE THREAD

**Issue by tenchman** [novnc/noVNC#61]
Last year the UltraVNC folks implemented extended clipboard support which provides the ability to handle UTF8 text, RTF and some more formats. It would be nice to see support for this in noVNC too.

**Comment by CendioOssman** [comment]
I also documented this in the rfbproto document:

https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#extended-clipboard-pseudo-encoding
