### ISSUE TITLE
Error with certificate and HTTPS

### ISSUE THREAD

**Issue by Issam2204** [novnc/noVNC#612]
I've setup TightVNC + noVNC on my dedicated server. I use an NGINX upstream so that I can easily browse to noVNC by going to "vnc.MYSERVER.net". Two things happen:

1) vnc.MYSERVER.net is translated into http://vnc.MYSERVER.net/vnc.html?host=DOMAIN&port=6080

2) HTTPS are redirected to HTTPS.

This way I always end up with http**s**://vnc.MYSERVER.net/vnc.html?host=DOMAIN&port=6080, which is good because it's what I want.

The domain and all subdomains are are certified with Letsencrypt.

What I did in the launch.sh file of noVNC is to indicate the path of the Letsencrypt certificate.

`CERT="/etc/letsencrypt/live/MYSERVER.net/fullchain.pem"`

noVNC starts on boot as root user so that it can read the Letsencrypt certificate.

What am I doing wrong with this approach? By using the IP address of the server everything works, but not on HTTPS. I get an error:

> Server disconnected (code: 1006)

Thanks!

**Comment by samhed** [comment]
Sorry for the late response, did you manage to find a solution?
