### ISSUE TITLE
Scaling mode on vnc_auto.html

### ISSUE THREAD

**Issue by drt0927** [novnc/noVNC#617]
I need the local downscaling mode in vnc_auto.html

**Comment by mkunz7** [comment]
https://github.com/novnc/noVNC/pull/780

Add the line
```
document.getElementById(""noVNC_setting_resize"").value = "Local Downscaling";
```

**Comment by samhed** [comment]
@mkunz7 There is no element called noVNC_setting_resize in vnc_auto.html

**Comment by mkunz7** [comment]
The vnc_auto suggests it is the autoconnect form of vnc. It's not, it's a stripped down version of vnc to demonstrate minimal functionality. Adding to that functionality seems counter intuitive. 

Using the full version you can add a few lines of code to vnc and it will auto connect like the name for vnc_auto implies and allows users to customize whatever.

**Comment by samhed** [comment]
Adding support for a few more settings through query parameters is fine in my mind. There could be other reasons aside from autoconnect that makes people want to use vnc_auto.html

**Comment by CendioOssman** [comment]
It depends on where we end up with #695. It can't be both minimal and have lots of features.

**Comment by CendioOssman** [comment]
It seems we're landing on the minimal approach, so I suggest we close this issue?

**Comment by samhed** [comment]
Agreed.
