### ISSUE TITLE
AltGr key combinations don't work with German keyboard layout

### ISSUE THREAD

**Issue by robert-scheck** [novnc/noVNC#634]
All AltGr key combinations don't seem to work with German keyboard layout (same layout at both sides). Client is Firefox 38.x (ESR) or 47.x (non-ESR), novnc 0.5.1 or 0.6.1, VNC server is provided via QEMU's websocket, started with `-k de`, QEMU 1.5.3 as provided with latest CentOS 7 including all updates. The AltGr key combinations however do work fine using `vncviewer` from TigerVNC 1.1.0 (as shipped with latest CentOS 6 including all updates).

**Comment by robert-scheck** [comment]
Btw, using https://github.com/danielhb/noVNC/tree/0.5.1_qemu_extension from @danielhb leads to the result that I can not type anything at all anymore.

**Comment by danielhb** [comment]
My branch will not work if you start QEMU with -k de or any other option of -k

**Comment by robert-scheck** [comment]
Good pointer, you are right! However I need a working German keymap for classic VNC clients such as TigerVNC and working noVNC…

**Comment by danielhb** [comment]
I believe the only German keymaps supported by QEMU -k option are 'de' and 'de-ch' (just checked in virt-manager)

However I think TigerVNC has the QEMU extension support. The trick to use this extension is to never use the -k option when starting QEMU. 

If TigerVNC doesn't support it I am sure that vinagre (Remote Desktop Viewer of Gnome) does.

**Comment by robert-scheck** [comment]
I was using 'de' before, but unfortunately TigerVNC was just an example, it also needs to work with RealVNC (which already needs a 'ColorLevel' setting change).

Any pointer how I could make AltGr key combinations working in a hackish way related to German keyboard layout only when QEMU is started with `-k de`?

**Comment by danielhb** [comment]
Aside from hacking in the source code of QEMU, the other way I can think of doing that is to setup the guest OS keymap to accept Right Alt + Left Ctrl as being equal to AltGR. Windows does that under the hood.

**Comment by robert-scheck** [comment]
Given this is Windows inside the virtual machine, your idea does interestingly not work for `\`, but for `€`…while I care more about the non-working `\` rather the `€`. Oh dear, these keymaps.

**Comment by CendioOssman** [comment]
The keyboard code has gotten lots of bug fixes. Can you check if this still is an issue?

**Comment by samhed** [comment]
Closing due to no response.
