### ISSUE TITLE
non-true color mode broken

### ISSUE THREAD

**Issue by CendioOssman** [novnc/noVNC#669]
I guess few use this so it has bit rotted. I'm getting this with Firefox and a TigerVNC server:

```
recv_message, caught exception: 
    name: TypeError
    message: bgr is undefined
Display.prototype._setFillColor@http://localhost:6080/core/display.js:687:17
Display.prototype.fillRect@http://localhost:6080/core/display.js:377:17
RFB.encodingHandlers.RRE@http://localhost:6080/core/rfb.js:1727:17
RFB.prototype._framebufferUpdate@http://localhost:6080/core/rfb.js:1257:23
RFB.prototype._normal_msg@http://localhost:6080/core/rfb.js:1163:31
RFB.prototype._handle_message@http://localhost:6080/core/rfb.js:551:25
Websock.prototype._recv_message@http://localhost:6080/core/websock.js:386:21
```

**Comment by samhed** [comment]
@kanaka @DirectXMan12 any objections on removing the true color option altogether?

**Comment by kanaka** [comment]
I have no objections. However, I asked for noVNC twitter followers to weigh in if they currently use or need it: https://twitter.com/noVNC/status/793507828598136832

I would wait a couple weeks and if no one has weighed in by then, it's probably safe to remove it.

**Comment by samhed** [comment]
@kanaka sounds good!

**Comment by CendioOssman** [comment]
Waited long enough. Removed in 26586b9ddf3f5aa3c96c0f1090cb2134966a055f. :)
