### ISSUE TITLE
bad performance with mac native vnc server

### ISSUE THREAD

**Issue by AngelKyriako** [novnc/noVNC#673]
Anyone has tried noVNC to view mac's native vnc server with websockify ?
https://www.dssw.co.uk/blog/2007-05-14-a-vnc-server-is-included-in-mac-os-x-104/

My noVNC client was very very slow. With 1 frame rendering every few seconds.

Setup:
server: mac native vnc server, websockify & ngrok
client: noVNC

**Comment by samhed** [comment]
Do you get better performance using any other VNC client?

**Comment by AngelKyriako** [comment]
@samhed I tried with a tigerVNC viewer from a linux machine and it was playing fine.

What should I check, in order to better understand what might be the issue ?

**Comment by samhed** [comment]
You could check if the server is sending updates slowly perhaps. Perhaps it would be easiest to modify the code in core/rfb.js in framebufferUpdate.

This is based on old code, but something like this maybe:

    Index: noVNC/include/rfb.js
    ===================================================================
    --- noVNC/include/rfb.js        (revision 31595)
    +++ noVNC/include/rfb.js        (working copy)
    @@ -77,6 +77,9 @@
             this._supportsContinuousUpdates = false;
             this._enabledContinuousUpdates = false;
     
    +        this._fps_updateCounter = 0;
    +        this._fps_oldTime = 0;
    +
             // Frame buffer update state
             this._FBU = {
                 rects: 0,
    
    @@ -1165,6 +1168,24 @@
             },
     
             _framebufferUpdate: function () {
    +
    +            if (Util.get_logging() == 'debug') {
    +                this._fps_updateCounter++;
    +                var frames = 20;
    +                if (this._fps_updateCounter >= frames) {
    +                    this._fps_updateCounter = 0;
    +
    +                    var d = new Date();
    +                    var newTime = d.getTime(); // returns number of milliseconds since 1970/01/01
    +
    +                    if (this._fps_oldTime != 0) {
    +                        var diffInSeconds  = (newTime - this._fps_oldTime) / 1000;
    +                        Util.Error("fps: " + frames/diffInSeconds);
    +                    }
    +                    this._fps_oldTime = newTime;
    +                }
    +            }
    +
                 var ret = true;
                 var now;

**Comment by samhed** [comment]
You could also try if there is any difference if you try to go back a few commits before we implemented Continuous Updates. While I find it unlikely that this is the cause of the problems you are seeing, I would appreciate if you can try to make sure.

**Comment by AngelKyriako** [comment]
It is not a new bug. Its been there for at least 3 months. I just did not bother at the time since it was not needed that much.

I will try and see if I can get out of the above samples.

thanx

**Comment by DirectXMan12** [comment]
If you can take a recording, that would also be useful, because we could then debug on any platform.

**Comment by samhed** [comment]
@AngelKyriako do you think you are able to take a recording of this?

**Comment by AngelKyriako** [comment]
@samhed I have a mac recording ready. However, our setup started lagging recently on a windows machine as well. Therefore, I will be examining some other aspects of it.

I will close the issue or upload recordings to let you know

**Comment by samhed** [comment]
Ok, thank you for the update

**Comment by patrakov** [comment]
I believe this has to do with the fact that the native MAC VNC server supports only ZLIB, ZRLE, RAW, and proprietary encodings. Not even Hextile. TigerVNC, unlike noVNC, supports ZLIB and ZRLE and thus works fine. NoVNC has to fall back to RAW until somebody implements ZLIB or ZRLE.
