### ISSUE TITLE
We should publish on NPM

### ISSUE THREAD

**Issue by DirectXMan12** [novnc/noVNC#675]
As a follow-up to #496, we should set up Travis to automatically publish to NPM on a successful tagged version.

**Comment by julien-f** [comment]
Any news on this?

**Comment by nraynaud** [comment]
Hello y'all, 
as a temporary measure, I have published a scoped version of the package on NPM.
It's here: https://www.npmjs.com/package/@nraynaud/novnc

here is an example:
```javascript
import RFB from '@nraynaud/novnc/lib/rfb'
...
    const rfb = new RFB({
      encrypt: isSecure,
      target: this.refs.canvas,
      wsProtocols: [ 'binary' ],
      onClipboard: onClipboardChange && ((_, text) => {
        onClipboardChange(text)
      }),
      onUpdateState: this._onUpdateState
    })
    rfb.connect(url.hostname, url.port, null, path)
```

**Comment by aftabnaveed** [comment]
For beginner like me it is very hard to use configure and use noVNC with existing projects. I recently started working on ReactJS/webpack project and all my modules are based on NPM. 
It is kind of hard for me to follow the integration instructions. My question is, is there a way to easily integrate noVNC into my existing project without using the browser-es-module-loader ?

**Comment by lanwen** [comment]
As a workaround direct link to repo can be used:

`yarn add https://github.com/novnc/noVNC.git#master`

**Comment by martinpitt** [comment]
Seems this became slightly more urgent, now that bower calls itself deprecated:
```
npm WARN deprecated bower@1.7.9: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us figure out one.
```
In cockpit we are [moving away from bower to npm+webpack](https://github.com/cockpit-project/cockpit/pull/6814), but for the time being we will use `"noVNC": "https://github.com/novnc/noVNC/archive/v0.6.2.tar.gz"` in `packages.json`. But that makes it much harder to stay on the current noVNC version.

Thanks for considering!
