### ISSUE TITLE
Question: QWERTZ layout on qemu startet with -k 'en_US' (Xenserver 6.x)

### ISSUE THREAD

**Issue by jtkoerting** [novnc/noVNC#680]
Hi,

Is it a known problem, that (xen/vnc) servers using qemu and startet with _-k 'en_US'_ does not recognize the QWERTZ layout of e.g. an german keyboard?
Could this be tweaked within noVNC or must we chance the qemu params in Xenserver (which is quite a pitty task...).

Thank you for your great software!
Jimmy

**Comment by DirectXMan12** [comment]
Hi,

There may be multiple issues at play.  First of all, we recently merged a patch that makes noVNC support the qemu RFB keyboard extension, *but* this also caused passing the `-k` option (which is not recommended by the qemu docs) to break in certain cases.  I'm not sure if Xen's qemu includes that extension, but if it does, that's probably your issue.  See #666.  If not passing the `-k` option fixes your issues, that's probably the problem.

**Comment by jtkoerting** [comment]
Hi,

many thanks for your response!
#666 (setting 'allowQEMUExtKeyEvent': false,) did not change the problem. Maybe I did not explained clear what the problem is. I have no errors or something else, just no translation of QWERTZ / QWERTY. I hoped that could be tweaked somewhere as disabling -k 'en_US' is no really option, if you don't want to mess with the Citrix XenServer. At lease the next patch from them might kill that.

**Comment by jtkoerting** [comment]
Update :)
I had the problems from #666, too - but only in chrome. That's why did not recognized it. In safari/firefox I had no problem. In chrome just NO input, but many messages when launching the console with debug mode enabled.

**Comment by samhed** [comment]
@jtkoerting does #766 help?

**Comment by CendioOssman** [comment]
#766 is merged so this is now fixed.
