### ISSUE TITLE
The future of vnc_auto.html

### ISSUE THREAD

**Issue by samhed** [novnc/noVNC#695]
The two example applications for noVNC are **vnc_auto.html** and **vnc.html**. Currently, the main differences between the two are:
- **vnc_auto.html** connects automatically
- **vnc_auto.html** is a minimal solution using very little code in comparison
- **vnc.html** has more features such as a settings UI and session controls
- **vnc.html** has several touch device support features

Recently the interface for **vnc.html** was updated to look better, use modern css features and to not take up any screen real estate. Personally I feel that **vnc_auto.html** is outdated and should either be retired or given some love.

**Comment by DirectXMan12** [comment]
Just to repeat here what I mentioned in #691: vnc_auto.html is used by OpenStack, so we need to work with them to figure out a replacement if we remove it.

**Comment by kosmasgiannis** [comment]
Hi there, 

I use a tweaked version of vnc_auto.html in my projects.  The auto-connection feature is of course the main reason that I use it but the fact that it is stripped from various UI parts that are not needed in my project is another one. I believe it is very useful and should not be retired.

I think the ideal solution would be to automate the generation of the startup html page. A script could incorporate specific features to the page based on user defined arguments. The default behaviour could result to the generation of vnc.html.

**Comment by devicenull** [comment]
FWIW, we also use vnc_auto.html to automatically connect customers to their VNC consoles.  If this were to go away, I'd like to see easy options in vnc.html to:

* Completely disable any possible connection/settings UI (if we leave these visible, we have customers changing options and either breaking their connectivity, or getting confused why features don't work)
* Automatically connect based on hardcoded information.

Our goal is really: Customers click '<VIEW CONSOLE>', and are presented with a noVNC connection to their console.  They don't have to do anything special, and they aren't presented with options that can confuse them.

**Comment by shadeslayer** [comment]
We also use vnc_auto.html like @devicenull described and would hate to see it being dropped entirely.

**Comment by shreyasvinaya** [comment]
There is a need for auto login.  Please upgrade and retain it.

**Comment by CleoQc** [comment]
another vote for vnc_auto.html please

**Comment by samhed** [comment]
> There is a need for auto login.

This is not something that is exclusive to vnc_auto.html fyi

**Comment by CendioOssman** [comment]
Yeah, the naming is part of the problem. `vnc_auto.html` should really be `vnc_lite.html` or something like that if we keep it.

**Comment by kanaka** [comment]
@CendioOssman yes, that's my fault. My intention was always for vnc_auto.html to demonstrate a fairly minimal integration of noVNC. The name has always been wrong and I just happened to pick one of it's main distinctive features without considering that the same feature makes perfect sense in vnc.html (and it wasn't that long before it got that functionality too). I'm fine with renaming it to better reflect the purpose. Might be good to do that at a major version increment though to minimize surprise breakage since it's been the name for so long.

**Comment by CendioOssman** [comment]
The next release seems to be planned to be 0.7.0 rather than 0.6.3. Can we do the name change there, even if we postpone deciding on the long term plan?

(Mildly related, are there any criteria for 1.0? I can't see anything obvious that's missing.)

**Comment by samhed** [comment]
Renaming vnc_auto.html to vnc_lite.html in the upcoming release sounds good to me.

**Comment by mkunz7** [comment]
https://github.com/novnc/noVNC/pull/780
Partially related.

**Comment by samhed** [comment]
Renamed vnc_auto.html to vnc_lite.html in 83391ffc38d91f6ceb5da6cf764a5411dc431543

**Comment by samhed** [comment]
So the plan for vnc_lite.html in the short term is to keep it, but to keep it light. I might strip it down a bit more or at least simplify the code. Thanks for your responses people.
