### ISSUE TITLE
Passwordless authentication doesn't work

### ISSUE THREAD

**Issue by samfrances** [novnc/noVNC#731]
I'm trying to use a noVNC to connect to a VNC server with password authentication switched off. My plan to to rely on other means to prevent unauthorised access. However, NoVNC won't accept an attempt to access a passwordless VNC server. The attempt to connect just hangs. Any help much appreciated.

**Comment by samhed** [comment]
It works for me. Which VNC server are you using? Are you using the latest master? Are you getting any errors in the JavaScript console?

**Comment by samfrances** [comment]
Hi @samhed . I'm using tightVNC on windows as my server. I will post again with any javascript errors.

**Comment by Vocalonation** [comment]
Hello, I'm in the same situation.

I'm trying to use noVNC to connect to a tightVNC server with no authentication. I get a javascript error and noVNC cannot start.

If I set any password, noVNC works without a hitch.

This is the javascript error that is thrown by Chrome when I try to connect to a TightVNC server without authentication enabled.

recv_message, caught exception: 
    name: TypeError
    message: this._updateState is not a function
TypeError: this._updateState is not a function
    at RFB._negotiate_tight_auth (http://hiei/page/vnc/noVNC/core/rfb.js:854:22)
    at RFB._negotiate_authentication (http://hiei/page/vnc/noVNC/core/rfb.js:916:33)
    at RFB._init_msg (http://hiei/page/vnc/noVNC/core/rfb.js:1077:33)
    at RFB._handle_message (http://hiei/page/vnc/noVNC/core/rfb.js:591:26)
    at Websock._recv_message (http://hiei/page/vnc/noVNC/core/websock.js:386:41)
Util.Error @ util.js:44
_recv_message @ websock.js:413

**Comment by samhed** [comment]
Judging from the error message, it looks like you are using a broken version of noVNC. Just as the error says, there is no function called _updateState anymore.

**Comment by DirectXMan12** [comment]
Can you please indicate the SHA of the commit that you're using?

**Comment by samhed** [comment]
closing due to no response
