### ISSUE TITLE
ie11 and edge no enter/backspace

### ISSUE THREAD

**Issue by flumm** [novnc/noVNC#734]
with current master, when pressing enter or backspace (possibly other keys too) nothing happens
with debug level on i can see on the console

onKeyPress down, keysym: 16777226(16777226)
onKeyPress up, keysym: 16777226(16777226)

on /tests/input.html i get

raw key event keydown (key: 13, char 0, which: 13)
RFB keypress up keysym: [object Object] key name: [object Object]

what can be wrong here?

**Comment by flumm** [comment]
i found, that ie11 and edge send "\n" as char in the keyboardevent
which gets parsed as unicode and the keysym 0x100000a gets sent, but the enter gets not recognized

**Comment by samhed** [comment]
I can somewhat reproduce your problem. When running xev in a session and pressing backspace or enter I get the same wierd 0x100000a keysyms. However, both keys work as expected when actually using them for typing etc.

**Comment by CendioOssman** [comment]
A lot of applications will expect the proper keysym though.

**Comment by flumm** [comment]
> I can somewhat reproduce your problem. When running xev in a session and pressing backspace or enter I get the same wierd 0x100000a keysyms. However, both keys work as expected when actually using them for typing etc.

what kind of vnc server do you use? i use the qemu builtin one, which does not work (qemu 2.7)

**Comment by samhed** [comment]
I used TigerVNC

**Comment by samhed** [comment]
This is a regression from commit 115eedf69c465548a44eab1b2a6492546b2ed6e1

**Comment by zoon01** [comment]
With latest release the problem still exist.
No Enter or Backspace keys working.

Windows 10 with IE11 connecting a freebsd 11 VM with virtualbox and LibVNCServer-0.9.9
The browser chrome does work correctly.

**Comment by CendioOssman** [comment]
> This is a regression from commit 115eedf

I reverted it and the problem still remains (albeit slightly different), so it's not that.

IE/Edge is setting `char` for its `keydown` events which is confusing our code. Will need to have a deeper look.

**Comment by flumm** [comment]
are you sure?

in my local branch i reverted that commit, and it works fine since...

**Comment by CendioOssman** [comment]
Perhaps not. I think I only got a revert on one of the files. Will have to look at it next week.

**Comment by zoon01** [comment]
Where are we standing now? Is the problem already fixed in master?

**Comment by samhed** [comment]
@zoon01 not fixed in master, but #766 fixes this at least for me.

**Comment by CendioOssman** [comment]
#766 is merged so this is now fixed.
