### ISSUE TITLE
Requests highest compression needlessly

### ISSUE THREAD

**Issue by patrakov** [novnc/noVNC#737]
By default, noVNC presents pseudo-encoding 0xffffff09 in its list of preferred encodings. This encoding corresponds to the highest compression level (9). However, libvncserver also interprets this compression level in its Tight encoder, and has an interesting comment:

https://github.com/LibVNC/libvncserver/blob/9c7efb7633ba62cd80c93e83284663f805bb3031/libvncserver/tight.c#L331

    /* CL 9 (which maps internally to CL 3) is included mainly for backward
       compatibility with TightVNC Compression Levels 5-9.  It should be used
       only in extremely low-bandwidth cases in which it can be shown to have a
       benefit.  For low-color workloads, it provides typically only 10-20%
       better compression than CL 2 with JPEG and CL 1 without JPEG, and it
       uses, on average, twice as much CPU time. */

See also the top of the file.

Besides the bad consequences for the CPU usage, it also hints libvncserver to use JPEG compression more often and thus sometimes blurs text. Red text in terminals on Ubuntu MATE 16.04 (with Vino) is affected. The screenshot below is with medium JPEG quality, but the same kind of blur is also reproducible with high JPEG quality, so it's best to avoid triggering this bug.

![image](https://cloud.githubusercontent.com/assets/2943163/21530771/edcded82-cd64-11e6-9082-d97d543c311c.png)

I suggest defaulting to ['compress_custom', -254 ] which is the highest compression level that doesn't lead to this kind of artifact.

**Comment by kanaka** [comment]
Interesting, I hadn't seen information about that before. Sounds like a reasonable change. @patrakov Can you submit a simple pull request so that you get credit for the change/suggestion (if the rest of the team approves).

**Comment by patrakov** [comment]
Yes - tomorrow. I should not submit pull requests after 1AM :)

**Comment by kanaka** [comment]
@patrakov no hurry. How's the weather in Yekaterinburg? :-)

**Comment by patrakov** [comment]
The weather is fine.

Further testing revealed that the blurry bug specifically affects Vino 3.8.1, which is still shipped by Ubuntu as the last version without hard dependency on the rest of GNOME. There is no blur when testing against x11vnc. Still, the "comment in libvncserver" rationale applies.

**Comment by samhed** [comment]
Fixed in #738

**Comment by hongweipeng** [comment]
@patrakov hi brother, where can set jpeg compression level? I want to use the `JPEG_quality_lo` .
