### ISSUE TITLE
AMX Touch Panel VNC Support

### ISSUE THREAD

**Issue by snorkeyg** [novnc/noVNC#74]
Currently NoVNC does not seem to work when attempting to VNC AMX Touch Panels (http://www.amx.com/).

Some other VNC programs list AMX Touch Panel VNC as a feature. I'm wondering if support for this could be added to NoVNC.

Currently NoVnc connects but, the screen never actually loads and the screen display area appears grey. Mouse clicks do appear to work. There are no error's reported that I can find.

Happy to help and test where possible.

Cheers
Chris

**Comment by nicoske** [comment]
I'm trying to connect to AMX panels and I have a different problem. It seems indeed they are not using standard VNC implementation but I'm able to connect with different VNC clients, so I assume noVNC could do the job :-)

In fact the connection works fine but nothing is displayed. It works fine by using a standard tightvnc server. Here's the debug log:

>> RFB.constructor
util.js:214 >> Display.constructor
util.js:214 User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
util.js:214 Browser: webkit 537.36
util.js:214 Setting viewport to full display region
util.js:216 Data URI scheme cursor supported
util.js:214 << Display.constructor
util.js:216 Using native WebSockets
util.js:214 >> Keyboard.allKeysUp
util.js:214 << Keyboard.allKeysUp
util.js:214 Setting viewport to full display region
util.js:218  Msg: noVNC ready: native WebSockets, canvas rendering
util.js:214 << RFB.constructor
util.js:214 >> Keyboard.allKeysUp
util.js:214 << Keyboard.allKeysUp
util.js:218 
util.js:214 >> RFB.connect
util.js:216 connecting to ws://s-scic-stats:9999/?token=S3
util.js:216 Detected binaryType support in WebSockets
util.js:214 << RFB.connect
websock.js:248 WebSocket connection to 'ws://./' failed: Error in connection establishment: net::ERR_TUNNEL_CONNECTION_FAILED
util.js:214 >> WebSock.onopen
util.js:216 Server choose sub-protocol: binary
util.js:218  Msg: Starting VNC handshake
util.js:214 << WebSock.onopen
util.js:216 Server ProtocolVersion: 003.003
util.js:218  Msg: Sent ProtocolVersion: 003.003
util.js:218  Msg: Authenticating using scheme: 1
util.js:218  Msg: No auth required
util.js:218  Msg: Authentication OK
util.js:216 Screen: 1920x530, bpp: 16, depth: 16, big_endian: 1, true_color: 1, red_max: 31, green_max: 63, blue_max: 31, red_shift: 11, green_shift: 5, blue_shift: 0
util.js:218 Server native endian is not little endian
util.js:218 Server native red-shift is not 16
util.js:214 Setting viewport to full display region
util.js:218  Msg: Connected (unencrypted) to: 
util.js:214 >> Keyboard.allKeysUp
util.js:214 << Keyboard.allKeysUp
util.js:214 >> Keyboard.allKeysUp
util.js:214 << Keyboard.allKeysUp

**Comment by nicoske** [comment]
Hi,

Tested with noVNC-1.0.0 and still have the same issue. I would love to be able to connect to AMX TPs.
Here's the debug log:

`connecting to ws://xxxxx:5900/websockify
websock.js:217 Server choose sub-protocol: binary
rfb.js:818 Server ProtocolVersion: 003.003
rfb.js:1196 Screen: 1280x800, bpp: 16, depth: 16, big_endian: 1, true_color: 1, red_max: 31, green_max: 63, blue_max: 31, red_shift: 11, green_shift: 5, blue_shift: 0
rfb.js:1208 Server native endian is not little endian
_negotiate_server_init @ rfb.js:1208
_init_msg @ rfb.js:1313
_handle_message @ rfb.js:734
_recv_message @ websock.js:304
rfb.js:1212 Server native red-shift is not 16
_negotiate_server_init @ rfb.js:1212
_init_msg @ rfb.js:1313
_handle_message @ rfb.js:734
_recv_message @ websock.js:304
browser.js:32 Data URI scheme cursor supported`

Connection is working but screens stays grey. Clicks are working.

**Comment by CendioOssman** [comment]
I'm afraid we've dropped support for this particular kind of broken VNC servers. :/

**Comment by edwinvuw** [comment]
I'm happy to report that the newer AMX control panels appear to implement RFB 3.8, and they use a standard implementation (i.e. according to RFB spec).  NoVNC works fine with these newer AMX control panels.

It's only the older ones that are incompatible with NoVNC.  Those ones claim to implement RFB 3.3 and appear to do so in a non-standard way (as per previous comments).

Hopefully this comment helps others who have encountered this issue.
