### ISSUE TITLE
Windows 7 + VMware SVGA II driver.  black box where cursor should be

### ISSUE THREAD

**Issue by vans163** [novnc/noVNC#740]
Using vncviewer for linux we have no issues.

Using novnc we can see a black box drawn around where the cursor should be.

If we do not install the VMWare SVGA II driver, novnc works, there is no black box.

The guest is a qemu windows vm (with a vmware vga adapter), using qemu's VNC option with websocket -> tcp proxy.

Using vnc_auto.html 0.6.0.

<img src="http://i.imgur.com/0NkUZeL.png" width="600" height="480" />

**Comment by DirectXMan12** [comment]
first off, it looks like you're using `vnc_auto.html`.  Does the same thing happen with `vnc.html`?  Secondly, which version of noVNC are you using (if using from master, please include the commit sha).  Finally, which version of Chromium are you using?

If I had to guess, it's a bug in the local cursor code.  If it happens with `vnc.html` as well as `vnc_auto.html`, a recording (`websockify --record`) would be useful in debugging the issue (this allows us to "play back" the exact VNC traffic that got sent to your copy of noVNC, but does so locally).

**Comment by DirectXMan12** [comment]
cc #695

**Comment by vans163** [comment]
@DirectXMan12 Got some more info on this. I tried 0.6.2 and I noticed that the black cursor starts as soon as the windows starts booting (loading screen visible). 

Here is the recording https://gist.githubusercontent.com/anonymous/d96234852b9618926ad62837dd51c639/raw/4a81e357f1c742c2f4564e1e5a43ed283901ce4c/vmware-0.6.2-cap

**Comment by vans163** [comment]
This seems a similar issue https://sourceforge.net/p/vnc-tight/bugs/996/.

The problem is the cursor is reporting itself as 41x39 for some odd reason when the maximum cursor size on windows is 32x32, and likewise the maximum cursor size you can set in the browser is 32x32.  Im not really sure what we can do here other ignore the cursor update? (if it this indeed this case)

**Comment by CendioOssman** [comment]
I just tried a 64x64 cursor here which worked perfectly. I tried Firefox and Chrome on both Linux and Windows. So I think the issue you're seeing is some qemu bug rather than a noVNC issue.

**Comment by vans163** [comment]
@CendioOssman If it was a QEMU bug then the same thing would happen in vncviewer. From all the vnc clients I tried, it only happens in noVNC.  Im pretty sure its something QEMU is sending in the protocol when the adapter is vmvga.

**Comment by CendioOssman** [comment]
Could you test the current development version of noVNC? And also please test `vnc.html` rather than `vnc_auto.html`.

**Comment by vans163** [comment]
@CendioOssman Issue is fixed for me using vnc_auto.html.

**Comment by CendioOssman** [comment]
Again, please test the development version of `vnc.html`.

**Comment by vans163** [comment]
@CendioOssman Yea I tried both. I edited my reply because at first it worked for both, then after some reboots the issue cropped up again.  I think the VM SVGA driver initialized itself or something after the 2nd reboot.

So current status is for both vnc.html and vnc_auto.html its the same issue. 

The only difference I noticed is maybe, just maybe, it takes longer for the clientside black box over the cursor to appear. Longer meaning it happens once we have booted and spent a minute, vs before it would happen while booting windows.

**Comment by DirectXMan12** [comment]
So, I was looking over the recording a bit, and AFAICT, at least initially, we get sent a square, black cursor (looking at the underlying protocol data).  Due to some time constraints, I was only able to take a cursory glance (no pun intended), but I'll take a closer look later to make sure I'm not missing something.  Perhaps the other viewers aren't sending the local-cursor encoding or something?

**Comment by vans163** [comment]
@DirectXMan12 Im taking a peek at this now, im noticing this:

core/display.js line 529: changeCursor: function (pixels, mask, hotx, hoty, w, h) {

Here we get a a 4096 sized array of 0's, mask filled with 0's too.  When we got to draw the cursor using line 869 display.js, we do var url = 'data:image/x-icon;base64,' + Base64.encode(cur);.

the x-icon seems to a ICO file and wikipedia has outlined instructions how to handle transparency.  A 0 for the 32bit pixel value means fully transparent pixel, not absence of color (black).

Also if noVNC is receiving a size of 32x32 for the windows cursor that is a bug in QEMU then or a limitation of the VNC protocol. The default windows cursor is 41x39 pixels in size (does not conform to 32x32 cursor size requirement).

**Comment by CendioOssman** [comment]
> the x-icon seems to be an ICO file and wikipedia has outlined instructions how to handle transparency. A 0 for the 32bit pixel value means fully transparent pixel, not a black pixel.
> 

Right. So definitely a bug somewhere. I'll have a look.

> Also if noVNC is receiving a size of 32x32 for the windows cursor that is a bug in QEMU then or a limitation of the VNC protocol. The default windows cursor is 41x39 pixels in size (does not conform to 32x32 cursor size requirement).

That's a QEMU limitation in that case. VNC can support dimensions of up to 65535x65535.

**Comment by CendioOssman** [comment]
So I dug around and it seems the browsers just have sucky support for the Windows cursor format. They don't seem to support proper alpha, but rather applies heuristics to see if someone hid alpha data in the unused bits. And in this case they are also zero, so the browsers assume there is no alpha...

I think we need to look at using PNG instead for cursors.

**Comment by vans163** [comment]
@CendioOssman I see. Temporary solution in this case is to just disable local cursor I assume?

Also is there a way to confirm on the wire what size of the cursor is sent, the cap I posted above im not sure how to interpret or what line the cursor would be. I want to also file a bug with QEMU here.

**Comment by CendioOssman** [comment]
Please give #782 a try and see if it solves the issue for you. Seems to do so here.

**Comment by CendioOssman** [comment]
> Also is there a way to confirm on the wire what size of the cursor is sent, the cap I posted above im not sure how to interpret or what line the cursor w/h would be. I want to also file a bug with QEMU in relation to the w/h being sent incorrectly thus truncating the white windows pointer.

You can debug the Javascript code and inspect the buffers. In this case it is sending a fully transparent 32x32 cursor. Presumably to get rid of any client side cursor as it is rendering the cursor directly on the server.

**Comment by vans163** [comment]
@CendioOssman #782 fixes it for me.  I get a transparent cursor.  But it seems there appeared a performance regression on master or its my system.  When I click/drag often the click does not register / is ignored.  It feels like something is off.
