### ISSUE TITLE
The future of the `token` setting

### ISSUE THREAD

**Issue by DirectXMan12** [novnc/noVNC#742]
continued from #715 

PR #715 removed the token setting.  It's more-or-less a websockify specific parameter, but it makes things easier for websockify users.

We may just want to continue having it as a URL-only parameter that doesn't get persisted, etc via the normal setting-handling code.

cc @CendioOssman @samhed @kanaka

**Comment by samhed** [comment]
I think it's fine as is, and we haven't had much input from people. Close?

**Comment by DirectXMan12** [comment]
yeah, that's probably fine.  We just need to note it in the release docs.
