### ISSUE TITLE
noVNC RFB protocol error with Chromebooks/Android devices

### ISSUE THREAD

**Issue by markknit** [novnc/noVNC#745]
I'm using noVNC on Ubuntu to connect to desktop sessions from Windows desktop, Android, and Chromebooks. All have managed to connect with no problem. However, I just tested a batch of new Chromebooks which all fail to connect. I checked the server log and am seeing the following error with each connection attempt: 'RFB protocol error: reading version failed: not an RFB server?'. This only occurs with the new Chromebooks (the older ones still connect), and some Android devices using Chrome.  THe windows desktops all connect with the latest versions of Firefox, Chrome, and Edge. I also checked the client side log and can see the connection attempt, using RFB protocol 3.8. It appears that the server is terminating the session. 

Does anyone have any idea what the issue is with the newer Chromeboks and Android devices?

**Comment by samhed** [comment]
What VNC servers are you using on the problematic devices?

**Comment by markknit** [comment]
x11vnc.

**Comment by samhed** [comment]
Eh, I didn't know there where x11vnc servers available as Chrome plugins and Android applications. Could you give me links?

A first step for me would be to try to reproduce your issue.

**Comment by markknit** [comment]
Sorry, I meant on Ubuntu. I have x11vnc on Ubuntu, and trying to connect from Chromebooks and Android devices to the Ubuntu server via noVNC using x11VNC. As I said, that configuration works fine from older Chromebooks, windows devices, etc. - just not the newer Chromebooks & Android devices.

**Comment by samhed** [comment]
Okay! Yes, that changes things :) I haven't heard about this issue before.

Which version of x11vnc are you running on your Ubuntu machine?

Is there any difference in how you connect from the newer Chromebooks & Android devices compared to how you connect from your older devices? Could you check the chrome versions running on the respective Chromebook devices? Which browser are you using on Android?

**Comment by shreyasvinaya** [comment]
On Android [Chrome Browser] On screen keyboard does not show up.

**Comment by samhed** [comment]
@shreyasvinaya it does for me. Are you clicking the keyboard button in the noVNC toolbar?

**Comment by shreyasvinaya** [comment]
@samhed - May be I am missing something. Where is the keyboard button? Please help.

**Comment by samhed** [comment]
![androidphone](https://cloud.githubusercontent.com/assets/4117162/21975271/fd91fbbc-dbcb-11e6-86d9-28a71520c04a.png)
The third button from the top there.. ?

**Comment by samhed** [comment]
@shreyasvinaya I could also add that vnc_auto.html doesn't have any support for touch interfaces at all. For more advanced interface features like these, you will obviously have to use vnc.html

**Comment by samhed** [comment]
closing due to no response
