### ISSUE TITLE
Dual Connections

### ISSUE THREAD

**Issue by shreyasvinaya** [novnc/noVNC#750]
Scenario: I have a Linux Remote System (Ubuntu) to which the following need to connect simultaneously
a. Student: Who will have access to modify the screen/session
b. Teacher: Who will have "view-only" access to the screen/session to view/observe (but not modify) what the Student is doing.

How should that be setup?

**Comment by ebuildy** [comment]
Hello,

you can use ``view_only`` parameter , or custom a bit ``vnc_auto.html`` to mach your needs, I thing this is only client-side security, but this could to the trick.

**Comment by shreyasvinaya** [comment]
@samhed - I know how to use view_only. The question is how to use both normal and view_only together. 
Say in chrome I use normal - I should be able to interact
Simultaneously, in firefox if I use view_only, I should see the interactions from the chrome window

When I use normal, the view_only connection does not show anything (blank screen)
Please help

**Comment by samhed** [comment]
So your VNC server is replacing your first connection when you are connecting again? This isn't related to noVNC.

PS: Have a look at ThinLinc and shadowing: 

https://www.cendio.com/resources/docs/tag-devel/html/shadowing.html
