### ISSUE TITLE
Server Setup Help Needed

### ISSUE THREAD

**Issue by shreyasvinaya** [novnc/noVNC#751]
On a headless Ubuntu 16.04 running on Amazon AWS or Digitalocean -->
How do I setup the x11vnc server (and any other dependencies) so that it is compatible with the launch script ./utils/launch.sh --vnc localhost:5901

**Comment by ebuildy** [comment]
Hello, you can search for existing issues, they are plenty of similar issues, such as:

https://github.com/novnc/noVNC/issues/535

**Comment by samhed** [comment]
Yes, let's try to keep it in one place
