### ISSUE TITLE
Releases dont contain release but code source 

### ISSUE THREAD

**Issue by ebuildy** [novnc/noVNC#752]
[suggestion]

In master branch, there is ``/app`` folder, but not in tags.

Could be very useful to have it also on release packages, to have noVNC working straight away w/o need to build it.

Hence noVNC could be included in continuous integration workflow easily, for instance with Docker:

```
RUN mkdir /opt/novnc && \
    curl -L https://github.com/novnc/noVNC/archive/v0.6.2.tar.gz \
        | tar -xz --strip-components=1 -C /opt/novnc
```

**Comment by CendioOssman** [comment]
There has been no change on this front. The releases as well as master both support running as-is. We've simply reorganised things in to multiple folders since the last release, hence why the `app` folder wasn't present before.
