### ISSUE TITLE
SSL + tomcat HTTPS question

### ISSUE THREAD

**Issue by josh1707** [novnc/noVNC#754]
Hi,
I deployed my application in server A using tomcat with https. The keystore is app.keystore.

The noVNC html is in server A.

The noVNC server is in server B and run with : 
"./websockify.py --cert=/opt/https/app.cer --key=/opt/https/app.key --target-config=/vms 29789"

/opt/https/app.cer  and /opt/https/app.key  is export from app.keystore.

I failed to connect to noVNC that in server B with wss from html in server A.
(It work fine when noVNC server is also in server A)

I got error in browser's console:

WebSocket connection to 'wss://192.168.17.102:29789/websockify/?token=i-59624075' failed: Error in connection establishment: net::ERR_INSECURE_RESPONSE

Msg: Server disconnected (code: 1006)

I got message in noVNC server:

WebSocket server settings:
  - Listen on :29789
  - Flash security policy server
  - SSL/TLS support
  - proxying from :29789 to targets generated by TokenFile
192.168.17.101: new handler Process
Reaping zombies, active child count is 0
Ignoring interrupted syscall

How should I config in this case ?

Thanks for helping my.

**Comment by josh1707** [comment]
It also work fine when not using SSL and HTTPS. Html is in server  A and noVNC server is in server B.

**Comment by CendioOssman** [comment]
You can't really do TLS sanely with IP-addresses. Server B should have a hostname thats used in the wss:// URL. That hostname should also be in the certificate.
