### ISSUE TITLE
code 400,message Bad request syntax

### ISSUE THREAD

**Issue by yyx12345678** [novnc/noVNC#757]
Sometimes this error occurs, causing the connection to fail. I can not fix it.

**Comment by yyx12345678** [comment]
1. Could not 
2. When I connect, there will be an error. like。。connecting to: 192.168.199.222:5900 192.168.199.222 - - [18/Jan/2017 16:49:23] code 400, message Bad request syntax ('\x88\x8f\xc3\x85\x95\xf7\xc0m\xc1\x96\xb1\xe2\xf0\x83\xe3\xe6\xf9\x98\xb0\xe0\xf1')
3.vnc4server

**Comment by samhed** [comment]
> Could not

Ok..? Can't help if you won't give enough information about your issue. Good luck
