### ISSUE TITLE
Dose it  or will it support openwrt?

### ISSUE THREAD

**Issue by wanglinjie168** [novnc/noVNC#759]
Dose it  or will it support openwrt?  How can i develop it on openwrt ?

**Comment by samhed** [comment]
I'm guessing that you are asking if websockify can run on OpenWrt? Haven't heard of anyone doing that, this is the first time I hear about OpenWrt at all. You should give it a try!

**Comment by wanglinjie168** [comment]
Thank you for replay . i've tryed it  , and succeeded . Maybe not perfect,but it worked. Now anthoer problem ,Does it support rdp?
