### ISSUE TITLE
autoscale

### ISSUE THREAD

**Issue by shreyasvinaya** [novnc/noVNC#763]
Has the autoscale=1 option changed in the latest version?
Is there a different query parameter now?

**Comment by samhed** [comment]
I can't remember an autoscale parameter, must be quite old. Which version of noVNC has this?

**Comment by shreyasvinaya** [comment]
Version 0.5.1 has autoscale option
It was used with vnc_auto.html?autoconnect=1&autoscale=1&quality=3

1. What is the equivalent option for "autoscale" now?
In autoscale the whole window was being used. 
None of "Local Scaling", "Local Down Scaling" and "Remote Resizing" do what the autoscale was doing.

2. Can the options be set using the url instead of the noVNC controls?

**Comment by samhed** [comment]
I have no idea what autoscale was, what was it doing?

    git checkout v0.5.1
    git grep autoscale

gives no hits..

Yes options can be set using the url.

**Comment by samhed** [comment]
I just grepped the entire git history, and there has never existed an option called 'autoscale'.

**Comment by CendioOssman** [comment]
So close?

**Comment by 0xC4N1** [comment]
it is vnc.html?resize=<scale | downscale | remote>
it doesn't seem to work with vnc_auto but you can append &autoconnect=1 to vnc.html.

**Comment by samhed** [comment]
Yes, vnc_auto miss a lot of functionality found in vnc.html
