### ISSUE TITLE
Use of tab key to switch between text inputs in a web browser

### ISSUE THREAD

**Issue by joemarct** [novnc/noVNC#765]
I am running Chrome in a remote server. I am connecting to it using noVNC to a tightvncserver. The tab key, which is normally used for switching to the next text input in my local browser, does not work in VNC. Is this a known limitation of noVNC+tightvncserver? Or is there any keyboard mapping (using xmodmap or anything like that) that I need to do for this to work?

**Comment by samhed** [comment]
This should work.

What local platform and browser are you using? If you run xev in a terminal on your remote server while connected via noVNC, press TAB, what do you get?

Works fine for me with TigerVNC server, perhaps you could changing VNC server and see if it changes things?

**Comment by joemarct** [comment]
Thanks for the reply @samhed. I am using Safari on MacOS Sierra. It's the same behavior I observe in Firefox and Chrome in my machine.

Anyway, I ran xev as you suggested and attached to the display where tightvncserver is running. I got the following log in xev stdout:
![screen shot 2017-01-27 at 2 01 44 pm](https://cloud.githubusercontent.com/assets/907605/22361914/6c62f1c4-e499-11e6-9292-a05359bdaf75.png)

I will update this thread later when I try to replace tightvnc with tigervnc.

**Comment by ekuefler** [comment]
I encountered this same problem under tightvnc, with the same xev output as @joemarct. It looks like an issue with tightvnc; this blog post describes the fix: http://blog.zerosum42.com/2011/10/tech-fixing-tab-key-in-vnc.html. tigervnc also works without the same problem.

**Comment by samhed** [comment]
Good to hear! Thank you for the info @ekuefler
