### ISSUE TITLE
Win10 + touch screen + Chrome client. No mouse input

### ISSUE THREAD

**Issue by vans163** [novnc/noVNC#767]
With 0.6.2 on Chrome on Windows 10 with the Asus Transformer laptop (touch screen laptop) there is no mouse input, key input works. It is as if its started in partial view only mode.

There are no errors in js console.

I think this maybe related to the special touch screen driver this laptop has. Anyone faced similar issues?

Firefox on the same system + hardware works fine.

**Comment by samhed** [comment]
Fixed in 795719ec3d519d39b8f9ed7d0e352ff71144cc17

**Comment by vans163** [comment]
Seems I should switch to master :)

**Comment by samhed** [comment]
Yeah, we will make a new release as soon as a couple of issues are resolved.
