### ISSUE TITLE
Right-clicking on a zoomed screen sometimes shows browser context menu

### ISSUE THREAD

**Issue by patrakov** [novnc/noVNC#772]
To reproduce, please use Chromium Version 56.0.2924.87 (64-bit) on Linux, and also on Firefox 51.0.1 (64-bit), on a non-touch device. The settings below are obviously absurd, but reproduce the issue reliably. It triggers a lot on other devices that have non-default zoom combined with "Local Downscale" setting.

Set your screen resolution to 1920x1080. Get a VNC server that exposes a 1600x900 screen. Go to a noVNC installation pointed to that server, set the browser zoom to 200% (just to trigger the bug reliably), shift+reload.

Please set the Scaling Mode to "Local Downscale", apply, then connect.

At this point, the browser zoom level is expected to stay at 200%, and remote screen is expected to occupy the whole height of the browser window, with no scroll bar.

Now right-click somewhere in the remote screen, near the bottom. The right click will be handled both by the remote system and by the browser. There is no such bug if you right-click near the top of the VNC screen.

![image](https://cloud.githubusercontent.com/assets/2943163/22759558/b4f4f7cc-ee74-11e6-8f0c-875bb2222e13.png)

**Comment by CendioOssman** [comment]
Fallout from 47fbdced4530dd2a66a5f20be27b69d6c12a6ffc. Should be fixed in 6ffdfd3aa74ad0338df5a05be9383a22dde1198b.
