### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by CendioOssman** [novnc/noVNC#781]
We don't properly free everything as we should, so I can see memory usage going up with each connection made (haven't verified if there are leaks during connection as well, but it's possible).

Interpreting the profiler info from Chrome and Firefox is a bit of a black art, so it's not entirely obvious where the leaks are being caused. Some suspects though:

 - We retain a pointer to the RFB object in UI
 - The disconnect timer is somehow causing references to be held
 - WebSocket event handlers cause the Websock object to never be freed

**Comment by agronick** [comment]
I found that making an explicit delete call to the rfb object while removing the canvas was the only way to free up memory. Without this, I saw around 15mb in Chrome taken up by every connection that would not go away. Even when RFB went out of scope and the Canvas was removed the memory wasn't freed.

**Comment by DirectXMan12** [comment]
Neat, we should add this in or track down why that's the case.  Thanks!

**Comment by CendioOssman** [comment]
Seems to work fine now. All memory seems to be dropped as long as RFB gets a proper close signal and the reference to it is dropped. Tested with Firefox 57.

(Minor note: Firefox doesn't automatically do GC before displaying used memory, so it easy to be fooled in to thinking that noVNC is indeed leaking memory)
