### ISSUE TITLE
SetCapture polyfill interferes with firing events when interacting with the canvas element

### ISSUE THREAD

**Issue by mjrussell** [novnc/noVNC#784]
I just recently started playing with the most recent version after upgrading from 5.1 (was using the node-noVNC fork) and everything works great except for a slightly unexpected change in how events are fired when clicking on the canvas. I've got the VNC canvas embedded within a page that has several other input elements (dropdowns, buttons, etc) and so maintaining focus in the correct spots is important.

I've been doing this using `grab` and `ungrab` for the keyboard in combination with click and focus events. The addition of the polyfill for setCapture [here](https://github.com/novnc/noVNC/commit/86d15a492940013d766bc95dde43e23953395eaa#diff-3b58bd1e94608ca282c9bb883622cef9) seems to break my existing behavior. Specifically, the focus event no longer fires for the parent element of the canvas when clicking on the canvas, and whats more interesting (and what helped me find the bug) is that a click event is triggered not for the canvas but rather the `body` tag. I think this is because of where the set capture hidden div is located (in chrome). I've confirmed that removing this resolves my issue (reverting to the previous behavior).

So I'm sure there was a perfectly good reason for using the setCapture, here. I guess I'm wondering what options you think there are here to try and retain the existing behavior with respect to these events. Im wondering if creating the capture element as sibling of the canvas would produce better events. I plan on doing some more testing myself but thought I would create this issue in case you all had any thoughts.

cc @CendioOssman because you originally added setCapture

**Comment by mjrussell** [comment]
I should also mention that events fire properly for all other elements on the page, just the canvas event behavior appears different

**Comment by CendioOssman** [comment]
The canvas is not an element that can have focus, so I'm not sure why you were getting `focus` events to begin with. The `click` events are also a bit odd as they should be prevented by the keyboard code. Triggering on `mousedown` should be more robust. Does that work for you?

Moving the capture element is not generally feasible unfortunately as it might inherit properties that will prevent it from functioning.

**Comment by mjrussell** [comment]
I should have been more clear that the focus was being fired by the parent of the canvas, not the canvas itself. I'll try the `mousedown` and report back. Thanks!

**Comment by samhed** [comment]
closing due to no response
