### ISSUE TITLE
Using noVNC with socket enabled mobileVNC issues

### ISSUE THREAD

**Issue by ramotswa** [novnc/noVNC#785]
Hello - 
So I have installed mobilevnc and got it up and running on my target (windows) device. I checked out the latest code of noVNC and launched it using the launch.sh --vnc localhost:5900 which is on which the mobileVNC server is running.
When I run that command - firstly it obviously tries to download websockify, but as I'm using mobileVNC (as per your readme) do I still need that? 
It downloads it and tries to run it starts and prints out a URL for me. But then it crashes with:

```
C:\Users\...\repos\noVNC\utils\websockify\websockify\websocket.py:30: UserWarning: no 'numpy' module, HyBi protocol will be slower
  warnings.warn("no 'numpy' module, HyBi protocol will be slower")
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: C:\Users\...\repos\noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5900
WARNING: no 'resource' module, daemonizing is disabled
Traceback (most recent call last):
  File "C:/Users/.../repos/noVNC/utils/websockify/run", line 5, in <module>
    websockify.websocketproxy.websockify_init()
  File "C:\Users\...\repos\noVNC\utils\websockify\websockify\websocketproxy.py", line 535, in websockify_init
    server.start_server()
  File "C:\Users\...\repos\noVNC\utils\websockify\websockify\websockifyserver.py", line 687, in start_server
    signal.SIGCHLD: signal.getsignal(signal.SIGCHLD),
AttributeError: 'module' object has no attribute 'SIGCHLD'

Terminating WebSockets proxy (5344)
./launch.sh: line 51: kill: (5344) - No such process

```
Any ideas? Is there a good way of doing this? 

Thanks

Ramo

**Comment by CendioOssman** [comment]
> When I run that command - firstly it obviously tries to download websockify, but as I'm using mobileVNC (as per your readme) do I still need that?

The files for noVNC needs to be server from some web server. You don't need websockify if your VNC server has native WebSockets support, but you still need some form of web server. You will need to set that up manually in that case though.

> ```
> AttributeError: 'module' object has no attribute 'SIGCHLD'
> ```

I'm afraid websockify doesn't work on Windows. See noVNC/websockify#108. So I'm afraid you'll have to find a Linux machine to run websockify, or use another web server to serve the noVNC files. Perhaps mobileVNC has something builtin?
