### ISSUE TITLE
VMware shows background only

### ISSUE THREAD

**Issue by shubham436** [novnc/noVNC#787]
In VMware novnc just shows background of Ubuntu there is no menu bar or icons plz help what to do

**Comment by CendioOssman** [comment]
If you get a background then it sounds like noVNC is working fine and your problem is in the server somewhere. Does it work with other VNC clients?

**Comment by samhed** [comment]
Perhaps the remote session is larger than the browser window? In that case, you should have scrollbars unless you have enabled window clipping

**Comment by shubham436** [comment]
sir
can you make video on following:
1)vmware with novnc
2)novnc on windows

**Comment by samhed** [comment]
rofl

**Comment by shubham436** [comment]
rofl means

**Comment by shubham436** [comment]
which server  is best server for novnc

**Comment by CendioOssman** [comment]
noVNC has no recommended server and we do not have any such guides. You'll have to check the documentation for those respective servers on how to set things up.
