### ISSUE TITLE
How to set the session timeout?

### ISSUE THREAD

**Issue by RandoMath** [novnc/noVNC#788]
I use noVNC-0.5 first time and log in to the virtual machine .
However I can still operate it in the browser the next day.(seems no timeout settings)
How to set the timeout,say 60 minutes.
Thank you all~

**Comment by samhed** [comment]
Any reason you can't set this on your server instead?

**Comment by samhed** [comment]
closing due to no response

**Comment by T0T4R4** [comment]
That's not a reply @samhed , what do you mean ? 
Is that to be setup in the app or on let's say the reverse proxy webserver ?

**Comment by samhed** [comment]
A session timeout is usually configured in the VNC server.
