### ISSUE TITLE
dead keys in firefox and chromium

### ISSUE THREAD

**Issue by voobscout** [novnc/noVNC#791]
Guess it's more of a rant, then an issue, but:

None of the linux browsers would work correctly with novnc, some keys are dead in firefox, others are in chromium, this stupidity has me spin up redmond crap to get a remote console on my servers.

Both firefox and chromium redmond versions work quite fine, no dead keys.

I am experiencing this on vultr, trying to access server consoles. I have also seen this some other places novnc is used, every time this annoyance gets me in a bad mood.

Skimming the issues, it seems it's a reported and confirmed bug since '14
very frustrating

**Comment by samhed** [comment]
Yeah, it sucks :(

Not much we can do however, since this is caused by a flaw in the browsers itself.
