### ISSUE TITLE
TyoeError: callback is not a function

### ISSUE THREAD

**Issue by nasparlik** [novnc/noVNC#792]
When i try to connect i get this error.
![untitled](https://cloud.githubusercontent.com/assets/16765638/24096780/f5d6c888-0d5a-11e7-89f5-9b3cbfc6a135.png)

**Comment by CendioOssman** [comment]
That's part of websockify, so ideally this should be in that issue tracker rather than the noVNC one.

That said, that code has been removed. Please try with the current version of `websockify.js`. Hopefully that should just work.

**Comment by titulus** [comment]
@DirectXMan12 update the [npm package](https://www.npmjs.com/package/websockify) please. It still 0.7.1
