### ISSUE TITLE
How to listen websockeify in different ports, for different VNC ports?

### ISSUE THREAD

**Issue by voxsoftware** [novnc/noVNC#794]
How to listen websockeify in different ports, for different VNC ports?

Example: 
VNC 5901 --> websocket 6080
VNC 5902 --> websocket 6081
VNC 5903 --> websocket 6082

**Comment by DirectXMan12** [comment]
you can use one of the token plugins, or write your own (see https://github.com/novnc/websockify/blob/master/websockify/token_plugins.py and the `--token-plugin` option for websockify).

**Comment by voxsoftware** [comment]
Please add an example

**Comment by DirectXMan12** [comment]
there are some examples here: https://github.com/novnc/websockify/wiki/Token-based-target-selection
