### ISSUE TITLE
installation tutorial

### ISSUE THREAD

**Issue by boistordu** [novnc/noVNC#795]
Hi, 
it could be a good idea to do an installation tutorial end to end, because I have a lot of difficulties to not forget a step or two and I don't think I'm the only one in the same case.

**Comment by samhed** [comment]
There is no installation needed! Simply use the launch script

**Comment by boistordu** [comment]
not true since I can't connect for example and in console it tells me : 
`[22/Mar/2017 16:21:56] connecting to: localhost:5900
handler exception: [Errno 111] Connection refused`

So I'm sure there is different configurations steps to do. And if I run it with --vnc localhost:5901 it doesn't connect to anything at all.

**Comment by boistordu** [comment]
anyway okey i m going to debug it myself don't worry.

**Comment by samhed** [comment]
> [22/Mar/2017 16:21:56] connecting to: localhost:5900 handler exception: [Errno 111] Connection refused

Do you have a VNC server up and running on localhost port 5900?
