### ISSUE TITLE
Respect source maps in error dialogs

### ISSUE THREAD

**Issue by DirectXMan12** [novnc/noVNC#796]
We should try and respect source maps (when available) in error dialogs (see #774), since they'll be more prevalent as of #774

**Comment by samhed** [comment]
Is this urgent, or can this wait until after release some time?

**Comment by CendioOssman** [comment]
Nice to have, but I'd rather see a release soon-ish.

**Comment by CendioOssman** [comment]
Both Chrome and Safari now load modules natively, so the need for source maps is fading away.

**Comment by samhed** [comment]
I'll go ahead and remove the milestone from this.

**Comment by CendioOssman** [comment]
We no longer convert things so no more source maps to support.
