### ISSUE TITLE
Set up builds for production and auto-publish on tags using Travis

### ISSUE THREAD

**Issue by DirectXMan12** [novnc/noVNC#797]
We should auto-publish production builds of noVNC for the supported "build" types, and publish the CommonJS version to NPM.  This should be done automatically using Travis when we tag a release.

**Comment by CendioOssman** [comment]
Is CommonJS the preferable build format though? It's advantage is a single file, but the downside is that this file prevents the loading animation, and source maps don't work (#798).

**Comment by DirectXMan12** [comment]
since NPM is node-related, most people probably expect it to work with browserify, so you need *unundled* commonsjs.  I was thinking on NPM we'd ship the unbundled CommonJS, as well as the raw files, but in both cases just the stuff under `core` (and `vendor` where appropriate).

**Comment by CendioOssman** [comment]
Ah, right. Of course. That sounds right.

But perhaps we **also** want a built version of the "app"?

**Comment by DirectXMan12** [comment]
It might make sense to distribute that as the "official" app, since it's self-contained, but that won't be on NPM.
