### ISSUE TITLE
Make source maps work in Browserify

### ISSUE THREAD

**Issue by DirectXMan12** [novnc/noVNC#798]
Browserify has some issues when processing files which have pre-existing source maps (discovered during #774).  There are ways around this, which we should make sure we do in the app-build version of the CommonJS release.

**Comment by CendioOssman** [comment]
Browserify also insists on inline source maps, whilst a separate file is more production friendly.

**Comment by samhed** [comment]
Postpone this until after release?

**Comment by CendioOssman** [comment]
We no longer convert anything so no source maps to fix.
