### ISSUE TITLE
Auto reconnect only reconnects to last connection

### ISSUE THREAD

**Issue by steve13814** [novnc/noVNC#799]
Open one vnc.html page, enable auto reconnect and connect to VM A (by specifying VM A's ip, port). And then open another vnc.html page and connect to VM B (by specifying VM B's ip port). When VM A's vnc.html page triggered reconnect, it actually reconnect to the VM B, not VM A.

I think this is because the local storage only save one instance of setting, so later connection override this setting. I've record a video to show how this can be reproduced.
https://www.youtube.com/watch?v=0b3zX-714Jk

**Comment by samhed** [comment]
Yes, you are correct, this is due to local storage.

**Comment by DirectXMan12** [comment]
I don't think there's much we can do about this.  I'm going to close, but feel free to reopen if you feel otherwise.

**Comment by steve13814** [comment]
I think this is a serious problem if the user is an IT working on multiple VMs. Auto reconnect might mislead the user.
There are still some workarounds available on this issue. For example, generate unique id for each connection and save multiple instance in local storage. Another method is to reread those options from the form and the URL again.
What's your opinion about the two methods?

**Comment by CendioOssman** [comment]
I'm with @steve13814 on this. This does not seem like desired behaviour. I think we need to have another look at how configuration works in the case of multiple tabs.

**Comment by DirectXMan12** [comment]
we could try to prefer sessionStorage over localStorage (apologies, I failed to recall sessionStorage when I closed this), but only the local storage would persist across close and re-open, I believe.

**Comment by Craigzyc** [comment]
Why does reconnect need to be persisted at all? If you set auto reconnect I would expect it to exist only for the current session, not after a reload.

**Comment by samhed** [comment]
Because there are cases where you'd want a session to remain connected no matter how many times you get disconnected.

**Comment by Craigzyc** [comment]
I get that but a disconnect is not a page refresh so storing it in a local variable still works in that situation. 
It only needs to go to localStorage to persist across full page reloads which seems counter intuitive from a security standpoint and is what's causing the issue mentioned. 

If it was stored in a variable each window would auto reconnect to the session its supposed to which seems like a far better idea

**Comment by samhed** [comment]
Sorry I misunderstood you, I see your point. I tend to agree tbh.

**Comment by CendioOssman** [comment]
Since #1010 is merged this should now be fixed. Could someone retest?

**Comment by CendioOssman** [comment]
No response. Assuming it works now.
