### ISSUE TITLE
Open Application programaticaly

### ISSUE THREAD

**Issue by aftabnaveed** [novnc/noVNC#802]
Is it possible to open application programatically through noVNC? I embedded noVNC in my web application Now when VNC session is running I would like to open browser automatically with provided URL.

**Comment by CendioOssman** [comment]
Do you want to open an application inside the VNC session? That isn't supported I'm afraid, and I'm not aware of any extension to do that. The closest thing is sending over the URL via the clipboard but you'll have to manually sort out opening something.

**Comment by aftabnaveed** [comment]
Thanks for your reply, I will look for a different option.
