### ISSUE TITLE
Mouse Arrow is hidden

### ISSUE THREAD

**Issue by zwick88** [novnc/noVNC#803]
Hallo everyone,

sorry for my bad english.
I've today updatet de flash player. Now if i put my mouse over the iframe from de novnc window, my Mouse arrow will hidden. But i don't wont that, because on my remotesystem, (its a embedded Linux on an ARM11) i can only klick on buttons, and no move the mous. So, now i dont see, where my mous is.

Can someone help me please?

**Comment by CendioOssman** [comment]
This is usually a server problem and has nothing to do with noVNC. Which VNC server are you using? Have you tried another VNC client and see if you get the same problem?

**Comment by zwick88** [comment]
No, this is no Server problem! Before i updatet to the new AdobeFlashPlayer version, it worked fine! I use frameBuffe VNC. With realVNC i see my arrow adv the cross of the mouse. The Server was built in Aug 2016 and worke since that absolutly fine!

**Comment by CendioOssman** [comment]
I had a quick look and it seems like libvncserver (which framebuffer-vncserver uses) will send an empty cursor if none is set. So I'm afraid it does look like a server bug. You can probably work around it for now though by disabling the "Local cursor" setting in noVNC. Have you tested that?

**Comment by zwick88** [comment]
I'm sorry, but i dont have any idea what do you mean. I can only programm C++, not html , java...
The only thing i Know is, that i have not updatet novnc or vnc server or anything like this. Flashplayer an Firefox were updatet. since that time, ther this issue. 
Can perhaps some help me to fix this?

**Comment by CendioOssman** [comment]
Which version of noVNC are you using?

**Comment by zwick88** [comment]
I Think its the version 0.6.1. in file /docs/version is it wirtten

**Comment by CendioOssman** [comment]
In that case you have a little gear icon on the top right. If you click that then you get a settings menu. Make sure "Local cursor" is unchecked and then connect.

**Comment by zwick88** [comment]
thank you very mutch. Now, the cursor is showing. have a nice day
