### ISSUE TITLE
noVNC Does Not OPen in an iframe

### ISSUE THREAD

**Issue by hernandito** [novnc/noVNC#806]
Hello,
A while ago, I was able to embed a noVNC URL inside an iframe. Cannot recall when, but at one point, it stopped loading. I just get white space. When I open the URL in a blank window, it shows up properly.

Is there any way to enable this? The noVNC is part of a Docker running on my server. It shows a Kodi interface of LibreELEC. The URL I am using to load the noVNC window is:

>  <iframe height="720" width="920" frameBorder="0" src="http://192.168.0.201:84/plugins/dynamix.vm.manager/vnc.html?autoconnect=true&host=192.168.0.201&port=5700"></iframe> 

Any help is greatly appreciated.

Thanks,

H.

**Comment by CendioOssman** [comment]
Is this the `master` branch? If so, then you're probably hitting #805.

**Comment by rajanbharti** [comment]
Is this issue resolved yet??

**Comment by CendioOssman** [comment]
That seems to be a different error. Are you running the laster `master`?
