### ISSUE TITLE
Is there a port of the utils\launch.sh script for windows e.g. powershell script? 

### ISSUE THREAD

**Issue by aberbegall** [novnc/noVNC#807]
Is there a port of the utils\launch.sh script for windows e.g. powershell script?

**Comment by CendioOssman** [comment]
Not that I'm aware of, no. Also websockify seems to not work on Windows (see novnc/websockify#108). So you'll most likely need to find some other websocket proxy if you need to run it on Windows.

**Comment by kanaka** [comment]
@aberbegall I've not tested it myself, but the node.js version of websockify should probably work okay in Windows: https://github.com/novnc/websockify/tree/master/other/js

You'll need to launch it directly rather than using the launch.sh wrapper.

**Comment by aberbegall** [comment]
@kanaka thanks for your feedback
I wasted quite some time converting the python code into a windows executable and later on realized that it does not work, then I looked for Websockets to Tcp alternatives spported on windows without much success, this has been quite frustrating so far...

My next step is actually what you have sugested me, try the node.js version of websockify... I hope I have more luck this time :)

**Comment by aberbegall** [comment]
It worked fine! thanks guys

**Comment by sebLopezCot** [comment]
Had the same issues with python for windows. Nodejs version worked great for me!

**Comment by aberbegall** [comment]
In case someone else needs a windows port, I share a few powershell scripts:
https://github.com/aberbegall/novnc-launch-powershell/blob/master/README.md

**Comment by Quintalq** [comment]
how to use script tags to pull-in it?
