### ISSUE TITLE
Enable Password Required

### ISSUE THREAD

**Issue by drunkBottle6** [novnc/noVNC#809]
I use noVNC. 
I want every user that access vnc.html and want to use noVNC needed to insert the password first. how to enable the feature? 
So it will be more like a login page but only require a password.

**Comment by CendioOssman** [comment]
Authentication requirements are controlled by your VNC server and not by noVNC. So please check the documentation for your server on how to configure such things.

**Comment by drunkBottle6** [comment]
Thanks you for your respond sir.
