### ISSUE TITLE
Wrong url for websockify request - handshake error

### ISSUE THREAD

**Issue by Alpha0x** [novnc/noVNC#810]
I'm using noVNC on a remote system wich is connected to a VPN server.
The problem is when I try to connect "press connect button on noVNC webpage" through internet I got the following error : 
`WebSocket connection to 'ws://www.XXXX.fr/websockify' failed: Error during WebSocket handshake: Unexpected response code: 302` (it's the same with http instead of ws)

This works fine when I try to connect locally.

The problem is my noVNC server (with websockify) is not located at `//www.XXXX.fr/websockify` but `//www.XXXX.fr/YY/ZZ/websockify` . This looks like the issue #805 but I can't find how to change this url request.

Thanks a lot.

**Comment by CendioOssman** [comment]
#805 has to do with the general loading of Javascript files, and not the websocket connection, so I'm afraid that's a different issue.

You can reconfigure the websocket path in the noVNC settings. Simply click the gear icon and you have a `path` setting there. In your case it would need to be `/YY/ZZ/websockify`.

**Comment by Alpha0x** [comment]
Thanks for your quick answer.
When I change the path, the error is 404 file not found... That's logical because I'have no websockify file here but it works locally. Can you help me ?

**Comment by CendioOssman** [comment]
Then it is not connecting to the proper server. Do you have some proxy or something inbetween? It would need to be configured to redirect the websocket connection.

**Comment by Alpha0x** [comment]
I just have the websockify proxy connected between the vnc server and the web server (through VPN).

**Comment by CendioOssman** [comment]
If you get different results locally and remotely then you must be using different servers.

You say that you use Apache, so you do in fact have a different server for remote connections? And yes, that needs to be properly configured if you wish to use it as a proxy.

**Comment by Alpha0x** [comment]
Thank you so much, I solved my issue. I just had to configure a new reverse proxy on my Apache server to lead my websocket.

Sorry for the trouble it wasn't really a noVNC issue... But thanks again for your help.
