### ISSUE TITLE
Mouse not working on Laptop Screen 12.5''

### ISSUE THREAD

**Issue by sicutdeux** [novnc/noVNC#816]
Tested on Chrome and Firefox (Windows 10 - 1607)

The bar with the touch assistive icons are shown but clicking and moving the mouse does not work, I used an external monitor, extended the screens, etc. and does not work either.

Tested using Edge Browse, the assistive icons are not shown and worked as it should.

**Comment by samhed** [comment]
what version of noVNC are you running?

**Comment by sicutdeux** [comment]
2 Versions:

Using proxmox 4.1-15, novnc-pve ver: 0.5-5

on Ubuntu 16.04 ver: 1:0.4+dfsg+1+20131010+gitf68af8af3d-4

**Comment by DirectXMan12** [comment]
those versions are both fairly old.  Can you test with master to see if it's still an issue?

**Comment by samhed** [comment]
I'm guessing this is the touch + normal mouse issue that was resolved some time ago.

**Comment by samhed** [comment]
closing due to no response
