### ISSUE TITLE
android chrome pinch to zoom "Cannot read property 'dispatchEvent' of null"

### ISSUE THREAD

**Issue by flumm** [novnc/noVNC#820]
When using noVNC on Chrome on Android (Nexus 5X, 7.1.1, Chrome 58.0.3029.83)

when doing a "Pinch" gesture, i get the error in the title (see screenshot)
![screenshot_20170511-085604](https://cloud.githubusercontent.com/assets/5641944/25936574/9aeb5a50-3628-11e7-973b-2866622cfadd.png)

is this expected behaviour? or should the scaling be changed?

**Comment by samhed** [comment]
Thanks for your report! I can reproduce your issue, while we don't have gesture support, you should not be getting this error.

I'm taking a look.

**Comment by samhed** [comment]
Should be fixed in 333ad45c7029d02e3660965953cc85d83ce9bec0
