### ISSUE TITLE
ReferenceError: fgt_sslvpn is not defined

### ISSUE THREAD

**Issue by krzyzaq** [novnc/noVNC#825]
Hi,
I'm trying to substitute the vnc server (java browser plugin) with noVNC behind/over the FortiWeb vpn tunnel.
In the local network as well as with normal vpn tunnel all looks great but the problem is with the webbrowser vpn tunnel.  When I connect via browser over webvpn to noVNC the error as in the subject apperars and in the details... https://vpn.some_domain.pl:10443/proxy/http/novnc:5915/vendor/browser-es-module-loader/dist/babel-worker.js:24772:0
What should I do to make it run?

**Comment by CendioOssman** [comment]
`fgt_sslvpn` is not something that is present anywhere in noVNC, so this sounds like a bug in FortiWeb. It sounds like it is trying to inject something in to our JavaScript.

So I'm afraid I'll have to point you at FortiNet and file a bug with them.
