### ISSUE TITLE
Could not able to connect remote machine.

### ISSUE THREAD

**Issue by jpatel956** [novnc/noVNC#826]
Hello NoVNC,

Earlier i did remote connection and it was working fine but now I got some error while trying to establish connection with remote machine. There error is "websockify.py code 400". I don't know how to comeout of this error. could you please guide me.

Thanks

**Comment by CendioOssman** [comment]
Did this start happening when you upgraded something? What versions are you using of the individual components? Could you share the entire log?

**Comment by jpatel956** [comment]
I am using version: 0.6.1
logs:
Remote IP: ignoring socket not ready
Remote IP: ignoring socket not ready
Remote IP: ignoring socket not ready
Remote IP: ignoring socket not ready
Remote IP: ignoring socket not ready

**Comment by CendioOssman** [comment]
And the other components?

And that is quite obviously not a complete log. It doesn't even include the error you mentioned.

**Comment by jpatel956** [comment]
Here are the whole log.

bash-4.2$ ./libs/noVNC/utils/launch.sh --listen 7002 --vnc Remote IP:5900 --cert cert.pem 
Using local websockify at /var/app/current/libs/noVNC/utils/websockify/run
Starting webserver and WebSockets proxy on port 7002
WebSocket server settings:
  - Listen on :7002
  - Web server. Web root: /var/app/current/libs/noVNC
  - SSL/TLS support
  - proxying from :7002 to Remote IP:5900


Navigate to this URL:

    http://ip-172-31-32-86:7002/vnc.html?host=ip-172-31-32-86&port=7002

Press Ctrl-C to exit



Remote IP: ignoring socket not ready
Remote IP: ignoring socket not ready
Remote IP: ignoring socket not ready
Remote IP: ignoring socket not ready
Remote IP: ignoring socket not ready

**Comment by CendioOssman** [comment]
And again, where is the error you originally referred to?

**Comment by jpatel956** [comment]
@CendioOssman , sorry but now i have faced another error. initial i was getting the same error that I mention in question. so I was provided log of the current error that I have got. and the error logs is difficult to interpret.

**Comment by CendioOssman** [comment]
That error occurs when websockify gets a connection and no data. Which browser are you using?

**Comment by jpatel956** [comment]
I am using chrome browser. In one senario, its working fine.
1: Installed VNC IN linux system. Where i can able to successfully connected remont machine.
2: Installed Tight Vnc. Where i am not able to connect. The same error occurred which I mentioned earlier. I have uses latest version of Tight Vnc.

**Comment by jpatel956** [comment]
Tight VNC In window base system. Where connetion issue occurred.

**Comment by jpatel956** [comment]
The issue was happend due to remont machine side. we are using RealVNC but when we going to changed it to TightVNC. it is working fine.
