### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by megamindbrian** [novnc/noVNC#829]
import RFB from "/files/rfb.js"

Uncaught SyntaxError: Unexpected token import

Can you please create a properly packed example that includes just the /dist/ folder needed for common use cases?

**Comment by CendioOssman** [comment]
The wiki isn't updated with the latest development changes, so it's not really production ready yet.

But you need to either use an engine that supports modules (only Safari AFAIK), or use `utils/use_require.js` to convert the files. It has `--help` that gives you some information about options and formats.
