### ISSUE TITLE
black splotches

### ISSUE THREAD

**Issue by kpetrow** [novnc/noVNC#833]
Running Novnc through websockify to a remote machine on a cell card.  Upon connection the only view-able areas are ones that are updating.  problem is solved by hitting cntrl+alt+del then escaping, but need the full view on load.  Is there a command to refresh screen?  It appears like the initial screen is lost and only updates are viewed, When testing on machine on local network no issue is seen. 
![image](https://cloud.githubusercontent.com/assets/18248938/26415546/11cdb0ea-4070-11e7-8009-7a8209daaf6b.png)

**Comment by kpetrow** [comment]
More bug shooting this might only be seen when using the unvc repeater.  Continue to trouble shoot.  Would be alot easiesr if i could find a refresh frame function to trigger.

**Comment by CendioOssman** [comment]
I'm having trouble setting up a test environment here. What VNC server are you using? And how is the repeater configured?

**Comment by kpetrow** [comment]
Ruled out the repeater issue.  We use the uvnc repeater for tunnelling out but found am able to reproduce without the repeater and can connect to some machines that use the repeater

We use uvnc server found here. http://www.uvnc.com/docs/uvnc-server.html

I can give out the credentials for a box that is showing an issue. They are probably off for the holiday today.  Couple theories that are based on pure speculation.

1. Crappy cell coverage.  This is only seen when we connect via cell card.  If we use our test machine on intranet or even a cell card at the office it works.  We also have boxes in intranet over vhf with no issue.

2.  Windows uac is blocking something?

3.  Some cell providers block some traffic?  We use a VPN to give the boxes ip's, and generally don't have issues with AT&T, Verizon, but maybe the shove some weird provider into the box?

5.  Websockify is dropping something on startup?

We are far away from narrowoing down this issue and can not blame novnc.  I was hoping with a refresh command we see that it isn't novnc?

**Comment by CendioOssman** [comment]
Have you tried with other clients? E.g. TigerVNC?

**Comment by CendioOssman** [comment]
So I got uvnc set up here and I see lots of missed updates both with noVNC and TigerVNC. So my initial impression is that uvnc is just generally bad at sending updates.

My guess is what you're seeing are more issues on this theme in uvnc. So for now I'm going to have to ask you to file a bug with them. If you can test other viewers and they don't have issues then we can investigate further.

**Comment by devZer0** [comment]
> VNC uses TCP, and the protocol does not handle loss of data, so none of those ideas sound plausible.

tcp DOES handle loss of data. udp doesn't

https://stackoverflow.com/questions/44599850/can-tcp-really-guarantee-delivery
