### ISSUE TITLE
.svg icons not working in vnc.html

### ISSUE THREAD

**Issue by 4cheese** [novnc/noVNC#834]
Checking the MIME-type shows "application/octet-stream"

**Comment by CendioOssman** [comment]
Is this with launch.sh? Which platform?

**Comment by 4cheese** [comment]
Yes CentOS 7

**Comment by CendioOssman** [comment]
Odd. That should be new enough. What does this command give you:

```
python -c 'import mimetypes; mimetypes.init(); print mimetypes.types_map[".svg"]'
```

**Comment by 4rhel** [comment]
[root@123 ~]# python -c 'import mimetypes; mimetypes.init(); print mimetypes.types_map[".svg"]'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '.svg'

**Comment by CendioOssman** [comment]
Alright, so something is off with the mime database on your system. Is the package `mailcap` installed?

**Comment by 4rhel** [comment]
Yeah wasn't installed. Installed and did a reboot. All icons work now EXCEPT Fullcreen and Settings

**Comment by CendioOssman** [comment]
Probably a cache issue. Try clearing it in your browser.

**Comment by 4rhel** [comment]
Another thing. Don't wanna create a new issue over this. How do I set the default scaling option to Local Scaling so that it scales like that by default without having to go through the UI every time.

**Comment by CendioOssman** [comment]
It should save the settings between runs. Open the developer tools in your browser and check local storage. Do you have an entry called `resize`?

**Comment by 4rhel** [comment]
No yeah. I meant something I can integrate in a shell script for every NEW setup of noVNC on different servers
