### ISSUE TITLE
novnc in openstack,the Clipboard cannot work

### ISSUE THREAD

**Issue by guanxianchun** [novnc/noVNC#835]
In openstack,we according QEMU to instance a machine,when I use novnc active the machine,the clipboard in novnc cann't work,it can not copy and paster content from my computer to the instance machine with QEMU in openstack,also can not copy and paster any content from it to my computer

**Comment by samhed** [comment]
There is no clipboard support in vnc_lite.html (former vnc_auto.html). If you are using vnc.html, you must be using the clipboard interface.

**Comment by CendioOssman** [comment]
I also don't think QEMU supports clipboard transfers. @DirectXMan12 ?

**Comment by DirectXMan12** [comment]
Yeah, I don't think qemu supports the clipboard part, at least for RFB (some suggest it works for Spice, but everything seems to point to it not being supported for RFB).

**Comment by guanxianchun** [comment]
yeah,I use vnc.html,but the qemu is  not supports the clipboard part,Also,I try to use Spice, the copy and paster is not work yet in openstack. In KVM,the copy and paster can work ,but in openstack the cannot,So,I do not know how to solve this problem?

**Comment by wylbjia** [comment]
Have you solved this problem？

**Comment by samhed** [comment]
?

The issue is not with noVNC.

**Comment by Liuhao-baby** [comment]
I have a same problem with you, have you solved this problem?
