### ISSUE TITLE
Daemonize and Rename launch.sh

### ISSUE THREAD

**Issue by danielkho** [novnc/noVNC#84]
I kind of like the idea of using that "launch.sh" script to launch vnc servers. However, so as not to confuse myself with other running processes, I renamed it to vncserverd.sh to follow the current conventions of daemon names (such as sshd, httpd, etc.).

Probably it's a good idea to rename launch.sh to something like that.

So, I could create a simple bash script (vncd.sh) that I could just run on the command line:
# !/bin/bash

vncserverd.sh --cert /export/home/user1/.vnc/self.pem --listen 6080 --vnc localhost:5900 &
vncserverd.sh --cert /export/home/user2/.vnc/self.pem --listen 6081 --vnc localhost:5901 &
vncserverd.sh --cert /export/home/user3/.vnc/self.pem --listen 6082 --vnc localhost:5902 &

And kill those processes when I need to.

Also, eventually I'd like this to be a "first-class" daemon. Probably something that I can run as an inetd under /etc/services? Not really sure of the best way to do this, and I've no experience with writing daemons.
Ideas?

P/S: I like that there are not many options to learn :) Hopefully, this stays this way so that people will find this easy to use.
I also like the idea that I could kill WebSockets (or the proxy), while my current VNC sessions remain active. I could kill and restart the proxy and recover back my active VNC sessions... cool :)

**Comment by allenzhao64** [comment]
In CentOS 7, it is trivial to make the launch.sh a daemon. 

For example, I just create a file /usr/lib/systemd/system/novnc@:1.service
`[Unit]
Description = start noVNC service
After=syslog.target network.target

[Service]
Type=simple
User=allen
ExecStart = /opt/noVNC/utils/launch.sh --vnc localhost:5901

[Install]
WantedBy=multi-user.target
`
then you can just start it as daemon: 
`system enable novnc@:1`
'system start novnc@:1`

**Comment by stiliajohny** [comment]
> ExecStart = /opt/noVNC/utils/launch.sh --vnc localhost:5901

I would advise if you want to start multiple sessions on multiple vnc listeners to have something like 

`ExecStart = /opt/noVNC/utils/launch.sh --vnc localhost:590%i --listen 608%i`

In which case, if you have a vnc server broadcasting on 5902 you can start the novnc by executing 
systemctl ( system ) start novnc@2 ( the number after the @ it will replace te %i )
