### ISSUE TITLE
Paste to keypresses

### ISSUE THREAD

**Issue by helmo** [novnc/noVNC#840]
When you connect to a textconsole you have no way to use clipboard integrations.

Would it be an option to add a button, similar to the one to send 'CTRL+ALT+delete', to sent the characters from the clipboard to the keyboard? Or from an intermediate textfield?

This would be really helpful for entering long passwords on a textconsole you only use for recovery purposes.

**Comment by CendioOssman** [comment]
I think this probably belongs in the server instead. After all, VNC has clipboard in the protocol so it's really a limitation in how your server decides to implement that protocol.

**Comment by helmo** [comment]
Thanks for the quick answer ... yes such support on the server side would be the best solution.

In the meantime I did find a piece of JS code that should do the trick ... on https://gist.github.com/croepha/7b53f211ae4be3c526c3 
For me unfortunately it gives an error `TypeError: offset is undefined rfb.js (line 1272)` ... but I'll dig into that. (proxmox bundled novnc, fairly old)

**Comment by flumm** [comment]
> (proxmox bundled novnc, fairly old)
i recently updated novnc for pve5 (the patches are applied)

if you are using proxmox, do you want this on a vm or container? (container should have working clipboard), with vms this will probably never work, as qemu has no knowledge of the guests clipboard

**Comment by helmo** [comment]
Thanks for working on that :)

My current focus is on VM's run by kvm/Qemu. I know the textconsoles don't have knowledge of a clipboard ... that's why I was thinking of a way to just sent the string as a number of keyPress events. 
That should then be just like you typed the long password yourself.

**Comment by flumm** [comment]
sorry for hijacking the issue,

i agree with @CendioOssman that this (normally) belongs in the server, but
for the use case in pve i guess your proposal makes sense,

can you maybe open a feature request on the pve bugtracker instead ? (https://bugzilla.proxmox.com )
we can then discuss this there instead of polluting the novnc bugtracker

**Comment by helmo** [comment]
OK, I've opened one https://bugzilla.proxmox.com/show_bug.cgi?id=1406
