### ISSUE TITLE
noVNC behind apache proxy

### ISSUE THREAD

**Issue by bforpc** [novnc/noVNC#842]
Hi,
i cant get noVNC to work behind a apache proxy in our intranet. The relevant part in the Apache config (ip=192.168.3.153) looks like that:

  ProxyPass /websockify/ ws://192.168.3.208/websockify/  retry=0
  ProxyPass / http://192.168.3.208:6080/ retry=0
  ProxyPassReverse / http://192.168.3.208:6080/ retry=0

At machine 192.168.3.208 is the X Server and vnc4server running. Also noVNC with defaults.
If i go to my url, i get the noVNC picture and the connecting dialogue. But no connect to it. (If i run it localy - within the intranet and without apache proxy - i can connect to the running vnc4server trought noVNC). So it seems to be the apache Proxy.
Additional question: for what do i need the "websockify" - i didnt have a websockify directory like the url in the target machine. And secondary: in the future i need to start noVNC trough the proxy not at the / root, but with a url like [address}/novnc or similar.

Best regards from Hamburg / Germany
bfo

**Comment by samhed** [comment]
Thanks for sharing your configuration @SeppBender
