### ISSUE TITLE
noVNC  sometimes gives error in iframe

### ISSUE THREAD

**Issue by rajanbharti** [novnc/noVNC#845]
Sometimes it works fine, sometimes, it stops working with errors. But able to use in window without any issues.

![vnc_error](https://user-images.githubusercontent.com/12953200/27176668-0e81992e-51e1-11e7-89c5-40da77020215.png)

**Comment by CendioOssman** [comment]
Could you share how the iframe is set up?

**Comment by rajanbharti** [comment]
<iframe id="device_frame" src="http://'+resp.host+':'+resp.vnc_web_port+'/vnc.html" style="width:340px; height:490px;"></iframe>

we are dynamically adding this iframe using jquery

**Comment by CendioOssman** [comment]
I'm afraid I'm unable to reproduce any issue.

Which browser are you using? On which platform?

Have you made any modifications to noVNC?

Have you changed any settings?

Could you open the settings panel and attach a screen shot of that?

**Comment by rajanbharti** [comment]
I am using chrome. noVNC  without any modifications and settings. i'll post screenshot asap

**Comment by CendioOssman** [comment]
> I am using chrome

Which platform?

**Comment by rajanbharti** [comment]
Ubuntu 16.04 LTS

**Comment by CendioOssman** [comment]
I tried that and I'm still not getting any errors.

Did you manage to get that screen shot?

And what commit of noVNC are you using?

**Comment by rajanbharti** [comment]
![vnc_error_settings](https://user-images.githubusercontent.com/12953200/27227738-52997cd0-52c2-11e7-9487-a5119c364584.png)

 I am unable to open settings, when it's crashed.
I was using 2 week old commit, as I had set up at that time, after pulling latest commit. Still got same issue

**Comment by CendioOssman** [comment]
Everything looks okay there as well. Can you test a different browser?

**Comment by samhed** [comment]
Closing due to no response.

**Comment by rajanbharti** [comment]
error was there sometimes only when creating iframe dynamically. not when we show/hide existing iframe.
