### ISSUE TITLE
NPM novnc browserify fails

### ISSUE THREAD

**Issue by aruns07** [novnc/noVNC#846]
Hi team,

I am trying to use novnc-browser module from npm. The provided build index.js file has auto generated _conect function with limited integration. Hence I tried to pull all necessary modules and build my own, but it failed when I browserify.  All files are required from lib folder e.g. require('novnc-browser/lib/rfb.js'). 

The reason is: novnc-browser/lib/inflator.js requires '../vendor/pako/lib/zlib/inflate.js' which is a ES module. The desired module is present at current folder './vendor/pako/lib/zlib/inflate.js'

Moreover the "../utils/common.js" file is not present neither in 'lib/vendor/pako/lib' nor in 'vendor/pako/lib'.

Is there a way I can build it, or may be I am doing something wrong?

**Comment by CendioOssman** [comment]
How did you convert things? Did you use our scripts or something else?

**Comment by aruns07** [comment]
I think `npm install novnc-browser` runs prepublish script, which converts the code.

**Comment by CendioOssman** [comment]
Actually that download some version of noVNC from npm that is not officially supported by us. We can't be fully sure how that was built, which version it is, or what local modifications it might have.

We do not yet fully support node.js (see #675). However I did some fixes and you might get it running by doing:

```
node ./utils/use_require.js --as commonjs
```

And then grabbing the files from `lib/`.
