### ISSUE TITLE
iPad Pro w/Smart keyboard capital letters not being sent

### ISSUE THREAD

**Issue by doug-w** [novnc/noVNC#847]
With the new iPad 10.5 and a Smart Keyboard, noVNC is ignoring the state of the shift key or cap locks and all letters are being sent in lower case.

**Comment by samhed** [comment]
That's really wierd.. It's [this keyboard](https://www.apple.com/smart-keyboard/) right?

What version of noVNC are you using? What VNC server are you using?

**Comment by doug-w** [comment]
That's the one (10.5 version.) 

Latest off of master ( 637a282be54f2c2e97aff6d94f4c2fe1a51e0b96 )
built with:
./utils/use_require.js --as commonjs --with-app
run with launch.sh.

Ran into it talking to a Windows 10 server (Couldn't unlock the screen due to capital letter until I unplugged keyboard and used OSK.) and then an OSX server when saw couldn't type open /Applications

**Comment by samhed** [comment]
Ok, thanks for the response. So it works with the on-screen keyboard. Are you having the same problem if you use the latest release of noVNC? We have done some changes recently and I know that I have tested a physical keyboard with an iPad mini before.

@CendioOssman I didn't test iOS with a hardware keyboard after the keyboard changes in #766. Did you?

**Comment by CendioOssman** [comment]
I did not, but I did test now and I can confirm that there is an issue.

**Comment by CendioOssman** [comment]
Alright, issue identified. iOS sends completely garbage key up events which screws up the key tracking and results in this issue. I'll see what can be done.

**Comment by CendioOssman** [comment]
Fixed in 9e99ce126ca8f6f350fa015c0e58d35103c62f7e. This doesn't make the keyboard work perfectly though as there are still very odd events being sent for some things, so it seems like Safari doesn't fully support hardware keyboards yet.

**Comment by samhed** [comment]
Thanks for taking a look and fixing!
