### ISSUE TITLE
binary websocket

### ISSUE THREAD

**Issue by vtolstov** [novnc/noVNC#849]
i have some problems when use binary websockets (golang backend).
Firstly - does anybody used binary websockets without websockify?

To succesedul auth i need to modify core/websock.js
```
     _decode_message: function (data) {
+        var u8 = new Uint8Array();
+
+if (typeof(data) == "string") {
+        var u8 = new Uint8Array(data.length);
+
+        for(var i=0,j=data.length;i<j;++i){
+            u8[i]=data.charCodeAt(i);
+
```

because data goes to this function as string and Uint8Array returns nothing.
After this i have problem with server init messages. My backend send serverinit, but chrome displays warning in console:
```
WebSocket connection to 'ws://85.143.203.138/websockify' failed: Could not decode a text frame as UTF-8.
open @ websock.js:216
_connect @ rfb.js:401
_updateConnectionState @ rfb.js:561
connect @ rfb.js:278
connect @ ui.js:1071
```

**Comment by vtolstov** [comment]
So, does anybody can helps me?

**Comment by CendioOssman** [comment]
Both errors indicate that your server is sending things as text, not binary. So this seems like a but in that end. Where is this server from?

**Comment by vtolstov** [comment]
Yes, thanks. I found root case of this issue - by default go websocket server send text but not binary.
After changing to binary all looks fine.
