### ISSUE TITLE
Optimize vnc.html for faster Loading/rendering

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [novnc/noVNC#850]
Optimize novnc code using suggestions from Google Page Speed Insights:

Suggestions from the tool given below:
Leverage browser caching
Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.
Leverage browser caching for the following cacheable resources:
/app/error-handler.js (expiration not specified)
/app/images/alt.svg (expiration not specified)
/app/images/clipboard.svg (expiration not specified)
/app/images/connect.svg (expiration not specified)
/app/images/ctrl.svg (expiration not specified)
/app/images/ctrlaltdel.svg (expiration not specified)
/app/images/disconnect.svg (expiration not specified)
/app/images/drag.svg (expiration not specified)
/app/images/esc.svg (expiration not specified)
/app/images/expander.svg (expiration not specified)
/app/images/fullscreen.svg (expiration not specified)
/app/images/handle_bg.svg (expiration not specified)
/app/images/keyboard.svg (expiration not specified)
/app/images/mouse_left.svg (expiration not specified)
/app/images/mouse_middle.svg (expiration not specified)
/app/images/mouse_none.svg (expiration not specified)
/app/images/mouse_right.svg (expiration not specified)
/app/images/power.svg (expiration not specified)
/app/images/settings.svg (expiration not specified)
/app/images/tab.svg (expiration not specified)
/app/images/toggleextrakeys.svg (expiration not specified)
/app/styles/Orbitron700.woff (expiration not specified)
/app/styles/base.css (expiration not specified)
/app/ui.js (expiration not specified)
/…-loader/dist/browser-es-module-loader.js (expiration not specified)
/vendor/promise.js (expiration not specified)

Eliminate render-blocking JavaScript and CSS in above-the-fold content
Your page has 2 blocking script resources and 1 blocking CSS resources. This causes a delay in rendering your page.
None of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.
Remove render-blocking JavaScript:
/app/error-handler.js
/vendor/promise.js
Optimize CSS Delivery of the following:
/app/styles/base.css

Eliminate render-blocking JavaScript and CSS in above-the-fold content
Your page has 2 blocking script resources and 1 blocking CSS resources. This causes a delay in rendering your page.
None of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.

Remove render-blocking JavaScript:
/app/error-handler.js
/vendor/promise.js
Optimize CSS Delivery of the following:
/app/styles/base.css

Prioritize visible content
Your page requires additional network round trips to render the above-the-fold content. For best performance, reduce the amount of HTML needed to render above-the-fold content.
The entire HTML response was not sufficient to render the above-the-fold content. This usually indicates that additional resources, loaded after HTML parsing, were required to render above-the-fold content. Prioritize visible content that is needed for rendering above-the-fold by including it directly in the HTML response.
None of the final above-the-fold content could be rendered even with the full HTML response.

Minify JavaScript
Compacting JavaScript code can save many bytes of data and speed up downloading, parsing, and execution time.
Minify JavaScript for the following resources to reduce their size by 6.6KiB (48% reduction).
Minifying /…-loader/dist/browser-es-module-loader.js could save 5.4KiB (47% reduction) after compression.
Minifying /vendor/promise.js could save 1.2KiB (51% reduction) after compression.

Minify HTML
Compacting HTML code, including any inline JavaScript and CSS contained in it, can save many bytes of data and speed up download and parse times.

Minify HTML for the following resources to reduce their size by 1.2KiB (37% reduction).
Minifying /vnc.html could save 1.2KiB (37% reduction) after compression.
Hide details

Minify CSS
Compacting CSS code can save many bytes of data and speed up download and parse times.

Minify CSS for the following resources to reduce their size by 1.2KiB (30% reduction).
Minifying /app/styles/base.css could save 1.2KiB (30% reduction) after compression.
Hide details

**Comment by DirectXMan12** [comment]
... I'm going to go ahead and close this.  A bunch of the suggestions don't apply (e.g. not blocking on the error handler) or are tasks for people actually deploying noVNC (e.g. minifying resources).  Please don't just verbatim dump output like this.  If you have specific, concrete suggestions for noVNC, though, feel free to make them.
