### ISSUE TITLE
Keypresses produce duplicates

### ISSUE THREAD

**Issue by sebLopezCot** [novnc/noVNC#851]
When typing in textboxes at certain times keypresses are duplicated. For example, "hello" turns into "hhhheeeelllllllloooo". Any thoughts why this might be? Have seen it mostly with TightVNC latest version.

**Comment by CendioOssman** [comment]
Usually that is the result of the server having keyboard repeat enabled. I'm not sure if TightVNC has protection against that. Could you check the settings on the server? Or test with another VNC server?

**Comment by sebLopezCot** [comment]
When testing with x11vnc, it appears as though the issue does not surface. I was not able to find a keyboard repeated setting in TightVNC, but I will keep looking.

**Comment by CendioOssman** [comment]
Alright, it would seem the issue is with TightVNC in that case. Please report the issue to them and hopefully they can provide a fix.
