### ISSUE TITLE
How to make novnc full screen display?

### ISSUE THREAD

**Issue by gqqcode** [novnc/noVNC#852]
I would like to modify the size of the display desktop, what should I do?

**Comment by CendioOssman** [comment]
There is a full screen button on the toolbar (if the browser supports it). Settings for resizing or scaling the session is in the settings panel (also on the toolbar). Resize requires support from the server though, so it might not work with all servers.

**Comment by samhed** [comment]
The full screen button is only available in vnc,html, not in vnc_lite.html. Just as with many other features.

**Comment by gqqcode** [comment]
Thank you for the answer, but I want the virtual machine to operate the area full-screen display, or according to the browser's wide and high adaptive @samhed @CendioOssman

**Comment by CendioOssman** [comment]
I take it is it QEMU in that case. As far as I know it does not support resizing. Please file an issue with them to add this feature.

**Comment by gqqcode** [comment]
Thank you for the answer @CendioOssman
