### ISSUE TITLE
Redirecting noVNC OnClose or Connects?

### ISSUE THREAD

**Issue by TclHttpd** [novnc/noVNC#853]
I have a websocket to TCP server which manages access to the server via a session id. When the noVNC client disconnects the session id is destroyed. When the user clicks on the Connect Button in noVNC my server will not accept the connection with the old session id (this is what I want). Therefore the user has to hit the back button of the browser to go to the launch page again to pickup a new session id. I tried sending a 302 redirect from the server to go to the launch page but noVNC is not redirecting. Is this correct behaviour or is there another to do this? Maybe a query parameter in the the URL string "OnCloseRedirect=URLpath"?

**Comment by CendioOssman** [comment]
I'm not sure where you are sending that redirect because there is no request made on disconnect. To do what you want you'd need to modify the JavaScript to change the location when disconnecting. Should be sufficient to modify `app/ui.js`.
