### ISSUE TITLE
Unable to connect to AWS ec2 instance without RDP

### ISSUE THREAD

**Issue by keksanket** [novnc/noVNC#855]
Hi ,
   I am facing this weird issue and I am not able to wrap my head around it. Basically I want to access my amazon ec2 instance using noVNC . 
When I am logging into my windows instance using RDP file(that amazon provide to connect to server) , I can access the machine using noVNC .

**But if I close the RDP session(using microsoft remote desktop) and try to access the machine instance using noVNC , it shows failed to connect to server [Error] .**

I am using websockify for websocket to tcp proxy on amazon server and noVNC on front end server.
I am able to telnet to 5900 port of my amazon IP Address 

Can anyone please help me out regarding this issue.

Thank you very much

**Comment by DirectXMan12** [comment]
I'm not sure we can help you much with this.  Does it work with other VNC clients?  Perhaps opening the RDP connection opens up some firewall rules?

**Comment by keksanket** [comment]
Hi , 
Thanks for the response , I am able to fix this issue. 
The issue is fixed by only connecting through noVNC and not connecting via RDP to ec2 instance . So if I reboot my instance , RDP is disconnected and thus I am able to connect using RFB(noVNC) protocol. 

I still do not know the reason behind this , but the issue I raised is fixed.

**Comment by DirectXMan12** [comment]
closing as per above comment.
