### ISSUE TITLE
Type '@' but got '2' by using android virtual keyboard

### ISSUE THREAD

**Issue by steve13814** [novnc/noVNC#858]
When I type '@' in android emulator or in my real phone, I got '2' in windows vm. When I type '#', I got '3'.
I also record a video for this.
https://youtu.be/ztiBNrCs54Y

Here's the novnc log when I type '@' using android virtual keyboard, only keysym is sent:
<pre>
Sending keysym (down): 64
Sending keysym (up): 64
</pre>

Here's the novnc log when I type '@' using real keyboard, it seems that keysym and scancode are both sent:
<pre>
Sending key (down): keysym 65505, scancode 42
Sending key (down): keysym 64, scancode 3
Sending key (up): keysym 64, scancode 3
Sending key (up): keysym 65505, scancode 42
</pre>

I think it is likely to be qemu's bug but not pretty sure. It works well when both keysym and scancode are sent. Not when only keysym is sent.

#### Server side:

Ubuntu 16.04
qemu 2.9.0
nginx 1.10.3
npm version 3.10.10
node v6.11.0
noVNC master branch (commit be70fe0a3d94a209b369cd3443974e5ec05df551)

#### Client side:

Android Emulator: Chrome 58.0.3029.121

Here's the step:

git clone https://github.com/novnc/noVNC.git
npm install
node ./utils/use_require.js --as commonjs --with-app
Open browser to http://x.x.x.x/noVNC/build/vnc.html?host=y.y.y.y&port=z&autoconnect=true

**Comment by steve13814** [comment]
I read the rfbproto (https://github.com/rfbproto/rfbproto/blame/master/rfbproto.rst#L1229). It seems that shift state should not be maintained when interpreting keysym, but qemu (https://github.com/qemu/qemu/blob/v2.9.0/ui/vnc.c#L1636) maintains shift state because qemu use keyboard layout as a parameter.
I don't know which side should modify the behavior....

**Comment by steve13814** [comment]
Okay, I think this is neither novnc's nor qemu's bug, but it is a design difference between them. Novnc doesn't have the idea of keyboard layout, so it does not maintain shift state. Qemu has the idea of keyboard layout. It chooses a specific keyboard layout (eg. us keyboard) and emulate the scancode.

To improve the use case of virtual keyboard, one of them can do some modifications. One possible solution is that novnc can provide an option to simulate specific keyboard layout, so novnc know when to generate shift key event. Another possible solution is that qemu can provide a special keyboard layout option to trust keysym and transform keysym to a specific keyboard layout.

**Comment by CendioOssman** [comment]
Virtual keyboards aren't really compatible with virtual machines as they are heavily oriented around an actual physical keyboard. Neither we nor QEMU want to maintain a database of keyboard layouts in order to try and bridge this gap. So I'm afraid this is not a use case we'll handle.
