### ISSUE TITLE
Ability to disable clipboard integration

### ISSUE THREAD

**Issue by hanselb** [novnc/noVNC#859]
I have a use case where an application I am testing becomes unresponsive if there is a nvc client connected sharing the clipboard. I am able to reproduce the issue using realvnc viewer, but if I disable send clipboard changes to server, the issue stops.

I tried looking into the RFB source as well as the client but didn't see anything about the clipboard at the RBF level. I tried disabling the events for clipboard, but that didn't help. 

I am guessing is a property that has to be sent with the connection.

Please let me know if there is a way to work around this or what we would need to do to implement this.

![image](https://user-images.githubusercontent.com/5930195/28122109-39478a00-66eb-11e7-8f9a-79037f5040d5.png)

Thanks,

Hansel

**Comment by samhed** [comment]
Correct, noVNC currently assumes that clipboard is always available.

**Comment by samhed** [comment]
Can you test #888 and see if that works for you?

**Comment by DirectXMan12** [comment]
So, this is a bit strange -- due to browser limitations, etc, the user has to actually interact with the clipboard panel in order for noVNC to send clipboard changes, so if you're not interacting with that panel, there shouldn't be an issue.  Does the issue occur without interacting with the panel?

**Comment by DirectXMan12** [comment]
closing due to no response

**Comment by hanselb** [comment]
Hey @DirectXMan12, I am sorry I didn't see this until now. The issue is definitely present without interacting with the panel.

I think the problem might be by the way the connection is initialized. I was able to reproduce it with realvnc viewer, but if I disable "send clipboard changes to server", the issue stops. That makes me think that just like realvnc sets some kind of flag on the connection, noVNC should be able to do the same when starting the RFB.

**Comment by samhed** [comment]
I don't believe that there is any flag that would indicate that you won't be sending clipboard to the server.

**Comment by CendioOssman** [comment]
I tested it here and there is no clipboard sent to the server just by connecting. So whatever your issue is it doesn't seem to be because of the clipboard.

I suggest you file a bug report with the application developer. They're in a much better position to figure out what the issue is.
