### ISSUE TITLE
Is there a way to disable mouse and keyboard control separately? 

### ISSUE THREAD

**Issue by antonioaguilar** [novnc/noVNC#861]
When setting ```view_only: false``` property in the ```RFB``` configuration object, this allows full mouse and keyboard control in the VNC session. But in my case, I only would like to enable mouse control but not keyboard control in the session. Is this possible?

**Comment by samhed** [comment]
There is no setting etc. for this, you will have to modify the JavaScript. Start by having a look at how it's done for view only.

**Comment by antonioaguilar** [comment]
ok - any specific sections of the code I should look at?

**Comment by samhed** [comment]
look at core/rfb.js
