### ISSUE TITLE
NoVNC performance monitoring

### ISSUE THREAD

**Issue by glin-sfdc** [novnc/noVNC#863]
hello team,

I am new to this. I would like to know if there is way to monitor the NoVNC performance, I would like to see if the log can provide each fbu-update-request and corresponding fbupdate delta time. This would give us a real time NoVNC performance view. 

Please advise and thanks.

**Comment by glin-sfdc** [comment]
to Joel Martin, Hi, I tried to load simple.js on the browser file:///home/user1/novnc/tests/vnc_playback.html?data=simple.js, it did not work. I open the browser on the VNC Gnome based GUI screen. 

Please advise if you can. and Thanks

**Comment by CendioOssman** [comment]
I would recommend using the profiling tools in the browsers. There is some debug performance logging in noVNC, but I wouldn't trust the accuracy or overhead of that.

And you can't use `file://` with noVNC as many modern web technologies are turned off with such URIs. :)
