### ISSUE TITLE
Safari stuck at loading screen indefinitely

### ISSUE THREAD

**Issue by nickjer** [novnc/noVNC#865]
Setup:

- using latest noVNC at commit edb7879927c18dd2aaf3b86c99df69ba4fbb0eab
- macOS Sierra 10.12.5
- Safari 10.1.1
- connected to with url:
  ```
  /vnc.html?autoconnect=true&password=******&path=path/to/websockify&resize=remote
  ```

We only see the loading screen:

<img width="1159" alt="screen_shot_2017-07-21_at_9 41 35_am" src="https://user-images.githubusercontent.com/4260509/28466156-6a8450de-6df9-11e7-965d-80b878a55e33.png">

Note: It does work for latest Chrome, latest Firefox, and IE Edge using the exact same link and VNC session.

**Comment by DirectXMan12** [comment]
@samhed is this maybe that double-loading issue?

@nickjer if you use the one of the built formats (`utils/use_require.js --as commonjs --with-app`, and then run the `vnc.html` in the `build/` directory`) does it work?

**Comment by samhed** [comment]
@DirectXMan12 I've been away from work for a couple of weeks now, I feel completely oblivious to any issue like this. Could you remind me? :)

**Comment by DirectXMan12** [comment]
I was talking about this, I believe: https://github.com/novnc/noVNC/pull/836

cc @CendioOssman (sorry, forgot who it was that dealt with this issue ;-) )

**Comment by nickjer** [comment]
@DirectXMan12 I built edb7879927c18dd2aaf3b86c99df69ba4fbb0eab using your suggested command line:

```sh
$ utils/use_require.js --as commonjs --with-app
Writing /path/to/noVNC/build/app.js
Writing /path/to/noVNC/build/app/error-handler.js
Writing /path/to/noVNC/build/app/styles/Orbitron700.ttf
...
```

 and pointed the browser to `/build/vnc.html?...` but the issue still exists for Safari.

**Comment by nickjer** [comment]
I lied, I was actually going to the old build at `/vnc.html?...`, turns out your suggestion @DirectXMan12 works with `/build/vnc.html?...`.

**Comment by DirectXMan12** [comment]
ok, so, probably something to do with the PR that I linked above then.

For future reference, the recommended way to run noVNC is with one of the "built" formats (you can pass `--as (amd|commonjs|systemjs|amd)` depending on what module format and loader you'd like to use), while the "unbuilt" form is mainly for development.

However, the unbuilt form should work on any browser we support, so I'd love to figure out the issue here.  What does the developer console in Safari say?

**Comment by nickjer** [comment]
That is good to know, will re-build from now on. Thanks.

**Comment by CendioOssman** [comment]
Is this still an issue?

**Comment by nickjer** [comment]
No, rebuilding the library resolved the issue.

**Comment by JoshuaLyle** [comment]
This is still an issue as of 37b4d13db81e0e80e117c07b86ff98714c7b6b1a (Oct 02, 2018).

On Safari 12 in Mojave on that commit, going to NoVNC with the normal safari useragent yields an endless loading screen. If I switch my user agent to MacOS Firefox inside of Safari, it loads just fine.

**Comment by samhed** [comment]
I can't reproduce the issue using either 37b4d13db81e0e80e117c07b86ff98714c7b6b1a or the latest 1.1.0 release. I tested Safari 12.1 on macOS 10.14.

Try clearing your browser caches, perhaps you are encountering some problems due to that.

**Comment by JoshuaLyle** [comment]
That could be the case. I haven't had the issue since just after an upgrade from a 2017 commit. It very well could be that the cache expired and that's why it's working now
