### ISSUE TITLE
Commercial Support for noVNC

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [novnc/noVNC#866]
Is there any organization that provides commercial support for noVNC?

**Comment by samhed** [comment]
Not that I know of. Let's leave this open for a while however, to give someone else the chance to answer.

**Comment by VinayaSathyanarayana** [comment]
Are there individuals (who are knowledgeable about the internal working of noVNC) willing to provide support for a fee?

**Comment by VinayaSathyanarayana** [comment]
Any responses please.

**Comment by DirectXMan12** [comment]
It's been open a couple months, doesn't look like anyone's responding.  I'm going to close this.  If you have a specific feature in mind, you may want to consider adding a bounty on one of the bounty sites (NOTE: I'm *not* trying to imply that any of the core maintainers prioritize features on bounties.  I'm simply suggesting that external contributors may be motivated by them).
