### ISSUE TITLE
Server resize does not trigger client rescale

### ISSUE THREAD

**Issue by haqa** [novnc/noVNC#867]
When the server changes resolution noVNC should rescale (if client side scaling is enabled) to keep the new screen within the viewport.

Is there also an interaction that triggers server scaling? Resizing the noVNC canvas seems to cause a rescale in either setting.

**Comment by chetanraj** [comment]
+1

**Comment by samhed** [comment]
> When the server changes resolution noVNC should rescale (if client side scaling is enabled) to keep the new screen within the viewport.

Indeed! +1

>Is there also an interaction that triggers server scaling? Resizing the noVNC canvas seems to cause a rescale in either setting.

Are you saying that you are getting scaling even is scaling mode is set to "remote resize" or "none"? What exactly do you mean by "server scaling"?

**Comment by haqa** [comment]
I mean when the setting is "remote resize"

**Comment by samhed** [comment]
Remote resize should not affect scaling in any way. It will send a resize request for the size of the browser window to the server. If the VNC server supports and allows this, the remote desktop / session will fit the browser window.

**Comment by haqa** [comment]
That explains the behaviour I've seen in that mode.

There is still the question of whether the client should automatically resize when scaling is set to "Local Scaling" and the server resizes the virtual screen. My feeling is that this is exactly what the user has requested - "noVNC, please always keep the whole screen visible, even if it's hard to read"

**Comment by samhed** [comment]
Ok, so nothing weird with "remote resize" then.

Yes, I absolutely agree.

**Comment by CendioOssman** [comment]
A small adjustment, so fixed in d1a1e0e529833c4ada0f6cc422c3f5b02ecbee60.
