### ISSUE TITLE
Running noVnc inside the docker container,  is this possible? 

### ISSUE THREAD

**Issue by darshansr** [novnc/noVNC#868]
I have multiple VM'S, that should be accessed by many users with different server instance.  But using noVnc I can access only one VM per instance.

So my idea is to access multiple VMs by multiple users. 
Is that possible using docker?? 
Or any other way can I run multiple server instance of noVnc? 🙃

If my question is wrong,  correct me. 
And please help in getting right solution.

**Comment by doug-w** [comment]
Seeing this made me polish up a container I'm using locally.  It's on the docker hub now at [https://hub.docker.com/r/dougw/novnc/](https://hub.docker.com/r/dougw/novnc/) with the code here on GitHub [https://github.com/doug-w/docker-novnc](https://github.com/doug-w/docker-novnc) I use it locally to talk to 2 desktops and 2 containers over a reverse proxy.

**Comment by DirectXMan12** [comment]
you could also listen on different ports, or use the token functionality in websockify do direct different clients to different vnc servers (see the websockify wiki for more information).

I'm closing this, since you now have two answers.  Feel free to re-open or continue to post if you have more questions.

**Comment by darshansr** [comment]
Thank you for the help, its working.
I am able to run multiple instances of VM using docker images.
@doug-w

**Comment by guotong1988** [comment]
Thank you.

**Comment by guotong1988** [comment]
@doug-w Does the image contains a ubuntu or centos?
