### ISSUE TITLE
Support resize option in Client

### ISSUE THREAD

**Issue by chetanraj** [novnc/noVNC#869]
I'm having an app, when the client resizes, option to resize or re-render the canvas.

**Comment by samhed** [comment]
?

What problem are you facing? Is 'client' referring to the browser?

**Comment by chetanraj** [comment]
yes it's browser, when i resize the browser, is there any option to adjust the screen based on the resolution ?

**Comment by samhed** [comment]
yes, change scaling settings to "remote resize". That does however require you to use a VNC server that supports the ExtendedDesktopSize encoding.

**Comment by rajchetan** [comment]
We're currently using **x11vnc**, and it supports _ExtendedDesktopSize_, when the resize happens do we have to invoke to vnc server to resize, can you please guide me how to do that ?

**Comment by samhed** [comment]
If your server supports and allows it, it should be automatic once you resize the browser. Given that you are using the correct setting in noVNC, as mentioned above, of course.

If you know for sure that your server supports it and if you are using the "remote resize" setting and it still doesn't work, you should check your VNC server logs for what's happening.
