### ISSUE TITLE
noVNC not able to resize properly when vnc server runs on openmotif 

### ISSUE THREAD

**Issue by drycup** [novnc/noVNC#870]
noVNC is able to resize correctly when vnc server runs on gnome desktop (centos).

With the same vnc server, when we change to openmotif window manager, noVNC client is not able to resize properly.

Any suggestion?  Thanks.

**Comment by samhed** [comment]
This does not sound like a noVNC issue, but do you have a screenshot or a better explanation of what's happening?

Which VNC server are you using?

**Comment by drycup** [comment]
We are running tigervnc on centos 7.  noVNC works perfectly against tigervnc on a centos gnome desktop.

Then we switched to running centos vnc inside a docker container.  Here is the docker container we model after. https://hub.docker.com/r/kevensen/centos-vnc/
Inside the container, it runs 3 things: xterm, mwm and tigervnc.  Everything else works except the resizing - when I resize the browser window, vnc viewer doesn't adjust the resolution accordingly.

I don't think docker is the issue here.  Tigervnc and noVNC are the same.  The only difference is mwm (motif window manager).  

I agree this is most likely not a noVNC issue.  But I am surprised that a different window manager would cause this kind of issue and wondering if there is any suggestion.

Thanks.

**Comment by samhed** [comment]
I don't have any personal experience with motif, but I know it's old. Maybe motif simply doesn't allow changing the resolution of a running desktop? Maybe it can only be set during startup?

**Comment by drycup** [comment]
No problem.  Thank you!

**Comment by DirectXMan12** [comment]
*closing as per the previous comment*
