### ISSUE TITLE
Vimperator (Firefox extension) breaks keyboard input

### ISSUE THREAD

**Issue by koreymacdougall** [novnc/noVNC#871]
Vimperator intercepts keystrokes, to modify their behaviour in the browser.  This will stop any keyboard input from reaching noVNC.

I spent a while trying to reconfigure keyboard layouts before realizing the plugin was the culprit.  Disabling it will restore functionality.  

(this issue may be better tagged as a known limitation, rather than a bug)

**Comment by DirectXMan12** [comment]
yeah, there's not much we can do here.  If the browser is intercepting input, there's nothing a webpage can do.  Thanks for the heads-up.
