### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by treaki** [novnc/noVNC#872]
ok, i now have installed novnc and made it correctly point to the vnc server listening only to localhost and it is all working perfectly.
all done by

```
cd [...]/noVNC
DISPLAY=:57 x11vnc -localhost -rfbport 5957 -forever -shared -passwdfile vncpw &
./utils/launch.sh --vnc localhost:5957 &
```

but how to log access? On the vnc server i can now only see that someone from localhost has established an connection to myself, but i would like to have an list of successful and unsuccessful connections with together with the exact timestamp and the remote ip/port.

What do i have to do to get such an output:

```
$ cat [...]/noVNC/novnc.log
event;         timestamp;                    remoteip;        remoteport
connecting;      Mo 31. Jul 04:01:40 CEST 2017; 203.0.113.3;    3512
login correct;   Mo 31. Jul 04:01:42 CEST 2017; 203.0.113.3;    3512
disconnected;    Mo 31. Jul 04:02:07 CEST 2017; 203.0.113.3;    3512
connecting;      Mo 31. Jul 04:09:14 CEST 2017; 203.0.113.66;   1666
login incorrect; Mo 31. Jul 04:09:15 CEST 2017; 203.0.113.66;   1666
login incorrect; Mo 31. Jul 04:09:18 CEST 2017; 203.0.113.66;   1666
login incorrect; Mo 31. Jul 04:09:19 CEST 2017; 203.0.113.66;   1666
login incorrect; Mo 31. Jul 04:09:19 CEST 2017; 203.0.113.66;   1666
login incorrect; Mo 31. Jul 04:09:20 CEST 2017; 203.0.113.66;   1666
login incorrect; Mo 31. Jul 04:09:21 CEST 2017; 203.0.113.66;   1666
login incorrect; Mo 31. Jul 04:09:21 CEST 2017; 203.0.113.66;   1666
disconnected;    Mo 31. Jul 04:09:22 CEST 2017; 203.0.113.66;   1666
$ 
```

thanks a lot in advance

**Comment by DirectXMan12** [comment]
noVNC itself is just a web application.  `launch.sh` launches websockify, which serves a websocket proxy and a normal HTTP server.  Neither of those has access to login information from your VNC server.  The only one who can log that server side is your VNC server.

Otherwise, websockify should log connections for you, and you can see client-side logs from the developer console in your browser.
