### ISSUE TITLE
How could I make clipboard panel working on embedded solution (novnc.xsl)?

### ISSUE THREAD

**Issue by dreyTee** [novnc/noVNC#873]
Hello everyone. 

First, I wanna mention - _it's not an issue, but a question about implementation._

I tested fresh installation of noVNC and it works fine (clipboard panel works). 
I have noVNC embedded into out product and it works fine except it doesn't have clipboard panel (we have only CtrlAltDel button and status bar with "Connected(encrypted)" text on the top of VNC-window). We use novnc.xsl file instead of vnc.html (we also use websockify, of course). Host and password are sent from our app to novnc.xsl and connection made automatically. Usual Ctrl+C/Ctrl+V don't work even if autocutsel and vncconfig is running near VNC-server (started with both -AcceptCutText and -SendCutText options).

The question is - **how should I include ui.js to xsl file to make clipboard panel accessible?** 

I tried to include it near others, inside these parenthesis:
```
// Load supporting scripts
        Util.load_scripts(["webutil.js", "base64.js", ...
```
but it gives me errors like this:
`Uncaught TypeError: Cannot read property 'options' of null`
on the line
`UI.addOption($D('noVNC_setting_stylesheet'),sheets[i].title, sheets[i].title);`
threating $D('noVNC_setting_stylesheet') as null. 
And I'm not familiar with JS.

Hope someone has similar experience and could help me.

**Comment by DirectXMan12** [comment]
`app/ui.js` is *very* specific to `vnc.html`, so you're going to run into issues unless the structure of your file matches ours.  I'd port just what you need to your program.

In this case, I'd recommend implementing your own copy of the clipboard panel -- you'll just need a textarea and to call the appropriate clipboard methods on the RFB object.

**Comment by DirectXMan12** [comment]
feel free to continue commenting on this issue, but I'm going to close it for now.

**Comment by dreyTee** [comment]
Thanks for reply and for an awesome project!
I did implement only clipboard button and it works like a charm!
