### ISSUE TITLE
why Clipboard not work?

### ISSUE THREAD

**Issue by liuguanfei** [novnc/noVNC#875]

**Comment by samhed** [comment]
Works perfectly for me. Could you better describe your issue and what you have tried please?

**Comment by DirectXMan12** [comment]
Please note that due to various browser limitations, the remote clipboard is not directly synced with the local clipboard.  Instead, it can be manipulated through the clipboard panel in the noVNC UI (or via the clipboard methods on the `RFB` object if you are building your own application using noVNC).

**Comment by liuguanfei** [comment]
Thank you I found that vncserver does not support the clipboard

**Comment by malisalulu** [comment]
Why didn't I use API RFB. clipboard PasteFrom (text) on the document to paste?

**Comment by malisalulu** [comment]
I use API RFB. clipboard PasteFrom (text) on the document. Why didn't it work as a paste?

**Comment by malisalulu** [comment]
I use API RFB. clipboard PasteFrom (text) on the document. Why didn't it work as a paste?Here's the function
that.clipboardPasteFrom = function(text) {
    if (rfb_state !== "normal") { return; }
    //Util.Debug(">> clipboardPasteFrom: " + text.substr(0,40) + "...");
    ws.send(clientCutText(text));
    //Util.Debug("<< clipboardPasteFrom");
};

**Comment by pm-pm** [comment]
Maybe tigervnc 1.7 is the problem? Or **at least an information to all using debian stretch (stable):**

If you use tigervnc **1.7** you have to **start "vncconfig" to use clipboard**.
See release notes tiger vnc 1.8: "[vncconfig no longer needed for clipboard with Xvnc/libvnc.so](https://github.com/TigerVNC/tigervnc/releases)"

Who is using old tigervnc 1.7? :-/ Tigervnc 1.7 is the [offcial debian release for debian strech](https://packages.debian.org/stretch/tigervnc-common) (stable). There are no backports available. For the next debian release buster (testing) the latest tigervnc 1.9 is available.

If you want to use tigervnc 1.8 or 1.9 with debian stretch you have to install tigervnc manually. You can find and[ follow the links here](https://github.com/TigerVNC/tigervnc/releases) to get the binarys.
