### ISSUE TITLE
Question on setting up secure vnc session between VMs

### ISSUE THREAD

**Issue by anrinch** [novnc/noVNC#876]
I am new to noVNC and I am trying to set up a secure vnc session between two VMs.
Both VMs run ubuntu 14.04 and have connectivity to each other. I want to run a VNC server (say x11vnc) on one of the VMs (IP: 192.168.56.101) and use noVNC on the other VM (IP: 192.168.56.102) to connect to the VNC server.  
I also want the VNC session to be encrypted so as I understand the best way to do this will be to run the websockify proxy on the same remote machine as the VNC server (192.168.56.101) and then connect with wss:// from the client (192.168.56.102).  Initially I am testing with a non-encrypted connection. 

So I run websockify on the server (192.168.56.101) using -- 
         
       python websockify.py 6080 localhost:5900

My x11vnc server is running on port 5900. Then I try to start a vnc session from the client (192.168.56.102) using noVNC as follows 

         ./launch.sh --vnc 192.168.56.101:6080

I follow the web link etc. but the VNC connection fails and websockify outputs the following.

WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5900

192.168.56.102: new handler Process
192.168.56.102: ignoring socket not ready
Ignoring interrupted syscall

 I have tried telnet from the client to websockify and to the vnc server. Both ports are open and listening. Also, this is not a firewall issue. This makes me believe that I am setting up the proxy incorrectly. I would greatly appreciate if someone can point out what I am missing here?

**Comment by DirectXMan12** [comment]
ah, so, note the noVNC is *purely* a browser component.  `utils/launch.sh` actually launches *websockfy* with a built-in webserver that also serves the noVNC HTML, JS, and CSS.

Use `utils/launch.sh` on the VM that is reachable via a browser, and point it at the VM that runs the VNC server (if the VM with the VNC server is accessible externally, you can just run `utils/launch.sh` directly on that).

**Comment by DirectXMan12** [comment]
please let me know if you have any further questions, but I'm closing this for the moment.

**Comment by anrinch** [comment]
Thanks for the clarification. Could get this working now!
