### ISSUE TITLE
iPad with external keyboard - spacebar won't work

### ISSUE THREAD

**Issue by getgray** [novnc/noVNC#878]
Using this via vultr's console app.  I can connect and apparently type everything except a spacebar.  (Spacebar tested, works in othr apps including ipad ssh client).  Any workaround?  I need to be able to get console access via the iPad, can't if spacebar won't work.

**Comment by samhed** [comment]
does it work with the virtual keyboard?

**Comment by getgray** [comment]
Negative.  With Vultr's installation I cannot get the virtual keyboard to come up at all.  I understand one of their tech is subscribed and listening here.  Maybe he will chime in.

**Comment by lwslade** [comment]
It's not possible to make the virtual keyboard show on an iOS device unless a text field is present. As such, the virtual keyboard isn't currently usable with noVNC consoles.

**Comment by samhed** [comment]
Yeah, you guys should use vnc.html instead of vnc_lite.html (former vnc_auto.html).

**Comment by samhed** [comment]
There are many nice to have features for touch devices available in vnc.html, among them a way to use the virtual keyboard.

**Comment by samhed** [comment]
Anyway, I won't be able to verify this bug with an external keyboard until I get back from my vacation in a few weeks. In the meanwhile, does the spacebar work in other **web** applications? That an ipad ssh client app that doesn't run in the browser works doesn't say much I'm afraid.

Try this one for example: http://www.keyboardtester.com/tester.html

If you are able to, it would also be interesting to know the results if you test our input.html, available in noVNC's "tests" subdirectory.

**Comment by getgray** [comment]
Verified functional on that website.  All keys on my keyboard with my device do work correctly there.  Tested with iPad Mini w/current IOS 10.3.3 and Microsoft Universal Foldable keyboard model 1695.

I don't see how I can access the tests subdirectory.  If there's some place on your site I can test it I'll be happy to.  FWIW, I went to http://novnc.com/noVNC-latest/vnc.html and in the host/password dialog popup, I can type spaces.

**Comment by samhed** [comment]
Ok, so just to make sure, the spacebar key lights up when you click it?

Do you have the possibility to plug in your iPad to a Mac for some debugging? The first thing to look for is to see if you get any errors in the JavaScript console.

> I don't see how I can access the tests subdirectory.

You would access it here, but it looks like it's broken in that version I'm afraid: http://novnc.com/noVNC-latest/tests/input.html

What version of noVNC are you using? Do you have the possibility to test the current master?

**Comment by getgray** [comment]
Not sure what you mean by lights up. No lights. But the space bar produces an in screen space every place tried except in the noVNC instance provided by vultr.com for their console access. 

I can round up a Mac Pro to test with. Will do as soon as I'm back to office. 

For version i must defer to the Vultr admins who are monitoring this thread to answer that.

**Comment by samhed** [comment]
> Not sure what you mean by lights up. No lights. But the space bar produces an in screen space every place tried except in the noVNC instance provided by vultr.com for their console access.

The link I gave you; http://www.keyboardtester.com/tester.html. That page should show a keyboard below the input box. The keys on that keyboard should highlight (first turn orange then green) when you press them.

**Comment by getgray** [comment]
Ahh, I see.  
At the KB tester website, Via my iPad, with the typing entry box selected:
1. via BT keyboard, type, the letters show in the box.  The webpage generates audible "clicks", the letters I type show in the box.  Spacebar gives space, and also generated clicks from the webpage audio.  The key "icons" on the page do not change to green boxes.
2. Virtual KB, same as above but the boxes do change to green after pressing a key.  Spacebar, too.

**Comment by getgray** [comment]
FYI.  Got a Macbook pro.  Checked it's KB at tester site.  Physical KB works, keys turn green when you type, spacebar, too.  Chrome and Safari.  vultr's comsole app works and allows spacebar from Macbook.

**Comment by CendioOssman** [comment]
Works fine for me (using TigerVNC's Xvnc) using latest `master`. What version is vultr using?

**Comment by samhed** [comment]
Thank you for testing this @CendioOssman

**Comment by samhed** [comment]
Closing due to no response
