### ISSUE TITLE
Disconnects when using x11vnc on to x11vnc clients

### ISSUE THREAD

**Issue by Craigzyc** [novnc/noVNC#879]
This doesnt seem to be an issue with noVNC but there is far more activity here so hopefully someone can shed some light.
I use noVNC to connect to both windows and linux based machines. On the windows machines the connections stay alive without issue. On the linux machines the connections are unpredictable and usually terminate between 10 seconds to 10 minutes but always self terminate.
In linux I'm using the websocket functionality built into x11vnc whereas on windows I'm using websockify running on a linux computer connecting to tigerVNC.

Are my issues likely x11vnc based? Would switching to a separate websockify process fix the issue?

All connections are over cellular so I originally thought it was that and accepted it until I added my first windows client which seem rock solid

**Comment by CendioOssman** [comment]
The first step would be checking logs. What does the browser console say when this happens? What do the logs from x11vnc say?

**Comment by samhed** [comment]
Closing due to no response
