### ISSUE TITLE
Better alignment of console window

### ISSUE THREAD

**Issue by rh-jelabarre** [novnc/noVNC#881]
One problem I've seen with the console window on noVNC is since the console starts immediately at the top of the page, it looks as though the top of the window is being cut off.  It took a bit of experimenting on my part to determine it isn't, but even with that it continues to appear as it is being cut off, or that you should be able to scroll upward.
I would suggest the window should have some small spacer above the console window to make it clear the console is being shown in it's entirety.

**Comment by DirectXMan12** [comment]
cc @CendioOssman who does most of the visual work on noVNC these days.

Can you post a screenshot with what you're suggesting?

**Comment by rh-jelabarre** [comment]
![novnc_console_current](https://user-images.githubusercontent.com/29484746/29432402-77222fca-8369-11e7-9e0c-6818da9d673b.jpeg)
![novnc_console_modification](https://user-images.githubusercontent.com/29484746/29432403-77254ce6-8369-11e7-8301-dce5f0367ba1.jpeg)

I have attached a couple jpeg images, one which shows a current view of an instance console in Openstack, and a second one with the suggested modification of dropping the console window jown just enough to separate it from the "header".  I believe Openstack makes use of the minimal (novnc_auto ?) form of NoVNC.

**Comment by DirectXMan12** [comment]
ah, I see what you mean.  That makes a bit less sense when fullscreen, but we can probably work out a good design that works in both cases.

**Comment by CendioOssman** [comment]
Ah, so this is `vnc_lite`. The standard frontend already centers the display. Perhaps the same should be done for lite?

And perhaps we should add a label so we can separate lite stuff from the rest?

**Comment by DirectXMan12** [comment]
> Ah, so this is vnc_lite. The standard frontend already centers the display. Perhaps the same should be done for lite?

Yeah, seems reasonable to me.

> Ah, so this is vnc_lite. The standard frontend already centers the display. Perhaps the same should be done for lite?

Done.  The labels are `ui/full` and `ui/lite`.

**Comment by samhed** [comment]
Fixed in #947
