### ISSUE TITLE
noVNC Connection to PLC

### ISSUE THREAD

**Issue by scorch95** [novnc/noVNC#882]
I got a problem connecting to GUI of a PLC (Manufacturer B&R). Connecting to other PC's in this Network with RealVNC Server running on them is working well. Connecting to the PLC with other VNC Clients is also working. Sadly i got no further information what kind of of VNC Server is running on the PLC.

Js Console:

 >> RFB.constructor
display.js:42 >> Display.constructor
display.js:70 User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
display.js:153 Setting viewport to full display region
display.js:92 << Display.constructor
devices.js:310 >> Keyboard.allKeysUp
devices.js:315 << Keyboard.allKeysUp
rfb.js:259 Using native WebSockets, render mode: canvas rendering
rfb.js:261 << RFB.constructor
rfb.js:536 New state 'connecting', was ''.
rfb.js:385 >> RFB.connect
rfb.js:396 connecting to ws://127.0.0.1:5901/websockify
rfb.js:409 << RFB.connect
ui.js:1039 [Violation] 'click' handler took 154ms
websock.js:222 >> WebSock.onopen
websock.js:224 Server choose sub-protocol: binary
rfb.js:213 Starting VNC handshake
websock.js:228 << WebSock.onopen
rfb.js:735 Server ProtocolVersion: 003.003
rfb.js:776 Sent ProtocolVersion: 003.003
rfb.js:831 Authenticating using scheme: 2
ui.js:1143 Passwort ist erforderlich
passwordRequired @ ui.js:1143
_negotiate_std_vnc_auth @ rfb.js:859
_negotiate_authentication @ rfb.js:983
_init_msg @ rfb.js:1136
_negotiate_security @ rfb.js:833
_init_msg @ rfb.js:1133
_handle_message @ rfb.js:658
_recv_message @ websock.js:312
ui.js:1143 Passwort ist erforderlich
passwordRequired @ ui.js:1143
_negotiate_std_vnc_auth @ rfb.js:859
_negotiate_authentication @ rfb.js:983
_init_msg @ rfb.js:1136
_handle_message @ rfb.js:658
_recv_message @ websock.js:312
rfb.js:1000 Authentication OK
rfb.js:1076 Screen: 1024x768, bpp: 8, depth: 8, big_endian: 0, true_color: 0, red_max: 7, green_max: 7, blue_max: 3, red_shift: 0, green_shift: 3, blue_shift: 6
rfb.js:1092 Server native red-shift is not 16
_negotiate_server_init @ rfb.js:1092
_init_msg @ rfb.js:1147
_handle_message @ rfb.js:658
_recv_message @ websock.js:312
rfb.js:1096 Server native blue-shift is not 0
_negotiate_server_init @ rfb.js:1096
_init_msg @ rfb.js:1147
_handle_message @ rfb.js:658
_recv_message @ websock.js:312
display.js:153 Setting viewport to full display region
devices.js:537 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
grab @ devices.js:537
_negotiate_server_init @ rfb.js:1106
_init_msg @ rfb.js:1147
_handle_message @ rfb.js:658
_recv_message @ websock.js:312
rfb.js:1721 Skipping Cursor pseudo-encoding
websock.js:172 bufferedAmount: 20
websock.js:172 bufferedAmount: 64
rfb.js:536 New state 'connected', was 'connecting'.
[Violation] Forced reflow while executing JavaScript took 76ms
devices.js:310 >> Keyboard.allKeysUp
devices.js:315 << Keyboard.allKeysUP

looks like connection is succesfull, but no picture is shown.

Output of websockify shows "[WINERROR 10054] an existing connection was forcibly closed by the remote host" 

I really appreciate any help you can provide.

**Comment by kimsto** [comment]
You don't say what version of noVNC you are using, but support for colormaps was removed some time ago, and it seems like it may be required since I see "true_color: 0" in the trace above.

**Comment by DirectXMan12** [comment]
I'd try a commit before novnc@26586b9ddf3f5aa3c96c0f1090cb2134966a055f and see if it works.  If it does, then it's probably the color map issue.

**Comment by scorch95** [comment]
I tried to use an older version with colormaps feature enabled. (fb73993 , 7569cdc)  Both throw the following exception:

websock.js:339 recv_message, caught exception: 
    name: TypeError
    message: this._display.set_true_color is not a function
TypeError: this._display.set_true_color is not a function
    at RFB._negotiate_server_init (http://127.0.0.1:8000/core/rfb.js!transpiled:1143:35)
    at RFB._init_msg (http://127.0.0.1:8000/core/rfb.js!transpiled:1201:41)
    at RFB._handle_message (http://127.0.0.1:8000/core/rfb.js!transpiled:674:34)
    at Websock._recv_message (http://127.0.0.1:8000/core/websock.js!transpiled:327:49)

This error is not limited to the PLC connection only. So maybe its a diffrent bug that was already fixed in newer versions.

**Comment by samhed** [comment]
I apologize that we missed responding to this one.

However, I tested these commits you mentioned and it works perfectly fine for me, both with and without true color. I suspect your code was broken someway. Perhaps you only checked out rfb.js from those commits and not the entire tree?

With regards to the original error, I believe, just as @DirectXMan12 and @kimsto wrote, the problem is that in new versions of noVNC we only support true color.
