### ISSUE TITLE
noVNC get stuck when connect to QEMU on a low speed network

### ISSUE THREAD

**Issue by lynncn** [novnc/noVNC#883]
If using noVNC to connect to a QEMU instance on a low speed network (e.g. 300KB/S Wide Area Network), the noVNC will be stuck when it receives a lot of frame buffer update.

The fastest way to reproduce:

1. Run a QEMU instance with option -vnc :1,websocket
2. Connect noVNC client to QEMU VM via websocket
3. Play a video on VM (To generates a lot of FBUs)
4. Limit the client inbound bandwidth to 300KB/S (To simulate a low speed WAN)
5. Then noVNC get stuck, the cursor is almost impossible to move

I know that noVNC is not designed for Multimedia but actually it works well with sufficient bandwidth (e.g. Local Area Network).

I tried using vncviewer to connect to QEMU in the same environment, although a lot of frame loss, it still works.

By contrast, I found that noVNC **never drop any frame**, it tried to display every frame
even when the network is congested so it will stuck.

As far as I'm concerned, it looks like a bug between QEMU and noVNC. 

Information about the environment: (tested version)
QEMU 2.7.1/2.9.0/2.10.0
Host OS: Ubuntu 16.04 Server LTS
Guest(VM) OS: Windows 7 64bit
Client OS: Windows 7 64bit
Client Browser: IE 11.0.9600/Chrome 60.0.3112
noVNC: 0.51/0.61/0.62

Any help much appreciated.

**Comment by CendioOssman** [comment]
It is the server that drops frames, not the client, so I'm not sure why you see a difference there.

Could you try with the current `master` of noVNC?

Which vncviewer was it you used?

**Comment by DirectXMan12** [comment]
I'd also like to note that qemu's RFB implementation *loves* to send lots of small updates.  One of the things I test performance against is a captured session of `ls -al ~` from qemu, since it really stresses the GC, etc.

**Comment by DirectXMan12** [comment]
So, is it actually dropping frames, or is it just that rendering and mouse handling are running in separate threads in the native client?  It may also be that there's a special encoding that we are (or are not) sending that the native client sends or does not send.

**Comment by lynncn** [comment]
@CendioOssman You are right, I did a further test.
Whatever the version, I got the same result:

- When connected via RFB protocol (vncviewer), the qemu will drop frames if network quality is poor .
- When connected via websocket (noVNC), the qemu will never drop any frames.

It seems that qemu's VNC/RFB implementation has plenty of problems : (   @DirectXMan12

**Comment by CendioOssman** [comment]
If the bug is in QEMU's websocket code then you could try using websockify. In that case QEMU will get a "normal" VNC connection.

**Comment by lynncn** [comment]
@CendioOssman  Well,  both Standalone websocket (websockify) and QEMU build-in websocket I have tried. Unfortunately, the results are no different.  It was extremely weird.

**Comment by CendioOssman** [comment]
Some network issue perhaps?

Could you try with a different VNC server together with websockify? Just to see if it specific to QEMU in some way.

**Comment by samhed** [comment]
Closing due to no response.
