### ISSUE TITLE
[RFC] New upstream noVNC release

### ISSUE THREAD

**Issue by kashyapc** [novnc/noVNC#889]
Is it reasonable to ask upstream to make a new release?

The last release happened in Jan 2017:

    $ git log --tags --simplify-by-decoration --pretty="format:%ai %d" | head -1
    2017-01-12 14:36:42 -0500  (tag: v0.6.2)

Since then, about 427 commits have accumulated:

    $ git log v0.6.2..HEAD --oneline | wc -l
    427

**Comment by DirectXMan12** [comment]
Yeah, I'd like to finish up the v0.7.0 milestone, but I'm thinking we're about ready for a v1.0.0 release.

@samhed @CendioOssman @kanaka WDYT?

**Comment by samhed** [comment]
+1 with regards to v1.0.0

**Comment by CendioOssman** [comment]
I agree. The system is more than ready for an official stable release. People are already using it that way. :)

We just need to go through the issues and decide which are blockers.

I mentioned this before, but I also think we need to severely limit what we consider a stable API in the cases where noVNC is used as a library.

**Comment by kashyapc** [comment]
Hi, wonder if there is any update on the release process here. From the last comment I see that sifting through issues to decide blockers is a pending item.

While at it --  did you consider making time-based releases?  It seems more in-line with current best practices.

**Comment by samhed** [comment]
Here's the list: https://github.com/novnc/noVNC/milestone/2

I'd like to boil it down to three important things remaining until we can wrap up a release:

* Get #893 tested and merged (should fix #860)
* Set up travis production builds
* Start publishing on NPM

**Comment by DirectXMan12** [comment]
Agree with @samhed on the blockers.  I'll move the rest to the "Future Features" milestone.

**Comment by CendioOssman** [comment]
We need to remember to get translations updated as well. Do you think we'll find volunteers on the mailing list, or should we get something like the translation project involved?

**Comment by samhed** [comment]
Ah yes, the translations. Currently we have German, Greek, Dutch and Swedish translations, plus an open PR for the Polish one (which can wait).

The original translators were:
* @LoekJanssen - German ( @lxp updated )
* @kosmasgiannis - Greek
* @LoekJanssen - Dutch
* me or @CendioOssman - Swedish

Are you guys able to update the translations if needed?

**Comment by kosmasgiannis** [comment]
I 'll be happy to update the Greek translations.

**Comment by CendioOssman** [comment]
Updated files ready to be translated:

[translations.zip](https://github.com/novnc/noVNC/files/1362008/translations.zip)

**Comment by yvanoers** [comment]
@LoekJanssen has asked whether I can help out. I'm happy to provide the Dutch translations, but won't be able to provide German translations.

**Comment by samhed** [comment]
Ok, thanks @yvanoers. We might have a colleague who can do the German translations, I'll ask him on Monday.

**Comment by samhed** [comment]
The colleague is sick at the moment. @yvanoers you are welcome to create a pull request with the updated Dutch translations.

**Comment by yvanoers** [comment]
I will. But before I do, could you, @samhed, or anyone please describe what 'clip to window' exactly does, so I can translate it properly?

**Comment by samhed** [comment]
"clip to window" is an alternative to scroll bars. It means that if the remote session's desktop is larger than the browser window - instead of getting scroll bars in your browser noVNC will trim the overflow.

In order to view the parts of the remote session that isn't displayed by noVNC in these cases, the user can use a different button (looks like a hand) in the interface that allows them to "drag" the viewport.

This mode is primarily designed for browsers that doesn't display proper scroll bars, such as most browsers on mobile platforms such as iOS or Android.

**Comment by flumm** [comment]
@samhed @CendioOssman i looked over the german translations in the translations.zip file, they look good

**Comment by CendioOssman** [comment]
I think there was one or two that was marked as `fuzzy` and needs adjustment.

**Comment by flumm** [comment]
you are right, i updated it and created the pull request https://github.com/novnc/noVNC/pull/920

**Comment by yvanoers** [comment]
Thanks, Dutch updates are in pull request #921

**Comment by samhed** [comment]
Thanks for all the help! Translations are all done now.

**Comment by samhed** [comment]
I have now moved the API documentation from the wiki to the repo.

**Comment by samhed** [comment]
Perhaps the last thing aside from writing release notes remaining: #924

**Comment by samhed** [comment]
#924 has been merged, but we should get #950 merged as well before a release. Unfortunately this means that we will need a new round of translations.

**Comment by samhed** [comment]
So, as I mentioned, we need new translations again. I'll tag you who have helped out in the past:

Dutch: @yvanoers, @LoekJanssen or @lxp 
German: @flumm or @LoekJanssen 
Greek: @kosmasgiannis 
Polish: @mariuszjamro 
Swedish: @CendioOssman or myself

Are you guys able to help once again?

**Comment by kosmasgiannis** [comment]
I 'll try to send new greek translations asap.

**Comment by CendioOssman** [comment]
I'm pretty happy with the state of things. Should we start fixing up a beta?

**Comment by samhed** [comment]
With 7f1049c0ee6f7f7c5d84509f9f2c5de70cd75dfb im now happy.

**Comment by samhed** [comment]
Found a couple of new issues, at least #979 should be fixed before a release.

**Comment by CendioOssman** [comment]
I've added a first suggestion on the steps for making a release:

https://github.com/novnc/noVNC/wiki/Development:-Making-a-release

Have a look and see what you think. If it looks okay then we should be able to get a beta out soon.

**Comment by samhed** [comment]
Looks good! Thank you

**Comment by DirectXMan12** [comment]
Looks like the only thing left is #997, which is fixed-ish AFAICT.  I think we may be ready!

**Comment by DirectXMan12** [comment]
(unless you want to move #973 into the 1.0 milesone)

**Comment by CendioOssman** [comment]
Great. If no one objects then I'll start following the release procedure next week, i.e. a beta will be released.

Is there anything special that needs to be done with NPM or is that completely automatic?

**Comment by DirectXMan12** [comment]
SGTM

It should autodeploy when you tag the release (look for the "deploy" phase to show up on Travis when you do)

**Comment by CendioOssman** [comment]
So, we've had the beta out for a couple of weeks now. Unfortunately there hasn't been a lot of feedback. :/

But we can't wait forever, so I'm thinking that we'll do a final release this week?

**Comment by samhed** [comment]
sounds good.

**Comment by CendioOssman** [comment]
Release is out, so closing this issue.
