### ISSUE TITLE
Visualization artifacts with Chrome 60.0.3112.107 on Android

### ISSUE THREAD

**Issue by paolovolpi** [novnc/noVNC#890]
I'm facing a problem after updating Chrome from v55 to v60 on an Android device connecting to a noVnc / x11vnc powered device using vnc_auto.html  with encrypt=0 and true_color=1 . I tried noVnc v0.6.2 and also the master branch(b02ecbee60) facing the same problem. Downgrading chrome to v55, or accessing with Firefox everything come back to work. 
Replacing x11vnc with the Qt vnc plugin gives the same problem. The only warning found in the noVnc log is: "Server native red-shift is not 16". Apart from the visualization artifacts (blank thick horizontal stripes, or totally blank screen apart from few pixels) everything is working (input is managed, screen is updated) .

**Comment by CendioOssman** [comment]
Could you give us a screen shot?

**Comment by paolovolpi** [comment]
![screenshot_2017-09-04-14-06-59](https://user-images.githubusercontent.com/2961708/30026108-ced61cfc-917b-11e7-9183-b14bac902e5b.png)
![screenshot_2017-09-04-14-09-16](https://user-images.githubusercontent.com/2961708/30026123-db9eeb94-917b-11e7-9c13-59beda969d30.png)

**Comment by CendioOssman** [comment]
Great, thanks.

Does the same thing happen with `vnc.html`? If possible, please test current `master`.

**Comment by paolovolpi** [comment]
Yes it happens also with vnc.html and my last check was with master b02ecbee60 that is the last commit.

**Comment by CendioOssman** [comment]
Are you using websockify? Could you make a recording of the data for us?

**Comment by CendioOssman** [comment]
We need something to test with unfortunately. And I assume this server is not something we can get up and running here?

**Comment by paolovolpi** [comment]
I can try to make a test using the python version of websockify to exclude problems on the C version and to record the session data for you but it will take some time to setup the env on the embedded system

**Comment by CendioOssman** [comment]
That would be very helpful. Let us know how it goes.

You could also start websockify on a different system, as long as you open up the VNC port externally.

**Comment by paolovolpi** [comment]
The python version of websockify is affected by the same problem. Please take a look to the data recorded using Chrome 55 (everything work perfectly) and using Chrome 60 (visualization artifacts). I suppose could be a problem related to 

[sessions.zip](https://github.com/novnc/noVNC/files/1276619/sessions.zip)


hybi/hixie decoding.

**Comment by CendioOssman** [comment]
I'm afraid I cannot reproduce this. :/

Do you have a different Android device to test with? It might be specific to certain devices.

Could you test different resize modes?

**Comment by paolovolpi** [comment]
Yes I tried with different Android devices with Chrome 60 facing the same problem.

**Comment by CendioOssman** [comment]
Could you try the different resize modes as wall? It might have something to do with scaling.

**Comment by paolovolpi** [comment]
Do you mean different scaling mode? I tried all the options available (None, Local Scaling, Local Downscaling, Remote Resizing) with the same result.

**Comment by CendioOssman** [comment]
Great, thanks. So we can rule that out.

Have you seen the issue with Chrome on a normal PC?

**Comment by paolovolpi** [comment]
Yes I tried with the same Chrome version on Linux and Mac and it's work.

**Comment by CendioOssman** [comment]
I'm not sure how to resolve this to be honest. We really need to be able to reproduce this in order to debug it. Any way you can make one of these devices accessible from the internet?

**Comment by paolovolpi** [comment]
I was able to reproduce the problem using a simple Qt (ver >= 5.8)  application with its embedded vnc server and python websockify both running on a linux pc. I'm attaching the source code of the Qt app, you need to lunch it setting the env variable  QT_QPA_PLATFORM to vnc:size=480x320 (QT_QPA_PLATFORM=vnc:size=480x320 ./TestVnc). 
[TestVnc.zip](https://github.com/novnc/noVNC/files/1284137/TestVnc.zip)

**Comment by CendioOssman** [comment]
I'm afraid I'm still unable to reproduce any issue. I compiled and started the application on Fedora 26, and it renders just fine from an Android device. Perhaps it has something to do with the theme you are using?

**Comment by paolovolpi** [comment]
Could you expose on internet that server? (I'd like to try my Android devices with it)

**Comment by CendioOssman** [comment]
No, this is an internal machine unfortunately. And the ones reachable externally don't have the required Qt 5.8. :/

**Comment by samhed** [comment]
How do we proceed with this? @paolovolpi I assume you didn't find a solution?

**Comment by paolovolpi** [comment]
No, I didn't

**Comment by samhed** [comment]
No response
