### ISSUE TITLE
how to connect to x11vnc using websocket without websockify

### ISSUE THREAD

**Issue by getmonyinfo** [novnc/noVNC#891]
Hey, i want to connect to x11vnc using websocket without websockify, how to do that

**Comment by samhed** [comment]
That's a question for x11vnc, not noVNC

**Comment by getmonyinfo** [comment]
I hava configed x11vnc with websocket, but it don't know how to set novnc to connect to x11vnc use websocket. i didn't find any docs about that!

**Comment by CendioOssman** [comment]
By default noVNC assumes the websocket connection is to be made to the same server it got the HTML from. Check under settings and you can modify the websocket host, port and path.
