### ISSUE TITLE
Import Declarations Error

### ISSUE THREAD

**Issue by jeffforbes** [novnc/noVNC#892]
I am getting this javascript error in firefox with the latest noVNC code:
SyntaxError: import declarations may only appear at top level of a module  webutil.js:13
plus others

It looks like this is an ES6 issue in the javascript code.
Could us  non expert users get some documentation on how to get the latest code to work?

**Comment by samhed** [comment]
It works for me, what version of Firefox are you running? What is the hash of the noVNC commit you are using?

**Comment by jeffforbes** [comment]
Firefox 55.0.2 64-bit Linux
I pulled the latest files into my git clone on 9/7/2017.
I then copied the javascript files into my test sysem
which was working with a version from Dec. 2016.


________________________________

**Comment by CendioOssman** [comment]
That was before we switched to ES6 modules. Are you sure you copied over everything? A lot of things were changed as part of that switch, not just the core JavaScript files.

**Comment by jeffforbes** [comment]
I will get a fresh clone and work from there.
Is there code that needs to be in place to tell the browser to use ES6?
I have not reviewed the latest vnc.html to see if there anything new that we need to
add to our code.

________________________________

**Comment by CendioOssman** [comment]
`vnc.html` most definitely needs to be updated. Check our version for how to handle things properly.

**Comment by jeffforbes** [comment]
I am now using your loading scheme from the latest vnc.html and get this error:
Error: selectbox is null
  Evaluating https://xxxxxxxxxx/app/ui.js
  Loading https://xxxxxxxxxxx/app/ui.js  browser-es-module-loader.js%20line%201424%20%3E%20eval:1652


________________________________

**Comment by CendioOssman** [comment]
Sounds like there is more stuff missing from `vnc.html`. If you wish to use `ui.js` then I'm afraid we can only really support our `vnc.html`. I suggest you start with an unmodified `ui.js` and `vnc.html` and port over your modifications one by one.
