### ISSUE TITLE
Compatibility with older noVNC?

### ISSUE THREAD

**Issue by bsampica** [novnc/noVNC#895]
Hi,

We're using a previous version of noVNC in an existing website, and have somewhat of a complicated setup that if need-be, I can describe.  Here's our current issue:

We currently connect using something like this:
/vnc/vnc_auto.html?host=central-server-hosting-reverse-proxy&port=7000&password=session-password&token=5851

The port is always 7000, this is used by the reverse proxy, the token is then used as the destination port.  Our VNC client connects to the reverse proxy using VNC full protocol over TCP, and then the browser connects to the web socket version (the reverse proxy uses nginx), using the token for the web socket proxied version.

1.) I can't find anyway to specify the password in the /vnc.html version now. 
2.) The host is present, the port is present, but the token is gone.
3.) vnc_lite.html works as is, but we want some of the additional UI and scaling options that are provided by the vnc.html window, as well as the fullscreen switcher.  Is this possible through the vnc_lite.html page?

Thanks

**Comment by samhed** [comment]
> 1.) I can't find anyway to specify the password in the /vnc.html version now.

You will be prompted for a password if required after pressing 'connect'.

> 2.) The host is present, the port is present, but the token is gone.

Answer by quoting from another issue:

>The token system was removed because it was redundant (and not standardised). You should modify the path element instead with the current code. 

For example: https://your.novnc/vnc.html?path=%2Fwebsockify%3Ftoken%3DXYZ

> 3.) vnc_lite.html works as is, but we want some of the additional UI and scaling options that are provided by the vnc.html window, as well as the fullscreen switcher. Is this possible through the vnc_lite.html page?

That depends on what you mean with "possible". The code to be able to do that is not available in vnc_lite.html, no.
You can add it if you want to, it shouldn't be too hard since you can look at vnc.html and ui.js.
