### ISSUE TITLE
Help with automation

### ISSUE THREAD

**Issue by JonTheNiceGuy** [novnc/noVNC#899]
I'm using noVNC through OpenStack to provide a console to a vendor supplied KVM image which doesn't understand DHCP, and I'm trying to automate some of our build processes.

I'd like (if possible) to be able to open the Developer tools, paste in some code, and be able to send automation instructions down the wire to the machine in question (something akin to AutoIT, AutoHotKey or similar).

Is this feasible, at all, or am I just going to have to provide manual build instructions for these machines (which is fine, if that's all I have...)

**Comment by DirectXMan12** [comment]
It's not impossible -- none of the core "RFB" interactions are directly tied to the mouse and keyboard -- you should be able to substitute your own, and manually call key inputs, mouse movements, and clipboard changes.  However, unlike AutoHotKey, we have no knowledge of the underlying windows being displayed, so you can't just say "jump to this window" -- you've have to say "move the mouse to this position, click, move the mouse again", etc.

Let me know if you have more questions.
