### ISSUE TITLE
Connect multiple vnc users sessions using noVNC client on a single host

### ISSUE THREAD

**Issue by thrinethratechhara** [novnc/noVNC#902]
Hello,

I am running a VNC client in a dedicated ubuntu. I have installed tight VNC server in windows 10 machine. I wish to allow multiple VNC sessions for all VNC users in my windows machine through noVNC client. Here the host/ip address is same for all hosts. I have a unique port number, password for all users created from Windows 10 machine. How can I use this in noVNC client such that all users should access their own VNC sessions with intercepting other's VNC session.

Is it possible to attain this. I should configure my client like url given below.

https://kanaka.github.io/noVNC/noVNC/vnc.html

Could you please help to achieve this. I have gone through the configuration file and I din't get any idea about this. 

Best Regards,
RK

**Comment by DirectXMan12** [comment]
you'd have to somehow externally set up authentication and authorization if you don't want people to be able to connect to others sessions.  One way to do this is with auth plugins and token plugins in websockify.  Check the websockify wiki for more details.

Please let me know if you have further questions.
