### ISSUE TITLE
NOVNC not continue reload.

### ISSUE THREAD

**Issue by AntoWkill** [novnc/noVNC#903]
From today without do nothing my novnc console stop working, its load and i can see the vm screen for 1-2 second and after disconnect and recharge.

The error is with ALL browser, i have also tried from Mobile Phone and i have the same error.

https://www.youtube.com/watch?v=7aPpensiZo0  --> Error screen

**Comment by CendioOssman** [comment]
Which version of noVNC are you using?

What does the browser console say?

**Comment by AntoWkill** [comment]
<img width="949" alt="novnc1" src="https://user-images.githubusercontent.com/21131925/30800951-f6aee792-a1e1-11e7-9b71-eee64baf84b2.png">
<img width="941" alt="novnc2" src="https://user-images.githubusercontent.com/21131925/30800957-fbe8432a-a1e1-11e7-84ff-138073ff50c2.png">
<img width="938" alt="novnc3" src="https://user-images.githubusercontent.com/21131925/30800964-040c706c-a1e2-11e7-83b1-e83898d05474.png">
<img width="937" alt="novnc4" src="https://user-images.githubusercontent.com/21131925/30800969-0862eec0-a1e2-11e7-8a19-f885bdf53a3d.png">

VERSION: novnc-pve: 0.5-9 (on proxmox)

**Comment by CendioOssman** [comment]
That is very old. I would suggest testing `master`.

However the logs seem to indicate a normal disconnect from the server. What VNC server is this? Can you check its log files?

**Comment by AntoWkill** [comment]
set 25 12:52:29 problem with client XXXX; ssl3_read_bytes: sslv3 alert bad certificate
I've already tried both letsencrypt and with the self-signed certificate s(the error becomes sslv3 alert unknown ca)

**Comment by CendioOssman** [comment]
A bad certificate would not cause the issues you describe. What else does the log say?

**Comment by AntoWkill** [comment]
Nothing alse on the log, the certificate is no bad. Is perfectly working.

**Comment by AntoWkill** [comment]
I had also tried to use the last version of novnc, and error is the same.

**Comment by CendioOssman** [comment]
What VNC server are you using?

**Comment by AntoWkill** [comment]
I think vncterm

**Comment by CendioOssman** [comment]
That seems to use libvncserver. Are you connecting directly to it, or do you have a websocket proxy inbetween?

**Comment by AntoWkill** [comment]
Yes there is pveproxy

**Comment by CendioOssman** [comment]
Alright, so I guess the log is from pveproxy?
What does the log from vncterm say?

**Comment by AntoWkill** [comment]
Sep 26 15:55:39 ns3008621 pvedaemon[14800]: <root@pam> end task UPID:ns3008621:00000410:93DE79C3:59CA5C59:vncproxy:100:root@pam: OK
Sep 26 15:55:39 ns3008621 pveproxy[24409]: problem with client 151.22.103.198; ssl3_read_bytes: tlsv1 alert unknown ca
Sep 26 15:55:40 ns3008621 pvedaemon[22464]: <root@pam> starting task UPID:ns3008621:00000413:93DE7AB9:59CA5C5C:vncproxy:100:root@pam:
Sep 26 15:55:40 ns3008621 pvedaemon[1043]: starting vnc proxy UPID:ns3008621:00000413:93DE7AB9:59CA5C5C:vncproxy:100:root@pam:
Sep 26 15:55:41 ns3008621 pveproxy[24409]: problem with client 151.22.103.198; ssl3_read_bytes: tlsv1 alert unknown ca
Sep 26 15:55:41 ns3008621 pvedaemon[22464]: <root@pam> end task UPID:ns3008621:00000413:93DE7AB9:59CA5C5C:vncproxy:100:root@pam: OK
Sep 26 15:56:01 ns3008621 CRON[1076]: (root) CMD (/usr/local/rtm/bin/rtm 44 > /dev/null 2> /dev/null)
Sep 26 15:57:01 ns3008621 CRON[1227]: (root) CMD (/usr/local/rtm/bin/rtm 44 > /dev/null 2> /dev/null)

**Comment by AntoWkill** [comment]
I found the problem but i haven't solution. The VNC Console start again to work IF i force SSLV3 (insicure). So the problem is tls.

**Comment by DirectXMan12** [comment]
hmm... maybe the TLS implementation is mismatched?

**Comment by AntoWkill** [comment]
And how i can check / solve?

**Comment by CendioOssman** [comment]
I'm afraid that would be a question for pveproxy. noVNC isn't involved in the TLS stuff in this case, only the browser and pveproxy. So I would suggest your next step would be to file a bug with pveproxy.

I'm going to close this issue since it doesn't involve noVNC.
