### ISSUE TITLE
Error: ignoring socket not ready

### ISSUE THREAD

**Issue by yugushihuang** [novnc/noVNC#906]
I have installed novnc and tightvnc on my ubuntu 16.04 and try to connect. When I navigate to the URL, the webpage appears but when I click the "Connect" button, it just show "Failed to connect to the server". I am not very familiar with VNC and hope to get some help to set it up right

The messages show below -->
warnings.warn("no 'numpy' module, HyBi protocol will be slower")
WebSocket server settings:

Listen on :6080
Web server. Web root: /home/yxiao/Desktop/noVNC/noVNC
No SSL/TLS support (no cert file)
proxying from :6080 to localhost:5901
Navigate to this URL:

http://ubuntu:6080/vnc.html?host=ubuntu&port=6080
Press Ctrl-C to exit

127.0.0.1: ignoring socket not ready
127.0.0.1 - - [28/Sep/2017 15:03:39] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
127.0.0.1 - - [28/Sep/2017 15:03:39] 127.0.0.1: Path: '/websockify'
127.0.0.1 - - [28/Sep/2017 15:03:39] connecting to: localhost:5901
127.0.0.1: ignoring socket not ready
127.0.0.1: ignoring socket not ready

Thank you very much for your help ahead!

**Comment by CendioOssman** [comment]
Please don't file multiple issues. This will be handled under noVNC/websockify#301.
