### ISSUE TITLE
QEMU RFB Extension not working correctly for Japanese A01/106/109 keyboards

### ISSUE THREAD

**Issue by tpatil** [novnc/noVNC#908]
I have downloaded and installed latest master branch (22nd Sep 2017) to test QEMU RFB Extension (https://github.com/novnc/noVNC/pull/596) using Japanese keyboard.

I have observed that I cannot input "Vertical Line" and "Yen Sign" characters. Nothing is displayed in the noVNC console. All other keys are working properly :).

Refer : http://hp.vector.co.jp/authors/VA003720/lpproj/others/kbdjpn.htm
Section: 106 Keyboard (Japanese A01/OADG106/OADG109/OADG109A)
KeyNumber: 14

Refer to the table: Keyboard Scan Code
and check details of Key number 14.

**Comment by CendioOssman** [comment]
It seems to be correctly encoded in noVNC, so it might be a bug elsewhere.

Which browser are you using?

Could you test this page:

https://dvcs.w3.org/hg/d4e/raw-file/tip/key-event-test.html

What does it say in the DOM3 code column when you press that key?

**Comment by tpatil** [comment]
>>https://dvcs.w3.org/hg/d4e/raw-file/tip/key-event-test.html

I have tested this web page in three different environments.

Test Page Results:

**Environment 1:**

UserAgent: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; Zoom 3.6.0; rv:11.0) like Gecko 

- Shift+Yen Symbol: I see one KeyPress event. In the DOM code column, 
code is - (means undefined), Key '|', Legacy keycode 124
I see in Input Field '|'

- Yen Symbol: I see one KeyPress event. In the DOM code column, 
code is - (means undefined), Key '|', Legacy keycode 92
I see in Input Field \

**Environment 2**
UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

(Note: In this environment, I have installed OpenStack and checked noVNC console. In the noVNC console, I see nothing when I input 'Vertical Line' and 'Yen' characters.

- Shift+Yen Symbol: I see one KeyPress event. In the DOM code column, 
code is 'IntlYen', Key 'Unidentified', Legacy keycode 0
I see in Input Field '' (nothing)

- Yen Symbol: I see one KeyPress event. In the DOM code column,  
code is 'IntlYen', Key 'Unidentified', Legacy keycode 0
I see in Input Field '' (nothing)

**Environment 3**

UserAgent: Mozilla/5.0 (Machintosh; Intel MAC OS X 10_12_5) Verson 10.1.1 Safari 603.2.4

- Shift+Yen Symbol: I see one KeyPress event. In the DOM code column, 
code is 'IntlYen', Key '|', Legacy keycode 124
I see in Input Field '|'


- Yen Symbol: I see one KeyPress event. In the DOM code column, 
code is - (IntlYen), Key '\', Legacy keycode 165
I see in Input Field ¥

**Comment by CendioOssman** [comment]
So IE doesn't seem to support this, but Firefox looks correct. Not sure what Safari is up to. I didn't understand you comment about OpenStack though. Are you running a different version of noVNC there?

Are you sure QEMU supports this key? Does it work with some other client?

**Comment by tpatil** [comment]
>>I didn't understand you comment about OpenStack though. Are you running a different version of noVNC there?

In environment 2 above, I have tried accessing novnc web console (current master branch) used in OpenStack and the result is same as seen using key-event-test.html. I don't see 'Vertical Line' and 'Yen' characters are getting displayed using both ways.

>> Are you sure QEMU supports this key?

Yes, QEMU supports 'Vertical Line', not checked 'Yen' symbol though. 

>>Does it work with some other client?
I will check with other clients and update results soon.

**Comment by samhed** [comment]
any news?

**Comment by DirectXMan12** [comment]
Some versions of OpenStack had manually set the qemu keyboard layout (even when unset in the Nova config file), meaning that they couldn't take advantage of the qemu keyboard extension logic.  That should have been fixed relatively recently, but it's hard to tell without looking at the command line arguments of a running qemu process.

**Comment by tpatil** [comment]
DirectXMan12: I have ensured -k option is not passed to the qemu process.

This patch added code to unset -k option: https://review.openstack.org/#/c/496605.
so basically you need to set following in nova.conf in order to unset -k option.

[vnc]
keymap=''

**Comment by DirectXMan12** [comment]
I'll try and repo locally

**Comment by CendioOssman** [comment]
@DirectXMan12, any luck?

**Comment by CendioOssman** [comment]
Ping @DirectXMan12. Would be nice to triage this.

**Comment by DirectXMan12** [comment]
I don't recall if I ever reproduced this.  Let me pull out my keyboard layout changing commands.

**Comment by DirectXMan12** [comment]
aah, the 106-key layout is proving annoying to fake (the onscreen keyboard I tried didn't handle it properly, either).  Need to figure out how to fake it.

**Comment by CendioOssman** [comment]
@tpatil, how did the testing with other VNC clients go?

**Comment by CendioOssman** [comment]
No response. Closing.
