### ISSUE TITLE
handler exception: need more than 1 value to unpack

### ISSUE THREAD

**Issue by henryliuom** [novnc/noVNC#911]
When i configed noVNC by token,i configed the token.conf file with:
abc123:192.168.132.133:5901
and started noVNC by command:
python ./utils/websockify/websockify.py —web ./ —target-config=token.conf 6080
and open the web by url:
http://192.168.132.130:6080/vnc.html?token=abc123
then i got the "failed to connect to server" error on the web when i clicked the connect button,and noVNC server print error:
handler exception: need more than 1 value to unpack

**Comment by henryliuom** [comment]
I have fix it by modify the token identifier "abc123" to "abcd123",maybe the length of the token identifier limits.

**Comment by CendioOssman** [comment]
I'm afraid this is simple case of syntax error. The format requires a space after the first `:`. I've added a better error message in 61879b175c70970511349ba78e2206cd38b0a44f though.

**Comment by samhed** [comment]
Doesn't look like that commit is pushed upstream @CendioOssman

**Comment by CendioOssman** [comment]
It was a bug (and fix) in websockify, not noVNC, so that's probably why it doesn't show up.

**Comment by samhed** [comment]
Ok: https://github.com/novnc/websockify/commit/61879b175c70970511349ba78e2206cd38b0a44f
