### ISSUE TITLE
Context menu isn't blocked in Firefox

### ISSUE THREAD

**Issue by CendioOssman** [novnc/noVNC#914]
Pressing the context menu key results in a local menu popping up in Firefox.

Tested with Firefox 55 on Linux.

Possibly related to #692.

**Comment by DirectXMan12** [comment]
is this a 1.0 blocker?

**Comment by CendioOssman** [comment]
For the problem itself, I'd say no. But #916 does fix some API warts which I think we want to get rid of before 1.0.

**Comment by CendioOssman** [comment]
Fixed by #916.
