### ISSUE TITLE
novnc stopped working with HTTP authentication in Chromium

### ISSUE THREAD

**Issue by khimaros** [novnc/noVNC#919]
I'm now receiving 401 authentication failures during module load in `vnc_lite.html`.

It seems like the likely root cause is: https://github.com/novnc/noVNC/commit/14ecdc62b461f66ac1ab6f0b6adcb51a40531fcc

Does polyfill work with HTTP basic auth?

**Comment by khimaros** [comment]
Setting `crossorigin="use-credentials"` on the `<script type="module">` tags fixes the issue for me.

**Comment by CendioOssman** [comment]
Well, that seems to be not entirely intended and is apparently changing:

https://github.com/whatwg/html/issues/2557
https://github.com/whatwg/fetch/pull/585

However until this rolls out we probably need that workaround.

The polyfill uses XHR which has different behaviour, so it should work fine.

**Comment by CendioOssman** [comment]
Fixed in bf82644461d95c8621923ffb472f50c1a65f9c33. Thanks for reporting and debugging this.
