### ISSUE TITLE
Implementation of ZLIB-based encodings

### ISSUE THREAD

**Issue by conteit** [novnc/noVNC#926]
I was wondering if, after writing the [Performance Notes](https://github.com/novnc/noVNC/wiki/Performance-notes) page on 21 Mar 2011, you had the chance to retry implementing ZLIB-based encodings.

I've read of [node/pako](https://github.com/nodeca/pako) zlib implementation, whose performance are declared to be near to C ones. Maybe now performance issues can be overcome.

**Comment by CendioOssman** [comment]
We're using pako already, so I think those notes are very much out of date. Performance is really nice these days.

@kanaka, you want put a note on that page or something? :)

**Comment by CendioOssman** [comment]
That page has now been removed since the information wasn't relevant for current versions of noVNC.
