### ISSUE TITLE
Improvement : add virtual trackpad

### ISSUE THREAD

**Issue by unityweb** [novnc/noVNC#93]
Here's the idea : http://imageshack.us/photo/my-images/64/novncidea.png/

Refering to the mobile branch with the new mouse button support.

It would be great to have a virtual trackpad (see image) that is transparent and draggable so users can do more complex actions such as holding the left mouse button while moving finger on trackpad which will for example select a bunch of files in a directory and then right click to do operations on them.

I saw this using VNC tunnel with iSSH (iOS), it really improves the user experience.

**Comment by samhed** [comment]
The image link is dead and the action described in the text is very much possible without any modifications. I think a better step forward towards making noVNC easier to use on mobile is gesture support. Closing this.
