### ISSUE TITLE
wss: IE11 version connecting error

### ISSUE THREAD

**Issue by koreanWeb** [novnc/noVNC#931]
Hello, I'm trying to start a project that uses ssl as vns, but I found it works very well in the Chrome browser. However, IE11 does not work under the same conditions. You are repeatedly connecting with the message "Your browser does not support local cursors." Can we solve it?

**Comment by samhed** [comment]
That message should not affect the possibility to connect. When local cursors aren't supported we should use remote cursors.

Connecting using IE11 works perfectly for me here when using the latest code from the master branch. What version of noVNC are you using?

**Comment by samhed** [comment]
Also, are you sure you aren't getting any other errors in the javascript console? Your issue could be related to your certificate for example.

**Comment by koreanWeb** [comment]
I am using a certificate I created. When launched from a Chrome browser, a shield icon appears at the top of the menu bar. Click on the icon and run it again. Set the encrypt option to false in the setting options. But it does not run in IE11 version. I wonder if it is because of an unsafe certificate. "Mixed Content: The page at 'https: // localhost: 8443 / Preferences / VncMain' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws: //10.15.19.31: 5700 / websockify'. has been blocked; this endpoint should be available over WSS. " It's a message on the chrome console. This is a message from console when running under the same conditions in IE11. "Failed when connecting: Error while connecting (SecurityError)" The novnc version was downloaded yesterday from github.

**Comment by CendioOssman** [comment]
That is your problem there. You cannot use unencrypted a WebSocket when the page was loaded with HTTPS. So edit your settings and enable encryption for your WebSocket server as well.
