### ISSUE TITLE
Keyboard not working in Android (chrome)

### ISSUE THREAD

**Issue by cmargulhano** [novnc/noVNC#932]
The keyboard does not appear in Android (chrome).

**Comment by CendioOssman** [comment]
We need some more details to debug this. Which version of noVNC are you running? Which VNC server? Which Android device? Could you try if it works in Firefox on the same device?

**Comment by cmargulhano** [comment]
I am using the latest version of noVNC and VNC server from MacOS.
The same behavior occurred in Firefox.
I use Android version 7.0.
As you see below, I can not enter the password to enter because the keyboard does not appear.
Thank you for your help.

![screenshot_20171018-091326](https://user-images.githubusercontent.com/11628058/31716345-1e1a3b2c-b3e6-11e7-9056-e52a5a362e8c.png)

**Comment by CendioOssman** [comment]
Have you modified noVNC on some way? There should be a toolbar on the left or right. You need to press the keyboard button on the toolbar for the keyboard to appear.

**Comment by cmargulhano** [comment]
Yes, I'm using it direct from rfb.js:

`
    import RFB from "../../../../assets/3rd-party/noVNC/core/rfb.js";

    connect(host: string, port: string, password: string, path: string) {
        try {
            this.canvas = document.getElementById('noVNC_canvas');
            this.rfb = new RFB({
                'target': this.canvas,
                'encrypt':     false,
                'repeaterID':   '',
                'local_cursor': true,
                'shared':       true,
                'view_only':    this.viewOnly,
                'onNotification':  this.notification,
                'onUpdateState':  this.updateState,
                'onDisconnected': this.disconnected,
                'onXvpInit':    this.xvpInit,
                'onPasswordRequired':  this.passwordRequired,
                'onFBUComplete': this.FBUComplete,
                'onDesktopName': this.updateDesktopName
            });       
            this.rfb.connect(host, port, password, path);
        } catch(e) {
            console.error(e);
        }
        setTimeout(() => {
            if (this.state != 'connected') {
                this.stateUpdated.emit('timeout');        
            }
        }, 15000);
    }
`
How can you programmatically call the method to pop up the keyboard? Is it possible?

**Comment by CendioOssman** [comment]
I'm afraid there is no support for virtual keyboards in the `RFB` object. You'll have to sort that out yourself. Please look at `ui.js` for how it is done there. I'm afraid there is no clean way to handle this.
