### ISSUE TITLE
Bug in Keyboard

### ISSUE THREAD

**Issue by cmargulhano** [novnc/noVNC#936]
In actual code of repository the keyboard doesn't work any more.

Old code that works:
...
'focusContainer': document,
...

```
  this._keyboard = new Keyboard({target: this._focusContainer,
                                   onKeyEvent: this._handleKeyEvent.bind(this)});

```

New code that I believe is not working:

```
this._keyboard = new Keyboard({target: this._target,
                                   onKeyEvent: this._handleKeyEvent.bind(this)});
```

Could you check out?

**Comment by CendioOssman** [comment]
`focusContainer` has been removed. The focus is now expected to be set on the canvas object. However that might be easy to forget, so we can probably add some code that makes sure of that. Give me a sec...

**Comment by CendioOssman** [comment]
Should be fixed in 458086177c97761392359222a3be6db8ad1eae78. Please remove `focusContainer` from your caller, update your tree and try again.

**Comment by samhed** [comment]
Is your problem fixed now @cmargulhano ?

**Comment by cmargulhano** [comment]
Yeap, but I do my own implementation . Thanks
