### ISSUE TITLE
unable to connect to vncserver over VPN

### ISSUE THREAD

**Issue by samgoud** [novnc/noVNC#937]
Hi,
I have used below command to start a mini-webserver and the WebSockets proxy (websockify) 
/noVNC-master/utils/launch.sh  --vnc localhost:5940 --listen 6085
When I try to open the output url in a browser, I always see a "Connecting..." message. The state never changes to 'connected'.
This problem I am only seeing in home network when I connect to office server over wecm vpn. In office network I am able to open the link without issues. Strangely some of my collegues are able to open the same link in their home network using the same vpn client. 
Infact I started seeing this problem starting last week. Prior to that I was able to open the links in my home network over the vpn. 

The logs at server:

```
Warning: could not find self.pem
Using local websockify at /noVNC-master/utils/websockify/run
Starting webserver and WebSockets proxy on port 6085
WebSocket server settings:
  - Listen on :6085
  - Web server. Web root: /noVNC-master
  - No SSL/TLS support (no cert file)
  - proxying from :6085 to localhost:5940

Navigate to this URL:

    http://xxx.yyy.zzz.com:6085/vnc.html?host=xxx.yyy.zzz.com&port=6085

Press Ctrl-C to exit

9.xx.xxx.xxx - - [19/Oct/2017 05:18:02] 9.77.211.240: Plain non-SSL (ws://) WebSocket connection
9.xx.xxx.xxx - - [19/Oct/2017 05:18:02] 9.77.211.240: Path: '/websockify'
9.xx.xxx.xxx- - [19/Oct/2017 05:18:02] connecting to: localhost:5940
```

I added 'logging=debug' in browser and did a F12, here are the console output:

```
This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
:6085/core/util/browsers.js:32 Data URI scheme cursor supported
:6085/core/rfb.js:233 Using native WebSockets, render mode: canvas rendering
:6085/core/rfb.js:375 connecting to ws://edagl12h.pok.ibm.com:6085/websockify
:6085/core/websock.js:224 Server choose sub-protocol: binary
:6085/core/rfb.js:716 Server ProtocolVersion: 003.008
```

Using other vnc clients (ultravnc, tightvnc), I am able to connect to the same vnc server without issues in home network over same vpn.

**Comment by DirectXMan12** [comment]
Hmm... looks like it's not getting past protocol negotiation.  Can you enable debug-level logging (looks like we're just getting INFO) as well?  You should see `Sent ProtocolVersion: 003.008` as well.

**Comment by samgoud** [comment]
Hi, 
Just realized that a advanced secure gateway was installed on our machines by our office recently which was blocking these connection requests over vpn. Disabling the gateway made things work.
I am closing this.

Thanks for the response
