### ISSUE TITLE
ubuntu 17.10 x11vnc + novnc

### ISSUE THREAD

**Issue by ubuntushop** [novnc/noVNC#938]
Trying to get this working but have issues.
Ubuntu 17.10 (user can log in with x11)
No Xauthority files exists.
start x11vnc must be separate:
x11vnc -forever -xkb -noxrecord -noxfixes -noxdamage -display :0 -auth /run/user/121/gdm/Xauthority -shared  -o /var/log/x11vnc.log &
and start novnc:
/usr/share/novnc/utils/launch.sh --vnc localhost:5900 &

I get a nice gdm3 login screen, but if want to login a user, i get black screen.
On the pc with the novnc, the user is logged in if I try to log in on remote machine with browser.
is this a gnome-session error?

**Comment by samhed** [comment]
Does your setup work with other VNC clients?

If noVNC properly displays a gdm login screen, I doubt your issue is related to noVNC. You should be looking for errors regarding session startup on your server, check journalctl.

Please re-open if I misunderstood you.

**Comment by CendioOssman** [comment]
I'm afraid what you are trying to do isn't possible. GDM starts a new X11 server for each user, but x11vnc will continue displaying the GDM session.

I would suggest looking at a standalone VNC server such as Xvnc provided by TurboVNC or TigerVNC.

**Comment by ubuntushop** [comment]
Seems correct. With lightdm all is working very good. Just log the user in with ubuntu-xorg.
With gdm, i get a black scrren on the client, however on de novnc machine, the user is logged in.
Any workaround for gdm?

**Comment by CendioOssman** [comment]
Probably not, but I'm not an expert on GDM. You'll have to have a look at its documentation and configuration.
