### ISSUE TITLE
Error:1006 using ultravnc repeater

### ISSUE THREAD

**Issue by Antony007** [novnc/noVNC#939]
I am trying to a vnc server using ultravnc repeater. When I try to connect to the server I recieve Server disconnected (code: 1006) error. I am able to connect to the server using ssvncviewer. Is there any setup needed on the server running repeater.

**Comment by Antony007** [comment]
I did some fiddling and now I am recieving the following error. ParseHostAndPort error

**Comment by brijeshtiwai00** [comment]
Antony007, I am also getting the same issue...

**Comment by samhed** [comment]
You guys need to provide more information here. "ParseHostAndPort" is not an error that noVNC sends, I'm assuming it is logged by the ultravnc repeater?

How far are you getting in noVNC? What error is noVNC displaying? Are you seeing any additional information in the JavaScript console?

**Comment by CendioOssman** [comment]
And more importantly, have you configured the repeater ID in the noVNC settings? Unfortunately it is a bit weird right now that you need to include a `ID:` prefix, but the plan is to fix that before the next release so you just specify the actual ID.

**Comment by brijeshtiwai00** [comment]
@CendioOssman I tried prefixing the repeater ID with 'ID:' but still getting the same error.

**Comment by CendioOssman** [comment]
Hang on, it looks like you are trying to specify the ultravnc repeater as the WebSocket host? That won't work. You need to have something that understands WebSockets there. Your repeater can be behind the WebSocket proxy, not in front of it.

**Comment by brijeshtiwai00** [comment]
@CendioOssman I am running x11vnc on the destination machine and ultravnc repeater on the server. Could you guide me on how to setup WebSocket proxy on the server.

**Comment by CendioOssman** [comment]
The easiest is probably using our convenience script. Please see the quick start part of our README:

https://github.com/novnc/noVNC#quick-start
