### ISSUE TITLE
Completely remove/hide control bar

### ISSUE THREAD

**Issue by rkarlsba** [novnc/noVNC#941]
Hi

I've looked around quite a bit, but I can't find a way to completely remove (or hide) the control bar. The intended use is to allow remote viewing of infoscreens around on campus with x11vnc in view only. This works, but I don't want that control bar (it has no use in view only, and it's annoying). Earlier one of our web developers helped me removing by changing the html code, and although this works, it's ugly. Is there a way to do this properly in a config file or a variable in the url?

thanks

roy

**Comment by samhed** [comment]
No, there is no other way to do this currently. 

vnc.html + ui.js and vnc_lite.html are example applications. If these does not fit your needs, our intention is that integrators of noVNC should take inspiration and tips from these examples and create their own application.

In the past couple of months the API between the inner modules and the UI has been a bit unstable. We are working on releasing noVNC 1.0 and the plan is to have an API that we are satisfied with for a long time. This will make it easier for projects that are using our modules but have their own interface/html.

**Comment by CendioOssman** [comment]
As a tip though, try to hide things using CSS if you can. That's usually more resilient to changes from our end. :)

E.g.

```CSS
#noVNC_control_bar {
  display: none;
}
```

**Comment by rkarlsba** [comment]
Thanks.

I tried to add this to app/styles/auto.css, but I can't see any difference. Have tried clear cache etc, but no change.

**Comment by CendioOssman** [comment]
Ah. My suggestion was for vnc.html, not vnc_auto.html (now called vnc_lite.html). Use `#noVNC_status_bar` instead.
