### ISSUE TITLE
No index page

### ISSUE THREAD

**Issue by rnveach** [novnc/noVNC#942]
noVNC is missing an index page and thus if you don't go directly to `http://host:port/vnc.html` and instead go to `http://rveach.no-ip.org:6080` by default you get a folder listing of everything in the folder which seems like a small security issue.

IMO, either `vnc.html` should be renamed to `index.html` or `index.html` should automatically redirect you to `vnc.html` or should be some type of message page if the `vnc.html` should remain hidden.

**Comment by DirectXMan12** [comment]
We expect that for production uses, you're either serving vnc.html off of a proper webserver, or are using websockify directly with directory listing turned off.  You should not be using launch.sh, and should generally not have directory listings turned on on your production web server.

**Comment by codesiddhant** [comment]
How did i use noVNC in my production webserver please explain 
How I can implement it using nginx or Apache Web server

I searched almost everywhere but I didn't found any solution for turn of directory browsing
