### ISSUE TITLE
Copy paste in noVNC bypassing clipboard

### ISSUE THREAD

**Issue by joynexa** [novnc/noVNC#943]
We have used noVNC to view a remote desktop within an iframe in a browser window.
Copy and paste works well within the  iframe using Ctrl+C and Ctrl+V.
However copying from within the iframe and pasting outside and vice versa, works only through the clipboard feature.(Pasting into the noVNC clipboard and copying from there)
Can the same functionality also be implemented with simple copy paste commands(Ctrl+C,Ctrl+V) bypassing the  noVNC clipboard?
Could this be incorporated into the vnc_lite version..?

Thanks

**Comment by samhed** [comment]
We are very limited by security restrictions in the browsers. See #509

**Comment by DirectXMan12** [comment]
(closing as duplicate)
