### ISSUE TITLE
noVNC Integration: Error Writing Into A Document from Async-Loaded External Script

### ISSUE THREAD

**Issue by JeffLeFevre** [novnc/noVNC#945]
The error:
```
error-handler.js:48 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
handleError @ error-handler.js:48
(anonymous) @ error-handler.js:54
promise.js:251 Uncaught TypeError: Cannot read property 'Promise' of undefined
    at promise.js:251
    at promise.js:255
(anonymous) @ promise.js:251
(anonymous) @ promise.js:255
```
   
My HTML:
```
<script src="{{ STATIC_URL }}js/noVNC/vendor/browser-es-module-loader/dist/babel-browser-build.js" type="module"></script>
<script src="{{ STATIC_URL }}js/noVNC/vendor/browser-es-module-loader/dist/babel-worker.js" type="module"></script>
<script src="{{ STATIC_URL }}js/noVNC/vendor/browser-es-module-loader/dist/browser-es-module-loader.js" type="module"></script>
<script src="{{ STATIC_URL }}js/noVNC/core/base64.js" type="module"></script>
<script src="{{ STATIC_URL }}js/noVNC/core/des.js" type="module"></script>
<script src="{{ STATIC_URL }}js/noVNC/core/display.js" type="module"></script>
<script src="{{ STATIC_URL }}js/noVNC/core/encodings.js" type="module"></script>
<script src="{{ STATIC_URL }}js/noVNC/core/inflator.js" type="module"></script>
<script src="{{ STATIC_URL }}js/noVNC/core/rfb.js" type="module"></script>
<script src="{{ STATIC_URL }}js/noVNC/core/websock.js" type="module"></script>
```
   
All noVNC files part of the repository can be found with directory structure intact at `{{ STATIC_URL }}js/noVNC/`
   
I've been beating my head against a wall, Googling, tried the IRC, can't really seem to find answers. If more information is needed, I'm happy to provide everything I can.

Thank you.

**Comment by DirectXMan12** [comment]
So first, if you're running noVNC in production, we recommend "compiling" away the module system.  
We recently restructured noVNC to use ES6 modules, but most browsers don't support loading ES6 modules yet, so for dev work we use a polyfill.

For production, we recommend against using the polyfill, as it effectively calls Babel in the browser every time (with some caching for efficiency).  You should use `utils/use_require.js --as $ONE_OF_THE_MODULE_FORMATS` (you can see the different output formats by passing `--help`, but we support AMD, CommonJS, SystemJS, and UMD).  We'll also be publishing the CommonJS version on NPM as soon as we resolve the last issue before v1.0.0.

**Comment by JeffLeFevre** [comment]
Thank you very much for your quick response.
I'm not typically a front-end developer, so please forgive my naivete. I assume the output option I choose would be based on which library I use, i.e. React, CommonJS, SystemJS? So I'll need to utilize one of those in order to integrate the newest noVNC?

**Comment by DirectXMan12** [comment]
> React, CommonJS, SystemJS? So I'll need to utilize one of those in order to integrate the newest noVNC?

Unlike React, CommonJS and SystemJS are just module systems, not full frameworks.  However, if you don't want any module loader at all, pass the `--as umd`, which just throws it all into one giant bundle without anything special (more or less), and you can just use a `<script src="path/to/the/bundle.js"></script>` like above.

If you already have some other system in place that deals with ES6 modules (e.g. Babel, TypeScript, etc), you can just import the modules as normal.  Shortly in the future, you won't have to bother with this at all any more, because ES6 modules are standards track JS (they're just not fully implemented yet in most browsers).

In any case, using them with the module loader polyfill is not recommended.

**Comment by JeffLeFevre** [comment]
Awesome, thank you very much for your help. I'll go ahead and close this out.
