### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of null app/ui.js:840:64

### ISSUE THREAD

**Issue by KartikeyaShukla** [novnc/noVNC#946]
Error occurs on connecting to vnc..reproducible : always

**Comment by CendioOssman** [comment]
That looks like your `vnc.html` has become corrupt somehow. Could you verify that none of your files have been modified?

**Comment by KartikeyaShukla** [comment]
I checked vnc.html... Exactly the same as in the master branch on GitHub. Git clone was used to download the project. FYI, an older version is working fine (which version exactly ...need to check) . I kept it as a backup before upgrading to the latest

**Comment by samhed** [comment]
It doesn't look like line 840 in ui.js calls "type" in the code on master. Are you sure you are running the latest version?

Anyway, it probably fails in `updateSetting()`, `saveSetting()` or `getSetting()`. What is the full error shown in the javascript console? Can you check which element it can't find?

**Comment by KartikeyaShukla** [comment]
attached screenshot of error
![novncerror](https://user-images.githubusercontent.com/8774746/32316055-85ab26f4-bfa6-11e7-96d2-21c1cfbac751.jpg)

**Comment by miniskipper** [comment]
In vnc.html replace
`noVNC_setting_view_clip`
by 
`noVNC_setting_clip`

**Comment by miniskipper** [comment]
Also had this error. Deleted the local browser-cache and it worked again.

**Comment by KartikeyaShukla** [comment]
works perfectly fine in incognito mode...didnt try the browser cache clear solution since i want certain other stuff to be retained in the browser (unless there is a method to delete site specific storage in chromium, tried google didn't get a solution..)

**Comment by CendioOssman** [comment]
Great, so this is simply a browser cache issue then. I'll go ahead and close it.

**Comment by KartikeyaShukla** [comment]
sure, the issue can be closed...but is it OK that the client side cache is required to be cleared every time the server side version of VNC is updated (just asking)..is it not expected that the client side code work irrespective of the browsers past state (not aware of the technical background here..so just asking)

**Comment by CendioOssman** [comment]
This is unfortunately a general problem with browsers that I've yet to see a good solution to. ES6 modules will make this worse, so perhaps the powers that be will come up with something soon.

**Comment by DirectXMan12** [comment]
> the server side version of VNC is updated (just asking)

If you're running a proper production web server, you can have the server set cache control headers (e-tags, etc).  The browsers will honor those.  If you're not running a production web server, please do.
