### ISSUE TITLE
graphic glitches on ios 9

### ISSUE THREAD

**Issue by CendioOssman** [novnc/noVNC#948]
Lots of random glitches on ios 9. Can't see it on newer ios. I'm fairly sure this has worked fine before, but I don't know what has regressed yet.

**Comment by CendioOssman** [comment]
Gah! Remote debugging doesn't work properly anymore for this old iOS. Perhaps it is time to drop support?

**Comment by samhed** [comment]
If remote debugging doesn't work, I'd say its quite difficult to maintain it..

**Comment by CendioOssman** [comment]
Indeed. Apple claims iOS 9 is 9% of all iOS users, and caniuse.com claims it is 0.35% of all browsers. Perhaps we should just drop support?

@kanaka, @DirectXMan12, any thoughts?

**Comment by DirectXMan12** [comment]
that's probably fine.  That's a pretty small amount of people.

**Comment by kanaka** [comment]
I have no problem with that. My intuition is that mobile devices are a less common use case for noVNC. Also, old iOS version market share tends to drop off quickly so it's probably not going to stay at 9% of iOS users for long.

Does Cendio have browser ThinLinc usage data? Or perhaps @DirectXMan12 knows if OpenStack tracks browser market share in some way. It would be great to have a rough idea of what sort of browsers are being used in the real world with noVNC. I'm sure this sort of deprecate or not question will keep coming up.

**Comment by samhed** [comment]
We do not have browser usage data for ThinLinc I'm afraid.

**Comment by samhed** [comment]
So close as won't fix and drop iOS 9 support?

**Comment by CendioOssman** [comment]
I guess so.
