### ISSUE TITLE
Script type module not working in chrome.

### ISSUE THREAD

**Issue by ProTechnologist** [novnc/noVNC#949]
In my streaming setup, NoVNC works in Edge & Firefox version 56.0.1 (64-bit) perfectly fine but in Chrome Version 62.0.3202.75 (Official Build) (64-bit), I'm getting this exception in browser console and NoVNC stuck in loading state.

`Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec. File: ui.js:1`

With verbose logging on, I got following additional information:
`[Violation] 'setTimeout' handler took 99ms - FILE: onloadwff.js:62`

In vnc.html file, following line is throwing the exception:

`<script src="app/ui.js" type="module"></script>`

I've tried changing this script line to be the following but it didn't helped. (removed quotes from type=module)

`<script src="app/ui.js" type=module></script>`

In chrome, I also tried enabling the _Experimental Web Platform features_ but it didn't helped either.

Is there anything else I should look into to address this issue?

**Comment by samhed** [comment]
That's wierd, ui.js mime-type is correct. And I can't reproduce your issue. A quick google search:

https://stackoverflow.com/questions/46138375/trouble-with-es6-modules

And especially this response:

> Yeah, I fixed the MIME issue which was due to me messing with httpd.conf a few months/years ago. Everything is working now. Thanks for the answer.

Maybe that's a hint for you.

**Comment by CendioOssman** [comment]
Indeed. I'm afraid this is a problem in your web server, not in noVNC. So make sure your server is server our files correctly and things will work fine for you.

**Comment by ProTechnologist** [comment]
@samhed It's possible that it's not related to noVNC but then it's definitely going to be a WebSockify issue. Since WebSockify is hosting noVNC thus exposing PC in browser so no web-server is involved like Apache / IIS so I don't have files like httpd.conf or web.config in case of IIS.

Here is the screenshot of it running with SSL. https://www.screencast.com/t/H3SOjCWEn
The problem exists only in Chrome.

**Comment by CendioOssman** [comment]
Please file an issue in the websockify tracker for that. However first please check that the mime databases are properly installed on your system. websockify lets the system identify file types, and the system uses those databases.

**Comment by ProTechnologist** [comment]
@CendioOssman Sure thanks. Let me first check the mime database on my web server and then I'll open a ticket there.

**Comment by unni1** [comment]
I was investigating a similar issue and came across this post. 

In my case, webutils.js and rfb.js were not loading as expected. I noticed 2 differences compared to other .js files loaded from novnc.
1. Content-type of these 2 were set to text/plain instead of application/javascript.
2. Authentication cookie was not present in the request header.
Only Chrome 61/62 had this issue. Firefox 56 and IE 11 loaded fine. I took the files from the commit tagged as v1.0.0-testing.2.

I noticed that in the latest master, the relevant entry was

<script type="module" crossorigin="anonymous">
// Load supporting scripts
import * as WebUtil from './app/webutil.js';
import RFB from './core/rfb.js';

The commit I took didnt have the crossorigin="anonymous" part. Once I added that, its working fine.

**Comment by DirectXMan12** [comment]
since it was fixed with adding `crossorigin`, I have a suspicion that Chome is mucking with the content-type because it didn't fit within the cross-origin content policy (so setting the content-type as `text/plain` warns the consumer and prevents the rest of the browser from treating it as JS).  That's just a suspicion, though.

**Comment by prinonis** [comment]
The crossorigin is not fixing this issue for us unfortunately.
We have two types of systems one SLES 11 and another SLES12.
On the SLES 11 mimetypes.types_map['.js'] resolves to 'text/x-js' while on SLES 12 it resolves to 'application/javascript'

So the noVNC websockify proxy on SLES11 hosts does not work on Chrome (works on Firefox). And on SLES12 hosts it work on either browser.

So is the issue on Websockify or noVNC client code ?

**Comment by CendioOssman** [comment]
I'm afraid it's neither. The problem is with your operating system as it is that which does the type identification. So please file a bug with SUSE.

**Comment by DirectXMan12** [comment]
> On the SLES 11 mimetypes.types_map['.js'] resolves to 'text/x-js'

Woah, that's pretty wrong

> So is the issue on Websockify or noVNC client code ?

FWIW, having websockify serve your web content in production is, IMO, a bit of an antipattern.  You should use a proper webserver to serve the web content, and just let websockify handle the websocket.  With a proper webserver, you can generally configure stuff like mimetypes (although they generally get it correct OOTB).

**Comment by sangbinlee** [comment]
----
Chrome version 75.0.3770.80 (64bit)
win 10 pro 64bit
----
novnc is working in ms edge
but not in chrome
---- 
chrome console error is
ui.js:1 ---> Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by sangbinlee** [comment]
i don't know why  another web browser msie 11 and ms edge works fine in my
web server.


2019년 6월 7일 (금) 오후 9:02, Samuel Mannehed <notifications@github.com>님이 작성:

**Comment by letanloc1998** [comment]
I have same problem
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by samhed** [comment]
I'll say it one more time:

I'm afraid this is a problem in your web server, not in noVNC. So make sure your server is serving our files correctly and things will work fine for you.

I'm locking this conversation now.
