### ISSUE TITLE
hang on "Connecting..." Thank you

### ISSUE THREAD

**Issue by guotong1988** [novnc/noVNC#954]
```
[root@byg612sv001 noVNC]# ./utils/launch.sh
Warning: could not find self.pem
Using local websockify at /opt/noVNC/utils/websockify/run
Starting webserver and WebSockets proxy on port 6080
WebSocket server settings:
  - Listen on :6080
  - Web server. Web root: /opt/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to localhost:5900


Navigate to this URL:

    http://byg612sv001:6080/vnc.html?host=byg612sv001&port=6080

Press Ctrl-C to exit


10.100.39.132 - - [17/Nov/2017 16:51:30] 10.100.39.132: Plain non-SSL (ws://) WebSocket connection
10.100.39.132 - - [17/Nov/2017 16:51:30] 10.100.39.132: Path: '/websockify'
10.100.39.132 - - [17/Nov/2017 16:51:30] connecting to: localhost:5900

```

**Comment by guotong1988** [comment]
![_20171117170705](https://user-images.githubusercontent.com/4702353/32940086-9b88d080-cbbc-11e7-9b16-0a0d1345f2ed.jpg)

**Comment by CendioOssman** [comment]
Could you check what the console in the browser says?

**Comment by guotong1988** [comment]
OK, how to check it?

**Comment by CendioOssman** [comment]
Press F12 and click `Console`.

**Comment by toschneck** [comment]
I got a similar problem wenn host is offline see  https://github.com/ConSol/docker-headless-vnc-container/issues/50

**Comment by guotong1988** [comment]
![_20171120090903](https://user-images.githubusercontent.com/4702353/32998048-9486b4b0-cdd2-11e7-8dfa-c6a6d6a0e35b.jpg)

![_20171120090930](https://user-images.githubusercontent.com/4702353/32998045-8e8a0184-cdd2-11e7-8271-886bdc71a532.jpg)

**Comment by CendioOssman** [comment]
Thank you. Unfortunately that didn't tell us much. Could you open the advanced settings in noVNC and change the logging to "debug"? Please try again and attach the console output after that.

**Comment by guotong1988** [comment]
Thank you.
Sure.
How to change it to "debug" mode?

**Comment by samhed** [comment]
As @CendioOssman said; open the settings in the noVNC UI, click advanced and then changed "Logging" from "warn" to "debug".

**Comment by guotong1988** [comment]
![_20171122103912](https://user-images.githubusercontent.com/4702353/33107272-6b4f3a7c-cf71-11e7-8331-b3644d449ec9.jpg)

**Comment by CendioOssman** [comment]
I'm afraid everything looks correct from our end and it's simply your VNC server that isn't responding properly. Have you checked the logs for the VNC server?

**Comment by guotong1988** [comment]
How to check the logs?

**Comment by CendioOssman** [comment]
That depends on your VNC server so I'm afraid we cannot really help you there. Please check with the vendor or project you got the VNC server from.

**Comment by samhed** [comment]
Closing due to no response.

**Comment by danielsmd** [comment]
I'm trying to get noVNC to run on Armbian, and I have the same issue. No error messages...just connecting .
![timeout](https://user-images.githubusercontent.com/23436369/94343402-372f6480-0018-11eb-9206-5aaf82b10a76.PNG)
After a few seconds, Chrome Console prints: rfb.js:811 Failed when connecting: Connection closed (code: 1000, reason: Target closed).
