### ISSUE TITLE
local scaling does not work on first connect

### ISSUE THREAD

**Issue by VidJa** [novnc/noVNC#959]
When I connect to my server for the first time in a session, the screen is not scaled correctly to fit the browser window if local scaling is turned on. It rescales when deselecting/reselecting local scaling or resizing the browser window or going to full screen.

Browser FF52 ESR on Win7, FF57 on MacOS/Linux)

noVNC:
commit 2efa8a5a7cca8e617b45d2ac5de0c4de18413964
Merge: 4d62072 ceea51f
Author: Pierre Ossman <ossman@cendio.se>
Date:   Thu Nov 23 15:22:50 2017 +0100

**Comment by CendioOssman** [comment]
I'm afraid I cannot reproduce this. I tried using FF57 with Linux and it scaled properly on connect.

Have you made any local modifications to noVNC?

**Comment by vdejager** [comment]
You are right. It works with FF57 with Linux/MacOS. FF52 ESR on Win7 does not. btw, Edge mobile does work too.

I'm running the latest master checkout of noVNC

**Comment by samhed** [comment]
It works perfectly for me with FF52 ESR on Linux.

**Comment by samhed** [comment]
I also went and tested a Windows 7 machine and installed FF52 ESR on it, works just fine.

**Comment by samhed** [comment]
So.. are you still seeing the problem? I find this very wierd

**Comment by samhed** [comment]
Well, @vdejager also saw the same problem on the same combination of platform and browser.. Could it be some sort of non-default configuration flag that you two are using?

**Comment by CendioOssman** [comment]
Or a cache issue? Could you try clearing the browser cache?

**Comment by VidJa** [comment]
I guess its a local issue. Clearing the browser cache does not resolve the issue.
The version on Win7 is a modified version of 52.5. So non standard, but I  could not find relevant modified flags in about:config.
I guess you can close this issue.

**Comment by samhed** [comment]
Feel free to reopen if you make any further findings.
