### ISSUE TITLE
better documentation on npmjs.com

### ISSUE THREAD

**Issue by CendioOssman** [novnc/noVNC#961]
This comment from #910 was overlooked:

> Can we modify the info shown at npmjs.com? It currently shows stuff relevant for the app, not the library.

**Comment by DirectXMan12** [comment]
From a quick googling, the answer may actually be "no".  I can't seem to find a way to override which readme is used for npm publishing.  We could *maybe* do some trickery on before-publish to rename files (e.g. have a `README-LIBRARY.md` and rename that to `README.md` just before publish)...

**Comment by CendioOssman** [comment]
Annoying. But I guess we need a section in the normal README then?

**Comment by DirectXMan12** [comment]
Yeah, I'll be out at a conference next week, but I can try to write one when I get back, unless you'd prefer to .

**Comment by CendioOssman** [comment]
I've merged #971 now. I'm pretty content with it for now. Anything else we need before closing this issue?

**Comment by samhed** [comment]
LGTM
