### ISSUE TITLE
Windows Black Screen

### ISSUE THREAD

**Issue by ScottJEhas** [novnc/noVNC#962]
I am not receiving any display input when reverse proxying to Windows based virtual machines.  The linux based virtual machines have no problems connecting, and displaying the proper input.  When I move the cursor on the Windows based machine I do see it move on the backend.

No luck with Google this problem.  Majority of the same posts state problems with truecolor, and this is an legacy version flag for rfb.js.  Any help would be appreciated. 

<img width="1127" alt="screen shot 2017-11-27 at 4 10 20 pm" src="https://user-images.githubusercontent.com/2292626/33289489-b97b6840-d38d-11e7-8ea0-e80d81286467.png">

**Comment by samhed** [comment]
are you getting an image with other VNC clients?

**Comment by ScottJEhas** [comment]
I am able to get an image with VNC Viewer on MAC OSX with the same proxy.   Any flags that are required to make this work for Windows based systems?

**Comment by samhed** [comment]
Seeing any errors in the browser console? Any errors from the VNC server?

**Comment by samhed** [comment]
Closing due to no response
