### ISSUE TITLE
noVNC encountered an error TypeError:this.tile is null

### ISSUE THREAD

**Issue by feifeixj** [novnc/noVNC#965]
I cloned the tree of master and run noVNC by command ./utils/launch.sh --vnc 172.17.0.2:5901
and the ip=172.17.0.2 is the host of ubuntu16.04 and it has installed  vnc4server and is listening on port 5901 and the noVNC has cloned on other host which system is centos7 .

However when I open the Firefox and use the right password,the page shows a warnging 

noVNC encountered an error:

TypeError: this._tile is null
http://192.168.20.50:6080/vendor/browser-es-module-loader/dist/browser-es-module-loader.js line 1408 > eval:414:25
.execute/Display.prototype.startTile@http://192.168.20.50:6080/core/display.js!transpiled:414:25
.execute/RFB.encodingHandlers.HEXTILE@http://192.168.20.50:6080/core/rfb.js!transpiled:2032:29
.execute/RFB.prototype._framebufferUpdate@http://192.168.20.50:6080/core/rfb.js!transpiled:1468:31
.execute/RFB.prototype._normal_msg@http://192.168.20.50:6080/core/rfb.js!transpiled:1354:39
.execute/RFB.prototype._handle_message@http://192.168.20.50:6080/core/rfb.js!transpiled:632:38
.execute/Websock.prototype._recv_message@http://192.168.20.50:6080/core/websock.js!transpiled:322:25

**Comment by CendioOssman** [comment]
Is this #963?

**Comment by samhed** [comment]
@zqwlai who saw the same problem in #969 what VNC server are you using?

**Comment by OwenOKI** [comment]
For those that need a fix for this RIGHT NOW, I found a code modification which appears to resolve the issue (only did 2 minutes of testing before writing this comment)

Modify core/display.js
Modify the function "startTile" you will find at line 388
At line 396 add the following code block:
```
if (this._tile == null) {
    this._tile = this._drawCtx.createImageData(width, height);
}
```

Yes, this is exactly the same code from the else block 3 lines above.  

After making this modification, run the start_util again, and the error goes away.  

I make no claim to understand the side effects of this change other than preventing the _tile == null problem, and allowing my noVNC to connect and draw the screen.

**Comment by CendioOssman** [comment]
Should be fixed now.
