### ISSUE TITLE
Unable to get token

### ISSUE THREAD

**Issue by tpatil** [novnc/noVNC#967]
Environment:
noVNC=v1.0.0-testing.2 
websockify=0.8.0

I'm using noVNC v1.0.0 in OpenStack nova environment to test QEMU RFB Extension (#596) using Japanese keyboard.

I tried to access vnc console using url "http://192.168.252.14:6080/vnc_auto.html?token=8cb819e5-5882-41c9-9ab3-17609160e6d0&title=nova(2ed16227-73a6-457a-8bc2-57ca2a41431c)", but in websockify proxy request handler [1], I don't get the token as query parameter as well as it is not set in cookie.

If I use noVNC 0.6.0, I get token as expected.

So I think there is some issue with passing token to websockify.

[1] : https://github.com/openstack/nova/blob/master/nova/console/websocketproxy.py#L122

**Comment by samhed** [comment]
Yes, the `token` setting was removed from master a year ago. It was merely an alternative way to modify path, you should use `path` instead. This should work for you:

    http://192.168.252.14:6080/vnc_auto.html?path=websockify%26token%3D8cb819e5-5882-41c9-9ab3-17609160e6d0&title=nova(2ed16227-73a6-457a-8bc2-57ca2a41431c)

**Comment by tpatil** [comment]
I have confirmed it works for me.
Thank you.

**Comment by samhed** [comment]
Good to hear!
