### ISSUE TITLE
Some question about a wiki?

### ISSUE THREAD

**Issue by guotong1988** [novnc/noVNC#968]
https://github.com/novnc/noVNC/wiki/Fixing-the-clipboard-under-linux

where  and how to install `autocutsel`? 
and where is the `.vnc/xstartup` file?

Thank you.

**Comment by samhed** [comment]
I have never had to use `autocutsel` during my 5 years here. I assumed that the clipboard wiki page was obsolete. Could you describe the issue you are trying to fix? Which VNC server are you using?

You will find .vnc/xstartup your home directory.

**Comment by CendioOssman** [comment]
Yeah, that page has not very much to do with noVNC and it lacks lots of details. Any objections to nuking it?

**Comment by samhed** [comment]
I'm fine with that

**Comment by CendioOssman** [comment]
Alright, nuked.

@guotong1988, if you're having issues with the clipboard in the session then please first ask the vendor of your VNC server.
