### ISSUE TITLE
creating a browserify bundle leaves .js files around

### ISSUE THREAD

**Issue by CendioOssman** [novnc/noVNC#970]
The easiest way to distribute the noVNC application is by doing:

```
$ utils/use_require.js  --with-app --as commonjs
```

However that leaves you with a `build/` directory with lots of extra crap in it, namely all the `.js` files that were bundled up in to `app.js`.

We should clean those files so people can easily just take the entire `build/` directory.

**Comment by DirectXMan12** [comment]
It'd be nice, but I'm not overly concerned.  It's mostly that the `--with-app` is a separate stage of the build, and the build script infra is just targeted at additive operations.

**Comment by shrihari-b** [comment]
I am new to JS. I tried utils/use_require.js --with-app --as umd . It's creating a lot of files in lib. Which all do I include?
I can see :
```
        import * as WebUtil from './app/webutil.js';
        import RFB from './core/rfb.js';

``` 
in the html but I don't see webutil.js in lib folder. Where do I add it from?
