### ISSUE TITLE
How to open bash shell in noVNC from cloud9 ide on Android?

### ISSUE THREAD

**Issue by survivor999** [novnc/noVNC#972]
HI, 
  Just thought I would attempt to see if anyone knows if there is another way to get a bash shell other than right clicking
in the browser while using No VNC with, via, the cloud 9  ide?  Android browsers do not allow or support
right clicking from any browsers.

**Comment by samhed** [comment]
If the cloud 9 ide is using the full UI from `vnc.html` and `ui.js` you can switch mouse buttons from the toolbar.

**Comment by samhed** [comment]
Anyway, this question should be directed towards cloud 9, not noVNC.
