### ISSUE TITLE
Local cursor not working

### ISSUE THREAD

**Issue by perhallstroem** [novnc/noVNC#975]
Somewhat related to https://github.com/novnc/noVNC/issues/974

It appears support for local cursor was removed some time back (https://github.com/novnc/noVNC/commit/8d1f0a3de8630300c6ffb87e98b8cb1d438f0f00). On high-latency connections, having only the remote cursor is problematic. The local cursor, for all its potential problems, should definitely be reinstated. I'm fine with it being disabled by default, but not having the option to enable it seems like a serious regression to us.

Edited to add: from reading the above commit my vague understanding is that the idea is to auto-enable the local cursor for browsers that support it. However, in our experience the feature detection does not work in Windows. On Macs, it works in Chrome and Safari for us; on Windows, it does not seem to work in any browser we have checked. Systems and setups being as unique as snowflakes, we would definitely want the ability to force the setting on reinstated.

**Comment by CendioOssman** [comment]
I'm afraid there has been some misunderstanding. It was never possible to force it on. It was always qualified on the browser supporting it. So if you are seeing issue then there is some bug.

Neither IE nor Edge supports local cursors, but the other browsers should. Which others have you tested?

**Comment by samhed** [comment]
Yes, to fully clarify here, **local cursor support has NOT been removed**.

As @CendioOssman said, its always used now, if supported by the browser. The only thing that was removed was the setting for disabling local cursor.

Could you elaborate on what you are seeing? Are you getting any errors or warnings in the browser console?

**Comment by perhallstroem** [comment]
Thanks for your replies. It has been hard for me to reproduce the problem since I do not use Windows myself. To make matters worse, it seems to be intermittent. One of my colleagues thanked me today for fixing the problem – obviously nothing has changed... 

We tend to use Chrome a lot, and the problem has been observed there. Possibly only on some versions of Windows or in particular conditions. I am going to ask for console logs when/if this happens again, and will have to report back.

**Comment by perhallstroem** [comment]
So far, it seems to be essentially broken in Windows but work on Macs. We have tested four different randomly chosen laptops and one single desktop machine. We have also tested four different MacBooks. It works on the Macs and the Windows desktop every time and never on the Windows laptops. Perhaps it has something to do with the graphics card/acceleration? All Windows laptops run Windows 10.

There is nothing at all in the console, unfortunately.

**Comment by samhed** [comment]
What version of noVNC are you using? Is your version of noVNC modified? Which versions of the browsers are your users using?

If there is nothing at all in the console, that would indicate that local cursors are in fact used. The default log level is `warn` and that would print a log line in the browser console if local cursors aren't supported.

**Comment by perhallstroem** [comment]
Hi @samhed, we are using the current _master_ revision (we just `curl -sL https://github.com/novnc/noVNC/archive/master.tar.gz | tar xz`). The issue seems to exist in all recent versions of Chrome – whatever was the most recent version yesterday did not work on the laptop that we tested, and the same version was running on the desktop where things worked. It does not seem to be specific to a particular setup: I have had this reported from people on three continents with varying, but quite standard, setups of Windows 10 running latest Chrome. Always laptops!

**Comment by CendioOssman** [comment]
Hang on, are these touch screen laptops?

**Comment by dongakang** [comment]
we are using novnc version 1.0.0-testing.2, I encountered a similar problem. The local cursor disappears on the Firefox browser on the MacBook Pro. And that led to the disappearance of the cursor in the browser when we closed the novnc interface. I think local cursor style was removed，We temporarily modify the disable.js Lane
```
disableLocalCursor: function () {
        this._target.style.cursor = "default";
    }
```

**Comment by CendioOssman** [comment]
That doesn't sound like the same issue. Could you check that the problem remains on the current development version? If it does then report a new issue.

**Comment by perhallstroem** [comment]
Sorry @CendioOssman, let's just say that it is easy to drown in the flow of notifications from modern life...

No, they are not touch-screen laptops. For us, it can be reliably reproduced on all Windows laptops but not on a single Mac. I am working in a different location now where I am blessed with a total absence of Windows machines, so have not been able to test today. I am still getting user reports that sound the same, though.

**Comment by CendioOssman** [comment]
That's the only thing I can think of that would explain things. :/

Could you fire up the browser inspector and check what attributes the `<canvas>` element has once a session is up and running?

**Comment by perhallstroem** [comment]
Seems to work well for everyone at the moment. Have gone through how to find the canvas element etc, so now I am waiting for this to happen again – but hoping it never will!

**Comment by samhed** [comment]
Let's close it for now then. Feel free to reopen in the future

**Comment by dvader** [comment]
I am experiencing this issue too. The VNC server is running on a touch screen/tablet (HMI). It is running on Windows CE and it is running smartlab.at server. I am using noVNC 1.0.0. I tried Firefox and Chrome with the same results. The cursor shows up on the HMI but not in the browser. I tried RealVNC and the cursor shows up as a small black square.
Here is my canvas information:
<canvas style="margin: auto; outline: medium none currentcolor; flex-shrink: 0; width: 800px; height: 480px; cursor: none;" width="800" height="480" tabindex="-1"></canvas>

**Comment by dvader** [comment]
I have changed the following and it now shows up but I'm thinking there is a less hack-ish way to do this?
` disableLocalCursor: function () {
        this._target.style.cursor = "default";
    },`

**Comment by CendioOssman** [comment]
If you have a touch screen then I'm afraid you won't get a local cursor. We cannot determine if the browser will show the cursor or not when touch is enabled, so we have to assume the worst and disable that function.

**Comment by dvader** [comment]
Is there a way to make it a selectable option on the settings or be able to force it through the parameters on the URL?

**Comment by CendioOssman** [comment]
I'm afraid it's not possible to force it on. You might want to keep an eye on #572 as the solution for that issue might resolve things on touch devices as well.

**Comment by dvader** [comment]
Just to make sure we’re on the same page, my issue is not that I can’t display the cursor, it’s just that noVNC incorrectly identifies the cursor as none. When I force the cursor on (by changing the “disableLocalCursor” function to default), the cursor is displayed properly on both the HMI and the browser.

**Comment by CendioOssman** [comment]
Hang on, I misread your original comment. Your problem is that your VNC server lacks support for cursors in any form. We don't currently have any handling of such servers, and I don't believe we have any issue for such support either. What server are you using?

**Comment by dvader** [comment]
I'm using MobileVNC from smartlab.at on Windows CE ([http://www.smartlab.at/MobileVNC/]). The pointer is usually hidden but when VNC is running it is showing. Do you want me to open a separate issue for my VNC server?

**Comment by CendioOssman** [comment]
That would be best, yes, as you are seeing something entirely different.

**Comment by superstar3222** [comment]
Hi everyone.
I have the same problem.
I am connecting to a TigerVNC server using novnc_proxy (https://github.com/novnc/noVNC), but the user's local cursor shape changes on the page linked to the server.
