### ISSUE TITLE
issues with browserify

### ISSUE THREAD

**Issue by shrihari-b** [novnc/noVNC#977]
I tried the following:
Step 1.
```utils/use_require.js --as umd```
Step 2.
``` browserify lib/rfb.js -o dev_build/rfb.js```
Step 3.
used it in index.html as follows:
```<script src="<cdn link>/dev_build/rfb.js" ></script>```

All that I want to do is to:
1. Move transpiled rfb.js and webutils.js to CDN and fetch it from there. 

Issue:
I am getting RFB is not defined on console .Also I am not able to figure out what I am doing wrong. Please add an example so it could be easier.

**Comment by CendioOssman** [comment]
We now have new instructions for how to embed things. Please see the main README.
