### ISSUE TITLE
Double-clicking connect breaks the UI

### ISSUE THREAD

**Issue by samhed** [novnc/noVNC#978]
See screenshot:

![doubleclick-connect-breaks-ui](https://user-images.githubusercontent.com/4117162/33894115-6ea7166c-df5d-11e7-813b-cd92abe3eabf.png)

The connect button and logo displays in front of the remote session, and the side toolbar disappears. Does not seem like a new issue, I rolled back almost a year and saw the same behavior.

**Comment by CendioOssman** [comment]
Should be easy enough to fix. Just ignore more clicks if `UI.rfb` already exists.
