### ISSUE TITLE
How to setup TLS certificate with noVNC

### ISSUE THREAD

**Issue by samgoud** [novnc/noVNC#980]
Hi, 
I am using the default option from novnc while running utils/launch.sh script. 
The process I see is 
sambadda  5243 14748  0 Dec12   00:00:00 python /kanaka-noVNC-tigerVNC/utils/websockify/run --web /kanaka-noVNC-tigerVNC/utils/../ --cert /kanaka-noVNC-tigerVNC/utils/self.pem 6080 localhost:5965

My company prohibits use of SSL v3 and asked me to switch to TLS 1.2.

Can you please help me how to achieve this.

**Comment by CendioOssman** [comment]
Please don't open multiple issues for the same thing.
