### ISSUE TITLE
Can noVNC clipboard support Chinese text copy/paste?

### ISSUE THREAD

**Issue by FrankChenIt** [novnc/noVNC#981]
Hi, How can I make the noVNC clipboard support chinese?

When I type Chinese in the novnc clipboard and paste on the remote server, the text encode not correct.

**Comment by CendioOssman** [comment]
I'm afraid not. Standard VNC only implements support for ISO 8859-1 and noVNC hasn't implemented any extension for this. See #61 for improving things.
