### ISSUE TITLE
self.pem not found when using mod_proxy

### ISSUE THREAD

**Issue by aslmx** [novnc/noVNC#982]
hey there,

i'm new to noVNC. It works great itself. However, i'm running this at home and i have already an apache2 running, exposed to the public and configured (for me) properly with SSL/TLS Certs. 

I thought i'd simply add another virtual host and use mod_proxy to secure the http connection to a second host running noVNC.
This works great with my homeautomation appliance that i'm "securing" this way.

I have seen other hints in the issues and i can come as far as that noVNC login opens, however if i click the "connect" button, it says "Failed to connect to server".

A quick intro:
my webserver is on 192.168.2.30 and runs on several high non-standard ports.
My host running noVNC is 192.168.2.46

In the console (on 192.168.2.46) i get 
192.168.2.30: SSL connection but '/home/user/self.pem' not found

my site.conf is (as i have figured from other issues, websockets had to be added as well)

```
        ProxyPass / http://192.168.2.46:6080/
        ProxyPassReverse / http://192.168.2.46:6080/
        ProxyPass "/websockify" ws://192.168.2.46/websockify retry=3
        ProxyPassReverse "/websockify" ws://192.168.2.46/websockify retry=3
```

i had also tried with specifying a port for /websockify but it did not help.

Apparently i have no clue where i can find further logs or info to further debug this. Anyone has successfully done something like this and can share some insights? 

Again, to make sure it's understood: if i access noVNC on the host directly it works just fine. Would love to securely access it from outside my homenetwork though, without the need to constantly run an ssh tunnel.

Thanks for your help!

**Comment by CendioOssman** [comment]
First off, you'll need a port for the websockify lines as well. Otherwise it will use port 80.

Secondly, please verify your websocket host setting in the noVNC settings and make sure it has the Apache hostname configured. Either your browser is connecting directly to your websockify machine, or there is some weird behaviour in Apache.
