### ISSUE TITLE
view_only not working as query parameter

### ISSUE THREAD

**Issue by yeya** [novnc/noVNC#983]
I'm running the quick start ` ./utils/launch.sh --vnc` app
It works great!
I tried to play with the url query parameters:
view_only=true does mark the checkbox at the side panel, but the mouse is active until I go to the side panel -> uncheck -> recheck back again.
The full url:
`hostname:6080/vnc.html?host=hostname&port=6080&view_only=true&autoconnect=true&password=pass123`

**Comment by samhed** [comment]
Yes, it seems like we have a bug here. #985 should fix things for you

**Comment by samhed** [comment]
Fixed in 37c609359ab3606cba2b233611adce029a84ac01
