### ISSUE TITLE
Connecting to a "regular" server

### ISSUE THREAD

**Issue by computernewb** [novnc/noVNC#984]
This isn't an issue, but rather a question I had. I was wondering if it was possible to use noVNC to connect to a regular VNC server (that is, a VNC server not running websockify or anything, just a standard desktop running a TightVNC server). This would be really convenient for me.

Thank you!

**Comment by CendioOssman** [comment]
No, WebSockets were meant to explicitly not allow this for security reasons. Connecting from a browser will always require a WebSocket server in some form. Some VNC servers have support for that built in though.
