### ISSUE TITLE
Ubuntu package manager only supports v0.4, PPA?

### ISSUE THREAD

**Issue by LNFWebsite** [novnc/noVNC#988]
It seems that the package maintainer of noVNC for Ubuntu is no longer updating the package.

Even 17.10 is still only supporting v0.4 of noVNC https://packages.ubuntu.com/artful/novnc

I run [Kimchi](https://github.com/kimchi-project/kimchi) and have been running into issues with mouse vs touch events which I see has been fixed in the latest stable of noVNC.

Am I able to remove the old noVNC and install noVNC by the install procedure listed here without breaking dependencies or is there a PPA somewhere that I'm missing?

Thanks

**Comment by CendioOssman** [comment]
No, I'm afraid we're not aware of any PPA. :/
Perhaps we'll see some renewed attention when 1.0 is released.

**Comment by LNFWebsite** [comment]
Okay... I've cloned master and replaced the files within `/usr/share/novnc`. That seems to have fixed it for now...
