### ISSUE TITLE
noVNC retry on connection refused

### ISSUE THREAD

**Issue by sarcarx** [novnc/noVNC#994]
Using vnc_lite.html as a template. I am using noVNC to connect to servers that are powered on at the same time.
Sometimes the server is not fully started but noVNC tries to connect to it and get a connection refuse.
Is there a way of telling noVNC to keep trying to connect for a certain amount of time before giving up?

**Comment by CendioOssman** [comment]
No, we do not have any such function. I'm not so sure it makes sense as a general feature either. You could try adding your own WebSocket polling function before you try creating the `RFB` object?

**Comment by sarcarx** [comment]
I have managed to retry to reconnect when the disconnected event was raised 
```
    function disconnected(e) {
        document.getElementById('sendCtrlAltDelButton').disabled = true;
        updatePowerButtons();
        if (e.detail.clean) {
            status("Disconnected", "normal");
        } else {
            status("Trying to connect", "error");
            console.log("retrying"); // the server was not reachable yet
            setTimeout(function(){vnc_connect(url)}, 1000);
        }
    }

```
