### ISSUE TITLE
Some string(s) can not be translated

### ISSUE THREAD

**Issue by PeterDaveHello** [novnc/noVNC#997]
At least I found one, I'm not sure if there are more

 - `Send Password` / https://github.com/novnc/noVNC/blob/9b84f51685243309afb9ca4cefe1de697594705b/vnc.html#L303

**Comment by samhed** [comment]
Hm, good find! It looks like `po/xgettext-html` doesn't support input type submit:

https://github.com/novnc/noVNC/blob/master/po/xgettext-html#L72

It's probably just a matter of adding submit to that list on that line, but I don't have the time to test today. I'll try to take a look tomorrow.

**Comment by CendioOssman** [comment]
This is a bug in the HTML spec AFAICT:

https://html.spec.whatwg.org/#the-translate-attribute

@samhed, do you think you have time to report this to @whatwg?

You also need to update https://github.com/novnc/noVNC/blob/master/app/localization.js#L150 or the translations won't actually be applied.

**Comment by samhed** [comment]
> @samhed, do you think you have time to report this to @whatwg?

https://github.com/whatwg/html/issues/3396

> You also need to update https://github.com/novnc/noVNC/blob/master/app/localization.js#L150 or the translations won't actually be applied.

86b9c47
