### ISSUE TITLE
Cant Control Remote Server

### ISSUE THREAD

**Issue by zwick88** [novnc/noVNC#999]
Hi, 

i have the problem, that since a few days i cant control der VNC Servers GUI.

I am using Firefox v.54.0.4 And in Settings from noVNC i have enabled "Local Cursor" "Clip to Window" "Shared Mode".

If i connect to the Same Server by using Internet Explorer, i have no Problem. I think there is a new setting in the Firefox i have to change.

Do anyone know this issue?

Thanks a lot 

Alexander

**Comment by samhed** [comment]
Which version of noVNC are you using? Are you seeing any errors in the browser console?

**Comment by zwick88** [comment]
Hi, 

Sorry i was not at work the last days, 

This is from the Console

**Comment by zwick88** [comment]
Fehler beim Verarbeiten des Wertes für 'width'.  Deklaration ignoriert.
custom.html
 Msg: Starting VNC handshake
util.js:218:43
 Msg: Sent ProtocolVersion: 003.008
util.js:218:43
 Msg: Authenticating using scheme: 2
util.js:218:43
util.js:218:43
 Msg: Passwort OK
util.js:218:43
Server native red-shift is not 16
util.js:218:43
Server native blue-shift is not 0
util.js:218:43
Skipping tight as it is only supported with true color
util.js:218:43
 Msg: Verbunden

**Comment by zwick88** [comment]
The Version  is 0.6.1. 

But the it worked since round about a year

**Comment by zwick88** [comment]
No its working without problem
